### ISSUE TITLE
failing disk in noquiklos + failed raid battery

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#100]
Device: /dev/sg1 [cciss_disk_01] [SCSI], SMART Failure: DATA CHANNEL IMPENDING FAILURE DATA ERROR RATE TOO HIGH

Device info:
[HP       EH0146FARUB      HPD9], lu id: 0x500000e1178ab3f0, S/N: D301PB30BCSY1111, 146 GB

---

Battery/Capacitor Status: Failed (Replace Batteries)

The raid controller battery unit should be replaced with a HP Part Number 534562-B21 (1GB) or 534916-B21 (512MB) FBWC instead of replacing the battery.

**Comment by zerebubuth** [comment]
We replaced the failing disk, and added a spare.

**Comment by zerebubuth** [comment]
Replaced with FBWC.
