### ISSUE TITLE
blogs.osm.org not updating

### ISSUE THREAD

**Issue by samwilson** [openstreetmap/operations#1000]
First reported at gravitystorm/blogs.osm.org/issues/73 but moving here as more likely an operational issue.

The feeds at https://blogs.openstreetmap.org are not updating. https://blogs.openstreetmap.org/atom.xml is empty.

@tomhughes [reports](https://github.com/gravitystorm/blogs.osm.org/issues/73#issuecomment-1825018642) that the error is:

> ```
> *** error: no implicit conversion of nil into String
> 
> bundler: failed to load command: pluto (/home/tom/.bundle/ruby/3.2.0/bin/pluto)
> (erb):17:in `escapeHTML': no implicit conversion of nil into String (TypeError)
> 	from (erb):17:in `block in make_for'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-models-1.6.2/lib/pluto/models/utils.rb:38:in `block in each'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/activerecord-6.1.7.6/lib/active_record/relation/delegation.rb:88:in `each'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/activerecord-6.1.7.6/lib/active_record/relation/delegation.rb:88:in `each'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-models-1.6.2/lib/pluto/models/utils.rb:16:in `each'
> 	from (erb):13:in `make_for'
> 	from /usr/share/ruby/erb.rb:429:in `eval'
> 	from /usr/share/ruby/erb.rb:429:in `result'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/erb/template.rb:23:in `render'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/erb/templater.rb:45:in `block in merge_pak'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/manifest.rb:47:in `block in each'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/manifest.rb:47:in `each'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/manifest.rb:47:in `each'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/erb/templater.rb:25:in `merge_pak'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-merge-1.1.0/lib/pluto/merge/formatter.rb:79:in `make_for'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-merge-1.1.0/lib/pluto/merge/formatter.rb:35:in `run'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:290:in `block (3 levels) in <top (required)>'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:270:in `each'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:270:in `block (2 levels) in <top (required)>'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/gli-2.21.1/lib/gli/command_support.rb:131:in `execute'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/gli-2.21.1/lib/gli/app_support.rb:298:in `block in call_command'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/gli-2.21.1/lib/gli/app_support.rb:311:in `call_command'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/gli-2.21.1/lib/gli/app_support.rb:85:in `run'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:390:in `<top (required)>'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `block in require'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:299:in `load_dependency'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/lib/pluto.rb:24:in `main'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/bin/pluto:5:in `<top (required)>'
> 	from /home/tom/.bundle/ruby/3.2.0/bin/pluto:25:in `load'
> 	from /home/tom/.bundle/ruby/3.2.0/bin/pluto:25:in `<top (required)>'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
> 	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
> 	from /usr/local/bin/bundle:25:in `load'
> 	from /usr/local/bin/bundle:25:in `<main>'
> ```

**Comment by tomhughes** [comment]
The maptiler feed is broken and has no item URLs which breaks our templates which assume all items will have URLs.

I've disabled that feed for now.
