### ISSUE TITLE
consider flushing tile cache of specific area to remove outdated rendered data

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#1001]
Some areas, sadly quite large, are stuck with outdated rendering due to how tile expire cache works.

I know that https://github.com/openstreetmap/operations/issues/987 will solve it for new cases if enabled

I know that it will take relatively long time to refresh it, but it may be worth doing as otherwise invalid renderings may stay for relatively long. Maybe flush cache of the most populated western parts of the area, while keeping eastern parts with some rare invalid data?

Was discussed with @Firefishy - got directed here to keep things triaged and in issues

(hopefully I managed to keep balance between being too cryptic and giving a manual)

**Comment by tomhughes** [comment]
Which cache are you talking about? The render cache or the CDN cache?

**Comment by Firefishy** [comment]
I think we will wait until https://github.com/openstreetmap/operations/issues/987 is fully deployed before any cache invalidation.

**Comment by Firefishy** [comment]
> The render cache or the CDN cache?

It is primarily a render cache issue.

**Comment by tomhughes** [comment]
There is a new carto release (https://github.com/openstreetmap/chef/issues/639) that I will likely deploy next weekend which will have the side effect of marking everything dirty.

**Comment by Firefishy** [comment]
[With](https://github.com/openstreetmap/operations/issues/987) and  New carto release pushed. All old tile are now marked dirty and the issue shouldn't repeat.

**Comment by matkoniecz** [comment]
See https://github.com/openstreetmap/chef/commit/a7d7bb9186bcd1ce33483c4587b80c90bc03534b causes relations to trigger rerender per https://community.openstreetmap.org/t/topic/106281/5

I also updated https://wiki.openstreetmap.org/wiki/Browser_cache#Exceptions
