### ISSUE TITLE
OSM Editing api appears to be broken

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#1008]
Noticed first when trying to open https://www.openstreetmap.org/edit?editor=id&note=3789569#map=18/50.12089/19.85544 for editing

https://www.openstreetmap.org/node/3295399508 loads for very long time

https://prometheus.openstreetmap.org/d/ST-7bi5Gz/api-database?orgId=1&refresh=1m shows severe reduction in some graphs, looking like it is impacting everyone

looked at https://twitter.com/osm_tech

very likely known problem, but reporting just in case

![screen02](https://github.com/openstreetmap/operations/assets/899988/862e1017-04a2-4234-bc43-174673456a91)
note drop to nearly zero on right

**Comment by tomhughes** [comment]
Already being dealt eith.
