### ISSUE TITLE
[Account request]: 

### ISSUE THREAD

**Issue by mfrdmfrd** [openstreetmap/operations#1009]
### Name

Muhammad Farid

### Email address

mfarid@goliveict.com

### OpenStreetMap username

5th Settelment ,New Cairo

### Username on the server

Mfrd77

### Bio

```markdown
I am starting to make a project for developing a map client for route optimization.
```

### Public SSH key

AAAAB3NzaC1yc2EAAAADAQABAAACAQCg3+ihlfOtszAT88pdFrwvazPKzBKGsruYpzl2RTq55ofH6rjs2JK4HTv6nqQhfwvXPL8amAm/blzSeabk1VehbwyPEL1aGhxLjU1Jp9X1ZvJu3qMF+og2c7LVQWUw7DuxBcXOCsIdk/yQTIFfxll0Nq46iPxqw/o5f68pP+suqWwAoVjinbBU8vrD+S8bsaC63I+q0xq+/8DOOFUF5X6zlE14f2Mq88Rm9GGt9efhMddmz6GDwg8lsHSDTTIGpb9mW8lp2in1SzswvLUKYNOqWPl1cRJ5vm8gILDxtUyqRsGRYOGMwdI1sdCi8nVOB20Ixvz3WsSDBgrYzJzEtWFl8hVKmjGAMj3TU1Ixp3i1xnWMfpYV3qOulnVV26YeoYzcysX+ISPgGuRStppma4b9ziRZdj11/zFzS1YSvV/mAHeoUuw1gvbe6g7+zbjw6nTQJaHe4kcIlCURKgA84GrBknRNy/Ipy/18RPeApMBppFDDDC54evcy3lj74hpTFgr6SgoD2NAsNn22nQsWOgikV+cE7q7yztguTMEkXD2Hx7SYI27A0Kd+xbPzci/mdihknHs37Myae5kZ1aY1RFDUlkU3/qNLdVBqCm6raxcD5tqAmCyj31hl1SoFB3/X64StcJmYqMu4nT1RULcZQXlA+ySi5T430ME7QzPRgg75rQ==

### Code of Conduct

- [X] I agree to follow the OpenStreetMap policies and codes of conduct, and to use the dev server only for OpenStreetMap-related tasks

**Comment by Firefishy** [comment]
The dev server does not offer any special methods for app or routing development.
