### ISSUE TITLE
Third party authentication failed

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/operations#1010]
As of at least 6:38 PM (UTC), logging in with third party account (Facebook) loads slowly, then returns Authentication failed error.
Re-adding the website and clearing cache does not help. Website is listed as active in third party settings before and after re-adding.
Is this an issue with osm.org, cookie, or third party?
Meta/OSM reports no issues for almost two hours now. I have not made any changes anywhere which could cause this afaik.

**Comment by tomhughes** [comment]
It's probably because I put a broad block on facebook IPs on the production web servers as they were scraping the API from a large number of addresses.

**Comment by tomhughes** [comment]
Having said that logging in with FB shouldn't involve any requests from FB to our web servers as it all goes via the client.

**Comment by tomhughes** [comment]
I've narrowed the block now which seems to have fixed things.

**Comment by danieldegroot2** [comment]
Thanks.
