### ISSUE TITLE
cgimap recipe for dev: switch to cmake

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#1018]
CGImap has moved to cmake yesterday, i.e. the old autotools based build steps in https://github.com/openstreetmap/chef/blob/8e86bcdcde5541c466540d6a9f908b17fc9c4884/cookbooks/dev/recipes/default.rb#L449-L465 no longer work.

Instead of running autogen.sh and configure, it should be sufficient to create a new `build` directory in the repo's main directory, and then run `cmake ..` from there. `make -j ` should then work as usual, assuming `cmake ..` didn't report any issues.

Hopefully, no extra parameters like "--with-fcgi=/usr --with-boost-libdir=/usr/lib/x86_64-linux-gnu --enable-yajl" are needed anymore. YAJL is enabled by default, and cmake should be able to figure out on its own where fcgi and boost libraries are located.

Thanks for looking into this!

**Comment by tomhughes** [comment]
Fixed inhttps://github.com/openstreetmap/chef/commit/730fadf59e0fc862128e7091f8cefa530fa2c6f0.

**Comment by mmd-osm** [comment]
I committed this change https://github.com/zerebubuth/openstreetmap-cgimap/commit/81e6a3a2a668990f70c7756e12742202e89270f5 to include the current build timestamp in the generator string (e.g. "CGImap 0.8.10.2401091705 ..."). The idea was to see more easily when changes made it to faffy without manually bumping the version number every time.

On faffy I still see the previous "0.8.10" in the generator string w/o the build timestamp: https://master.apis.dev.openstreetmap.org/api/0.6/node/4317965188 . 

I can't really figure out if the build is failing for some reason, or if there's some other issue with the new cmake set up.

**Comment by tomhughes** [comment]
It had rebuilt, just not restarted. Fixed in https://github.com/openstreetmap/chef/commit/844fb4d99d4e99ccf8a87d49ceb6b7ae28a67702.

**Comment by mmd-osm** [comment]
Thanks a lot for the quick fix, looking good now!
