### ISSUE TITLE
CiviCRM 4.6.14 security update

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/operations#102]
When logging in to CiviCRM (at join.osmfoundation.org) it displays a little pink notice on the bottom of the page: "Powered by CiviCRM 4.6.14. Security update required." - Perhaps someone could take a look to see if this applies to us?

**Comment by tomhughes** [comment]
@toffehoff usually lets me know what upgrades he wants done...

**Comment by tomhughes** [comment]
As this is now public I have updated to 4.6.20 for now which is the latest 4.6 release and hopefully wont break anything - please let me know if any of the plugins need updating to work with that @toffehoff.

**Comment by pnorman** [comment]
I notified the MWG.
