### ISSUE TITLE
Review Facebook login details

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/operations#1020]
As of yesterday, Facebook login returns

> Feature Unavailable
> Facebook Login is currently unavailable for this app, since we are updating additional details for this app. Please try again later.

May be due to any of the following (found in account [page](https://developers.facebook.com/apps))
- app auth is disabled (unlikely)
- missing setup steps (may have changed)
- up-to-date/valid privacy policy needs to be (re-)supplied
- permissions (advanced access) for email and/or public_profile need to be (re-)requested
- requiring business account login verification for such requests (since May 2023)
- pending data use checkup (app will be highlighted in red)
- password needs to be reset (also fairly unlikely)

See also notices on [Login permissions](https://developers.facebook.com/docs/permissions#login_permissions) page.

**Comment by tomhughes** [comment]
Yes facebook have refused to register the OpenStreetMap Foundation in line with their new security rules so we are no longer able to access login with Facebook and we are going to have to disable it.

**Comment by tomhughes** [comment]
Specifically as of 8th January they require Facebook applications that are used for logging in to be connected to a verified Meta Business Account but while we have been able to link the application to a Business Account we have been trying for months to get them to verify the account and they just keep rejecting our paperwork with no explanation and attempts to reach out to contacts inside Facebook to get this resolved have gone nowhere.

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/31e786d715dbb4599a129f5e3bbfdda7c1c54cbb for some value of fixed.

**Comment by danieldegroot2** [comment]
Okay. I would suggest communicating this change to users via official publicity channels, indicating
- what happened
- if there are any plans to continue work on this issue
- whether any data is lost
- can be retrieved
- etc.

if not already being considered.

Sidenote: I assume this change (disabling Facebook login) has been approved internally.

**Comment by Firefishy** [comment]
I have put out an initial message:
* https://en.osm.town/@osm_tech/111732296234508046
* https://twitter.com/OSM_Tech/status/1745101129896133113

OSM's communication working group might put out something more formal later.

**Comment by danieldegroot2** [comment]
Thanks. The workaround is working for now.
