### ISSUE TITLE
[Account request]: i want to delete my notes.. one of my notes on the web is wrong.. injust put it today

### ISSUE THREAD

**Issue by BudiPurnomoGitHub** [openstreetmap/operations#1021]
### Name

Budi

### Email address

budipurnomomail@gmail.com

### OpenStreetMap username

Budi Purnomo

### Username on the server

Budi Purnomo

### Bio

```markdown
[Account request]: i want to delete my notes.. one of my notes on the web is wrong.. injust put it today
```

### Public SSH key

[Account request]: i want to delete my notes.. one of my notes on the web is wrong.. injust put it today

### Code of Conduct

- [x] I agree to follow the OpenStreetMap policies and codes of conduct, and to use the dev server only for OpenStreetMap-related tasks

**Comment by Firefishy** [comment]
This is not a dev server user account creation request. Please contact the Data Working Group is there is a data issue.
