### ISSUE TITLE
[Account request]: 

### ISSUE THREAD

**Issue by YellowCrimes** [openstreetmap/operations#1022]
### Name

Vigo

### Email address

odingtaulani@gmail.com

### OpenStreetMap username

VRainmaker

### Username on the server

VRainmaker

### Bio

```markdown
I am a cyber security
```

### Public SSH key

authentication:none=yes

### Code of Conduct

- [X] I agree to follow the OpenStreetMap policies and codes of conduct, and to use the dev server only for OpenStreetMap-related tasks

**Comment by tomhughes** [comment]
What is your planned use for a dev server account?

**Comment by Firefishy** [comment]
Sorry, we cannot yet offer you an account on the dev linux server. Please try again when you have been active for a longer period in OpenStreetMap.

**Comment by YellowCrimes** [comment]
For sync osm to my business in instagram. I want you to help me sync my
business to new address on instagram and tiktok. I have trouble in this
momment, my costumer have a lot trouble because a past address. Please fix
this, i need your help.
Link new address business : https://www.openstreetmap.org/way/857276120

Pada tanggal Sen, 22 Jan 2024 17.05, Tom Hughes ***@***.***>
menulis:

**Comment by tomhughes** [comment]
You do not need a shell account on the dev server to make changes to the map!

**Comment by YellowCrimes** [comment]
I am apologize for all. I want you help me to sync my new address to
instagram and tiktok. I am so sorry for all because me not fully understand
in osm.

Pada tanggal Sen, 22 Jan 2024 18.09, Tom Hughes ***@***.***>
menulis:
