### ISSUE TITLE
Decommission tabaluga (or use for spares, or fix)

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#1024]
We've abandoned tabaluga (#834)

- [x] Remove Chef config
- [ ] Wipe Disks (already done?)
- [x] Remove DNS
- [ ] De-rack
- [ ] Disposed

Alternatively, the motherboard (~60€) can be changed, or the machine (~€300-500) can be replaced to use the remaining hardware in it.

**Comment by Firefishy** [comment]
Part number: 843307-001

**Comment by Firefishy** [comment]
I have bought a replacement motherboard for £41.39 and will attempt to repair the system on the upcoming AM6 visit.
