### ISSUE TITLE
Deprecated grafana plugin

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#1029]
The Discourse dashboard has a warning about the graph plugin being outdated

<img width="306" alt="image" src="https://github.com/openstreetmap/operations/assets/1190866/f089de96-2092-4b86-aaaf-938f25922aaf">

This should be a fairly easy fix, but I didn't want to start it this late at night.

**Comment by tomhughes** [comment]
I've been gradually upgrading those as I run into them.

**Comment by tomhughes** [comment]
Fixed the discourse one.
