### ISSUE TITLE
OSMF-membership@openstreetmap.org mailing list administration

### ISSUE THREAD

**Issue by datendelphin** [openstreetmap/operations#1032]
Since a few week, mwg is getting the daily pending moderator requests mail. But we don't have the password for that list. And I don't think that list is still in use.

Could we either get the password to clear out all the old spam on the queue to silence it, or get removed from the owners of that list?

**Comment by tomhughes** [comment]
Well if it's not in use then we should shut it down - how do we find out if it's in use?

Somebody from MWG used to keep it in sync with CiviCRM somehow I believe so presumably somebody had a password? Not sure if that was automated or manual though?

**Comment by tomhughes** [comment]
Or am I confusing it with osmf-talk? What's the difference?

**Comment by datendelphin** [comment]
Yes I think you are confusing it with osmf-talk. osmf-talk is now opt-in, so we just confirm the subscriptors are members, but don't subscribe all members automatically. We do have the password for osmf-talk.

I have no idea about osmf-membership, I am pretty sure it is not used. We mail members through civicrm directly, without a mailinglist. Shut it down for all I know.

**Comment by datendelphin** [comment]
This is still an issue. We are still getting those mails. We have no idea what to do about it, as we only get the mails, but not the password.
It is annoying.

**Comment by tomhughes** [comment]
Well if MWG want it shutdown we can do that.

**Comment by dorotheakazazi** [comment]
@datendelphin Dave Corley was made the administrator of that list in 2014. If there was no change, he might still have the password. I can send his OSM username and one of his email addresses via another channel, if you want to contact him. Just let me know.

**Comment by pnorman** [comment]
I'm sure we can reset the admin info, but we should check if the MWG wants it shut down first.

**Comment by datendelphin** [comment]
Thank you :) I'm not long enough with the MWG to know what that list was intended for. Paul and Tom probably know more about it.

I'll be so bold to say yes, we want it shut down. We didn't even know it exists before the mails started coming in. The archive shows no mails since 2018. Judging the content of the mails, it seems similar in purpose to the osmf-talk list. The listinfo page even says "This list is no longer used"

**Comment by tomhughes** [comment]
List has been removed. Archives remain at https://lists.openstreetmap.org/pipermail/osmf-membership/.

**Comment by datendelphin** [comment]
Thank you :) the mails have stopped
