### ISSUE TITLE
Block *.yandex.net imagery

### ISSUE THREAD

**Issue by deevroman** [openstreetmap/operations#1033]
### Problem

Yandex Maps satellite images are not allowed to be used in OSM

### Description

Example of use:

https://www.openstreetmap.org/changeset/147580817

The domain on which they are located is:
`https://core-sat.maps.yandex.net/tiles?.....`

In addition, Yandex has the Tiles API, which should also be blocked:

https://yandex.ru/dev/tiles/doc/ru/quickstart

`https://tiles.api-maps.yandex.ru/....`

**Comment by tomhughes** [comment]
Requests to change the imagery blacklist need to come from DWG as described in https://github.com/openstreetmap/chef/pull/623.

**Comment by grischard** [comment]
In the DWG chat, one comment was that if there's a block, it should be on *.[maps.yandex.net](http://maps.yandex.net/) because they have file hosting, image hosting etc. on that domain that has nothing to do with their maps.

**Comment by AntonKhorev** [comment]
When using yandex.ru/maps/

https://core-sat.maps.yandex.net/ = aerial imagery
https://core-renderer-tiles.maps.yandex.net/ = map tiles
other kind of tiles are also under maps.yandex.net

**Comment by talllguy** [comment]
It does not appear that yandex is in the imagery index, though [it was proposed once here](https://github.com/osmlab/editor-layer-index/issues/459).

**Comment by pnorman** [comment]
> In the DWG chat, one comment was that if there's a block, it should be on *.[maps.yandex.net](http://maps.yandex.net/) because they have file hosting, image hosting etc. on that domain that has nothing to do with their maps.

Has the DWG decided to request a change to the blacklist?

**Comment by grischard** [comment]
Green light from dwg.

**Comment by tomhughes** [comment]
I thought @AntonKhorev said all the actual map tiles were under the maps.yandex.net domain?

**Comment by tomhughes** [comment]
Actually maybe I misunderstood what he was saying... Blocked both in https://github.com/openstreetmap/chef/commit/92d4fd1e5f12a09f6937872834cc048b91e3e7fc.

**Comment by AntonKhorev** [comment]
maps.yandex.net has all tiles as used by the official yandex map app

api-maps.yandex.ru has tiles that anyone with an api key can use
