### ISSUE TITLE
Sort out Fastly root access

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#1034]
Neither @tomhughes nor myself have Fastly root access, so we can't set up new distributions. We should have access.

Maybe @Firefishy or @iandees has access? If no one knows, I'll ask Fastly.

**Comment by Firefishy** [comment]
I have access. Let me know basic creation details and I can create. May take a few days. I will also look into granting another admin at the same time

**Comment by pnorman** [comment]
I've created the distribution but can't set up the SSL, DNS, and other properties. Also access to see them is inconsistent, since Tom can't see either the test tile or vector tile distributions.

**Comment by Firefishy** [comment]
Access now fixed for both users.

**Comment by pnorman** [comment]
Confirmed working.
