### ISSUE TITLE
Decommission gorwen

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#1039]
Decommission gorwen at Dublin.

- [x] Remove Chef config
- [x] Wipe Disks
- [x] Remove DNS
- [ ] De-rack
- [ ] Disposed

**Comment by grischard** [comment]
Isn't gorwen in DB4?

**Comment by tomhughes** [comment]
Sorry, bad copy and paste... Fixed now.

**Comment by Firefishy** [comment]
Hard disk wipe has been started. First time using `HPE Intelligent Provisioning` for the erase.

**Comment by Firefishy** [comment]
Server has become an emergency replacement after jakelong failed unexpectedly.
gorwen is now hosting community.openstreetmap.org.

Original wiped disks from gorwen have been moved to rack shelf.
