### ISSUE TITLE
[Account request]: Openfietsmap

### ISSUE THREAD

**Issue by ligfietser** [openstreetmap/operations#1044]
### Name

Minko

### Email address

wizardofoh.nl at gmail

### OpenStreetMap username

ligfietser

### Username on the server

openfietsmap

### Bio

I'm looking for server space to store the Openfietsmap (bicycle maps for garmin devices) based on OSM data. You have contacted me a few years ago that it was possible, so I hope it is still an option.

### Public SSH key

i have no clue

### Code of Conduct

- [X] I agree to follow the OpenStreetMap policies and codes of conduct, and to use the dev server only for OpenStreetMap-related tasks

**Comment by grischard** [comment]
Your connection to the server will be over ssh, so we need a public key for you. Which operating system do you use, and are you familiar with linux, which we use on the dev server?

**Comment by ligfietser** [comment]
I'm working on a Windows PC, and I'm not familiar with Linux sorry.
Don't have a key too. Maybe I'll ask someone else within the community first to set things up for me?

________________________________
Van: Guillaume Rischard ***@***.***>
Verzonden: vrijdag 15 maart 2024 04:58
Aan: openstreetmap/operations ***@***.***>
CC: ligfietser ***@***.***>; Author ***@***.***>
Onderwerp: Re: [openstreetmap/operations] [Account request]: Openfietsmap (Issue #1044)


Your connection to the server will be over ssh, so we need a public key for you. Which operating system do you use, and are you familiar with linux, which we use on the dev server?

**Comment by grischard** [comment]
Here's how to set up a key on Windows: https://system.cs.kuleuven.be/cs/system/security/ssh/setupkeys/putty-with-key.html

Yes, it would be best if someone in the community could show you the ropes of how to get your scripts to run on a Linux system.

**Comment by ligfietser** [comment]
Thanks Guillaume, I'll look into it
________________________________
Van: Guillaume Rischard ***@***.***>
Verzonden: vrijdag 15 maart 2024 05:18
Aan: openstreetmap/operations ***@***.***>
CC: ligfietser ***@***.***>; Author ***@***.***>
Onderwerp: Re: [openstreetmap/operations] [Account request]: Openfietsmap (Issue #1044)


Here's how to set up a key on Windows: https://system.cs.kuleuven.be/cs/system/security/ssh/setupkeys/putty-with-key.html

Yes, it would be best if someone in the community could show you the ropes of how to get your scripts to run on a Linux system.

**Comment by ligfietser** [comment]
OK I have created a key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUvwO82HzjNPpeNYZ2kZrl/riepA0n2sjqQGCHWSZ44Y8ch9NFVHu0KigrrKaUnzkjAv/c0nwgxUwr8d54Qq/M36SyBehmZEgVS45MK5AwoQaGEP9dPt7sCGxLLZI9RUTu8DQh1/IS7u5/2lJsyOzCQ9xiirNPz04U9pII3aQzH3gYOlsZPVY2SJKMIe3PdkqdPaazKUTduYH6CYOyK8P79uYXdh8BKhrEUD0wW0dOSm+aGqbBBppcQynYNdz3nwhTtDdvPQ6nGV73REekx8gRc1mTa3oxe5Job3CbMnxA5ZYwGQRk0MrW4jVM7fDLJqSwPzb5j/HlGMSYhoI6sWVZ rsa-key-20240315

**Comment by ligfietser** [comment]
Please go ahead, I have now some linux support

**Comment by ligfietser** [comment]
@Firefishy @grischard Any idea how long this will take?

**Comment by Firefishy** [comment]
`ligfietser` user has now been created on `dev.openstreetmap.org`. You should be able to login using your ssh key.
The directory`/home/ligfietser/public_html/` is web accessible via  https://ligfietser.dev.openstreetmap.org/ (certificate will be automatically issues in next ~ 2 hours).

**Comment by ligfietser** [comment]
@Firefishy unfortunately I have lost my passphrase, so I can't login.  Can I create and send a new key?

**Comment by ligfietser** [comment]
Here is a new key, hope you can reset the old one 

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYd3z5L8YQXRw3JHXwD0KyTdfWncom7UPAP3BcrfUK/oJXFAE6w4w4nsYHk4axRddIKLXYXl5guine/hd7uBk77mqVYSi4JpCDhYt8cIvAd6xHOmWEQwU3Yjvov3XcKOz304sD93pcynBXwpUxih4k3UifgUJz7Ire0f99FaOQ5+yI6qVMEcOReNGgtR3k7vbZXJhzNanKaZoUVeA/PAZx+Zv9cOXvmfgsYSmU6Thrf78dMBH+4GkXSodXC5iliQTepWFQxQ0hHSxndP3UkxVLQdi426jsceG4bXjkmh+cv3q6ue3e/hAU5BZmAzyT/NOGrC92FYlqTYfqNKv+RqVZ rsa-key-20240327

**Comment by Firefishy** [comment]
> Here is a new key, hope you can reset the old one
> 

Will update in the next hour.

**Comment by ligfietser** [comment]
Thanks guys, seems to work fine now!

**Comment by tomhughes** [comment]
Can they not mirror from http? I don't really want to be giving ssh access even under a separate account ..

**Comment by ligfietser** [comment]
Thanks Tom, I'll ask.
