### ISSUE TITLE
create clone of osm blog for dev/staging

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/operations#1047]
need ability to test plugins and themes before making production changes.

**Comment by tomhughes** [comment]
Well it's not a clone if it has different plugins and themes ;-)

More seriously while we can easily deploy a clean install under a different name it's not very easy to then experiment with plugins and themes as those are managed through chef.

**Comment by mikelmaron** [comment]
@tomhughes what's your recommendation for the best way to set up a development version of the blog? we do need to experiment with plugins and themese.

**Comment by Firefishy** [comment]
I have added https://staging.blog.openstreetmap.org/
Do I need to import the old content?

**Comment by Firefishy** [comment]
I will need to backport data.

**Comment by Firefishy** [comment]
Site is up and @mikelmaron has access. Chef disabled from updating the site during development. @mikelmaron will make notes on any changes made so that the changes can be rolled into blog.osm.org as required.
