### ISSUE TITLE
Static iD assets caching

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#1049]
While testing brotli on faffy in iD editor, I've noticed that some of the iD asset files are being repeatedly downloaded. I've also tested the same on production with Chrome and Firefox. A bit of panning triggered the following requests:

![image](https://github.com/openstreetmap/operations/assets/5842757/980c8b58-3d57-4a5e-ad71-f800005cbf32)

My expectation would be that these files are served from the browser cache instead. Of course, there's also the question why iD keeps requesting these files in the first place...

**Comment by tomhughes** [comment]
I'm not sure what you expect us to do about this? Do you want us to drop by and fix your browser or something?

**Comment by mmd-osm** [comment]
Ah, you're right, I tried now with a third browser (Chromium), and caching is working as expected, so it's definitely browser related. Closing here. Thanks!
