### ISSUE TITLE
Generate rendering query data for style optimizations

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#105]
The OpenStreetMap Carto developers haven't looked at optimizing the queries for over a year and there's probably new low-hanging optimization fruit. This is for two reasons

1. Generating the query and query length information is a big pain without a production server. It's possible, but takes me multiple days to arrange.

2. Going from logs to understanding what needs to be changed is difficult. This is outside the scope of ops.

Rather than try to set up a rendering server representing production and throw a load at it, I'd rather have samples of the queries running on production. This avoids the slowdown of statement logging which has to write to the logfile on each SQL statement.

Could this be run on vial? It will take about an hour and impose minimal load since it's just checking `pg_stat_activity`

```sh
for i in `seq 1 163`; do 
psql -AtqX -d postgres -c "COPY (SELECT pid, NOW(), NOW()-query_start AS query_duration, query FROM pg_stat_activity WHERE datname = 'gis' AND pid != pg_backend_pid() AND state != 'idle') TO STDOUT;" >> query_log.txt;
sleep 22;
done
```

22 is chosen to not divide by 5 minutes or 1 minute as I don't want it to happen to align with every munin run or diff update.

**Comment by tomhughes** [comment]
Here you go: [query_log.txt](https://github.com/openstreetmap/operations/files/440716/query_log.txt)

**Comment by pnorman** [comment]
Thanks. There's a total of 340 render queries and 24 osm2pgsql queries, for an average of 2 render queries running at the same time. It feels like vial's rendering capacity is underutilized. This is *wonderful* to see.

**Comment by tomhughes** [comment]
Well it wasn't running flat out when I did that sure.

**Comment by StyXman** [comment]
Is it me or this only shows the time spent _so far_ on each query?

**Comment by pnorman** [comment]
> Is it me or this only shows the time spent so far on each query? This, I think, gives no information about how much is going to take, it's just a lower bound, so I'm not sure how useful it is.

It gives statistical information about the time the queries will take. For a rigorous analysis you can treat it like the [German tank problem](https://en.wikipedia.org/wiki/German_tank_problem), but that's not needed since the purpose is to identify likely areas for optimization

> Also, queries are truncated, so unless you read one by one and compare, you can't really tell if there are two very similar (for instance, road fill vs road casing). Lastly, there's no info which ZL issued the query.

The log provided worked, even with the 1k query limit.

> What I have done for my own style is the following:
> 
> Compile my own version of mapnik, while reverting this commit.
> Render a handful of (meta)tiles, making sure that they're not empty sea tiles, and collecting the output.
> I understand if you're reluctant to install your own mapnik lib. On the other hand, I could try to run that for the current osm-carto release and provide the numbers that come up in my setup.

I'm happy with the data I got from production. Replicating the workload and performance characteristics of a production server is difficult, which is why I went this route instead of benchmarking on my server.
