### ISSUE TITLE
Decommission draco

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#1052]
Decommission draco at UCL.

- [x] Remove Chef config
- [x] Wipe Disks
- [x] Remove DNS
- [x] De-rack
- [x] Disposed

**Comment by Firefishy** [comment]
Disk wipe started on draco.

**Comment by Firefishy** [comment]
Wipe completed and server powered down.

**Comment by Firefishy** [comment]
https://web.archive.org/web/20240313130059/hardware.openstreetmap.org/servers/draco.openstreetmap.org/

**Comment by grischard** [comment]
Blocked by #1060

**Comment by Firefishy** [comment]
Server has gone for WEEE recycling and is waiting to be collected.
