### ISSUE TITLE
OSMF Email Forwarder List-id

### ISSUE THREAD

**Issue by T-o-m-H-u** [openstreetmap/operations#1053]
The previous mail-forwarders added List-ID’s to individual emails. Would it be possible to add that functionality to the current forwarders?

**Comment by Firefishy** [comment]
Unlikely. We are reliant on what features mailbox.org offer and I am not aware of any option which would enable this (Setting UI and Settings UI).

What is the requirement for this header?

**Comment by T-o-m-H-u** [comment]
Very convenient to filter by
`fileinto :create "${1}";`
