### ISSUE TITLE
Hurricane Electric Maintenance @ Amsterdam

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#1059]
> Hello,
> 
> You are receiving this email because there will be work performed in Equinix AM7, Amsterdam, which may affect your service(s) with Hurricane Electric as specified below:
> 
> Window Start Time: Friday, April 26, 2024 03:00 (UTC+0200)
> Window End Time: Friday, April 26, 2024 07:00 (UTC+0200)
> Expected Impact: < 2 hours
> Reason: Router and switch software updates to enhance security and stability
> Associated circuit(s):
>  - 184.104.202.69/30
>  - 2001:470:1:fa2::1/126

**Comment by Firefishy** [comment]
Announced:
https://twitter.com/OSM_Tech/status/1781571775165280693
https://en.osm.town/@osm_tech/112302149576978841
https://lists.openstreetmap.org/pipermail/announce/2024-April/000117.html

**Comment by Firefishy** [comment]
Maintenance done. Outage of around 22 minutes.
