### ISSUE TITLE
Apply for AWS Open Source 2024/2025 credits

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1061]
Submit the required application form for the AWS 2024 / 2025 Open Source Credits.
Deadline April 2024.

**Comment by Firefishy** [comment]
Application has been submitted and confirmed received. It will be reviewed shortly.

**Comment by Firefishy** [comment]
Blocked until confirmed.

**Comment by pnorman** [comment]
I believe we got credits, but not quite as many as we asked for?

**Comment by Firefishy** [comment]
Yes, we have been granted the same amount of credits as the previous year, and they will only be added to our account on Sept 1st, 2024.
