### ISSUE TITLE
Faffy account request

### ISSUE THREAD

**Issue by altilunium** [openstreetmap/operations#1062]
### Name

rtnf

### Email address

rtnf141@gmail.com

### OpenStreetMap username

rtnf

### Username on the server

rtnf

### Bio

```markdown
to create a static version of the old help.openstreetmap.org site
```

### Public SSH key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZmRTAN92TeqR9iIFsPFGmNdC7fGoH112eoY3D4JskfnezgdF+knA5qRf62VGnoa3oHfDZKGNaMexLZmyFLycyqFUln+TjzUpBLO3Ni7GykmIoxpTvzbs7iCtY9YChUUHz4qq7LP9W7QBRYYhgGMfa8IZUqTE3ogAG8uyKl+jn20PyVkkQabwePfCEm6WhcqKWA86u6R7SuE3O4YJsXIq9uaUZJVBomg

### Code of Conduct

- [X] I agree to follow the OpenStreetMap policies and codes of conduct, and to use the dev server only for OpenStreetMap-related tasks

**Comment by Firefishy** [comment]
Created `rtnf@dev.openstreetmap.org` you should be able to ssh in using your ssh private key.

**Comment by altilunium** [comment]
![image](https://github.com/openstreetmap/operations/assets/70379302/99e16c7e-2418-4ada-9736-46b71c94ebab)

**Comment by Firefishy** [comment]
@altilunium The ssh public key you supplied is incomplete / truncated. Please include the full string.

**Comment by Firefishy** [comment]
You can create a PR to update it yourself: https://github.com/openstreetmap/chef/blob/master/cookbooks/accounts/files/default/rtnf/.ssh/authorized_keys

**Comment by altilunium** [comment]
Yes, it is actually [truncated](https://github.com/openstreetmap/chef/pull/662/commits/ee0a0b3131d8f29af8451e9ac39a47bef1aab064). 
Thank you for the answer.
