### ISSUE TITLE
Private GitLab for LCCWG Chapter Applications

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#1063]
LCCWG is requesting:

1) A "local chapters applications" private repo on the foundation gitlab, so that details/discussions around Local Chapters applications can be held somewhere both private and owned by the OSM Foundation.
2) The moving of the tickets listed here into the new repo https://osmfoundation.org/wiki/Local_Chapters/Applications aka 193, 359-262.

The gitlab user accounts that would like access are the same as https://gitlab.com/osmfoundation/lccwg/-/project_members

Adam Hoyle (@atomoil) has offered to help: "I can create the repo and move the tickets and add people myself, and then you can remove the permissions"

**Comment by Firefishy** [comment]
OK done. Surprised I even had access, I don't normally manage gitlab.

1. https://gitlab.com/osmfoundation/lccwg/ renamed project to `lccwg-issues`.
2. Created `lccwg` group: https://gitlab.com/osmfoundation/lccwg
3. Created private project: https://gitlab.com/osmfoundation/lccwg/lccwg-private-issues
4. Moved `lccwg-issues` to https://gitlab.com/osmfoundation/lccwg/lccwg-private-issues
5. Invited all project member to new group: https://gitlab.com/groups/osmfoundation/lccwg/-/group_members
6. Removed all direct members from old group: https://gitlab.com/osmfoundation/lccwg/lccwg-issues/-/project_members
7. Moved ticket 193, 359, 360, 361 & 362 to `lccwg-private-issues` project.
