### ISSUE TITLE
create wordpress site for 20th birthday

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/operations#1070]
CWG is building a standalone site for OSM's 20th birthday. The designer we are hiring to build it works in WordPress. We need a fresh WordPress instance to develop this, with access to install themes and plugins.

**Comment by Firefishy** [comment]
Done.

https://birthday20.openstreetmap.org/ is now up for development. As per other development site please administer plugins / themes / users using wp-cli

eg:
```
/opt/wp-cli/wp --path=/srv/birthday20.openstreetmap.org/wp/ user list
```

The chef role for updating the site has been disabled during dev, which means chef will not make any changes to the site itself. The site is backed up daily. Certificates will NOT be updated while chef is not managing the site.

**Comment by Firefishy** [comment]
Another tip: wordpress installed files should be owned by `wordpress` user. To accomplish this using wp-cli you may need to use sudo eg:
```
sudo -u wordpress /opt/wp-cli/wp --path=/srv/birthday20.openstreetmap.org/wp/ *some-command*
```
