### ISSUE TITLE
Create private sotm social media mailinglist

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1074]
Requested...

_Could you please create the mailinglist sotm-comm AT osm-default-domain.org and make it private. Only members can read. And everybody is allowed to write to that list._

**Comment by tomhughes** [comment]
What is "osm-default-domain" exactly? Is this a mailman list they are asking for?

**Comment by Firefishy** [comment]
yes, sorry I didn't want to put openstreetmap.org because it will immediately be picked up by email address scrapers ;-)

**Comment by tomhughes** [comment]
I mean normally https://wiki.openstreetmap.org/wiki/Mailing_lists#Requests_for_new_lists is the correct way to request but it might be better for me to do it if they have special requirements.

I'm kind of reluctant to be creating new ones at this point really...

**Comment by tomhughes** [comment]
Created.
