### ISSUE TITLE
In welcome email for new members link to mastodon instead of twitter

### ISSUE THREAD

**Issue by md42** [openstreetmap/operations#1078]
The "Welcome to the OpenStreetMap Foundation!" email links to https://twitter.com/OpenStreetMap were the last post is from 2021. I suggest to link to https://en.osm.town/@openstreetmap instead which frequently in use :)

[
<img width="1205" alt="Screenshot 2024-05-14 at 07 29 52" src="https://github.com/openstreetmap/operations/assets/857448/9e5cb81a-c38d-4f3c-a8c0-781833e3fc5d">
](url)

**Comment by pnorman** [comment]
This would be an issue for the Membership Working Group, not operations. 

> the last post is from 2021.

No it isn't. The last post is within a day.

**Comment by iandees** [comment]
> The last post is within a day.

That's not what they show:

<img width="1263" alt="image" src="https://github.com/openstreetmap/operations/assets/261584/9b78c261-a536-4c24-8a52-99268f051e1c">

**Comment by Firefishy** [comment]
> > The last post is within a day.
> 
> That's not what they show:
> 

Just tested logged out of twitter and I can confirm it shows ancient posts. :-(

**Comment by md42** [comment]
thanks @pnorman i wrote the email. Have a good day :)
<img width="1069" alt="image" src="https://github.com/openstreetmap/operations/assets/125574078/769ef94a-4cee-4b5f-a358-ec14bb1b4f6c">

**Comment by grischard** [comment]
I've passed this to CWG.
