### ISSUE TITLE
Replace fans in yevaud

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#108]
3 fans have failed (according to sensors) in yevaud.

**Comment by zerebubuth** [comment]
I have contacted [the supplier, now known as Zeta Systems](http://www.zeta.systems/) for tech docs or part numbers.

**Comment by zerebubuth** [comment]
The supplier has very generously agreed to ship replacement fans at no charge. Thanks [Zeta Systems](http://www.zeta.systems/)! Will replace as soon possible after they arrive.

**Comment by zerebubuth** [comment]
Fans arrived. Will replace as soon as possible.

**Comment by tomhughes** [comment]
Fans have been replaced.
