### ISSUE TITLE
Reduce storage demand on root filesystem on balerion and bowser

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1080]
balerion and bowser both have small root filesystems.

We should move apache logs and potentially other large storage requirements to the currently unused array mounted at /store/unused

**Comment by tomhughes** [comment]
The apache logs are fine, we just need to move the replication state. Some of the other servers are affected as well.

I did manage it by hand last night but got distracted and didn't implement a permanent solution.

**Comment by tomhughes** [comment]
Replication state has now been moved to the large filesystem on those machines.
