### ISSUE TITLE
[Account request]: I would like to have an development account to develop a website for an American Client with omeka classic

### ISSUE THREAD

**Issue by nguyenloi85** [openstreetmap/operations#1084]
### Name

Hello, my name is Loi. I like the maps

### Email address

nguyenloi85@gmail.com

### OpenStreetMap username

nguyenloi85

### Username on the server

nguyenloi85

### Bio

```markdown
The website is for the class blue music platform. The map is use on home page and in the detail page.
```

### Public SSH key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAf7iiX+yA4IFkj+WCLs7VMeCVhDzDfZCyWwCwEeg+kD nguyenloi85@gmail.com

### Code of Conduct

- [X] I agree to follow the OpenStreetMap policies and codes of conduct, and to use the dev server only for OpenStreetMap-related tasks

**Comment by grischard** [comment]
The OpenStreetMap dev server is intended for OpenStreetMap-related development, not unrelated client projects.
