### ISSUE TITLE
[Account request]: r4113r

### ISSUE THREAD

**Issue by R4113R** [openstreetmap/operations#1095]
### Name

Rayer Serna

### Email address

jonaxelpi99@gmail.com

### OpenStreetMap username

R4113R

### Username on the server

r4113r 

### Bio

```markdown
I'M STUDENT & CURIOSITY :):
```

### Public SSH key

Ssha-rsa-R4113R

### Code of Conduct

- [X] I agree to follow the OpenStreetMap policies and codes of conduct, and to use the dev server only for OpenStreetMap-related tasks

**Comment by Firefishy** [comment]
That isn't a valid ssh public key.

What is soy editor?

**Comment by Firefishy** [comment]
No response.
