### ISSUE TITLE
Donation result page reports missing template

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/operations#1103]
### URL

https://supporting.openstreetmap.org/donate/

### How to reproduce the issue?

Make a payment, and you are returned to this page.

The page notes there is a template missing.

### Screenshot(s) or anything else?

![Screenshot 2024-06-22 at 12 10 21](https://github.com/openstreetmap/openstreetmap-website/assets/361423/52cbbb82-a824-47d9-9edd-d1be2b9bcc7b)

**Comment by grischard** [comment]
@dw504 this is for you.

**Comment by lonvia** [comment]
This is mainly an MWG issue. @datendelphin should be on the case now. They might need some operations support, so lets leave it open.

**Comment by mvl22** [comment]
I did search for a repo but couldn’t find it, so put it here so you could move the ticket to wherever it should be.

**Comment by datendelphin** [comment]
This issue is now solved. Thank you @mvl22 for reporting it. @tomhughes please close it, thank you.
