### ISSUE TITLE
Upgrade odin memory to match ysera?

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1105]
ysera and odin are twins.

We recently upgraded ysera from 256GB to 384GB of RAM.

Do we also want to upgrade odin from 256GB to 384GB of RAM?

Cost: £260 inc
Remote hands is an extra fee, else upgrade can be timed with the next site visit.

**Comment by Firefishy** [comment]
https://www.ebay.co.uk/itm/145646902805

**Comment by pnorman** [comment]
When both machines are at 100% ysera is consistently generating 5% more tiles. This is under 1 metatile per second.

A "new" odin or ysera would cost 2200 GBP, so 12% of the cost of an identical server for 5% of the performance gain.

We wouldn't buy another odin/ysera, we'd buy something newer, and the cost effectiveness of the upgrade is even worse in comparison to that.

I don't think we should do this.

**Comment by mboeringa** [comment]
@Firefishy 

Have you ever considered upgrading the **CPUs** _instead of RAM_? 

Although @pnorman may be right that upgrading the RAM on these machines with already 256GB may not be worth the money in terms of performance gains, upgrading the CPUs might be worth it.

I noticed many of the current OpenStreetMap servers use mid-range CPUs. While that is perfectly understandable to keep the cost down of a newly acquired brand new system, as the CPU cost and choice can be a very significant part of the cost of a new system, it also means there is considerable room for performance improvements once more powerful high end refurbished CPUs of the same generation hit the market, often at a cost that is only a fraction of the original new price.

E.g. the current Supermicro systems run [dual Intel Xeon Gold 5120 105W TDP CPUs](https://hardware.openstreetmap.org/servers/odin.openstreetmap.org/). According to [PassMark benchmarks](https://www.cpubenchmark.net/cpu.php?cpu=Intel+Xeon+Gold+5120+%40+2.20GHz&id=3154&cpuCount=2), those have a **29566-MT** and **1730-ST** score in dual CPU configuration, which is well below the top of their generation.

A nice replacement for those CPUs would be the [Intel Xeon Gold 6148](https://ark.intel.com/content/www/us/en/ark/products/120489/intel-xeon-gold-6148-processor-27-5m-cache-2-40-ghz.html). This, not very latest series, also FCLGA3647 socket, processor with 150W TDP should be supported on the system according to the [docs](https://www.supermicro.com/products/system/1U/1029/SYS-1029P-WTRT.cfm) of Supermicro.

These processors score **46668-MT** and **2110-ST**  [PassMark results](https://www.cpubenchmark.net/cpu.php?cpu=Intel+Xeon+Gold+6148+%40+2.40GHz&id=3176&cpuCount=2) in dual CPU configuration, which is about **55-60%** higher in multi-threaded performance than the current processors. So essentially, replacing all four 5120 processors in odin and ysera with 6148 CPUs would potentially result in a performance equal _to three of the current servers_, with added bonus of about 20% higher single threaded performance as well.

These processors can now be had for as little as about 200-225 euros including VAT, e.g. see these sites:
https://www.omniserver.nl/producten/onderdelen/processors/xeon-gold-processors/xeon-gold-6148-processor/ 
https://www.servershop24.de/en/intel-xeon-gold-6148-cpu/a-123546/
I am sure if you do more searching, maybe even better deals can be had, but even these prices are only 1/10th or less of original retail price, which is a major deal.

So for about 800 euro's, you could extend the life of these two servers for another few years with a clear uptick in performance.

Replacing CPUs is entirely doable. I replaced the dual Xeon E5-2680 v4 CPUs in my HP Z840 workstation with dual E5-2699 v4 processors, and got a similar about 45% uptick in multi-threaded performance closely matching the PassMark results.

Yes, it is not as quick and easy as popping in and out a new memory bank in a slot. But reading the available maintenance documentation and carefully follow the torc adjustment instructions regarding screwing down the heat sink on the processors, should allow a successful replacement without to much hassle. Only the very latest behemoth processors and sockets seem to be quite finicky and fragile, and may need special torc-adjustable screw driver tools to safely replace a CPU from what I read, but not these older processors.

**Comment by mboeringa** [comment]
I now noticed that [piasa](https://hardware.openstreetmap.org/servers/piasa.openstreetmap.org/) is already using that suggested Intel Xeon Gold 6148 processor in an HPE Proliant system, so it would be nice to compare throughput on piasa when under max load with the odin and ysera systems to see if the figures of real world performance match up to expectations.

**Comment by Firefishy** [comment]
@mboeringa Yes, I did put some time into looking at potential CPU upgrades. I had primarily been looking at [Cascade Lake](https://en.wikipedia.org/wiki/List_of_Intel_Xeon_processors_(Cascade_Lake-based)), as these are the best the system supports. I wasn't able any great value Xeon Cascade Lake CPUs on the reseller market. Best I could easily find is the Xeon Gold 6230.

In pure render speed there doesn't seem to be a huge improvement from Xeon Gold 5120 and a Xeon Gold 6148. Realistic difference is only maybe only 20% / 25% improvement. The Xeon 6148 does indeed look like very good value.

I've a large collection of different high-end thermal pastes and high-end thermal pads. Despite this I am not a huge fan of server CPU upgrades. It is a risk prone exercise. Our Supermicro systems are built by Supermicro in the Netherlands and pre-certified by them.

**Comment by mboeringa** [comment]
> It is a risk prone exercise.

Is this anecdotal or your own experience? Have you ever had real failure of a system after an upgrade?

My track record of doing these upgrades is admittedly non-existent, as I only did this twice (swapped out a Core i5 for i7, and these Xeons in the HP Z840), but I honestly and generally found it easier than expected if done with some due care. The main challenge is spreading the thermal paste properly, so as not to create heat spots on the processor where it cannot properly dissipate its heat, as you undoubtedly know.

Since the upgrade some 1,5 years ago though, I have trashed my HP Z840 for months on end at max CPU load without any noticeable (thermal) issues. The system has been rock solid ever since.

Yes, the Cascade lake processors do not yet seem to have come down enough in price to be worth it, while the 6148 is nearly the same speed for a fraction of the price.

Of course, if the real world experience still doesn't add up, it may need some further deliberation. Any other potential bottlenecks that may cause it, or some configuration needing a change to push the processors to their true potential?

**Comment by pnorman** [comment]
I wouldn't want remote hands to do this, so it would have to be Grant on one of his site visits. Time always feels limited on those.

**Comment by Firefishy** [comment]
The servers has a  SuperServer 1029P-WTRT chassis which says it ships with 2x SNK-P0067PSMB "_1U Passive High Performance Front CPU Heat Sink_"

 SNK-P0067PSMB specs say "_Up to 165 Watts_"

**Comment by Firefishy** [comment]
I have [found online resellers selling systems](https://www.etb-tech.com/supermicro-superstorage-ssg-6019p-acr12l-cse-802-x11ddw-nt-2-x-platinum-8173m-2-0ghz-twenty-eight-core-256gb-4-x-4tb-sata-7-2k-3-5-2-x-3-84tb-sata-2-5-aom-s3224-l-p-ipmi-v2-0-svr-ssg6019p-007.html) with  2x `Xeon 8173M` using the `X11DDW-NT` motherboard, so they are likely compatible.

**Comment by Firefishy** [comment]
model | cores | speed | TDP | cost (EUR) | CPU Mark (all core)
---|---|---|---|---|---
8173M | 28 | 2.0 | 165W | 245  | 28025
8160 | 24 | 2.1 | 150W | 304 | 28825
6152 | 22 | 2.1 | 140W | 186 | 25441
6148 | 20 | 2.4 | 150W | 161 | 28999 (fastest)
5120 | 14 | 2.2 | 105W | existing | 17686

**Comment by mboeringa** [comment]
The 6148 still seem the best value for the money. High MT performance and low cost. Added benefit is the slightly lower TDP that doesn't reach the limits of supported TDP of the systems, leaving some headroom.

**Comment by Firefishy** [comment]
I have ordered the matching memory.

I am also going to go ahead with the purchase of the 4x Xeon 6148. Thank you @mboeringa for the recommendation!

**Comment by Firefishy** [comment]
Order of 4x Xeon 6148 CPUs confirmed. Bargain price of £425 total.

**Comment by Firefishy** [comment]
Orders arrived. CPU and RAM now in stock in Catford.

**Comment by Firefishy** [comment]
Memory upgraded and confirmed working. CPU upgrade pending.

**Comment by Firefishy** [comment]
CPU upgraded but running very very hot. The thermal paste takes awhile to settle in and there is a very bad airflow pattern with the switches. We can create new tickets if needed.
