### ISSUE TITLE
520 when connecting via OAuth2

### ISSUE THREAD

**Issue by yohanboniface** [openstreetmap/operations#1110]
Hi!

You may already be aware, or it may be something on uMap configuration side for OAuth 2, but I've been reported today this error message (reproduced myself):

![image](https://github.com/openstreetmap/operations/assets/146023/3cacb395-ab71-4ba4-97c2-b5cc4490b3d6)

Thanks for your lights on this :)

Yohan

**Comment by Firefishy** [comment]
We were under a large DDOS attack. This is most likely a consequence of the attack.

**Comment by yohanboniface** [comment]
Seems to back. 
Thanks for the info, and sorry for that :(
