### ISSUE TITLE
Upgrade 4G antenna @ AMS

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1111]
The 4G modem at AMS keeps falling back to 2G due to poor signal.

We should try upgrade the antenna to see if it helps.

**Comment by Firefishy** [comment]
The current modem is: https://teltonika-networks.com/products/modems/TRM240/
The current antenna is: https://teltonika-networks.com/products/accessories/antenna-options/mobile-sma-antenna

**Comment by mboeringa** [comment]
You mean potentially something like this? From the teltonika site it appears the current antenna is already the highest gain version they offer there:
https://www.amazon.com/ZDTECH-10-12dBi-External-Directional-Cellular/dp/B09B15BSJH

**Comment by Firefishy** [comment]
> You mean potentially something like this? From the teltonika site it appears the current antenna is already the highest gain version they offer there: https://www.amazon.com/ZDTECH-10-12dBi-External-Directional-Cellular/dp/B09B15BSJH

Yes, something like that. Many antenna's seem to have poor reviews and fake dBi number. The ZDTech antenna linked above doesn't have a good reviews.

Poynting antennas have generally good reviews.

**Comment by Firefishy** [comment]
For what its worth I did tweet Teltonika to ask if they can recommend any antenna: https://x.com/OSM_Tech/status/1811739244236308838

**Comment by Firefishy** [comment]
Switched the antenna. Ping times 50% to 80% better. 2G -> 4G connection.
I am not really sure it is a better antenna. The signal strength in the hall seems good, so the antenna type may be affecting the noise floor.

**Comment by Firefishy** [comment]
The new antenna did help, but the signal strength is still very weak, with higher than expected latency.

I am going to replace the antenna with a [Quectel YE0001BA 5 dBi antenna](https://mou.sr/4dxQooS). (Note to reader the 12 dBi quoted for the Amazon antenna is fake.)

Current signal strength is Poor:
```
LTE:
	RSSI: '-87 dBm'
	RSRQ: '-19 dB'
	RSRP: '-124 dBm'
	SNR: '-6.4 dB'
```

**Comment by Firefishy** [comment]
Forcing the mobile network to `NL KPN` has improved the signal strength and drastically improved the latency from ~180ms to ~60ms.

```
LTE:
	RSSI: '-85 dBm'
	RSRQ: '-11 dB'
	RSRP: '-114 dBm'
	SNR: '0.8 dB'
```

**Comment by Firefishy** [comment]
Antenna upgraded. Very nice improvement in latency.

**Comment by Firefishy** [comment]
```
LTE:
	RSSI: '-73 dBm'
	RSRQ: '-11 dB'
	RSRP: '-99 dBm'
	SNR: '5.4 dB'
```
