### ISSUE TITLE
Clarification Needed on EPSG:3857 Coordinate Conversion in Slippy Map Wiki

### ISSUE THREAD

**Issue by moong23** [openstreetmap/operations#1121]
**Is this the right place to ask about the Wiki?** (Sorry if not 😢, please feel free to close this issue if it's not appropriate.)

I need to get the tile for the coordinates I have in EPSG:4326 format.
So, I tried to transform the coordinates into EPSG:3857 format according to the [Slippy Map Wiki](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames).

Following the [example provided](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Example:_Convert_a_GPS_coordinate_to_a_pixel_position_in_a_Web_Mercator_tile), I used proj4 instead of manually coding the mathematical expressions.

However, the wiki states that the x and y values are in EPSG:3857 format, but the values seem very different from what I found using [this calculator](https://epsg.io/transform#s_srs=4326&t_srs=3857&x=139.7006792&y=35.6590700).

So, my question is:
Are the x_EPSG:3857 and y_EPSG:3857 values on the wiki really in EPSG:3857 format?
If not, what format are the x and y values in?

**Comment by tomhughes** [comment]
No it is not the correct place to ask - this tracker is used by the operations team to track operational issues running the servers and is not a general support forum.

Please use https://community.openstreetmap.org/help to ask your question.
