### ISSUE TITLE
SSL certificate of 20th birthday site has expired

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/operations#1128]
I’m no longer able to load [birthday20.openstreetmap.org](https://birthday20.openstreetmap.org/) because of an `SEC_ERROR_EXPIRED_CERTIFICATE` error. Firefox reports that the current certificate expired on July 31. This is unfortunate since we’re starting to get more attention on the site as the birthday nears. (For example, I’m fielding a request to add a big banner linking to the site from the wiki’s homepage.)

**Comment by tomhughes** [comment]
Well that's what you get for demanding we launch an under development site without properly bringing it under chef control as a production service.
