### ISSUE TITLE
OSU Planned Maintenance Outage - August 13 2024 -  August 14, 2024

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1129]
OSU network uplink may be offline during  upcoming planned maintenance. 

> On August 13, 2024 (08/13), Oregon State University (OSU) will be cutting both primary and backup power to its data center in the Kerr Administration building, to install new power distribution and backup equipment. This will take two of Link Oregon’s points of presence offline, resulting in a loss of all provisioned network services provided by Link Oregon at those POPs, over a period of approximately eight (8) hours (08/13-20:00 to 08/14-04:00).

UTC: 3am to 11am August 14, 2024.

## Servers affected 
* piasa (tile)
* stormfly-03 (prometheus)
* stormfly-04 (nominatim)

**Comment by Firefishy** [comment]
@pnorman Any rebalancing we should do in preparation with the fastly cache?

**Comment by Firefishy** [comment]
`TL;DR: If LinkOregon can find power for their switches, we won't have an outage. If they can't, we will have an eight (8) hour outage next Tuesday evening PDT.`

**Comment by pnorman** [comment]
> @pnorman Any rebalancing we should do in preparation with the fastly cache?

Nope. It'll fail over to put all traffic on the AWS server. If we find that becomes overloaded we'll have to rearrange traffic.

**Comment by Firefishy** [comment]
Latest update, looks like the connectivity will remain (no downtime).

>  I have some great news! LinkOregon and OSU have figured some secondary power to keep our connection to LinkOregon online during the outage. 
> [...]
> we should stay online during the planned outage.
