### ISSUE TITLE
S3 permissions request: GetBucketLocation

### ISSUE THREAD

**Issue by mojodna** [openstreetmap/operations#1130]
Please add [`s3:GetBucketLocation`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html) permission to the bucket policy for the `osm-planet-eu-central-1` S3 buckets on AWS. This will allow data consumers to write code that can automatically resolve the right region to use when accessing a bucket w/o parsing the bucket name.

Without this permission, calls will return access denied:

```console
❯ aws s3api get-bucket-location --bucket osm-planet-eu-central-1

An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
```

This currently works for the `us-west-2`-hosted bucket:

```console
❯ aws s3api get-bucket-location --bucket osm-planet-us-west-2
{
    "LocationConstraint": "us-west-2"
}
```

**Comment by tomhughes** [comment]
I believe we deliberately direct everybody to the one bucket because we can't guarantee the mirror will work.

**Comment by mojodna** [comment]
That's a separate issue. I'm asking for the buckets (however they're used) to have matching configurations.

`GetBucketLocation` is used to determine which region a given bucket is located in, not to do any sort of redirect.

**Comment by tomhughes** [comment]
Sorry I thought you meant you wanted to get the region in order to decide which bucket to use but you mean you want it in order to decide where to put your consumer?

**Comment by mojodna** [comment]
Ish. The AWS SDKs require setting a region in order to configure the client that talks to the S3 API. Some S3 APIs (like `GetBucketLocation`) will work the same regardless of which region is called, but `GetObject` (which fetches things) requires that the client be configured to talk to the region where the bucket is located, which either needs to be done manually or by using `GetBucketLocation`. Understandably, many tools use the latter approach.

**Comment by Firefishy** [comment]
`osm-planet-eu-central-1` Bucket policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadBucket",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::osm-planet-eu-central-1"
        },
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "s3:GetObjectTagging",
                "s3:GetObjectAttributes",
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::osm-planet-eu-central-1/*"
        }
    ]
}
```

`osm-planet-us-west-2` Bucket policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadBucket",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::osm-planet-us-west-2"
        },
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "s3:GetObjectTagging",
                "s3:GetObjectAttributes",
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::osm-planet-us-west-2/*"
        }
    ]
}
```

**Comment by Firefishy** [comment]
These work:
`AWS_REGION=eu-central-1 aws s3api --no-sign-request get-bucket-location --bucket osm-planet-eu-central-1`
`AWS_REGION=us-west-2 aws s3api --no-sign-request get-bucket-location --bucket osm-planet-us-west-2`

**Comment by mojodna** [comment]
I'll do some more digging to figure out how it's supposed to work. Something doesn't seem right here (and you shouldn't need to know the bucket's region to, um, look up the bucket's region).

```console
❯ aws --region us-west-2 s3api get-bucket-location --bucket osm-planet-eu-central-1

An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
❯ aws --region eu-central-1 s3api get-bucket-location --bucket osm-planet-eu-central-1
{
    "LocationConstraint": "eu-central-1"
}
```

**Comment by Firefishy** [comment]
I will dig more. Doesn't seem right to me either, but has been [reported](https://github.com/aws/aws-sdk-go/issues/720) [elsewhere](https://github.com/aws/aws-sdk-go/issues/380) too.

**Comment by mojodna** [comment]
I'm holding it wrong. I was just looking at https://github.com/aws/aws-sdk-go/issues/720#issuecomment-243891223 too. It sounds like it's related to making calls as someone other than the bucket owner.

This works as expected:

```console
❯ aws --region eu-central-1 --no-sign-request s3api head-bucket --bucket osm-planet-eu-central-1
{
    "BucketRegion": "eu-central-1",
    "AccessPointAlias": false
}
❯ aws --region us-west-2 --no-sign-request s3api head-bucket --bucket osm-planet-eu-central-1
{
    "BucketRegion": "eu-central-1",
    "AccessPointAlias": false
}
```

**Comment by ganeshgk** [comment]
@mojodna Thanks a ton! saved us a lot of time. This is not documented anywhere. We were having the same issue with GetBucketLocation & have been going crazy with the bucket policies as to what to fix.
