### ISSUE TITLE
Minutely OSM Replication diffs stopped @ Mon Aug 05 02:24:48 UTC 2024

### ISSUE THREAD

**Issue by pa5cal** [openstreetmap/operations#1131]
The minutely replication diff stopped at

```
#Mon Aug 05 02:24:48 UTC 2024
sequenceNumber=6205195
timestamp=2024-08-05T02\:24\:04Z
```
https://osm-planet-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com/planet/replication/minute/state.txt

Hourly diff no longer exists either.
```
#Mon Aug 05 02:02:04 UTC 2024
sequenceNumber=104275
timestamp=2024-08-05T02\:00\:00Z
```
https://osm-planet-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com/planet/replication/hour/state.txt

However, the changeset diffs are still available:
https://planet.openstreetmap.org/replication/changesets/

**Comment by mmd-osm** [comment]
https://en.osm.town/@openstreetmap/112907332329555972

**Comment by tomhughes** [comment]
When there are no changes there are no diffs.

**Comment by pa5cal** [comment]
That's not true.

The data can currently be edited in OSM and there are currently neither minute diffs nor changeset diffs.

**Comment by mmd-osm** [comment]
It seems replication only worked for 2 minutes after the restart, and is now defunct.

https://planet.osm.org/replication/minute/006/205/

**Comment by hholzgra** [comment]
That's what I'm seeing, too. Lag went back to basically zero briefly, then started to build up again:

https://get-map.org/munin/get-map.org/print.get-map.org/osm_lag.html

**Comment by tomhughes** [comment]
Yes I thought I had found the root cause when I posted before but it turns out I spoke too soon and had to reboot the database and the replication job got stuck when that happened. I've restarted it now.

**Comment by mmd-osm** [comment]
Rails job queue keeps on growing at the moment. Maybe something got stuck there, too: https://prometheus.openstreetmap.org/d/5rTT87FMk/web-site?orgId=1&from=now-12h&to=now&refresh=1m&viewPanel=25
