### ISSUE TITLE
Sign up flow blocked for some email addresses

### ISSUE THREAD

**Issue by eneerhut** [openstreetmap/operations#1135]
As I'm sure you know, Meta has paid editors that map in OSM. We have a consistent username and email format we use to keep track of these accounts e.g. username: xyzxxx and email: roadedits+xyzxxx@gmail.com. Our team has been encountering errors on sign up recently when they try to create these accounts.
![image](https://github.com/user-attachments/assets/50d30c30-6658-43a9-b575-5a124dcee9e5)

Is there a recent change that is causing these signups to be blocked? Is this an vandalism initiative? We can adjust accordingly, but wanted to confirm.

Thank you!

**Comment by tomhughes** [comment]
Not recent, no, but multiple signups from the same email have been heavily limited for the best part of a year now.

**Comment by eneerhut** [comment]
@tomhughes do you have any recommendations?

The reason we use aliases is to stay on top of the feedback our mappers receive by ensuring it goes to one inbox. E.g. If we gave a range of emails, could they be put on an allowlist?

**Comment by tomhughes** [comment]
Well if it was on a meta domain then I could whitelist it as we did for mapbuilder but I can't really whitelist gmail.

What I need is either an email domain or an IP address range that is reasonably specific that I can then whitelist.

**Comment by eneerhut** [comment]
Ok thank you. I'll look into it and reply back.

**Comment by eneerhut** [comment]
@tomhughes if you are able to add @meta.com to an allow list, that would be much appreciated. We'll make sure all new organization editing accounts are created on this domain. We'll use the account to track any feedback that the community is providing.

Thank you!

**Comment by tomhughes** [comment]
You're going to be using a single account with plus addressing on meta.com is that correct?

**Comment by eneerhut** [comment]
Yes, that's correct @tomhughes

**Comment by tomhughes** [comment]
That should be allow listed now.

**Comment by eneerhut** [comment]
Much appreciated. Thank you @tomhughes!
