### ISSUE TITLE
Additions to use policies

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/operations#114]
Pro memoria (I'll produce a corresponding PR): the use policies should contain pointers to the new privacy policy and at least the tile usage policy should require a suitable link to https://www.openstreetmap.org/fixthemap

**Comment by tomhughes** [comment]
As the use policies are in the wiki I'm not sure what you're going to produce a PR against?

**Comment by lonvia** [comment]
Sounds okay to me.

**Comment by simonpoole** [comment]
Given that this seems to be non-controversial updating the policies as we speak.
