### ISSUE TITLE
Minute replication broken

### ISSUE THREAD

**Issue by drolbr** [openstreetmap/operations#1143]
Files https://planet.openstreetmap.org/replication/minute/006/217/368.state.txt and https://planet.openstreetmap.org/replication/minute/006/217/368.osc.gz point towards an error message instead of actual files:

````
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>planet/replication/minute/006/217/368.osc.gz</Key>
<RequestId>JM88FWJM0114RDCC</RequestId>
<HostId>
5Y5ra5Vl92IxBmUKpySwWkhyPXxTnHmFvwvD1Qdl6rWDh7dc0BRSETMy42oFanTzIZ7IYOczCbk=
</HostId>
</Error>
````

This breaks minute replication.

**Comment by drolbr** [comment]
Fixed since about 06:07 UTC

**Comment by tomhughes** [comment]
Well I was going to close this once I was happy I had addressed the root cause permanently but whatever.
