### ISSUE TITLE
z17 tiles rendered full-color construction color

### ISSUE THREAD

**Issue by tilmanb** [openstreetmap/operations#115]
At the moment some tiles on z17 are rendered with a full construction color fill, and someone suggested it might be full metatiles that get this color. Was there some kind of database hiccup that might create this?

See for example http://www.openstreetmap.org/#map=17/51.95633/13.88896 .

Requesting single tile re-rendering using /dirty does not solve anything.

**Comment by tomhughes** [comment]
Data issue - somebody has created a large planet spanning polygon.
