### ISSUE TITLE
Migate Faffy (dev server) to Debian 12

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1151]
The OpenStreetMap.org servers now run Debian 12. It is best if we also align the dev server to run Debian 12.

- [x] Announce planned migration to existing dev server users.
- [x] Offline move existing filesystem data to temporary folders.
- [x] Install Debian 12 onto existing partitions without formatting partitions.
- [x] Re-install chef and allow initial setup. May require some package tweaks.
- [x] Move original `/home` back to correct location.
- [x] Restore postgres databases + reindex.
- [x] Restore mysql databases + reindex.
- [x] Restore user cronjobs. 
- [x] Restore encrypted user passwords using `chpasswd -e`

**Comment by Firefishy** [comment]
I have BCC emailed all dev server users who have logged in over the last year notifying them about the change. I will email them again when the upgrade has been completed.

I said a likely date for the upgrade is 3rd or 4th September 2024.

**Comment by Firefishy** [comment]
Some of the reasons for the migration to Debian are captured here: https://github.com/openstreetmap/operations/issues/844

**Comment by mmd-osm** [comment]
https://master.apis.dev.openstreetmap.org/rails/active_storage/disk/... seems to be unavailable atm (avatar images + gpx traces)

**Comment by tomhughes** [comment]
That should be fixed now.

**Comment by Firefishy** [comment]
Thank you for the help @tomhughes
