### ISSUE TITLE
OSMF WG email bounce messages

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#1152]
Sometimes a working group list includes an email address that bounces. When this happens anyone who sends an email gets an error message, for example, 

```
This is the mail system at host mx2.mailbox.org.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

[<user@example.com>](mailto:user@example.com) (expanded from [<engineering@ grant-removing-domain .org>](mailto:engineering@ grant-removing-domain .org)): host
    aspmx.l.google.com[142.250.147.26] said: 550-5.7.1 Alumni email service
    over limit, email blocked outside example.com. 550-5.7.1 Messages to/from
    non-Example accounts will not be sent or received. 550 5.7.1 See
    https://bconnected.example.com/alumni-email for details. - gcdp
    4fb4d7f45d1cf-5c25290fe26si2709338a12.136 - gsmtp (in reply to end of DATA
```

These error messages should not be sent to possibly external people as they reveal who is on the email list, and because it is a bad user experience to give error messages that can't be solved and aren't obvious.

Update: Grant has removed the OSMF domain to avoid spammers picking it up. OSMF has a known domain.

**Comment by Firefishy** [comment]
engineering@ does not have @example.com as a member. I guess you mean an existing specific member is bouncing. In that case ask me or Dorothea to remove them from the alias.

**Comment by pnorman** [comment]
> engineering@ does not have @example.com as a member. I guess you mean an existing specific member is bouncing. In that case ask me or Dorothea to remove them from the alias.

Yes - the problem is this has happened on multiple lists.
