### ISSUE TITLE
ysera CPU upgrade

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1156]
Forked issue from https://github.com/openstreetmap/operations/issues/1105

Upgrade the CPUs in ysera to 2x Xeon 6148.

**Comment by Firefishy** [comment]
CPUs upgraded. "Fun" aka crazy tight 1U heatsink mounting but seems ok.

**Comment by Firefishy** [comment]
Performance appears to have improved ~33% in nightly low zoom render. Previously ~3 hours, now ~2 hours.

**Comment by mboeringa** [comment]
> Performance appears to have improved ~33% in nightly low zoom render. Previously ~3 hours, now ~2 hours.

That's a nice uptick in performance!
