### ISSUE TITLE
Replace Switch PSU + Fans with AFI version

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1158]
The switches at AMS blow heat in the wrong direction. This is causing a heat bubble due to hot air being continuously cycled through the servers and switches within the rack.

Per switch the following is required:
2x JPSU-350-AC-AFI
2x  EX4300-FAN-AFI 660-044938 (Fan Module, Airflow In)

**Comment by mboeringa** [comment]
Related: https://github.com/openstreetmap/operations/issues/1076

**Comment by Firefishy** [comment]
I've ordered 1x JPSU-350-AC-AFI for testing - £26.

**Comment by Firefishy** [comment]
2x JPSU-350-AC-AFI 
5x EX4300-FAN-AFI 660-044938
Ordered. £256

**Comment by Firefishy** [comment]
The 5x EX4300-FAN-AFI 660-044938 have arrived in Catford stock.

**Comment by Firefishy** [comment]
Ordered another 5x EX4300-FAN-AFI 660-044938

**Comment by Firefishy** [comment]
I've ordered another 2x JPSU-350-AC-AFI refurbished from a it-planet.com (Germany). The earlier order of PSU has not shipped and I've opened a dispute with ebay.

**Comment by Firefishy** [comment]
All required EX4300-FAN-AFI 660-044938 in stock.
2x JPSU-350-AC-AFI in stock.
2x JPSU-350-AC-AFI delivery pending.

**Comment by Firefishy** [comment]
I have now tested a few different replacement methods (Fans First, PSUs First, Mixed) all work, with temporary `Major  FPC 0 Fan & PSU Airflow direction mismatch` warnings or similar.

**Comment by Firefishy** [comment]
2x JPSU-350-AC-AFI ordered beginning of October have now arrived.

Catford Stock:
5x EX4300-FAN-AFI 660-044938
4x JPSU-350-AC-AFI

**Comment by Firefishy** [comment]
Installed
