### ISSUE TITLE
Nominatim rate limit increase for new GNOME IP addresses

### ISSUE THREAD

**Issue by barthalion** [openstreetmap/operations#1160]
Hi folks,

Two years ago, we requested being whitelisted for Nominatim access (which I think boiled down to up to 12 requests/s). We are currently migrating infrastructure again, which means we're hitting Nominatim from new IPs:

34.234.151.67
54.165.53.199
35.153.15.118

Can I ask you to update the list to the addresses above? Thank you!

prev issue: https://github.com/openstreetmap/operations/issues/738

**Comment by Firefishy** [comment]
Change should be deployed in the next hour.
