### ISSUE TITLE
Prometheus postgres exporter broken on PG17

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/operations#1180]
I'm seeing https://github.com/prometheus-community/postgres_exporter/issues/1060 on the Nominatim machines that have switched to PostgreSQL 17:

```
> journalctl -u prometheus-postgres-17-main-exporter.service
Oct 29 08:40:44 dulcy.openstreetmap.org postgres_exporter_x86_64[63312]: ts=2024-10-29T08:40:44.190Z caller=collector.go:202 level=error msg="collector failed" name=stat_bgwriter duration_seconds=0.010848917 err="pq: column \"checkpoints_timed\" does not exist"
```

There is a PR to fix it but it looks to be stuck.

[Suggested remedy](https://github.com/prometheus-community/postgres_exporter/issues/1060#issuecomment-2420235829) is to run the exporter with `--no-collector.stat_bgwriter` in the meantime.

**Comment by tomhughes** [comment]
I've pushed https://github.com/openstreetmap/chef/commit/da3e292dc325b96df2c805d729427c8bf6741b81 to do that fir postgres 17 as a temporary fix.

**Comment by Firefishy** [comment]
[Fixed in postgres_exporter](https://github.com/prometheus-community/postgres_exporter/pull/1072) [0.17.0](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.17.0), we are now running 0.17.1
