### ISSUE TITLE
bug at https://dns.openstreetmap.org

### ISSUE THREAD

**Issue by Cyrille37** [openstreetmap/operations#1183]
Hi

There is 3 links at https://dns.openstreetmap.org 

The one to [tile.openstreetmap.org](https://dns.openstreetmap.org/tile.openstreetmap.org.html) throws the javascript error "Uncaught Error: Bounds are not valid." so the page fails.

Thanks & cheers

**Comment by tomhughes** [comment]
There is no tile geozone these days so that link is redundant. Only the nominatim zone still exists.

**Comment by tomhughes** [comment]
Fixed.

**Comment by Cyrille37** [comment]
Thanks.

But now only link to nominatim, no more renderer and tile ?
