### ISSUE TITLE
Electrical shutdown at Imperial

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#119]
We have been informed of a complete electrical shutdown in both rooms at Imperial from midnight on Friday 6th January 2017 to 6am on Saturday 7th January 2017.

**Comment by tomhughes** [comment]
I suggest we leave making karm the master until after this, so that we can run the site at bytemark during this outage without having to flip the master back to York.

Other than that, and making sure we are running from the alternate nominatim instance the main thing we will lose is the wiki I think - tile serving should be fine without one render server in the early hours of a Saturday morning.

**Comment by zerebubuth** [comment]
This happened, and I don't think there are any issues left over from it. If I'm wrong, please re-open or (better still) file a new, more specific issue for it.
