### ISSUE TITLE
2015 budget & plan

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#12]
Write up 2015 needs, with budget, and plan for expansion.

**Comment by gravitystorm** [comment]
We haven't heard back from the treasurer yet, but I've just sent a chasing email to find out what the progress is. For reference, we submitted our budget on the 24th December.

**Comment by Firefishy** [comment]
Donate site is up and running: http://donate.openstreetmap.org/server2015/

**Comment by zerebubuth** [comment]
We've done the donation drive, and part of that was budgeting. I'm going to call this one closed. Feel free to re-open if there's any outstanding issue.
