### ISSUE TITLE
Dual ISP policy routing appears to have broken docker networking for mail-receiver for community.osm.org

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1200]
The mail-receiver container for community.osm.org is unable to connect to the IPs for community.osm.org

Likely an issue with policy routing or similar.

**Comment by Firefishy** [comment]
As a workaround I have manually host hacked community.openstreetmap.org in the container to point to 172.17.0.4 (Docker special IP for host)

**Comment by Firefishy** [comment]
This appears to fix the routing issue:
```
sudo ip route add 172.17.0.0/16 dev docker0 table 100
```

Need to backport it into chef.

**Comment by tomhughes** [comment]
Ah so it's actually the route back to 172.17 that is the problem, not the outgoing route from from 172.17 to the public address. That explains why I was having so much trouble fixing it.

I suspect that an additional rule would also work:

```
sudo ip rule add to 172.17.0.0/16 table main priority 50
```

**Comment by tomhughes** [comment]
Yes that seems to work so I've implemented it in https://github.com/openstreetmap/chef/commit/e397f006ac6cacb175c27f81b86ce5d90e39e7c3.
