### ISSUE TITLE
Recover overwritten minutely diffs 000000001... 000000234

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#121]
Files http://planet.openstreetmap.org/replication/minute/000/000/001.state.txt through http://planet.openstreetmap.org/replication/minute/000/000/234.state.txt and http://planet.openstreetmap.org/replication/minute/000/000/001.osc.gz through http://planet.openstreetmap.org/replication/minute/000/000/234.osc.gz have been overwritten by an osmosis run in May 2016 and no longer include the original data.

Can the original minutely diffs recovered somehow? I think we also have a copy of those files on the Overpass server and we're happy to provide them if needed.

**Comment by tomhughes** [comment]
As far as I know there is no way to regenerate diffs.

More to the point, nobody should be trying to replay diffs going back that far, and people that I catch doing so often get blocked anyway...

**Comment by mmd-osm** [comment]
Well, that's the usual way to set up an Overpass API instance with attic / museum data: import the first ODbL planet and apply and subsequent minutely diff. I'll post a link to those files, so that the overwritten files can be replaced, if that's ok for you.

**Comment by pnorman** [comment]
> import the first ODbL planet and apply and subsequent minutely diff

Don't do that. If you can't use the full history planet (which you should use), use daily diffs.

**Comment by mmd-osm** [comment]
@pnorman : you're right, I can't use the full history planet for that purpose. As you may remember, I mentioned in some post on osm dev, that I faced some issues with daily diffs, notably that a few minutely diffs were missing in a daily diff in some cases. In the long run that caused some severe inconsistencies on Overpass side due to inconsistent/lacking data.

My impression so far is that this affects only a very small number of daily diffs, notably, when osmosis aborted on that day has re-created the same minutely diff on that day. But I haven't found an effient approach to validate the completeness of daily diffs wrt to the corresponding minutely diffs.

**Comment by gravitystorm** [comment]
> you're right, I can't use the full history planet for that purpose.

Is this because of a software limitation (i.e. overpass would need new code written) or something else? Is there information in the minutely diffs that can't be synthesised from a history dump?

As Tom says, we provide history dumps to avoid needing to replay hundreds of thousands of diff updates.

We should also either fix the broken diffs, or remove them, rather than leaving them broken.

**Comment by tomhughes** [comment]
A lot of the times I have noticed people doing it I suspect they are catching up render servers or nominatim servers rather that overpass, but they let them get six months out of date and then try and catch them up using minutely diffs rather than reimporting or using daily diffs to do most of the catch up.

**Comment by tomhughes** [comment]
BTW what I'd really like is an overpass mode that is clever enough to use dailies and switch to hourlies and then minutelies as it gets close to the target, but I'm not sure how possible that is due to needing to synchronise between the three feeds.

**Comment by mmd-osm** [comment]
@gravitystorm : Some time ago, I tested a small libosmium based full history splitter to re-create daily diffs. That's was needed to keep memory requirements on Overpass import in reasonable limits. Processing a few weeks even worked ok. However, the big issue I faced were *redactions*. They're really screwing things up on Overpass side, as the attic/museum stores data as difference/delta to previous versions. If those versions no longer exist in the full history dump, thing go seriously wrong, unfortunately. I haven't yet found a way to work around that.

**Comment by Komzpa** [comment]
`osmupdate` is able to get diffs in that manner, getting minutely/hourly
diffs only to fetch half a day intervals.

вт, 8 нояб. 2016 г. в 15:43, Tom Hughes <notifications@github.com>:

**Comment by pnorman** [comment]
> @gravitystorm : Some time ago, I tested a small libosmium based full history splitter to re-create daily diffs. That's was needed to keep memory requirements on Overpass import in reasonable limits. Processing a few weeks even worked ok. However, the big issue I faced were redactions. They're really screwing things up on Overpass side, as the attic/museum stores data as difference/delta to previous versions. If those versions no longer exist in the full history dump, thing go seriously wrong, unfortunately. I haven't yet found a way to work around that.

Strictly speaking we shouldn't be showing redacted objects in the diffs either, it's just that we've never removed them and never gotten a takedown request specific to them. Anything which relies on the assumption that all versions of an object will be accessible is broken.

**Comment by Firefishy** [comment]
I likely have an old backup of the diffs on a powered down server. Can check later

**Comment by mmd-osm** [comment]
I put a backup of the first 300 minutely diffs on the following server now: http://dev.overpass-api.de/tmp/minutely_diffs_backup.tar.gz ... just in case no old backup is available.

**Comment by tomhughes** [comment]
I've replaced those file the ones from your backup now, so thanks for providing those.

**Comment by zerebubuth** [comment]
Just a thought - might it be worth `chmod -r` on the first `000/000/*` files just to make accidental overwriting more difficult in the future?
