### ISSUE TITLE
Make tile block look better

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/operations#122]
Right now block for tile access looks pretty ugly:

![image](https://cloud.githubusercontent.com/assets/810638/20098365/7cc5a926-a5c4-11e6-8169-8a9203fbbb11.png)

Is there a tech issue to send an image for this kind of traffic without poisoning browser cache?

Can this be implemented if we make 'OpenStreetMap is over capacity / donate' 256x256 banner?

**Comment by Zverik** [comment]
https://github.com/openstreetmap/chef/tree/master/cookbooks/tile/files/default/html

**Comment by tomhughes** [comment]
No, we do not want them to think they can just send us some money and then get to do what they want. That's not how it works.

In this case they completed melted down at least two caches and one render server by the sudden addition of a vast amount of additional load that was well outside the usage policy.

We are not trying to run a free google maps alternative and provide everything to all comers.
