### ISSUE TITLE
Ramoth pending disk failure

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#123]
ramoth has a disk failing SMART health warning:
Device: /dev/sg2 [megaraid_disk_37], SMART Failure: FAILURE PREDICTION THRESHOLD EXCEEDED
Device info:
[SEAGATE  ST3600057SS      000B], 600 GB

Serial: 6SL1AWKG

Disk should be replaced.

**Comment by Firefishy** [comment]
Some of the other disks in the machine are not particularly healthy.

**Comment by Firefishy** [comment]
Another disk should likely be replaced as it is particularly unhealthy:
Serial 6SL24P57

**Comment by zerebubuth** [comment]
6SL1AWKG replaced.

**Comment by zerebubuth** [comment]
6SL24P57 was replaced shortly afterwards.
