### ISSUE TITLE
Replace 72GB disks in ridley

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#124]
Replace ageing 2x 72GB disks with newer 146GB disks to fill out the RAID6 array. @Firefishy has the disks.

**Comment by zerebubuth** [comment]
Replaced 1x 72GB disk. Only doing one at a time so that we can still tolerate one failure while rebuilding. Will replace the other on the next trip.

**Comment by Firefishy** [comment]
1 more disk to replace in ridley:
physicaldrive 1I:1:2 (port 1I:box 1:bay 2, SAS, 72 GB, OK)

**Comment by zerebubuth** [comment]
Replaced.
