### ISSUE TITLE
UCL server moves - 7th Dec

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#129]
The [servers at UCL](https://hardware.openstreetmap.org/#university-college-london) will be shut down and relocated to another datacenter on 7th Dec 2016. Although everything is planned to go smoothly, we don't have all the details yet. Nor do we know how long the services might be down for.

Services that will be affected:

1. Render ~~and Nominatim~~ will have reduced capacity due to Yevaud ~~and Pummelzacken~~ being down.
2. Dev will be down.
3. The forum will be down.
4. Whatever draco is doing will stop. 
5. Piwik will be down.
6. ~~Taginfo will have to move to OSUOSL?~~
7. The GPS tile server will be down.
8. Gosmore will be down.
9. Munin will be down.
10. The foundation sites will be down, including blog, donate, OTRS, SOTM and switch2osm.

**Comment by gravitystorm** [comment]
I can make myself available for either datacentre that day, if it helps.

**Comment by lonvia** [comment]
pummelzacken is running as cold spare, so it's in the clear. Taginfo is running from OSUOSL already as far as I can tell.

**Comment by gravitystorm** [comment]
It's definitely worth chipping away at each of these until we're focussed on what's left. Makes the problem smaller that way.

Can a sysadmin please find out what draco is up to? There's nothing obvious in chef as to what it's supposed to be doing.

**Comment by tomhughes** [comment]
It's @Firefishy's other imagery machine isn't it?

**Comment by tomhughes** [comment]
I'll reduce all the DNS TTLs this evening but other than that I don't think there's much to do - as @lonvia says taginfo is already pointing at the US and nominatim is also pointing elsewhere.

**Comment by zerebubuth** [comment]
I think the most important things we could be looking at are the Forum (clifford), Foundation sites (ridley) and maybe Piwik.

@tomhughes if Piwik is down, is there any noticeable problem on osm.org?

I definitely want to backup and exfiltrate copies of the Forum and Foundation sites, in case the worst happens and those machines don't come back up, or are offline for a significant period of time. The best thing would be to stand them up somewhere else for the duration, but that's probably a lot of work. What's the hardest thing about moving those services?

**Comment by tomhughes** [comment]
Piwik is loaded asynchronously so should be fine.

There's far too much going on on ridley to think about moving them, especially as some of them can probably only run on 14.04 and we don't have many 14.04 machines now.

**Comment by mtmail** [comment]
We (https://geocoder.opencagedata.com/) happen to have a fresh installed unused Nominatim server ready next week, the timing is fortunate. Ubuntu, latest Nominatim+Tiger (no other software) on dedicated 8-core, 64GB RAM, 2x960 SSD (RAID1).

You can have root, any ssh keys on the machine you like, even lock us out and wipe the drives after use if needed. As I understand `Dulcy` is expected to be able to keep up with the full traffic so this would only be needed when something unexpected happens.

**Comment by tomhughes** [comment]
Thanks for the offer @mtmail but our Nominatim instance is currently running on dulcy, which is at Imperial and hence unaffected by this move, so we should be fine.

**Comment by zerebubuth** [comment]
This happened, and I don't think there are any issues remaining from it. If I'm wrong, please re-open or (even better) file a new, more specific issue for it.
