### ISSUE TITLE
Ironbelly Disk Issue - Disconnecting

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#130]
The global host spare disk in ironbelly seems to be having problems. It is appearing and disappearing

sudo smartctl -a /dev/sg2 -d megaraid,19
Logical Unit id:      0x50000c0f01fac4fc
"Non-medium error count" is 5511 which can indicate bad seating or disk issue.

Disk should be reseated or warranty replaced.

**Comment by zerebubuth** [comment]
This is the same as #146. Closing to merge to the longer discussion there.
