### ISSUE TITLE
Prepare 2017 budget

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#132]
#131 reminds me of this.

There might be some money from the 2015 drive that is left over and would be earmarked for the OWG, but as one of the WGs with bigger expenses, it'd be a good idea to do some planning before the board asks.

**Comment by gravitystorm** [comment]
I should update this with progress - sorry for being silent on this topic.

@zerebubuth and I prepared the 2017 budget, and as usual with low/medium/high options for the Board to consider. This was reviewed by the rest of OWG and submitted to the Treasurer on 22nd January.

There is a board meeting today, on the agenda is an item to consider the whole OSMF budget. I expect we'll hear back after that what we've got.

When we get our budget approved I plan to publish it here.

**Comment by pnorman** [comment]
The treasurer has gotten back with allocations. Do you want to use this issue for next steps, or open a new one?

**Comment by gravitystorm** [comment]
For reference and for anyone who is interested, here's the OSMF Budget allocations for OWG in 2017.

| Line Item         | Allocation GBP |
| ------------- |-----:|
| Various servers     | £49,000 |
| Consultancy & Services    |    £12,000 |
| Consumables |   £4,000 |
| Hosting | £11,500 |
| Computer Insurance | £3,500|

Note that the financial year runs from the 1st January, and all allocations include VAT. Apologies for the delay in posting here.
