### ISSUE TITLE
Update Postgres to 9.6 on main database

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/operations#136]
Currently main OpenStreetMap database works on Postgres 9.1, a release dated back to 2011.

Latest Postgres release is 9.6.1. 

It got a lot of speed and feature improvements.

Some highlights:
 - jsonb datatype support, which is essentially a renewed and updated hstore, supported in core;
 - GiST indexes now handle deletions and updates better;
 - faster sorting of values using "abbreviated keys" mechanism;
 - support for more index-only scans;
 - lots of improvements in replication handling, giving more control over applying to replicas.

**Comment by tomhughes** [comment]
This is already covered by #94 which got prematurely closed.
