### ISSUE TITLE
Updates for new website

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#138]
OWG has a new website at https://operations.osmfoundation.org/ . It replaces various pages on the osmf wiki, policies previously hosted on the openstreetmap wiki, and the owg-log site.

We should ensure the previous sites are cleaned up, to reduce any confusion.

- [x] owg-log
- [x] osmf owg overview and minutes pages (I don't have access to do this)
- [x] links from openstreetmap-website codebase
- [x] policies on the osm wiki

**Comment by gravitystorm** [comment]
https://github.com/openstreetmap/openstreetmap-website/pull/1395

**Comment by lonvia** [comment]
I've replaced the usage policy pages on the wiki by links to the OWG website. There might still be some sites which link to the wiki which we might want to change. In particular, does the 'you have been blocked' tile image need an update?

**Comment by pnorman** [comment]
The wiki pages have translations. How do we want to handle them?

If we want to change the URL on the tiles, it'll need to be something short, e.g. tile.osm.org/blocked

**Comment by Tigerfell** [comment]
I suggest to move https://wiki.openstreetmap.org/wiki/Dev_Server_Account_Policy to the OWG webpage as well. https://wiki.openstreetmap.org/wiki/Dev_Server_Account is potentially also worth moving.
