### ISSUE TITLE
No OOB access to dulcy

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#139]
We don't appear to have OOB access to dulcy.

The card appears to be getting a dynamically assigned IP address rather than one in our normal IC internal range and that address appears to be firewalled so that it is unusable even from within the IC environment.

The MAC address is 0c:c4:7a:66:ce:95 and I guess we need get the network people at IC to assign a fixed address in our internal network for it.

**Comment by zerebubuth** [comment]
Looks like this was unallocated because we ran out of internal IPs. We've since removed a machine, which means we can allocate `.174` to dulcy's OOB. It looks like the IPMI card has already picked up that change, and I can ping it from ironbelly.

Thanks to the IC team for helping with this!
