### ISSUE TITLE
Add dns.git to github

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#140]
The repository at https://git.openstreetmap.org/dns.git/ isn't available on github. We've had a contributor indicate that we could have received a contribution (in the form of a pull request) if it was mirrored there. It would also allow us to have an issue tracker for that repo.

**Comment by tomhughes** [comment]
Well I'd never really bothered because it's mostly just DNS records which isn't really something anybody other than the admins will be changing.

There is a small amount of code though so I guess it might be worth doing for that.

**Comment by pnorman** [comment]
> We've had a contributor indicate that we could have received a contribution (in the form of a pull request) if it was mirrored there

I also had a contribution I wanted to make to improve the interface on dns.osm.org, and this would be easier to do with a github PR than via email.

**Comment by tomhughes** [comment]
Done - https://github.com/openstreetmap/dns.
