### ISSUE TITLE
Support trace upload on dev server rails instances

### ISSUE THREAD

**Issue by HarelM** [openstreetmap/operations#141]
I get an InternalServerError (500) when trying to upload a trace using the OSM API 0.6 to dev server.
When using the same code with the production server everything works as expected.
The error says something with rename failure on the server, according to @tomhughes the issue is that there's no storage defined for this server.
Server: http://api06.dev.openstreetmap.org/
API Call: /api/0.6/gpx/create
This prevents me from testing my code against the dev server before moving it to production.

See issue here:
https://github.com/openstreetmap/openstreetmap-website/issues/1412

**Comment by gravitystorm** [comment]
This has now been deployed, using the new [built-in trace import jobs](https://github.com/openstreetmap/openstreetmap-website/pull/2120) in the openstreetmap-website codebase, and implemented for the dev apis [in this commit](https://github.com/openstreetmap/chef/commit/fc360eb083bafd47de673a91857b0120fb36f6fa) in the chef repository.
