### ISSUE TITLE
Tiles are not available via IPv6

### ISSUE THREAD

**Issue by bekreyev** [openstreetmap/operations#142]
Please enable support Ipv6, otherwise competitors tiles (Google, Yandex) are available, but favorite OpenstreetMap - no.

Also need statistics and monitored separately via IPv4 and via IPv6, because they are two different Internet.

$ host 2a02:06b8:b010:5065:0000:0000:0000:a001
1.0.0.a.0.0.0.0.0.0.0.0.0.0.0.0.5.6.0.5.0.1.0.b.8.b.6.0.2.0.a.2.ip6.arpa domain name pointer gorynych.yandex.net.

$ ping6 2a02:06b8:b010:5065:0000:0000:0000:a001
PING6(56=40+8+8 bytes) 2a00:1138:0:2::2 —> 2a02:6b8:b010:5065::a001
16 bytes from 2a02:6b8:b010:5065::a001, icmp_seq=0 hlim=55 time=16.577 ms
16 bytes from 2a02:6b8:b010:5065::a001, icmp_seq=1 hlim=55 time=16.453 ms
^C
—- 2a02:06b8:b010:5065:0000:0000:0000:a001 ping6 statistics —-
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 16.453/16.515/16.577/0.062 ms

More IPv6 deployment measurements:
http://www.worldipv6launch.org/measurements/

**Comment by tomhughes** [comment]
We are unable to offer this at present because our CDN relies on squid 2 which doesn't support IPv6 unfortunately.

At some point we hope to move to varnish at which time those nodes in our CDN which support IPv6 will have it enabled as a matter of course - we always enable IPv6 where we have it available and the software we are using supports it.

**Comment by Komzpa** [comment]
Can it be provided the same way the https is provided - by making a local nginx listen to the port and forward the request to squid?

**Comment by mtmail** [comment]
Answering my own question, here's a link to the existing ticket about switching to varnish https://github.com/openstreetmap/operations/issues/7
