### ISSUE TITLE
Reduce maximum changeset size to 10k changes

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#144]
This ticket is intended to be a central place to discuss the possibility of reducing the maximum changeset size to 10k changes. The Data Working Group is having more and more problems dealing with large changesets.

The [website pull request](https://github.com/openstreetmap/openstreetmap-website/pull/1259) is uncontroversial, however [TomH (rightly) doesn't want to take the decision by himself](https://github.com/openstreetmap/openstreetmap-website/pull/1259#issuecomment-276432222).

We don't have guidelines for how to decide on this kind of pull requests, but we have guidelines on community approval for automated edits and imports, which I'll adapt here. I will publicise this ticket over the usual mailing lists, irc channels, forums and weeklyosm, and if there is no negative feedback from the community after two weeks, would suggest that we merge this.

**Comment by tomhughes** [comment]
Is one interminable thread not enough?

**Comment by tomhughes** [comment]
As people are apparently just going to bang on until I do this I've merged it. I will refer complaints to you.

**Comment by grischard** [comment]
Thank you.

**Comment by DenisCarriere** [comment]
No complaints on this type of change, I think it's a great way to limit any OSM API abuse.
👍

**Comment by Firefishy** [comment]
Note to future readers of this ticket, many editor apps already honor the api capabilities API call. https://wiki.openstreetmap.org/wiki/API_v0.6#Capabilities:_GET_.2Fapi.2Fcapabilities

**Comment by zerebubuth** [comment]
> if there is no negative feedback from the community after two weeks, would suggest that we merge this.

That sounds good. Thanks very much for your work on this, @grischard.
