### ISSUE TITLE
arcconf regularly hangs on pummelzacken

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/operations#147]
chef regularly hangs on pummelzacken. The reason is a hanging arcconf process which seems to be waiting on another arcconf process that has deadlocked. I'm not sure where that other arcconf comes from, it doesn't have any parent that could be an obvious caller.

**Comment by tomhughes** [comment]
Well they come from a mixture of chef and the regular RAID status checks I think?

**Comment by pnorman** [comment]
@lonvia, is this still an issue on pummelzacken? I know we've had changes to servers over the last couple years so I'm not sure if it's running the same hardware anymore.

**Comment by lonvia** [comment]
I haven't noticed the issue in a while. I think we changed the RAID controller but I'm not quite sure. In any case, closing now. I'll reopen the ticket if I see it again.
