### ISSUE TITLE
plugin for join.osmfoundation.org wiki

### ISSUE THREAD

**Issue by datendelphin** [openstreetmap/operations#148]
Hi

We would like to get a plug in installed on the join.osmfoundation.org wiki, in order to provide a form which will be sent as a mail to membership@… when the user submits it (instead of the google form ​https://docs.google.com/forms/d/e/1FAIpQLSc0th2KpV2R2mcKZiKPRFH_GVEl12aepf7eYQER9BqFPZtHWA/viewform)

I have experience with the following plug-in ​http://www.campbellhoffman.com/form-manager/ which we use for the Swiss OSM association here: ​http://sosm.ch/membership/ and would suggest to install this one.

By he way, civicrm needs an update.

Thank you
Michael

**Comment by datendelphin** [comment]
Just read the comment from TomH:

>  I've updated civicrm to 4.6.26 (the latest LTS version) as I'm unsure whether there might be any issue going to a 4.7 release.
> 
> I have to say I'm not inclined to install that wordpress plugin - a plugin from some random web site that doesn't seem to be listed in the official plugin directory doesn't fill me with confidence. I know there is a link to the official directory but it's broken and I can't find it with a search.

I will search for a better plugin

**Comment by datendelphin** [comment]
I tried following plugin, which seems to be currently maintained:
https://wordpress.org/plugins-wp/contact-form-7/
Would that be acceptable?

**Comment by tomhughes** [comment]
Sure - that should be installed now.
