### ISSUE TITLE
Move eustace to a G6

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#15]
Grant ran out of time for this last time he was at UCL but it's still on the list of things to do.

**Comment by zerebubuth** [comment]
I tried cloning the disks yesterday with [clonezilla](http://clonezilla.org), which cloned really well but seemed to have issues restoring to a different disk than it cloned from. The G4ps have their RAID array at `/dev/cciss/cNdNpN` whereas the G6 has its at the more normal `/dev/sdaN`. Clonezilla attempts to "convert" the cloned image, but something goes a bit wrong later in the process and it bails.

Not sure what to do about this - could have another go, or try a different bit of cloning software. Anyone have any recommendations?

**Comment by Firefishy** [comment]
This script seems to be able to fix the device names in the image.
https://github.com/stevenshiau/clonezilla/blob/master/sbin/cnvt-ocs-dev

**Comment by tomhughes** [comment]
I think we may know the author of that script as well ;-)

**Comment by zerebubuth** [comment]
All done - using `partimage` alone seemed to do the trick. The machine is now up as a G6.
