### ISSUE TITLE
wiki search currently broken

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/operations#151]
Search on the wiki is currently broken. Seems like no search results are appearing   (_"There were no results matching the query"_)  Only exact page/redirect name matching is working

**Comment by tomhughes** [comment]
I believe you've already been told that the indexes are in the process of being rebuilt!

**Comment by tomhughes** [comment]
@Firefishy says the reindex apparently failed...

**Comment by tomhughes** [comment]
There was a page which was timing out trying to syntax highlight a complex BAT file... I've temporarily changed it and started the reindex again.

**Comment by tomhughes** [comment]
The rebuild didn't seem to help so I recreated the indexes completely and am now rebuilding again and results are starting to appear - about 10% of pages have been done so far.

**Comment by tomhughes** [comment]
Indexing is complete and search appears to be working OK now.
