### ISSUE TITLE
Missing GPS trace import notification emails 

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/operations#153]
I got emails after uploading a GPS trace. 
Since a few days I don't get this emails anymore. I checked my spam folder. 
Was there a breaking change?

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/eccb2fd351faa65302c80a86f5ba6798ecd0d90c.

**Comment by HolgerJeromin** [comment]
My trace two hours ago did not triggered an email... :-(

**Comment by tomhughes** [comment]
Not sure what was going on but it seems to be working now after a restart.

**Comment by HolgerJeromin** [comment]
Yes. Works. Thanks
