### ISSUE TITLE
Replacement for dmca.openstreetmap.org

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#155]
The server hosting dmca.openstreetmap.org is going-away during April 2017.
For historical reasons the site is hosted on a VM owned by @Firefishy

The site currently uses code which requires a very old version of PHP and some deprecated PEAR libraries. Here is a gist: https://gist.github.com/Firefishy/fa4f787130cc5a420ffe39378bc3be78

**Comment by Firefishy** [comment]
Whatever replaces the site can likely be hosted on ridley.

**Comment by pnorman** [comment]
It's been suggested to make use of the OSMF wordpress instance and set up a form on there.

If that doesn't work, just having a static page explaining what to email would be tolerable.

**Comment by slachiewicz** [comment]
Maybe replace with Google Forms https://www.google.com/forms/about/ ?

**Comment by pnorman** [comment]
We can't use Google Forms if there are open-source alternatives.

**Comment by grinapo** [comment]
(I am using LimeSurvey for various forms; it's a pretty heavywight tool but can be used for reeeeally simple forms as well, and the output is available in various formats. Installation is quite simple, too. https://github.com/LimeSurvey/LimeSurvey  )

**Comment by pnorman** [comment]
The output format we need is email.

Another idea that occurs to me is seeing if there's a way to do a form that feeds into OTRS, automatically filling out the necessary fields.

**Comment by grischard** [comment]
It looks like it's not too difficult to have a custom form for OTRS: http://forums.otterhub.org/viewtopic.php?t=30039

**Comment by pnorman** [comment]
We've moved dmca to osmf hardware: https://github.com/openstreetmap/chef/blob/db60e8c86c11b04555fc2a0b6b3775ddc1ac47a5/roles/ridley.rb#L79

A custom form would still be a good idea imo, but that's up to the DWG.
