### ISSUE TITLE
building visible for some users, not visible for others

### ISSUE THREAD

**Issue by polarbearing** [openstreetmap/operations#156]
Following a complaint on the tagging list, I filed gravitystorm/openstreetmap-carto#2611, however it seems more a caching issue than a style bug. We already traced that different cache servers are being used. 

@mboeringa can see it via cache server 'trogdor', I cannot via cache server 'kalessin'.

**Comment by tomhughes** [comment]
Different caches will expire at different times to this is pretty much just as expected.

**Comment by polarbearing** [comment]
The question is why an object that was last touched a year ago, is visible for some people and some not, in the first place.

**Comment by tomhughes** [comment]
I have no idea and we don't really have the resources to investigate individual rendering discrepancies.

I can tell you that one of the three render servers is missing that building, and I've been trying to rerender the tile but the machine is too busy currently.

**Comment by tomhughes** [comment]
Simple answer is that the database on orm doesn't have that object - no way to tell why at this point though. Most likely it's just an unlucky coincidence.

It will fix itself next time the database is reloaded.

**Comment by polarbearing** [comment]
> It will fix itself

Thanks Tom, that's what I wanted to hear :-)
