### ISSUE TITLE
taginfo-server ipv6

### ISSUE THREAD

**Issue by joto** [openstreetmap/operations#157]
I got a request by email to support IPv6 for taginfo.openstreetmap.org. I don't think there is anything special I can do. This is something that needs to be done in kernel/apache.

**Comment by tomhughes** [comment]
As a matter of policy we enable IPv6 whenever we have it available and the software supports it.

In the case of taginfo the software is fine, and one of the two servers has IPv6 but the other one does not because the data centre where it is hosted doesn't provide it.
