### ISSUE TITLE
Sort out OOB access to ouroboros

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#16]
It seems that OOB access to ouroboros isn't working - suspect IC have the wrong MAC address or something as it is getting a 172.20 address from DHCP and statically setting the correct address doesn't work either so it is likely on the wrong VLAN as well.

**Comment by tomhughes** [comment]
Did IC ever get back to you on this @zerebubuth?

**Comment by tomhughes** [comment]
If IC are claiming to have updated the database then there is some other problem because it is still not getting an address by DHCP and configuring a static address doesn't work either.

**Comment by Firefishy** [comment]
hponcfg reports iLO port speed of 10Mb/s which normally indicates it is unplugged. Will try to remember to check while I am there tomorrow.

**Comment by tomhughes** [comment]
This seems to be resolved now.
