### ISSUE TITLE
Increase Mediawiki Session Timeout

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/operations#164]
The session timeout in Mediawiki seems to be the default which is too short. After the timeout you have to re-login.

It seems that this issue was introduced with the last major Mediawiki upgrade on the OSM servers. The timeout was much higher before that upgrade.

On my Mediawiki instances, I replace in `/etc/php5/apache/php.ini` `session.gc_maxlifetime = 1440` by `session.gc_maxlifetime = 7200`. After this change users of my instances stopped complaining. :-)

**Comment by tomhughes** [comment]
Well I don't see how a mediawiki upgrade could have changed that value so that sounds like a misdiagnosis.

Does mediawiki rely leave this to PHP and not manage the lifetime itself? I mean I'm logged in right now and I can't remember how long I've been logged in but it must be days if not weeks.

**Comment by Nakaner** [comment]
The issue came up around the time when you did the last major Mediawiki upgrade (the one which Verdy_p complained about because some stuff did not work anymore after the upgrade).

I don't activate the checkbox "Keep me logged in" at the login form.

**Comment by mmd-osm** [comment]
@Tigerfell: could you take a quick look if this is still relevant? Thanks!

**Comment by pnorman** [comment]
If this is still relevant, please have a wiki admin comment or open a ticket for ops.
