### ISSUE TITLE
fix page on sotm.org

### ISSUE THREAD

**Issue by althio** [openstreetmap/operations#166]
http://sotm.org/ is a registered domain to OSM/Grant Slater.

Now it shows a "Apache2 Ubuntu Default Page".
Could it be updated or redirected to another meaningful page? eg. https://stateofthemap.org/

cc @RobJN
ref https://github.com/osmfoundation/sotm2017/issues/98#issuecomment-316835930

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/a704f4b2d2279800b5b5ebe44e347510463731e6.

**Comment by althio** [comment]
Wonderful, thanks @tomhughes 👍
