### ISSUE TITLE
gorynych server is unstable

### ISSUE THREAD

**Issue by dbf256** [openstreetmap/operations#167]
Hi, if this place is not a valid to report such issues or you are already aware of this problem, please close this ticket.

Russian OSM users have issues with tiles because of unstable gorynych tile server, error 500 is returned from time to time with such text:

> ERROR
> The requested URL could not be retrieved
> 
> The following error was encountered while trying to retrieve the URL: http://tile.openstreetmap.org/
> 
>     Socket Failure
> 
> The system returned: (98) Address already in use
> 
> Squid is unable to create a TCP socket, presumably due to excessive load. Please retry your request.
> 
> Your cache administrator is webmaster@openstreetmap.org.
> 
> Generated Mon, 24 Jul 2017 20:37:17 GMT by gorynych.openstreetmap.org (squid/2.7.STABLE9)

Thanks in advance.

**Comment by tomhughes** [comment]
I expect the scrapers I blocked last week have moved to new IP addresses.

I'll have a look when I've got time but chances are they'll just move again - it's a bit of a game of whack-a-mole I'm afraid.

**Comment by Zverik** [comment]
Is there anything to identify these scrapers? Maybe we could contact them.

**Comment by tomhughes** [comment]
Yep, looks like they had shifted to the adjacent address. I've blocked that now and as you can see from https://munin.openstreetmap.org/openstreetmap/gorynych.openstreetmap/fw_conntrack.html it has had a dramatic effect on the number of open connections...

**Comment by Zverik** [comment]
Awesome, thanks Tom!

**Comment by Zverik** [comment]
Looks like they are back: https://munin.openstreetmap.org/openstreetmap/cmok.openstreetmap/fw_conntrack.html

**Comment by tomhughes** [comment]
I'm not actually sure it is the same. I thought it was to start with, but it looks like it might be a broken DNS resolver instead.
