### ISSUE TITLE
Download tiles attack on the cmok server

### ISSUE THREAD

**Issue by gardster** [openstreetmap/operations#168]
Suddenly increased connections amount to the `cmok` server
https://munin.openstreetmap.org/static/dynazoom.html?plugin_name=openstreetmap%2Fcmok.openstreetmap%2Ffw_conntrack&start_iso8601=2017-07-14T15%3A28%3A55%2B0300&stop_iso8601=2017-07-25T15%3A27%3A11%2B0300&start_epoch=1500035335&stop_epoch=1500985631.05&lower_limit=&upper_limit=&size_x=800&size_y=400&cgiurl_graph=%2Fmunin-cgi%2Fmunin-cgi-graph

Seems similar with yesterday's situation with the `gorynych` server.

cc @tomhughes

**Comment by tomhughes** [comment]
Two reports is quite enough, we don't need a third.
