### ISSUE TITLE
Planet osm redirects to non-existent files on ftp.heanet.ie mirror 

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#171]
Not sure where to address this issue. All old planet files dating back to 2016 and earlier are no longer available via ftp.heanet.ie. Example:

http://planet.openstreetmap.org/planet/2012/planet-120912.osm.bz2

redirects to:

http://ftp.heanet.ie/mirrors/openstreetmap.org/planet/2012/planet-120912.osm.bz2

which no longer exists.

This issue was initially reported on Help OSM: https://help.openstreetmap.org/questions/58326/urls-to-download-old-planetosm-files-are-not-working

**Comment by Firefishy** [comment]
Fixed now.

**Comment by stvno** [comment]
The same happens to 2017 planet files now:

https://planet.openstreetmap.org/planet/2017/planet-171009.osm.bz2 

redirects to the non-existing 

http://ftp.heanet.ie/mirrors/openstreetmap.org/planet/2017/planet-171009.osm.bz2

**Comment by mmd-osm** [comment]
Seems like heanet.ie had some severe issues recently and stopped mirroring OSM for the time being: https://ticketing.heanet.ie/public/show.html?id=1312119

**Comment by stvno** [comment]
The same happens to 2017 planet files now:

https://planet.openstreetmap.org/planet/2017/planet-171009.osm.bz2 

redirects to the non-existing 

http://ftp.heanet.ie/mirrors/openstreetmap.org/planet/2017/planet-171009.osm.bz2
