### ISSUE TITLE
Visual editor does not save alt texts for images

### ISSUE THREAD

**Issue by rugk** [openstreetmap/operations#172]
In the visual editor alt-texts are not saved and I notice some things not being up-to-date with Wikipedia sites.

I think updating the wiki software might solve this problem. Or at least, tackle the "visual editor alt-text" problem.

**Comment by Firefishy** [comment]
Most likely this is because you are a new user and are trying to add a URL, the anti-spam is catching you out. Any luck recently?

**Comment by rugk** [comment]
I think in such a case and error would be shown. Also it worked in the source code mode.

**Comment by tomhughes** [comment]
Mediawiki has been updated to 1.29.2 if you want to retest this.

**Comment by rugk** [comment]
The Visual Editor is still broken, it does save the alt text here.

**Comment by rugk** [comment]
BTW even when showing the image properties, the alt text is never shown, already.

You can test it here: https://wiki.openstreetmap.org/wiki/StreetComplete/Quests

**Comment by Tigerfell** [comment]
It looks to me like a problem with Visual Editor, so I reported it at https://phabricator.wikimedia.org/T216285. 
I also documented this edit https://wiki.openstreetmap.org/w/index.php?title=Sandbox&type=revision&diff=1791566&oldid=1791564. I hope it is the same problem.

**Comment by rugk** [comment]
That said, I never saw/could reproduce this on any Wikipedia/Wikimedia site…

**Comment by rugk** [comment]
It looks like upstream solved the issue: https://phabricator.wikimedia.org/T216285

I am leaving this open here though, so the new version can be deployed and the fix can be verified.

**Comment by mmd-osm** [comment]
@rugk : @Tigerfell : is this still relevant, or can this be closed by now?

**Comment by rugk** [comment]
Upstream seems to be fixed, so closing this.
