### ISSUE TITLE
Cannot find images uploaded in the OSM wiki in visual editor

### ISSUE THREAD

**Issue by rugk** [openstreetmap/operations#173]
When I upload an image as usual and then try to use it in the use the visual editor, it won't appear, even if I enter the exact file name I give it.

The visual editors, however:
* allows me to upload and embed new images directly
* notices when I want to upload a duplicate of the image

**Comment by tomhughes** [comment]
It looks like this might be working now - can you confirm if it's still a problem for you?

**Comment by rugk** [comment]
Yeah, for some reason seems to work… :thinking:
