### ISSUE TITLE
Filter DMCA emails

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#174]
With the current spam flood we really need to filter the DMCA form server side to take out the 1 source of 99% the spam. Just filtering in the PHP form based on sender's email would be sufficient for this.

As far as I can tell, it needs to be done on our side, not Google.

**Comment by tomhughes** [comment]
Do those emails actually pass through our infrastructure? If they do then they should be getting our standard filtering and if they don't then there's not much we can do...

**Comment by pnorman** [comment]
> Do those emails actually pass through our infrastructure?

Yes, they're coming from us, triggered by someone pressing submit on dmca.openstreetmap.org

**Comment by tomhughes** [comment]
Right, but the email never passes through us, which is what I meant - that form sends email to an osmfoundation address I think, not not an openstreetmap address?

**Comment by tomhughes** [comment]
In any case most of the spam protection we have wouldn't work for a form like that because it has no idea of the real source - you'd really only get things like the bayesian filter in spamassassin and that isn't much use.

**Comment by pnorman** [comment]
> Right, but the email never passes through us, which is what I meant - that form sends email to an osmfoundation address I think, not not an openstreetmap address?

It's coming from our PHP script. The mail server is pearl.firefishy.com, for reasons related to #155.

> you'd really only get things like the bayesian filter in spamassassin and that isn't much use.

Filtering out submissions where the URL is in a couple of values is enough of a spam filter. This is not sophisticated spam.
