### ISSUE TITLE
www.openstreetmap.org uses an invalid security certificate.

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#176]
>  The certificate expired on October 12, 2017, 8:05 PM. The current time is October 12, 2017, 8:13 PM. 

> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

https://gist.github.com/matkoniecz/adfee99da2d308507ac738fbe75991f4

**Comment by tomhughes** [comment]
Already fixed.
