### ISSUE TITLE
Predicted disk fail on katla

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#177]
Smartd says:

```
Device: /dev/sg2 [megaraid_disk_21], SMART Failure: FAILURE PREDICTION THRESHOLD EXCEEDED: ascq=0x5

Device info:
[SEAGATE  ST900MM0026      0003], 900 GB
```

**Comment by Firefishy** [comment]
Disk is under warranty until 18-Jan-2018. (5 year)

**Comment by tomhughes** [comment]
Is that in the sdb array? ie the one that's going to run out of space any day now...

**Comment by Firefishy** [comment]
Yes, this was in the array that was running out of disk space, resolved in: https://github.com/openstreetmap/operations/issues/185

**Comment by zerebubuth** [comment]
The SMART failed disk was pulled yesterday, and the array has been rebuilt. The failed disk is being RMA'd, so we'll have to hope it scrapes in under the warranty deadline.

**Comment by zerebubuth** [comment]
Array was rebuilt, and everything looks good. Many thanks to the support team at [Bytemark](https://bytemark.co.uk) for their help.
