### ISSUE TITLE
Failed disk in pummelzacken

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#178]
A disk in pummelzacken appears to have failed - it's a 1Tb Seagate ST91000640NS currently at /dev/sdc and it has been booted out of the RAID and is not responding to SMART queries.

**Comment by lonvia** [comment]
Not sure it is worth replacing those. /dev/sda1, which is currently mounted on /data, is completely unused an can serve as root FS instead. /dev/sdb1 is sufficient for the Nominatim database.

pummelzacken is currently running as cold spare, so disk rearrangements can be done at any time.

**Comment by Firefishy** [comment]
Replaced disk with a cheap WDC Red 1TB 2.5". Rebuilding.
