### ISSUE TITLE
OSM wiki dump is not available

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#179]
I wanted to download OSM wiki dump for backup purposes (I expected it to be fairly small), but discovered that it is documented as broken at https://wiki.openstreetmap.org/wiki/Wiki with no useful discussion at https://wiki.openstreetmap.org/wiki/Talk:Wiki#wiki_dump

>  http://dump.wiki.openstreetmap.org/ ...but in year 2015 and currently (2016) offline. Worked in 2010 and 2013.

Is it available elsewhere? Is OSM wiki backuped?

**Comment by tomhughes** [comment]
Yes it is backed up.

**Comment by mmd-osm** [comment]
@tomhughes : are there any plans to make the Wiki dump available for public download again?

**Comment by tomhughes** [comment]
The dump and the backup are different things. The dump is nothing to do with me.

**Comment by mmd-osm** [comment]
The reason I'm asking is because there seems to be a `dump.wiki.openstreetmap.org` site configured in chef, which is somehow defunct. Is this something @Firefishy could look into?

https://github.com/openstreetmap/chef/blob/master/cookbooks/wiki/recipes/default.rb#L84

**Comment by Stunkymonkey** [comment]
any updates on this?

**Comment by matkoniecz** [comment]
> The dump is nothing to do with me.

@tomhughes Do you know who handles wiki? Or is it case of "nobody is doing this, you can start fixing if you really want wiki to keep working"?

**Comment by roxanadangerm** [comment]
Is there any updates on this? 
If not I would be happy to help on setting up the wiki dump again.
Many thanks in advance

**Comment by pnorman** [comment]
There are dumps at https://wiki.openstreetmap.org/dump/, so this issue is out-dated.
