### ISSUE TITLE
Improve planet mirror redirect code

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#18]
Currently the planet-mirror-redirect-update is a very simplistic script which checks if an identically sized planet.osm or changesets.osm exists at ftp.heanet.ie, if it does it adds the file to a .htaccess redirect rule.

We should investigate alternatives:
- https://github.com/rgeissert/http-redirector (debian redirector)
- http://mirrorbrain.org/ (requires apache module, intrusive)
- https://github.com/mozilla/tuxedo

**Comment by tomhughes** [comment]
https://fedorahosted.org/mirrormanager/ is another option (it's what Fedora uses to manage it's mirrors).

**Comment by pnorman** [comment]
Closing since we're not using the script at all. If we get a new mirror we redirect to we'll have to revisit it.
