### ISSUE TITLE
Planet file retention policy

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#180]
We have a recurring problem with the [disk on ironbelly filling up](https://munin.openstreetmap.org/openstreetmap/ironbelly.openstreetmap/df.html):

![image](https://user-images.githubusercontent.com/271360/33016175-5f35e7be-cde5-11e7-83f3-da93e2f47706.png)

This is largely down to the storage of planet files (16TB total) and logs (7.7TB). The vast majority of both logs and planet files are old (2% of space used is for the last 3 planets, 76% is for planets from before 2017).

Old planet files can be useful for historical spelunking, but very few people actually do so (94% of requests in the last 10 weeks were for planets generated within the same period). A close approximation to an old planet can be obtained using [`osmium-tool`'s `time-filter` command](http://osmcode.org/osmium-tool/manual.html#working-with-history-files), which can recover a point-in-time planet from the full history. Recovering several planet files in this way would likely be significantly faster than downloading the older planet files, on most internet connections. A possible downside is that there isn't enough information in the history file to recover the transactional state of the database, so timestamps alone might produce a planet which doesn't have referential integrity. If one is spelunking in older planets, this is something that one would have to be robust against anyway.

Another issue with old planet files is that they preserve data which has since been redacted, which really shouldn't be available anyway.

I think we should have a policy for the number of old planets we keep around - or perhaps generate them on-demand using `osmium-tool` from the most recent history file. Here's a starting place:

1. Keep all the "before current era" planet files, i.e: all the CC-BY-SA ones.
2. Keep the last 3 good planet files.
3. Regenerate a planet file for the 1st of each month using `osmium-tool` (possibly on-demand?)

How does that sound?

**Comment by Zverik** [comment]
I suggest keeping one planet file for each month before 2012-09-12 and one planet file for each year after that, plus three latest planet files as you suggest.

Do we have a CC-BY-SA full history extract?

**Comment by imagico** [comment]
Reducing the number of historic planet files readily available for download seems fine to me but i wanted to make sure that removing them would not mean historical data contained in there is lost forever.  I think the importance of the OpenStreetMap project warrants that the history of its data *including what has been redacted* is preserved for future generations.  If there is already a separate archive storage or if the data including what has been redacted is already stored otherwise in more compact form that point would be moot of course.

**Comment by iandees** [comment]
It makes sense to thin out the historical/old planet files (but not completely delete them). Can I suggest that we upload the older planet files to archive.org before we delete them? I'm sure [the AWS Public Datasets team](https://aws.amazon.com/public-datasets/osm/) would be happy to host the historical planet files, too.

**Comment by zerebubuth** [comment]
> Do we have a CC-BY-SA full history extract?

Yes. There are [two on the planet server](http://planet.openstreetmap.org/cc-by-sa/full-experimental/), one of which is named "final", and the other is two months later (?!). I'm not totally sure which would have been the final one before the license change, but the one dated in June is probably it.

> I think the importance of the OpenStreetMap project warrants that the history of its data including what has been redacted is preserved for future generations.

Yes, the redacted data is preserved in the database and database backups. Apologies - I should have been clearer in saying that I think continuing to distribute (via planet files) the redacted data is the problem. Continuing to keep it privately and internally until the copyright expires doesn't seem like a problem.

> Can I suggest that we upload the older planet files to archive.org before we delete them?

I think that any planet file containing redacted data is a potential legal liability. I wouldn't want to foist that onto archive.org or anyone else.

**Comment by imagico** [comment]
> Yes, the redacted data is preserved in the database and database backups.

Then i have no objection.  The most likely future use case for such data would be research - for such it would of course be convenient if the data was publicly available but the legal issues and ultimately the interests of those whose rights might be violated by this data stand above this aspect of convenience.

**Comment by Zverik** [comment]
Maybe just keep the first planet file for each month, for a start? This does not solve the issue long-term, but we will have a couple more years to think of a solution.

**Comment by HolgerJeromin** [comment]
Do anyone needs minute diffs from 2012?

http://planet.openstreetmap.org/cc-by-sa/minute-replicate/001/172/

**Comment by Zverik** [comment]
Yes, minute diffs are important and irreplaceable. And they don't take much space.

**Comment by HolgerJeromin** [comment]
Ok, i thought a BY-SA consumer will use the last (full-history?) planet for all he wants.

**Comment by pnorman** [comment]
> Yes. There are two on the planet server, one of which is named "final", and the other is two months later (?!). I'm not totally sure which would have been the final one before the license change, but the one dated in June is probably it.

Final is from before redactions started. The other is post-redaction, but pre-license change.

I'd recommend making the last 4 weeks available, as well as every month (4 weeks) for the last year, then every 6 months.
I'm not sure what to do with history files, as I don't use them. I imagine there is very little use for old history files.

Files we remove should be archived to offline storage.

Regarding redacted data, we should not be considering it when planning this. If it weren't technically difficult, it would be better to remove any redacted data from all planet files, since we can't distribute it.

**Comment by mmd-osm** [comment]
> A close approximation to an old planet can be obtained using osmium-tool's time-filter command, which can recover a point-in-time planet from the full history

> Regarding redacted data, we should not be considering it when planning this. If it weren't technically difficult, it would be better to remove any redacted data from all planet files, since we can't distribute it.

Regenerating previous planet files based on current full history files along with redaction has the downside that older versions of an object (which haven't been redacted) still "shine through", and will be used by osmiums time filter. This can cause quite a bit of havoc with object geometries. 

While this is a bit off topic for this issue, creating full history files should - rather than just skipping redacted versions - at least contain a dummy marker including object id, version, an exact timestamp of the original object, and an information that this version has been redacted.

**Comment by hbogner** [comment]
I'm one of those people who uses(or at least used) older planet files for history processing.
There are still people who don't know how to process full history planet file and would like to access OSM history.
Is there really no slot for additional disk in the server?

**Comment by tomhughes** [comment]
It already has 12 x 4Tb disks - how many more should we be prepared to add for your convenience?

Note that it's not really one server as the goal is to actually have this in at least two and probably three places for redundancy. Right now our second site has a machine with 12 x 2Tb disks though the two aren't quite equivalent.

**Comment by hbogner** [comment]
I was just asking, not judging or ordering, just curiosity. 

Also few years ago I asked does OSM need any more servers in Croatia because we could host them here(one or maybe two locations), but there was no need then.

**Comment by zerebubuth** [comment]
> There are still people who don't know how to process full history planet file and would like to access OSM history.

What could be done to make it easier? It seems like it would be possible to write a server to do a point-in-time reconstruction of a planet file, streamed from [`osmium-tool time-filter`](http://osmcode.org/osmium-tool/manual.html#working-with-history-files), since it works in a single pass. Would that remove the need to store the individual old planet files?

> Is there really no slot for additional disk in the server?

The space on disk was the proximate reason for adding this issue, since running out of space on disk causes all kinds of bad things to happen. For the reasons @tomhughes already said, maintaining a really high capacity, resilient storage is a pain. We're working on an approach #169 which should make that easier, and any help with that would be appreciated.

I think there's a bigger issue; old planet files can contain data that we no longer want to redistribute, such as data copied from other maps that has since been redacted. I can't think of a feasible way to edit those redactions out of old planet files, and I think a better way would be to rely on the up-to-date "history" planets for historical information.

**Comment by Zverik** [comment]
I assume we're talking about keeping less of older planet files, not removing them altogether.

**Comment by mmd-osm** [comment]
> It seems like it would be possible to write a server to do a point-in-time reconstruction of a planet file

In theory yes. However there are issues with redactions in that file, i.e. versions before a redaction "shine through". Please see my comment above https://github.com/openstreetmap/operations/issues/180#issuecomment-346447888

**Comment by zerebubuth** [comment]
> I assume we're talking about keeping less of older planet files, not removing them altogether.

That's the easiest thing to do, short term, and it seems that there's reasonably broad support for keeping one per month. It would still be relatively easy (although harder than just downloading the file) to recover other weeks by applying diffs to the monthly files.

Long term (and I think I've gone a little off-topic, sorry), I'd prefer not publicly distributing old files apart from a small number of snapshots before and after the license change, and older planets of historical interest.

I think this issue is clear - we can trim down to one a month. I should file a follow-up for the remaining issues blocking a more thorough and legally defensible approach, as @mmd-osm pointed out in https://github.com/openstreetmap/operations/issues/180#issuecomment-346447888.

**Comment by Firefishy** [comment]
I assume this can be closed now?

**Comment by tomhughes** [comment]
Did it actually get switched to live mode?

**Comment by tomhughes** [comment]
No, it's still in debug mode.

**Comment by zerebubuth** [comment]
Good point. Seems to have been working well for the past few months. We can turn debug off - or even just close the issue. I don't mind getting the monthly reminder of what got deleted.

**Comment by tomhughes** [comment]
So it is actually deleting now then?

**Comment by zerebubuth** [comment]
Yup, it got enabled back in April: https://github.com/openstreetmap/chef/pull/157

![image](https://user-images.githubusercontent.com/271360/45780723-13312f80-bc56-11e8-8953-a054d85b28bc.png)

It's hard to see whether the rate of growth has really slowed, though. Perhaps we've simply found space for other stuff to accumulate...

**Comment by pnorman** [comment]
The planet files have been thinned out
