### ISSUE TITLE
Ironbelly Disk Failing

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#183]
```
The following warning/error was logged by the smartd daemon:

Device: /dev/sg2 [megaraid_disk_14], SMART Failure: HARDWARE IMPENDING FAILURE TOO MANY BLOCK REASSIGNS

Device info:
[WD       WD4001FYYG-01SL3 VR02], lu id: 0x50000c0f01c47d2c, S/N: WMC1F0627275, 4.00 TB
```

**Comment by Firefishy** [comment]
2x Seagate ST4000NM0125 has been purchased.

**Comment by Zverik** [comment]
Thanks Grant.

**Comment by zerebubuth** [comment]
Failing disk replaced. New disk installed. This fills the final bay in ironbelly - if we want to increase capacity further in the same chassis, we'll need to upgrade all the disks.

@Firefishy do we want/have a follow-up issue for resizing the array, or should we leave this open to represent that?

**Comment by Firefishy** [comment]
@zerebubuth Rebuild onto hotspare done. Likely best to keep open until grow done.

I have started the grow to add the extra disk. To watch progress: `sudo megacli LDRecon -ShowProg -l0 -a0` or to set rate (to 10%): `sudo megacli -AdpSetProp RebuildRate 10 -a0`

**Comment by Firefishy** [comment]
Finished rebuild and grow. Filesystem expanded. Close this issue but another disk is failing see https://github.com/openstreetmap/operations/issues/188
