### ISSUE TITLE
Recreate disk array on katla as RAID6

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#185]
The `/dev/sda1` aka `/store/arrays/fast` is currently a hardware LSI RAID10 array and is very near capacity. The RAID controller does not support migrating or growing RAID10 arrays.

We should rebuild the array as a RAID6.

1) We'd need to backup / delete all data.
2) Remove the array
3) Create new array as RAID6
4) Restore.

**Comment by tomhughes** [comment]
Sounds like a plan to be - drop the database and reformat then run a new base backup.

Suggest we also move the SSD data from /store/arrays/ssd to that partition at the same time as the SSDs are also going to fill up soon.

We'll have to point the bytemark servers (which aren't actually taking any load) at karm or eddie while katla is rebuilt.

**Comment by tomhughes** [comment]
Query load from bytemark has been moved to eddie and chef and postgres have been stopped on katla so we should be good to go on recreating the array.

**Comment by Firefishy** [comment]
The array was rebuilt as RAID6 and postgresql re-synced.
