### ISSUE TITLE
Is it OK to use /api/0.6/notes/search with large limits?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#189]
I am not sure whatever in https://github.com/ENT8R/NotesReview/issues/1 I worry without a good reason or is it a good idea to reduce default limit to avoid overloading API.

I am also not certain is it the best place to ask, but I was unaware about a better one.

**Comment by zerebubuth** [comment]
10,000 does seem like a lot! But that's the [limit set in the source code](https://github.com/openstreetmap/openstreetmap-website/blob/9340c461732ef7387dd453ea3fcf5e64ea782ab4/app/controllers/notes_controller.rb#L310), and I've no reason to expect it wouldn't be OK.

Perhaps give it at a go against the [development / testing server](https://master.apis.dev.openstreetmap.org) and see if it has acceptable performance there? If we see that there are problems, we might need to reduce it at a later date.

**Comment by matkoniecz** [comment]
> Perhaps give it at a go against the development / testing server and see if it has acceptable performance there?

Is my interpretation "development / testing server has lower performance and potential problems will be easier to notice, queries with decent performance on dev server are likely to not use too many resources" correct?

**Comment by zerebubuth** [comment]
> Is my interpretation "development / testing server has lower performance and potential problems will be easier to notice, queries with decent performance on dev server are likely to not use too many resources" correct?

It's certainly the case that if the performance is _terrible_ then we'll notice it on the dev server, and might be able to fix it before hurting the main production site.

But it's not always the case that things which run well on the dev server will run well on the production site, as the dev server has a tiny fraction of the data that the production site has, and runs on completely different hardware. But the good news is that we can try and fake it by adding a whole bunch of notes on the dev server to test how it scales.

Another possibility is that we could add a better interface for dealing with note data in bulk. Would a "note changes stream" similar to the minutely diffs be useful?

**Comment by pnorman** [comment]
> Another possibility is that we could add a better interface for dealing with note data in bulk. Would a "note changes stream" similar to the minutely diffs be useful?

Yes. People currently fake this by fetching note n+1 and pausing when it fails, but this is hackish, fails when the `serial` goes up by more than one, and isn't a great design.

I don't know if a notes stream helps this particular use-case, but there are others it would.

**Comment by pnorman** [comment]
Question was answered, and although a new notes change stream would be nice, this issue isn't the right place for that to develop.
