### ISSUE TITLE
Redirect to heanet for /pbf like /planet

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#191]
Planet files in http://planet.openstreetmap.org/planet/2018/ redirect to the heanet mirror, e.g. http://planet.openstreetmap.org/planet/2018/planet-180101.osm.bz2 to http://ftp.heanet.ie/mirrors/openstreetmap.org/planet/2018/planet-180101.osm.bz2.

This isn't happening for files in http://planet.openstreetmap.org/pbf/

If it's a speed increase for one, it should be for the other.

**Comment by mmd-osm** [comment]
After some larger incident Heanet doesn’t seem to be mirroring osm anymore, see #210.

**Comment by Firefishy** [comment]
It looks like http://ftp.heanet.ie/mirrors/openstreetmap.org/ is no longer mirroring us. I have removed all the redirect mirror links for the moment. If they start mirroring us again we can consider the redirect.
