### ISSUE TITLE
missing membership renewal reminders

### ISSUE THREAD

**Issue by datendelphin** [openstreetmap/operations#196]
There are regularly missing membership renewal reminders. Civicrm should send reminders (two before the membership lapses, five after it lapsed) which usually works, but there are e certain percentage of reminders which are not sent.
I have a few examples, but I should share them in private because those are actual OSMF members.
In all cases of the missing reminders, the mails are not recorded as being sent by Civicrm. Otherwise, the reminder mails are recorded on the Activities tab on the member page. But I see nothing why this happens sometimes. Maybe you can have a look at the logs?

**Comment by tomhughes** [comment]
This is nothing to do with operations - the civicrm instance is run by the membership working group.

**Comment by tomhughes** [comment]
I'm told that you are asking on behalf of the membership group, but there's not much we can do without some idea where to look - we will need some idea of timestamp and what address we are looking for.

Are you sure civicrm actually sent the mail, or just assuming?

**Comment by pnorman** [comment]
> Are you sure civicrm actually sent the mail, or just assuming?

I don't think the MWG has a way to verify this.

**Comment by datendelphin** [comment]
I think civicrm did not send the mail, but I would like to find some clue why it didn't. All I can see is the activity log, where the mail does not show up, when it should, and in many cases it is sent. Let's say in about 10% of cases the mail is missing. Now I hope for some kind of log from Civicrm to get some clue

**Comment by datendelphin** [comment]
I reviewed a few experts from this site: https://civicrm.org/partners-contributors and would contact one or two to ask if they can help the MWG. Any comments from the OWG side on what I should look out for?

**Comment by pnorman** [comment]
Is this still an issue after the change from `sendmail -t` to direct SMTP?

**Comment by datendelphin** [comment]
Yes it is. Steve Friedl did further tests after the switch, and found missing reminders.

**Comment by datendelphin** [comment]
I had contact with Jon from megaphone technology consulting, and I think we have now resolved that issue. The fix was deleting the existing renewal reminders and adding them again, which "reset" some bogus state in the database. The bug was in versions prior to civicrm 4.6 and persisted in the data even though the bug was fixed in 4.6 and later. Here some more info from Jon:

> This is a vestige of a problem that was resolved with CiviCRM 4.6 (see
> https://issues.civicrm.org/jira/browse/CRM-15728).  Before 4.6, there
> was a problem where a contact would only receive any scheduled reminder
> once for a particular membership - which meant that when the membership
> renewed, you wouldn't get the notice the following year.
> 
> CRM-15728 fixed the problem for new memberships created after 4.6 was
> installed - but memberships created prior to 4.6 would still exhibit
> this behavior.
> 
> The MySQL table that stores a record of which scheduled reminder are
> sent is "civicrm_action_log" - reference_date is the relevant field here. 

I have readded the reminders 10 days ago, and checked for reminder mails since then, and all checked reminder mails were at least recorded in civicrm. Thank you @tomhughes for helping investigating and fixing this issue
