### ISSUE TITLE
Enable TemplateData extension on Wiki

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#198]
[TemplateData](https://www.mediawiki.org/wiki/Extension:TemplateData) is the standard way of annotating a template so a meaningful UI can be presented when editing. It is listed as having a stable release status, and in use on WMF wikis.

Without it, editing usage of a template looks something like this

![image](https://user-images.githubusercontent.com/1190866/36636087-f4b3153a-1973-11e8-87f3-88edbaacf711.png)

**Comment by pnorman** [comment]
Who's the best person to speak to to get this done? Should I have a wiki admin make this request?

**Comment by tomhughes** [comment]
Open a PR against chef?

**Comment by tomhughes** [comment]
Obviously it would be good if somebody familiar with mediawiki said they were happy with it as well.

**Comment by tomhughes** [comment]
Added in https://github.com/openstreetmap/chef/commit/005ae5bd819640bdfd31656393df2d2923be1f96.
