### ISSUE TITLE
Reissue certificates

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#2]
We need to reissue both our main certificate and the tile certificate with SHA256 checksums before Chrome starts warning (around March 2015 for us I think).

We're also going to add a bunch of extra domains to the main certificate.

**Comment by Firefishy** [comment]
"OpenStreetMap Foundation" has now been authenticated by StartSSL.

Any additional names to include before I issue the certificate? Re-Issuing tickets is complicated and is best avoided with StartSSL.

**Comment by tomhughes** [comment]
Well http://git.openstreetmap.org/dns.git/blob/HEAD:/Makefile#l23 is the list of all the domains I'm aware of.

**Comment by Firefishy** [comment]
Had to re-verify domains. Few issues, but should have certs by the weekend.

**Comment by Firefishy** [comment]
Requested all domains. Waiting on StartSSL now.

**Comment by Firefishy** [comment]
Annoyance is they will include base names eg: osm.org in blog.osm.org cert

**Comment by Firefishy** [comment]
osmfoundation.org cert issued. Others still pending.

**Comment by Firefishy** [comment]
osm.org + tile.osm.org certificates issued.

**Comment by daganzdaanda** [comment]
Hi, how do I get the new certificates to work with JOSM? 
Right now, it produces an error message when trying to download data.

**Comment by Firefishy** [comment]
@daganzdaanda We will likely revert. The JOSM/java incompatibility was an oversight of mine.

**Comment by daganzdaanda** [comment]
OK, thanks. 
Just out of curiosity, how is Java incompatible with the new certs?

**Comment by Firefishy** [comment]
@daganzdaanda seems Oracle Java Runtime Environment does not support StartSSL/StartCom who signed our new certificates.

**Comment by don-vip** [comment]
Hi, JOSM dev here.
As you are a StartCom customer, can you please ask them what is the current situation with Oracle? It's up to StartCom to meet the requirements of Oracle program and apply to be included in the Java Root CA, see http://www.oracle.com/technetwork/java/javase/javasecarootcertsprogram-1876540.html
If there's no hope to see StartCom in a future Java update very soon and you're still determined to switch to this CA, we'll probably have to disable HTTPS by default, as it is not really conceivable to include StartCom certificate inside JOSM and install it the JRE cacerts.

**Comment by tomhughes** [comment]
Do Oracle not work with the CA/Browser forum (https://cabforum.org/) like all the browsers do for defining CA requirements...

**Comment by don-vip** [comment]
I don't know, likely not. But discussing the well-founded of Oracle requirements is not the point. It's up to StartCom to see how to be included in that list, not us. I have sent them a tweet but I doubt they'll reply to me as I am not a customer.

**Comment by tomhughes** [comment]
So that we have a record of the deadlines involved here, per http://blog.chromium.org/2014/09/gradually-sunsetting-sha-1.html and our certificate expire of 17th March 2016 the deadlines are:

* Chrome 41 which is currently in beta will treat it as “secure, but with minor errors”
* Chrome 42 will likely treat it as “neutral, lacking security”
* Chrome 43 will likely treat it as “affirmatively insecure”

**Comment by stoecker** [comment]
For JOSM/Java it will not be easily solvable to accept StartSSL. OTOH JOSM does not access most of the pages, but only api.openstreetmap.org, www.openstreetmap.org, wiki.openstreetmap.org, taginfo.openstreetmap.org and throught the wiki trac.openstreetmap.org. First one most important, second also used from JOSM, third probably only inside online help and the last two mainly by browser calls.

Could these 5 get a certificate acceptable for Java and only the others use StartSSL? As that would be no wildcards, maybe it can be cheaper? Java7 supports SNI, so it should be possible to setup the servers to respond with wildcard cert where necessary when no SNI is used and thus there should be no negative effects.

I'd like to prevent to switch back to HTTP in JOSM, as that would be really the wrong sign regarding transmission security.

BTW: I could not use StartSSL with some E-Mail clients, especially on Android, so Java is not the only one affected.

**Comment by stoecker** [comment]
Forgot some: https://(abc).tile.openstreetmap.org, https://nominatim.openstreetmap.org, (svn.openstreetmap.org is also used, but not yet as https, which should probably be fixed).

**Comment by bastik** [comment]
Could you please clarify, what the plans are right now? Are you delaying the StartSSL move to give us more time to work around the missing root certificate in JOSM or are you looking for alternative CAs? This would be interesting to know, so we aren't surprised in mid-March.

I would appreciate, if we could find a Java-compatible CA, it would save a lot of troubles. In case there are financial limitations, we can think about ways to support this.

**Comment by Firefishy** [comment]
I'm looking for reasonably priced wildcards from Java-compatible CAs.

**Comment by tomhughes** [comment]
This has been done now.
