### ISSUE TITLE
Wolfson House electrical shutdown

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#20]
Our UCL hosting at Wolfson House will be out of action due to an electrical shutdown from around 5pm on Friday 20th February until around 8am on Monday 23rd February.

**Comment by tomhughes** [comment]
Plan to move either poldi or pummelzacken to IC before this.

**Comment by tomhughes** [comment]
We'll use stormfly-01 for taginfo - it is still running and up to date from last time.

**Comment by lonvia** [comment]
Is there any date planned yet for moving poldi/pummelzacken?

**Comment by zerebubuth** [comment]
Yup, I'll be moving poldi on Monday - hopefully upgrading / refreshing the HDD controller too (if so, it'll need a re-install after, sorry).

**Comment by tomhughes** [comment]
Is there going to be enough time to do a reinstall before we need it on the Friday?

**Comment by lonvia** [comment]
It's sufficient time for the initial import but not for catching up completely. Not a big issue, it'll just be a few days out of date.

**Comment by zerebubuth** [comment]
I'll try to install the new controller as soon as I get it, perhaps it'll be Friday and we'll have a few extra days to catch up.

**Comment by lonvia** [comment]
Wednesday will be too late for an import from scratch for poldi. That leaves us with either deferring the HDD controller install or resorting once more to the backup database.

**Comment by zerebubuth** [comment]
Yup, you're right. I won't be installing the new HDD controller this week. I'll try to get back to IC as soon as possible to do that and the new SSD for orm.

**Comment by tomhughes** [comment]
Poldi is now up and running at IC and taginfo has been moved to the US machine for now.

**Comment by tomhughes** [comment]
Nominatim was switched to poldi around 1745 on Friday and power went out around 1830.

**Comment by tomhughes** [comment]
Power came back just before 9am on Monday.
