### ISSUE TITLE
Redirect planet.openstreetmap.org to HTTPS

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#200]
I'm splitting this out from #190 to have a dedicated issue to point to and post information specific to planet.osm.org, which has complications other subdomains don't.

The plan is to switch planet.openstreetmap.org from HTTP or HTTPS to HTTPS by default, by redirecting everything to HTTPS. During testing of this, it was identified that many clients of planet.openstreetmap.org don't follow redirects and were using `http://planet.openstreetmap.org`, causing their updates to fail.

The biggest issue is probably osmosis. https://trac.openstreetmap.org/ticket/5483 tracks the changes needed there. Fortunately, people can fix the problem on their install by adjusting the configuration.txt and don't need to update osmosis versions.

Steps that need doing are
- [x] Write an email informing people of the change (@pnorman)
- [x] Change the configuration.txt generated by `osmosis --rrii` (https://trac.openstreetmap.org/ticket/5483)
- [ ] Optional: Make osmosis follow redirects
- [x] Optional: Search for configurations that need changing on code hosting sites and submit patches
- [ ] Blog post?

**Comment by SomeoneElseOSM** [comment]
For those that go that route, https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ uses https://github.com/SomeoneElseOSM/mod_tile/tree/switch2osm (which is already customised for easier setup) and https://github.com/SomeoneElseOSM/mod_tile/blob/switch2osm/openstreetmap-tiles-update-expire changes an osmosis-initialised "http" to "https".

**Comment by grischard** [comment]
`curl` also doesn't follow redirects by default.

A github search finds [130 results](https://github.com/search?q=%22http%3A%2F%2Fplanet.openstreetmap.org%22+curl&type=Code&utf8=%E2%9C%93) for curl and [124 for osmosis](https://github.com/search?utf8=%E2%9C%93&q=%22http%3A%2F%2Fplanet.openstreetmap.org%22+osmosis&type=Code). I can [open issues like this one](https://github.com/pear/Services_Openstreetmap/issues/18) where relevant, but it would be great to have a sunset date. May 7?

**Comment by tomhughes** [comment]
Works for me.

**Comment by wosch** [comment]
How about planet.osm.org - will it switch to HTTPS by default as well?

**Comment by wosch** [comment]
It is true that curl also doesn't follow redirects by default. But that is a non issue here - in the past the site http://planet.openstreetmap.org/pbf/planet-latest.osm.pbf always sent a redirect to the actual file (sometimes on a mirror) site. To use curl, you had to run it with the -L parameter to follow symlinks in your scripts.

**Comment by tomhughes** [comment]
@wosch for full planet files yes, but not for the replication diffs, which are the big issue.

**Comment by grischard** [comment]
Done tasks 1 and 4.

**Comment by grischard** [comment]
Afaict 2 [is done](https://github.com/openstreetmap/osmosis/search?utf8=%E2%9C%93&q=%22planet.openstreetmap.org%22&type=) too.e

**Comment by grischard** [comment]
Of course this applies to http://planet.osm.org too. I'll open issues on github projects that use it.

**Comment by grischard** [comment]
So [I think we can close this](https://git.openstreetmap.org/chef.git/commitdiff/5924746)!

**Comment by mmd-osm** [comment]
Apologies for hijacking this closed issue. Is there an easy way to find out how many clients are currently affected by this change, i.e. they still request data from http and don't follow redirects to https?

Someone posted a munin chart for https://munin.openstreetmap.org/openstreetmap/ironbelly.openstreetmap/apache_accesses.html. For sure, there's some drop off at the time when the switch occurred, but I don't know if this is truly meaningful to analyze broken clients.
