### ISSUE TITLE
Wiki: Visual Editor shows error when loading

### ISSUE THREAD

**Issue by rugk** [openstreetmap/operations#204]
Go to any wiki site, e.g. https://wiki.openstreetmap.org/wiki/StreetComplete/Quests?veaction=edit and click edit (link already links to edit version BTW):

> Fehler beim Laden der Daten vom Server: apierror-visualeditor-docserver-http: HTTP 406. Soll der Vorgang erneut durchgeführt werden?

Note for myself: Adding `https://github.com/westnordost/StreetComplete/pull/986` and `https://github.com/westnordost/StreetComplete/pull/991` depends on this issue as I need to edit the wiki there and really don't want to use the non-VisualEditor.

**Comment by rugk** [comment]
BTW, actually, I can see no such error code.
I see a request (http code: 200) https://wiki.openstreetmap.org/w/api.php?action=visualeditor&format=json&paction=parse&page=StreetComplete%2FQuests&uselang=de&oldid=1593373, which returns this:
```

error | {…}
-- | --
code | apierror-visualeditor-docserver-http
info | HTTP 406
* | See https://wiki.openstreetmap.org/w/api.php  for API usage. Subscribe to the mediawiki-api-announce mailing list at  &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt;  for notice of API deprecations and breaking changes.
```

**Comment by tomhughes** [comment]
No thanks to wikimedia, who pushed a new version of parsoid in their apt repository that isn't compatible with any released version of visual editor, this should now be fixed.

**Comment by rugk** [comment]
Thanks very much! Works now again.

**Comment by KarelWintersky** [comment]
How are you solved this problem?
