### ISSUE TITLE
Inconsistent `Strict-Transport-Security` headers on tile servers

### ISSUE THREAD

**Issue by TobiX** [openstreetmap/operations#205]
Currently, the tile servers send the `Strict-Transport-Security` with unencrypted responses (which the RFC discourages, see also https://github.com/openstreetmap/operations/issues/117#issuecomment-259192002).

On the other hand, the `Strict-Transport-Security` is sent twice on encrypted connections, which might confuse clients (Firefox seems to ignore the header outright, see also [SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=a.tile.openstreetmap.org))

It would probably be best to only send the header once on HTTPS connections.

**Comment by tomhughes** [comment]
Unfortunately due to the number of components in the chain I'm not sure this is very easy right now.

Basically an https connection for an uncached tile actually goes https->http->https before actually reaching a render server and as I recall I couldn't find a way to make nginx do what was needed at the outer level to remove the header added by the upstream apache.

**Comment by Firefishy** [comment]
I can likely fix it. Give me a bit

**Comment by tomhughes** [comment]
Of course we could just get rid of nginx now that we have a squid that can do SSL ;-)

**Comment by Firefishy** [comment]
The latest squid in Ubuntu 16.04 is now also compatible with our usage case and has some interesting peering options.

**Comment by Firefishy** [comment]
Fixed the double `Strict-Transport-Security` in HTTPS mode in https://github.com/openstreetmap/chef/commit/1af304f7852542300224c6634686933f3c93652d

I'm bias to leaving `Strict-Transport-Security` enabled for HTTP. It is upto the client if it should honour it.

**Comment by Firefishy** [comment]
A+ now: https://www.ssllabs.com/ssltest/analyze.html?d=a.tile.openstreetmap.org
