### ISSUE TITLE
Would the OWG provide server space for a "Attach photo to note comment" feature?

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/operations#206]
It has been proposed that the notes-feature on the openstreetmap website (and API) could be extended by the possibility to add a photo: https://github.com/openstreetmap/openstreetmap-website/issues/395

Whether or not the maintainers would accept a PR that implements this depends on whether the OWG would in that case provide enough server space for this feature. So, that is what I want to find out here. (I do not intend to implement it myself, I just want to find out if it may be implemented):
Would the OWG provide server space for a "Attach photo to note comment" feature?

Note, that amongst others, the following things could be done to limit the amount of server space this feature would consume:
- attached images could be deleted X days after a note has been closed
- attached images could be automatically scaled down, stripped of metadata and saved on a certain quality on upload
- or, images could also be deleted after at most X days (regardless of if the issue has been closed or not)

**Comment by tomhughes** [comment]
I think any consideration of this is likely dependent on us getting proper shared storage up and running for the web cluster - it seems like a bad idea to add anything more to our current ad-hoc solution.

**Comment by gravitystorm** [comment]
My initial reaction is: not in the short term. We have been planning to move the website storage (e.g. user images, gpx files) off of a centralised machine and onto a storage cluster, but that is still in progress.

https://github.com/openstreetmap/operations/issues/169

After the storage cluster is available, then we can consider adding additional things like this.

**Comment by zerebubuth** [comment]
Storage considerations aside, I worry about the potential for abuse on a something which would essentially be a photo-sharing service. Content moderation is a lot of work, and OSMF (esp. DWG) would have to be happy that adding this service wouldn't create an unmanageable amount of additional work. There might also be liability related to hosting those photos.

**Comment by westnordost** [comment]
Okay, I think that suffices for an answer. I will close this issue.

**Comment by westnordost** [comment]
After more than five years of uploading photos with StreetComplete, here are some numbers:

The photos are deleted shortly after its associated note is closed. Photos are also resized to 1280px in width before upload.

In five years (Apr 2018 - Apr 2023), ~150k photos were uploaded. Of these, ~20k remain (5 GB).

So, if all photos would be kept forever, it would be ~38 GB in five years.

If uploaded pictures in StreetComplete were not resized, it would probably approximately 10 times the size, as photos from cameras nowadays are usually at 4k resolution or higher.

**Comment by Zverik** [comment]
Huh, didn't know this ticket existed. As a developer of Every Door, I support it.
