### ISSUE TITLE
Default map is not visible

### ISSUE THREAD

**Issue by kocio-pl** [openstreetmap/operations#209]
I'm not sure if this is the right place to report it, but the default map layer on OSM.org is not visible for a few minutes, only gray area:

![screenshot-2018-5-1 openstreetmap](https://user-images.githubusercontent.com/5439713/39479802-9d09a156-4d66-11e8-863d-97e16603d689.png)

**Comment by kocio-pl** [comment]
Might be a cache problem, when testing on remote browsers test sites (like https://browsershots.org), the map is visible in some cases and gray in some other.

**Comment by tomhughes** [comment]
Likely a temporary problem with whatever cache you're using - it should fail over eventually.
