### ISSUE TITLE
Planet osm redirects to no longer existing ftp.heanet.ie mirror (II)

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#210]
Follow up for #171 which is closed now. 

Recently heanet.ie appears to have had some severe issues and it seems as if they had stopped mirroring OSM for the time being: https://ticketing.heanet.ie/public/show.html?id=1312119

Example:

https://planet.openstreetmap.org/planet/2017/planet-171009.osm.bz2

redirects to the non-existing

http://ftp.heanet.ie/mirrors/openstreetmap.org/planet/2017/planet-171009.osm.bz2

[Link 1](https://github.com/openstreetmap/chef/blob/master/cookbooks/planet/templates/default/planet-mirror-redirect-update.erb#L13) and [Link 2](https://github.com/openstreetmap/chef/blob/master/cookbooks/planet/templates/default/planet-mirror-redirect-update.erb#L44) still point to the non-existing mirror, and it seems that there's an `.htaccess` file on the server with lots of invalid rewrite rules now. This script somehow doesn't have a way to expire old and/or defunct links.

Old planet files are still around here: https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/planet/

This is also related to #18

**Comment by Firefishy** [comment]
I have disabled the mirror redirect links to heanet.
