### ISSUE TITLE
Check for invalid polygons on rendering servers

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#211]
We're looking into gravitystorm/openstreetmap-carto#1644, so polygon validity is going to become important soon. Can you run this query on **all** the rendering servers?

```sql
SELECT COUNT(*) FROM planet_osm_polygon WHERE NOT ST_IsValid(way);
```

If any of them return non-zero counts, can you check the osm2pgsql version as well as run the query `SELECT postgis_full_version();`

**Comment by tomhughes** [comment]
It looks like there is one single invalid polygon. All four servers report as follows:

```
gis=# SELECT COUNT(*) FROM planet_osm_polygon WHERE NOT ST_IsValid(way);
NOTICE:  Hole lies outside shell at or near point -359741.25 7191782.5
 count 
-------
     1
(1 row)
```

Hilariously that one error appears to be https://www.openstreetmap.org/relation/4621350, in Barrow-in-Furness where the last edit (three years ago) was to remove a self intersection.

The osm2pgsql version is `0.88.1` and the postgis version reports as:

```
POSTGIS="2.3.3 r15473" GEOS="3.5.0-CAPI-1.9.0 r4084" PROJ="Rel. 4.9.2, 08 September 2015" GDAL="GDAL 1.11.3, released 2015/09/16" LIBXML="2.9.3" LIBJSON="0.11.99" RASTER
```
