### ISSUE TITLE
attempt to save edit adding "{{#tag:osmtaginfo||key=|value=}}" on OSM wiki ends with "Fatal exception of type "Error"", some existing pages are also affected

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#216]
Attempting to save page containing 

> {{#tag:osmtaginfo||key=|value=}}

results in unclear error:

> [148d8293d1603b94aa78200d] 2018-05-26 08:59:41: Fatal exception of type "Error"

**Comment by mmd-osm** [comment]
Was it intended to leave both key= and value= empty?

**Comment by matkoniecz** [comment]
In my case - yes.

But

> {{#tag:osmtaginfo||key=dummy_value|value=dummy_value}}

worked perfectly fine, once I figured out what was happening.

**Comment by mmd-osm** [comment]
Seems to be this line: https://gitorious.org/osmtaginfo/osmtaginfo?p=osmtaginfo:osmtaginfo.git;a=blob;f=OSMTagInfo.class.php;h=5685b639cd279a1e142f44a357d13efd1f929a61;hb=HEAD#l57

I think the code wants to tell you that the key is missing, but there's no error message defined for it, or the function wfMsg is unknown.

```php
 if ( $key == '' AND $rtype == '' ) $error .= wfMsg( 'osmtaginfo_keymissing' ) . '<br>';
```

@Firefishy should know what's going on here...

**Comment by pnorman** [comment]
Confirming that this is still an issue. The link above is now 
https://github.com/Firefishy/osmtaginfo/blob/19f6ec35172bd928c744459588e639c139c8d6b0/osmtaginfo.class.php#L57

**Comment by Firefishy** [comment]
I honestly have recollection of writing that mediawiki extension.... But hey PR welcome.

**Comment by Tigerfell** [comment]
> But hey PR welcome.

In case you did not notice, openstreetmap/chef has currently 6 open PRs and 3 of them focus on MediaWiki. Reviews highly appreciated. :+1:

**Comment by mmd-osm** [comment]
I found this elsewhere:  “replace wfMsg by wfMessage”. Maybe give it a try.

**Comment by matkoniecz** [comment]
See also https://github.com/openstreetmap/operations/issues/536#issuecomment-1207353887

**Comment by matkoniecz** [comment]
@Tigerfell It took over two years, but PRs appear to be processed: https://github.com/openstreetmap/chef/pulls

**Comment by Firefishy** [comment]
> @Tigerfell It took over two years, but PRs appear to be processed: https://github.com/openstreetmap/chef/pulls

Now that I have time, I hope to be a lot quicker in responding to PRs. Previously I was spread quite thin and some items got dropped, sorry.

**Comment by Firefishy** [comment]
Hopefully this fixes the errors: https://github.com/Firefishy/osmtaginfo/commit/196b69399aaa5197b5c8c4bce8b77c4d189e659b (already deployed)

**Comment by matkoniecz** [comment]
Tried editing https://wiki.openstreetmap.org/w/index.php?title=Sandbox&action=edit&section=1 by adding 

```
  {{#tag:osmtaginfo||key=|value=}}
```

got `[4baa09e8481a644fd40096cb] 2022-08-07 10:57:37: Fatal exception of type "Error"`

**Comment by Firefishy** [comment]
Try again. Hackish fix deployed. Needs some work

**Comment by matkoniecz** [comment]
Yes, now it works

**Comment by Firefishy** [comment]
Closing as "fixed". PRs open: https://github.com/openstreetmap/osmtaginfo
