### ISSUE TITLE
Request token error

### ISSUE THREAD

**Issue by willemarcel** [openstreetmap/operations#217]
We are having some issues with the OSMCha staging server (https://osmcha-django-staging.tilestream.net). Since some days ago, we can not get the oauth keys that makes it possible to the user to authenticate.

The response we get when we try to access the https://www.openstreetmap.org/oauth/request_token URL is:

`<h1>Application error</h1>\n    <p>The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)</p>\n    <p>Feel free to <a href': '"http://wiki.openstreetmap.org/wiki/Contact" '`

We have already tested two oauth client keys. Furthermore, when I run the same codebase on other machine, it works.

I would appreciate if you have some suggestion to solve that problem. Using the OSM Dev instance would be complicated, because the library we use to get the user details have the OSM main url set.

**Comment by tomhughes** [comment]
The other thing which typically causes that error is an invalid client ID to be honest.

Certainly there's not much I can do to help without looking at the logs, and I can't do that without some way of finding your requests.

**Comment by tomhughes** [comment]
Hang on, is that using the python social auth module thing?

If so then you probably just need to update that - the old version uses http and doesn't follow redirects. That might explain why it works on other machines.

**Comment by tomhughes** [comment]
Argh. Will you please stick to one communication channel. I've just answered your email to find that you've also commented here!

It seems clear at this point that it's a problem in your environment and not anything at our end.

All looking at the logs is likely to tell me is that you are sending requests with an invalid signature which won't help at all.

**Comment by tomhughes** [comment]
Just to add that token you sent in email doesn't appear in any of today's logs.

**Comment by tomhughes** [comment]
I can see calls to request-token with that callback, but that are using a different client key and they are successful.

**Comment by willemarcel** [comment]
Thank you very much for your support, @tomhughes !
