### ISSUE TITLE
Move grindtooth to a G6

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#22]
The taginfo server, grindtooth, is pulling about 280W during the day, increasing to 350W overnight when it updates, so moving a G6 would be good to reduce our power footprint at UCL.

**Comment by zerebubuth** [comment]
I shut this machine down yesterday and @tomhughes switched the DNS across to stormfly-01 in the US. For the moment, we're down to acceptable power usage levels, but we can revisit running something on grindtooth and/or replacement G6 once the power issues have been sorted.

**Comment by zerebubuth** [comment]
Grindtooth is back, although I think I got the disks mixed up or something, because it wouldn't boot off them and needed a re-install.
