### ISSUE TITLE
Upgrade machines to Ubuntu 18.04

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#220]
Upgrade all our machines to Ubuntu 18.04:

- [x] angor.openstreetmap.org (currently 16.04)
- [x] ascalon.openstreetmap.org (currently 16.04)
- [x] clifford.openstreetmap.org (currently 16.04)
- [x] cmok.openstreetmap.org (currently 16.04)
- [x] culebre.openstreetmap.org (currently 16.04)
- [x] draco.openstreetmap.org (currently 16.04)
- [x] drogon.openstreetmap.org (currently 16.04)
- [x] dulcy.openstreetmap.org (currently 16.04)
- [x] eddie.openstreetmap.org (currently 16.04)
- [x] errol.openstreetmap.org (currently 16.04)
- [x] eustace.openstreetmap.org (currently 16.04)
- [x] gorynych.openstreetmap.org (currently 16.04)
- [x] grindtooth.openstreetmap.org (currently 16.04)
- [x] grisu.openstreetmap.org (currently 16.04)
- [x] ironbelly.openstreetmap.org (currently 16.04)
- [x] jakelong.openstreetmap.org (currently 16.04)
- [x] kalessin.openstreetmap.org (currently 16.04)
- [x] karm.openstreetmap.org (currently 16.04)
- [x] katie.openstreetmap.org (currently 16.04)
- [x] katla.openstreetmap.org (currently 16.04)
- [x] kessie.openstreetmap.org (currently 16.04)
- [x] konqi.openstreetmap.org (currently 16.04)
- [x] ladon.openstreetmap.org (currently 16.04)
- [x] longma.openstreetmap.org (currently 16.04)
- [x] nepomuk.openstreetmap.org (currently 16.04)
- [x] noquiklos.openstreetmap.org (currently 16.04)
- [x] odin.openstreetmap.org (currently 16.04)
- [x] orm.openstreetmap.org (currently 16.04)
- [x] ouroboros.openstreetmap.org (currently 16.04)
- [x] pummelzacken.openstreetmap.org (currently 16.04)
- [x] ramoth.openstreetmap.org (currently 16.04)
- [x] ridgeback.openstreetmap.org (currently 16.04)
- [x] ridley.openstreetmap.org (currently 16.04)
- [x] saphira.openstreetmap.org (currently 16.04)
- [x] sarel.openstreetmap.org (currently 16.04)
- [x] sarkany.openstreetmap.org (currently 16.04)
- [x] scorch.openstreetmap.org (currently 16.04)
- [x] shenron.openstreetmap.org (currently 14.04)
- [x] simurgh.openstreetmap.org (currently 16.04)
- [x] spike-01.openstreetmap.org (currently 16.04)
- [x] spike-02.openstreetmap.org (currently 16.04)
- [x] spike-03.openstreetmap.org (currently 16.04)
- [x] spike-04.openstreetmap.org (currently 16.04)
- [x] spike-05.openstreetmap.org (currently 16.04)
- [x] stormfly-01.openstreetmap.org (currently 16.04)
- [x] stormfly-02.openstreetmap.org (currently 16.04)
- [x] thorn-01.openstreetmap.org (currently 16.04)
- [x] thorn-02.openstreetmap.org (currently 16.04)
- [x] thorn-03.openstreetmap.org (currently 16.04)
- [x] thorn-04.openstreetmap.org (currently 16.04)
- [x] thorn-05.openstreetmap.org (currently 16.04)
- [x] tiamat-00.openstreetmap.org (currently 16.04)
- [x] tiamat-01.openstreetmap.org (currently 16.04)
- [x] tiamat-02.openstreetmap.org (currently 16.04)
- [x] tiamat-03.openstreetmap.org (currently 16.04)
- [x] tiamat-11.openstreetmap.org (currently 16.04)
- [x] tiamat-12.openstreetmap.org (currently 16.04)
- [x] tiamat-13.openstreetmap.org (currently 16.04)
- [x] tiamat-21.openstreetmap.org (currently 16.04)
- [x] tiamat-22.openstreetmap.org (currently 16.04)
- [x] tiamat-23.openstreetmap.org (currently 16.04)
- [x] trogdor.openstreetmap.org (currently 16.04)
- [x] urmel.openstreetmap.org (currently 16.04)
- [x] viserion.openstreetmap.org (currently 16.04)
- [x] yevaud.openstreetmap.org (currently 16.04)

**Comment by sommerluk** [comment]
With the upgrade we have the new Mapnik version for rendering, which includes in important bugfix for label positions for polygons. That looks great.

This is a good opportunity to say “thank you” for all the work you’re doing here @tomhughes 👍

**Comment by tomhughes** [comment]
The upgrades are now complete!
