### ISSUE TITLE
Wiki Visual Editor loading fails

### ISSUE THREAD

**Issue by rugk** [openstreetmap/operations#221]
When I try to edit vai Visual Editor (https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ?veaction=edit&section=6) I get a 406 error:

> Fehler beim Laden der Daten vom Server: apierror-visualeditor-docserver-http: HTTP 406. Soll der Vorgang erneut durchgeführt werden?

**Comment by tomhughes** [comment]
This should be fixed now.

**Comment by rugk** [comment]
Oh thanks for the fast fix! :smile:
