### ISSUE TITLE
Multi Fetch GET for user details

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/operations#222]
The API currently lets us fetch [details for a single user](https://wiki.openstreetmap.org/wiki/API_v0.6#Details_of_a_user) like this:
```
GET /api/0.6/user/#id
```

It would be nice to be able to fetch details for several users with a single call, similar to how we can do for [other OSM objects](https://wiki.openstreetmap.org/wiki/API_v0.6#Multi_fetch:_GET_.2Fapi.2F0.6.2F.5Bnodes.7Cways.7Crelations.5D.3F.23parameters):

```
Multi fetch: GET /api/0.6/[nodes|ways|relations]?#parameters
```
☝️ add to above things like.. `users`  `notes`

### why?
The reason I'm requesting this for `users` is because soon iD will start showing OSM notes:

<img width="960" alt="screenshot 2018-07-06 01 25 07" src="https://user-images.githubusercontent.com/38784/42361261-7ae1f76c-80bb-11e8-8487-b910b37672dd.png">

I'd like to include the user's profile pictures next to their comments.  So we currently just fire off a bunch of single user GET calls and cache the results, but would be nice to fetch many at a time.

**Comment by mmd-osm** [comment]
Seems like the wrong repo, `/api/0.6/user/#id` is implemented in https://github.com/openstreetmap/openstreetmap-website

**Comment by bhousel** [comment]
> or maybe even both.

Yes, I've been told before this is the place to raise API issues that cut across multiple repos.

**Comment by tomhughes** [comment]
I assume that's something I said but I'm not sure that's exactly what I meant.

I mean once something exists in the underlying tools this is the place to ask about enabling it if that is necessary but just opening a ticket here asking for a new feature is unlikely to have any effect as I'm not sure many people (outside operations people) actually watch this.

**Comment by tomhughes** [comment]
I'm guessing you're referring to something like the vector tiles ticket? Which is more about glueing together other existing components than about adding a feature to an existing project.

**Comment by bhousel** [comment]
Sure if it makes more sense to open tickets in both openstreetmap-website and cgimap, I can do that..

**Comment by tomhughes** [comment]
Well I think the user API is still in rails isn't it? Don't think it has moved to cgimap yet?

**Comment by mmd-osm** [comment]
Right, it's still in rails. I mentioned both repos, as the multi fetch stuff for nodes/way/rels is already in cgimap. So multi user fetch could be a candidate for cgimap, but doesn't have to be.

**Comment by bhousel** [comment]
> Well I think the user API is still in rails isn't it? Don't think it has moved to cgimap yet?

I have no idea
