### ISSUE TITLE
MediaWiki inserted 'Code blocks' are not visible in VisualEditor

### ISSUE THREAD

**Issue by skylerbunny** [openstreetmap/operations#223]
If using the MediaWiki VisualEditor (such as at the URL [https://wiki.openstreetmap.org/wiki/Sandbox?veaction=edit](https://wiki.openstreetmap.org/wiki/Sandbox?veaction=edit) ), it is possible, and not unusual, to add a _Code block_, using the _Insert_ menu option. A popup window will appear, and code can be pasted or typed in.

When the window is closed, the symbol `<>` appears. _This probably isn't what's supposed to happen; (my guess is it should show you the actual result of the code block insert), but it can at least be selected during this single edit session._

The real problem is that after saving the document, and then going in to edit it with VisualEditor a second time, the Code block created (which uses `<syntaxhighlight>` tag pairs in MediaWiki source) is not visible at all. It cannot be seen, highlighted, or edited.

Code blocks are useful, even moreso than `<pre>` blocks, because they allow code syntax highlighting. Whether using the deprecated <source> tag or the newer <syntaxhighlight> tag, this appears frequently (to give one example) in pages featuring Overpass Turbo/Overpass and QL code snippets.

Wikipedia's MediaWiki (by using its sandbox) can show what "should" happen; when editing a page with a previously inserted Code block, the block should both be visible in VisualEditor, and selectable to edit.

**Comment by tomhughes** [comment]
We just deploy the visual editor - we're not doing anything at all clever so if it doesn't work properly it pretty much has to be an upstream bug.

**Comment by Dalesjo** [comment]
This can be a issue in the parsoid configuration. You are doing 302 redirect from http to https. If parsoid is configured to use an http url (default) this issue will appear for syntaxhighlight. 

File to change is /etc/mediawiki/parsoid/config.yaml

```
mwApis:
	- # This is the only required parameter,
	  # the URL of you MediaWiki API endpoint.
	  # uri: 'http://localhost/api.php'
	  uri: 'https://localhost/api.php'
```

**Comment by tomhughes** [comment]
Thanks. I've pushed a change in https://github.com/openstreetmap/chef/commit/d13ebdee36c818b4efd5d8a3a1d458503ab7a63b to fix that.
