### ISSUE TITLE
Stagger power bar startup in AM6

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#225]
Right now there is a very small delay between outlets turning on with the AM6 power bars. We should increase this to avoid strong inrush currents if we have a total power loss and one bar comes up first, taking all the load. Maybe 500ms between outlet, for a total startup of about 12s?

**Comment by pnorman** [comment]
Doesn't seem as important as other issues, and we've tested that everything works with a partial power outage.

**Comment by Firefishy** [comment]
We should do it. Else we risk blowing trip switch on our rack.

**Comment by Firefishy** [comment]
Done.
thorn-01 (lockheed), thorn-02, thorn-02, dulcy and faffy power on delayed.
Delay between 90 seconds and 180 seconds.

Rest power on immediately on power return.

See private repo https://github.com/openstreetmap/oxidized-configs for config.
