### ISSUE TITLE
Grant access to Cogent portal

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#227]
I need to create accounts for the relevant people on the Cogent portal

**Comment by pnorman** [comment]
I can't find the option int he portal, so I asked in a ticket

**Comment by Firefishy** [comment]
@pnorman Still required?

**Comment by pnorman** [comment]
Yes. I'll check in with them after the weekend.

**Comment by pnorman** [comment]
I asked, and the easiest way to do it is through a ticket, so I'll do that.

**Comment by pnorman** [comment]
Ticket created.

**Comment by Firefishy** [comment]
Closing as likely no longer required.
