### ISSUE TITLE
Local chapters

### ISSUE THREAD

**Issue by sabas** [openstreetmap/operations#229]
Hi,
at Sotm one of the ideas to organise discussion between local chapters was to have a Github repo for coordination.
I wonder if the openstreetmap organization here is the best place to host it, if so, could some administrator create it?

Thanks

/cc @joostschouppe

**Comment by tomhughes** [comment]
Maybe osmlab would be better? especially if it's going to include unofficial local organisations?

**Comment by joostschouppe** [comment]
We do aim to become an official OSMF working group. But I guess we can always move house if and when that's the case.

**Comment by hbogner** [comment]
I don't think intention was to use github but mailing list: https://lists.openstreetmap.org/listinfo/local-chapters
And to recycle and reuse Local chapter working group: https://wiki.osmfoundation.org/wiki/Local_Chapters_Working_Group

**Comment by joostschouppe** [comment]
Mailing list for archiving and discussion; chat room for quick questions; github for planning.
Recycling the Local chapter working group didn't click in my head (I thought that was only about the mailing list), but that does make sense.

**Comment by sabas** [comment]
osmlab is ok as well.
@hbogner I think github it's useful for documentation purposes, I subscribed to the mailing list also

**Comment by hbogner** [comment]
For github maybe it's better to use https://github.com/osmfoundation as local chapers are part of osmf?

**Comment by joostschouppe** [comment]
Different options were discussed, and several people wanted to use Github. Since the objectives are clearly related to OSMF, asking the people operating the central OSM github seems logical. Again, we can always go somewhere else and move to central accounts once things are "official enough".

**Comment by pnorman** [comment]
I'm still not sure why it's in this issue tracker. If you want a repo created on the "openstreetmap" github account, [the docs say](https://github.com/openstreetmap/openstreetmap-mirror/blob/master/ABOUT.md) to contact bastik or avar.

**Comment by tomhughes** [comment]
Well the docs are, err, wrong.

**Comment by tomhughes** [comment]
To be more precise I think that is ancient history, although avar does still have admin rights bastik certainly doesn't while the other admins are mostly the normal ops/admin people.

**Comment by imagico** [comment]
I would like to second what @hbogner and @pnorman said - that we should, as discussed in the local chapters meeting in Milano - use the existing local-chapters mailing list for main coordination.  If a need for certain technical infrastructure beyond that arises we should discuss that there based on the specific needs of the project in question (and potentially the OSMF [FOSS policy](https://wiki.osmfoundation.org/wiki/FOSS_Policy)).

**Comment by xivk** [comment]
@tomhughes @pnorman Why is this closed so fast and who makes these decisions? Is the operations working group the only group that can use the openstreetmap github organization?

I think it makes sense to have a repo for coordination of our efforts. The majority of us discussing this at SOTM are members of the OSMF and I think we have say on this too...

**Comment by tomhughes** [comment]
Sorry I thought the agreement was to use the local-chapters list to work out what you wanted and then come back so I closed it.

Just to be clear although this tracker is called `operations` it's really mostly a sysadmin thing rather than an OWG thing - if OWG was to have an issue tracker it should probably be under the `osmfoundation` organisation.

**Comment by xivk** [comment]
Thanks @tomhughes no worries, we'll work it out better and come back here once we've discussed further...

**Comment by xivk** [comment]
Or somewhere else where it is appropriate to ask these questions instead of `operations`

**Comment by hbogner** [comment]
Switch to https://github.com/osmfoundation/lcwg for further github needs.

**Comment by bhousel** [comment]
Also worth mentioning, anybody can add repositories to the https://github.com/osmlab/ organization.  Anybody who asks can join and use it - please PM me if you want to be added.

**Comment by gravitystorm** [comment]
Also, this is a completely ridiculous discussion. If anyone wants a repository under the "openstreetmap" organisation for anything vaguely related to openstreetmap then they should get one straight away. Repos are free, and can be moved / renamed / whatever in the future if any need transpires. There's no need to make creating a repo any kind of hassle. The "openstreetmap" organisation on github isn't any kind of official thing and there are no, and never have been any, requirements to get added.

If anyone feels there should be some sort of process for this, then lets create a ticket and agree so. But lets not have invisible barriers or hidden impediments to getting things done.

**Comment by RobJN** [comment]
> if there's no code and just discussion, a source code hosting site seems like a poor fit. 

You would think so, but having used it for 3 years for State of the Map planning, I discovered that the Issues section in GitHub is amazing as a "to-do lists on steroids" system. Unlike other to do lists you can add multiple checkboxes, assign to someone, use basic text formatting, attach files, have an in thread discussion, etc... It's unbeaten so far.

SotM has two: The website here on github.com/openstreetmap (that's a traditional code based repo) and a private one on github.com/osmfoundation (our planning to-do list). I'm grateful for both.

See you over on https://github.com/osmfoundation/lcwg
