### ISSUE TITLE
Replace RAID controller battery in yevaud

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#23]
The RAID controller battery in yevaud has, to quote @zerebubuth, "swelled up like a  dead whale on a beach" and needs replacing.

**Comment by Firefishy** [comment]
Areca ARC-1220 batteries are no longer available AFAIK. It is possible to hack-up a replacement from a 3rd party battery with some cable splicing, but risky.

**Comment by zerebubuth** [comment]
Looks like we have a few options:

1. Leave it as it is. Without the controller battery, the controller will be even slower than before as it won't cache writes.
2. Use the new LSI controller + `md` to control all the disks, not just the SSD. This has the advantage that the LSI is a much more recent and capable controller than the ARC-1220, but isn't a full-featured RAID controller and doesn't have battery backup either. Also, this would mean either re-installing the whole system, or a lengthy process of shuffling disks / clonezilla.
3. Buy a new [controller](http://www.span.com/product/Areca-SAS-RAID-Controller-ARC-1883i-SAS-SATA-12Gbit-8-Port-Dual-Core-Two-x4-Internal-SFF8643-PCI-Express-x8-v3-0-RAID-0-1-5-6~42314) and [capacitor backup](http://www.span.com/product/Areca-Remote-Battery-ARC-1883-CAP-PCIe-Battery-Card-for-ARC-1883i-x-lp~45866) (total about £716), which would be much faster and battery backed-up.

Personally, I'm all for trying out option 2 and re-installing the system... but I don't know how much of a pain it would be to do that... emptying the cache would be pretty bad for performance for a week or two, but at least the database is already on the SSD, so wouldn't need reloading. If option 2 doesn't work then moving on to option 3. What does everyone else think?

**Comment by Firefishy** [comment]
Status update?

**Comment by Firefishy** [comment]
Batteries are no longer available for this model and hacking up a replacement is not ideal. Closing. Performance is OK without.
