### ISSUE TITLE
Write labels on boxes at AM6

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#230]
The [AM6 inventory](https://github.com/openstreetmap/operations/wiki/AM6-Inventory) has a box by box breakdown of where stuff is, but the boxes aren't labeled.

A sharpie or other permanent marker would work, or a label maker.

**Comment by pnorman** [comment]
Assigned to @Firefishy for next site visit

**Comment by Firefishy** [comment]
I have done this.
![PXL_20220621_211524422 MP](https://user-images.githubusercontent.com/248188/180576818-8bcfe254-25e7-4422-b006-5281f579c3f6.jpeg)
