### ISSUE TITLE
Failing disk in yevaud

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#233]
This isn't a full on failure but it's probably on it's way out:

```
This message was generated by the smartd daemon running on:

   host name:  yevaud
   DNS domain: openstreetmap.org

The following warning/error was logged by the smartd daemon:

Device: /dev/sg3 [areca_disk#03_enc#01], 1 Currently unreadable (pending) sectors

Device info:
WDC WD6000HLHX-01JJPV0, S/N:WD-WXL1E4053252, WWN:5-0014ee-00253c25a, FW:04.05G04, 600 GB

For details see host's SYSLOG.

You can also use the smartctl utility for further investigation.
Another message will be sent in 24 hours if the problem persists.
```

**Comment by tomhughes** [comment]
In fact earlier today it logged 7 offline uncorrectables as well:

```
This message was generated by the smartd daemon running on:

   host name:  yevaud
   DNS domain: openstreetmap.org

The following warning/error was logged by the smartd daemon:

Device: /dev/sg3 [areca_disk#03_enc#01], 7 Offline uncorrectable sectors

Device info:
WDC WD6000HLHX-01JJPV0, S/N:WD-WXL1E4053252, WWN:5-0014ee-00253c25a, FW:04.05G04, 600 GB

For details see host's SYSLOG.

You can also use the smartctl utility for further investigation.
The original message about this issue was sent at Wed Mar 14 20:23:44 2018 UTC
Another message will be sent in 24 hours if the problem persists.
```

**Comment by Firefishy** [comment]
It is worth replacing regardless. Google paper explains https://ai.google/research/pubs/pub32774

**Comment by Firefishy** [comment]
I am thinking of getting 2x Samsung 860 Pro 512GB disks and add them to the LSI HBA controller. mdraid RAID0 and migrate /store/tiles/default-low. Then in a few weeks moved the 2x Samsung 840 Pro 512GB off the Areca controller to the LSI HBA controller too and get rid of the old default-low zoom HW raid.

**Comment by Firefishy** [comment]
2x Samsung 860 Pro 512GB ordered.

**Comment by jburgess777** [comment]
If these machines have spare PCIe slots then I am slightly surprised you don't opt for NVMe drives. The SATA interface is a bottleneck on all fast SSDs. You can either get SSDs in a PCIe HHHL form factor or an m.2 card with adapter. A few months ago I bought a Samsung 960 EVO NVMe drive, (PRO drives are available too) and this adapter: https://www.amazon.co.uk/gp/product/B077GM755X

**Comment by Firefishy** [comment]
New 2x 512GB disks installed and low-zoom moved across to them. Failing disks haven't been pulled yet. Machine only has 2x PCI-E free with 1 complete obscured by RAID card. Remaining PCI-E is 4x.

**Comment by Firefishy** [comment]
I moved 2x good Samsung SSD 840 PRO 512GB to the LSI controller. According to SMART both have around 40% of write capacity left. (sde/sdf respectively)

**Comment by Firefishy** [comment]
I have removed the WD6000HLHX and also a WD 300GB disk that had failed.

**Comment by Firefishy** [comment]
I left the failing WDC WD1000DHTZ on the areca, but added a stock WDC Red 2.5" 1TB disk as hot-spare.
