### ISSUE TITLE
add https to uptime.openstreetmap.org

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/operations#235]
http://uptime.openstreetmap.org/ is a CNAME to statuscake's service.

They recently added the feature to allow SSL. https://www.statuscake.com/kb/knowledge-base/using-public-reporting-cname/ *) Basically one needs to change the CNAME to `uptimessl.statuscake.com` and I think change a toggle in their dashboard. They do http => https redirect as well.

*) Blog entry says "Created October 19, 2015" but I use them for one of my websites as well and asked their support. The SSL feature was only added last month.

**Comment by tomhughes** [comment]
Done.
