### ISSUE TITLE
Visual Editor loading error

### ISSUE THREAD

**Issue by rugk** [openstreetmap/operations#238]
Loading the visual editor fails with this error:
> Fehler beim Laden der Daten vom Server: Es konnte keine Verbindung mit dem Server hergestellt werden. Soll der Vorgang erneut durchgeführt werden? [Cancel] [Okay]

(loosely translated it just says it could not get data from the server, as it had no connection)

The URL, which fails to load is this:
> https://wiki.openstreetmap.org/w/api.php?action=visualeditor&format=json&paction=parse&page=StreetComplete%2FQuests&uselang=de&oldid=1636429

**Comment by rugk** [comment]
It's the URL that does not load when I look into the network console. 

But now it loaded, so maybe it was just temporarily.

**Comment by tomhughes** [comment]
Yes the server is clearly having problems but I don't think it's specific to that page or to the visual editor.
