### ISSUE TITLE
Failed disk in ramoth

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#24]
@Firefishy reports that ramoth has a failed disk

**Comment by Firefishy** [comment]
Replacement disks have been ordered via OSMF Treasurer.
I think @zerebubuth will install.

**Comment by zerebubuth** [comment]
Yup. The replacement disk has arrived - along with a couple of spares, which I'll try to get us some space to store at IC... just in case. Hopefully the high temperatures this week haven't done any lasting damage.

**Comment by tomhughes** [comment]
Two failed disks in ramoth have been replaced.
