### ISSUE TITLE
Grindtooth DIMM failure

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#240]
1x 4096MB DIMM in Grindtooth has failed and should be replaced.
```
Processor #:                     1 of 2
Module #:                     8
```

**Comment by tomhughes** [comment]
Machine is now and seemingly failing to recognise it's RAID card which @Firefishy suspects may be related to the failed memory.

**Comment by Firefishy** [comment]
grindtooth's onboard P410 raid controller has completely failed. I replaced the machine with a new DL360 G7,
