### ISSUE TITLE
osmose.openstreetmap.fr redirects to HTTP

### ISSUE THREAD

**Issue by rugk** [openstreetmap/operations#241]
> When I manually input https://osmose.openstreetmap.fr , it automatically redirects me to osmose.openstreetmap.fr/en/map/ , without the https:// out front.

from original report in https://github.com/EFForg/https-everywhere/issues/16463 

---

I guess this should be fixed. HTTPS should be the default nowadays!

**Comment by tomhughes** [comment]
You might be right, but that's an openstreetmap.fr site so you will need to contact OpenStreetMap France about it - we only deal with openstreetmap.org domains.

**Comment by franklinyu** [comment]
I think it’s https://github.com/osm-fr ? Not sure which repository to look for.

**Comment by rugk** [comment]
Think so, yes, thx. Opened at https://github.com/osm-fr/osmose-frontend/issues/106.
