### ISSUE TITLE
Wiki tries to load unsafe scripts

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/operations#243]
Wiki.osm.org tries to load unsafe scripts, causing users to see browser warnings.
https://bugs.chromium.org/p/chromium/issues/detail?id=882177
Must be related to #190 but I couldn't add a comment there.

**Comment by tomhughes** [comment]
Being loaded over http does not, in and of itself make a script "unsafe" so the basic premise here appears to be flawed.

There's not much we can do anyway - we're just running upstream mediawiki code so this will get fixed as and when they fix it.

**Comment by Firefishy** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/13713e5c16b9715fbae41cfe88067628041d3270
