### ISSUE TITLE
Disk space is getting tight on ouroboros

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#246]
Disk space is getting tight on the wiki machine (ouroboros) so we should at what can be done to increase it - currently it is at 80% or so but peaking at over 92% during the daily backup.

It's current 4x146Gb disks in RAID6 for ~285Gb total array size.

**Comment by Firefishy** [comment]
I wonder if the machine has 8x bays. @pnorman any chance you have a photo?

**Comment by pnorman** [comment]
![image](https://user-images.githubusercontent.com/1190866/45521765-4fefb900-b774-11e8-90b5-b97ac42301c2.png)

I'm not familiar enough with HP machines to be 100% sure, but looks like the top are solid.

.5 TB SATA drives are about £70-£100 from [reputable manufacturers](https://www.newegg.com/global/uk/Product/ProductList.aspx?Submit=ENE&N=100196041%20600038463%208000%20600038502%20600038492%20600038491%2050001077%2050001157%2050001183%2050001404%2050001455%20600038519&IsNodeId=1&bop=And&Order=PRICE&PageSize=36), less than the cost on 10k drives. The cheapest option might be to switch to a raid1 array of SSDs, which would also be a performance boost.

**Comment by Firefishy** [comment]
Damn. That is a 4x bay machine. There is a part upgrade to take it to 8x bay, but I'd say beyond what is reasonable to ask remote hands.

My suggestion would be to swap out each disk slowly to HP 300GB or 600GB 10k SAS disks, then grow the RAID.

**Comment by Firefishy** [comment]
Example of the upgrade extra backplane kit: https://www.ebay.co.uk/itm/HP-DL360-G6-G7-SFF-SAS-Backplane-Kit-w-screws-516966-B21-532147-001-532391-001/222872808446

**Comment by Firefishy** [comment]
I have ordered 20x HP 300GB 2.5" disks for stock.

**Comment by Firefishy** [comment]
I have 2nd backplane and will install 8x 300GB.

**Comment by pnorman** [comment]
![image](https://user-images.githubusercontent.com/1190866/49686020-12fd3f00-faa3-11e8-8ed5-3018c8348f14.png)
Upgraded
