### ISSUE TITLE
Adding "Maps" extension to the main wiki

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#249]
It was recently discussed whether to add a newer (and more reliable) maps extension to the main wiki at [Talk:Wiki](https://wiki.openstreetmap.org/wiki/Talk:Wiki#Map_extensions). The result was basically to give ["Maps" extension](https://www.mediawiki.org/wiki/Extension:Maps) a try. 
It would be great if you would install it. 

I wrote a file containing the configuration of the extension: https://github.com/Tigerfell/chef/tree/master/cookbooks/mediawiki/templates/default (I do not want to add a pull request, as I am not sure if I created the correct file at the correct place). The configuration file disables undesired non-open map and geocoding APIs and limits the numbers of tile providers.

**Comment by tomhughes** [comment]
Given that we already have two map extensions installed I don't really want to install yet another one on a "give it a try" basis. I'd rather we properly evaluate the options and try and decide what is best and that we have buy in that people are going to use it, and to convert all the existing maps to use it so we can get rid of the old extensions...

**Comment by Tigerfell** [comment]
Sorry, I do not understand. That was exactly what I have done. 

> The result was basically to give "Maps" extension a try.
referred to the fact that someone said that he could not judge without seeing it alive.

**Comment by AndrewHain** [comment]
Is there an active test wiki that could be used to demonstrate how we would use this extension then?

**Comment by tomhughes** [comment]
So a major problem seems to be that the "Maps" extension doesn't exist in the normal places - ie as a mirror under https://github.com/wikimedia...

**Comment by tomhughes** [comment]
Well I tried installing directly from their github repo but it just errors, so I think this one is a bust I'm afraid.

**Comment by Tigerfell** [comment]
Have you tried it using [Composer](https://www.mediawiki.org/wiki/Composer/For_extensions)?
Their manual suggests that (https://www.semantic-mediawiki.org/wiki/Maps/Installation).

**Comment by tomhughes** [comment]
We don't have any support for installing using composer in our cookbooks and I don't really want to add it because as I understand that requires running composer at the top level, which will make random changes to the libraries being used by the mediawiki core.

**Comment by Tigerfell** [comment]
Composer seems to be a hard requirement for this extension.
The Composer manual says that it installs the libraries in a folder within the project, but does not install anything globally. Source: https://getcomposer.org/doc/00-intro.md#dependency-management. 

Is there a way of trying that out? Maybe in a less sensitive environment?

**Comment by tomhughes** [comment]
Believe me. I have run composer in the root of our wiki install and had to clean up the resulting mess. The vendor directory is exactly the thing I don't want it to mess with when I said globally I meant "global to the wiki" not "global to the whole system".

Here's the problem - when you run composer yes it will install the extension and and libraries it needs but it will also feel free to update any other libraries which are already installed (within the constraints specified by the `composer.json` for the main wiki and any extensions) which is fine in theory, if mediawiki has specified it's dependencies right and no upstream has published a new version of a library which accidentally breaks something.

Right now we stick with the library versions used by wikimedia upstream and published by them as part of the mediawiki release which hopefully minimises risk.

**Comment by Tigerfell** [comment]
Ok, then thanks for trying all of that, the helpful explanations, and never mind. 

I guess we will search for an alternative then and put it up in a new issue / request ...

**Comment by JeroenDeDauw** [comment]
> So a major problem seems to be that the "Maps" extension doesn't exist in the normal places - ie as a mirror under https://github.com/wikimedia...

It does not matter where the extension is developed for deployment or usage

**Comment by tomhughes** [comment]
Well no, but our preferred (and default) way of deploying extensions is from the wikimedia github repos because they are all setup in a common way with branches named after mediawiki versions so we can be sure we are tracking changes that are appropriate for the mediawiki release we are running.

Plus it means deploying an extension for us is about three lines of code in chef.

We can (and sometimes do) deploy from other repos but it's definitely not the preferred option.

**Comment by JeroenDeDauw** [comment]
Fair enough

Beware that those version branches are arbitrarily made off master when the MW version is bumped. If I where running a wiki I'd not be using those.

**Comment by Tigerfell** [comment]
When installing the Wikibase extension, we circumvented the problems with Composer by setting up a [separate repo](https://github.com/nyurik/OsmWikibase) and using Composer there only if I understand it correctly (the extension was also changed which is not necessary in this case). Would that be an option in this case as well?

@tomhughes Sorry for coming up with yet another suggestion, but I am very keen to get this going one or the other way as Simple Image extension is now finally broken and the alternatives for providing at least a slippy map are not very appalling:
* employing [Kartographer](https://www.mediawiki.org/wiki/Extension:Kartographer) (has dependencies as well and is not able to show standard tiles)
* re-coding SlippyMap extension and *maintaining it* (more extensive coding involved including maintenance)

**Comment by tomhughes** [comment]
We are capable running composer inside an extension and do that for several extensions (including Wikibase I think) to get any libraries needed by the extension but that is different to running it at the top level which is what is needed to actually install the extension itself via composer.

**Comment by Tigerfell** [comment]
Sorry, you already pointed that out and I forgot it.

So, effectively we have the choice between recoding SlippyMap extension and maintaining it or doing nothing, right?

**Comment by tomhughes** [comment]
Well I'd love to find a way to make the Maps extension work for us but I don't currently see a clean way to do it. I did spend several hours trying to make it work without much success...

**Comment by mmd-osm** [comment]
Pinging @nyurik, as he might know someone who could help us out here.

**Comment by nyurik** [comment]
Sorry @mmd-osm , i'm not a composer expert to be honest.  Usually the best course of action is to try these things on a copy of the production server (which is exactly what i did for the wikibase install).  It would be a bit tricky to set it up though :(

**Comment by tomhughes** [comment]
Well I'm sure it will work if we do that though it will mean a major re-engineering of our cookbooks to switch to using composer for mediawiki base instead of the upstream git repository and to provide a means of building a shared `composer.local.json` to cover composer supported modules - one of the biggest problems is that installing a module requires editing it into a shared file rather than being able to drop it in which is easy for manual installs but hard for automation.

The concern is that once we've done that work we never know what libraries we're going to be running and how library they are to work - not every library in the mediawiki `composer.json` is version locked and they don't publish a `composer.lock` and even if they did adding an extension would require rebuilding it.

I'm also not at all clear if installing extensions this way is the "future" or a dead end as all the mediawiki pages about it are unclear and inconsistent.
