### ISSUE TITLE
Adding "MultiMaps" extension to the main wiki

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#252]
This is a follow-up to #249. The MultiMap extension allows the display of maps in MediaWiki using Leaflet ([Link to MediaWiki's extension page](https://www.mediawiki.org/wiki/Extension:MultiMaps)). 

The following points should be accessed before adding:

- [x] problems with composer: If I see it correctly, the requirements are defined in https://github.com/wikimedia/mediawiki-extensions-MultiMaps/blob/master/composer.json. Does it work with our configuration?
- [x] support of for an additional tile address using Leaflet: If the extension could support Transport tiles from thunderforest.com as well as the main style, it could replace the current slippy map completely, which is the goal. 
I could take care of this one if the composer configuration works.
- [x] disabling other map providers: straightforward setting change

**Comment by tomhughes** [comment]
All of those composer requirements are dev only - there is nothing needed for ordinary run time deployments.

**Comment by tomhughes** [comment]
Fixed by https://github.com/openstreetmap/chef/pull/241.
