### ISSUE TITLE
Budget 2019

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#256]
It's that time of year again, when OWG needs to make a budget.

We're working with the OSMF treasurer on examining our 2018 expenditure (so far), which might prove useful. But we also need to decide what we want to spend money on in 2019. For clarity, OSMF works on a calendar year so from 1st January - 31st December basis.

**Comment by pnorman** [comment]
Our hosting costs should be easy to budget, as with our consumables. The two big unknowns are consulting and capital expenses. For consulting, I'd like to carry forward the 2018 PostgreSQL stuff, and add to it for #154, or do it under the existing item. We've got increased capacity, so I could see this getting done.

For capital expenses, a ballpark would be 20% of the current replacement cost. I'd like to have specific plans, but we're not likely to get that done by Jan.

**Comment by pnorman** [comment]
We're halfway into feb right now without progress.

Should we budget 20% of current replacement cost as a best guess? This is what we need to average at in order to replace hardware with a 5 year lifecycle.

**Comment by mmd-osm** [comment]
2019 is over in 7 weeks. Time to close this issue.
