### ISSUE TITLE
Fume - Pull failed disk

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#26]
Fume's disk port 1I:box 1:bay 8 is stuck in a fail, OK, rebuild cycle. 

The disk should be pulled to allow a hot-spare to take over.

Disks 2I:1:4 and 1I:1:6 should also be pulled due later (after rebuild) due to flagged SMART Predictive Failure.

**Comment by gravitystorm** [comment]
Has this been tackled?

It looks like there's another failed disk on fume, we get the following report each day:

```
/dev/cciss/c0d0: (Smart Array P400) RAID 1 Volume 0 status: OK.   At least one spare drive designated.
/dev/cciss/c0d0: (Smart Array P400) RAID 1 Volume 1 status: OK.   At least one spare drive designated.  At least one activated on-line spare drive is completely rebuilt on this logical drive.  At least one spare drive activated.
  Failed drives:
         connector 2I box 1 bay 4                 HP      EG0146FAWHU                          6SD0JKPA0000B04918RR     HPDD

  Drives currently substituted for by spares:
         connector 2I box 1 bay 2                 HP      DG0146BALVN                          3SD0V0BJ00009001MGVY     HPD4

    Total of 1 failed physical drives detected on this logical drive.
```

What needs to be done to sort this out?

**Comment by tomhughes** [comment]
@Firefishy did chase them, and he claimed to have pulled the failed disks, but the mails started up again fairly quickly thereafter,

**Comment by Firefishy** [comment]
I'll follow up. I think this might be another disk the machine that has failed.

**Comment by Firefishy** [comment]
I've rebuilt the raid on fume without the faulty disk. We should stop getting error reports now.
