### ISSUE TITLE
Switch Amsterdam AM6 to redundant 1Gbps connection

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#260]
We currently have a 1Gbps connection at Equinix. We're nearing it's capacity
![image](https://user-images.githubusercontent.com/1190866/51015760-49a2fb00-1522-11e9-80f4-4b88a3e55b9c.png)

The biggest single user seems to be Apache on ironbelly
![image](https://user-images.githubusercontent.com/1190866/51015835-8838b580-1522-11e9-8a1a-c34fd73b7403.png)

Volume is up significantly from 9 months ago, are we sending more traffic to ironbelly?

![image](https://user-images.githubusercontent.com/1190866/51015881-bc13db00-1522-11e9-95a6-78a1d759f4ed.png)

If we want to upgrade our network connection, do we want to go for 2x GigE, 1x 10 GigE, or 2x 10 GigE?

**Comment by tomhughes** [comment]
Saying "apache" isn't very helpful - it's more useful to know what machine you're talking about than what service.

Are you saying ironbelly is the source of the extra traffic?

**Comment by pnorman** [comment]
Edited to add missing info.

> Are you saying ironbelly is the source of the extra traffic?

Yes - it's got an order of magnitude more traffic than pre-move.

**Comment by tomhughes** [comment]
Indeed but I don't understand why...

It appears that grisu was carrying similar load when it was standing in during the move so the jump appears to have been in mid July at the point when load was transferred from ironbelly to grisu for the move.

I thought for a minute that it was when heanet stopped mirroring, and we stopped redirecting to them (see #210) but that was in May.

That said we're only talking about 150-200Mbit/s average, so about 20% of the capacity.

**Comment by pnorman** [comment]
The plan is to switch to HEnet and a 10Gbps connection in Amsterdam

**Comment by Firefishy** [comment]
- I've asked HEnet (2x 10G) + Equinix Cross Connect (AM6/AM7) for quotes
- I've emailed AMS-IX asking if they can help or point us at anyone.
- I've asked [Vorboss](https://vorboss.com/) if they can quote. They are based in AM6. (via 2x 10G cross connects)

**Comment by grischard** [comment]
Can we also ask Equinix about the prices for a connection inside the same DC? The difference might not be prohibitive.

**Comment by grischard** [comment]
Let's also ask other ISPs in AM6 if we can't get a satisfying response.

**Comment by pnorman** [comment]
Cross-connections between AM6 and AM7 HE are about the same cost as within AM6. I propose moving ahead with HEnet. The other option would be starting to do BGP stuff.

**Comment by grischard** [comment]
Let's reassess our capacity planning after #678 - ironbelly will use a lot less bandwidth with planet files on S3.

**Comment by grischard** [comment]
[Prometheus bandwidth stats](https://prometheus.openstreetmap.org/d/CMu3T1R4k/switch-monitoring?orgId=1&refresh=5m&from=now-4M&to=now) do not support migrating to 10G for now, especially with #678 coming up.

**Comment by grischard** [comment]
HE order form submitted for 2x1G.

**Comment by Firefishy** [comment]
HE Diverse Cross Connects are now connected. Patched across to the 2x switches.
Network config to follow.

![Patches labeled](https://github.com/openstreetmap/operations/assets/248188/34a492cc-bd95-4542-85a7-286ba7e43a59)
![Patch panel](https://github.com/openstreetmap/operations/assets/248188/f044dc42-f309-4973-8ff2-5378475a4602)
![SW2 link up](https://github.com/openstreetmap/operations/assets/248188/3f84fb37-faeb-46a3-88f0-93a6ed5d0d85)
![SW1 link up](https://github.com/openstreetmap/operations/assets/248188/11ea1cef-8bfe-430d-a232-acbfc6d8eed9)

**Comment by Firefishy** [comment]
We have higher than expected signal loss on a new cross connect to HE. It is being investigated by the team at Equinix.

**Comment by Firefishy** [comment]
The issue with higher than expected signal loss has now been resolved. The issue was a faulty patch cable on remote end.

**Comment by Firefishy** [comment]
Blocked by decision on Private ASN BGP ($$$?) or static IP subnet routing.

**Comment by Firefishy** [comment]
Both HE links are up and working. We have switched DNS.

**Comment by grischard** [comment]
Email sent to Cogent to cancel.

**Comment by Firefishy** [comment]
"So, we hereby confirm that service will be ceased by 1st August 2023."
