### ISSUE TITLE
Reconfigure mailman to avoid kicking members off the lists

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#262]
Due to DMARC settings on some mailing list senders emails, other innocent mailing list subscribers (like me!) keep getting kicked off of the mailing lists. We should reconfigure mailman to avoid kicking innocent members off of the lists.

The basic problem is that some email providers (such as Yahoo) have set DMARC policies that mean when their customers emails go via any mailing lists, the DMARC validation will fail. When a victim uses an email service that respects the DMARC policy (like Gmail), the offending mail is bounced. Mailman counts these bounces, and then eventually kicks the victim off the list. This happens every month or so, across our lists. Note that it's the innocent victim (e.g. Gmail user), not the sender (e.g. Yahoo user), who gets kicked off.

Other list owners have dealt with this by changing their mailman configuration, to subtly change the DMARC-affected emails. Linuxchix has a detailed explanation (better than mine) about the problem, and their solution:

https://www.linuxchix.org/content/mailing-list-changes

We should make similar changes to our mailing list configuration.

**Comment by tomhughes** [comment]
Our mailman is too old to support these options.

**Comment by Firefishy** [comment]
The required version of mailman is available in Ubuntu 18.04 but upgrading is currently blocked by https://github.com/openstreetmap/operations/issues/149 and https://github.com/openstreetmap/operations/issues/220

**Comment by tomhughes** [comment]
It's not something we can just upgrade - the OS needs to be upgraded and we can't do that because the machine also runs OSQA for help.openstreetmap.org and that is dead and won't run on newer versions.

I will just reiterate that DMARC with p=reject is fundamentally broken unless you are going to ban all your users from subscribing to any mailing lists or forwarding mail in any way because it completely ignores decades of internet standards.

**Comment by tomhughes** [comment]
As shenron has now been updated I have set `dmarc_moderation_action` to "munge from" for all lists and made it the default for new lists.

**Comment by thiagocrepaldi** [comment]
> As shenron has now been updated I have set `dmarc_moderation_action` to "munge from" for all lists and made it the default for new lists.

Thank you for sharing the *exact* solution. Helped me a lot.
