### ISSUE TITLE
saphira/yevaud constipated again?

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/operations#267]
I modified an object around 2019-01-24 08:45.  Six hours later, it's still not rendered.  According to the debug, yevaud load average is hovering around 30.  Dunno if that load average is normal or not.  Yesterday changes appeared within a couple of minutes, today it's 6 hours and counting.

**Comment by tomhughes** [comment]
No it's just busy because of the style change last weekend so is unlikely to have time to do non-essential renders during the european day time at the moment.
