### ISSUE TITLE
Slow Carto tile performance

### ISSUE THREAD

**Issue by NKAmapper** [openstreetmap/operations#268]
Performance for Carto tiles has been deteriorating for several months, to a point now where Carto is not really usable anymore in my country (Norway). Tiles are slow and missing, and I have not seen rendering of updates for several days. These observations are shared by my fellow mappers here.

The Swedish mailing list are discussing similar [problems](https://lists.openstreetmap.org/pipermail/talk-se/2019-January/003513.html).

Debug report:

```
tile.openstreetmap.org debug
 
Server Stats
 
Cache Server: ridgeback.openstreetmap.org
 
Render Server: orm.openstreetmap.org
Load Average: 26.57
 
File Status
 
world_boundaries-spherical.tgz last modified: Tue Jun 4 11:59:57 2013
simplified-land-polygons-complete-3857.zip last modified: Thu Jan 31 09:07:45 2019
ne_110m_admin_0_boundary_lines_land.zip last modified: Tue Jun 4 12:00:51 2013
land-polygons-split-3857.zip last modified: Thu Jan 31 09:08:19 2019
antarctica-icesheet-polygons-3857.zip last modified: Thu Jan 31 10:13:08 2019
antarctica-icesheet-outlines-3857.zip last modified: Thu Jan 31 10:13:18 2019

```

**Comment by tomhughes** [comment]
I've reduced the bandwidth target for that server but mostly the problem seems to be that the Scandinavian countries are producing far more load that our last log analysis (done only a few weeks ago) says they should - like twice what we are expecting. So more load is being sent to that server than intended.

The loading is also really odd - this week Monday was really high, Tuesday lower, Wednesday lower again, Thursday the same as Wednesday then today it's back to Monday levels. Normally I would expect to see fairly similar levels through the week with a drop at weekends.

**Comment by kocio-pl** [comment]
Maybe there is some kind of a big data import?

**Comment by NKAmapper** [comment]
> Maybe there is some kind of a big data import?

Not that I can see in the changesets for Norway. There is one person doing a topography import but only in one municipality, and not any larger than previous imports. There was a large address update in December.  Our community is small so even low volume activity could show up as a big variation.

**Comment by tomhughes** [comment]
I'm not sure what a data import would have to with how many tiles are requested either...

**Comment by kocio-pl** [comment]
You're right probably... Do you see some consistent pattern in these requests, like for example most of it coming from single IP (tiles leeching) or so?

**Comment by tomhughes** [comment]
Well the effect of my target reductions has been to move Finland from the Norwegian cache to the Danish cache and that seems to have moved about 40Mbit/s of traffic which is something like three times our expectation.

So it looks like Finland is the issue at any rate - the Norwegian cache looks much better now and the Danish cache is copy with the extra load OK as it had plenty of headroom.

**Comment by NKAmapper** [comment]
Performance improved, however I am getting very few tiles at zoom 18 and 19.
Example: https://www.openstreetmap.org/#map=19/59.48291/8.62755

Also, I still cannot see any updates done in the past week or so.
