### ISSUE TITLE
Vector export problems

### ISSUE THREAD

**Issue by kocio-pl** [openstreetmap/operations#270]
We are currently trying to investigate why exporting map to vector format gives raster inside (https://github.com/gravitystorm/openstreetmap-carto/issues/3653). There might be a solution for this, but we don't know which script is used for it currently. Is this https://trac.openstreetmap.org/browser/sites/tile.openstreetmap.org/cgi-bin/export or maybe something else?

Is this the right place to ask it, BTW?

**Comment by tomhughes** [comment]
It's a bug in mapnik - https://github.com/mapnik/mapnik/issues/3749 which has a PR opened today in https://github.com/mapnik/mapnik/pull/4029.

**Comment by kocio-pl** [comment]
Just for a reference - workaround is applied here: https://github.com/gravitystorm/openstreetmap-carto/issues/3653
