### ISSUE TITLE
Failing Disk in rhaegal

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#272]
Rhaegal has a failing disk that should be replaced.

`Device: /dev/sdd, new Self-Test Log error at hour timestamp 27963
Device info:
[SEAGATE  ST9146852SS      0005], lu id: 0x5000c50017792edb, S/N: 3TB0V88N00009016E7XT, 146 GB`

**Comment by hbogner** [comment]
Why didn't you ping me on this? I was there almost once a month, but didn't go to the server room. I have spare drive on my table ready to be replaced. Will go there again in few days and replace the drive.

**Comment by Firefishy** [comment]
@hbogner Cheers. Normally we'd email but I'm completely overstretched at the moment.

**Comment by tomhughes** [comment]
Disk has been replaced by @hbogner.
