### ISSUE TITLE
CT2000MX500SSD1 SMART pending issue in orm

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#273]
The 2x CT2000MX500SSD1 disks in orm are frequently reporting SMART `Currently unreadable (pending) sectors`.

Normally we replace disks as soon as disks start reporting issues with SMART health, but these disks are relatively new. The pending sectors recover after an hour or 2.

Search doesn't reveal others having the same issue.

**Comment by Firefishy** [comment]
If we don't believe the issue is a concern, we should try mute it. If it is a concern, we should try fix it... `fstrim` or improved temperature stability or replace.

**Comment by pnorman** [comment]
I'm inclined to leave it alone since we've ordered a replacement for the entire server.

**Comment by pnorman** [comment]
Orm is replaced so the failed disks are no longer an issue.
