### ISSUE TITLE
Review elevated user rights of inactive wiki users

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#274]
I suggest to review the privileges of inactive users with admin rights in the main wiki. I guess the best way would be to contact the relevant users or is there a policy? Please feel free to forward this in case the OWG is not responsible. 

The following admin users have not been active (no contributions, no logged actions) since at least 9 February 2018:
Abuse filter, Aude, Avatar, CoreyBurger, Emj, Gnonthgol, Matt, Morwen, Oliver.kuehn, Putnik, Simone

Users inactive for the span of two years:
Abuse filter, Aude, Avatar, CoreyBurger, Emj, Gnonthgol, Morwen, Oliver.kuehn, Simone

The log is available at https://wiki.openstreetmap.org/w/index.php?title=Special%3ALog&user=Abuse+filter and the contributions are available at https://wiki.openstreetmap.org/w/index.php?limit=1&title=Special%3AContributions&contribs=user&target=Abuse+filter.

**Comment by tomhughes** [comment]
The wiki has generally been self governing and OWG haven't historically been involved in decisions about adding and removing administrators.

**Comment by Tigerfell** [comment]
Okay, I guess I need to address this to @Firefishy and @harry-wood then?

**Comment by grinapo** [comment]
@Tigerfell what would be the **purpose** of this demotion wave? Are these people hurting OSM, or the Wiki, or cause any harm or inconvenience whatsoever?

(There are usually two motives along these lines on Wikipedia: one is that "I am not admin so they shouldn't be either" and the other is "I am admin and they are not worthy", neither of those usually have any real reason apart from personal emotions, and I find it troubling to pop up here. I am not admin and I don't wish to be.)

**Comment by Tigerfell** [comment]
No one does any harm. As an editor in the wiki, I would like to know who is responsible for the wiki and certain community requests. 
To be more concise, we recently had a dispute about deletion requests in the wiki and nominations of users for adminship initiated by an admin himself, but we do not have a process for that and the users with the ability to change something were not involved. As you always have to contact the admins/beaurocrates individually, I think it is beneficial to know who is available for the requests. 

I am sorry for annoying the people on GitHub but I though the OWG is in charge of this. 

Since your post suggests conflicting interests on my side, I would like to declare that I was, among someone else, proposed as an admin, but I declined for now. You can retrieve this from https://wiki.openstreetmap.org/w/index.php?title=Talk:Wiki&oldid=1784834#Wiki_Adminship_for_Minh_Nguyen (including the following section).

**Comment by zerebubuth** [comment]
I'm "Matt" on the wiki, and I should definitely be demoted. Here are a couple of reasons to demote me, off the top of my head:

1. If people try to contact me as a wiki admin, they'll be disappointed that I probably won't see their message. Users are probably happier if the list of admins corresponds to the list of people who can help them with admin-related issues.
2. I don't log into the wiki often, so would be slow to notice a hack of my account. In general, I shouldn't hold any credentials that I don't use regularly.

**Comment by harry-wood** [comment]
I think it's logical for server admins like Matt to have all the access to these things, plus I suppose people might _expect_ you to have access, in case of wiki-based emergencies. But... no point people having permissions they don't want. It looks like you're the only member of OWG who has avoided touching the wiki for a whole year Matt :-)

Thanks for the inactive list @Tigerfell . I've just sent Talk page messages to those people. If we don't hear back from them then I will remove them as admins (at least unless/until they request to be re-added in future). That's a good starting point for slimming down the admins list, which I think is worth doing a little bit at least.

**Comment by zerebubuth** [comment]
I might have avoided touching the wiki for a whole year in part because I'm [retired from OWG](https://wiki.osmfoundation.org/wiki/Operations_Working_Group#Who_we_are) :wink: 

In case of wiki-based emergencies, where through some extreme set of circumstances none of the existing wiki admins nor other sysadmins were available, I could always reach into the database directly. I think it's clearer and more transparent to reserve wiki adminship for people who want to be actively involved in wiki administration - rather than the "admin of last resort" that I might represent.

**Comment by Tigerfell** [comment]
Having a dedicated user group might be a solution? These users would only have the power to block users and to remove admin flags (otherwise admins could unblock themselves). This could clarify the situation and minimise the risks. 


Feb. 12, 2019, 12:20 p.m. by notifications@github.com:

**Comment by putnik** [comment]
I am an administrator of the OSM wiki (inactive) and several Wikimedia projects. And I support the principle that is used in some Wikimedia communities. If an administrator does not use their flag for a long time (e.g. six months), then we should ask they if the flag is still needed. If they answers negatively or does not answer (for example, within a month), then the flag should be removed.

**Comment by putnik** [comment]
Important note: Abuse filter is a technical account used by the AbuseFilter extension. Regardless of the decision that will be made, you do not need to remove the admin flag from it.

**Comment by Tigerfell** [comment]
Can I close this or is there a need for further discussion here?

**Comment by harry-wood** [comment]
I just went ahead and removed admin permissions for those inactive wiki users: Aude, Avatar, CoreyBurger, Emj, Gnonthgol, Matt, Morwen, Oliver.kuehn, Putnik, and Simone. So [the admins list](http://wiki.osm.org/Special:ListAdmins) is looking a little bit shorter.
