### ISSUE TITLE
No new planet file for 15 days

### ISSUE THREAD

**Issue by jwass** [openstreetmap/operations#275]
Hello. The latest planet file is from 1/28, posted on 1/31 - https://planet.osm.org/planet/2019/. It looks like there was no new planet file posted the week of 2/4.

Just wondering if this is expected or when an updated planet file will be posted. Apologies if this has been discussed on the mailing lists or elsewhere. Thanks!

**Comment by tomhughes** [comment]
The dump failed last week but there should be one later this week.
