### ISSUE TITLE
Ironbelly eth1 has no link

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#277]
ironbelly's 2nd ethernet connection eth1 link (bond0 backup) is down. 

Cabling should be checked and issue corrected.

**Comment by Firefishy** [comment]
@pnorman This is likely a worthwhile task for remote hands.

Could be as simple as ensuring the cable is plugged in or replacing the cable.

**Comment by pnorman** [comment]
Remote hands request submitted in Equinix order 1-185586501387

per discussion I'm only having them check the cable lights, on both ironbelly and its port on the switch.

**Comment by pnorman** [comment]
![ironbelly](https://user-images.githubusercontent.com/1190866/52896568-c8710080-317e-11e9-9253-2852114b5821.JPG)
![switch 2](https://user-images.githubusercontent.com/1190866/52896573-d9ba0d00-317e-11e9-943a-0547a5e33eef.JPG)

Lights are out on ironbelly eth1 and port 23 on switch 2.

Should we have them install a replacement cable from the box?

**Comment by pnorman** [comment]
Unless there are objections I'll go ahead with a cable replacement work order over the weekend

**Comment by Firefishy** [comment]
Yes, please go ahead. It might be as simple as re-seating the cable.

**Comment by pnorman** [comment]
I've asked them to reseat the cable, then if that doesn't bring up the link lights, replace it. Equinix order 1-185612405256

**Comment by pnorman** [comment]
Both ends reseated. The switch end was not properly connected and the link lights are now turned on.

**Comment by HolgerJeromin** [comment]
I am surprised the remote hand resisted the temptation to push the cable in the first place... :)

**Comment by Firefishy** [comment]
This was also partially a test to understand how to book and instruct remote hands work at the data centre.
