### ISSUE TITLE
Elasticsearch update to 1.3.x

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#28]
Update elasticsearch chef to 1.3.x and add elasticsearch.yml custom config requirements for mediawiki (script.disable_dynamic: false)

Also see:
https://git.wikimedia.org/blob/operations%2Fpuppet/production/modules%2Felasticsearch%2Ftemplates%2Felasticsearch.yml.erb

**Comment by Firefishy** [comment]
Updated repo to 1.3.x.

Likely best to move to a managed elasticsearch.yml config

**Comment by tomhughes** [comment]
Was there a reason for only going to 1.3 when 1.7 seems to be current? In particular kibana wants 1.4 so is it OK to move the wikis to that, or do I need to keep those on 1.3 and only update the logstash instance?

I have made elasticsearch.yml managed anyway.

**Comment by tomhughes** [comment]
So it looks like 1.7 is fairly new, but 1.4 and 1.5 were available.

**Comment by Firefishy** [comment]
Newer versions now seem to be OK: https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FCirrusSearch/e53c8ea477e24d55bd1fe879221a1e649fe9db81/README#L6

**Comment by tomhughes** [comment]
Update to 1.7 seems to have gone OK. In any case this is all done now.
