### ISSUE TITLE
Tiles are not loading

### ISSUE THREAD

**Issue by PercyP** [openstreetmap/operations#281]
Hi,

I keep getting 404 errors and the map does not display. In chrome inspect it is saying these tiles do not exist:

https://a.tile.openstreetmap.org/16/53857/38957.png
https://b.tile.openstreetmap.org/16/53858/38957.png
https://c.tile.openstreetmap.org/16/53859/38957.png

If I paste the url into google it comes back with an error message saying the file is not found on the server.

Is anyone else experiencing this problem?

**Comment by tomhughes** [comment]
What does https://tile.openstreetmap.org/cgi-bin/debug say about which cache server and render server you are using?

**Comment by PercyP** [comment]
Hi Tom,

I clicked on that link. Does the following mean anything to you?

tile.openstreetmap.org debug
Server Stats
Cache Server: rimfaxe.openstreetmap.org

Render Server: orm.openstreetmap.org
Load Average: 23.09

File Status
world_boundaries-spherical.tgz last modified: Tue Jun 4 11:59:57 2013
simplified-land-polygons-complete-3857.zip last modified: Mon Feb 25 09:11:05 2019
ne_110m_admin_0_boundary_lines_land.zip last modified: Tue Jun 4 12:00:51 2013
land-polygons-split-3857.zip last modified: Mon Feb 25 09:11:40 2019
antarctica-icesheet-polygons-3857.zip last modified: Mon Feb 25 10:16:59 2019
antarctica-icesheet-outlines-3857.zip last modified: Mon Feb 25 10:17:08 2019
Browser Request Headers
HTTP_REFERER: https://github.com/openstreetmap/operations/issues/281
CONTEXT_DOCUMENT_ROOT: /srv/tile.openstreetmap.org/cgi-bin/
SERVER_SOFTWARE: Apache/2.4.29 (Ubuntu)
CONTEXT_PREFIX: /cgi-bin/
SERVER_SIGNATURE:

Apache/2.4.29 (Ubuntu) Server at tile.openstreetmap.org Port 443

REQUEST_METHOD: GET
SERVER_PROTOCOL: HTTP/1.0
QUERY_STRING: 
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
HTTP_CONNECTION: keep-alive
SERVER_NAME: tile.openstreetmap.org
REMOTE_ADDR: 130.225.254.109
HTTP_VIA: 1.1 rimfaxe.openstreetmap.org:3128 (squid/2.7.STABLE9)
SERVER_PORT: 443
SERVER_ADDR: 130.117.76.3
DOCUMENT_ROOT: /srv/tile.openstreetmap.org/html
SCRIPT_FILENAME: /srv/tile.openstreetmap.org/cgi-bin/debug
SERVER_ADMIN: webmaster@openstreetmap.org
SCRIPT_URI: https://tile.openstreetmap.org/cgi-bin/debug
HTTP_HOST: tile.openstreetmap.org
SCRIPT_URL: /cgi-bin/debug
HTTPS: on
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_CACHE_CONTROL: max-age=518400
REQUEST_URI: /cgi-bin/debug
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
GATEWAY_INTERFACE: CGI/1.1
HTTP_X_FORWARDED_FOR: 81.152.47.38, 127.0.0.1
SCRIPT_NAME: /cgi-bin/debug
REMOTE_PORT: 49075
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.9
REQUEST_SCHEME: https

**Comment by Zverik** [comment]
404 for me as well. Cache is `cmok`, render is `orm`.

**Comment by PercyP** [comment]
Hi,

it seems to be working today :)

**Comment by Zverik** [comment]
First one does, `b` and `c` do not.

**Comment by PercyP** [comment]
If you click on the links above that I posted the do work. My map works correctly now.

**Comment by pnorman** [comment]
Replacing orm appears to have fixed the render capacity issues and the CDN has more headroom now from a combination of more nodes and blocking apps faking their user-agent or referrer. Any new issues are unlikely to be related to this one.
