### ISSUE TITLE
Upgrade HP DL360 G6 phase one

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#282]
We're planning to refresh the three spike machines in Amsterdam and Oroboros, also in Amsterdam. This is a tracking issue for visibility, but because most of the work involves quotes everything is being done by email and this issue won't have many public updates.

I'm getting quotes for 240GB or 480GB for storage, Gen8 or Gen9. 64GB RAM.

**Comment by pnorman** [comment]
Four HP DL360 Gen9 on order with 2x E5-2640v4 64GB RAM, 2x 480GB SSD.

We went for 480GB SSDs because that allows all the machines to have common parts and be interchangeable. The latter is important because the front-end machines are essentially overprovisioned to allow a failing DL360 to be replaced with an excess front-end.

**Comment by pnorman** [comment]
@Firefishy where should we have them racked? The options are a) the 6U between the shelf and Cisco RPS, or b) pull the DL180 + MSA60 and use those 4U. (a) has no cables, (b) has two sets and would need two more.

We also need 1U for the orm replacement, which I expect to be *after* the G9 boxes. (#283)

**Comment by Firefishy** [comment]
Option A. Between the shelf and Cisco RPS.

**Comment by pnorman** [comment]
29-32 reserved for the Gen9 boxes. This leaves two spaces free between them and the Cisco.

**Comment by pnorman** [comment]
Servers are installed. I still need to add the info to the table.

**Comment by Firefishy** [comment]
Servers do not have RAID controllers. We should get P440ar controllers before these machines go live.

**Comment by pnorman** [comment]
Servers are ready for use.

**Comment by Firefishy** [comment]
Learnings:
* Ensure when ordering from resellers that we specify exactly what we want. (eg: RAID controllers)
* Instructions from Remote Hands need to be very granular and ideally with supplier installer guides or images.

**Comment by gravitystorm** [comment]
Thanks for posting the learnings @Firefishy , that's very useful.
