### ISSUE TITLE
Strange network patterns with gorynych

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#284]
I've been investigating why the tiles are sometimes not working for me, and we've had reports from Russia and at #281 of other people having problems too. I don't know if they are related so I'm opening a new ticket for this, in case it's unrelated.

The [network charts](https://munin.openstreetmap.org/openstreetmap.org/gorynych.openstreetmap.org/index.html#network) for [gorynych](https://hardware.openstreetmap.org/servers/gorynych.openstreetmap.org/) are strange, and it looks to me like some external throttling (or similar) is happening during the day:

![if_eth1-day](https://user-images.githubusercontent.com/360803/53494212-8066ad80-3a9d-11e9-8fb7-6bd10d1da423.png)

It looks like this is regularly happening, but not at the weekends

![if_eth1-month](https://user-images.githubusercontent.com/360803/53494249-94aaaa80-3a9d-11e9-8651-8bd5334056c0.png)

**Comment by tomhughes** [comment]
The russians just generate stupid amounts of traffic and even that machine is insane it's probably overloaded.

I think @Firefishy was supposed to be banning a bunch of piss takers but I don't think it's happened yet.

**Comment by tomhughes** [comment]
Those traffic drops do correspond to massive CPU spikes.

If I had to guess I'd say we're hitting some sort of cliff edge in squid's internals where when traffic hits a certain level the CPU rockets and you enter a death spiral.

We really, really need to dump squid...

**Comment by mmd-osm** [comment]
> Those traffic drops do correspond to massive CPU spikes.

What's really bad here is that those CPU spikes are massive peaks of "system cpu time" (=kernel time), while the "user cpu time" percentage drops to below 25% of the usual value. Somehow squid seems to do some crazy stuff which triggers so much kernel activity. I think it would be interesting so check out `perf top` during those peaks and see what the kernel is spending all the time on.

![cpu-day](https://user-images.githubusercontent.com/5842757/53513851-8f158a80-3ac6-11e9-8e0f-ef92a64700e7.png)

**Comment by Firefishy** [comment]
I pushed some updates last night which seem to be helping a bit.

Here are some of the problems:

* Squid only uses a single thread and maxes out a CPU core.
* Nginx is struggling to get a backend connection to squid.

**Comment by Firefishy** [comment]
Seems ok now. Closing for now. If issues come back feel free to re-open.
