### ISSUE TITLE
AM6 Peering issues with Cogent

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#285]
We have recurring routing issues with our peering in AM6 with Cogent.

We should consider our options and this is the ticket to do it.

**Comment by pnorman** [comment]
From the previous quotes some of the other options were

- another ISP of similar size, for about the same price. But they seem to be the other part of a peering dispute
- A larger ISP: about 4x cost
- Equinix: About 4-8x cost
- Going with something managed: Cost TBD, I never got quotes for this. The advantage is it gets us out of some of the networking stuff.

**Comment by grischard** [comment]
See also #260

**Comment by Firefishy** [comment]
Mostly now resolved. HE.net replacement is coming soon, and has or will have own tickets. Closing this ticket now.
