### ISSUE TITLE
Decide on future of DL180 and MSA60 at Equinix

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#286]
We have a DL180 (G6?) and MSA60 racked up in Equinix. We should either decide to get them working for the original plan (?) or derack and dispose of them.

cc @Firefishy

**Comment by pnorman** [comment]
ping @Firefishy

**Comment by pnorman** [comment]
DL180 is deracked and disposed of. The MSA60 has drives in it with very old backups we want to preserve for historical reasons.

**Comment by tomhughes** [comment]
The MSA60 has now been deracked.
