### ISSUE TITLE
Should we move to serial numbered cables?

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#290]
Most larger deployments I see are using serial numbered cables. Some software (e.g. https://github.com/digitalocean/netbox) assume serial numbered cables, and Equinix's remote hands forms are designed for them too.

Should we move to serial numbers at equinix instead of labels?

**Comment by pnorman** [comment]
I'm bringing this up now because we've got the new HP Gen9 boxes coming in, and they'll need cabling.

**Comment by grischard** [comment]
Dymo heat shrink tube is a neat inexpensive way of doing this. https://www.dymo.eu/dymo-rhino-18055-heat-shrink-tubing-black-on-white-12mm.html

**Comment by Firefishy** [comment]
OSMF owns a Brother label printer, here is the equivalent: https://www.brother.co.uk/supplies/p-touch/tapes/hse/hse251
It is unlikely that Equinix will be happy me using a heat gun in the data centre ;-)

My preference is still labelling the ends, but making the labelling more generic.

**Comment by pnorman** [comment]
It's better have identifiable cables that indicate what port on switch it is
