### ISSUE TITLE
IPv6 not enabled on {a,b,c}.tile.openstreetmap.org

### ISSUE THREAD

**Issue by imcdona** [openstreetmap/operations#292]
The tile servers  {a,b,c}.tile.openstreetmap.org don't yet support IPv6. Allot of time has passed since this was last discussed in [issue 142](https://github.com/openstreetmap/operations/issues/142). Are there any show stoppers preventing you from being able to provide IPv6 connectivity at this time?

**Comment by tomhughes** [comment]
I refer the honourable gentleman to the answer given previously.

That is to say that there has been no change since the answer given in the ticket which you are already clearly aware of.

**Comment by imcdona** [comment]
You're mistaken. I don't automatically assume you're in the habit of retroactively updating the notes on tickets in a "closed" status as the situation changes.

If you don't want to keep this issue "open", maybe this should be tracked elsewhere? Should I be submitting this as a feature request somewhere else instead?

If you can point me in the right direction I'd appreciate it.

**Comment by tomhughes** [comment]
There's already an open ticket for upgrading to varnish that is referenced from the ticket you mentioned before.

Our policy (as I have stated before) is to enable IPv6 wherever we can so there is no need for a ticket for it specifically - as soon as we are able to do so we will turn it on just as we do for other services.

**Comment by imcdona** [comment]
Thanks for the clarification. I'm providing a link to the [varnish upgrade issue](https://github.com/openstreetmap/operations/issues/7) so there's a link between the these issues.
