### ISSUE TITLE
"Invalid authentication credentials" logging in via GitHub

### ISSUE THREAD

**Issue by Chaz6** [openstreetmap/operations#294]
I normally log into www.openstreetmap.org using GitHub, but today after being redirected back to www.openstreetmap.org from github.com, it showed the message `Invalid authentication credentials`. I checked at https://github.com/settings/applications and it still shows "OpenStreetMap Authentication". My id is chaz@chaz6.com. Thank you for any assistance.

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/fedc49956d2e917e3e05d092ba820f0a41272638.

**Comment by Chaz6** [comment]
Thank you!
