### ISSUE TITLE
Root filesystem on ironbelly is filling up

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#30]
The root filesystem on ironbelly is growing fairly relentlessly and has now reached 80% full with 110Gb of data. Large users include:

* /home/grant - 22Gb
* /home/matt - 13Gb
* /var/lib/awstats - 30Gb
* /var/lib/replication/streaming - 28Gb
* /var/log/apache2 - 8.4Gb
* /var/log/chef-server - 4Gb

**Comment by tomhughes** [comment]
I've added rotation for the chef-server nginx logs and it looks like @zerebubuth has removed most of his stuff.

**Comment by Firefishy** [comment]
I've moved most of my stuff. Down to ~53% now.

**Comment by tomhughes** [comment]
I reached out to Brett with some queries about the streaming replication.

**Comment by zerebubuth** [comment]
We're at 55% now on the root filesystem - do we need to worry about this? Perhaps just moving and linking `/var/lib/replication/streaming` to `/store` somewhere is enough?

![df-year](https://cloud.githubusercontent.com/assets/271360/7535029/960f6c8a-f578-11e4-8e16-89a0f5c6229f.png)

**Comment by tomhughes** [comment]
I've got an email from Brett about the streaming that I need to look into...

**Comment by Firefishy** [comment]
Seems to be stable around 40% now. Closing.
