### ISSUE TITLE
iD editor not starting up on master.apis.dev - iD has not been configured

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#301]
I believe, some of the Rails code changes back in March haven't been fully reflected in the dev instance settings yet.

When I try to spin up the iD editor on https://master.apis.dev.openstreetmap.org/edit?editor=id#map=19/17.40329/78.39228, I'm getting an error *iD has not been configured*.

This is not urgent at all, as I'm testing on http://preview.ideditor.com/master/ atm.

**Comment by tomhughes** [comment]
I'm not sure why you would think that.

**Comment by tomhughes** [comment]
As expected that instance is using the new configuration system.

**Comment by mmd-osm** [comment]
Ok, that's good. Maybe it's something else then. I'll try and delete all of the id entries underneath "My Authorised Applications", and see if that helps.

**Comment by mmd-osm** [comment]
On my local instance, I have a dedicated id_key in settings.local.yml, that's the OAuth consumer key for iD. I think, if that key isn't available for some reason, id.js.erb shows an error message.

**Comment by tomhughes** [comment]
It's ok I've found it - there is a dynamic setup script we add to the initialisers for those instances and it didn't understand the new configuration system.

**Comment by mmd-osm** [comment]
Great,many thanks for looking into it!

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/7c138bff74e0ccc03bcb662bfbe752b3fca68c37.
