### ISSUE TITLE
Proper formatting of RTL languages in the main wiki

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#302]
MediaWiki offers a configuration which allows users to change the content language for individual wiki pages. Enabling the feature would support formatting and editing of RTL language wiki pages. Currently, a template is used, but this seems to interfere with VisualEditor. 
Changing the page content language essentially wraps the content in an HTML div block with proper attributes for text direction and content language as it is done in Wikimedia Commons for instance. 
I would now like to add the following config for the main wiki only:
```
$wgPageLanguageUseDB = true;  // store languages of individual pages in data base
$wgGroupPermissions['user']['pagelang'] = true; // assigns users the right to change the page language
```
Where is the correct place to add this to the wiki cookbook?

* Link to the user discussion: https://wiki.openstreetmap.org/wiki/Talk:Wiki#Visual_editor_isn.27t_usable_because_of_.7B.7BFa.7D.7D_template
* Configuring the page language: https://www.mediawiki.org/wiki/Manual:Language#Page_content_language

**Comment by tomhughes** [comment]
Well just put it in the `LocalSettings` template, or as a new dropin file in `LocalSettings.d`.

**Comment by Tigerfell** [comment]
Could you check my PR?

**Comment by tomhughes** [comment]
Fixed by https://github.com/openstreetmap/chef/pull/239.
