### ISSUE TITLE
Bad Request (400) - Version may not be negative at line 1

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/operations#303]
This may as well be a bug in StreetComplete or osmapi, I am currently investigating. Maybe you immediately know what is wrong or can help me find the bug.

Since this morning, I am getting error reports from users of StreetComplete about failing upload. The error returned by the OSM API  `Bad Request (400) - Version may not be negative`.

The newest version of the app is out for some weeks already, but I am only getting error reports about this now. So, _something_ must have changed very recently that leads to the app making a bad request.

I can't find where in the OSM API a string like _"Version may not be negative"_ is returned. Could you point me at it? Also, the version mentioned in that error message is the version of the element uploaded, right?

**Comment by mmd-osm** [comment]
Could you please create an issue on the cgimap repo with exact step by step description on how to reproduce the issue? Thanks!

**Comment by tomhughes** [comment]
I would have moved this there if I could ;-) That's https://github.com/zerebubuth/openstreetmap-cgimap/issues/ @westnordost...

There's a reasonable argument that it is rails that is wrong though - the 409 response is meant to mean that the version you gave is out of date because somebody else has edited since you fetched the object. A negative version is just straight up invalid and should arguably be a 400 error as cgimap is doing.

**Comment by westnordost** [comment]
I created a new issue there and thus will close this one here.

**Comment by mmd-osm** [comment]
Let's take a brief look at the [OSM API 0.6 documentation](https://wiki.openstreetmap.org/wiki/API_v0.6#Version_numbers.2Foptimistic_locking) on version numbers:

*  _If the version supplied is not the same as the server's current version, an error will be returned (HTTP status code 409: Conflict)_
* _Version numbers will always begin at 1 and increase by 1 every time an element is changed._

By using negative version numbers, you're actually violating the second requirement, although the documentation doesn't explicitly mention that an HTTP 400 would be raised in that case.

I somehow tend to backport this behavior to Rails.

As a side note, the diff upload references error messages for individual objects (such as [this one](https://wiki.openstreetmap.org/wiki/API_v0.6#Update:_PUT_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id)), where the docs state on the topic of version numbers:

> HTTP status code 400 (Bad Request):
> When the version of the provided element does not match the current database version of the element

It's interesting that Rails returns HTTP 409 in this case. I haven't looked into it yet to find out where it comes from.

**Comment by tomhughes** [comment]
It's https://github.com/openstreetmap/openstreetmap-website/blob/master/lib/consistency_validations.rb#L11, which raises `APIVersionMismatchError` when the versions are different.
