### ISSUE TITLE
Replacing yevaud

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#304]
We replaced [orm](https://github.com/openstreetmap/operations/issues/283) with odin because it was old hardware as well as having problems. This was a huge boost to render capability, and odin can easily handle twice what orm did. Yevaud is of the same age and we should decide what to do with it. Options are

- replace it with a clone of odin
- decommission it without a replacement
- run it into the ground until something fails

If we decommission it, we still have more rendering capacity than we did at the start of the year. I think the main question is, do we want to have two OSMF-owned rendering servers in different DCs, or are we okay with one?

**Comment by pnorman** [comment]
> or are we okay with one?

I forgot about pyrene.

To have it recorded, current rendering servers and approximate metatile/s capacity before dropping tiles are

Server | Capacity
------------ | -------------
bowser | 25+
pyrene | 25
rhaegal | 8
scorch | 10
odin | 20+
yevaud | 8

**Comment by tomhughes** [comment]
I would expect odin to be capable of rather more than that but I suspect we haven't really discovered what it can do yet - it has more cores than pyrene though and much better disks so it ought to be able to out do pyrene at least though maybe not bowser. A quick summary of the hardware:

Server | Cores | Memory | Disks
---------|---------|------------|--------
bowser | 36 | 256Gb | 2 x 2TB Intel DC P3500 SSD [NVME SSD] in RAID1
pyrene | 20 | 192Gb | 8 x 400GB HP MO0400JEFPA [SAS HDD] in RAID5
rhaegal | 12 | 72Gb | 6 x 1TB Samsung SSD 860 [SATA SSD] in RAID10
scorch | 8 | 128Gb | 4 x 800GB Intel SSDSC2BB800G6 [SATA SSD] in RAID5
odin | 28 | 256Gb | 2 x 4TB Intel Express Flash NVMe P4500 [NVME SSD] in RAID1
yevaud | 12 | 96Gb | 1 x 1TB Samsung SSD 850 [SATA SSD] for database<br/>4 x 500GB Samsung SSD [SATA SSD] in RAID0 for tiles

**Comment by hbogner** [comment]
Is rhaegal OK for now, or should I be looking for newer hardware?

**Comment by pnorman** [comment]
> I would expect odin to be capable of rather more than that but I suspect we haven't really discovered what it can do yet

Are we bandwidth limited?

**Comment by tomhughes** [comment]
Not as far as I know, we just don't have enough load to really stress it!

**Comment by pnorman** [comment]
> Not as far as I know, we just don't have enough load to really stress it!

Other rendering servers are dropping tiles in peak hours, should we then shift more load to odin?

I think it'd be a good idea to shift load to Odin in a controlled manner until we hit its limit, so we know what it is, even if we wouldn't put that much load on it normally.

**Comment by pnorman** [comment]
Having thought about it, I think we should replace yevaud with a machine like odin. Right now I don't think we're resilient to a failure of odin, or able to schedule downtime of it for maintenance

**Comment by mmd-osm** [comment]
> Other rendering servers are dropping tiles in peak hours

As a side note: Is this related to the queue management in mod_tile, or something else? CPU and memory wise there should be plenty of extra capacity, so those kind of statements always come a bit as a surprise.

**Comment by tomhughes** [comment]
Not sure why you would think that - the only time I ever see render servers dropping tiles is when the CPU is maxed out. I moved some load at the weekend but if you at when rhaegal was dropping render requests last week:

https://munin.openstreetmap.org/openstreetmap.org/rhaegal.openstreetmap.org/renderd_processed.html

then it corresponds to when the CPU was basically maxed out:

https://munin.openstreetmap.org/openstreetmap.org/rhaegal.openstreetmap.org/cpu.html

**Comment by mmd-osm** [comment]
Ok, dropping tiles during peak CPU utilization makes sense.

I didn't quite understand where those metatile/s values in the second post were coming from, and what exactly contributed to the "render server is dropping tiles" situation, and how you would identify this on munin charts.

**Comment by tomhughes** [comment]
Note that a queue there just means we weren't immediately able to render a tile - it doesn't necessarily mean no tile was served, just that it might have been an out of date tile. Cases where we can't even render missing tiles (which are higher priority than outdated ones) will show up as 404s on this graph:

https://munin.openstreetmap.org/openstreetmap.org/rhaegal.openstreetmap.org/mod_tile_response.html

**Comment by pnorman** [comment]
> I didn't quite understand where those metatile/s values in the second post were coming from, and what exactly contributed to the "render server is dropping tiles" situation, and how you would identify this on munin charts.

The munin charts show MT/s so both can be read from the throughput graph.

We seem to be drifting away from what to do with yevaud into a general discussion of architecture with no clear connection back to planning.

**Comment by pnorman** [comment]
OWG has decided to replace yevaud with a machine the same as odin.

**Comment by Firefishy** [comment]
https://hardware.openstreetmap.org/servers/ysera.openstreetmap.org/ is installed and will be live shortly.
