### ISSUE TITLE
HTML document can never receive a 304 Not Modified

### ISSUE THREAD

**Issue by alexkemp9** [openstreetmap/operations#306]
*Background*    
Conducting a simple refresh (f5) on a recently downloaded [test map page](https://www.openstreetmap.org/way/17236956) causes only half (10 out of 21) of the files to give a `304 Not Modified`. Obviously *Not Good* both for the user (slow) plus OSM (increased bandwidth + load).

Some of those files may well be dynamic, but some are clearly static. Because of the wide range of *Response Header* symptoms + my ignorance these are individual file-type reports to allow those with a working knowledge of the code to decipher it all.

*The meat*    
An HTML doc based on a map *way*.    

- `Last-Modified`: not present    
- `eTag`: weak
- `Expires`: not present
- Request: `If-None-Match` (no match, so no 304)    
(I've checked that the way is unchanged & yet the `eTag` changes on every refresh. BUG!!!)

*Related*    
The tiles supplied by *toothless* (eg https://b.tile.openstreetmap.org/18/130245/85447.png) are also all dynamic yet all have a strong `eTag` (matched by the `If-None-Match`) + `Expires` and thus get cached + a 304.

*Extra*    
See bottom of [this Diary page](https://www.openstreetmap.org/user/alexkemp/diary/368814) for fuller details.

**Comment by tomhughes** [comment]
By the way I can reproduce your results but what you don't seem to understand is that the decision as to what to cache is up to the browser, not us.

We tell the browser it can cache it for a year and it chooses not to. That's not our fault, or anything we can control.

**Comment by alexkemp9** [comment]
*TomH:*    
We tell the browser it can cache it for a year

Are you sure about that?

> *My report:*    
> • Expires: not present

Further, that is only the first of 2 problems. The second one is:

> *My report:*    
> • Request: If-None-Match (no match, so no 304)

The value of the weak eTag in the INM header changes on *every* re-request. That is a bug, I believe.

**Comment by alexkemp9** [comment]
Further info on caching, something I did miss out:

- cache-control: max-age=0, private, must-revalidate

**Comment by tomhughes** [comment]
Because in all your waffle I missed what URL you were actually talking about. I suggest putting the key facts front and centre and leaving the lessons in egg sucking for later (if you need to include them at all).

Yes rails generated pages will be uncachable.

Yes in theory maybe some of them could be cacheable but actually trying to encode that in accurate way is extremely hard so it's easier to fail safe.

Bear in mind that basically every page is different depending on who (if anybody) you are logged in as at a minimum.

**Comment by alexkemp9** [comment]
> TomH
> I suggest putting the key facts front and centre…

You are not the only person that will read this sequence of reports. Other people are likely to read only one report, in which case the *Background*, which is clearly flagged as such, will be vital in understanding the meat of the matter.

> TomH
>  …and leaving the lessons in egg sucking for later

Now, if you will agree to stop being so damn insulting I will promise to stop pointing out just how incredibly [narcissistic](https://en.wikipedia.org/wiki/Narcissism) you are.

**Comment by pnorman** [comment]
Locking this because it is not productive.
