### ISSUE TITLE
Setting the page content language for new wiki pages automatically on page creation

### ISSUE THREAD

**Issue by iriman** [openstreetmap/operations#307]
Follow-up from #302, it's better that page content language for new pages to be set automatically. For example content language of Farsi pages with `Fa:` prefix should be set as `fa` on page creation. Also for other RTL languages like Ar, He, etc. it's necessary, otherwise every time we create a new page we should change its content language manually.

This might be relevant:
from https://www.mediawiki.org/wiki/Manual:Language#Page_content_language :
> **Configuration**
>     Extensions can change all other pages through the [PageContentLanguage](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:Hooks/PageContentLanguage) hook.

**Comment by tomhughes** [comment]
You're better off talking to the wiki admins really - if they have a change they want us to make then fine but we're not mediawiki experts.

**Comment by iriman** [comment]
I see. Sorry. I will do that way.

**Comment by pnorman** [comment]
Wiki admin issue, not ops issue.
