### ISSUE TITLE
svn.openstreetmap.org does not support https

### ISSUE THREAD

**Issue by simon04** [openstreetmap/operations#31]
http://svn.openstreetmap.org/ shows the SVN repository, but
https://svn.openstreetmap.org/ shows the Git projects …

**Comment by tomhughes** [comment]
So something we've never claimed exists or works doesn't work? Film at 11 ;-)

**Comment by zerebubuth** [comment]
Yeah, but rather than not working, we should make it either work or not exist. I can see why it's annoying and _unexpected_ for the HTTPS version of a site to be completely different from the HTTP version.

**Comment by tomhughes** [comment]
Did I close the ticket? No, I didn't.

**Comment by tomhughes** [comment]
There you go, I've fixed the title of the ticket now.

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/cc72dc2d2fdd53030fb34a0f0842002bcc105f68.
