### ISSUE TITLE
id not loading

### ISSUE THREAD

**Issue by ClarkstonCorrect** [openstreetmap/operations#310]
Whenever I open iD to try edit it just brings up this screen
![broken](https://user-images.githubusercontent.com/51952664/59674364-104e7580-91bb-11e9-86ed-5d64dddea51d.PNG)

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/1be0e5d385d5c4048ffac061b614aa21312ffcd8.

If you find you are still having problems please try clearing the browser cache.
