### ISSUE TITLE
attempting to login using previously unused gmail account gives application error 500

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#311]
Discovered during UX testing of one of OSM editors.

Screenshot after attempted login on a mobile Chrome: https://user-images.githubusercontent.com/899988/60381621-d3566e80-9a57-11e9-9e73-60bca2d24b7c.png

I (and user) would expect redirect to a registration page with prefilled data.

Reloading page revealed prefilled registration form.

**Comment by tomhughes** [comment]
One of the servers had been rebooted so had lost the blackhole route that fixes this.
