### ISSUE TITLE
Link OSM forum to main website using OAuth

### ISSUE THREAD

**Issue by Chaz6** [openstreetmap/operations#312]
When you are signed into openstreetmap.org you should also be automatically signed into forum.openstreetmap.org. This is useful when you use a 3rd party authentication provider such as GitHub.

**Comment by tomhughes** [comment]
As far as I know this is not a feature the forum software (which is not written by us) supports, so we are unable to offer this.

**Comment by Chaz6** [comment]
I believe the forum uses FluxBB which is an open source project, so you could add support yourself and even upstream it. How about marking it as a feature request for the future as opposed to outright closing it?

**Comment by tomhughes** [comment]
Well yes sure we could, but it's vanishingly unlikely - we've got plenty do developing out own software without writing major enhancements for the many pieces of third party software we use.

Would you open a ticket her to suggest an improvement to apache?

The place to make an enhancement request for fluxbb is the fluxbb repositories where the relevant experts are to be found.

**Comment by Chaz6** [comment]
If it was a part of apache directly relevant to osm operations, sure I would raise it here, because the actual user base is here who are interested in that feature, but I recognize that if it was upstreamed others could benefit from it also. There would be more momentum to develop it within this project rather than as a footnote on the larger 3rd party project where fewer people are interested in it. That said, I will raise a request on the FluxBB project as you request.
