### ISSUE TITLE
OTRS logs users out on IP changes

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#313]
This makes OTRS very difficult to use or impossible for those behind NAT with multiple IPs, or mobile internet.

There should be an OTRS setting for this, writing this issue as a reminder to myself.

**Comment by Firefishy** [comment]
Here is the change required: https://gerrit.wikimedia.org/r/#/c/operations/puppet/+/242789/3/modules/otrs/templates/Config.pm.erb

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/744395e6921f407f2267240b5eb7bbbac9ed41d2.

**Comment by richlv** [comment]
Yay, thank you all for this quick improvement.
