### ISSUE TITLE
Favicon for forum

### ISSUE THREAD

**Issue by TZornG** [openstreetmap/operations#314]
Could you please add a favicon to the forum website?

**Comment by Tigerfell** [comment]
I guess this relates to #248 where I just made a suggestion for a potential logo.

**Comment by Tigerfell** [comment]
Duplicate of OSM-Forum/openstreetmap-forum#10

**Comment by mmd-osm** [comment]
@TZornG : can you close this issue and follow up in #248? Thanks.

**Comment by TZornG** [comment]
Followed up in #248 .
