### ISSUE TITLE
Error when trying to buy a SotM ticket.

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/operations#315]
Reported by @rory via email to SotM Working Group:
> Hello SotM WG,
> 
> I have tried to buy a ticket for SotM, and I got this error:
> 
> Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
> DB Error: unknown error
> 
> Return to home page.
> 
> I've attached a screenshot
> 
> This happened just now, and also on Sunday last. 🙁
> 
> I hope this is fixed soon so I can go to SotM.
> 
> Rory 

[Screenshot_2019-07-17 https join osmfoundation org-nq8](https://user-images.githubusercontent.com/3611273/61386616-df925680-a8b4-11e9-85e4-91a34b7fc631.png)

EDIT: Change user name rorym to rory. (Stupid auto completion suggested Andy Allan.)

**Comment by tomhughes** [comment]
What does this have to do with us?

**Comment by Nakaner** [comment]
CiviCRM

**Comment by tomhughes** [comment]
The MWG are responsible for join.osmfoundation.org as far as I know - we don't really know anything about CiviCRM configuration.

Stereo might be able to help...

**Comment by tomhughes** [comment]
At the very least we need some useful information, like the URL being visited or the time it occurred. A picture of the error is almost completely useless.

**Comment by tomhughes** [comment]
The only thing I can see in the logs from the last few hours is:

```
[Wed Jul 17 14:46:26.622178 2019] [php7:error] [pid 17586] [client a.b.c.d:35290] PHP Fatal error:  Uncaught CRM_Core_Exception: [0: Transaction integrity error: Expected to find active frame\n\n  thrown in /srv/join.osmfoundation.org/wp-content/plugins/civicrm/civicrm/Civi/Core/Transaction/Manager.php on line 107, referer: https://join.osmfoundation.org/?page=CiviCRM&q=civicrm%2Fevent%2Fregister&_qf_Confirm_display=true&qfKey=elided
```

Which looks like a bug in CiviCRM so not something we can do much about.

**Comment by Nakaner** [comment]
Thank you, @tomhughes, for pointing out the responsibilities.

@grischard Could you please help?

@rory Does this problem persist or does it happen from time to time?

**Comment by tomhughes** [comment]
Are we even sure that the registration hasn't gone through? Presumably other people are managing to register?

**Comment by rory** [comment]
> At the very least we need some useful information, like the URL being visited or the time it occurred

The URL was (I think) https://join.osmfoundation.org/?page=CiviCRM&q=civicrm%2Fevent%2Fregister&_qf_Confirm_display=true&qfKey=1632c031e13a6ca29b41401165312a76_2200
 and I visited it within the last hour

> A picture of the error is almost completely useless

😛 I was asked to send a screenshot 

> Are we even sure that the registration hasn't gone through? Presumably other people are managing to register?

I haven't received any email confirmation, and I haven't paid anything. 🤷 The people will access to the ticket list should be able to tell if I am registered or not.

> Does this problem persist or does it happen from time to time?

I tried again just now. The URL is https://join.osmfoundation.org/?page=CiviCRM&q=civicrm%2Fevent%2Fregister I tried 3 times and the same error every time.

**Comment by tomhughes** [comment]
OK so that looks like it matches the log entry I found.

**Comment by grischard** [comment]
Hi everyone

It looks like it's simply a borken link - https://join.osmfoundation.org/?page=CiviCRM&q=civicrm%2Fevent%2Finfo&id=13&reset=1 works.

@rory where did you find a link to that page?

**Comment by rory** [comment]
I have now successfully bought a ticket by not putting in my OSM user name.

CivicCRM is buggy and cannot handle all OSM usernames.

**Comment by SomeoneElseOSM** [comment]
@rory I think it would be informative to link to your username at this point...

One question - would the same problem occur with names with characters from in in-use character sets (Arabic, Persian, Burmese etc.)?

**Comment by rory** [comment]
> @rory I think it would be informative to link to your username at this point...

At the time, my OSM username was `rorym 🏳️‍🌈`. The last character has sometimes causes problems, but not as much as you may think.

> would the same problem occur with names with characters from in in-use character sets (Arabic, Persian, Burmese etc.)?

That is a good point, and needs to be tested. I do not know enough about those writing systems to know. If so, it's important to find out if OSMF members would be able to vote in board elections.

**Comment by dorotheakazazi** [comment]
> If so, it's important to find out if OSMF members would be able to vote in board elections.

Just a note: board election votes are linked to email addresses, not OSM usernames :)

**Comment by grischard** [comment]
@rory yeah, we'd already seen that at the Hack Weekend in Karlsruhe. CiviCRM can't currently handle 4-byte emoji, kanji, etc

See https://lab.civicrm.org/dev/core/wikis/utf8mb4

OK to close this since this is a CiviCRM issue, not OWG?
