### ISSUE TITLE
Login through OpenID fails

### ISSUE THREAD

**Issue by FTno** [openstreetmap/operations#316]
Login with OpenID to edit map stopped working about a week ago. It worked one day and on the next day it had suddenly stopped working, and the problem is still there. The error message appearing is: Connection to authentication provider failed

I have used my Launchpad profile URL for OpenID, and tried to login with 3 different browsers.

**Comment by tomhughes** [comment]
I've null routed the canonical IPv6 block on the production cluster for now as the IPv4 still seems to be working.

**Comment by FTno** [comment]
Can confirm it's working now. Thanks for fixing.
