### ISSUE TITLE
Tiles in London need to be forced out of cache

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/operations#317]
I'm not sure where best to put this ticket, but the OSM website Mapnik tiles need a serious flush in London:

![Screen Shot 2019-08-04 at 14 44 45](https://user-images.githubusercontent.com/361423/62424436-62454f00-b6c6-11e9-8aae-12b2a9901ed2.png)

This is presumably related to the problem noted at:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-August/023327.html
https://lists.openstreetmap.org/pipermail/talk-gb/2019-August/023329.html

Also noticed on Twitter:
https://twitter.com/MatthewMarks42/status/1157965326736404481

**Comment by tomhughes** [comment]
It looks to me like they had mostly rerendered already - a simple shift-reload was enough to clean up any broken ones in the squid cache for me.

**Comment by mvl22** [comment]
Thanks, Tom. However, does that imply then that data here:
https://www.openstreetmap.org/changeset/72983873

is still wrong somehow? Even using a force-refresh I am still seeing a seriously broken map, though the data in iD looks correct:

![Screen Shot 2019-08-04 at 14 52 27](https://user-images.githubusercontent.com/361423/62424519-78074400-b6c7-11e9-96bc-cb181e085ae5.png)

**Comment by tomhughes** [comment]
Well once you get into z19 there is probably a danger of tiles being spanned by broken ways without any nodes actually in the tile which may mean they don't get dirtied by the revert.

There's still not a lot I can do about it though - well not without writing a lot of code at any rate.

**Comment by harry-wg** [comment]
Marked as fixed, but is still serving up corrupted tiles. I retested only a few minutes ago using a different browser, so these tiles are not coming from my local cache

**Comment by harry-wg** [comment]
5 days later, users are still getting this problem. Is there really nothing more systematic that can be done about it?

https://www.openstreetmap.org/note/1875952

https://www.openstreetmap.org/note/1875951

https://www.openstreetmap.org/note/1876136

**Comment by tomhughes** [comment]
Well if force refresh works then no there definitely isn't.

I did attempt to force invalidation on the render servers but failed as mod_tile doesn't have any good tools for marking a bbox as dirty.

But if a force reload works that means it is just the caches that still have the old tiles, and I'm not about to start trying to flush that bbox from 30 odd cache servers, even if I had a way to do so, which I don't.
