### ISSUE TITLE
Corrupted map tiles

### ISSUE THREAD

**Issue by harry-wg** [openstreetmap/operations#318]
I'm getting obviously-corrupted tiles on the Standard Map? For about the last 11 hours. 

For instance, try https://www.openstreetmap.org/#map=14/51.5697/-0.0264

Checked in two browsers, so the problem is not in my local cache. Other parts of London are affected too -- sometimes not when the map is initially loaded, but zoom in and out and pan for a while and the weird tiles appear.

Only the standard map seems to be affected -- if I choose different map tiles (eg cycle map) it seems to be OK so far

![Untitled-1](https://user-images.githubusercontent.com/9380304/62455891-38943280-b76f-11e9-9a70-a21986d9710c.gif)

**Comment by gravitystorm** [comment]
Dupe of #317 (and there's a thread on the talk-gb mailing list too).

**Comment by harry-wg** [comment]
Sorry, seems this is alreay covered by 317

**Comment by tomhughes** [comment]
It is, plus a shift reload on that view has just cleared them for me so they had already rerendered most likely and were just in the CDN cache.
