### ISSUE TITLE
Failed disk in stormfly-01

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#320]
1x 72GB 15K disk has failed in stormfly-01

```
      physicaldrive 1I:1:4
         Port: 1I
         Box: 1
         Bay: 4
         Status: Failed
         Last Failure Reason: Hardware error
         Drive Type: Data Drive
         Interface Type: SAS
         Size: 72 GB
         Drive exposed to OS: False
         Logical/Physical Block Size: 512/512
         Rotational Speed: 15000
         Firmware Revision: HPDJ
         Serial Number: 3TA0JP72000090145C7Z
         WWID: 5000C500174FE185
         Model: HP      DH0072FAQRD
         Current Temperature (C): 26
         Maximum Temperature (C): 41
         PHY Count: 2
         PHY Transfer Rate: 6.0Gbps, Unknown
         Sanitize Erase Supported: False
         Shingled Magnetic Recording Support: None
```

**Comment by Firefishy** [comment]
Email osuosl about sending a replacement.

**Comment by Firefishy** [comment]
@pnorman What do you think? Replace with SSD? HP Part Number 632492-B21

Or stick to replacing with say 300GB spinning rust? HP Part Number 627117-B21

**Comment by Firefishy** [comment]
My preference is replace all with 627117-B21.

**Comment by pnorman** [comment]
Right now it's running 7 x 72GB 15k and 1x146 15k, for a raid6 of 410.01gb which peaks at about 290GB, 25% y/y growth.

My preference is to replace the RAID6 with a couple of SSDs in RAID1.

**Comment by Firefishy** [comment]
Ordered some replacement disks. Annoyingly gone for spinning rust. ETA for delivery is Wednesday 21 August 2019.

**Comment by Firefishy** [comment]
Disks have arrived and will be installed shortly.

**Comment by pnorman** [comment]
@Firefishy were these installed?

**Comment by Firefishy** [comment]
All disks have been installed. Thanks @pnorman for the poke ;-)

**Comment by Firefishy** [comment]
8x 300 GB disks installed. Array grown to new size.
