### ISSUE TITLE
Create official OSMF thank you page for donations

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#323]
After creating a recurring PayPal donation to OSMF, they are apparently forwarded to [NewRecurringDonorWelcome wiki page](https://wiki.openstreetmap.org/wiki/NewRecurringDonorWelcome). I suggest to change this to some OSMF page for the following reasons:
1. The page should not be editable by everyone and probably does not need to be edited anyway. 
2. I think it is confusing to donate to OSMF and getting referred to the main wiki with a "Thank you" page instead of an official OSMF page. 

This was previously discussed at https://wiki.openstreetmap.org/wiki/Talk:NewRecurringDonorWelcome.

**Comment by tomhughes** [comment]
I don't believe this is anything to do with operations but if you can clarify exactly what you're referring to then we can try and find out who is responsible.

Presumably you followed a link to PayPal from somewhere which then led you back to that page - where exactly was that link you followed?

**Comment by grischard** [comment]
This would probably be something for CiviCRM, where donations could also be tracked better. @Tigerfell 	would you like to join the Membership Working Group?

**Comment by v4hn** [comment]
It was me who found the outdated forward.

I followed the `Donations` button on the left on [the main wiki](https://wiki.openstreetmap.org/wiki/Donations) and selected a (€) link in the `PayPal Recurring Donation` section.
After setting up the donation on paypal, I got forwarded to the page @Tigerfell referred to.

**Comment by Tigerfell** [comment]
I actually thought of the setup of donate.osm.org when contacting OWG. The rest is not relevant for them. 

Regarding the wiki pages, some user of OSMF wiki ([list](https://wiki.osmfoundation.org/wiki/Special:ListUsers)) would need to set up a page. Then, an admin of the main wiki would need to change all donation links (I found out, you can simply change the links set a new return address):

```diff
+ https://www.paypal.com/cgi-bin/webscr?...&return=http%3a%2f%2fwiki%2eopenstreetmap%2eorg%2findex%2ephp%2fDonationThankYou...
- https://www.paypal.com/cgi-bin/webscr?...&return=http%3a%2f%2fwiki%2eosmfoundation%2eorg%2findex%2ephp%2fDonationThankYou...
```
(... = all the irrelevant parameters that remain the same)

@grischard I am happy to help out, but I am not a member of OSMF.

**Comment by Tigerfell** [comment]
The line that would need to be changed after transferring the content to OSMF wiki is 
https://github.com/osmfoundation/donation-drive/blob/f4c9094edbcf9d761135a89e903b613e84b427dd/process/paypal-submit.php#L46

**Comment by dorotheakazazi** [comment]
[A thank you page](https://wiki.osmfoundation.org/wiki/Donate/PayPal/Thank_you) was created on the OSMF website and the links on the [OSMF Paypal page](https://wiki.osmfoundation.org/wiki/Donate/PayPal) were updated to point there as the return page.

The [OSM wiki page Paypal links](https://wiki.openstreetmap.org/wiki/Donations#PayPal_Donations) remain to be updated - at the moment this can't be done by me as the page is protected :) Happy to change them, if someone gives me the rights to do so :)

**Comment by Tigerfell** [comment]
The single donation links in OSMF wiki are unchanged. Was that intended?

**Comment by Tigerfell** [comment]
@dorotheakazazi OSM wiki pages were updated, the remaining OSMF wiki links should follow. 
@pedaB @tyrasd Could you please consider merging the PR linked further up? It looks to me as if you have access to this repository.

**Comment by tyrasd** [comment]
> @tyrasd Could you please consider merging the PR linked further up?

you mean https://github.com/osmfoundation/donation-drive/pull/14, right? sorry, I don't have write access to that repository. Maybe @Zverik can help?!

**Comment by Zverik** [comment]
Merged. Thanks for pinging.

**Comment by Tigerfell** [comment]
Great, thanks everyone. This issue is solved!
