### ISSUE TITLE
Wiki is unavailable: "internal error"

### ISSUE THREAD

**Issue by zorun** [openstreetmap/operations#325]
Trying to access https://wiki.openstreetmap.org/wiki/Main_Page or any other page results in:

```
[a2b8232fc119d7ea96f31b94] 2019-08-27 18:15:17: Fatal exception of type "Error"
```

The error is not really helpful, sorry.

**Comment by tomhughes** [comment]
There is an upgrade in progress - it's up at the moment but with wikibase disabled for now.

**Comment by tomhughes** [comment]
It's this:

```
[06f8020a50a070da0e723858] [no req]   Error from line 35 of /srv/wiki.openstreetmap.org/w/extensions/Wikibase/lib/WikibaseLib.entitytypes.php: Class 'Wikibase\DataModel\Entity\ItemId' not found
```

even though that file has this at the top:

```
use Wikibase\DataModel\Entity\ItemId;
```

and the relevant file (`/srv/wiki.openstreetmap.org/w/extensions/Wikibase/vendor/wikibase/data-model/src/Entity/ItemId.php`) appears to exist.

**Comment by 1ec5** [comment]
Could this be relevant? https://phabricator.wikimedia.org/T225364

**Comment by tomhughes** [comment]
It looks like it but I did already try running composer.
