### ISSUE TITLE
fix publisher meta information on osm.org website's HTML header

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/operations#326]
The osm.org website contains in the HTML header the following outdated (now dead) link to google plus as the "publisher" of the website:

```html
<link rel="publisher" href="https://plus.google.com/111953119785824514010">
```

In the website's [config/settings.yml](https://github.com/openstreetmap/openstreetmap-website/blob/c162c065c6f6db5dc584599f5639b296b627a165/config/settings.yml#L5) this should be changed to something current, e.g. just "OpenStreetMap Foundation".

**Comment by tomhughes** [comment]
Why not just delete it - it's only purpose was to make links posted to google plus associate to our account there.

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/4bc7810fa3c896fa0058518a64f8c9d4c5114f2a.

**Comment by tyrasd** [comment]
Sure. I wasn't aware of this original purpose of this field. Thanks!
