### ISSUE TITLE
Using OSM tile server for commercial application

### ISSUE THREAD

**Issue by kmprakashbabu** [openstreetmap/operations#328]
Hi,
     When I contacted OSM SystemAdministrator they asked me to contact here. I don't know if it is still a right place but I will go ahead ask my questions on usage.
1. Can I use osm tile server for commercial use? 
2. Tile usage policy says get permission first for Heavy use. I don't think my application will have heavy use, but I would like to get permission.
3. What is defined as heavy use?
4. In case of occasional heavy use and if I get blocked, how to request to unblock?

Thanks
Prakash

**Comment by tomhughes** [comment]
I don't know who you contacted, but no system administrator would have told you to open a ticket here for this - this a matter where you should contact operations@osmfoundation.org but only after you have read https://operations.osmfoundation.org/policies/tiles/ which should answer most of your questions, at least to the extent that answers exist.

**Comment by matkoniecz** [comment]
Sorry for a misdirection - I based this advice on https://wiki.openstreetmap.org/w/index.php?title=Talk:System_administrators&diff=1857866&oldid=1857856

**Comment by kmprakashbabu** [comment]
@tomhughes 
           Thank you.
@matkoniecz 
           No worries
