### ISSUE TITLE
Better outage reporting on pingdom for Nominatim

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/operations#33]
pingdom currently only checks if the Nominatim server is up, it does not check if the database is actually working, which has recently caused a few outages to go undetected until users started complaining. Would it be possible to change the pingdom check to test for a 200 result on the /status.php URL which does explicitly test if the DB is ok? Also, the two servers should be checked independently. So the actual URLs to check for a 200 result should be:

http://poldi.openstreetmap.org/status.php
http://pummelzacken.openstreetmap.org/status.php

**Comment by tomhughes** [comment]
I've changed it to check status.php (it was doing a search for London) and split it in two, one for each server.
