### ISSUE TITLE
Mention if membership fee is lifetime or per year

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/operations#331]
https://wiki.osmfoundation.org/wiki/Membership says

> We have three membership classes: Normal (£15), Associate (£15) and Corporate (€500 to €20,000).

It should say if that is lifetime, or per year.

**Comment by mmd-osm** [comment]
Whatever text you're quoting here, it's nothing to be found anywhere on https://wiki.osmfoundation.org/wiki/Membership. Also, this report doesn't belong in this repo.

**Comment by dorotheakazazi** [comment]
@jidanni fixed, thanks 
_(the text was on https://join.osmfoundation.org, "per year" was mentioned further along in the text but not on that sentence)_

Could someone close this? :)
