### ISSUE TITLE
LaTeX <math>..</math> Extension:Math

### ISSUE THREAD

**Issue by Nautic** [openstreetmap/operations#334]
Please can you install/enable [Extension:Math](https://www.mediawiki.org/wiki/Extension:Math) to the OSM-Wiki? 
[OpenSeaMap](https://map.openseamap.org) would like to describe calculations about sperical trigonometry and orthodromes.
Thanks for help, Markus

**Comment by tomhughes** [comment]
That looks quite non-trivial as it appears to require Node.js and the usual endless stack of node modules on top of the normal mediawiki extension.

**Comment by mmd-osm** [comment]
@Nautic : I believe your requirement is very specific and most likely only very few users would benefit from it. Also, the implementation effort does not really justify installing and keeping this extension up to date.

A few points worth checking:

* Can you elaborate a bit why we need this on the OSM Wiki?
* Could you link to some Wikipedia page instead? There are probably existing pages explaining some of the math involved.
* In the worst case, you might simply prepare your formulas locally and upload some rendered PNG in your page instead.

**Comment by pnorman** [comment]
Closing as abandoned
