### ISSUE TITLE
Nginx upstream keepalive and ephemeral socket exhaustion

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#335]
Following on from #299 and #284, I've heard complaints that [azure](https://hardware.openstreetmap.org/servers/azure.openstreetmap.org/), one of the North America tile caches, is struggling. The symptoms are similar to those reported before; requests are being rejected by `nginx` with a 504 status code, and the number of open TCP sockets oscillates wildly:

![image](https://user-images.githubusercontent.com/271360/67001193-16a11f80-f0d1-11e9-861e-76c3e94b56ef.png)

One solution to this would be more tile caches - and **if anyone has a North American machine they'd be willing to donate, please get in touch**!

However, in the absence of generous benefactors, I thought I'd look into the issue a little more. Digging into the `nginx` logs during bad periods shows a number of entries similar to this:

```
2019/10/16 14:MM:SS [crit] 31375#31375: *XXXXXXXX connect() to 127.0.0.1:80 failed
   (99: Cannot assign requested address) while connecting to upstream, 
   client: X.X.X.X, server: localhost, request: "GET /Z/X/Y.png HTTP/2.0", upstream: 
   "http://127.0.0.1:80/Z/X/Y.png", host: "a.tile.openstreetmap.org", referrer: "URL"
```

It looks like what @Firefishy [said before](https://github.com/openstreetmap/operations/issues/284#issuecomment-468616353) is happening here; when the request rate gets high enough, `nginx` is running out of ephemeral sockets on `localhost` to connect to Squid.

We currently configure [256 `keepalive` connections](https://github.com/openstreetmap/chef/blob/6dd0bc2f6c86a5d8b1ff5f38d84e60ae931b95b7/cookbooks/tilecache/templates/default/nginx_tile.conf.erb#L18) to the backend, which should be used in preference to opening new connections. The default for `nginx` is to [recycle the keepalive connection after 100 requests](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive_requests), after which the socket will close and go into `TIME_WAIT` for 60s.

This means that each socket used for keepalive is capable of 1.67 req/s average before it cycles back to a usable state. Over 256 such sockets, we'd expect to see `nginx` start opening non-keepalive connections when the request rate goes over 426 req/s. Each non-keepalive socket is only capable of one request (it's not keptalive) before going into `TIME_WAIT`, so cycling the whole ephemeral socket set gives only an additional (65000-1024-256)/60 = 1,062 req/s, for a total of around 1.5kreq/s.

We don't log `nginx` requests, but the Squid req/s graph seems to start showing problems when it goes over about 1,200 req/s.

![image](https://user-images.githubusercontent.com/271360/67002754-7816bd80-f0d4-11e9-8281-94fba9f7fce6.png)

It's entirely possible that Squid couldn't handle any more load anyway, but the bottleneck does appear to be related to the number of `localhost` ephemeral connections.

Do you think it would help if we set `keepalive_requests` to a larger value, say 1,000, and the number of keepalive sockets up to 1,024? By rough calculation, this should lift the req/s `nginx` is able to make over `localhost` to 18kreq/s.  And we'll reach Squid's limits long before that.

If it's of interest, please let me know and I can submit a PR.

**Comment by tomhughes** [comment]
The problem with azure is more likely (or at least in part) that it has hardware issue - it has kicked out one half of it's disk mirror and @Firefishy reckons the RAID card is probably not up to the job of handling SSDs.

**Comment by Firefishy** [comment]
The RAID card definitely cannot handle the SSD cards on the machine. The control is frequently blocking and latency on IO wildly spikes. We have report the issues to the host and they are looking at a solution.

But saying all that, nginx could also likely use some tweaks.

**Comment by zerebubuth** [comment]
`nginx` settings tweaked, but it doesn't seem to have helped noticeably. I guess the IO latency spikes @Firefishy pointed out are just too much. :man_shrugging: 

Fingers crossed the hardware issue is sorted soon (and/or generous donors come forward).

**Comment by slachiewicz** [comment]
I found article https://tech.freckle.com/2016/01/21/scaling-beyond-65k-reverse-proxy-connections-on-localhost/ maybe for future use multiple IP's for squid backed connections can help.
