### ISSUE TITLE
Change accounting email address with our regular suppliers

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/operations#336]
For a more streamlined processing of invoices it would be good if supplier invoices were sent to accounts@osmfoundation.org in the future, instead of treasurer@. That way our accountant doesn't have to wait for the treasurer to forward them.

As far as I know our regular suppliers are 

- [x] Equinix
- [x] AWS
- [ ] Cogent
- [ ] Statuscake
- [ ] Gandi

The top three are most important since they bill every month; Pingdom and Gandi are less important. 

It would be great if you could make this change with the suppliers. I either don't have an account with them or lack the access permission. I could probably do it with Gandi but would prefer someone from operations do it.

**Comment by pnorman** [comment]
I will do Equinix and Cogent

**Comment by tomhughes** [comment]
I've done AWS. I did look at StatusCake the other day but I think that currently goes to operations and we forward it - not clear there is a separate billing contact. It's only once a year anyway I believe.

**Comment by woodpeck** [comment]
Equinix seem to have switched but Cogent are still emailing treasurer@ not accounts@... can you check @pnorman?

**Comment by pnorman** [comment]
We believe this is done.
