### ISSUE TITLE
FIxing incomplete daily replication file 000/000/876

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#338]
About 1231 objects are currently missing the daily replication file created on February 05 2015 (000/000/876). This is a bit unfortunate, as we'd like to give users the chance to build their Overpass API based on daily diffs, rather than minutely diffs. Due to those missing objects, building a complete history is not possible this way.

My proposal would be to merge the existing incomplete daily file with a minutely diff file by using the osmium tool merge feature, and again publish the new file on planet.openstreetmap.org (not sure if we give it a new name or replace the old file?).

```
wget https://planet.openstreetmap.org/replication/day/000/000/876.osc.gz
wget https://planet.openstreetmap.org/replication/minute/001/252/157.osc.gz
osmium merge 876.osc.gz 157.osc.gz -o 876_new.osc.gz
```

### Old

```
osmium fileinfo -e 876.osc
File:
  Name: 876.osc
  Format: XML
  Compression: none
  Size: 569224026
Header:
  Bounding boxes:
  With history: yes
  Options:
    generator=Osmosis 0.41-7-g87182e9
    version=0.6
[======================================================================] 100% 
Data:
  Bounding box: (-175.6751675,-62.5979115,176.11447,70.4908675)
  Timestamps:
    First: 2015-02-03T23:59:03Z
    Last: 2015-02-04T23:58:57Z
  Objects ordered (by type and id): yes
  Multiple versions of same object: yes
  CRC32: not calculated (use --crc/-c to enable)
  Number of changesets: 0
  Number of nodes: 1937046
  Number of ways: 266264
  Number of relations: 9837
  Smallest changeset ID: 0
  Smallest node ID: 81079
  Smallest way ID: 462
  Smallest relation ID: 4180
  Largest changeset ID: 0
  Largest node ID: 3331163090
  Largest way ID: 326468264
  Largest relation ID: 4559072
```

### New

```
osmium fileinfo -e 876_new.osc 
File:
  Name: 876_new.osc
  Format: XML
  Compression: none
  Size: 569478226
Header:
  Bounding boxes:
  With history: yes
  Options:
    generator=osmium/1.10.0
    version=0.6
[======================================================================] 100% 
Data:
  Bounding box: (-175.6751675,-62.5979115,176.11447,70.4908675)
  Timestamps:
    First: 2015-02-03T23:59:03Z
    Last: 2015-02-04T23:58:57Z
  Objects ordered (by type and id): yes
  Multiple versions of same object: yes
  CRC32: not calculated (use --crc/-c to enable)
  Number of changesets: 0
  Number of nodes: 1938075
  Number of ways: 266464
  Number of relations: 9839
```

**Comment by Firefishy** [comment]
Sounds like a reasonable hack to me. What do @gravitystorm and @tomhughes thing?

**Comment by tomhughes** [comment]
No idea... I mean if it's safe then sure but I have no idea what the risks are. What I can say is that it will have to have the right name or none of the tools will find it. Of course anybody that has already gone past that sequence isn't going to get it but there's not much as can do about that.

**Comment by gravitystorm** [comment]
> What do @gravitystorm and @tomhughes thing?

It seems reasonable to me, as a short term fix. It needs to replace the file though, not have a new name, or as @tomhughes says no tool will find it.

Longer term, I don't think OSMF should keep the entire set of diffs. The history dumps are a better source of historic data, and we should encourage tool developers to use them, both for technical reasons and also non technical ones. For example, because the diffs aren't retrospectively redacted, OSMF should really have removed the old ones already e.g. diffs over 18 months old.

**Comment by mmd-osm** [comment]
> Longer term, I don't think OSMF should keep the entire set of diffs The history dumps are a better source of historic data, and we should encourage tool developers to use them, 

We're happy to invite you to reimplement the Overpass API import process, then. Seriously, this will definitely break the Overpass API import process beyond repair, and we won't be able to offer any historic data anymore. It's an issue on the conceptual level, and a history dump will not help. I tried it before, it didn't work out at all.

**Comment by mmd-osm** [comment]
I've uploaded the corrected file here: http://dev.overpass-api.de/replication/000_000_876_new.osc.gz

**Comment by tomhughes** [comment]
I've replaced the live file with that.
