### ISSUE TITLE
Update tile caches to squid 4

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#339]
This is a tracking ticket to track progress on upgrading the tile caches to use squid 4:

- [x] angor.openstreetmap.org
- [x] ascalon.openstreetmap.org
- [x] balerion.openstreetmap.org
- [x] boitata.openstreetmap.org
- [x] cherufe.openstreetmap.org
- [x] chrysophylax.openstreetmap.org
- [x] cmok.openstreetmap.org
- [x] culebre.openstreetmap.org
- [x] drogon.openstreetmap.org
- [x] fafnir.openstreetmap.org
- [x] fume.openstreetmap.org
- [x] gorynych.openstreetmap.org
- [x] jakelong.openstreetmap.org
- [x] kalessin.openstreetmap.org
- [x] katie.openstreetmap.org
- [x] keizer.openstreetmap.org
- [x] konqi.openstreetmap.org
- [x] ladon.openstreetmap.org
- [x] longma.openstreetmap.org
- [x] necrosan.openstreetmap.org
- [x] nepomuk.openstreetmap.org
- [x] nidhogg.openstreetmap.org
- [x] noomoahk.openstreetmap.org
- [x] norbert.openstreetmap.org
- [x] ridgeback.openstreetmap.org
- [x] rimfaxe.openstreetmap.org
- [x] saphira.openstreetmap.org
- [x] sarkany.openstreetmap.org
- [x] simurgh.openstreetmap.org
- [x] stormfly-02.openstreetmap.org
- [x] toothless.openstreetmap.org
- [x] trogdor.openstreetmap.org
- [x] tuatara.openstreetmap.org
- [x] vipertooth.openstreetmap.org
- [x] viserion.openstreetmap.org
- [x] waima.openstreetmap.org

**Comment by grischard** [comment]
This will finally let us switch the tile servers to https only, and close #117, right?

**Comment by tomhughes** [comment]
I don't see why this is necessary for https, or would change anything in that regard.

I can't remember what the issues are with going https there, other than that it makes the rate limiting less effective, which is no different with squid 4.

**Comment by grischard** [comment]
IIRC, we currently have nginx in front of the old squids because the squids don't support https. The rate limiting is already less effective, because we never had time to do proper rate limiting in nginx or do buckets based on x-forwarded-for in squid.

We didn't set up redirection for the tile server because we were quite happy with bots hitting the better rate limiting on the http tile servers.

If we have squid 4 speak https directly, we get rid of nginx, redirect all http to https, throw everyone into the good rate limiting bucket, and get better rate limiting for everyone.

**Comment by tomhughes** [comment]
That is an option though @Firefishy has just been putting some caching in the nginx layer to take load off squid ;-)

**Comment by grischard** [comment]
The added value of nginx was that it terminated https. Why keep the complexity now?

While we're at it, we could also [disable TLS1.0 and TLS1.1 on that infrastructure](https://www.ssllabs.com/ssltest/analyze.html?d=a.tile.openstreetmap.org)?

**Comment by tomhughes** [comment]
Well the critical, and currently unknown question, is can squid (even with multiple workers) handle the load that would result. We know that it was struggling, which is why @Firefishy has been trying to offload some of the work to nginx though the addition of multiple workers in squid 4 may change that calculation.

As to the second question, why would we do that here before doing it anywhere else? As and when we decide to disable TLS1.0 and 1.1 we should do it everywhere, not cherry pick some services. Obviously there is a push to start dropping them from the start of next year but we have to bear in mind that will effectively exclude:

* Android 4.3 and earlier
* IE 10 and earlier
* Java 7 and earlier
* Safari 6 and earlier on OS X (but not on iOS)

I'm guessing Android is the biggest issue, followed by IE. Maybe @simonpoole has some idea on how big the Android issue is?

**Comment by simonpoole** [comment]
I'm fairly sure that browsers running on pre-4.3 are not effected as they likely are using non-system TLS implementations. As to apps that don't do that, they are essentially dead in the water AFAIK except if they do the same.

From an impact pov this is roughly ~2% of all android devices (these numbers tend to based on measurement methods that work against old versions, so might be off substantially), including all 1st generation android tablets. 2% is roughly 50 million devices (again these numbers need to be taken with large grains of salt).

**Comment by Firefishy** [comment]
Disabling TLS 1.0 and 1.1: https://blog.qualys.com/ssllabs/2018/11/19/grade-change-for-tls-1-0-and-tls-1-1-protocols
Likely worth disabling it at the beginning of January 2020. Likely worth announcing it before.
I'd recommend we redirect all HTTP traffic to HTTPS then too.

**Comment by Firefishy** [comment]
nginx caching seems to be working well. It is more flexiable than squid, but has poor reporting.
I was tempted to move all HTTP traffic across to nginx too, changing the backend port.

**Comment by grischard** [comment]
@Firefishy you're suggesting dropping squid completely?

**Comment by Firefishy** [comment]
@grischard No, I think squid has its place for bulk caching... nginx is best for hot item caching and specific logic like dropping URL parameters. nginx needs more investigation to work out the maximum number of items is can practically cache (Likely `keys_zone` being the main limit)
