### ISSUE TITLE
Set up replication for Nominatim servers

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/operations#34]
poldi and pummelzacken are currently running independent instances of Nominatim. That's ok as a hot standby but not useful for dividing traffic because the instances work with different placeids, so that requests are incompatible. The idea is to set up full replication of the DB with pummelzacken as master, which also runs the updates, and poldi as slave for fallback and for serving part of the requests.

I was hoping to have #4 resolved before tackling this but there has been a rather strong increase in traffic to Nominatim that means we really need the second server to help out.

Basic todo list:
- [x] set up postgres replication
- [ ] set up regular copy of flatnode file, so that we can fall back to the other server for doing updates
- [x] divide traffic between machines
- [x] automatically update php code on slave (via chef) 

For the first point, I'll have a look at the replication setup for the master DB servers. Is there any additional setup necessary that I should be aware of? Something like firewall setup etc.

**Comment by pnorman** [comment]
> set up regular copy of flatnode file, so that we can fall back to the other server for doing updates

You also need the state file to resume replication, which should be no *newer* than the flat nodes file.

**Comment by lonvia** [comment]
It is not in active use but the setup is done except the flatnode file backup. In practise it turned out that switching updates to a different machine is not really feasible. If master fails, we'd just be running on a static database until the master is back. The flatnode file backup is not really needed then. So closing here.
