### ISSUE TITLE
Check usage of expand_bbox call

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#341]
Over at https://github.com/openstreetmap/openstreetmap-website/issues/2316 / https://github.com/openstreetmap/openstreetmap-website/pull/2427 we have proposed removing the `expand_bbox` call from the API. We aren't aware of any software that uses it, but it would be best to check the logs.

So this ticket is a request for someone with access to the logs (presumably a sysadmin) to check if this call is being used. Thanks in advance.

**Comment by tomhughes** [comment]
There appear to be no uses in the last 28 days which is the limit of the logs.
