### ISSUE TITLE
Disk space on karm and eddie

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#343]
We need to start thinking about our plans for adding disk space to the database servers, karm and eddie, as they are now at 90% with about 1Tb free - it has grown from about 75% to 90% over the last year suggesting there is less than a year left.

Note that karm also peaks at closer to 95% when doing the backup each week.

**Comment by pnorman** [comment]
Karm's CPU is 4.5 years old and the P3700 drives in it are EOL, so they cost about 50% more per TB than newer faster drives do. I'm wondering if it makes more sense to get a new primary + mirror, then throw all the P3700s into one server for a second mirror.

**Comment by pnorman** [comment]
Notes:

DB growth is 15% y/y. 5 year estimate is 20TB. For RAID6 + 1 hot spare this is 8 4TB or 13 2TB

The modern version of karm and eddie is 2029U-TN24R4T

**Comment by hbogner** [comment]
Go for larger drives for more upgrade slots later on, usually faster speeds than smaller ones, overal DWPD is the same but larger drives can have more TB written.

**Comment by pnorman** [comment]
We have budget approval for this, and it's identified as a high priority.

Some open questions
1. Do we buy both servers at once, or stagger their purchases
2. 2TB or 4TB drives
3. How much CPU
4. How much RAM? 384, 512 or 768 are the logical options

My thoughts are
1. Both at once
2. Whichever is cheaper. Our DWPD is no where *close* to 1.
3. Not sure - will edit after studying munin
4. Not sure

**Comment by Firefishy** [comment]
Discussing with @tomhughes and @pnorman we are going to order 2x [P4510 2TB](https://www.scan.co.uk/products/2tb-intel-dc-p4510-25-u2-ssd-pcie-31-x4-nvme-12-3d-tlc-nand-3200mb-s-read-2000mb-s-write-637k-815k-i) for karm and 2x [P4510 2TB](https://www.scan.co.uk/products/2tb-intel-dc-p4510-25-u2-ssd-pcie-31-x4-nvme-12-3d-tlc-nand-3200mb-s-read-2000mb-s-write-637k-815k-i) for eddie. This is to give us some room while we plan disk upgrades.

FYI: Disks on karm have ~186TB written currently / ~1% write lifetime usage.

**Comment by grischard** [comment]
The disks are on their way.

**Comment by Firefishy** [comment]
2x disks installed in eddie.

**Comment by Firefishy** [comment]
2x disks have been posted to AMS. Tracking RN620061040GB
Need to arrange arrival + smart hands with Equinix

**Comment by tomhughes** [comment]
The extra disks have now been installed in karm.
