### ISSUE TITLE
DKIM sign outbound email

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#345]
We should DKIM sign outbound emails.

exim seems to have support. https://www.exim.org/exim-html-current/doc/html/spec_html/ch-dkim_and_spf.html

**Comment by tomhughes** [comment]
I just hate the idea of giving DKIM any legitimacy...

**Comment by pnorman** [comment]
Done with https://github.com/openstreetmap/chef/commit/19ca76c7c5e79cbb4e497b937376bffcb42d85fc and other chef commits

**Comment by mmd-osm** [comment]
There are some users on slack reporting that they don’t receive any email since dkim was enabled beginning of March. Seems to be Verizon/yahoo in the US. Is this a known issue?

**Comment by tomhughes** [comment]
No, but the signatures are fine so any issue are likely at their end. Those are not exactly the most reliable email hosts.

**Comment by tomhughes** [comment]
Note that we don't publish any DMARC policy, so even if the signature had been rendered invalid by forwarding or something then the question of what to do about that is up to the recipient - we haven't published policy saying such mails should be hard rejected, or even soft rejected.

**Comment by mmd-osm** [comment]
In fact there are two different users reporting very similar behaviour: 

> I have a verizon email and I also don't notifications of changeset comments. Actually I don't get notifications in my OSM account inbox either. I only found the comment through hdyc.

**Comment by tomhughes** [comment]
What exactly do you expect me to do though? Personally inspect every email going to Verizon to see if I can figure out who you are talking about and if there is any error being reported to us?

**Comment by tomhughes** [comment]
It looks like verizon use yahoo for mail anyway so that at least collapses it down to one problem.

A quick grep of today's log shows exactly three emails going to verzion.net addresses, all of which were mailing list posts, and all of which were accepted  by yahoo servers.

**Comment by Thorwynn** [comment]
I wrote the above about Verizon on Slack. I actually get emails from OSM about other things, Its just that someone commented on one of my changesets on 2020-02-13 but I never got any notice about this either through email or in my OSM inbox. In fact I had a message in my OSM inbox last fall that I left unopened purposely so the notification of it remind me to take care of it, but that disappeared at some point also.

**Comment by tomhughes** [comment]
Well there's nothing I can do about an email sent in February! The logs are long gone.

**Comment by Thorwynn** [comment]
The other person in Slack who complained about this specifically mentioned "others may appear unresponsive to changeset comments when actually the Emails are being blocked." So maybe its just changeset comment notifications that are broken?

**Comment by tomhughes** [comment]
I really need a specific example from the last week or two - details of a comment that was made and a person that didn't get notified. Otherwise I have nothing to look for.

**Comment by mmd-osm** [comment]
For the record, the other user was: https://www.openstreetmap.org/user/MikeN

**Comment by Thorwynn** [comment]
I just had someone comment on my most recent changeset & did get an email so I guess the Feb problem was just a fluke.

**Comment by MikeNice-IB** [comment]
I didn't get the changeset comment Email above (since 16 minutes).   My email would be niceman  (at) att.net

A better example with a longer time allowed for delivery is from 16 hours ago https://www.openstreetmap.org/changeset/85696544  somewhere around  26-May-2020  @ 02:00 UTC

If I can confirm that Verizon / Att/ Yahoo accepted the Email, I know that they're discarding the emails before they even get to my spam box and I can try to open the ticket with them.

**Comment by tomhughes** [comment]
It was refused by att.net because they appear to have blacklisted our server:

```
2020-05-26 17:24:32.451 [25207] 1jddJR-0006YQ-JM ** niceman AT att.net F=<bounces@openstreetmap.org> P=<bounces@openstreetmap.org> R=dnslookup T=signed_smtp H=ff-ip4-mx-vip2.prodigy.net [144.160.159.22]:25 PRX=[]:0 I=[212.110.172.32]:59448: SMTP error from remote mail server after MAIL FROM:<bounces@openstreetmap.org>: 553 5.3.0 flpd589 DNSBL:RBL 521< 212.110.172.32 >_is_blocked.For assistance forward this error to abuse_rbl@abuse-att.net
```

It must be a private DNSBL that they're running because https://www.dnsbl.info/dnsbl-database-check.php?IP=212.110.172.32 shows green for all the main public lists.

**Comment by MikeNice-IB** [comment]
Thanks - that's a great help.   I'll pursue this with AT&T.

**Comment by MikeNice-IB** [comment]
AT&T opened a ticket from my report and they appear to have removed the IP from their internal DNSBL.   A test changeset comment is now delivered to my Email.

Their boilerplate reply:
"The mail-server IP address(es) associated with your request will be removed from the block list within 24-48 hours from the date of this letter.  AT&T and its affiliates do NOT intentionally block legitimate mail in the course of our anti-spam initiatives and regret any inconvenience this may have caused.  If the IP that was recently blocked begins to exhibit the characteristics of a compromised network object or is compromised by an offender of Acceptable Use Policies, the IP address will be blocked again."
