### ISSUE TITLE
API 0.6 retrieving /history for a particular relation stalls and returns nothing

### ISSUE THREAD

**Issue by EwenH** [openstreetmap/operations#347]
I am trying to return the details for a mountain bike relation that is long (1060km), uses multiple road segments and has an extensive change history. The relation is [5810814](https://www.openstreetmap.org/relation/5810814) 

**Results (Chrome 79.0.3945.88):**
**Fails:** attempting to retrieve /history using this end point it fails to respond 

- https://www.openstreetmap.org/api/0.6/relation/5810814/history 

**Success:**
When attempting to retrieve the /full for the same relation it returns data as expected.

- https://www.openstreetmap.org/api/0.6/relation/5810814/full

Looking at a much simpler relation 8966633, both return xml correctly

- https://www.openstreetmap.org/api/0.6/relation/8966633/history
- https://www.openstreetmap.org/api/0.6/relation/8966633/full

Is the issue the complexity or just an oddity for this relation? The issue appears to have been present for over two weeks so appears that it is not intermittent or a one off.

**Comment by tomhughes** [comment]
The history call is provided by cgimap so this would need to be raised at https://github.com/zerebubuth/openstreetmap-cgimap/issues. Normally I would move the issue but I can't move to that repo.

**Comment by tomhughes** [comment]
That said it seems to work for me and responds in a matter of seconds - the result is about 8.4Mb so it wouldn't surprise me if the XML viewer in Chrome gave up on such a massive document.

**Comment by mmd-osm** [comment]
Right, Chrome needs almost 4 GB memory and almost two minutes to render the XML response.

Better use "Save link as..." or maybe wget or curl to download the result to a file.

**Comment by EwenH** [comment]
Thanks @tomhughes and @mmd-osm, I was using CURL to extract this and it started failing but thought it was easier to replicate and discuss the issue via Chrome.  I have increased the memory limit for the script thanks to both of you and it is now working again. It allows the management to track any unintended changes or where the official Government route is out of date.

**Comment by mmd-osm** [comment]
It sounds your use case is more analytical/monitoring in nature, which is not in scope for this api: https://operations.osmfoundation.org/policies/api/

You probably want to use Overpass api instead.
