### ISSUE TITLE
Slow request of tiles

### ISSUE THREAD

**Issue by helamdaini** [openstreetmap/operations#348]
The tiles request from the fetch function is very slow, specially for the zoom level > 10. it took 20 seconds and sometimes more:

 def fetch(self, request):
        url = self.parent._request_http(request)
        self.logger.info("Requesting %s", url)
        if self.parent.headers is not None:
            response = _requests.get(url, headers=self.parent.headers)
        else:
            response = _requests.get(url)
        if not response.ok:
            raise IOError("Failed to download {}.  Got {}".format(url, response))
        return response.content

how can i resolve this problem?

**Comment by tomhughes** [comment]
You probably can't - tile fetches are deliberately rate limited especially for third party users.

To get best available performance make sure you are complying with the [usage policy](https://operations.osmfoundation.org/policies/tiles/) especially that you are setting sensible user agent and/or referer values.

There are no performance guarantees however - it is a best effort service and we prioritise www.openstreetmap.org over third party users where necessary.

**Comment by Firefishy** [comment]
@helamdaini Can you send the output of https://tile.openstreetmap.org/cgi-bin/debug specifically cache server and render server.

**Comment by helamdaini** [comment]
@Firefishy: 
tile.openstreetmap.org debug
Server Stats
Cache Server: kalessin.openstreetmap.org

Render Server: odin.openstreetmap.org
Load Average: 15.58

File Status
simplified-land-polygons-complete-3857.zip last modified: Tue Jan 7 07:35:51 2020
simplified-water-polygons-split-3857.zip last modified: Tue Jan 7 07:35:56 2020
ne_110m_admin_0_boundary_lines_land.zip last modified: Wed Apr 3 17:50:02 2019
land-polygons-split-3857.zip last modified: Tue Jan 7 07:36:08 2020
water-polygons-split-3857.zip last modified: Tue Jan 7 07:36:38 2020
antarctica-icesheet-polygons-3857.zip last modified: Tue Jan 7 07:37:00 2020
antarctica-icesheet-outlines-3857.zip last modified: Tue Jan 7 07:37:03 2020
Browser Request Headers
HTTP_REFERER: https://github.com/openstreetmap/operations/issues/348
CONTEXT_DOCUMENT_ROOT: /srv/tile.openstreetmap.org/cgi-bin/
SERVER_SOFTWARE: Apache/2.4.29 (Ubuntu)
CONTEXT_PREFIX: /cgi-bin/
SERVER_SIGNATURE:

Apache/2.4.29 (Ubuntu) Server at tile.openstreetmap.org Port 443

REQUEST_METHOD: GET
SERVER_PROTOCOL: HTTP/1.1
QUERY_STRING:
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
HTTP_CONNECTION: keep-alive
SERVER_NAME: tile.openstreetmap.org
REMOTE_ADDR: 185.66.195.245
HTTP_VIA: 1.1 kalessin.openstreetmap.org (squid/4.9)
SERVER_PORT: 443
SERVER_ADDR: 130.117.76.15
DOCUMENT_ROOT: /srv/tile.openstreetmap.org/html
SCRIPT_FILENAME: /srv/tile.openstreetmap.org/cgi-bin/debug
SERVER_ADMIN: webmaster@openstreetmap.org
HTTP_SEC_FETCH_MODE: navigate
SCRIPT_URI: https://tile.openstreetmap.org/cgi-bin/debug
SCRIPT_URL: /cgi-bin/debug
HTTPS: on
HTTP_SEC_FETCH_SITE: none
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_CACHE_CONTROL: max-age=1209600
REQUEST_URI: /cgi-bin/debug
HTTP_SURROGATE_CAPABILITY: kalessin.openstreetmap.org="Surrogate/1.0 ESI/1.0"
GATEWAY_INTERFACE: CGI/1.1
HTTP_X_FORWARDED_FOR: 217.8.57.158, 127.0.0.1
SCRIPT_NAME: /cgi-bin/debug
REMOTE_PORT: 60536
REQUEST_SCHEME: https
HTTP_HOST: tile.openstreetmap.org
