### ISSUE TITLE
Switch 2 needs serial connected

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#349]
The Switch 2 at equinix needs a serial connector like switch 1 does.
Recently switch 2 became master and we were unable to access serial console connected via switch 1.

Switch 1 is connection to ironbelly via USB->Serial RJ45 connector.

**Comment by Firefishy** [comment]
Second serial confirmed working. Connected via ironbelly until replaced by oob system (likely tomorrow)

**Comment by grischard** [comment]
Is serial connected to oob now?

**Comment by Firefishy** [comment]
Yes. Serial now via OOB.
