### ISSUE TITLE
Renew Pingdom

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#35]
Our pingdom account is due for renewal and will be suspended in six days (24th June) if we haven't paid by then.

Also it emails every day complaining that it can't charge our card to topup our SMS credits - we should either give it a way to do so or decide we're not going to use SMS and turn the auto-topup off.

**Comment by tomhughes** [comment]
Amount due for the annual subscription is $599.25.

**Comment by Firefishy** [comment]
OSMF Treasurer has renewed via Paypal.
