### ISSUE TITLE
Rendered tiles not taking edits into account anymore

### ISSUE THREAD

**Issue by tbertels** [openstreetmap/operations#350]
Since 10 January 2020, standard layer rendered tiles don't seem to take into account new edits.

At https://www.openstreetmap.org/#map=18/19.38733/-97.96746 the standard layer shows nothing new, while the humanitarian one shows the added university: https://www.openstreetmap.org/#map=18/19.38733/-97.96813&layers=H

Same thing for this way: https://www.openstreetmap.org/way/762205989
https://b.tile.openstreetmap.org/19/270272/176375.png/status (already forced rendered) says
> Tile is clean. Last rendered at Sun Jan 12 18:09:56 2020. Last accessed at Sun Jan 12 18:10:04 2020. Stored in file:///srv/tile.openstreetmap.org/tiles/default/19/66/27/240/207/0.meta

**Comment by tomhughes** [comment]
Please be patient and stop forcing rerenders.

**Comment by tomhughes** [comment]
If you want to do something useful then go to https://tile.openstreetmap.org/cgi-bin/debug and tell us which render server you are using.

**Comment by tbertels** [comment]
Yes, I forgot that: ysera.openstreetmap.org

**Comment by tomhughes** [comment]
I've restarted replication on ysera and bowser and they are now catching up.

**Comment by tbertels** [comment]
Thanks, that was fast!
