### ISSUE TITLE
Activation of "Catwatch" $wgRCWatchCategoryMembership

### ISSUE THREAD

**Issue by muekoeff** [openstreetmap/operations#351]
Hello, I'd like to request the activation of the Mediawiki-global [`$wgRCWatchCategoryMembership`](https://www.mediawiki.org/wiki/Manual:CategoryMembershipChanges) ("Catwatch") for the OSM-wiki. Catwatch adds two new settings _"Hide categorization changes"_ in the user settings and allows a user to watch categories for changes in memberships to that category and displays these changes in the watch list and/or recent changes page.
These two options are enabled by default and therefore wouldn't change the default and present behaviour of Mediawiki. Additionally, a new switch _"Show page categorization"_ is added to the recent changes page, which is disabled by default.

My specific use case would be to watch [Category:Proposals with "Voting" status](https://wiki.openstreetmap.org/wiki/Category:Proposals_with_%22Voting%22_status) and some maintenance categories.

**Comment by Tigerfell** [comment]
I asked for comments at https://wiki.openstreetmap.org/w/index.php?title=Talk:Wiki&oldid=1950229#Current_requests_for_configuration_changes and there were no objections so far.

**Comment by Tigerfell** [comment]
@Firefishy I would like to open a PR to implement the feature on the main wiki only, but this needs code from openstreetmap/chef#257, because it is currently not possible to add general PHP configuration code for one wiki only, just inside the configuration of an extension, which would be confusing I guess.

**Comment by pnorman** [comment]
https://github.com/openstreetmap/chef/pull/400 has been merged which does the same as https://github.com/openstreetmap/chef/pull/257. Can you create a PR for the changes you want?
