### ISSUE TITLE
Rename OpenStreetMap Wikibase repo name

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/operations#352]
By default, `$wgWBClientSettings['repoSiteName']` falls back to the overall MediaWiki instance’s name, which results in misleading messages such as “[Show OpenStreetMap Wiki edits in your watchlist](https://wiki.openstreetmap.org/wiki/MediaWiki:Wikibase-watchlist-show-changes-pref/en)” and “[OpenStreetMap Wiki edits](https://wiki.openstreetmap.org/wiki/MediaWiki:Wikibase-rcfilters-hide-wikibase-label/en)” that actually refer to the Wikibase instance. As a result, users tend to [overlook](https://wiki.openstreetmap.org/wiki/Talk:Wiki#Transition_to_use_data_items_when_this_can_be_done_without_loosing_information) options that could make it easier to live with Wikibase, such as filtering data item changes out of their watchlists.

https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/c03c0db85cded61116b6e4d5f3948af3907b5e99/client/config/WikibaseClient.default.php#L184-L189

We should set the setting to something that can’t be confused with the overall wiki, such as “OSM Wikibase” or simply “data items”. I think the change would take place somewhere around here:

https://github.com/openstreetmap/chef/blob/16bd6e5fa3754e0a656790368459aab3ecca9368/cookbooks/wiki/templates/default/mw-ext-Wikibase.inc.php.erb#L67

/cc @Tigerfell @nyurik

**Comment by 1ec5** [comment]
For the time being, I’ve customized the two messages linked above to say “data items” instead of “OpenStreetMap Wiki”, but that only affects the English interface and I’m unprepared to make the same change for every major language used on the wiki. The `repoSiteName` configuration variable affects the `{{WBSITENAME}}` variable in the interface messages, which will automatically update all the relevant messages in all languages.

**Comment by pnorman** [comment]
PR https://github.com/openstreetmap/chef/pull/261 was closed without merging, so still an open request.

**Comment by matkoniecz** [comment]
I reopened it as https://github.com/openstreetmap/chef/pull/523

**Comment by Firefishy** [comment]
Is this still required?

**Comment by 1ec5** [comment]
It would be pretty nice to have. I’m still playing whack-a-mole customizing things to say “data items” to avoid confusion.

**Comment by Firefishy** [comment]
Change is now live.
