### ISSUE TITLE
Increase AbuseFilter throttling thresholds on the wiki

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/operations#353]
Yesterday I created [this “abuse filter”](https://wiki.openstreetmap.org/wiki/Special:AbuseFilter/10) to automatically [tag](https://wiki.openstreetmap.org/wiki/Special:Tags) changes to data item descriptions, so that users can [filter translation changes out of their watchlists](https://wiki.openstreetmap.org/wiki/Talk:Wiki#Transition_to_use_data_items_when_this_can_be_done_without_loosing_information). It was working well until it got [throttled](https://www.mediawiki.org/wiki/Extension:AbuseFilter#anchor-Emergency_throttling) due to a high incoming rate of matching edits. This feature is intended to head off mistakes where an administrator accidentally blocks everyone because of a malfunctioning filter. But in this case, we’re only using the filter to enhance watchlist filtering, not track abuse.

The default throttling heuristics are far too strict for this use case:

> Disable a filter if it matched more than 2 edits, constituting more than 5 % of the actions which were checked against the filter's group in the "observed" period (at most one day), unless the filter has been changed in the last 86400 seconds (one day).

All it takes is for someone to edit a handful of translations on a slow day to throttle this filter. The filter gets throttled silently without notifying administrators, and we have to modify the filter (not just a null edit) to reactivate it.

For reference, several Wikimedia wikis are configured to have [higher thresholds](https://noc.wikimedia.org/conf/highlight.php?file=InitialiseSettings.php) (search for `wgAbuseFilterEmergencyDisableThreshold`). I think we should similarly increase `wgAbuseFilterEmergencyDisableThreshold` to 30% and `wgAbuseFilterEmergencyDisableCount` to at least 25 edits per day.

/cc @Tigerfell @nyurik

**Comment by nyurik** [comment]
I agree that we should raise the threshold here too

**Comment by matkoniecz** [comment]
Would it potentially impact AbuseFilter that acts/blocks/deletes and is broken and should be stopped?

**Comment by 1ec5** [comment]
There would still be a limit. It would just be a little laxer, to account for editing volume more typical of smaller wikis like ours compared to Wikipedia.

**Comment by Tigerfell** [comment]
@1ec5 Do you think we need this change, if we had a better indicator for Wikibase edits? If so, I would suggest we tackle the root issue instead of enhancing a work-around.

**Comment by Firefishy** [comment]
Pushed https://github.com/openstreetmap/chef/commit/0ce945812edc79a9a404125f30ba3af49abe2bcc

**Comment by 1ec5** [comment]
> Do you think we need this change, if we had a better indicator for Wikibase edits? If so, I would suggest we tackle the root issue instead of enhancing a work-around.

There’s already a built-in filter for data item edits, but this custom filter is specifically about translations in data items. A feature request upstream in Wikibase might make sense, but I don’t have a strong opinion about what other filtering should go in the extension itself – maybe a language selector?

**Comment by Tigerfell** [comment]
@1ec5 I misunderstood your edit filter. I thought you intended to tag all Wikibase edits. 
@Firefishy It looks like you tried to close the issue, but it is still open.
