### ISSUE TITLE
Ask UCL for IPv6 allocation

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#354]
We currently do not have any IPv6 addressed at UCL / Slough. 

We check to see if we can be allocated an IPv6 range.

**Comment by pnorman** [comment]
We're moving services hosted there to Dublin - think we still need IPv6 for the stuff remaining?

**Comment by Firefishy** [comment]
I am going to close this. We are phasing out our servers @ UCL, unlikely the effort to request and configure IPv6 is justified.
