### ISSUE TITLE
Include pbf files in planet mirror redirect update

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#355]
(Just creating an issue for https://lists.openstreetmap.org/pipermail/dev/2020-January/030873.html for better tracking.)

---

@Firefishy wrote:

The 20GB+ planet .osm.bz2 files are automatically redirected to the
https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/
mirror. 

But unfortunately due to flaw in the mirror update script the redirect was not working for PBF files. **Pull requests welcome:**

https://github.com/openstreetmap/chef/blob/master/cookbooks/planet/templates/default/planet-mirror-redirect-update.erb

I have manually fixed the PBF file mirroring now (for current files).

---

That's what was happening in week 02:

> we started to exceed 1Gbps... Once we exceed the limit, packets get
dropped.

Redirect was manually re-established close to the end of week 04:

![image](https://user-images.githubusercontent.com/5842757/73287868-3aa8ec80-41fa-11ea-80b2-203a2161e449.png)

**Comment by mmd-osm** [comment]
A brief recap what was manually fixed:

* https://planet.openstreetmap.org/pbf/  
* https://planet.openstreetmap.org/pbf/full-history/

**Comment by mmd-osm** [comment]
This of course would require that our mirror https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/pbf/ to be able to download a new planet at full speed without being limited to 400K/s. Otherwise, many clients would start downloading from planet.openstreetmap.org instead, and we're seeing the spike again as last week. 

Unfortunately, after 24h, the planet file dated 30-Jan-2020 still hasn't made it to our mirror ftp5.gwdg.de:

![grafik](https://user-images.githubusercontent.com/5842757/73543631-a4620a00-4437-11ea-9506-cc8509343835.png)

It is indispensable that our mirror is up to date as quickly as possible, so can redirect traffic right away to the mirror site.

**Comment by tomhughes** [comment]
That mirror uses rsync and is not limited to 400Kb/s.

**Comment by mmd-osm** [comment]
Right, I think @Firefishy mentioned this before somewhere. Do we have some indication why the mirror is lagging behind that much?

**Comment by tomhughes** [comment]
That it downloads a huge amount of data?

It started at 15:09 yesterday, just over an hour after planet was published. I'm not sure what files it has got so far, or what order it is fetching in, but it is currently fetching `planet/full-history/2020/history-200127.osm.bz2` and is about 70% of the way through it.

**Comment by mmd-osm** [comment]
Looking through the different directories, it seems we've generated about 343 GB worth of data yesterday. Hopefully, rsync is configured to resolve `...-latest.*` files as symlink, rather than downloading them as normal files, in which case those figures would double.

```
history-200127.osm.bz2     2020-01-30 13:33  129G  
planet-200127.osm.bz2      2020-01-30 13:33   85G  
planet-200127.osm.pbf      2020-01-30 13:33   49G 
history-200127.osm.pbf     2020-01-30 13:33   80G  
```

It's a bit unfortunate that none of those files show up on the mirror until the rsync has actually finished. 

Could we delay publishing the osm.bz2 and history* files a bit so that planet-*.osm.pbf gets synched with the highest priority?

Then, we might ask ourselves why we're still offering 214 GB in osm.bz2 format, in particular for the history file. Is this something people typically still download? My expectation would be that everyone uses pbf these days as it's smaller and faster to download.  Running `osmium cat` on a pbf file  can easily recreate the osm.bz2 version.

**Comment by tomhughes** [comment]
Well a normal rsync would make each file available as it finished so I'm not sure if they're using some switch that does all the renames at the end? or using some other technique to get atomic updates?

**Comment by mmd-osm** [comment]
In the meantime, mirroring planet files to ftp.gwdg.de has finished.

What's left to do now is fixing Apache redirects for all new PBF (planet+full history) files, as per  https://github.com/openstreetmap/operations/issues/355#issuecomment-579208387. We should be good for another week then.

**Comment by mmd-osm** [comment]
@mtmail: I'm thinking more in terms of defining an array with different directories, their respective regex and the directory prefix used on the mirror, and then iterate over this array. Something along those lines:

```php
$_YEAR = date('Y');

$_MIRROR = 'https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/';

$_FOLDERS = [ 
              "planet_bz2" => [
                          'FOLDER'     => '<%= node[:planet][:dump][:xml_directory] %>/',
                          'REGEX'      => '/^(planet|changesets)\-\d{6}(\-nolt)?\.osm\.(bz2|gz)$/',
                          'DIR_PREFIX' => 'planet/'.$_YEAR.'/'
                          ],

              "history_bz2" => [
                          'FOLDER' => '<%= node[:planet][:dump][:xml_history_directory] %>/',
                          'REGEX'  => '/^(history)\-\d{6}(\-nolt)?\.osm\.(bz2|gz)$/',
                          'DIR_PREFIX' => 'planet/full-history/'.$_YEAR.'/'
                          ],
              "planet_pbf" => [
                          'FOLDER'     => '<%= node[:planet][:dump][:pbf_directory] %>/',
                          'REGEX'      => '/^(planet|changesets)\-\d{6}(\-nolt)?\.osm\.pbf$/',
                          'DIR_PREFIX' => 'pbf/'
                          ],

              "history_pbf" => [
                          'FOLDER' => '<%= node[:planet][:dump][:pbf_history_directory] %>/',
                          'REGEX'  => '/^(history)\-\d{6}(\-nolt)?\.osm\.pbf$/',
                          'DIR_PREFIX' => 'pbf/full-history/'
                          ]
            ];

$_PLANET_HTACCESS = realpath('<%= node[:planet][:dump][:xml_directory] %>/..').'/.htaccess';

function _MIRROR_FILE_SIZE($url) {
	$ch = @curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_NOBODY, TRUE);
	curl_setopt($ch, CURLOPT_VERBOSE, FALSE);
	$curl_response = @curl_exec($ch);
	$curl_result = curl_getinfo($ch);
	if ($curl_result['http_code']!='200') return FALSE;
	return ($curl_result['download_content_length']);
}

if (!is_writable($_PLANET_HTACCESS)) die('File '.$_PLANET_HTACCESS.' is not writable by current user.'."\n");

$htaccess_contents = file_get_contents($_PLANET_HTACCESS);
$htaccess_handle = fopen($_PLANET_HTACCESS, 'a');

foreach ($_FOLDERS as $FOLDER) {

  $_PLANET_FOLDER = $FOLDER["FOLDER"];
  $_PLANET_REGEX  = $FOLDER["REGEX"];

  if (!(is_dir($_PLANET_FOLDER))) {
    continue;
  }

  if ($dh = opendir($_PLANET_FOLDER)) {
    while (($file = readdir($dh)) !== false ) {
      if (preg_match($_PLANET_REGEX, $file)) {
        $file_slashed = $FOLDER['DIR_PREFIX'].str_replace(array('.','-'), array('\.','\-'), $file);
	if (strpos($htaccess_contents, $file_slashed) === false) {
          $file_size = filesize($_PLANET_FOLDER.$file);
	  sleep(rand(2,5));
	  $file_mirror_size = _MIRROR_FILE_SIZE($_MIRROR.$file);
	  if ($file_size==$file_mirror_size) {
            echo 'Adding: '.$file."\n";
            fwrite($htaccess_handle, 'RewriteRule'."\t". '^('.$file_slashed.')$'."\t".$_MIRROR.'$1'."\t".'[R,L]'."\n");
          }
        }
      }
    }
    closedir($dh);
  }
}

fclose($htaccess_handle);
```

**Comment by mmd-osm** [comment]
@tomhughes : I added some more folders to the planet-mirror-redirect-update script (see previous) post, and ran some basic local testing using sparse files (simulate files via `truncate -s 91347973049 planet-200127.osm.bz2`). A few new .htaccess entries were created as a result, and I believe those should be good.

I'm not fully convinced if this good enough for a PR. Could you maybe take a look, if this seems ok?

**Comment by tomhughes** [comment]
You want @Firefishy really - that script is his doing and I don't profess any PHP knowledge...

**Comment by mmd-osm** [comment]
I've created a pull request for this now: https://github.com/openstreetmap/chef/pull/265

Please feel free to edit / adjust as needed. Thanks!

**Comment by Firefishy** [comment]
Awesome! Nice work @mmd-osm . Thank you.

Some output...
```
Adding: history-200120.osm.bz2
Adding: history-200106.osm.bz2
Adding: history-200127.osm.bz2
Adding: history-200113.osm.bz2
Adding: planet-200127.osm.pbf
Adding: history-200127.osm.pbf
```
