### ISSUE TITLE
Add striktrough template on the wiki

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/operations#356]
Having a template like this one from Wikipedia would be useful for text formatting on the wiki (when retracting comments for example) https://en.wikipedia.org/wiki/Template:Strikethrough

**Comment by tomhughes** [comment]
You don't need operations to create a template do you? I'm not sure you even need a wiki admin...

**Comment by tomhughes** [comment]
I'm not really sure why `{{Strikethrough|text}}` is better than `<s>text</s>` which is what it expands to but I see no reason why this needs operations involvement - just create that template if you want it and copy over the source from wikipedia.
