### ISSUE TITLE
Enable SMTP MTA Strict Transport Security (MTA-STS)

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#357]
We should consider publish DNS records for SMTP MTA Strict Transport Security (MTA-STS):  https://tools.ietf.org/rfc/rfc8461.txt

**Comment by tomhughes** [comment]
You can't just publish a DNS record - you need to have a web server that serves up a policy document as well I believe.

**Comment by tomhughes** [comment]
By the way do you know of any evidence of people using this? or of MTAs that use it when sending mail?

**Comment by Firefishy** [comment]
Both Gmail and Outlook Online support it as far as I know. Google and Microsoft are co-authors of the RFC.

**Comment by tomhughes** [comment]
Published (eventually) in testing mode: https://www.hardenize.com/report/openstreetmap.org/1580238589#email_mta_sts

**Comment by tomhughes** [comment]
This is now enforcing.
