### ISSUE TITLE
Move away from BBR as congestion control algorithm

### ISSUE THREAD

**Issue by zorun** [openstreetmap/operations#359]
All servers were switched to the BBR congestion control algorithm:
https://github.com/openstreetmap/chef/commit/67c05c6c4b484a6cdac9473b4e6951e5c76c42a3
https://lists.openstreetmap.org/pipermail/dev/2020-January/030873.html

For tiles, it was not an issue because files are very small. But for larger downloads, BBR is known to behave very unfairly. In particular, in some circumstances, it can generate massive amount of packet loss and completely crush non-BBR streams.

Quoting from [this paper](http://doc.tm.uka.de/2017-kit-icnp-bbr-authors-copy.pdf):

```
On the one hand, the intended behavior
of BBR could be observed with our experiments. On the other
hand, some severe inherent issues such as increased queuing
delays, unfairness, and massive packet loss were also detected.
```

Thus, I would suggest to revert this change. At the very least, this would likely improve the situation for the 1 Gbit/s uplink mentioned in the mailing list discussion above: currently, anybody that can pull files at more than ~600 Mbit/s may cause massive packet loss for all streams.

**Comment by pnorman** [comment]
We're back on cubic: https://github.com/openstreetmap/chef/commit/484bf308fb9f43eda4c2d7ac7b3d3d23a3288044

**Comment by Firefishy** [comment]
@zorun Appreciated the heads up. We'll wait for BBR v2. If you spot anything else, we'd be happy to hear from you.
