### ISSUE TITLE
Replace remaining HP DL360 G6 servers

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#361]
These are getting old, with the CPUs launched in 2010. They should be replaced like the others were last year. There are 7 machines.

The hardware in question are
## UCL
* clifford.openstreetmap.org (forum)
* eustace (piwik)
* noquiklos (GPS tile)
* ridley (foundation-related sites)
* urmel (munin)

## OSUOSL
* stormfly-01 (taginfo)
* stormfly-02 (tile cache)

* [x] Budget requested based on list prices
* [x] Budget obtained
* [x] Specs written
* [x] Quotes obtained from UK vendors
* [x] Quotes obtained from US vendors
* [x] UK servers ordered
* [x] US servers ordered

**Comment by pnorman** [comment]
US HP servers are thie higher priority since one of the stormfly servers is an overloaded cache node.

480GB is enough disk space for everything to last 5 years at current growth rates. noquiklos is closest at 450GB forecasted need.

**Comment by pnorman** [comment]
Now that the DB machines are on order I can get back to this. I need to review my notes on specs.

**Comment by pnorman** [comment]
US orders sent to treasurer.

**Comment by pnorman** [comment]
We should decide on UK specs now, even if we put off purchasing for a bit due to COVID restrictions.

Across the five machines noquiklos has the highest usage at 290GB and 13% y/y growth for 530GB needed in 5 years.
None of them need >32GB except for caching. I'd go with 64GB or 96GB.
noquiklos peaks at 12 CPU threads. (6 cores).

Looking at pricing I'd go with

2x E5-2680v4 (cheaper than 2620v4)
96GB DDR4-2400
P440ar with battery
561FLR-T (10GB Intel X540 FlexLOM card)
2x 800GB HP SSD
2x 500W Plat power sxupply
Easy install rail kit (ball bearing is the same price)
ILO

The only open question I see is if we go SATA or SAS for the drives - we've gone both ways with past purchases.

cc @Firefishy

**Comment by hbogner** [comment]
I'm a fan of Supermicro machines and would recommend going that way, we use them in 99% of the cases. I could try and see who to contact in UK for best service/quote...

**Comment by pnorman** [comment]
We made the decision some years ago to use used HP 360 machines for these type of tasks. When we need a new machine that's customized we go with supermicro.

**Comment by hbogner** [comment]
Thx for the info, I get it, keep the machines as much as same as they can be.
I use used supermicro for my servers whenever I can. Rhaegal came from UK as I can remember :)

**Comment by Firefishy** [comment]
My preference is SAS disks over SATA disks for busy servers.

**Comment by pnorman** [comment]
Sufficient HP DL360 Gen9 servers are on order to Dublin to replace the machines listed here.

**Comment by pnorman** [comment]
Remaining servers are on order and tracked in https://github.com/openstreetmap/operations/issues/525
