### ISSUE TITLE
Alternative authoritative DNS for OpenStreetMap.org domains

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#362]
Currently we use Bytemark for NS / Authoritative DNS for the OpenStreetMap.org + other domains.

It would be pragmatic to consider finding an alternative DNS provider.

Criteria:
1) Fast to query globally.
2) Rock solid reliably / availability.
3) API access to update / manage.
4) Affordable.

**Comment by Firefishy** [comment]
Cloudflare offer DNS hosting: fast, reliable, API and free.

**Comment by tomhughes** [comment]
I'm already working on a plan... That plan in fact ;-)

**Comment by tomhughes** [comment]
You might notice my domain has been hosted with them (and DNSSEC enabled) for about a week now ;-)

**Comment by Firefishy** [comment]
Ha! I was just about to mention DNSSEC.

**Comment by tomhughes** [comment]
I was looking for ways to actually make it work last night and found https://stackexchange.github.io/dnscontrol/ which will do a good job I think of letting us keep git in sync with any one of a range of providers.

**Comment by Firefishy** [comment]
Wow, dnscontrol looks awesome!

**Comment by tomhughes** [comment]
DNS has been with cloudflare for some weeks now.
