### ISSUE TITLE
Dropping TLSv1 and TLSv1.1 support

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#363]
We should consider if we want to drop support for TLSv1 and TLSv1.1 as there is a general effort to deprecate them.

Since the start of the month SSL Labs is capping grades to B if they are enabled and, for example, the Stack Exchange network is [planning to turn them off](https://meta.stackexchange.com/questions/343302/tls-1-0-and-tls-1-1-removal-for-stack-exchange-services?cb=1) on 12th February.

Chrome, Edge, Firefox and Safari are all planning to drop client side support in March.

Looking at traffic to one of the www.openstreetmap.org frontends for yesterday we see:

* TLSv1 - 71365
* TLSv1.1 - 1293
* TLSv1.2 - 10651609

No TLSv1.3 yet as Ubuntu 18.04 doesn't support it.

From SSL Labs clients that would no longer be able to connect are:

* Android 4.3 and earlier
* IE 7 on Vista
* IE 8-10 on Windows 7 (but IE 11 works)
* IE 10 on Windows Phone 8.0 (but IE 11 on Windows Phone 8.1 works)
* Java 7
* OpenSSL 0.9.8
* Safari 6 and earlier on OS X (so OS X 10.8 and earlier)

**Comment by Firefishy** [comment]
To guage what others think I have created a Twitter poll: https://twitter.com/OSM_Tech/status/1226471866803671041

**Comment by tomhughes** [comment]
There is a related question about updating the cipher list - the latest [Mozilla intermediate configuration](https://ssl-config.mozilla.org/#server=apache&version=2.4.41&config=intermediate&openssl=1.1.1d&guideline=5.4) which is what we have used in the past would drop a number of older ciphers.

I don't have a full analysis of that yet but we think it would knock out some more things - to start with although Mozilla say it supports Safari 9 I believe that is only true on OS X 10.11 and newer.

**Comment by cquest** [comment]
Why do we need to **enforce** high security levels on the server side ?
We're not a bank !

My point of view is that if a user wants to be sure to use only the latest and highest ciphers and protocols, it's up to him to enforce that on the client side, not the server. Just make sure the servers supports TLS v1.3 and latests ciphers with the older ones.

Even http is fine most of the time that forcing https seems overkill in many cases.

**Comment by Firefishy** [comment]
> Why do we need to **enforce** high security levels on the server side ?
> We're not a bank !
> 

Indeed we are not a bank, but we have mappers globally who may be mapping in regions or territories where citizen mapping could put mappers into legal hot water. The sysadmin team, should take pragmatic steps to ensure the privacy and integrity of our mappers' access to the OpenStreetMap websites.

> My point of view is that if a user wants to be sure to use only the latest and highest ciphers and protocols, it's up to him to enforce that on the client side, not the server. Just make sure the servers supports TLS v1.3 and latests ciphers with the older ones.
> 

It is possible that leaving older TLS protocols enabled may introduce weaknesses, which would allow communications to be more easily Man-in-the-Middle attacked or sniffed.

**Comment by mmd-osm** [comment]
What would be the impact on mobile apps using api.openstreetmap.org?

**Comment by tomhughes** [comment]
As documented above?

**Comment by mmd-osm** [comment]
I mean, do we know which apps on iOS or Android would be impacted (assuming that some of them would use their own libs, etc.), and would that differ from the stats you mentioned for www.openstreetmap.org.

**Comment by tomhughes** [comment]
No I'm sorry but I'm afraid my crystal ball is malfunctioning this morning.

As far as I know mobile apps generally use the networking facilities of the operating system so I would expect Android 4.3 and earlier to be affected by protocol changes and iOS 8 and earlier to be affected by cipher changes.

The statistics I gave are for one of the frontend servers, so other than only being one out of three that don't differ in any way - the API is just part of the web site and api.openstreetmap.org is just an alias for www.openstreetmap.org and nobody makes people use one name or the other for API requests.

**Comment by simonpoole** [comment]
@tomhughes I suspect more relevant numbers would be actual "editing" access, that is to the changeset or diff upload endpoints (mainly because for everything else there are alternatives, and browsers potentially are bringing their own implementations with them in any case).

**Comment by tomhughes** [comment]
So out of 37041 called to create a changeset yesterday 35159 were TLSv1.2 and 1882 were TLSv1.

The vast majority of the TLSv1 calls have no user agent at all, suggesting some sort of custom tool. The full breakdown is:

* Unknown - 1837
* StreetComplete - 26
* OsmAnd - 7
* Unknown app on Android 4.4.2 -12

The last one just identifies as Dalvik and is I suspect one individual.

**Comment by simonpoole** [comment]
That would seem to clearly support moving forward with droping ..... the only problem is that there is no way to announce it to those 1882 users.

**Comment by mmd-osm** [comment]
CGImap log files contain both user IP address and the changeset id in a single line. This in turn could be used to identify user accounts.

For sure this adds extra effort but there are ways to find those users.

**Comment by RubenKelevra** [comment]
@simonpoole well, there is a way... we know which changesets has been generated, so we have user accounts associated with it. Maybe generate automatic DMs when a changeset has been generated via TLSv1/TLSv1.1 or an outdated cipher.

**Comment by RubenKelevra** [comment]
> The last one just identifies as Dalvik and is I suspect one individual.

Or it might be related to the old Virtual Machine Android used. So an application that doesn't set a default string of some kind and the default of the VM was Dalvik? :)

**Comment by tomhughes** [comment]
The browser phase out was delayed by COVID but Firefox 78 has now moved ahead and disabled TLS 1.0 and 1.1 and I believe Chrome 84 is due to do the same.

**Comment by tomhughes** [comment]
It turns out that OpenSSL in Ubuntu 20.04 has TLS 1.0 and 1.1 disabled by default so we actually been gradually doing this already as we perform upgrades!

That doesn't include the main web site yet but does include many secondary services.

**Comment by Firefishy** [comment]
Ubuntu 18.04 -> 20.04 upgrades are listed here if anyone is interested: https://github.com/openstreetmap/operations/issues/427 Services can be matched up again https://hardware.openstreetmap.org/

**Comment by Firefishy** [comment]
Looks like we still enabled TLS 1.0 and TLS 1.1 in Ubuntu 20.04, it just takes a bit more work.

**Comment by tomhughes** [comment]
Yes it would mean taking the whole of `/etc/ssl/openssl.cnf` under chef control and adding a `crypto_policy` section as there is no drop in support other than via explicit includes which doesn't help.

**Comment by tomhughes** [comment]
Chrome 84 is now out and has disabled 1.0 and 1.1 although I believe for now you can still click through the warning for a few more months.

**Comment by simonpoole** [comment]
Just for the record, an issue I ran in to just now. 

Vespucci supports TLS 1.2 on 4.1 to 4.4 devices, however the WebView implementation on these devices is potentially not replaceable and potentially does not support 1.2. The result is that while the app will work just fine for API calls etc. authorizing the app with OAuth will fail (because that is partially handled by the WebView).

**Comment by tomhughes** [comment]
I just checked the logs on one of the frontends, and going back the full 28 days there are no calls to `/oauth/` using TLSv1.0 so it doesn't look likely that anybody much will be affected.

The production site has actually had 1.0 and 1.1 disabled since Sunday and there have been no issues raised so far.

**Comment by mmd-osm** [comment]
@simonpoole : JOSM does all this stuff under the hood in "fully automatic mode" without any browser component involved. Maybe that could be an option for those users affected by the issue. Security wise this isn't exactly best practice, using Basic Auth probably isn't either.

**Comment by simonpoole** [comment]
@mmd-osm I'm fully aware of what JOSM dies and it clearly isn't best or even good practice.

**Comment by mmd-osm** [comment]
(For the sake of completeness, this is the JOSM implementation in question: https://github.com/openstreetmap/josm/blob/master/src/org/openstreetmap/josm/gui/oauth/OsmOAuthAuthorizationClient.java - the code fakes all browser based communication.)

**Comment by pnorman** [comment]
The tile CDN no longer has support for TLS 1.0 or 1.1

**Comment by pnorman** [comment]
As a consequence of upgrades to 20.04 we have dropped TLS 1.0 and 1.1 from most services, and the remaining ones will be done as we upgrade them.
