### ISSUE TITLE
Tiles not updated at zoom levels ~14-15 but tile status says clean and rendered recently

### ISSUE THREAD

**Issue by ftrebien** [openstreetmap/operations#365]
Hello,

Thank you for all your efforts in delivering OSM services to the world. I am not filing a complaint, but it could be a bug.

After [this significant edit on February 13th](https://www.openstreetmap.org/changeset/80979626), which changed the classification of a city's highway system to better match the [official classification](https://wiki.openstreetmap.org/wiki/Passo_Fundo/Sistema_Vi%C3%A1rio#Passo_Fundo), I used _/dirty_ several times to request a rerender of some specific tiles. I did so when the pyrene server (which serves the boitata server, which serves requests from my area - Brazil) had low load, which is mostly at night. The tiles of zoom levels 16 and higher started to update on the same day, even at times when server load was high. Many alternative tile servers, which usually take longer to update, such as osm.de, osm.fr, osm.bzh, HOT and OpenCycleMap, have already updated zoom levels 14 and higher. [This](https://mc.bbbike.org/mc/?lon=-52.399018&lat=-28.260587&zoom=15&num=4&mt0=mapnik&mt1=mapnik-german&mt2=osmfr&mt3=osmfr-hot) looks like [this](https://i.imgur.com/IOOKeA8.png) to me at the moment, showing that only the main tile layer is significantly outdated at zoom level 15. Although the area has little mapping activity and probably little demand for tiles, I suspect that the behavior I am receiving might be due to some configuration problem in boitata or in pyrene.

As an example, [this tile](https://a.tile.openstreetmap.org/15/11613/19067.png) should be dirty since February 13th. Its _/status_ reports that it was rendered today, but its contents do not reflect the many significant changes in the data. If it was rerendered, it must have used old data. If this is intentional for this zoom level, please ignore this report.

Output of https://b.tile.openstreetmap.org/cgi-bin/debug:

Cache Server: boitata.openstreetmap.org
Render Server: pyrene.openstreetmap.org
Load Average: 13.37

File Status
simplified-land-polygons-complete-3857.zip last modified: Thu Jan 9 07:10:24 2020
simplified-water-polygons-split-3857.zip last modified: Thu Jan 9 07:10:31 2020
ne_110m_admin_0_boundary_lines_land.zip last modified: Mon Sep 3 20:17:11 2018
land-polygons-split-3857.zip last modified: Thu Jan 9 07:11:36 2020
water-polygons-split-3857.zip last modified: Thu Jan 9 07:13:04 2020
antarctica-icesheet-polygons-3857.zip last modified: Thu Jan 9 07:13:29 2020
antarctica-icesheet-outlines-3857.zip last modified: Thu Jan 9 07:13:39 2020
Browser Request Headers
CONTEXT_DOCUMENT_ROOT: /srv/tile.openstreetmap.org/cgi-bin/
SERVER_SOFTWARE: Apache/2.4.29 (Ubuntu)
CONTEXT_PREFIX: /cgi-bin/
SERVER_SIGNATURE:

Apache/2.4.29 (Ubuntu) Server at tile.openstreetmap.org Port 443

REQUEST_METHOD: GET
SERVER_PROTOCOL: HTTP/1.1
QUERY_STRING:
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
HTTP_USER_AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
HTTP_CONNECTION: keep-alive
SERVER_NAME: tile.openstreetmap.org
REMOTE_ADDR: 2801:82:80ff:8002:216:ccff:feaa:21
HTTP_VIA: 1.1 boitata.openstreetmap.org (squid/4.10)
SERVER_PORT: 443
SERVER_ADDR: 2605:bc80:3010:700::8cd3:a762
DOCUMENT_ROOT: /srv/tile.openstreetmap.org/html
SCRIPT_FILENAME: /srv/tile.openstreetmap.org/cgi-bin/debug
SERVER_ADMIN: webmaster@openstreetmap.org
SCRIPT_URI: https://tile.openstreetmap.org/cgi-bin/debug
HTTP_DNT: 1
HTTP_HOST: tile.openstreetmap.org
SCRIPT_URL: /cgi-bin/debug
HTTPS: on
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_CACHE_CONTROL: max-age=1209600
REQUEST_URI: /cgi-bin/debug
HTTP_SURROGATE_CAPABILITY: boitata.openstreetmap.org="Surrogate/1.0 ESI/1.0"
GATEWAY_INTERFACE: CGI/1.1
HTTP_X_FORWARDED_FOR: 189.6.132.236, 127.0.0.1
SCRIPT_NAME: /cgi-bin/debug
REMOTE_PORT: 39104
REQUEST_SCHEME: https

**Comment by tomhughes** [comment]
I'm afraid we don't have the resource to investigate individual rendering issues.

Please just be patient, and don't use `/dirty` as it just makes service worse for everybody.

**Comment by tomhughes** [comment]
I have checked that pyrene has the current stylesheet deployed and that the tile you mention was last rendered today.

You don't what you think is wrong about the image, but the version pyrene is serving seems to be the same as the one ysera is serving so it seems unlikely that there is any rendering problem.

**Comment by ftrebien** [comment]
Hello @tomhughes . As for my personal use of the map, I don't mind waiting, but I'm a little concerned that none of the casual mappers in the area are in contact with the national community or even the regional community, so they may be confused by the differences that they see when making the transition between these zoom levels. I use _/dirty_ sparingly and only in very special situations, as originally intended.

I don't have an in-depth knowledge of the entire rendering system, so I'm guessing that this may be a configuration issue, but it may also be a bug. I believe that boitata may be asking pyrene to rerender the tiles, and pyrene somehow is returning old versions of the tile, then boitata reports thinks the tiles it received are up-to-date. I'm well aware that lower zoom levels take longer to update by design, but I always thought this was for zoom levels 13 and lower.

**Comment by tomhughes** [comment]
I assume you're expecting an orange secondary road across that tile but you're seeing a tertiary?

The render server seems to be correct ([here](https://pyrene.openstreetmap.org/15/11613/19067.png)) so this just seems to be a cached tile on boitata that will expire in due course.

**Comment by ftrebien** [comment]
Yes, [this](https://pyrene.openstreetmap.org/15/11613/19067.png) is what I expected from an updated tile. I will wait then. Could it be that boitata has any problem with its cache configuration for this zoom level? If so I could try contacting the maintainers.

**Comment by tomhughes** [comment]
How could there be a problem? The caches don't care what the zoom level is, they cache everything equally.

I'm not sure what maintainer you think you're going to contact - we are the maintainers.

You have to understand that `/status` goes direct to the render server and tells you the status there. It knows nothing about whether the tile is cached by nginx and/or squid on the cache server or when that cache is due to expire.

**Comment by tomhughes** [comment]
In fact the tile on boitata didn't come from pyrene, it came from rhaegal.

**Comment by tomhughes** [comment]
The tile has in fact now rerendered on rhaegal but it wasn't able to do it in real time so it served the old version to boitata. Basically this is all just fairly normal stuff and will fix itself in due course.

**Comment by ftrebien** [comment]
Oh, alright. I thought that boitata, which the wiki says is located at UFPR (a national university here in Brazil), actually had local maintainers.

rhaegal? That's [unexpected to me](https://dns.openstreetmap.org/render.openstreetmap.org.html), but as I said I'm not so knowledgeable about the details. I thought that requests from Brazil would go to boitata and from that to pyrene.

I will wait then. I was just a little puzzled that level 16, which had many more tiles to update, was updated throughout the city a few minutes after the edit, while level 15 is still not updating anywhere at all (not just that tile) even 3 days after the edit, even after refreshing the tiles at times of low server load.

**Comment by tomhughes** [comment]
The upstreams are not fixed - they can change as servers come and go. Plus squid also has fallback to the other render servers if the normal one doesn't answer.

UFPR provide the hardware but we manage the software.

Zoom 16 tiles are much faster to render so are more likely to rerendered in real time rather than in the background after the old tile has been returned.

**Comment by ftrebien** [comment]
Thank you for all the clarifications, @tomhughes .
