### ISSUE TITLE
Review other servers for capacity

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#367]
We have plans to refresh the [API servers](https://github.com/openstreetmap/operations/issues/343) the remaining [HP DL360 G6](https://github.com/openstreetmap/operations/issues/361), and to [upgrade nominatim capacity](https://github.com/openstreetmap/operations/issues/259).

We need to go through the [hardware list](https://hardware.openstreetmap.org/) and for each server in not in the above lists that is hosted at Equinix Amsterdam, University College London (UCL), or bytemark check its munin stats to see if anything is near or at capacity.

**Comment by Firefishy** [comment]
I believe we should plan moving some more stuff to the EU continent or Ireland, either physically or by buying now.

**Comment by Firefishy** [comment]
What data centers are there in Ireland? Any have good deals on or want to help a Open Source project?

**Comment by pnorman** [comment]
Superseded by 2021 planning.
