### ISSUE TITLE
Asset Register

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/operations#37]
Our accountant would like to have an asset register. An ideal asset register would list all assets with
- time of purchase and price (this is already known from the invoices)
- any identifying information like a serial number for large items (currently not recorded)
- whether the item is still in service, or out of service (broken, lost, or thrown away)
- if still in service, where (which data centre or part of which machine)
- if out of service, time when the item went out of service

Ideally that register would be updated yearly, in spring, in time for the preparation of the yearly financial figures.

This is our current account register according to the books:
http://www.remote.org/frederik/tmp/asset_register.ods
(note link may not be there any more if viewing this later than 2015).

We're not looking to create an _ideal_ register at this time, but it would be great if OWG could at least put a column to that list that says "definitely still here / definitely gone / don't know", and where it is easy to say also add info about where the item is or when approximately it went out of service (year is enough).

The number of items in the list may be a bit daunting, and the most interesting items are really those bought in the last four years and/or the more expensive ones. Even if you can only give information on 10-20% of the items, that would already be quite helpful for accounting.

**Comment by woodpeck** [comment]
A new asset register (as of 2015-12-31) has been compiled with your help, and sent round by email. That asset reigster has only 77 items remaining and should serve as a good starting point to track our inventory properly in the future.

**Comment by zerebubuth** [comment]
@woodpeck are you happy for us to close this issue?
