### ISSUE TITLE
Stop running CGI:IRC on irc.openstreetmap.org

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/operations#374]
Seems like we should think about ceasing with running CGI:IRC ( http://cgiirc.org/  perl IRC web client) on irc.openstreetmap.org for a couple of reasons:

* I'm told OFTC would prefer us not to be doing this. It makes handling abuse harder for them. dwfreed on IRC knows more. I'm not sure how strongly they feel or how urgent that is. Not _super_ urgent I would guess. If it was a heavy channel for abuse, then we'd know about it! But we don't want to be making life harder for OFTC. Also...
* I didn't get a response to this https://github.com/dgl/cgiirc/issues/12 which seems like a fairly stupid issue which should be easy to fix. The issue itself means that OFTC's client is better, and we end up _having to_ link to it instead of our own (https://github.com/osmlab/osm-community-index/issues/136 ) ...but also this might suggest CGI:IRC is not well maintained

When I say "stop running" we could either just redirect irc.openstreetmap.org to https://webchat.oftc.net/?channels=#osm 

Or (better?) we could embed it as an iframe with some channel presets. This is something they encourage on there. See the _"Add webchat to your site"_ option.

**Comment by tomhughes** [comment]
Another problem is that Ubuntu no longer have `cgiirc` in their package set - the version we're running is from a previous release and just remained over upgrades over the years.

That's why the irc cookbook didn't get a test, because the test can't work as it can't install the package...

**Comment by Firefishy** [comment]
I am in favour of us redirecting. Alternatively we could public a static page with links to https://webchat.oftc.net/?channels=#osm https://webchat.oftc.net/?channels=#osm-dev etc.

**Comment by gravitystorm** [comment]
> Alternatively we could publish a static page with links to

I think this would be the best option, since we have a bunch of different channels which are otherwise hard to discover.

**Comment by harry-wood** [comment]
on CGI:IRC I like the drop-down o  box to choose a channel to join. Unfortunately the iframed webchat.oftc.net doesn't behave like that. It lets us specify multiple channels but that ends up like this:  https://webchat.oftc.net/?channels=osm%2Cosm-dev%2Chot%2Cosm-gb&uio=MT11bmRlZmluZWQb1  ...which lets the user join _all the channels_ all at once.

Guess we could make our own form to launch https://webchat.oftc.net

**Comment by Firefishy** [comment]
Here is the list of channel: https://github.com/openstreetmap/chef/blob/master/cookbooks/cgiirc/templates/default/cgiirc.config.erb#L11

I would list each out individually and with a separate link to https://webchat.oftc.net for each.

**Comment by tomhughes** [comment]
Done.
