### ISSUE TITLE
Redirect irc.openstreetmap.org

### ISSUE THREAD

**Issue by systemed** [openstreetmap/operations#375]
OFTC have asked that we no longer run irc.openstreetmap.org as it makes it harder for them to manage abuse.

They have their own web client at https://webchat.oftc.net . This can take a channel parameter (https://webchat.oftc.net?channels=osm) and can be used as an iframe (see menu top left).

I guess the most user-friendly thing to do, while keeping OFTC happy, would be to replace irc.openstreetmap.org with either a redirect to webchat.oftc.net or to put an iframe there.

**Comment by tomhughes** [comment]
Duplicate of #374.
