### ISSUE TITLE
Mailman zh-tw options form mangled

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/operations#376]
Not sure where to post this, but after one logs in to
https://lists.openstreetmap.org/options/talk-tw
there is no submit button at the bottom of the form.
The user cannot change his options.
email to group and site owner didn't help.

**Comment by Tigerfell** [comment]
I can confirm this problem. The web interface looks different from talk@ or dev@ mailing lists, some settings are missing and the unsubscribe option is at a different place). Either this is a translation issue or someone changed the interface for this mailing list. I could not find a matching setting in the Mailman2 documentation.

**Comment by tomhughes** [comment]
Oh I can reproduce it, though only when using the chinese language interface as you say - switch to english and it is ok.

No idea what we can do about it though - we don't customise anything so this is just how mailman as shipped by Ubuntu behaves it seems.

**Comment by jidanni** [comment]
OK, I figured out a workaround:
[e.g., to turn back on mail delivery, previously turned off by me back when the page was working]
Go to some other group you are subscribed to,
then turn on mail delivery there, checking the box to apply to all
subscribed groups. Then turn it back off, but this time with the box
unchecked.

Oops... I forgot I was subscribed to many other groups... "gasp"... as my
mailbox soon said.

**Comment by jidanni** [comment]
Thanks @tomhughes.
So one needs to go to
https://lists.openstreetmap.org/options/talk-tw
not yet logged in. Then at the top choose English instead of "Taiwan".
Then one can proceed to login normally.

**Comment by pnorman** [comment]
This is an upstream mailman issue and not within operations control.
