### ISSUE TITLE
Replace Faulty Fan in Katla

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#38]
Katla has a fault light flashing. Both PSU are good. Most likely cause is a faulty fan. See munin: http://munin.osm.org/openstreetmap/katla.openstreetmap/ipmi_fans.html

**Comment by Firefishy** [comment]
Server has 3 years on-site hardware support (Next Business Day) with Rackservers. Expires ~ 06/2016.

**Comment by tomhughes** [comment]
Done by @zerebubuth.
