### ISSUE TITLE
ogr2ogr on tile servers

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#382]
OpenStreetMap Carto is [looking at a change](https://github.com/gravitystorm/openstreetmap-carto/issues/4089) that would require ogr2ogr to load data into PostgreSQL. This would not normally be a problem, except older versions of gdal are incompatible with PostgreSQL 12, and I believe this includes the version with Ubuntu 18.04.

How much operational burden would it be if we required ogr2ogr?

**Comment by tomhughes** [comment]
Well that depends, but first we will need to know what version is required, which it sounds like you are not clear about.

**Comment by tomhughes** [comment]
So 18.04 has gdal 2.2.3 while 20.04 will have 3.0.4 when it arrives.

If you need newer than 2.2.3 before 20.04 then the question becomes is there a PPA or other source for a newer version, or is an easy backport possible.

**Comment by pnorman** [comment]
2.2.3 is not recent enough, the entire 2.2.x series isn't recent enough.

3.0.4 has [the commit](https://github.com/OSGeo/gdal/commit/0ee2ee219b3b55b6568e5dc43fd817a3bbf908e9)

Backporting the latest isn't an option because it depends on a new proj. Backporting 2.4.x is probably an option, although it might need a cherry-pick to bring that change in.

Given we're almost in April, 20.04 will probably be out before we do our next release, and if not, it's not a big hold-up.

**Comment by Firefishy** [comment]
gdal 3.0.4 is available in Ubuntu 18.04 via https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable

**Comment by pnorman** [comment]
> gdal 3.0.4 is available in Ubuntu 18.04 via https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable

Do you know if it is compatible with pgdg's PostgreSQL 12 + PostGIS 3?

**Comment by pnorman** [comment]
v5.3.0 is out and this is solved
