### ISSUE TITLE
Consider removing CAPTCHA from main wiki

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#383]
In February 2020, a new wiki user suggested to replace the current CAPTCHA in the wiki, because there are tools which can solve it automatically. The discussion lead to the following questions:

1. Is there any better CAPTCHA?
2. What would happen if we remove CAPTCHA completely?

We did not find a better system for MediaWiki. This was also considered in #19 which discussed the use of CAPTCHA and its alternatives when the current system was configured. 
With regards to 2, we could not figure that out, because the number of spam trapped by CAPTCHA is not available. Given that http://wiki.openseamap.org is full of spam despite of the same CAPTCHA used here and that osm.org does not use any CAPTCHA, I propose to deactivate CAPTCHA and only re-enable it if spam increases significantly. 

Link to the wiki discussion: https://wiki.openstreetmap.org/w/index.php?title=Talk:Wiki&oldid=1972218#CAPTCHA

**Comment by matkoniecz** [comment]
Is it very complicated to toggle CAPTCHA enablement? Note that @Tigerfell is one of few OSM Wiki admins (AKA people that will be handling most of spam cleanup)

**Comment by matkoniecz** [comment]
Is it blocked by noone knowing where it is configured (and searching for that info would help) or is it blocked by something else?

**Comment by Firefishy** [comment]
See https://github.com/openstreetmap/operations/issues/454 we plan on switching away from Google's ReCaptcha.

**Comment by matkoniecz** [comment]
Is it blocked by noone knowing where it is configured (and searching for that info would help) or is it blocked by something else?

**Comment by tomhughes** [comment]
By nobody being sufficiently interested to do the work I assume given I don't see a pull request to implement it.

**Comment by Firefishy** [comment]
We have switched to hCaptcha. I have kept the instances the captcha is used to a minimum.
