### ISSUE TITLE
Turn jit off all the time for PostgreSQL 12 tile servers

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#386]
While doing osm-carto development I found PostgreSQL was getting it wrong with when to use JIT. These particular queries would be run at most once in production, but until someone has a chance to evaluate the use of JIT with osm-carto, I think it should be turned off.

**Comment by tomhughes** [comment]
I'm reluctant to do this on the basis of a hunch, but I'm also a bit confused - in https://github.com/gravitystorm/openstreetmap-carto/issues/4095 you seem to suggest that you have encountered a specific issue but you reference this ticket as the source and this ticket doesn't seem to document any specific issue?

**Comment by pnorman** [comment]
The case here was PostgreSQL using JIT for a mapnik-issued `SELECT * FROM (SELECT * FROM ... ORDER BY ...) _ LIMIT 0`

LIMIT 0 queries have inappropriate cost estimates, so PostgreSQL spent about 1000ms to execute a query that without JIT is 1-2ms.

JIT *might* get us performance gains but until I've benchmarked it, it's safer to leave it off. We know the style works without JIT from running it on previous PostgreSQL versions.

**Comment by tomhughes** [comment]
Done in https://github.com/openstreetmap/chef/commit/59e504520024e88571bc10c3147f055b2ba35640.
