### ISSUE TITLE
katie server has failing disk

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#387]
Katie has a failing disk

```
Device: /dev/sda [SAT], ATA error count increased from 261 to 262

Device info:
TOSHIBA DT01ACA300, S/N:23CEG9WGS, WWN:5-000039-ff4c61e93, FW:MX6OABB0, 3.00 TB
```

**Comment by tomhughes** [comment]
That's a hetzner machine so we can presumably get them to fix it - just need to work our who is actually paying hetzner for it!

**Comment by Firefishy** [comment]
I have contacted Freerk about the failing disk.

**Comment by Firefishy** [comment]
Disk has been replaced. I have re-configured md and reinstalled grub to the new disk.
