### ISSUE TITLE
osm.li should resolve to sosm servers

### ISSUE THREAD

**Issue by datendelphin** [openstreetmap/operations#389]
osm.li accidentally got to be a forward to osm.org but actually SOSM is hosting a link shortening service there. The dns should point again to the sosm servers.

Either enter the sosm dns servers as delegates for this domain:
falerin.sosm.ch. urlaun.sosm.ch. ns.poole.ch. he.poole.ch. ns3.spreng.ch.

Or make it resolve to 95.128.36.189

Thanks
Michael from SOSM

**Comment by Firefishy** [comment]
What about `openstreetmap.li`? Should we do the same for that?

**Comment by tomhughes** [comment]
Fixed by https://github.com/openstreetmap/dns/commit/1c2a1d4.
