### ISSUE TITLE
Re-seat ramoth cards & cables

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#39]
@Firefishy thinks there might be something loose in ramoth. Re-seat all the cards and cables to make sure there's a solid connection.

**Comment by Firefishy** [comment]
Re-seat: RAID Controller and PCI-E riser.
Optional: Confirm all RAM well seated; Blow out motherboard & connectors with compressed air.

**Comment by Firefishy** [comment]
zerebubuth reports that this has been done.

**Comment by tomhughes** [comment]
Has it improved things at all?

**Comment by Firefishy** [comment]
Yes, burn-in test ran for 66 hours without issue. I'd recommend we return some load and see how it goes.
