### ISSUE TITLE
Ideas/Problems regarding Tile CDN

### ISSUE THREAD

**Issue by danfai** [openstreetmap/operations#392]
Hi all,

first I want to apologize in advance that this might be a longer text including ideas for improvements at the tile CDN (tile and/or render infrastructure). I am looking forward to discuss some of them in more detail if necessary and also work on implementations of those ideas.

This issue looks at the current infrastructure and its improvement, although I know there are other ideas, like fastly. Additionally the focus is more on the server side and not on the applications using the tilecaches (like API keys or other changes necessary on client side).

First of all my assumption of things to be optimized to improve the overall experience:
* increasing hit rate at tilecaches
* reducing the delivery time (request time/latency for users)
* reducing load/number of requests at render server
* increase throughput at render server
* (more effectively blocking abusers)

### Disk Usage (Increase Hitrate at tilecaches, minor)

Currently there are multiple caches configured for each tilecache.
There is the cache for squid (rock...) and the nginx cache.

1. Having two caches and storing some tiles twice decreases the usable disk space.
2. Some hosts might have enough space to support a larger cache as shown in munin graphs:
https://osm.danfai.de/munin-tile/target/df-month.html

**Idea** 1: Removing squid
I am not quite sure, whether this was the long term plan anyways, but this would eliminate the problem with having two different caches. 
The servers then would be configured with a larger proxy_cache for nginx and all should be good. (if it would only be that easy, I know)

**Idea** 2: Maybe some hosts can get larger squid caches, although I think you already tuned them according to the disk size.

**Idea** 3: Some hosts have larger disk space. Use those as upstream for hosts with smaller disk space, if they are near enough (latency) and it works from a utilization perspective. (May be similar to https://github.com/openstreetmap/operations/issues/7#issuecomment-552184152 with regards to multi-tier cache)

### Too much tiles to store/Disks too small
**Idea**: combine multiple tilecaches disk space 

Obviously there are much more tiles, than a single tile server can store on its disk.
Using a predetermined location for a tile with low latency in mind can improve the overall performance.
For low latency nearby tilecaches can be combined. 
E.g. stormfly-{01,02} can store odd/even tiles to increase the overall cache size.

Ideally this information could be used in the clients/applications as well for better performance. Maybe use the typical leaflet {s} parameter aka {a,b,c}.tile.osm.org for storing tiles on those hosts. (Abstractly speaking mathematically encapsulating information about the tile number (hashing) in the DNS request)

### Render takes too long
**Idea**: split rendering based on tile coordinate

I cannot go into too much detail here, since I looked more on the caching perspective.
While the servers itself are very powerfull, none of those can cache the hole database.
In europe we have at least two servers with low latency to many of the caches.
We could prefer one of those render servers based on the tile numbers. 
E.g the french server renders everything western europe and North/South America and Amsterdam renders everything east of that border.
With the help of the recent requests, we can create a heatmap to distribute the number of requests with regards of the request locations to the different render servers. (see also paragraph "Not enough insight" below)

### Reducing processing time on tilecache (very minor)
**Idea**: simplify nginx header processing

I am not quite sure which headers should be forwarded to squid or the render servers.
In nginx there is the possibility to disable all headers and manually add your own / the necessary ones.
e.g  `proxy_pass_request_headers off;` and `proxy_set_header`
This might be more of an issue for better understanding and I did not have time to test this right now.

### Abusers use a lot of rendering capacity
**Idea**: limit number of requests

Currently in the nginx config the bandwith for abusers is limited using `set $limit_rate 1024; # or 512`
With limit_req (and limit_req_zone) we would be able to limit the number of requests.
With the right burst and delay configuration to support one or two zooms for large monitors, we can reduce typical bulk downloader in their number of requests.
The delay option can be used to delay the requests until the zone allows more.
In case the number of delay connections overflows, nginx can return error code 503/509 to indicate the problem.
As for the parameter used for the limiting, this could be either IP address based, User-agent based, or basically any other variable nginx provides.

Similarily abusers might use multiple caches to circumvent this measure, in which case a similar rule can be applied at the render servers using X-Forwarder-For IP addresses.

https://www.nginx.com/blog/rate-limiting-nginx/

### Too much requests from cache to render server
Not quite sure how much this impact is. Basically the render server can return the relevant codes if the load is to high to accept new requests.

**Idea** 1: limit requests to render server per cache
With some additional configuration nginx can be configured to only allow a certain number of requests per second to the render server. This works similarly to the above.

The behaviour could be to ask other tilecaches if they have the tiles (Currently reverted with cache_peer in squid but partly added to nginx as backup servers).

### Additional bandwidth between tilecaches
**Idea**: use redirects

This is somewhat of a long shot. For tiles that do not need to be cached by the tilecache receiving the requests, the tilecache could return the address of the tilecache that has the tile on disk.
HTTP provides this with 301 or 302 Moved temporarily/permanently. Since all tilecaches have their own DNS names, we might be able to return the hostname with the 301/302.

(possible) Disadvantage:
1. The CDN becomes more visible to the clients.
2. The client may need to do additional DNS and HTTP request increasing the load time/latency.

To determine the necessity to reduce this problem we need additional statistics for traffic between tilecaches.
Which leads us to the next:

### Not enough insight
**Idea**: extend logging of internal stats

There are many variables in nginx usable for log_format. Of course most of them are probably useless for logging.
Useful ones may include $upstream_cache_status and $upstream_addr. ( http://nginx.org/en/docs/http/ngx_http_upstream_module.html#variables or http://nginx.org/en/docs/varindex.html )

Maybe this munin plugin would do the same thing as the squid miss/hit rate, with the above variables in the log:
https://github.com/munin-monitoring/contrib/blob/master/plugins/nginx/nginx-cache-hit-rate

To get the path each tile has travelled, either log the number of caches involved in each request (based on headers, e.g. number of X-Cache... or custom header, where each tilecache adds one character (maybe unique) to the header)

For a fast analysis of the requests between tilecaches, the logs can be searched for the IP addresses of other tilecaches.
The problem will be that those values can only be aggregated by sysadmins and would not be in munin. Additionally using munin graphs adds the advantage of long term analysis for the above ideas. (E.g. historical statistics are available and therefore one can see, that January 2020 nginx has a lot more requests because of some change in git/chef)
https://osm.danfai.de/munin-tile/target/request-year.html

I am currently working on understanding the typical tile usage based on the access logs from tilecaches (https://planet.openstreetmap.org/tile_logs/). On https://osm.danfai.de/tileaccess a heatmap for requests on current zoomlevel+9. Data is aggregated by calendar week (cw14 and cw15 currently). Each pixel represents one tile, depending on the amount of requests the pixel gets more white.
This is work in progress, I want to extend it to combine all zoomlevels and hope to find some more insight for possible splitting of region for render resources. Comments are welcome :)
Sadly those tile_logs are from squid, can/should we get aggregate ones for nginx?

For a side by side view of some munin graphs, I created https://osm.danfai.de/munin-tile/target, already linked in this text.

### Loops/Traversing multiple caches
Already discussed here: https://github.com/openstreetmap/chef/issues/292

To address the issue of logging the path in our network, we can add each name of the tilecache to a custom header when requesting the upstream server.

### End
Thanks for reading to this point. Looking forward to discussions of the individual points and hopefully enhancing the current situation.
I am available for talk here, in IRC or other channels if we wish to discuss it somewhere else.

Kind regards
danfai

**Comment by tomhughes** [comment]
I'm really not sure these massive TLDR tickets are very helpful...

Here you seem to present a total of nine "issues" and at least ten "ideas" for fixing them. Even if some of them are good and actionable this ticket would be impossible to ever close because we would never get to a point when we were sure everything had been dealt with.

Tickets should as far possible cover a single issue and a single proposed change, or maybe multiple changes if they're closely related or mutually exclusive so that it's a question of choosing which one to implement.

**Comment by danfai** [comment]
You're right, I agree.
Can rework this in multiple issues tomorrow.
