### ISSUE TITLE
Tilecache: Limit request rate instead of bandwidth for abusers

### ISSUE THREAD

**Issue by danfai** [openstreetmap/operations#393]
Currently the bandwith for abusers is limited using `set $limit_rate 1024; # or 512`  in the nginx config
With limit_req (and limit_req_zone)[1] we would be able to limit the number of requests.
With the right burst and delay configuration to support one or two zooms for large monitors, we can reduce typical bulk downloader in their number of requests.                               
The delay option can be used to delay the requests until the zone allows more.
In case the number of delay connections overflows, nginx can return error code 503/509 to indicate the problem.
As for the parameter used for the limiting, this could be either IP address based, User-agent based, or basically any other variable nginx provides.

Similarily abusers might use multiple caches to circumvent this measure, in which case a similar rule can be applied at the render servers using X-Forwarder-For IP addresses.                

[1] https://www.nginx.com/blog/rate-limiting-nginx/

**Comment by danfai** [comment]
Also bandwidth limiting does not prevent the render servers from rendering the tile and thus the load increases anyway.

**Comment by tomhughes** [comment]
We have always chosen to rate limit (aka tar pit) requests rather than outright rejecting them  - the idea was to tie up bulk downloaders rather than rejecting which will just lead to an immediate request for another tile.

That said I'm not convinced that it's the best strategy so I'm open to being convinced.

**Comment by danfai** [comment]
I also prefer not rejecting them directly. For this the nginx module allows to configure bursts and queues/delay. Advantages of queues are you may not lose those requests and shift the required resources for rate limiting to the receiving side (aka request begin) instead of having it on the outgoing side. 

It also allows for rate limiting based on variables in nginx. For example you could use rates per referer, if not directly related to OSM, and thus limit the free use for other sites/apps. (regardless of how many users they have)

Also to mention bulk downloader could circumvent the current limit_rate by using parallel requests.

**Comment by pnorman** [comment]
As we are moving to a commercial CDN this issue is now moot.
