### ISSUE TITLE
Low Disk usage on tilecaches

### ISSUE THREAD

**Issue by danfai** [openstreetmap/operations#394]
Some hosts might have enough space to support a larger cache as shown in munin graphs: https://osm.danfai.de/munin-tile/target/df-month.html

Maybe some hosts can get larger squid caches, although I think you already tuned them according to the disk size.
e.g. squid at ascalon has on average 83 misses/second but over 80% disk space available (chef role has approx 125GB as cache configured or ~12 million entries over the 4 rock caches)

**Comment by tomhughes** [comment]
Disk caching is a disaster area in squid 3 and 4 so I'd really rather not increase and experience shows that the current size (for those caches using the full 128Gb configuration) is about the useful limit anyway.
