### ISSUE TITLE
Tilecache: Simplify nginx header processing

### ISSUE THREAD

**Issue by danfai** [openstreetmap/operations#396]
I am not quite sure which headers should be forwarded to squid or the render servers.
In nginx there is the possibility to disable all headers and manually add your own / the necessary ones.
e.g  `proxy_pass_request_headers off;` [1] and `proxy_set_header` 
This might be more of an issue for better understanding and I did not have time to test any perforamnce impact of this right now.

[1] http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass_request_headers

**Comment by Firefishy** [comment]
Implemented in https://github.com/openstreetmap/chef/commit/d9b30b9713a815dd1d9c962c0fb873340504296b
