### ISSUE TITLE
Rate limiting requests from tilecache to render server

### ISSUE THREAD

**Issue by danfai** [openstreetmap/operations#397]
There are multiple ways to implement rate limiting between cache and render servers.
1. tilecache nginx (or squid) use some sort of rate limiter for accesses to the backend. 
2. rate limit at the render servers

Ideally there should be some sort of fallback to either another render or cache server.
Not quite sure how much of an impact this is currently though. But might be another screw we can use to control performance.

**Comment by tomhughes** [comment]
Why would we want to deliberately degrade performance like this? The render servers already effectively rate limit when they are busy and prioritise the more important requests, something which only they can do as the caches don't know the status of the tiles on the render servers.

**Comment by danfai** [comment]
This was based on the same assumption as in the other ticket, that render servers are at limit, so maybe can be closed.

From an engineering perspective I rather have a very high limit that is most likely never reached than have none, that might destroy any backend behind it when overly used.
Of course overhead and overcomplications should also be avoided.
