### ISSUE TITLE
Combine nearby tilecaches disk space

### ISSUE THREAD

**Issue by danfai** [openstreetmap/operations#398]
Obviously there are much more tiles, than a single tile server can store on its disk.
Using a predetermined location for a tile with low latency in mind can improve the overall performance.
For low latency nearby tilecaches can be combined.
E.g. stormfly-{01,02} can store odd/even tiles to increase the overall cache size.

I know that the cache_peer for sibling caches in squid was recently taking out. But then the caches did not filter the stored tiles.

Ideally this information could be used in the clients/applications as well for better performance. Maybe use the typical leaflet {s} parameter aka {a,b,c}.tile.osm.org for storing tiles on those hosts. (Basically mathematically encapsulating information about the tile number (hashing) in the DNS request)

**Comment by tomhughes** [comment]
As soon as you start doing this you are limiting redundancy and increasing the damage done by a cache failing - obviously that can be worked around at the cost of even more complication in the fallback systems.

What I think you have to understand is the current system is already on the edge of what is manageable and adding extra complication just makes that worse - it also makes debugging failures much harder and it's already hard enough!

**Comment by pnorman** [comment]
As we are moving to a commercial CDN this issue is now moot.
