### ISSUE TITLE
Replace RAID controller in poldi

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#4]
Poldi's RAID controller battery has been removed because it had failed and was stopping the machine from booting - it needs to be replaced.

**Comment by zerebubuth** [comment]
E.g: (disk controller)[http://www.span.com/product/LSI-Logic-SAS-SATA-Controller-SAS9300-8I-Single-LSI00344-SAS-SATA-12Gbit-8-Port-Two-x4-Internal-SFF8643-PCI-Express-v3-0-x8-Non-RAID~41424] - will need extra cable converters.

**Comment by zerebubuth** [comment]
As mentioned in #20, we'll have to delay this until at least next week so that we can maintain at least one running, current Nominatim instance.

**Comment by Firefishy** [comment]
@zerebubuth any update?

**Comment by zerebubuth** [comment]
I've got all the right cables now, and I'll arrange a visit to IC once I'm
back. It'll require a complete reinstall, so I'll check when's convenient
with @lonvia.

**Comment by lonvia** [comment]
The new software raid setup has a significantly worse [IO performance](http://munin.osm.org/openstreetmap/poldi.openstreetmap/cpu.html) to the point that it cannot handle requests in a reasonable time. Machine remains offline for now.

**Comment by Firefishy** [comment]
RAID controller has been replaced. RAID performance is improving after some tuning and cache warming up.
