### ISSUE TITLE
Replace Karm and Eddie

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#407]
ref #343

Replacements for Karm and Eddie are on-order.

I need to create the remote hands ticket for AMS. The Eddie replacement is being sent to Grant while there are COVID restrictions in the UK

**Comment by Firefishy** [comment]
Oooooh Grant gets a nice new Desktop machine... Finally some real power </joke>

**Comment by pnorman** [comment]
And fans loud enough to require hearing protection ;)

I've created the ticket for the incoming shipment. We need to decide where to put it in the rack and then I'll create a remote hands ticket

**Comment by pnorman** [comment]
The new server is racked in Amsterdam.

**Comment by pnorman** [comment]
Clearing my assignment since both servers are racked and powered on, but not set up with anything other than chef.

**Comment by Firefishy** [comment]
Servers are up and running.
