### ISSUE TITLE
Tabaluga needs Storage Battery Replaced

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#408]
tabaluga's Smart Storage Battery appears to have failed and should be replaced.

HPE Part Number: P01366-B21

**Comment by Firefishy** [comment]
Notes on battery part number: https://support.hpe.com/hpesc/public/docDisplay?docLocale=en_US&docId=emr_na-a00040078en_us

**Comment by pnorman** [comment]
This is under warranty. I've emailed to ask about how we handle it under warranty.

We could also do out of warranty if it requires less remote hands work, but I'd like to see what the process is.

**Comment by Firefishy** [comment]
I am tempted to get a new battery. eg: https://www.lambda-tek.com/HP-P01366-B21~sh/B42127388
Why? Because these are batteries and they have a limited lifespan. The P01366-B21 an updated model of the original battery which was installed in the server, unsure exactly why HPE updated it, but may be due to faults with the original battery.

**Comment by Firefishy** [comment]
I've gone and ordered the a new P01366-B21

**Comment by hbogner** [comment]
> I am tempted to get a new battery. eg: https://www.lambda-tek.com/HP-P01366-B21~sh/B42127388
> Why? Because these are batteries and they have a limited lifespan. The P01366-B21 an updated model of the original battery which was installed in the server, unsure exactly why HPE updated it, but may be due to faults with the original battery.

Just curious, does HP have capacitor based "batteries" model?
I know Supermicro switched from standard batteries to capacitors for raid card BBU, at least in machines we built in recent years.

**Comment by Firefishy** [comment]
@hbogner The HP G6/G7 range HP had a capacitor based "battery" option (which was my preferred option), but it unfortunately they only have the battery based option on later models.

**Comment by Firefishy** [comment]
Battery has arrived. Date of Manufactor: 2020/01.
Delivered in an insanely oversized box.

**Comment by Firefishy** [comment]
Battery was used for server in Dublin during site visit, a replacement needs to be purchased.

**Comment by Firefishy** [comment]
Replacement batteries ordered.
Related ticket: https://github.com/openstreetmap/operations/issues/553

**Comment by Firefishy** [comment]
Battery replaced... But still complaining. We retry shortly.

**Comment by Firefishy** [comment]
Replacement battery likely a dud. Will need to get another battery.

**Comment by Firefishy** [comment]
Battery install is still pending. I didn't have enough on last visit. I have stock to take on next visit.

**Comment by Firefishy** [comment]
Replaced. Reporting good in ssacli
