### ISSUE TITLE
Intermittent OSM Wiki failures

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#409]
OSM Wiki is intermittently not responding. Unlikely to be just my connection as other users reported the same issue (me from Poland, others from Germany, Kosovo and the Netherlands).

OSM Wiki is up again, but this connection dropping appeared also earlier.

**Comment by Firefishy** [comment]
Wiki is back. Had some hardware issues earlier. https://github.com/openstreetmap/operations/issues/408
