### ISSUE TITLE
Check BIOS serial console settings on poldi

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#41]
Should be 115200 8n1 but possibly isn't as messages don't seem to appear until the kernel takes over.

**Comment by Firefishy** [comment]
http://www.tyan.com/manuals/AST2050_Manual_v100.pdf lists the default in BIOS as: "COMA, baud rate to 38.4K, 8 bits, no parity, and Xon/Xoff handshaking"

**Comment by tomhughes** [comment]
Fixed by @zerebubuth.
