### ISSUE TITLE
Wipe and/or derack old machines in Amsterdam

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#410]
We should wipe and have remote hands derack the old unused machines at Amsterdam

- [ ] orm (old render server)
- [ ] spike-01 (old frontend server)
- [ ] spike-02 (old frontend server)
- [ ] spike-03 (old frontend server)

- [x] HP DL180
- [ ] MSA60 (requires copying of existing data)

The old wiki server (ouroboros) is to be kept for now

Do we want to keep one of the old spike servers as an option for disaster recovery if multiple servers in use fail?

**Comment by tomhughes** [comment]
There's ramoth in Amsterdam as well...

**Comment by pnorman** [comment]
I'm in favour of getting rid of that too but had we made a decision on that?

**Comment by pnorman** [comment]
I made #412 for Ramoth because it's a bit more involved.

**Comment by tomhughes** [comment]
These have all been deracked now.
