### ISSUE TITLE
Dispose of Ramoth

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#412]
Ramoth needs disposal of. Normally we could remote in, wipe the drives, and have it unracked and gotten rid of as ewaste, but because it's not working we can't remote in.

 It has 19-20 15k RPM drives, 2 7200 RPM drives and 2 cache SSDs. These need disposing of correctly because they have confidential data on them. The suggest route is post them to the UK and destroy them.

We should save the RAM, 16x16GB DDR3 could upgrade other machines.

Are the supermicro PSUs worth saving?

**Comment by Firefishy** [comment]
* Post the disks.
* Post the RAM.
* Scrap the PSUs, unlikely they will be compatible with what we now have.

**Comment by hbogner** [comment]
A lot of supermicro PSUs are compatible between chassis, but guessing the age difference i wouldn't count on it being useful for new servers, only as spare parts if there is a similar old machine in use somewhere else.

**Comment by pnorman** [comment]
> * Post the RAM.

Do we want the RAM in the UK or Amsterdam?

I'll do two shipments so we don't have RAM we care about in the same box as drives we don't care about.

Thinking about the PSUs and checking what I have, 👍  on scrapping. The newest PSUs are 80+ Platinum, the old ones are worse.

**Comment by Firefishy** [comment]
Wow this is a big machine.
