### ISSUE TITLE
Request: Extend highest zoom level to 21

### ISSUE THREAD

**Issue by c933103** [openstreetmap/operations#413]
In low longitude area like Singapore or Hong Kong, the current highest zoom level of 19 rendered by OSM tile server is only sufficient to distinguish buildings, but not details within buildings or other similarly small objects, for example the location of individual shops, apartment units, door in building, or location of bus stop pole, telephone booth, trees, post box on street, as well as numerous other details. Please enable the rendering for level 20 and 21 so that these details can be shown in the map. (At zoomlevel 20 it would be somewhat possoble to distonguish their rough location in buildings while at zoomlevel 21 it would be easier to tell and would also be somewhat possible to map small shops and such in a building using area.)

Redirected from https://github.com/gravitystorm/openstreetmap-carto/issues/4145
Related discussion at https://github.com/gravitystorm/openstreetmap-carto/issues/3686 https://github.com/openstreetmap/openstreetmap-website/issues/1672 https://github.com/openstreetmap/openstreetmap-website/issues/2094
The current max zoom level of 19 have reportedly impacted quality of data https://github.com/openstreetmap/openstreetmap-website/issues/2094

**Comment by tomhughes** [comment]
I think it's very unlikely we would be able to do this with raster tiles due to the significant additional resources that would be required.

**Comment by gravitystorm** [comment]
> I think it's very unlikely we would be able to do this with raster tiles due to the significant additional resources that would be required.

I can be more specific about this - yes, it's not a good idea to do this with the generate-and-store-rasters approach used by mod_tile. 

For other systems that generate raster images on-demand (e.g. rasters rendered on-request from vector tiles), then additional zooms are practical without any additional resource requirements. This is why additional zoom levels are available on the OpenCycleMap and Transport layers, for example.

So we don't need client-side vector rendering to implement additional zooms, just server-side vector tiles.

**Comment by tomhughes** [comment]
Sorry yes I mean with a full raster stack - as you say the story is different with vector tiles regardless of whether the rendering is client side or server side.

**Comment by c933103** [comment]
Is it possible to supply simply magnified zl19 tiles as zl20?

**Comment by tomhughes** [comment]
You can do that but the effect is not good.

**Comment by tomhughes** [comment]
Also it doesn't really achieve anything - you're not suddenly going to see more detail. It's just what was a single black pixel will now be four black pixels.

**Comment by SomeoneElseOSM** [comment]
Separately to OSM's servers, if you want to create a map containing higher zoom levels have a read of the links from https://www.openstreetmap.org/user/SomeoneElse/diary/39423 - that gives you a few options, and you can even use the normal OSM Carto style if you want to.  I maintain a map server supporting up to z24 for a relatively small area, and tile disk space is concentrated around z16/z17, not anything higher (mainly because I'm not seeing many scrapers).

**Comment by c933103** [comment]
> Also it doesn't really achieve anything - you're not suddenly going to see more detail. It's just what was a single black pixel will now be four black pixels.

My understanding is that it would turn something like this:
![IMG_20200514_210436](https://user-images.githubusercontent.com/1525293/81938638-c454bc80-9627-11ea-908f-347d40456f34.jpg)
Into something like this:
![IMG_20200514_210609](https://user-images.githubusercontent.com/1525293/81938681-d46c9c00-9627-11ea-9ea9-a4b0b0ebe343.jpg)
Which would have made it easier to tell apart details that were too close together at standard zoom level.

**Comment by SomeoneElseOSM** [comment]
(offtopic in this repository, but for info)
Re "Which would have made it easier to tell apart details that were too close together at standard zoom level."

On Android with a Leaflet map such as the one that OSM uses you can touch the screen with 2 fingers and drag them apart.  The screen will magnify.  This is all client-side - no server change needed.  Also in Android more generally look at "settings / accessibility / magnification" and try setting "magnify with triple-tap".  That can quickly magnify any part of the screen.  

The best place for general help requests is probably https://help.openstreetmap.org/ and there are all sorts of answers there already.

**Comment by c933103** [comment]
> (offtopic in this repository, but for info)
> Re "Which would have made it easier to tell apart details that were too close together at standard zoom level."
> 
> On Android with a Leaflet map such as the one that OSM uses you can touch the screen with 2 fingers and drag them apart.  The screen will magnify.  This is all client-side - no server change needed.  Also in Android more generally look at "settings / accessibility / magnification" and try setting "magnify with triple-tap".  That can quickly magnify any part of the screen.  
> 
> The best place for general help requests is probably https://help.openstreetmap.org/ and there are all sorts of answers there already.

Yes it can be done on Android apps but that cannot be done on e.g. OSM official site when people browsing it on a desktop computer. My screenshot was Android merely because I was too lazy to screenshot it on a PC.

**Comment by grischard** [comment]
On the gripping hand, the OpenStreetMap Foundation owns openstreetmap.sg, and would be happy to make the domain available for the local community, for example by pointing it at a map service run by the local community that does z22. If you set up something, get in touch with me.

**Comment by c933103** [comment]
I used a Singapore address as an example in this issue but I am not personally related to Singapore.
What about Hong Kong?

**Comment by jidanni** [comment]
> In low longitude area like Singapore or Hong Kong, the current highest zoom level of 19 rendered by OSM tile server is only sufficient to distinguish buildings, but not details within buildings or other similarly small objects, for example the location of individual shops, apartment units, door in building, or location of bus stop pole, telephone booth, trees, post box on street, as well as numerous other details.

I added this to
https://en.wikipedia.org/wiki/Talk:North%E2%80%93South_divide_in_the_World#Northern_mappers_don%27t_feel_southern_mappers_pains !

**Comment by c933103** [comment]
But Hong Kong or Singapore are usually considered Global North in the
context of North-South Divide.

在 2021年3月26日週五 00:53，積丹尼 Dan Jacobson ***@***.***> 寫道：
