### ISSUE TITLE
Rhaegal upgrade plan

### ISSUE THREAD

**Issue by hbogner** [openstreetmap/operations#417]
I will need to take it offline for a day or two.
Need to get it from Zagreb, upgrade motherboard & CPU(switch X5675 with E5-2695v2), stress it to see everything works without problems, and return it to Zagreb after all that.
Are there any objections for this?
When would it be good time to take it offline?

**Comment by tomhughes** [comment]
Whenever you like - we have plenty of capacity.

**Comment by hbogner** [comment]
Rhaegal is back online.
