### ISSUE TITLE
Please create a dev instance for microcosms

### ISSUE THREAD

**Issue by openbrian** [openstreetmap/operations#419]
People are asking me to see microcosms, which is obviously not ready.  But I'd like to get feedback from club organizers, individual members, and event organizers.

Can you stand up an instance of OSM using this PR or this fork/branch?

* PR: https://github.com/openstreetmap/openstreetmap-website/pull/2390
* fork/branch: https://github.com/openbrian/osm-microcosms - microcosms is the default branch

I continue to write minitests to complete coverage of new code: https://coveralls.io/builds/31034893

Users can file bugs, feedback, and feature requests on microcosms here: https://github.com/openbrian/osm-microcosms/issues

**Comment by openbrian** [comment]
Also set microcosms_dev_instance: true in settings.local.yml for this instance.

**Comment by tomhughes** [comment]
Site added in https://github.com/openstreetmap/chef/commit/217fa53bba8c1b5977220dde7457ee2938b3fc4a but I don't have any way so set custom options currently so I will have to look at that later.

It sounds very odd anyway - what does that option do? Users of the dev site should be seeing what it will look like in production, not some special dev mode... Not that we usually have special modes in our code...

**Comment by openbrian** [comment]
I use it as a feature flag.  It adds a link in the header for feedback to be sent to my repo.  You don't want all these bugs do you?  But if we forget to take out the link, I would not want this to appear on prod.

**Comment by tomhughes** [comment]
Well I wouldn't expect anybody to be looking at that dev site without being aware of what this about and how to report issues... If you really want it then the easiest solution is to default it to on for now.

**Comment by openbrian** [comment]
OK.  Honestly... It's a glaring eye sore.  We won't forget to take it out.

**Comment by openbrian** [comment]
I found the website here.  It's up and running.  Dumb question.  How do I sign in?

**Comment by tomhughes** [comment]
Create an account as you would on the main site.

**Comment by tomhughes** [comment]
I mean does https://microsms.apis.dev.openstreetmap.org/user/new not work for you?

**Comment by openbrian** [comment]
Of course it does.  I'm an idiot.

**Comment by openbrian** [comment]
One issue.  For me on Firefox on Android and for Clifford Snow on Firefox on Linux, we're getting a bad certificate issue.  For me Firefox on Linux, it's working.  I see it's signed by Let's Encrypt.

**Comment by openbrian** [comment]
microcosms.apis.dev.openstreetmap.org uses an invalid security certificate. The certificate is only valid for the following names: ant.dev.openstreetmap.org, ant.dev.osm.org Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by openbrian** [comment]
Firefox 68.8 can not get past this.

**Comment by tomhughes** [comment]
No, it doesn't. Really. I know this because my browser would refuse to load it if it did.

If you are using a client that is so prehistoric it doesn't do SNI then maybe that is the default certificate.

**Comment by tomhughes** [comment]
OK so it was working but now it isn't?

**Comment by openbrian** [comment]
Desktop FF 65 works, Mobile FF 68 doesn't.

**Comment by openbrian** [comment]
Chromium 81 desktop, works.

**Comment by tomhughes** [comment]
For crying out loud. I've admitted there's a problem and if you can leave me alone for five minutes I might have some change of solving it.

**Comment by openbrian** [comment]
Sorry, was just answering your question.

**Comment by tomhughes** [comment]
Damn. It's the stupid fecking name of the thing. I typoed it as microsms (which almost means something) and that name, which is the one I was using initially, does work.

I'll fix it but it will take a while.

**Comment by openbrian** [comment]
Working well in Chrome.  Not so much in my ESR v68.  Whatever.
