### ISSUE TITLE
Replace SATA cables in poldi

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#42]
Poldi's new HBA is unreliable; disks keep dropping from the md arrays and performance is much, much slower than we'd expect. The current leading theory is that either the cables are too long (they are at max. allowed 1m for SATA cables), are faulty or are not seated well. Rather than fiddle with it several times, just go and replace with 0.5m cables and make sure they're firmly seated.

**Comment by zerebubuth** [comment]
Replaced one of the cables with a 0.5m cable. Unfortunately, 0.5m wasn't long enough for the other cable, so that was just re-seated.

It was looking good until just now, when `/dev/sdd1` was thrown. This disk is on the longer cables, so potentially supports the theory that the cables are too long, although the same 1m cables are used in yevaud and (iirc) we don't have issues there. The disks on the longer cables are; the two 2TB WDC WD2003FYYS (sda & sdd) and the two 256GB C300-CTFDDAC256M (sdb & sdc).

Let's see what happens, but it seems possible that we'll have to visit again... this time with a 0.6m cable.

**Comment by zerebubuth** [comment]
Replaced the other cable with a 0.6m cable and sprayed liberally to remove dust. It's been under load for a few hours now, and so far without throwing any disks. I'm fairly happy that we can call this fixed... What do you think, @lonvia & @Firefishy?

**Comment by zerebubuth** [comment]
Oh well... still some problems. :cry:

```
[103397.313795] sd 0:0:2:0: attempting task abort! scmd(ffff880036b16880)
[103397.313801] sd 0:0:2:0: [sdc] CDB: 
[103397.313804] Inquiry: 12 00 00 00 24 00
[103397.313813] scsi target0:0:2: handle(0x000a), sas_address(0x4433221101000000), phy(1)
[103397.313816] scsi target0:0:2: enclosure_logical_id(0x500605b006f957d0), slot(2)
[103397.346023] sd 0:0:2:0: task abort: SUCCESS scmd(ffff880036b16880)
[103397.346097] program smartctl is using a deprecated SCSI ioctl, please convert it to SG_IO
[103397.654005] end_request: I/O error, dev sdc, sector 2064
[103397.659457] md: super_written gets error=-5, uptodate=0
[103397.659460] md/raid1:md129: Disk failure on sdc1, disabling device.
[103397.659460] md/raid1:md129: Operation continuing on 1 devices.
```

**Comment by gravitystorm** [comment]
While this continues to be a (known) problem, is there any way to suppress the degradedarray emails, e.g. via a chef attribute?

**Comment by tomhughes** [comment]
Well of course there's a way, the question is how much work we want to do to work around a temporary problem.

Frankly, in the totality of the admin emails it's a small bit of noise.

**Comment by gravitystorm** [comment]
> Frankly, in the totality of the admin emails it's a small bit of noise.

If we're getting so many email notifications that 4 a day, every day, fromjust this machine counts as "a small bit of noise", then that highlights the number of emails we're getting is completely ridiculous! I figure we should be sorting out the deluge one step at a time.

**Comment by tomhughes** [comment]
Sure, but there's so many that are next to impossible to fix that I've pretty much given up.

The big problem is that many of the RAID monitoring tools are buggy but upstream is essentially dead so there's no point me developing patches as there is nowhere to send them.

So, for example, every time ramorth does a RAID check (once a week) we get a bazillion bogus emails that the RAID is broken.

**Comment by zerebubuth** [comment]
Closing in favour of #79.
