### ISSUE TITLE
stormfly-03/04 switch network card

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#421]
stormfly-03/04 servers are using the slower `HP Ethernet 1Gb 4-port 331i Adapter` and should be switched to using the faster `HP 561FLR-T 2-port 10Gb Ethernet Adapter`

eno1/2/3/4 -> eno49/50

**Comment by Firefishy** [comment]
With OSUOSL remote hands, it is likely best if we bond all the interfaces first and get remote hands to switch at their leisure.

**Comment by tomhughes** [comment]
Interfaces are now bonded.

**Comment by Firefishy** [comment]
Network card was switched on the 17th June 2020.

Spot the change:
![Screenshot 2020-06-30 at 21 56 48](https://user-images.githubusercontent.com/248188/86176303-a3cfbb80-bb1c-11ea-8471-3fea2c844fd4.png)
