### ISSUE TITLE
Create tile logs from nginx logs

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#422]
https://planet.openstreetmap.org/tile_logs/ are created from squid's logs. Because nginx is now running as a level 1 cache in front of squid, the numbers are not accurate for frequently accessed tiles.

These files should be generated from nginx hits instead.

**Comment by AnastasiyaZhd** [comment]
Hello, we've used the tile logs to create the OpenStreetMap Antiquity map view on [disaster.ninja](https://disaster.ninja/live/) and just noticed that logs now stopped refreshing. Could you check it?

**Comment by Firefishy** [comment]
@AnastasiyaZhd The log issue has been fixed. The missing gap is being generated now.

**Comment by pnorman** [comment]
As we are moving to a commercial CDN this issue is now moot.
