### ISSUE TITLE
Update CAA record configuration

### ISSUE THREAD

**Issue by markwoodbury** [openstreetmap/operations#423]
It would appear from https://github.com/openstreetmap/dns/blob/master/src/openstreetmap.js (and similar in the same directory) that the intention is to "Publish CAA records indicating that only letsencrypt should issue certificates", however it would appear that this isn't actually happening in practice.

<pre>$ dig +short @8.8.8.8 openstreetmap.org CAA
0 iodef &quot;mailto:hostmaster@openstreetmap.org&quot;
0 issue &quot;comodoca.com&quot;
0 issue &quot;digicert.com&quot;
0 issue &quot;letsencrypt.org&quot;
0 issuewild &quot;comodoca.com&quot;
0 issuewild &quot;digicert.com&quot;
0 issuewild &quot;letsencrypt.org&quot;</pre>

Similar can be found in [SSL Labs checks](https://www.ssllabs.com/ssltest/analyze.html?d=www.openstreetmap.org&s=130.117.76.13&latest).

I suspect this is due to Cloudflare adding their helpful CAA records for their Universal SSL functionality (see [their documentation](https://support.cloudflare.com/hc/en-us/articles/115000310832-Certification-Authority-Authorization-CAA-FAQ#h_645975761191543365946939)) which results in the additional records being added.

Other than [this](https://crt.sh/?id=2430513711) (and similar results for other domains), it would appear that [in practice](https://crt.sh/?q=openstreetmap.org), only Let's Encrypt is actually issuing certs, but still seems counter to what you desire.

If indeed validated, it would appear that disabling the Universal SSL functionality within Cloudflare would resolve this.

**Comment by tomhughes** [comment]
Yes I know cloudflare add extra things - the line in our source is simply meant to mean that we only issue from LE.

If we ever use cloudlfare to frontend anything then we need to allow them to issue as well.
