### ISSUE TITLE
Consider dropping split frontend/backend configuration for web site

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#424]
I think we should consider dropping the split between frontend and backend web servers and just run everything on the frontends - the original reasoning for the split was to provide higher capacity servers (in particular memory) for the backend which was very memory intensive with API calls in rails.

Not only are we not using rails for those calls now, but our servers also have far more memory these days - in fact the frontends in Amsterdam are now considerably more powerful that the backends.

The current specifications in the primary data centre in Amsterdam are:

* three frontends each a G9 with 16 cores and 64Gb of memory
* three backends each a G7 with 12 cores and 32Gb of memory

CPU usage looks to be something like:

* frontends average around 2 threads in use peaking at 4-5 threads
* backends barely use 1 thread at peak

Memory usage looks to be something like:

* frontends have around 4-8Gb of application memory usage
* backends have around 8Gb of application memory usage

So we could easily merge the backends into the frontends and still have loads of spare CPU and memory resource while also making the configuration simpler and allowing us to turn off three older machines.

It would also make the idea of adding a web cluster at UCL easier as we would jsut require 2-3 combined machines rather than say 2 of each.

**Comment by pnorman** [comment]
I like this because it simplifies our configuration, purchasing, and set-up of alternate sites.

**Comment by grischard** [comment]
I also like it because it lets us more easily have hot spares for automatic failovers.

**Comment by tomhughes** [comment]
So it sounds like everybody thinks this is a good idea then...

**Comment by mmd-osm** [comment]
Chairperson is also aware that shutting down 3-5 machines mostly used for API purposes won't sacrifice the "stability, reliability, and robustness of the technology platform"?

**Comment by tomhughes** [comment]
Sorry, what?

**Comment by Firefishy** [comment]
@mmd-osm Because these requests pass through the frontends to get to the backends, it is likely we'd actually see an improvement to stability and reliability. The frontend servers have sufficient CPU / RAM to easily handle the extra work.

**Comment by mmd-osm** [comment]
Sorry for not providing any context, I was referring to this post here: https://lists.openstreetmap.org/pipermail/osmf-talk/2020-August/007043.html and was wondering, if shutting down some machines couldn't be falsely interpreted as sacrificing robustness, in particular when looking at it from a more management like point of view.

Just wanted to be sure that those changes won't get challenged in the light of the overarching reliability topic.

**Comment by tomhughes** [comment]
There would no change in reliability - the backends are useless without the frontends and there are three of each in the production cluster.

Currently requests hit one of the three frontends and, for some requests, that frontend proxies it to one of the three backends, so there is three way redundancy at bother layers.

In the new architecture the frontends will simply do all requests themselves and the backends will be redundant, so there will still be three way redundancy, plus less complication.

**Comment by tomhughes** [comment]
This has now been implemented.

**Comment by mmd-osm** [comment]
Test Kitchen still runs some of those web-backend tests: https://github.com/openstreetmap/chef/search?q=web-backend

I guess that's not all that relevant anymore and could be dropped?
