### ISSUE TITLE
Upgrade servers to Ubuntu 20.04

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#427]
This is a tracking bug for upgrading servers to Ubuntu 20.04 over the next few months:

* [x] albi.openstreetmap.org
* [x] angor.openstreetmap.org
* [x] ascalon.openstreetmap.org
* [x] balerion.openstreetmap.org
* [x] boitata.openstreetmap.org
* [x] bowser.openstreetmap.org
* [x] cherufe.openstreetmap.org
* [x] chrysophylax.openstreetmap.org
* [x] clifford.openstreetmap.org
* [x] cmok.openstreetmap.org
* [x] culebre.openstreetmap.org
* [x] draco.openstreetmap.org
* [x] drogon.openstreetmap.org
* [x] dulcy.openstreetmap.org
* [x] eddie.openstreetmap.org
* [x] errol.openstreetmap.org
* [x] eustace.openstreetmap.org
* [x] fafnir.openstreetmap.org
* [x] falkor.openstreetmap.org
* [x] fuchur.openstreetmap.org
* [x] fume.openstreetmap.org
* [x] gackelchen.openstreetmap.org
* [x] glaedr.openstreetmap.org
* [x] gorwen.openstreetmap.org
* [x] gorynych.openstreetmap.org
* [x] grindtooth.openstreetmap.org
* [x] grisu.openstreetmap.org
* [x] idris.openstreetmap.org
* [x] ironbelly.openstreetmap.org
* [x] jakelong.openstreetmap.org
* [x] kalessin.openstreetmap.org
* [x] karm.openstreetmap.org
* [x] katie.openstreetmap.org
* [x] katla.openstreetmap.org
* [x] keizer.openstreetmap.org
* [x] kessie.openstreetmap.org
* [x] kokosnuss.openstreetmap.org
* [x] konqi.openstreetmap.org
* [x] ladon.openstreetmap.org
* [x] longma.openstreetmap.org
* [x] meraxes.openstreetmap.org
* [x] naga.openstreetmap.org
* [x] neak.openstreetmap.org
* [x] necrosan.openstreetmap.org
* [x] nepomuk.openstreetmap.org
* [x] nidhogg.openstreetmap.org
* [x] noomoahk.openstreetmap.org
* [x] noquiklos.openstreetmap.org
* [x] norbert.openstreetmap.org
* [x] odin.openstreetmap.org
* [x] pummelzacken.openstreetmap.org
* [x] pyrene.openstreetmap.org
* [x] rhaegal.openstreetmap.org
* [x] ridgeback.openstreetmap.org
* [x] ridley.openstreetmap.org
* [x] rimfaxe.openstreetmap.org
* [ ] saphira.openstreetmap.org
* [x] sarel.openstreetmap.org
* [x] sarkany.openstreetmap.org
* [x] scorch.openstreetmap.org
* [x] shenron.openstreetmap.org
* [x] shruikan.openstreetmap.org
* [x] snap-01.openstreetmap.org
* [x] snap-02.openstreetmap.org
* [x] spike-04.openstreetmap.org
* [x] spike-05.openstreetmap.org
* [x] spike-06.openstreetmap.org
* [x] spike-07.openstreetmap.org
* [x] spike-08.openstreetmap.org
* [x] stormfly-03.openstreetmap.org
* [x] stormfly-04.openstreetmap.org
* [x] tabaluga.openstreetmap.org
* [x] takhisis.openstreetmap.org
* [x] thorn-01.openstreetmap.org
* [x] thorn-02.openstreetmap.org
* [x] thorn-03.openstreetmap.org
* [x] thorn-04.openstreetmap.org
* [x] thorn-05.openstreetmap.org
* [x] tiamat-00.openstreetmap.org
* [ ] tiamat-01.openstreetmap.org
* [ ] tiamat-02.openstreetmap.org
* [ ] tiamat-03.openstreetmap.org
* [x] tiamat-11.openstreetmap.org
* [ ] tiamat-12.openstreetmap.org
* [ ] tiamat-13.openstreetmap.org
* [x] tiamat-21.openstreetmap.org
* [ ] tiamat-22.openstreetmap.org
* [ ] tiamat-23.openstreetmap.org
* [x] toothless.openstreetmap.org
* [x] trogdor.openstreetmap.org
* [x] tuatara.openstreetmap.org
* [x] urmel.openstreetmap.org
* [x] vipertooth.openstreetmap.org
* [x] viserion.openstreetmap.org
* [x] waima.openstreetmap.org
* [x] ysera.openstreetmap.org

Chef tests are already passing for the vast majority of cookbooks with just a few issues left to resolve.

**Comment by Firefishy** [comment]
shenron.openstreetmap.org upgrade has been delayed by issues with `trac` and `osqa`. @tomhughes may be able to provide more details.

**Comment by tomhughes** [comment]
The issue with trac is simply that the trac package has been dropped from the Ubuntu 20.04 repositories.

The issue with osqa is just that I need to figure out to get the virtualenv that it uses using python 2 now that python 3 is the default.
