### ISSUE TITLE
 Nominatim DNS misconfigured?

### ISSUE THREAD

**Issue by toebu** [openstreetmap/operations#428]
I'm having trouble resolving nominatim.openstreetmap.org on one of my servers.

    > nslookup nominatim.openstreetmap.org
    Server:         127.0.0.53
    Address:        127.0.0.53#53
    
    ** server can't find nominatim.openstreetmap.org: SERVFAIL

Resolving with another DNS server works:

    > nslookup nominatim.openstreetmap.org 1.1.1.1
    Server:         1.1.1.1
    Address:        1.1.1.1#53
    
    Non-authoritative answer:
    nominatim.openstreetmap.org     canonical name = nominatim.geo.openstreetmap.org.
    nominatim.geo.openstreetmap.org canonical name = amsterdam.nominatim.openstreetmap.org.
    Name:   amsterdam.nominatim.openstreetmap.org
    Address: 130.117.76.9

I already contacted support of the DNS server that my server uses by default and they replied, saying the following:

Our investigation shows that it may depend how their domain is being queried: if geo.openstreetmap.org is resolved first the misconfigured records [1] are being cached and will make any other related queries to fail.

It works if nominatim.geo.openstreetmap.org is resolved first and the (almost) correct records being cached for further queries. [2]

[1] https://mxtoolbox.com/SuperTool.aspx?action=dns%3ageo.openstreetmap.org&run=toolpage
[2] https://mxtoolbox.com/SuperTool.aspx?action=dns%3anominatim.geo.openstreetmap.org&run=toolpage

----

As one can see on the mxtoolbox site, it reports quite a few warnings for the DNS config of these domains and especially one error for geo.openstreetmap.org.

I'm not sure if I should have rather created an issue on GitHub or if this is the place to report potential bugs...

*(I'm posting this here as suggested by someone on https://help.openstreetmap.org/questions/75378/nominatim-dns-misconfigured)*

**Comment by Firefishy** [comment]
Possible fix pushed a few hours ago: https://github.com/openstreetmap/chef/commit/ee35b7b

**Comment by toebu** [comment]
Awesome, do you know when this will be deployed? I could then test if everything works as expected.

**Comment by tomhughes** [comment]
It was deployed as soon as it was pushed.

One of your URLs is still complaining though which is why I didn't say anything here but @Firefishy jumped in ;-)

I think it's just a check that doesn't make sense but I'll investigate when I have time.

**Comment by Firefishy** [comment]
@toebu Would you mind running your local tests again?

**Comment by toebu** [comment]
It works correctly now, yes! Awesome, thanks a lot for the fast response!
I'm also checking with the hoster so that they can confirm that it won't cache any queries with errors in them. I'll reopen in case they find anything else.
