### ISSUE TITLE
Tiles not updating

### ISSUE THREAD

**Issue by Recoil016** [openstreetmap/operations#430]
Looks like the render servers have been building up a massive data import lag since Friday evening (example: https://munin.openstreetmap.org/openstreetmap.org/odin.openstreetmap.org/replication_delay.html), leading to tiles not being rendered with up-to-date data. Is this problem known?

**Comment by tomhughes** [comment]
Yes and it's being worked on.

**Comment by Firefishy** [comment]
Some more details if interested: https://twitter.com/OSM_Tech/status/1277001284705570821

**Comment by Firefishy** [comment]
libosmium v2.15.6 workaround release with fix: https://github.com/osmcode/libosmium/blob/master/CHANGELOG.md#fixed-1
osm2pgsql update is pending, expected to be v1.2.2

**Comment by tomhughes** [comment]
This had already been fixed with a workaround but the new osm2pgsql is now deployed in any case.
