### ISSUE TITLE
Ensure .git folders are not accessiable via web server

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#434]
A few of our site are checked out from git and and the `.git` folder is publicly accessiable.

While all sites git repos code is likely public and the exposed `.git` folder would not be private data, it would be best practice to lock down access:

1. To reduce chance of accidentially exposing data which is checked into git working copies.
2. To stop false positive alerts from security scanning which find the `.git` folder exposed.

**Comment by pnorman** [comment]
This one needs testing to define which sites need work.

**Comment by Firefishy** [comment]
Thank you to Yevheniia from WebSafety Ninja for pointing out that https://dmca.openstreetmap.org/.git/config was accessible. The checkout is from the public repo: https://github.com/openstreetmap/dmca-website

**Comment by Firefishy** [comment]
All looks good to me.
