### ISSUE TITLE
Kalessin idle?

### ISSUE THREAD

**Issue by nrenner** [openstreetmap/operations#437]
There are increased issues with some tile caches for Germany lately - I suppose you already removed Konqi - and I might open a separate issue for that. Just a quick shot for now: 

I noticed that Kalessin seems to be largely idle since about three weeks, although it has been doing fine before?

![kalessin - nginx_request](https://user-images.githubusercontent.com/1092030/87006480-0b42d680-c1c1-11ea-914d-7ddd0a007080.png)
https://munin.openstreetmap.org/openstreetmap.org/kalessin.openstreetmap.org/nginx_request.html

![kalessin - load](https://user-images.githubusercontent.com/1092030/87006515-16960200-c1c1-11ea-9efd-548bbf388f6f.png)
https://munin.openstreetmap.org/openstreetmap.org/kalessin.openstreetmap.org/load.html

**Comment by tomhughes** [comment]
It's paused at the moment but I'm not sure why. I don't think I did it... Maybe @Firefishy knows?

**Comment by Firefishy** [comment]
My mistake, kalessin was running very slowly and I pulled it from the cluster to do some testing / tweaking, but I forgot to re-add the machine to the cluster.

**Comment by nrenner** [comment]
Thanks!

I already mentioned Konqi, but just to be sure, because that was only my assumption:

Konqi was disabled on sunday on purpose?

![grafik](https://user-images.githubusercontent.com/1092030/87071554-ac11b000-c21a-11ea-8d2c-d3e4c2931bea.png)
https://munin.openstreetmap.org/openstreetmap.org/konqi.openstreetmap.org/tcp.html

**Comment by tomhughes** [comment]
No, it failed to come back after a reboot and my mail to the provider has not yet been answered.

**Comment by nrenner** [comment]
Ok, thanks.
