### ISSUE TITLE
OSM Forum (FluxBB) update

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#439]
https://forum.openstreetmap.org runs a [custom version of FluxBB v1.5.10](https://github.com/openstreetmap/openstreetmap-forum/commits/openstreetmap-1.5.10). 

The [archlinux forum](https://bbs.archlinux.org/) also runs a [custom version of FluxBB](https://github.com/archlinux/archbbs) with a responsive style and synced upto latest v1.5.11 release of FluxBB.

Task is to sync code upto v1.5.11 (or latest) and pull in some of the improvements from the archlinux code. Minimal set of changes as want to be able to track future fluxbb upgrades.

**Comment by tomhughes** [comment]
I can probably resync.

I'm reluctant to start pulling in other changes though.

**Comment by grischard** [comment]
Won't fix in favour of #604.
