### ISSUE TITLE
Replace failing OS disk in Yevaud

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#44]
Yevaud has an OS failing disk. It should be replaced. RAID 1 member behind areca.

Disk is under WDC warranty.

Model Family:     Western Digital RE4 (SATA 6Gb/s)
Device Model:     WDC WD2000FYYZ-01UL1B0
Serial Number:    WD-WCC1P0014324
LU WWN Device Id: 5 0014ee 25cb74971
Firmware Version: 01.01K01
User Capacity:    2,000,398,934,016 bytes [2.00 TB]

**Comment by zerebubuth** [comment]
Disk replaced, rebuilding now (46%).

**Comment by Firefishy** [comment]
Awesome thank you.
