### ISSUE TITLE
Konqi down

### ISSUE THREAD

**Issue by nrenner** [openstreetmap/operations#441]
from #437:
> No, it failed to come back after a reboot and my mail to the provider has not yet been answered.

Has the provider already responded?

**Comment by tomhughes** [comment]
Why do you care? That's something for us to worry about - we have many caches and one or two of them are usually down at any given time.

**Comment by nrenner** [comment]
Because there are reports of slow loading or gray tiles again since Kalessin was and Konqi is not available.

**Comment by tomhughes** [comment]
So report the problem then, not what you think the cause is.

Konqi is a fairly low powered machine so won't make much difference.

I have a new cache for Germany that I need to bring on line, which is on my to do list this evening with a bit of luck.

**Comment by gravitystorm** [comment]
> Why do you care? That's something for us to worry about

I know you're busy @tomhughes but it's really discouraging to see responses like this. I think it turns away people who might become interested in learning what's going on and getting involved.

**Comment by tomhughes** [comment]
Well I had politely explained the situation previously and I was just confused why I should be expected to provide a running commentary on our communications with our cache suppliers.

I mean we do our best to keep the caches online but where we don't have console access all we can do is reach out to our contact and hope they reply - often they do, sometimes they don't and we eventually treat the cache and dead and drop it altogether.

I agree I was a bit short but I'm not clear what @nrenner would have done if I'd just repeated myself and said "not yet". It's not clear there was anywhere helpful for this ticket to go for either party.

**Comment by nrenner** [comment]
Sorry about that.

Two out of five of the usual cache servers for Germany offline seemed like an obvious cause.

With Kalessin back things improved, but from what I could observe, Gackelchen and Katie were still having issues. I saw Stormfly-03/4 stepping in, but not so much this week and their response times were not the fastest either.

The background was if the German community could help with communicating with the suppliers or finding new sponsors and how pressing that would be.

But now that there is already a new server Kilgharrah at work, the immediate issues should be solved for now.

Thanks a lot for all your work.
