### ISSUE TITLE
openstreetmap.org is sometimes failing with "queue full"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#444]
This website is under heavy load (queue full)

We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.

**Comment by tomhughes** [comment]
Working fine for me.

**Comment by Firefishy** [comment]
The errors do seem to appear in munin: https://munin.openstreetmap.org/openstreetmap.org/www.openstreetmap.org/api_calls_error.html
503 Service Unavailable.
