### ISSUE TITLE
Switch away from ProxyFCGISetEnv for PHP fastcgi and enable full disable_functions

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#445]
Using ProxyFCGISet appears to have the problem that ENV is reused regardless of source.
 
Full set of disabled_functions should be re-enabled and likely reviewed for newer versions of PHP.

**Comment by tomhughes** [comment]
It may make more sense to use systemd to sandbox the fpm process, especially if there's a separate pool per site.

**Comment by Firefishy** [comment]
Sounds good!

**Comment by tomhughes** [comment]
The switch has now been done and each app is using a separate FPM pool that can have it's own configuration.

Currently each app is using whatever configuration it was using before.

**Comment by Firefishy** [comment]
Sounds great. Thanks @tomhughes
