### ISSUE TITLE
Proposal: Switch from ops custom secret text store to pass https://www.passwordstore.org/

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#446]
Proposal...

A few of the ops team have access to a custom developed secret text storage using gpg with custom wrapper scripts.

It would be good to migrate this over to [pass](https://www.passwordstore.org/) backed by a private repo on github (and mirrored to git.openstreetmap.org)

Pass has a large community behind it.
I am moving my own passwords across to it and it would be good to have an OSM repo I could add on.

I propose additionally we consider adding an additional pass repo for ops related stuff we may share with others eg: treasurer.

**Comment by tomhughes** [comment]
Whilst I agree we could do with something better than what we have I'm not sure this is the solution.

It really only wants to store simple passwords - you can store larger chunks of text but it all looks pretty hacky.

I suspect we also want to be thinking about something that allows different groups of people to have access to different subsets of the data.

**Comment by mikini** [comment]
> I suspect we also want to be thinking about something that allows different groups of people to have access to different subsets of the data.

Take a look at the --path (-p) option to the [init command](https://git.zx2c4.com/password-store/about/#COMMANDS), it can be used to specify a set of keys to encrypt the passwords of a specific subfolder for. The key-set is [stored in a file named .gpg-id inside the folder for which it applies](https://git.zx2c4.com/password-store/about/#FILES) and is thus revisioned and distributed together with the encrypted passwords if using git.

One caveat of this, however, is that you can't really revoke anyone's (and their key's) access to the password if they also have access to the git history; they'll always have access to the password they were once authorised to use. So to be able to revoke someone's access to the service you wish to protect, the credentials for authentication to that service have to be refreshed when revoking access.

If you need to partition and separate even further, you can have multiple separate stores which can be combined for a specific  use case using multipe techniques; symlinks, direnv, git submodules (see [recent ml discussion regarding](https://lists.zx2c4.com/pipermail/password-store/2020-June/004183.html)).

At first look pass and the way its built seems simple and a bit of a kludge, and it kind of is being a shell script and just glue between a bunch of files, gpg and git. But the concept is easy to comprehend and use, and pass itself is particularly well-written and maintained (by Jason of [wireguard](https://www.wireguard.com) fame, btw.).

**Comment by pnorman** [comment]
I use pass and find it works well for my personal use, but I haven't needed to store multiline stuff.

**Comment by Firefishy** [comment]
We have migrated to [gopass](https://www.gopass.pw/). Working well.
