### ISSUE TITLE
Corrupted tile PNG format

### ISSUE THREAD

**Issue by petoc** [openstreetmap/operations#450]
Recently I run into few corrupted tiles. Status page shows that tile is clean, but when I checked its contents, it is missing PNG signature and has some strange data.

Tiles:
https://tile.openstreetmap.org/12/2279/1401.png (https://www.openstreetmap.org/#map=12/49.3017/20.3557)
https://tile.openstreetmap.org/12/2284/1412.png (https://www.openstreetmap.org/#map=12/48.6654/20.7821)

Cache Server: sarkany.openstreetmap.org
Render Server: rhaegal.openstreetmap.org

**Comment by tomhughes** [comment]
I can't easily check the cached versions, but the versions from rhaegal seem fine so I suggest just doing a shift-reload to get fresh copies from upstream.

**Comment by petoc** [comment]
Checked most of cache servers (if responded) and tile servers from https://hardware.openstreetmap.org, but only cache server `sarkany` gives me invalid PNG files for both tiles mentioned above. Tried different browsers, curl, always same result.

**Comment by Firefishy** [comment]
Those tiles the first bit is missing... weird stuff, no idea how it happened

I've started a purge of the tiles on `sarkany`, it may take awhile before it hits that bad tile.

**Comment by petoc** [comment]
Today I encountered similar problem.
Now tile is only partially corrupted. Browser can render part of it, as you can see below, but for example QGIS or some image viewers, reject whole image.
Again, from all tile caches I could reach, only ```sarkany``` has corrupted this particular tile.
What is interesting is, that headers say ```sarkany``` cached from ```rhaegal```, where tile is fine.

**rhaegal tile**
https://rhaegal.openstreetmap.org/15/18231/11246.png

![rhaegal](https://user-images.githubusercontent.com/63091190/99041143-ab9f7200-258a-11eb-84df-bfa48b2cbd47.png)

```
...
00003fb0  8e 3d f7 b7 21 44 2f 98  00 80 c6 ca ca 52 41 65  |.=..!D/......RAe|
00003fc0  b1 c1 0d 6e 13 e0 cc cf  b2 f6 6f 0e 75 00 bb 21  |...n......o.u..!|
00003fd0  b8 e5 0d 2c b4 6f 6e 83  54 00 51 65 3d 5b c8 d9  |...,.on.T.Qe=[..|
00003fe0  2d af 9f 3f 79 fa f4 b1  bb 7f ac 4c 0a 8a b5 7f  |-..?y......L....|
00003ff0  34 a2 98 5b ca e4 2e cc  eb 73 7d c0 63 8d 9e 73  |4..[.....s}.c..s|
00004000  75 ee ac 6e e5 71 3a 50  74 b6 52 cd f0 55 31 80  |u..n.q:Pt.R..U1.|
00004010  a9 c5 61 12 3b eb 25 a3  21 a0 90 1b 67 1a 00 3a  |..a.;.%.!...g..:|
00004020  28 59 4f 29 20 db c4 bf  7a ee ed b7 0f 0d 33 b3  |(YO) ...z.....3.|
00004030  4d 00 18 c1 1a 84 36 5a  1a 04 c9 3b 4f fd 21 ef  |M.....6Z...;O.!.|
00004040  47 0e 75 8e b6 76 9f cb  82 6f ce 77 b7 96 4c b1  |G.u..v...o.w..L.|
...
```

**sarkany tile**
https://sarkany.openstreetmap.org/15/18231/11246.png

![sarkany](https://user-images.githubusercontent.com/63091190/99041144-ac380880-258a-11eb-8780-87d664382982.png)

```
...
00003fb0  8e 3d f7 b7 21 44 2f 98  00 80 c6 ca ca 52 41 65  |.=..!D/......RAe|
00003fc0  b1 c1 0d 6e 13 e0 cc cf  b2 f6 6f 0e 75 00 bb 21  |...n......o.u..!|
00003fd0  b8 e5 0d 2c b4 6f 6e 83  54 00 51 65 3d 5b c8 d9  |...,.on.T.Qe=[..|
00003fe0  2d af 9f 3f 79 fa f4 b1  bb 7f ac 4c 0a 8a b5 7f  |-..?y......L....|
00003ff0  34 a2 98 5b ca e4 2e cc  eb 73 7d c0 63 8d 9e 73  |4..[.....s}.c..s|
00004000  f6 f4 87 b6 ff db f6 b1  af da 58 1b 66 f9 4c df  |..........X.f.L.|
00004010  05 b8 df 8b 98 ee 96 2c  d5 1a 6f 0d f9 c7 01 cf  |.......,..o.....|
00004020  0c 93 9c 6a 12 47 30 03  93 11 9f cb 14 16 8c 18  |...j.G0.........|
00004030  08 80 6d ef 98 fe ba 85  f4 b7 7a 66 b6 ed af 56  |..m.......zf...V|
00004040  97 4c e3 36 55 04 68 bf  1b 41 a0 4b 5c 9e 0f 61  |.L.6U.h..A.K\..a|
...
```

As you can see, corrupted tile differs from 16384 byte (```00004000```).
When investigating issue with previous tiles from July, corrupted tile contents looked like parts of different tile/s. Maybe cache memory leak or something. Hard to tell if similar issues are not present on other tile caches but with different tiles.
