### ISSUE TITLE
Error message for Wiki visual editing 

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/operations#452]
When I try to edit a page on the OSM wiki, I get the following error message:

> Error loading data from server: apierror-visualeditor-docserver-http: ⧼apierror-visualeditor-docserver-http⧽. Would you like to retry?

Editing with the source editor is still possible.

![image](https://user-images.githubusercontent.com/4661658/89041618-f8e23580-d345-11ea-8ac2-5dec7b84d42b.png)

**Comment by mmd-osm** [comment]
Which browser (version), wiki page, etc. did you try? Any browser plugins?

**Comment by westnordost** [comment]
Windows 10, Firefox 79.0 (64-bit), all addons disabled,

tried with https://wiki.openstreetmap.org/wiki/Default_speed_limits

**Comment by mmd-osm** [comment]
Thanks, I tried my user page on the Wiki, and that didn't work either on Ubuntu 18.04, Firefox 76.

**Comment by Firefishy** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/9152419

**Comment by westnordost** [comment]
Thank you!
