### ISSUE TITLE
wiki gateway timeout and slow response times

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/operations#453]
Not sure if this is known but every now and then I'll encounter

> Gateway Timeout
> The gateway did not receive a timely response from the upstream server or application.
> 
> Apache/2.4.29 (Ubuntu) Server at wiki.openstreetmap.org Port 443

Othertimes it will work but the request spends 7.3sec waiting TTFB with a 430ms content download, which is okay but of course a faster response would be nicer.

**Comment by Firefishy** [comment]
We recently switched to use PHP-FPM with a set number of workers. Likely what is happening is all workers get tied up serving (slow?) requests and the waiting requests timeout. Will need some investigation.

**Comment by Firefishy** [comment]
I have upgraded the wiki server settings in https://github.com/openstreetmap/chef/commit/e49218f4d5a297a8a5ccf5998df62ce4e66e6a65, hopefully this resolves the issue. Please do report it if you see it again.
