### ISSUE TITLE
Switch mediawiki from reCaptcha -> hCaptcha

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#454]
https://www.hcaptcha.com/ support is coming to mediawiki.
This issue is to track that it is an alternative and we should likely switch to it once it becomes fully available in mediawiki / Confirmedit.

https://www.mediawiki.org/wiki/Extension:ConfirmEdit#hCaptcha

**Comment by Firefishy** [comment]
To be clear: We don't have the resources to develop a custom replacement for reCaptcha. If someone else develops a custom replacement with an OpenStreetMap focus, we would be interested.

**Comment by Firefishy** [comment]
Hopefully the captcha upgrade will also fix the mobile issue: https://github.com/openstreetmap/operations/issues/449

**Comment by simonpoole** [comment]
> If only someone created a 'maptcha' that made people do mini-tasks like the Missing Maps app...

That has long been tried for OSM data, but was not particularly popular.

**Comment by Firefishy** [comment]
hCaptcha is now live on OpenStreetMap wiki
