### ISSUE TITLE
15 August 2020 - Planned Maintenance

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#458]
On Saturday 15th August 2020 - 10:00 UTC / GMT+0 we will be performing planned maintenance on ironbelly.
[ironbelly](https://hardware.openstreetmap.org/servers/ironbelly.openstreetmap.org/) is currently a critical server with a warm twin [grisu](https://hardware.openstreetmap.org/servers/grisu.openstreetmap.org/) at Bytemark.

- [x] Update LSI firmware on ironbelly raid controller
- [x] Sync rails data to grisu, repeating as necessary
- [x] Sync planet data to grisu, repeating as necessary
- [x] Sync rails data to AWS S3
- [x] Sync planet data to AWS S3
- [ ] Prep NAT gateway alternative @ Equinix
- [x] Take web site to GPX offline mode
- [x] Shutdown replication
- [x] Perform final sync of rails data to grisu
- [x] Perform final sync of planet data to grisu
- [x] Live OOB remote console ironbelly
- [x] Reboot ironbelly
- [x] Return services once ironbelly back to live state

**Comment by Firefishy** [comment]
Announced the maintenance here: https://twitter.com/OSM_Tech/status/1293685109518934018

**Comment by Firefishy** [comment]
And mailinglist: https://lists.openstreetmap.org/pipermail/announce/2020-August/000109.html

**Comment by gravitystorm** [comment]
The plan above has syncing of data from ironbelly to grisu (and S3), but the services like GPX imports and osmosis diffs will still be running at that point. So if ironbelly doesn't come back immediately, and you have to use grisu for a while, does that mean there would be data loss? Or do you need a 'final sync' after the services have stopped?

**Comment by grischard** [comment]
If I understood correctly, the plan is a continuous sync to reduce the delta, and a final sync once read only.

**Comment by Firefishy** [comment]
Final copes were taken of GPX and diffs.

**Comment by Firefishy** [comment]
Reboot done. New RAID controller firmware installed. New Kernel Installed.

**Comment by Firefishy** [comment]
All done.
