### ISSUE TITLE
fix https://osm.org/g/… URLs

### ISSUE THREAD

**Issue by darkk** [openstreetmap/operations#46]
Looking at [OSM Website #870](https://github.com/openstreetmap/openstreetmap-website/issues/870), [OSM Website #862](https://github.com/openstreetmap/openstreetmap-website/issues/862) and [OSM OPS #2](https://github.com/openstreetmap/operations/issues/2) I assume that https://osm.org/g/ URLs should work.

But they don't. `curl -v https://osm.org/_404_` shows me following certificate, that is valid only for openstreetmap.org and *.openstreetmap.org, but not for osm.org.
```
* Server certificate:
* 	 subject: OU=GT33044578; OU=See www.rapidssl.com/resources/cps (c)12; OU=Domain Control Validated - RapidSSL(R); CN=*.openstreetmap.org
* 	 start date: 2015-05-16 11:11:49 GMT
* 	 expire date: 2016-03-18 14:24:26 GMT
* 	 subjectAltName does not match osm.org
* SSL: no alternative certificate subject name matches target host name 'osm.org'
```

Excuse me, if it's wrong place to report this bug to.

**Comment by tomhughes** [comment]
Correct, we don't have a certificate for osm.org which is why we don't publish those URLs.

If you read the full history of #2 you will discover that we had problems with the new provider that would allowed us to offer this and had to revert to the original provider.

Hopefully once letsencrypt is up and running we will be able to revisit this.

**Comment by genodeftest** [comment]
*bump* please reopen! Let's encrypt is up and running so you can get certificates for https://osm.org/ now.

**Comment by tomhughes** [comment]
No, we can't because it will break old JOSMs - we need to wait for a large enough proportion of our user base to upgrade to versions that support letsencrypt first. I have a query that I use to watch that.

**Comment by genodeftest** [comment]
Ok, understood.

**Comment by genodeftest** [comment]
Ok, understood. Still, don't you want to reopen this bug? It still is a bug, it's just blocked by time or JOSM development.

**Comment by tomhughes** [comment]
It might be a feature request, but it's not a bug because we have never claimed to support such URLs.

Moving to letsencrypt is a large project that is completely on my radar on whether or not this ticket is open will have no effect whatsoever on that other that acting as noise.
