### ISSUE TITLE
Setting LimitRequestBody for Rails endpoints

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#460]
Several Rails endpoints happily accept POST requests of just about any size, which isn't ideal. As a countermeasure I'd like to suggest to add a LimitRequestBody on Apache level to have at least a global upload limit of maybe 500MB-1GB. This should be sufficient for anything I can think of, while keeping the really insane uploads out.

Obviously, I haven't tested this before, so there might be some limit in place that I'm unaware of, in which case, this issue is redundant.

**Comment by tomhughes** [comment]
As of apache 2.4.54 (which we are no running) there is a default of 1Gb for this value according to https://httpd.apache.org/docs/2.4/mod/core.html#limitrequestbody.

**Comment by mmd-osm** [comment]
Sounds good, 1Gb is well within the limits I had in mind. Closing here.
