### ISSUE TITLE
404 response when tiles are supposed to be loading

### ISSUE THREAD

**Issue by 0x78f1935** [openstreetmap/operations#462]
- https://a.tile.openstreetmap.org/18/134929/86954.jpg
- https://b.tile.openstreetmap.org/18/134930/86954.jpg
- https://c.tile.openstreetmap.org/18/134930/86955.jpg

Same issue as https://github.com/openstreetmap/operations/issues/281

I quote: """
Replacing orm appears to have fixed the render capacity issues and the CDN has more headroom now from a combination of more nodes and blocking apps faking their user-agent or referrer. Any new issues are unlikely to be related to this one.
"""

```
tile.openstreetmap.org debug
Server Stats
Cache Server: trogdor.openstreetmap.org

Render Server: odin.openstreetmap.org
Load Average: 8.88

File Status
simplified-land-polygons-complete-3857.zip last modified: Thu Sep 10 06:30:55 2020
simplified-water-polygons-split-3857.zip last modified: Thu Sep 10 06:31:02 2020
ne_110m_admin_0_boundary_lines_land.zip last modified: Wed Apr 3 17:50:02 2019
land-polygons-split-3857.zip last modified: Thu Sep 10 06:31:15 2020
water-polygons-split-3857.zip last modified: Thu Sep 10 06:31:50 2020
antarctica-icesheet-polygons-3857.zip last modified: Thu Sep 10 06:32:14 2020
antarctica-icesheet-outlines-3857.zip last modified: Thu Sep 10 06:32:18 2020
Browser Request Headers
CONTEXT_DOCUMENT_ROOT: /srv/tile.openstreetmap.org/cgi-bin/
CONTEXT_PREFIX: /cgi-bin/
DOCUMENT_ROOT: /srv/tile.openstreetmap.org/html
GATEWAY_INTERFACE: CGI/1.1
HTTPS: on
HTTP_CACHE_CONTROL: max-age=1209600
HTTP_CONNECTION: keep-alive
HTTP_HOST: tile.openstreetmap.org
HTTP_SURROGATE_CAPABILITY: trogdor.openstreetmap.org="Surrogate/1.0 ESI/1.0"
HTTP_USER_AGENT: NONE
HTTP_VIA: 1.1 trogdor.openstreetmap.org (squid/4.11)
HTTP_X_FORWARDED_FOR: 217.102.188.76, 127.0.0.1
LC_CTYPE: C.UTF-8
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
QUERY_STRING:
REMOTE_ADDR: 134.90.146.26
REMOTE_PORT: 46842
REQUEST_METHOD: GET
REQUEST_SCHEME: https
REQUEST_URI: /cgi-bin/debug
SCRIPT_FILENAME: /srv/tile.openstreetmap.org/cgi-bin/debug
SCRIPT_NAME: /cgi-bin/debug
SCRIPT_URI: https://tile.openstreetmap.org/cgi-bin/debug
SCRIPT_URL: /cgi-bin/debug
SERVER_ADDR: 130.117.76.15
SERVER_ADMIN: webmaster@openstreetmap.org
SERVER_NAME: tile.openstreetmap.org
SERVER_PORT: 443
SERVER_PROTOCOL: HTTP/1.1
SERVER_SIGNATURE:

Apache/2.4.41 (Ubuntu) Server at tile.openstreetmap.org Port 443

SERVER_SOFTWARE: Apache/2.4.41 (Ubuntu)
```
When visiting the links you will end up on a 404 not found page.

Is anyone else experiencing this problem?

**Comment by tomhughes** [comment]
This was fixed a few hours ago when trogdor was dropped from the CDN.

**Comment by 0x78f1935** [comment]
I would like to point out to people who walk against the same issue: "Check your tile server endpoint".
I looked into https://wiki.openstreetmap.org/wiki/Tile_servers and noticed that the endpoint I was calling used PNG extension.
Some refactor in the code of mine changed every png extension to jpg and therefor the endpoint to the tile server was incorrect.

"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.jpg" should have been "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"

This fixed my problem.

--

Thanks for your reply tomhughes
