### ISSUE TITLE
Diff state.txt file sporadically returns 10 spurious null bytes at the end

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#465]
On different servers we have noticed that https://planet.openstreetmap.org/replication/minute/state.txt sporadically returned a payload with 10 NULL bytes towards the end. 

This appears to be some "ghost" left over from a previous state.txt file which happened to be 10 bytes larger. It seems that the file size assumed by the Apache server is out of sync with actual state.txt file contents. There might be some race condition, e.g. between Apache and osmosis.

Is this a known problem other users also encountered before?

Original issue: https://github.com/drolbr/Overpass-API/issues/596

**Comment by tomhughes** [comment]
While I don't the symptom, your suggested cause is totally implausible. It's far more likely that the file on disk just has ten nul bytes for some reason than that apache has somehow cached a file length and then, hitting EOF before it gets that far, chooses to send a stream of zeros rather than just stopping or erroring.

**Comment by mmd-osm** [comment]
We have two productive Overpass instances in place, and only one of them was affected by this issue. I'm assuming that both instances had to read the same state.txt file, as the munin stats indicate a maximum lag of 60 seconds. Therefore I'm not really convinced that it is the state.txt file on disk that has those extra NULL bytes.

**Comment by tomhughes** [comment]
Well if it is a bug in apache (which still seems unlikely to me) then there's not going to be a lot we can do.

I certainly can't do anything with some sort of details, like which state file it was, what time it was fetched, what machine fetched it, etc.

**Comment by mmd-osm** [comment]
Thanks for looking into this. We've seen those NULL bytes both in https://planet.openstreetmap.org/replication/minute/004/238/749.state.txt and https://planet.openstreetmap.org/replication/minute/state.txt. Roland concluded from his analysis that issue was already present in the central state.txt file (minute/state.txt). This matches with what another user reported back in September.

* Timestamp: 2020-10-14T19:26:02Z  - 
Some users on Slack US reported that the db was stuck at 2020-10-14T19:25:00Z, which matches Roland's analysis. Maybe all log files entries +/- 2 minutes could be relevant here. There shouldn't be too many for this host.

* Host: lz4.overpass-api.de
I don't know if the host would show up under its ipv4 or ipv6 ip in the logs.

**Comment by tomhughes** [comment]
Well that machine definitely got stuck at that point, though it was 748 not 749 that it got stuck on:

```
2a01:4f8:120:6464::2 - - [14/Oct/2020:19:25:18 +0000] "GET /replication/minute//state.txt HTTP/1.1" 200 4045 "-" "Wget/1.17.1 (linux-gnu)"
2a01:4f8:120:6464::2 - - [14/Oct/2020:19:25:18 +0000] "GET /replication/minute//004/238/748.state.txt HTTP/1.1" 200 4045 "-" "Wget/1.17.1 (linux-gnu)"
2a01:4f8:120:6464::2 - - [14/Oct/2020:19:25:18 +0000] "GET /replication/minute//004/238/748.osc.gz HTTP/1.1" 200 91383 "-" "Wget/1.17.1 (linux-gnu)"
2a01:4f8:120:6464::2 - - [14/Oct/2020:19:25:33 +0000] "GET /replication/minute//state.txt HTTP/1.1" 200 4045 "-" "Wget/1.17.1 (linux-gnu)"
2a01:4f8:120:6464::2 - - [14/Oct/2020:19:25:48 +0000] "GET /replication/minute//state.txt HTTP/1.1" 200 4045 "-" "Wget/1.17.1 (linux-gnu)"
2a01:4f8:120:6464::2 - - [14/Oct/2020:19:26:03 +0000] "GET /replication/minute//state.txt HTTP/1.1" 200 4045 "-" "Wget/1.17.1 (linux-gnu)"
```

after that there is nothing more for at least half an hour.

There are no nuls in the on disk version of 748 or 749 at the moment.

What was the other machine? Only what I really wanted was to compare the log entries...

**Comment by mmd-osm** [comment]
> What was the other machine? Only what I really wanted was to compare the log entries...

That's "z.overpass-api.de, having ipv6 2a01:4f8:110:502c::2 and ipv4 178.63.11.215

**Comment by tomhughes** [comment]
So the final fetch that the first server did before it blocked was logged as 4045 bytes while the server which didn't block was logged one second later as 4037 bytes - that is actually the global version of the 749 state. The working server logged that as:

```
2a01:4f8:110:502c::2 - - [14/Oct/2020:19:26:04 +0000] "GET /replication/minute//state.txt HTTP/1.1" 200 4037 "-" "Wget/1.17.1 (linux-gnu)"
2a01:4f8:110:502c::2 - - [14/Oct/2020:19:26:04 +0000] "GET /replication/minute//004/238/749.state.txt HTTP/1.1" 200 4037 "-" "Wget/1.17.1 (linux-gnu)"
2a01:4f8:110:502c::2 - - [14/Oct/2020:19:26:04 +0000] "GET /replication/minute//004/238/749.osc.gz HTTP/1.1" 200 58967 "-" "Wget/1.17.1 (linux-gnu)"
```

The working server when it restarted then logged it as 4035 but those numbers are slightly tricky to compare as they include the response headers.

I still think it probably was wrong on disk - we know there are issues with osmosis not syncing the files and we have hacks in place that sync them but there might be a window of time where you can see extra padding or something.

**Comment by tomhughes** [comment]
I can't see anything obviously wrong in what osmosis is doing - an strace shows that it creates a temporary file, closes it (which does an fdatasync due to our hack) and then renames it into place. So there shouldn't be any window where it might be dodgy.

So maybe it is apache but if so then it's ahrd to see what we can do.

**Comment by mmd-osm** [comment]
This post on atomically replacing files w/ Apache is a bit dated and for an earlier Apache version, nevertheless this might hint to what's going on here: https://serverfault.com/questions/576495/how-to-atomically-replace-files-in-apache

> When I replace served file (or modify symlink) and download this file simultaneously, Apache rarely (in small fraction of percent) responds with headers from old file, but with content from new file.

What's puzzling is at what point that screw up happens, and what's impacted by it:
* Are those log file content length figures correct, or do they also reflect the old content?
* Would wget on the client side add those null bytes on its own to match the Content-Length reported by the server?

**Comment by lonvia** [comment]
I have definitely seen `minute/state.txt` files that were cut. This would be explained by Apache sending a wrong length.

I'm not sure it is worth fixing on the server side though. The client code should have provisions anyway to handle receiving garbage from the server.

**Comment by mmd-osm** [comment]
My preference would always be to fix the issue at the source, rather than having everyone else trying to make some sense out of potentially broken data. Cut files also sounds quite nasty. Did that fit the same pattern, where a previous state.txt file size was used instead?

In this particular case, the issue may just disappear once we switch to osmdbt, as all txn* fields will be gone by then. They were the only reason for varying state.txt file sizes.

**Comment by tomhughes** [comment]
Well sure we'd all love to fix it at source. Are you volunteering to debug apache and get a patch accepted upstream and do new Ubuntu builds?

**Comment by mmd-osm** [comment]
As always there are multiple options:
1. Do nothing and wait a few months for osmdbt (see above)
2. Acknowledge that Apache isn’t good at serving static content that is changing rather frequently. Mitigation could be to treat state.txt as dynamic content and serve it via own cgi script instead. 
3. Log issue with Apache, find out 5 years later that this is a works as designed (ok, just kidding, I don’t know what the answer will be)

Are there other options? Which one would be the preferred one?

**Comment by tomhughes** [comment]
Do nothing on the grounds nothing has changed here for years and nobody has had a problem with the current behaviour until now?

Note that osmdbt changes nothing as we still have apache serving a file that can change underneath it.

**Comment by mmd-osm** [comment]
Well, for Overpass the process was changed only recently based on your recommendation in https://wiki.openstreetmap.org/wiki/Planet.osm/diffs#Fetching_diff_files - the logic never considered the minute/state.txt earlier on.

I did an strace on Apache yesterday, and it seems to go ahead with a “stat” using the actual state.txt file location, followed by opening the file and working with the file descriptor.

If that’s the reason for the incorrect Content-Length, we should be good with osmdbt, as the file size would never change.

**Comment by mmd-osm** [comment]
Reported as upstream issue with Apache: https://bz.apache.org/bugzilla/show_bug.cgi?id=64834

**Comment by mmd-osm** [comment]
Feedback so far seems to confirm our hypothesis. There’s even a pending patch for Apache out there, and some ideas for mitigation.

**Comment by mmd-osm** [comment]
I'm closing this one due to the move to osmdbt this coming weekend. As the new state.txt files will always have exactly the same size, this issue can no longer occur.

Apache issue to fix the root cause is still open: https://bz.apache.org/bugzilla/show_bug.cgi?id=54962
