### ISSUE TITLE
Sticky table headers

### ISSUE THREAD

**Issue by aovanessian** [openstreetmap/operations#467]
Hi all, trying to add support for sticky table headers (useful for large tables).

The changes are minimal and non-invasive (a couple of style rules for Common.css); details here: https://wiki.openstreetmap.org/wiki/MediaWiki_talk:Common.css#Sticky_table_headers

**Comment by tomhughes** [comment]
Right, but a wiki admin can do that - you don't need us.

**Comment by aovanessian** [comment]
Got it, thank you!
