### ISSUE TITLE
Tiles do not load with extra leading / in path

### ISSUE THREAD

**Issue by omaues** [openstreetmap/operations#468]
Hello,
I keep getting errors and the map does not display. In all browsers

http://a.tile.openstreetmap.org//9/131/235.png
http://b.tile.openstreetmap.org//9/130/238.png
http://c.tile.openstreetmap.org//9/131/237.png

If I paste the url into browser it comes back with an error message saying: Not found.

in the morning it doesn't work but in the afternoon it works

**Comment by tomhughes** [comment]
There is no actionable information here - you provide no idea where you're located, what browser you're using, or anything else which might help us diagnose the problem.

This is not something anybody else has reported, so it's likely specific to you in some way and we will need more information before we can help.

**Comment by tomhughes** [comment]
Also the fact you're using http URLs make me think that maybe you are using a third party application or site, as our site would use https URLs?

**Comment by omaues** [comment]
![OSM](https://user-images.githubusercontent.com/73643942/97574559-06dd3c00-19b1-11eb-8318-e073228e2a21.png)

I attach an image of the problem and if you are right I have tried https, I apologize for not copying the URL correctly, I have tried chrome, firefox, edge in all the browsers that I have installed
I was seeing that they had a similar incidence which is described in:
https://github.com/openstreetmap/operations/issues/281
I would like to guide me to solve this problem

**Comment by iandees** [comment]
Please try removing the extra slash in the URL in your screenshot.

**Comment by omaues** [comment]
He probado y efectivamente funciona, pero en mi aplicación funciona y esa URL es la que me muestra el log

**Comment by omaues** [comment]
I have tried and it actually works, but in my application it works and that URL is the one that shows me the log

**Comment by tomhughes** [comment]
Can you confirm where you are, or go to https://tile.openstreetmap.org/cgi-bin/debug and tell us what server it says you are using?

**Comment by omaues** [comment]
I am located in ElSalvador, Central America and when accessing the site it shows the following information:
tile.openstreetmap.org debug
Server Stats

Cache Server: glaedr.openstreetmap.org

Render Server: pyrene.openstreetmap.org
Load Average: 35.76
File Status

simplified-land-polygons-complete-3857.zip last modified: Thu Oct 29 08:02:24 2020
simplified-water-polygons-split-3857.zip last modified: Thu Oct 29 08:02:31 2020
ne_110m_admin_0_boundary_lines_land.zip last modified: Mon Sep 3 20:17:11 2018
land-polygons-split-3857.zip last modified: Thu Oct 29 08:03:37 2020
water-polygons-split-3857.zip last modified: Thu Oct 29 08:05:05 2020
antarctica-icesheet-polygons-3857.zip last modified: Thu Oct 29 08:05:33 2020
antarctica-icesheet-outlines-3857.zip last modified: Thu Oct 29 08:05:43 2020
Browser Request Headers

CONTEXT_DOCUMENT_ROOT: /srv/tile.openstreetmap.org/cgi-bin/
CONTEXT_PREFIX: /cgi-bin/
DOCUMENT_ROOT: /srv/tile.openstreetmap.org/html
GATEWAY_INTERFACE: CGI/1.1
HTTPS: on
HTTP_CACHE_CONTROL: max-age=1209600
HTTP_CONNECTION: keep-alive
HTTP_HOST: tile.openstreetmap.org
HTTP_SURROGATE_CAPABILITY: glaedr.openstreetmap.org="Surrogate/1.0 ESI/1.0"
HTTP_USER_AGENT: NONE
HTTP_VIA: 1.1 glaedr.openstreetmap.org (squid/4.11)
HTTP_X_FORWARDED_FOR: 138.186.251.73, 127.0.0.1
LC_CTYPE: C.UTF-8
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
QUERY_STRING:
REMOTE_ADDR: 200.25.1.71
REMOTE_PORT: 55464
REQUEST_METHOD: GET
REQUEST_SCHEME: https
REQUEST_URI: /cgi-bin/debug
SCRIPT_FILENAME: /srv/tile.openstreetmap.org/cgi-bin/debug
SCRIPT_NAME: /cgi-bin/debug
SCRIPT_URI: https://tile.openstreetmap.org/cgi-bin/debug
SCRIPT_URL: /cgi-bin/debug
SERVER_ADDR: 140.211.167.98
SERVER_ADMIN: webmaster@openstreetmap.org
SERVER_NAME: tile.openstreetmap.org
SERVER_PORT: 443
SERVER_PROTOCOL: HTTP/1.1
SERVER_SIGNATURE:
Apache/2.4.41 (Ubuntu) Server at tile.openstreetmap.org Port 443

SERVER_SOFTWARE: Apache/2.4.41 (Ubuntu)

**Comment by tomhughes** [comment]
Thanks. So you're hitting the cache in Bogotá which is actually two machines but they both look to be coping OK with the load so I don't think there's a problem there.

So are you saying it always fails with the `//` and always works with `/` in the URL there? If so it's likely so filter rule in our cache configuration that is blocking you. If you're not able to reconfigure the software you're using to avoid that then you should probably talk to whoever created it.

**Comment by omaues** [comment]
![OSM2](https://user-images.githubusercontent.com/73643942/97589740-82e07f80-19c3-11eb-8284-21625a8d098e.png)
the curious thing that at times if it works with the double // as seen in the attached image

**Comment by omaues** [comment]
The fact that sometimes it works and other times it doesn't, will it have to do with some issue of the number of requests made to the server?

**Comment by pnorman** [comment]
I also get a 404 from `https://tile.openstreetmap.org//0/0/0.png`. This is not an error on our servers, whatever site or program you are using needs to use the correct tile URL which is `https://tile.openstreetmap.org/{zoom}/{x}/{y}.png`.

**Comment by iandees** [comment]
The regex that filters out bad tile requests in Fastly will 404 a request like this.

**Comment by tomhughes** [comment]
Well I was assuming it was something like that but the test he did was hitting our CDN not fastly.

Some of his requests must be coming from a different IP or something, and winding up at fastly.

**Comment by omaues** [comment]
When testing with the double / equal it works for me, but sometimes yes and sometimes not, that's the weird thing
![OSM2](https://user-images.githubusercontent.com/73643942/97629117-40cf3200-19f3-11eb-9c95-bd8918c6706b.png)

**Comment by pnorman** [comment]
Part of our cache network considers the path with two leading `/` invalid, part does not. I don't see rejecting `//` as a bug, but consistency would be nice.

**Comment by omaues** [comment]
Thank you very much, any recommendation that you can give me, it is worth mentioning that the source code of the application has not been changed in about 2 years, it will be that the filter made by the open street maps servers was updated and that is causing this behavior, or some other update of the open street maps servers

**Comment by tomhughes** [comment]
Yes we are in the process of deploying a new CDN infrastructure and it is that new infrastructure that is refusing your requests.

It seems that for some reasons some of your requests are coming from a different IP that geocodes to the US and hence hit the new infrastructure while others are geocoding to south america and hitting the old infrastructure.

**Comment by grischard** [comment]
People who are using Cloudflare's DNS resolvers will be geocoded to the US, and therefore routed to the new CDN test infrastructure.

http://www.whatsmydnsserver.com/ should tell you if you're using their services.

**Comment by omaues** [comment]
I share the result by entering http://www.whatsmydnsserver.com/
Your DNS Server:	74.125.184.137
Owner of this server:	Google LLC
Status of this server:	Everything is fine

**Comment by pnorman** [comment]
We discussed this at the meeting of OWG & helpers and concluded there isn't anything wrong on our end. Your map client should be using URLs without the double slash.

**Comment by omaues** [comment]
Thank you very much for all your input, I will check that the double / no part is present. Very fine.
