### ISSUE TITLE
https://wiki.openstreetmap.org/ is down

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#469]
Appears to not be just me according to https://www.isitdownrightnow.com/wiki.openstreetmap.org.html and some other people at https://t.me/OpenStreetMapOrg/65500

**Comment by donalhunt** [comment]
system stats: https://munin.openstreetmap.org/openstreetmap.org/tabaluga.openstreetmap.org/index.html

**Comment by donalhunt** [comment]
/dev/shm usage growth may be culprit looking at the graphs.

**Comment by matkoniecz** [comment]
note: below is uninformed speculation and lame attempts to diagnose what went wrong

https://munin.openstreetmap.org/openstreetmap.org/tabaluga.openstreetmap.org/users.html - I wonder is it symptom of failure or indication that someone is fixing it

https://munin.openstreetmap.org/openstreetmap.org/tabaluga.openstreetmap.org/diskstats_iops/index.html https://munin.openstreetmap.org/openstreetmap.org/tabaluga.openstreetmap.org/mysql_commands.html https://munin.openstreetmap.org/openstreetmap.org/tabaluga.openstreetmap.org/mysql_innodb_bpool.html https://munin.openstreetmap.org/openstreetmap.org/tabaluga.openstreetmap.org/forks.html https://munin.openstreetmap.org/openstreetmap.org/tabaluga.openstreetmap.org/processes.html show spikes

https://munin.openstreetmap.org/openstreetmap.org/tabaluga.openstreetmap.org/threads.html looks like something went and killed whatever normally operates (OOM killer?)

**Comment by tomhughes** [comment]
It was being upgraded.
