### ISSUE TITLE
Suppress FailedReadSmartSelfTestLog errors for katla

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#47]
We get a daily email which contains

```
Device: /dev/sg0 [megaraid_disk_16], Read SMART Self-Test Log Failed

Device info:
[SEAGATE  ST900MM0026      0003], lu id: 0x5000c5005e8fe503, S/N: S0N01WTZ00009320PEKN, 900 GB
```
If I understand @zerebubuth correctly, in #43 he notes that this is because the spare drives are spun down, i.e. this is a false alert. So we should suppress it somehow.

**Comment by tomhughes** [comment]
Again, easily, said, but hard to do.

Seriously, there's nothing more I'd like than for this stuff to work, but it's basically intractable.

**Comment by tomhughes** [comment]
This should be fixed now - chef was wedged and had not updated `smartd.conf` after the disk swap.
