### ISSUE TITLE
FR: Put wiki.openstreetmap.org behind a reverse proxy

### ISSUE THREAD

**Issue by donalhunt** [openstreetmap/operations#470]
This morning's upgrade of wiki.openstreetmap.org highlighted some improvements that could be made:
- During maintenance events, it would be useful to continue serving a splash page of some sort.
- wiki performance has been noticeable slow recently. Caching pages could improve performance.

Use of a reverse proxy would allow the following:
- ability to direct visitors to a splash page during maintenance periods.
- ability to block / slow down any automated scraping of the wiki that could impact regular users
- allow operations to scale the number of backends in the future.
- allow for zero downtime upgrades (assumes multiple backend servers)

**Comment by tomhughes** [comment]
Well I never expected to have such a substantial downtime but there were a number of issues.

I'm not going to spend a load of time building extra infrastructure to avoid a minor inconvenience to a secondary service for an hour or two a year though.

Those who have been around will remember that years ago we used to have a reverse proxy and it was removed for good reasons.

The performance issue is already being discussed in other tickets I believe.
