### ISSUE TITLE
SyntaxHighlight stopped highlighting, adds syntax highlighting error category

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/operations#472]
The SyntaxHighlight extension stopped working after upgrading to MediaWiki 1.35 (openstreetmap/chef@6f4710e93b75a06ac8fa6ec7469dda912c775221). Code blocks marked with `<syntaxhighlight>` are no longer highlighted. Pages containing `<syntaxhighlight>` are always added to the “[Pages with syntax highlighting errors](https://wiki.openstreetmap.org/wiki/Category:Pages_with_syntax_highlighting_errors)” category, even if there are no apparent errors. Compare the following pages, which are identical:

https://wiki.openstreetmap.org/wiki/Special:PermanentLink/2056497
https://en.wikipedia.org/wiki/Special:PermanentLink/986943084

**Comment by tomhughes** [comment]
Well the extension is still enabled so I don't know what more to say.

I don't really know anything about PHP, mediawiki, or any of the extensions we deploy so I most rely on people telling me what is needed.

**Comment by tomhughes** [comment]
I believe https://github.com/openstreetmap/chef/commit/7d5f15d40941310c1e2e99db5566c1a5ad0576fb has fixed this.
