### ISSUE TITLE
Disk failure in stormfly-03

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#473]
A disk has failed in stormfly-03:

```
This is a RAID status update from cciss-vol-statusd.  The cciss_vol_status
program reports that one of the RAIDs changed state:

/dev/sda: (Smart HBA H240ar) RAID 5 Volume 0 status: Using interim recovery mode. 
  Failed drives:
         connector 1I box 1 bay 3                                                                    INQUIRY FAILED         

    Total of 1 failed physical drives detected on this logical drive.

Report from /usr/local/bin/cciss-vol-statusd on stormfly-03.openstreetmap.org
```

**Comment by Firefishy** [comment]
Model: `HP VO0960JFDGU`

**Comment by Firefishy** [comment]
Wow HPE wow! `The issue affects SSDs with an HPE firmware version prior to HPD8 that results in SSD failure at 32,768 hours of operation (i.e., 3 years, 270 days 8 hours), neither the SSD nor the data can be recovered, after the SSD failure occurs.` in a firmware update.

**Comment by Firefishy** [comment]
@pnorman Would you mind handling updating here if you think we have a warranty case.

**Comment by Firefishy** [comment]
Potential option if we need to buy one: https://www.ebay.co.uk/itm/HP-816559-002-PM1633-960GB-12Gbps-2-5-SAS-SSD-Solid-State-Drive-for-Gen8-Gen9/143728623914

**Comment by pnorman** [comment]
We have a 1 year warranty ending in March or April 2021 on the systems but we bought them diskless then purchased disks separately which only had a 90 day.

https://www.ebay.com/itm/HP-816559-002-PM1633-960GB-12Gbps-2-5-SAS-SSD-Solid-State-Drive-for-Gen8-Gen9/143728623914 looks okay to me.

**Comment by Firefishy** [comment]
> We have a 1 year warranty ending in March or April 2021 on the systems but we bought them diskless then purchased disks separately which only had a 90 day.
> 

@pnorman Would you mind organising the warranty replacement if possible?

**Comment by pnorman** [comment]
> @pnorman Would you mind organising the warranty replacement if possible?

Sorry, I wasn't clear above. Disks had a 90 day warranty which expired mid last year, so were not under warranty when they failed.

**Comment by Firefishy** [comment]
OSU contacted. I will order disk shortly.

**Comment by Firefishy** [comment]
Disk ordered and is on-route.

**Comment by tomhughes** [comment]
Disk has been replaced and array rebuilt.
