### ISSUE TITLE
Errol disk issues

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#476]
Recent replacement disk in errol seems to have issues. It needs to be re-seated or replaced.
```
Device: /dev/sg2 [areca_disk#04_enc#01], ATA error count increased from 459 to 461

Device info:
WDC WD2002FFSX-68PF8N0, S/N:WD-WCC6N2UE2YL2, WWN:5-0014ee-2672f148c, FW:81.00A81, 2.00 TB
```

Does not look like the RAID controller has a way to preemptively failed the disk to switch to the hot-spare.

**Comment by pnorman** [comment]
We've put a new machine in the [budget request](https://operations.osmfoundation.org/2021/02/23/budget.html), so if approved, we'll have something new with new drives.

**Comment by Firefishy** [comment]
I already have a replacement disk, warranty replacement. But I have a suspicion the issue is actually the controller not liking the modern disk controller.

**Comment by Firefishy** [comment]
Replaced with old stock.
