### ISSUE TITLE
Update Pyosmium version on grindtooth

### ISSUE THREAD

**Issue by joto** [openstreetmap/operations#477]
Grindtooth currently uses a monkey-patched version of pyosmium to be able to update history planet files correctly.

Installed is version `3.0.0-1~ubuntu20.04.1~ppa1` of `python3-pyosmium`, but we need version 3.1.0 which contains this fix. I had thought that this would fix itself automatically when the Debian package for 3.1.0 is out, but I guess the package comes from somewhere else.

**Comment by tomhughes** [comment]
Update to Debian packages will normally come to new releases of Ubuntu eventually but not to existing releases.

We're using osmium builds from our own PPA anyway (https://launchpad.net/~osmadmins/+archive/ubuntu/ppa/+packages) so I've kicked off a backport build of pyosmium 3.1.0 there.

**Comment by tomhughes** [comment]
Build has finished and I've updated grindtooth.
