### ISSUE TITLE
Don't say "wound up"

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/operations#479]
https://wiki.osmfoundation.org/wiki/Membership#Normal_Members says
> Also, normal members are liable for up to £1 (one) if the Foundation is **wound up**.

Don't say slang(?) [wound up](https://dictionary.cambridge.org/dictionary/english/wound-up). Pick a more formal word.

**Comment by gravitystorm** [comment]
The Operations Working Group is not responsible for the content of the OSMF website.

To 'wind up a company' is a regular business term, not slang. See e.g. the first sentence in this UK government guidance: https://www.gov.uk/liquidate-your-company

If you want to pursue this topic, my advice would be to contact the [OSMF Membership Working Group](https://wiki.osmfoundation.org/wiki/Membership_Working_Group).

**Comment by jidanni** [comment]
I get it!
https://en.wiktionary.org/wiki/Talk:wind_up
OK, no change to the OSMF website is needed.
