### ISSUE TITLE
tile cleanup regularly not reaching its target

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#48]
The tile cleanup script is failing to reach its target (80% disk free) almost daily now, on both yevaud and orm. I think the targets are good ([run if over 90%](https://github.com/openstreetmap/chef/blob/024d0c2965ffe6b4438c3c53353698ea65dfc068/cookbooks/tile/templates/default/cleanup-tiles.erb#L21), stop [when under 80%](https://github.com/openstreetmap/chef/blob/024d0c2965ffe6b4438c3c53353698ea65dfc068/cookbooks/tile/templates/default/cleanup-tiles.erb#L27)) but perhaps the atime ([currently 10 days](https://github.com/openstreetmap/chef/blob/024d0c2965ffe6b4438c3c53353698ea65dfc068/cookbooks/tile/templates/default/cleanup-tiles.erb#L23)) needs adjusting.

Of course, reducing the atime means that we're more likely to remove a file which is then needed again, so reducing this might just cause a lot of re-rendering. The real problem could be that the total set of tiles being requested each day is too large for the disks we have - either because we have more legitimate traffic than in the past (i.e. bigger disks required), or because the level of scrapers/bulk downloaders are causing too many tiles to be generated each day (i.e. banhammer required).

So there are three possible things to do here, which is the right one?

**Comment by tomhughes** [comment]
That's only half the problem - the other half is that if we start at 90% we often hit 92% and generate munin warnings before it has started removing anything.

The first thing to do is to figure out why the code to remove empty directories isn't working, as that causes expiry to slow down over time.

**Comment by tomhughes** [comment]
https://github.com/openstreetmap/chef/commit/a0858c90b268bfa28bc362d687f89e43b48830e3 should hopefully fix the cleanup of empty directories, and I'm running a manual cleanup to get rid of legacy ones now.

**Comment by Firefishy** [comment]
Much quieter than before. Only 1 failure on orm on 9th Nov in over a month.

**Comment by gravitystorm** [comment]
Excellent.
