### ISSUE TITLE
Figure out how to process fastly logs

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#485]
The fastly logs are being saved to S3, but we need to figure out how to process them. As part of this we need to consider

- what we are going to use to do ad-hoc log analysis
- what will be generating the published tile access logs
- any other regular analysis we want to do
- the log string we want to use

This doesn't record everything we need. In particular, if something was a cache hit or not would be very useful as well as the country code. Are there any other variables we should add at the same time?

ref. https://docs.fastly.com/en/guides/useful-variables-to-log https://docs.fastly.com/en/guides/custom-log-formats

*Edit: Made issue more about how to process the logs than the precise string used*

**Comment by pnorman** [comment]
As part of this we need to consider
- what we are going to use to do ad-hoc log analysis
- what will be generating the published tile access logs
- any other regular analysis we want to do

**Comment by Komzpa** [comment]
Disaster Ninja uses z/x/y and count to visualize the interest to the map. It used to be published to https://planet.openstreetmap.org/tile_logs/ in that form, restoring it as-is will be helpful. 

https://disaster.ninja/live/#id=c269b084-0990-46d9-b47d-405d9d7dc0f8;position=3.9324272978735735,44.08095096390545;zoom=5.560836658964773;excluded=bivariate-custom_kontur_openstreetmap_road_length,bivariate-custom_kontur_openstreetmap_building_quantity,bivariate-custom_kontur_openstreetmap_mapping_activity,bivariate-custom_kontur_openstreetmap_antiquity,bivariate-custom_kontur_openstreetmap_quantity;overlays=bivariate-custom_kontur_openstreetmap_antiquity

**Comment by migurski** [comment]
How often will ad-hoc analysis be done? With logs already in S3, AWS Athena (hosted PrestoDB) may be a good choice since it will read them in place and only cost money when in active use. I agree with @Komzpa that z/x/y is important to keep.

**Comment by Firefishy** [comment]
Ideally we produce logs in the same format as existing (and backfill). The code for the existing is here: https://github.com/zerebubuth/openstreetmap-tile-analyze , but a re-implementation would likely be much simpler. 

The main bit is the cut-off rule for output is: https://github.com/zerebubuth/openstreetmap-tile-analyze/blob/master/src/main.cpp#L114 (>=10 tile requests from at least 3>= different IP addresses)

**Comment by mmd-osm** [comment]
https://github.com/tyrasd/osm-tile-access-log-viewer might be a good option to quickly validate any uncompressed tile_logs, without  publishing them to the official site.

**Comment by ra0e** [comment]
Mhm, from my perspective the osm-tiles-access-log-viewer looks good. But the project hasn't been updated for three years, does it still work or is maintained?

**Comment by pnorman** [comment]
I'm not too worried about validating the produced tile logs. I think the main part of the work is logging string + generating tile logs. The tile log format itself is quite simple.

**Comment by Komzpa** [comment]
Can a sample of fastly logs be provided so we can help on getting converter working? Or, otherwise, how can we help except for nagging here?

**Comment by pnorman** [comment]
Right now we are collecting 
Format string | Description
-|-
`%h` | The remote IP address
`%l` | Not supported, always `"-"`
`%u` | Not supported, always `"-"`
`%t` | Time
`"%r"` | First line of request (HTTP request type)
`%>s` | HTTP status
`%b` | Response types in bytes
`"%{Referer}i"` | Referer
`"%{User-agent}i"` | User-agent
`%{regsub(fastly_info.state, "^(HIT-(SYNTH)|(HITPASS|HIT|MISS|PASS|ERROR|PIPE)).*", "\2\3") }V` | Cache hit status
`"%{_osm_totp_token}C"` | osm.org TOTP cookie contents
`"%{Accept}i"` | `Accept` header contents
`"%{Accept-language}i"` | `Accept-Language` header contents
`"%{client.geo.country_code}V"` | Country Fastly thinks the request is from
`%{fastly_info.edge.is_tls}V` | [If the client-side connection is TLS](https://developer.fastly.com/reference/vcl/variables/client-connection/fastly-info-edge-is-tls/)
`%{client.as.number}V` | [AS Number of the client](https://developer.fastly.com/reference/vcl/variables/client-connection/client-as-number/)
`"%{Host}i"` | Host the client is connecting to

In addition, the syslog string collects which fastly cache it was.

We should drop the syslog string for easier ingestion by Presto, the unsupported `%l` and `%u`, and add cache info

**Comment by pnorman** [comment]
Information on response we want:
Time of end of request, fastly node, HTTP status, bytes, response time, cache hit status, tls version

Information on request
requesting IP, first line of request, original host header, referer, user-agent, accept header, accept-language header, ASN, country code

The above is what I'll start with. I'm wondering if any of the cache-related variables might be worth it too: https://docs.fastly.com/en/guides/useful-variables-to-log#cache-related-logging-variables

**Comment by pnorman** [comment]
Log string is now ``"%{end:%Y-%m-%dT%H:%M:%S%z}t","%h","%r","%{Fastly-Orig-Host}i","%{Referer}i","%{User-agent}i","%{Accept}i","%{Accept-language}i","%{client.as.number}V","%{client.geo.country_code}V","%{server.datacenter}V","%>s","%b","%{time.elapsed.usec}V","%{regsub(fastly_info.state, "^(HIT-(SYNTH)|(HITPASS|HIT|MISS|PASS|ERROR|PIPE)).*", "\2\3") }V","%{cstr_escape(tls.client.protocol)}V"``

Will test when I have some logs.

For the presto query, something like this is what I was thinking
```sql
SELECT tile, SUM(ip_reqs) FROM (
SELECT func(request) AS tile, ip, COUNT(*) AS ip_reqs FROM logs GROUP BY func(request), ip)
WHERE func(request) IS NOT NULL
GROUP BY tile
HAVING COUNT(*) > 3 AND SUM(ip_reqs) > 10
```
where func() is a call to get the z/x/y from a request, stripping off GET, HTTP version, query parameters, and returning null for any non-tile requests.

**Comment by pnorman** [comment]
Presto is working well, so now it's a matter of scripting it to run the query, take the results, handle postprocessing and compression, and upload them.

**Comment by pnorman** [comment]
Can someone do a QA check on the attached file to make sure it still works? I've limited it to z0-z3

Note that the order of lines may be different from the old software.

I didn't xz compress it because Github doesn't support that.

[tiles-2021-03-23.txt](https://github.com/openstreetmap/operations/files/6193519/tiles-2021-03-23.txt)

**Comment by Lokks** [comment]
@pnorman Hello! 
It looks like it works
![image](https://user-images.githubusercontent.com/11870780/112269981-293a6380-8c8a-11eb-85d6-c690b9976024.png)

**Comment by pnorman** [comment]
I've tagged a release and opened a ticket for chef integration. Some full logs are up at https://pnorman.dev.openstreetmap.org/tilelogs/

**Comment by tyrasd** [comment]
> I've tagged a release and opened a ticket for chef integration. Some full logs are up at https://pnorman.dev.openstreetmap.org/tilelogs/

Nice. :+1: Two minor things I noticed:

In `tiles-2021-03-24.txt`, there seem to be a few superfluous lines (starting with `03`, etc.) at the beginning of the file:
```text
0/0/0 3105943
03/2/4 29
03/3/4 29
03/4/2 29
03/4/3 30
04/5/8 10
04/6/8 11
1/0/0 1145745
```
These extra lines are not present in `tiles-2021-03-20.txt`.

<hr>

The sorting of the lines is currently alphabetic (i.e. `10` comes immediately after `1`, `2` comes after `19`), but would be slightly more user friendly if it was numerical by zoom level.

**Comment by tyrasd** [comment]
another strange artifact in `tiles-2021-03-24.txt` is that the following zoom 19 tiles seems to have an excessive large amount of views: https://a.tile.openstreetmap.org/19/265638/180334.png – Nearby tiles all have very low access numbers (which is typical for zoom 19 tiles):

```
19/265638/180293 13
19/265638/180318 10
19/265638/180334 536800
19/265638/180335 11
19/265638/180416 15
```

The second most accessed zoom 19 tiles is [19/262144/262143](https://a.tile.openstreetmap.org/19/262144/262143.png) (null island?) with 85631 views and a much less suspicious tile neighbourhood:

```
19/262144/262137 43
19/262144/262138 99
19/262144/262139 269
19/262144/262140 1645
19/262144/262141 5483
19/262144/262142 14980
19/262144/262143 85631
19/262144/262144 47629
19/262144/262145 14470
19/262144/262146 15837
19/262144/262147 1640
19/262144/262148 451
19/262144/262149 120
19/262144/262150 78
19/262144/262151 43
```

**Comment by pnorman** [comment]
> In `tiles-2021-03-24.txt`, there seem to be a few superfluous(?) lines (starting with `03`, etc.) at the beginning of the file:

The filter expression is `[0-9][0-9]`, I can change it to `1?[0-9]` which will exclude leading zeros. 

-----

> The sorting of the lines is currently alphabetic (i.e. `10` comes immediately after `1`, `2` comes after `19`), but would be slightly more user friendly if it was numerical by zoom level.

Yes, this comes from the new code treating the z/x/y as a string. Unless this breaks something, I'm inclined to leave it as-is. 

-----

> another strange artifact in `tiles-2021-03-24.txt` is that the following zoom 19 tiles seems to have an excessive large amount of views: https://a.tile.openstreetmap.org/19/265638/180334.png – Nearby tiles all have very low access numbers (which is typical for zoom 19 tiles):

I checked and this is real, not a bug. I might dig into it more, but because it's all the same tile it won't have been impacting the render servers.

**Comment by tyrasd** [comment]
> > In `tiles-2021-03-24.txt`, there seem to be a few superfluous(?) lines (starting with `03`, etc.) at the beginning of the file:
> 
> The filter expression is `[0-9][0-9]`, I can change it to `1?[0-9]` which will exclude leading zeros.

:+1: I could imagine that having "duplicates" like `03/2/4 29 […] 3/2/4 649606` could result in ambiguous situations, e.g. when storing the contents into a database table with an index on (z, x, y).

**Comment by pnorman** [comment]
Fixed this and uploaded for the 25th to 27th

**Comment by Komzpa** [comment]
The updated files are now rendered in Antiquity layer on Disaster.Ninja: 
https://disaster.ninja/live/#id=16e68d1d-0c77-487d-ad46-fb703b1079ab;position=39.58903951959019,55.82364157360965;zoom=7.182912027239239;overlays=bivariate-custom_kontur_openstreetmap_antiquity

Data looks good - better than before when some of the regions/caches/users were missed. Looking forward to prod deploy.

**Comment by pnorman** [comment]
tilelog is now running in production.

**Comment by pnorman** [comment]
We have backfilled until 2021-04-13. A logging error means that earlier data would not be complete, and this gives the last few months, so we do not intend to backfill any farther back.
