### ISSUE TITLE
Consider disallowing asset tracking sites

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#486]
Vehicle or other asset tracking sites have [historically been heavy users](https://github.com/openstreetmap/operations/issues/371) and continue to be so, accounting for 0.2 to 0.4 of the tiles loaded from the osm.org page.

Given their history of overusage, I'm wondering if we should disallow asset tracking sites in the tiles usage policy.

**Comment by matkoniecz** [comment]
If someone has enough assets to require map to track them they also should have enough funds to host own servers.

**Comment by pnorman** [comment]
Closing as I doubt we'll end up doing this. There doesn't seem to be much desire to introduce use restrictions beyond technical ones, and they're not currently posing a problem with load. Since the move to Fastly, we have the capacity on the CDN and the higher use asset tracking uses tend to have higher cache hit ratios.

Anyone considering writing an vehicle tracking app using OSM tiles, I *strongly* recommend a persistent cache of tiles as it will improve the user experience by reducing the number of tiles downloaded.
