### ISSUE TITLE
Please delete the empty page 

### ISSUE THREAD

**Issue by JochenBoettcher** [openstreetmap/operations#487]
Please delete the empty page https://wiki.openstreetmap.org/wiki/DE:Bicycle/Fahrradrouten_kartieren.

The page "DE:Fahrradroutentagging" should be moved here, including the version history. Since the new page already exists and has a version history, the action fails (2 Versions without page content). 

I accidentally created the new page and cannot delete it myself.

Thank you in advance.

**Comment by tomhughes** [comment]
The wiki admins can take care of things like that.

**Comment by JochenBoettcher** [comment]
Thanks, i will ask the admins.
