### ISSUE TITLE
Wiki: File upload permissions for trusted, but new accounts

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#488]
Following two posts in the forum ([1](https://forum.openstreetmap.org/viewtopic.php?id=69925), [2](https://forum.openstreetmap.org/viewtopic.php?id=71382)) of users who wanted to upload images to the wiki but were not allowed to, there was some discussion at [Talk:Wiki](https://wiki.openstreetmap.org/wiki/Talk:Wiki#Unconfirmed_users_that_want_to_upload_images_to_the_wiki) how to support these users. Technically, one needs to be in the "autoconfirmed" user group to upload files. Users are added to the group automatically after they made a certain number of edits (configured in [LocalSettings.php.erb](https://github.com/openstreetmap/chef/blob/dfc631109a486788a18b57da696c06339368993e/cookbooks/mediawiki/templates/default/LocalSettings.php.erb#L248-L250)). In all cases, the user needs to wait the number of days and do some random edits to receive the permissions. In certain cases (esp. in the OSMF wiki) this might not be desirable. Two solutions have been proposed

1. Allow page moves and file uploads to everyone and thereby eliminate the "autoconfirmed" user group (simple solution).
2. Establish a mechanism which enables wiki administrators (or some other trusted user group) to manually grand those rights to individual users (Wikipedia's solution).

I can write a PR for either of these. @Firefishy once configured the "autoconfirmed regime" (probably as a measure against spam). Is one of the options preferable from a sysadmin's point of view?

**Comment by Firefishy** [comment]
For all non wiki.openstreetmap.org autoconfirm should likely be automatic. If 2. is easily possible, that sounds like a reasonable option.
