### ISSUE TITLE
Delayed updates

### ISSUE THREAD

**Issue by richlv** [openstreetmap/operations#489]
For the past few weeks I've observed significant delay in map updates appearing in the tiles.
While lately updates appeared in the matter of minutes (satisfying, helpful to spot mistakes, great in mapping events), currently some changes do not appear for days.
This does not seem to be local browser cache related, as dropping the cache and trying other browsers shows the same effect.
Example area - https://www.openstreetmap.org/#map=18/57.07964/24.32793 had footways and other detail added yesterday, still not showing up.

**Comment by tomhughes** [comment]
Please be patient - with our new caching infrastructure the render servers are busy than normal while the new caches are warming up and they do not always have time to render out of date tiles immediately.

If you are viewing in europe then there is also a complication that the load is being distributed randomly over several render servers so forcing a reload may queue a render on one server but when you next refresh you actually wind up on a different render server. It should all sort itself out with a couple of attempts and some time though.

**Comment by richlv** [comment]
Sorry about getting the wrong repo.

Are there any estimates when tile updates could get back to the minute range?

**Comment by tomhughes** [comment]
Updates to the database remain in the minute range.

There is no way to predict when, or if, load on the upstream servers will reduce to the point that there are no render queues. The recent behaviour of generally having no queues is actually historically unusual and mostly caused by the lack of changes to the style.

There are no current plans to change the randomisation of upstream servers.

**Comment by richlv** [comment]
Got it, thank you.
The almost-immediate renders were wonderful, hopefully they will return :)

**Comment by tordans** [comment]
@richlv JFYI https://www.openstreetmap.org/user/bdon/diary/395221 might be interesting for you to see changes in context
