### ISSUE TITLE
Prometheus metrics for modtile rates off

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#492]
When viewing the graphs for the tile servers, any `rate` graphs on modtile metrics show unexpected lulls which are not seen in the apache rates or the tile CDN. I'm not sure if this is a bug in how we're querying prometheus, the collector, the apache setup, or mod_tile.

The problem is most obvious when only one server is being graphed

`sum(rate(modtile_http_response_total{instance=~"$instance"}[$__rate_interval])) by (code)`
![image](https://user-images.githubusercontent.com/1190866/103464179-89061b80-4ce6-11eb-8dba-b23f0320e8c5.png)

By changing the interval from `$__rate_interval` (4m) to 1m it's possible to see what's going on

`sum(rate(modtile_http_response_total{instance=~"ysera"}[1m]))`
![image](https://user-images.githubusercontent.com/1190866/103464256-22cdc880-4ce7-11eb-8fcb-5d51bdda2144.png)

Looking at `sum(rate(modtile_http_response_total{instance=~"ysera"}[1m]))` and `sum(modtile_http_response_total{instance=~"ysera"})` with both set to a step of 1m shows that sometimes the counter repeats itself

Date | Rate | Counter
-|-|-
2021-01-02 18:30:00 | 1861 | 57164631
2021-01-02 18:31:00 | 1512 | 57232692
2021-01-02 18:32:00 | 1603 | 57304828
2021-01-02 18:33:00 | 1562 | 57375098
2021-01-02 18:34:00 | 0 | 57375098
2021-01-02 18:35:00 | 0 | 57462998
2021-01-02 18:36:00 | 0 | 57528702
2021-01-02 18:37:00 | 1927 | 57615429
2021-01-02 18:38:00 | 1839 | 57698197
2021-01-02 18:39:00 | 1699 | 57774668

When discussing this on #prometheus IRC the theory came up that there is either something broken in what is converting the status page to the prometheus stats, or there is a multi-process issue going on with the counters.

The prometheus exporter [fetches http://localhost/mod_tile](https://github.com/openstreetmap/prometheus-exporters/blob/2d4caa70ed83000eeef2784c01c0174c6fb3cfc4/collectors/modtile/modtile_collector#L93) which is public, so I ran `curl -sL https://albi.openstreetmap.org/mod_tile | head -n1` every second logging to a file overnight and found no duplicate rows with `uniq -c mod_tile_resps | grep '2 NoResp200'`.

At this point I'm puzzled

- [ ] Are there multiple `/tmp/http_shm.*` files? (ref https://github.com/openstreetmap/mod_tile/blob/master/src/mod_tile.c#L1448-L1452)
- [ ] Does querying every 60s with curl change anything?
- [ ] Would querying every 15s with Prometheus help?

Thanks to those who helped in #prometheus

**Comment by SuperQ** [comment]
I pulled some raw data by using some curl tricks to use the "instant" query mode against Grafana. I queried for `modtile_http_response_total{instance=~"ysera"}[24h]` to get the last day of data.

```bash
url='https://prometheus.openstreetmap.org/api/datasources/proxy/1/api/v1/query'
query='modtile_http_response_total%7Binstance%3D%22ysera%22%7D%5B24h%5D
curl -s "${url}?query=${query}" |
  jq -r '.data.result[0].values[][1]' |
  uniq -c
```

This clearly shows repeating data.

The interesting bit I found is is in `jq -r '.data.result[0].metric`. The job is node, which implies this is coming from the node_exporter textfile collector. This means that even if the scrape interval is one thing, the data is not getting updated by whatever cron job is supposed to populate the metric.

**Comment by tomhughes** [comment]
Sorry I'm no really clear on what I'm supposed to be looking for here? Are you suggesting there is a `modtile.prom` file with duplicate rows?

**Comment by tomhughes** [comment]
The prom file is generated roughly once a minute by running https://github.com/openstreetmap/prometheus-exporters/blob/main/collectors/modtile/modtile_collector to parse the mod_tile stats URL.

A duplicate counter is not really surprising as there's no guarantee you won't get four exporter runs between generations if there gap is slightly over a minute. I don't see why it should be a problem though so long as it doesn't move backward.

**Comment by pnorman** [comment]
> A duplicate counter is not really surprising as there's no guarantee you won't get four exporter runs between generations if the gap is slightly over a minute. I don't see why it should be a problem though so long as it doesn't move backward.

It's producing artifacts in the metrics like the first graph.

**Comment by SuperQ** [comment]
So, the root cause here is the mismatch between the cron script and the node_exporter collection intervals. The cron script is only run once per minute, but the exporter is collected every 15 seconds.

I have 3 ideas:
* Convert the script to a "standard" exporter that collects data on demand, rather than use a textfile collector.
* Increase the script frequency to match the node_exporter scrape interval.
* Set a min step in Grafana to 1m to work around the data / frequency mismatch.

**Comment by tomhughes** [comment]
We do have a min step of 1m but the issue is that there are two things running that aren't exactly in sync so sometimes it takes 75s not 60s between updates so we would need to increase it beyond 1m.

I'm probably going to convert it to an exporter as collectors don't really work very well for fast updating statistics like this - they're just a lot easier to write!

**Comment by SuperQ** [comment]
I made an attempt to add a Prometheus metrics endpoint directly to mod_tile. My C is pretty rusty, but it looks like it should work.

**Comment by tomhughes** [comment]
That is the other option yes, though there's also renderd to consider which will have the same problem.

**Comment by tomhughes** [comment]
I've converted the existing collectors to exporters now (in https://github.com/openstreetmap/prometheus-exporters/commit/fca4c25ac7f0d857dd6a069a2b3e1ea35facd5cf) and that seems to have fixed things.

We can still look at moving the functionality into renderd/mod_tile directly in the longer term.

**Comment by SuperQ** [comment]
Oh yea, that looks way more sane: 
![image](https://user-images.githubusercontent.com/1320667/103481704-0318cc00-4ddd-11eb-884e-f47b25cadabf.png)

**Comment by tomhughes** [comment]
A significant part of the problem was that it was running on a systemd timer which (by default) only has an accuracy of +/- one minute which is a lot for something running every minute.

I could reduce that but with one process effectively being clocked by the remote host that is polling the exporters and the other locally we would never guarantee an update ever four exporter cycles.
