### ISSUE TITLE
Send a different status code for tiles that are out of bounds

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#494]
People request invalid tiles like 0/0/1. We filter these out on the CDN and send a 404 instead. This shields the render server, but we can't tell these 404s apart from other valid 404s like a tile that wasn't rendered in time, and this makes analytics harder.

We should send a different error code. I think a 400 Bad Request is most appropriate because an invalid tile location is a client error, and the tile never existed, and never will exist.

**Comment by Firefishy** [comment]
Sounds good to me.

**Comment by pnorman** [comment]
Done.
