### ISSUE TITLE
Generate query information

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#495]
It's been awhile since we've looked at OpenStreetMap Carto performance and I'd like to see what's taking the most times.

Can this shell script be run on rhaegal at some point during the day when it's overloaded?

```bash
for i in `seq 1 360`; do 
psql -AtqX -d postgres -c "COPY (SELECT pid, NOW(), NOW()-query_start AS query_duration, query FROM pg_stat_activity WHERE datname = 'gis' AND pid != pg_backend_pid() AND state != 'idle') TO STDOUT;" >> query_log.txt;
sleep 5;
done
```

It should take about one hour and generate very little load.

**Comment by tomhughes** [comment]
You can grab it at https://tomh.dev.openstreetmap.org/query_log.txt.gz.

I ran it a bit later in the day then I intended so shout if you need e to grab it again though it will have to wait until Monday to get the higher weekday load.

**Comment by pnorman** [comment]
Looks good - it lets me get the layers which I can take back to osm-carto devs.

From the operations side, the main takeaway is that the osm2pgsql updates are small compared to rendering, which is no surprise.
