### ISSUE TITLE
Add Structured Discussions (Flow) Wiki Extension

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/operations#496]
_[Initial Talk:Wiki Topic](https://wiki.openstreetmap.org/wiki/Talk:Wiki#Add_Structured_Discussions_.28Flow.29_Extension)_

Editing talk pages is hard for new/inexperienced Wiki users due to WikiText being the only option to edit them.

This can be especially frustrating/limiting when wanting to comment on: 

- A Proposal being proposed.
- Talk pages in-general

Adding the [Structured Discussions](https://www.mediawiki.org/wiki/Extension:StructuredDiscussions) extension provides a simple interface that allows users to respond, create, resolve, etc. topics easily.

This is how it makes conversations look:
![image](https://user-images.githubusercontent.com/22477298/107094415-94a89e80-67cc-11eb-86fe-51e603550148.png)

All wiki talk pages should be [converted](https://www.mediawiki.org/wiki/Extension:StructuredDiscussions#Migrating_existing_pages) to use it.

The [WikiMedia Talk Pages Project](https://www.mediawiki.org/wiki/Talk_pages_project/Feature_summary) is another option for better talk pages. It is being worked on but it doesn't look like it's available for install. Converting to this should also be a priority when it becomes available.

**Comment by matkoniecz** [comment]
As asked and not answered at wiki talk page:

    (1) what would be import plan for old talk pages?

    (2) is there a working export from StructuredDiscussions to standard talk pages if development on it stops?

**Comment by lectrician1** [comment]
1. Convert all of them (see convert link in original post that explains the script). All current talk page discussions would be archived, though I don't think there would be much of an impact since discussion isn't that frequent and users would be made aware that their discussions moved to archives (we would make an announcement and they would see it in their watchlist). Current discussions would have to have a new topic be made with Structured Discussions to continue them. I think converting all of them at once gets the issue of converting each of them individually off our plates, and the benefits in the long term will outweigh the costs of interrupting discussions in the short term.
2. Structured discussions isn't really developed anymore. [WikiMedia Talk Pages Project](https://www.mediawiki.org/wiki/Talk_pages_project/Feature_summary), the MediaWiki official talk-pages revamp project, would be the next option to convert to. Because it is in beta, there aren't any details on how you could transition Structured Discussions to that, but someone in the Wikimedia community is bound to make a script that converts them. The MediaWiki wiki and itself uses Structured Discussions (and other prominent wikis) and they're going to have to convert at some point too.

**Comment by matkoniecz** [comment]
> Structured discussions isn't really developed anymore

I am worried by that part.

**Comment by lectrician1** [comment]
It's _**stable**_ and _**complete**_ though. That's what's important.

[299 other wikis use it too](https://wikiapiary.com/wiki/Extension:Flow)

**Comment by ZeLonewolf** [comment]
Is there a way for the community to test out the implementation on a page or two so we can get a feel for the value it may provide?

**Comment by lectrician1** [comment]
You could test it on your Wikidata user talk page:

https://www.wikidata.org/wiki/User_talk: _your Wikimedia username_

**Comment by ZeLonewolf** [comment]
I made a test edit at https://www.wikidata.org/wiki/User_talk:ZeLonewolf#Test_discussion and I didn't see anything special.

**Comment by lectrician1** [comment]
Oh, sorry! You have to enable Structured Discussions your [Beta features page](https://www.wikidata.org/wiki/Special:Preferences#mw-prefsection-betafeatures)

For more help: https://www.wikidata.org/wiki/Wikidata:Structured_Discussions

**Comment by ZeLonewolf** [comment]
I like this a lot.  Is there a way to selectively enable the extension within just a certain namespace?  It lends itself well to proposal talks since it's an author-moderated discussion, but I wouldn't want to wipe all the talk pages across the wiki.  Perhaps a new proposal space could be started e.g. [[Proposals/Proposal_Name]] where that extension is enabled.

**Comment by lectrician1** [comment]
You would just go to the Special:EnableStructuredDiscussions page on the Wiki once installed.

You can see this page on [MediaWiki](https://www.mediawiki.org/wiki/Special:EnableStructuredDiscussions).

See also: https://www.mediawiki.org/wiki/Extension:StructuredDiscussions#Migrating_existing_pages

**Comment by ZeLonewolf** [comment]
I wouldn't want to mangle existing pages.  I would want to use the structured discussions only on the new pages going forward.  Also, we need to make sure this can work without users having to go configure something.

**Comment by lectrician1** [comment]
I _think_ once it's enabled, all _new_ pages going forward should have it.

I suggested [in this comment](https://github.com/openstreetmap/operations/issues/496#issuecomment-769894644) to just convert it for all pages too though. 

Talk pages for tags are still used for people to bring up questions about them. Leaving them in their current state isn't taking advantage of this extension, even if it means archiving past discussions.

**Comment by ZeLonewolf** [comment]
I think it's better to introduce new features in a careful and controlled way, and if people like it, then we can talk about converting other pages once/if everyone's comfortable with how it's working.

For past proposals, I'm not in favor of converting them as that's essentially an archived discussion.

**Comment by pnorman** [comment]
We've discussed the wiki extension requests, and would like a wiki admin to comment on this extension request supporting it before we consider it. In future, all requests for the sysadmins to add a wiki extension should be made by a wiki admin.

For any extension requests, the sysadmins will have to consider the cost of maintaining it, and have a strong bias to only enable modules that ship with mediawiki itself.

**Comment by pnorman** [comment]
If a wiki admin requests the extension we can reconsider it.

**Comment by 1ec5** [comment]
[DiscussionTools](https://www.mediawiki.org/wiki/Extension:DiscussionTools) is a much more lightweight alternative to Flow. I’ve used both extensions extensively on Wikimedia wikis and find DiscussionTools to be much more usable than either Flow or the Convenient Discussions gadget. I’m hopeful that it will also be much easier to maintain on the backend than Flow, since it doesn’t require moving anything to a special namespace. As far as I can tell, the database changes are only for tracking discussion notifications and creating permalinks to individual comments in discussions.

I’ve started [a discussion on the wiki](https://wiki.openstreetmap.org/wiki/Talk:Wiki#DiscussionTools_extension) to gauge support before formally requesting DiscussionTools.
