### ISSUE TITLE
Investigate alerting solutions for prometheus

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#499]
We need to investigate alerting solutions for prometheus and decide on a solution - the main options are alerting directly from prometheus via AlertManager and alerting from the web dashboard.

**Comment by tomhughes** [comment]
Documentation on alerting:

* Using prometheus: https://prometheus.io/docs/alerting/latest/overview/#alerting-overview
* Using grafana: https://grafana.com/docs/grafana/latest/alerting/

Both can deliver into Alertmanager though grafana can also deliver directly to various other channels.

**Comment by pnorman** [comment]
We've got some alerts off of prometheus now, right? Are we happy with the state of them?
