### ISSUE TITLE
grisu CPU2 heatsink badly seated or poor thermal paste application

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#50]
Grisu's CPU2 is running significantly hotter than CPU 1. CPU Fan or thermal paste application is likely poor and should be checked.

**Comment by Firefishy** [comment]
Under load CPU2 triggers an overheat warning :-(

**Comment by zerebubuth** [comment]
@Firefishy yeah, i'll schedule a visit ASAP.

**Comment by Firefishy** [comment]
Heatsink was dry. New thermal paste was installed last week Friday.
