### ISSUE TITLE
Source permanent hardware for prometheus

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#500]
Prometheus is currently running as an experimental service on tiamat-11 but it really needs to be moved to better quality hardware.

**Comment by pnorman** [comment]
We've moved it to one of the stormflys, and that seems to be working.

**Comment by pnorman** [comment]
prometheus reports pg_database_size at 364GB, growing at 5.4 GB/day, so we'd need ~4TB for two years. I'd like at least a month of data to be more confident in predictions.

**Comment by tomhughes** [comment]
I make it (from https://prometheus.openstreetmap.org/d/EsDDqrLGk/prometheus?orgId=1&refresh=1m&from=now-7d&to=now) about 300Gb but agree on the growth rate - the absolute site is complicated by the saw tooth pattern as it compresses chunks of older data.

Note that currently there is no downsampling being done so we are preserving the full 15s resolution which I would not expect to be doing.

Support for automated downsampling is allegedly coming soon... Currently they suggest doing it via rewrite rules in prometheus at ingestion time but that doesn't seem very practical to me.

**Comment by Firefishy** [comment]
Growth rate seems to be around 5GB/day now. We have around 9 months spare capacity on [stormfly-03](https://hardware.openstreetmap.org/servers/stormfly-03.openstreetmap.org/)

We can add 960GB for ~[£100](https://www.ebay.co.uk/itm/195238364546). We can add upto 4x disks.
