### ISSUE TITLE
Decommission old Servers @ AMS

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#505]
There are a few old DL360 machines at AMS which still need to be wiped.

Machines being decommissioned and removed from DC:

- [ ] lockheed | (formerly thorn-01)
- [ ] thorn-02
- [ ] thorn-03
- [x] ramoth (powered down)
- [x] spike-01
- [x] spike-02
- [x] spike-03
- [x] ouroboros

**Comment by tomhughes** [comment]
To be more precise I believe that following are turned off but still present:

* spike-01
* spike-02
* spike-03
* ouroboros

Also still powered up but no longer in use:

* thorn-01
* thorn-02
* thorn-03

In addition there was another HP storage box or something that we took from Imperial but have never used, and ramoth which isn't an HP but isn't in use.

**Comment by Firefishy** [comment]
I will also de-rack / remove the following 

* lockheed | (formerly thorn-01)
* ramoth (powered down)

**Comment by Firefishy** [comment]
@pnorman @tomhughes ^^^ above machines ok to decommission?

**Comment by tomhughes** [comment]
Sure.

**Comment by Firefishy** [comment]
I am going to leave the thorn machines as spares. Rest have been removed from rack
