### ISSUE TITLE
Corrupt tiles at zoom level 17

### ISSUE THREAD

**Issue by magiwanders** [openstreetmap/operations#506]
Approximate Location: 45.716980 N - 9.355548 E

There are some broken tiles at zoom level 17 at the given coordinates and immediate vicinity (not all are included in the screenshot)
![corrupt tiles](https://user-images.githubusercontent.com/50774142/106741564-26bd7500-661c-11eb-9247-af2099060b01.png)

**Comment by tomhughes** [comment]
You're likely just seeing a mix of old and new tiles combined with a change in the data or style. Be patient and it will fix itself.

**Comment by tomhughes** [comment]
It seems to be fine for me at least but it will depend on what cache server you're hitting exactly what you see.

**Comment by magiwanders** [comment]
Thank you, I suspected about the caching but posted because it was for a few days like that (and still is as of now). I'll wait!

**Comment by tomhughes** [comment]
The. servers are this week because a new version of style was rolled out so they don't always have time to rerender everything.

In addition you appear to be using a third party site so you will be unable to force a cache flush - you may find using openstreetmap.org gives better results.

**Comment by mnalis** [comment]
Just to add some related information: when using openstreetmap.org map, the [tile status can be checked and tile rendering forced](https://wiki.openstreetmap.org/wiki/Slippy_Map#OpenStreetMap_.22Standard.22_tile_server)
