### ISSUE TITLE
Failed PSU in viserion

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#514]
Looks like a PSU failed in viserion a few weeks ago:

```
1e60 | 02/16/2021 | 23:46:57 | Power Unit #0x44 | Redundancy Lost | Asserted
```

IPMI shows one PSU as "redundancy lost" and the other one as "not readable".

**Comment by tomhughes** [comment]
This is a former tile cache that's currently unused - one for @hbogner anyway...

**Comment by hbogner** [comment]
PSU replaced
