### ISSUE TITLE
Certificate error uptime.openstreetmap.org

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#515]
In case https://uptime.openstreetmap.org/ is still a thing, there's currently some error about an invalid self signed certificate.

**Comment by tomhughes** [comment]
That's outside our direct control - it just points at a statuscake run site.

It's pretty hopeless anyway.

**Comment by tomhughes** [comment]
Apparently they changed the name of the CNAME target without telling us...

Fixed in https://github.com/openstreetmap/dns/commit/c27fc6e78efc57c9031e409999323e343c9de3b1.
