### ISSUE TITLE
No access to KVM at UCL Slough

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#516]
We no longer appear to have access to a KVM at slough. We should get our own small monitor. We already have a keyboard.

**Comment by Firefishy** [comment]
I did eventually find a KVM crash trolley, but is required a C14 to UK power plug which I wasn't able to find.

**Comment by pnorman** [comment]
Is this still an issue, or do they have crash carts now? If not, do we still need a monitor given we're moving stuff out of Slough?

**Comment by grischard** [comment]
Won't fix since we're slowly moving out. Linked issue #770
