### ISSUE TITLE
Migrate OTRS to Znuny

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#518]
We use OTRS 6 for support-like workflows, primarily for sysadmins, LWG, DWG, and MWG. When OTRS 7 came out it was closed source, with the promise that it would be open sourced in the future, lagging behind the closed-source versions. This promise never happened, and we need to find a long-term alternative to OTRS 6.

[OTOBO](https://otobo.de/en/) is one fork of OTRS 6 while [Znuny](https://www.znuny.org/en) is another. Looking at their pages, it sounds like Znuny is focused on maintaining OTRS 6, while OTOBO is doing more new stuff.

**Comment by pnorman** [comment]
My inclination is towards OTOBO, although I've not tested either one.

**Comment by Firefishy** [comment]
Looks like Debian 12+ now has znuny packaged https://packages.debian.org/bookworm-backports/znuny

Likely worth investigating that as an upgrade path option.

**Comment by pnorman** [comment]
I re-checked the two forks. otobo is still active and getting updates and znuny is now getting new features with znuny 7.0. So neither are obvious dead-ends.

**Comment by pnorman** [comment]
We'll be going with Znuny

**Comment by Firefishy** [comment]
First tiny PR to move us from OTRS to latest Znuny 6.0.x release: https://github.com/openstreetmap/chef/pull/655

**Comment by Firefishy** [comment]
I have been testing the Znuny debian package and how practical it is for us to move using it.

The debian package uses `dbconfig-common` for managing database and installs its own apache vhost. We need some custom config to work for our setup (eg: certificates and aliases).

**Comment by Firefishy** [comment]
We are now running Znuny, but the migration to latest 6.5 release is still pending.

**Comment by Firefishy** [comment]
PR: https://github.com/openstreetmap/chef/pull/658

**Comment by Firefishy** [comment]
I have tipped off CWG, LWG and MWG that OTRS will likely be updated in the next few days with some period of outage. I will likely move server at the same time.

**Comment by Firefishy** [comment]
OTRS now moved to server naga and migrated to [latest release of znuny from debian backports](https://packages.debian.org/bookworm-backports/otrs2).
