### ISSUE TITLE
Disk failure in stormfly-03

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#519]
```
=> ctrl slot=0 pd all show status

   physicaldrive 1I:1:1 (port 1I:box 1:bay 1, 0 GB): Failed
   physicaldrive 1I:1:2 (port 1I:box 1:bay 2, 960 GB): OK
   physicaldrive 1I:1:3 (port 1I:box 1:bay 3, 960 GB): OK
```

**Comment by Firefishy** [comment]
An SSD death... Disk hadn't been the healthiest for awhile.

**Comment by Firefishy** [comment]
Replacement has been ordered and shipped.
"HPE 960GB SAS 12G RI SFF SC DS SSD P06584-B21 P08608-001 P02763-001"

**Comment by Firefishy** [comment]
I have also for paranoia sake ordered 1 extra disk for stormfly-03 and another for stormfly-04.

**Comment by Firefishy** [comment]
Disk replaced.
