### ISSUE TITLE
Identify ISP for Dublin location

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#520]
- [x] Identify ISP
- [x] Get LOA
- [x] Get cross-connect

## Requirements
- Not Cogent
- 10 Gbps port
- A provider that blends multiple upstream connections

## T.B.D.
- Redundant port?
- What commit bandwidth?

**Comment by pnorman** [comment]
After talking to ISPs, a port that could fail over with something like VRRP would be fairly expensive, so I'm dropping it from the requirements. We have the required redundancy from multi-site connectivity

**Comment by pnorman** [comment]
ETA for recommendation is May 17th.

**Comment by pnorman** [comment]
Recommendation sent to the OWG

**Comment by pnorman** [comment]
Paperwork is being drawn up.

**Comment by Firefishy** [comment]
We will be going with http://he.net/

**Comment by grischard** [comment]
Paperwork signed and sent.

**Comment by grischard** [comment]
Can we ask them for their price for two or four ports for redundancy?

**Comment by pnorman** [comment]
Our port is connected to the ISP, we just need to do the site visit to install our equipment.
