### ISSUE TITLE
Plan new rendering server

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#521]
- [x] Decide specs
- [x] Get quote
- [x] Circulate quote for comment
- [x] Request pro-forma invoice
- [x] Send invoice to treasurer
- [x] Wait for server to be built and shipped
- [x] Notify academic computing club
- [x] Send networking cables to academic computing club

-----
We've budgeted for a new rendering server for somewhere outside of Dublin. The current plan is in a Swedish university, although Amsterdam is a fallback option.

## Disk usage
Disk usage is somewhat misleading on render servers, since the tile store will expand to fill available free space. Current disk usage on odin is 1TB for the database and 3TB for the store.

The 5 year estimate of DB size is 2TB which gives 2TB for the store if we stick to 4TB drives, which I think is okay.

**Comment by pnorman** [comment]
Asked for a quote for 2x render servers, and we decided to go up to 3x4TB to have a hot spare drive. One render server is for Umea, another for Dublin

**Comment by pnorman** [comment]
Rendering server status: Awaiting pro-forma and then payment. Due to component shortages it may not be done until after July 1st.

**Comment by pnorman** [comment]
Pro-forma sent to treasurer for payment.

**Comment by pnorman** [comment]
Quote 189243

1 x Delivery - Overnight
1 x Build and Full System Soak Test
1 x Supermicro Super Server 1124US-TNRP
2 x AMD EPYC™ 7453 DP/UP 28C/56T 2.75G 64M 225W SP3
16 x Supermicro Validated 16GB DDR4-3200 ECC Registered Memory Module
3 x 4TB Enterprise Class NVMe U.2
2 x 240GB Enterprise Class Solid State Drive
2 x Supermicro MCP-220-00187-0B
1 x 3 Years Return to Base Warranty

**Comment by pnorman** [comment]
Assigning to @Firefishy to order and send DAC cables

**Comment by Firefishy** [comment]
DAC cables have been sent and have been delivered to the University already.

**Comment by Firefishy** [comment]
Levererat den
17.08.2021 9:40

Levererat till
UMEAA, SE

Mottagen av
MORGAN C19

**Comment by Firefishy** [comment]
https://hardware.openstreetmap.org/servers/nidhogg.openstreetmap.org/ is up and running.
