### ISSUE TITLE
Proposals: What's the exact time for start/end?

### ISSUE THREAD

**Issue by tracker51** [openstreetmap/operations#522]
Hello,

Now that I'm writing this posting it's April 20, 2021,  about 12:30 UTC.  My question relates to the current proposal 

boundary=forestry(_compartment) relations.

On the related website, one can read the following text:

boundary=forestry(_compartment) relations
--
Voting (under way)
Penegal
boundary=forestry
 Tagging scheme for areas used for forestry
2020-12-27
2021-03-17
2021-04-06
2021-04-20

As to this it should still be possible to vote.  Am I right? Wouldn't it be useful to additionally give the exact time for start and end of proposals? Or is there an explanation anywhere which I haven't found?

Best regards

tracker51

**Comment by gravitystorm** [comment]
This is the issue tracker for the Operations Working Group, who deal with running the servers operated by the OSMF. This group has no involvement in tagging proposals.

I would suggest using the talk page for the tagging proposal that you are interested in, or by asking on the [tagging mailing list](https://lists.openstreetmap.org/listinfo/tagging).
