### ISSUE TITLE
Add subdomain and email for Nextcloud instance

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/operations#523]
The board contracted a [Nextcloud instance of cloud68.co](https://osmfiles.cloud68.co/) for the use of the OSMF. 

As per conversation on IRC we would like to ask for
* subdomain, like `files.osmfoundation.org` pointing to `78.47.246.206`.
* an email address (group) to add a few volunteers (from the LCCWG and FOSS Policy committee) who will help creating/deleting user accounts, looking that the storage quota won't get hit (within the first week, etc...)

Many thanks.

**Comment by xamanu** [comment]
Thanks, @tomhughes for adding the subdomain. Can you help me to set up the email?

**Comment by tomhughes** [comment]
You need @Firefishy for that really, and he's away this week.

I do have access to the Google console so I can try, but I have no idea what I'm doing with it...

**Comment by tomhughes** [comment]
You don't seem to have indicated who it needs to go to anyway?

**Comment by xamanu** [comment]
Thanks for looking into this! Just sent them to you in a direct message.

**Comment by xamanu** [comment]
It's all done. Thanks.
