### ISSUE TITLE
Purchase switches for DB4

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#526]
The following need to be selected and purchased

## Switches
We need two switches with 4x SFP for upstream and interconnect, and 48x 10Gbase-T for servers. They need redundant power, or an external redundant power unit
- [x] Decide switch models
- [x] Decide vendor
- [x] Purchase
- [ ] Open incoming shipment ticket with Equinix

## Cabling
We need fiber optic cables (DAC) for interconnect, and fiber optic patch cables (LC UPC to LC UPC Duplex) for connecting to the patch panel.
- [x] Purchase
- [ ] Open incoming shipment ticket with Equinix

## SFP modules
We need fibre optic modules (10G Modules LR)
- [x] Purchase
- [ ] Open incoming shipment ticket with Equinix

**Comment by Firefishy** [comment]
Example switches we thinking about:
* https://it-market.com/en/switches/gigabit/juniper/ex4300-48mp?number=164880
* https://it-market.com/en/switches/gigabit/cisco/sg550xg-48t-k9-na?number=145148
* https://www.ebay.co.uk/itm/264476030649

**Comment by grischard** [comment]
Two Juniper EX4300s delivered at Grant's, eight 10G modules ordered but not delivered yet.

**Comment by Firefishy** [comment]
The 8x fibre modules have arrived too.

**Comment by Firefishy** [comment]
I have ordered 2x 40Gb DAC cables.
