### ISSUE TITLE
Get cabling and accessories for DB4 install

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#529]
We need
- [x] cage nuts 
- [x] network cables
- [x] power cables
- [x] cable ties
- [x] labels / label printer
- [x] rack shelf
- [x] bins to store stuff in
- [ ] racking hand gloves

It would be nice to have
- [x] IEC to UK power socket cable
- [ ] IEC to EU power socket cable

**Comment by Firefishy** [comment]
Power Cables:
https://www.apc.com/shop/uk/en/products/Power-Cord-Kit-6-ea-Locking-C13-TO-C14-90-Degree-0-6m/P-AP8702R-WW
https://www.apc.com/shop/uk/en/products/Power-Cord-Kit-6-ea-Locking-C13-to-C14-0-6m/P-AP8702S-WW

**Comment by pnorman** [comment]
to-do: split some of the items in this ticket to their own tickets

**Comment by grischard** [comment]
Network cables:

- Category: cat6, cat6a, cat7?
- Two colours? (switch A, switch B)
- Fiber for 10G (two colours?)

**Comment by pnorman** [comment]
Three colours of cat6a. One for switch A, one for switch B, and one for OOB.

**Comment by grischard** [comment]
You want the OOB to only go to one switch?

**Comment by pnorman** [comment]
In AM6 we sent half the OOB to one switch, half the OOB to the other.
