### ISSUE TITLE
Selection of mirror resulting in slow mirror?

### ISSUE THREAD

**Issue by msetzerii** [openstreetmap/operations#53]
I was just downloading the new LibreOffice, and it showed a download time of 2 hours. Cancelled the download, and the manually selected a US location, and got the file in 2 minutes. Seems that Guam IP see AU as being close, but very slow connections.

**Comment by tomhughes** [comment]
Whilst I'm sure that's very interesting to somebody I'm not sure what it has to do with OpenStreetMap?

**Comment by Firefishy** [comment]
Closing. This is the OpenStreetMap operations ticket repo, we are not related to LibreOffice at all.
