### ISSUE TITLE
Migrate AMS network to HEnet

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#532]
After Dublin is live, we should migrate AMS away from Cogent.

Placeholder ticket. Fill out more details once known.

**Comment by pnorman** [comment]
Plan is to get quotes for a 10Gbps connection

**Comment by grischard** [comment]
Cogent being a joke (#632) raises the priority on this a bit.

**Comment by grischard** [comment]
Merging into duplicate #260. HE isn't in our datacenter, and the detail is in the other ticket.
