### ISSUE TITLE
"Fatal exception" when accessing wiki page

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#533]
When navigating to https://wiki.openstreetmap.org/wiki/Template:Languages/div I would expect to see some wiki page. Instead I get 

`[14e6405d969a03b492986979] 2021-05-14 16:27:16: Fatal exception of type "Wikimedia\Rdbms\DBQueryError"`

I can see the history of the page and I open the editor with the page loaded, but I can not submit changes or view any version of the page. No other page seems to be effected. The issue was [first reported on 26 April 2021 on Talk:Wiki](https://wiki.openstreetmap.org/w/index.php?title=Talk:Wiki&oldid=2150625#Template:Languages.2Fdiv_Mediawiki_bug).

**Comment by mmd-osm** [comment]
When I open the page in [edit mode](https://wiki.openstreetmap.org/w/index.php?title=Template:Languages/div&action=edit), and then hit "preview", I'm getting the same error. However, the error no longer occurs once I remove one of the three languages underneath _Devanagari abugidas_, and then hit preview again:

```
{{LanguageLink|{{{n}}}|mr|{{{p}}}}} 
```

**Comment by AndrewHain** [comment]
As https://wiki.openstreetmap.org/wiki/Template:Languages/div and https://wiki.openstreetmap.org/wiki/Template:LanguagesLink are no longer used since Minh rewrote https://wiki.openstreetmap.org/wiki/Template:Languages and the wiki has never had any pages in Marathi the only real concern is what the underlying problem is. Has this been reported on the Mediawiki bug tracker?

**Comment by tomhughes** [comment]
What on earth good do you will think that will do? Is there any reason to think this is a mediawiki bug rather than a simple database corruption of some sort? Given it only affects one page a database issue seems more likely to me.

**Comment by mmd-osm** [comment]
Well, I just removed that part on the Wiki page, as it's reportedly unused anyway. The page can be accessed again now: https://wiki.openstreetmap.org/wiki/Template:Languages/div
That's what I was hoping to see after the preview was also successful.

If there's some need to analyse the underlying issue, some previous version might still do to trigger the error: https://wiki.openstreetmap.org/w/index.php?title=Template:Languages/div&oldid=1705035

**Comment by AndrewHain** [comment]
You get the error when you type {{#language:_xx_|mr}} or {{#language:_xx_|tl}} to get the name of a language in Marathi or Tagalog at https://wiki.openstreetmap.org/wiki/Special:ExpandTemplates.

**Comment by 1ec5** [comment]
> You get the error when you type {{#language:_xx_|mr}} or {{#language:_xx_|tl}} to get the name of a language in Marathi or Tagalog at https://wiki.openstreetmap.org/wiki/Special:ExpandTemplates.

Following up in #602.
