### ISSUE TITLE
Replace failed disk in thorn-05

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#535]
```
/dev/sda: (Smart Array P410i) RAID 6 Volume 0 status: Using interim recovery mode.
  Failed drives:
         connector 1I box 1 bay 2                 HP      EG0146FAWHU                          6SD35JSS0000B141KALJ     HPDG
```

**Comment by tomhughes** [comment]
This is the disk that was replaced in October 2020! #414

**Comment by pnorman** [comment]
It's a HP G7 with no roles, should we scrap the machine?

**Comment by tomhughes** [comment]
Yes all those machines at Bytemark are likely to be scrapped.

**Comment by pnorman** [comment]
The machine is powered down in preparation for scrapping, so there's no need to replace the drive.
