### ISSUE TITLE
Providing an offline-version of the Wiki

### ISSUE THREAD

**Issue by kmpoppe** [openstreetmap/operations#536]
In the German-speaking Telegram group (OSM_de) a user [asked](https://t.me/OSM_de/53598), if there was an offline version of the wiki because he didn't have mobile data packages on his phone.

After some digging, I found out that [Kiwix](https://www.kiwix.org) (non-profit, open source software) had a March 2021 version on the OSM Wiki in their ZIMFarm as a `.zim`-file that can be opened with the readers they provide for Windows, MacOS, *UX, and Android - and I could really work with that.

Creating said `.zim`-files takes time and produces data transfer which would not be necessary if it would be created with bot-access to the API on the same machine as the wiki and provided alongside the XML-dump on wiki.openstreetmap.org/dump.

Their configuration for the OSM wiki can be seen [here](https://farm.openzim.org/recipes/osm-wiki/config). It seems they use a docker-version of [mwoffliner](https://github.com/openzim/mwoffliner) to get the copy going. This should be possible in the OSM server infrastructure as well.

After talking to a co-founder of Kiwix, they would be more than willing to save a copy of the OSM Wiki in their farm for their users to access when it was created "somewhere else" (i.e. OSM servers) and provided for download.

I'm therefore proposing to dedicate a service within the OSM infrastructure to regularly (once a week) creating an offline version of the wiki and making it available for download.

I'd be very happy to hear everyone's thoughts on my idea. Thanks!

Edit: If it's decided to not being a workable solution, we should check if we can provide a way to access to the Wiki's API for Kiwix's farm to create the offline version themselves reliable, because currently (for three months now) the creation fails due to API limits.

Kai

**Comment by mmd-osm** [comment]
A wiki dump is already available here:  https://wiki.openstreetmap.org/dump/

**Comment by kmpoppe** [comment]
Well yes, the dump is there. Problem is: There's no reader app for the dump. So you can download the file to your phone but then you're left with nothing but a database file and whole lot of files/images out of context.

Creating the zim file would create one file that has all structural information integrated that makes it possible to view the data with the reader I linked without any more additional work needing to be done on the user's side.

Kai

**Comment by mmd-osm** [comment]
> we should check if we can provide a way to access to the Wiki's API for Kiwix's farm to create the offline version themselves reliable, because currently (for three months now) the creation fails due to API limits.

that’s what the dump is good for…

**Comment by matkoniecz** [comment]
> There's no reader app for the dump

Is it in some way unusual? Or is it a regular Wikimedia dump can be processed by anyone who wants to provide offline-version of wiki?

If you want to make such project with offline version of OSM Wiki - is dump format an actual blocker?

**Comment by matkoniecz** [comment]
> Edit: If it's decided to not being a workable solution, we should check if we can provide a way to access to the Wiki's API for Kiwix's farm to create the offline version themselves reliable, because currently (for three months now) the creation fails due to API limits.

Is limit present on Kiwix or on OSM Wiki side? Which exact limit is a problem? Is Kiwix able to work with a standard Wikimedia dump file?

**Comment by kmpoppe** [comment]
> Well, that could be a good use for the wiki dump. Creating a zim file in the first place may likely be out of scope for osm infrastructure.

If it's out of scope then nothing remains but finding a way to create the zim file from the dump "offline" (without the use of the API) - which seems to be something either noone has tried yet - I'm yet to find a working concept to do this.

> Is limit present on Kiwix or on OSM Wiki side? Which exact limit is a problem? Is Kiwix able to work with a standard Wikimedia dump file?

@matkoniecz The Kiwix ZIMFarm, that is currently trying to create a ZIM file by accessing the API through mwoffliner get shut down with a generic API message from the OSM wiki side, shown [here](https://farm.openzim.org/pipeline/728cc38399f46f34a6c37a06/debug) under `Scrapper stderr`.

@matkoniecz @mmd-osm I will check back with the mwoffliner team if there's a way to use the dump. No need to bother.

**Comment by kmpoppe** [comment]
Some more investigation lead nowhere, sadly. There are a handful of tools, yet all require API and frontend access to do their job.

If, as @mmd-osm pointed out, there's no reason the start the creation of the ZIM file within the OSM farm, I will happily go about finding another place to provide the capacity and computing power.

The API limit problem remains. Can anyone guess what happened about 2-3 months ago, because before the ZIMfarm recipe worked? Is there a way to whitelist IPs from said limits?

Kai

**Comment by matkoniecz** [comment]
Are you sure that it is about API limit? My scrip had no problem fetching basically entire wiki - it just sleeps and retries on error.

`Failed to run mwoffliner after [3254s]`  may be API limit on OSM Wiki side, may be also something else.

I would start from implementing (or requesting) more clear errors, as this one fails to identify what went wrong.

**Comment by mmd-osm** [comment]
By the way, what kind of information on the OSM wiki would you need on your mobile device in an offline scenario?  Is this somehow mapping related, and if so, in what way? It would be good to understand the user requirement better before discussing technical solution to a presumably niche requirement.

**Comment by mnalis** [comment]
@mmd-osm I don't know about the OP, but I would be interested (map-related, for example creating POIs / adding additional tags in OsmAnd) at least in all pages describing accepted keys/tags  (although a few other would be nice too, like country and linked pages etc.)

**Comment by kmpoppe** [comment]
@matkoniecz I will get over to the mwoffliner Repo and see if I can get any meaningful information as to what exactly goes wrong. I can, however, confirm that the mwoffliner in the ZIMFarm fails with the same error as a dock instace that runs on my PC - just at slightly different pages - this can also be seen in the different tries from ZIMFarm. The error is always the same, just the point in processing the pages where it occurs is different.

@mmd-osm Pretty much like @mnalis said - having the Wiki at hand offline when you are required to do offline edits due to shortage of mobile data (or lack of coverage) is very helpful. Also, something not discussed as of yet was, that Kiwix provides [so called Hotspots](https://www.kiwix.org/en/downloads/kiwix-hotspot/) for developing countries. They use Wikipedia and other offline Wiki images to bring these information to people where internet coverage is less than wide spread. They are considering adding an offline version of The Map (with rendering server at all, I'm currently talking to them about that).

Kai

**Comment by mmd-osm** [comment]
> Some more investigation lead nowhere, sadly. There are a handful of tools, yet all require API and frontend access to do their job.

Did they also explore setting up their own Mediawiki instance, populate it using the OSM wiki dump,, and then run their API calls against their own Wiki instance?

**Comment by kmpoppe** [comment]
> Did they also explore setting up their own Mediawiki instance, populate it using the OSM wiki dump,, and then run their API calls against their own Wiki instance?

In this case, "they" would be me. Kiwix provides the ZIMfarm free of charge for users and tries to provide as many ZIMs as possible which implies that as much automation as possible would be used.

I quickly tried the manual population of the dump into a new installation on my local machine which also failed.

**Comment by mmd-osm** [comment]
Thanks! If we assume for a moment that mwoffliner itself is working on your own Mediawiki instance, then this issue would be a matter of setting up a new Mediawiki instance using the existing OSM Wiki dump. Either there's some documentation issue, or the dump itself isn't working as expected, because nobody has tried it before.

**Comment by mmd-osm** [comment]
I'm running  `php importDump.php --conf ../LocalSettings.php ../dump.xml.gz --username-prefix=""` according to https://www.mediawiki.org/wiki/Manual:ImportDump.php right now, and it seems to make some progress. I can even see some OSM content showing up in my Mediawiki instance.

**Comment by kmpoppe** [comment]
@mmd-osm I had tried using MWDumper as described in the Manual, but that kept throwing different errors as to the database structure, which I can only presume is an inconsistency between the two.

I'll try using the slower importDump script and then check if mwoffliner works as nintended :-)

Thanks!

K

**Comment by mmd-osm** [comment]
MWDumper seems to no longer work on more recent Mediawiki versions. https://www.mediawiki.org/wiki/Manual:MWDumper notes: "_Apparently, it can't be used to import into MediaWiki 1.31 or later._"

The main disadvantage I see with importDump is that it's really slow. I haven't investigated if there are ways to speed it up. Unfortunately, it also tries to reconstruct every single version of a wiki page, which is probably not what you need.

**Comment by kmpoppe** [comment]
Well.

Importing OSM into a local installation -> 5 hours, ~3000 articles. With 60000+ articles in the Wiki it's just unrealistic as a proper functioning solution.

I haven't heard back from mwoffliner yet as to what the problem actually is, sadly.

So for the time being I cannot provide any sensible means of creating a ZIM file :-(

**Comment by mmd-osm** [comment]
Reaching out to @1ec5, @tigerfell: do you happen to know anyone that might support @kmpoppe to import an OSM wiki dump into a plain vanilla Mediawiki instance? Existing scripts either don't work at all or show abysmal performance issues. 

Should we move this discussion to https://wiki.openstreetmap.org/wiki/Talk:Wiki?

**Comment by Tigerfell** [comment]
Kmpoppe brought this up at [Talk:Wiki](https://wiki.openstreetmap.org/wiki/Talk:Wiki/Archive_8#Providing_an_offline-version_of_the_Wiki) already. I directed him to this place, because it seemed to be a technical question. 

> do you happen to know anyone that might support @kmpoppe to import an OSM wiki dump into a plain vanilla Mediawiki instance? 

I would suggest some MediaWiki IRC channel. There seems to be a [manual page](https://www.mediawiki.org/wiki/Manual:Importing_XML_dumps), too. Unfortunately, the error messages are not really helpful. It might be related to Parasoid (search result when entering the error message). 

Two notes on the speed issue

- The [linked report](https://farm.openzim.org/pipeline/728cc38399f46f34a6c37a06/debug) indicates that there is a speed parameter set to 0.1. 
- I would try to filter the Kiwix input first: take the most recent page version only, filter for page names starting with "Key:" or "Tag:", try out the process with a few pages first to test the setup.

**Comment by kmpoppe** [comment]
> Two notes on the speed issue
> 
>     * The [linked report](https://farm.openzim.org/pipeline/728cc38399f46f34a6c37a06/debug) indicates that there is a speed parameter set to 0.1.

Yes. That parameter is _explicitly_ there to prevent what's happening here, that mwoffliner gets denied further access to the API because it sends too many requests in a short amount of time. Sadly, the speed cannot be set lower than 0.1.

>     * I would try to filter the Kiwix input first: take the most recent page version only, filter for page names starting with "Key:" or "Tag:", try out the process with a few pages first to test the setup.

I might try that at a later date, but it won't be a workable solution. When you look at the start page, there's not one link that goes directly to Tag: or Key: - I see what you're trying to tell me here, but in my eyes it's just not a workaround worth exploring.

I am still wondering why on earth the mwoffliner process is failing now after having run for quite some time before. Who might know what changed in the OSM wiki's settings about 3 months ago? @pnorman?

**Comment by matkoniecz** [comment]
> Sadly, the speed cannot be set lower than 0.1.

Sounds like a root cause that should be fixable.

**Comment by kmpoppe** [comment]
@Firefishy, are you responsible for [this tweet](https://twitter.com/OSM_Tech/status/1555512517119688704)? It seems that whatever happened now stops mwoffliner from keeling over almost instantly and we might be looking at an up-to-date version of the offline wiki again! 🥳

**Comment by Firefishy** [comment]
@kmpoppe Yes, I am to blame ;-)

If you still think it is worth it and not a duplication of effort, I will still action https://github.com/openstreetmap/operations/issues/609

**Comment by kmpoppe** [comment]
Sadly, I was a bit premature in my hopes as mwoffline died after 2439 seconds with the same error as before. So, if you're on #609 ... it would be **fabulous** ... A direct ZIM file from the source was my secret wish all along ;-)

**Comment by Firefishy** [comment]
I found the timeout issue. Fixed in https://github.com/openstreetmap/chef/commit/912efbc1f99141d3e1540fc127496f80c81b310e

**Comment by kmpoppe** [comment]
Oh nice. I shall be trying it again, shouldn't I?

**Comment by Firefishy** [comment]
Yes by all means try again.

**Comment by kmpoppe** [comment]
Nope, same error as before, albeit later in the process: https://farm.openzim.org/pipeline/eabc002ba3ee7c3a1c32ee26/debug

**Comment by mmd-osm** [comment]
I don't seem to be able to open the page mentioned in the log file: https://wiki.openstreetmap.org/wiki/RU:%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F/%D0%93%D0%BE%D0%BB%D0%BE%D1%81%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F/%D0%A1%D0%BE%D0%B2%D0%B5%D1%82_OSM_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F

It's returning some internal error.

**Comment by matkoniecz** [comment]
That is 

> attempt to save edit adding "{{#tag:osmtaginfo||key=|value=}}" on OSM wiki ends with "Fatal exception of type "Error""

#216 

Fixed in https://wiki.openstreetmap.org/w/index.php?title=RU:%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F/%D0%93%D0%BE%D0%BB%D0%BE%D1%81%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F/%D0%A1%D0%BE%D0%B2%D0%B5%D1%82_OSM_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F&diff=2367776&oldid=1895805

**Comment by matkoniecz** [comment]
@kmpoppe This specific error should be now gone.

**Comment by Firefishy** [comment]
@kmpoppe Please could you try another run. It worked for me locally.

**Comment by kmpoppe** [comment]
@Firefishy I'm currently running mwoffliner to check if everything works. Meanwhile, for some reason, the ZIMFarm's runs also ran correctly in November and December (although they failed in transferring the file, but I'll have to talk to the guys there what happened).

Meanwhile I put up this section in the Wiki: https://wiki.openstreetmap.org/wiki/Using_OpenStreetMap_offline#Using_the_Wiki_offline

**Comment by kmpoppe** [comment]
@Firefishy as expected, the `nopic` run finished after around three days and seems to have without any failures. Currently downloading the file to check the number of articles and such.
`maxi` run is at 10%. Let's see if it finishes.
