### ISSUE TITLE
Get new planet server for DB4

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#537]
- [x] Decide specs
- [x] Get quote
- [x] Circulate quote for comment
- [x] Request pro-forma invoice
- [x] Send invoice to treasurer
- [x] Wait for server to be built and shipped
- [x] Give vendor name and phone number for shipping
- [ ] Open incoming shipment ticket with Equinix

-----

From the budget

> The planet server powers a primary service and is due for replacement. There are two options — replace it with a similar server, or move long-term planet storage to a commercial object store. If we go with the second option we anticipate being able to secure sponsored hosting from a cloud provider for this. We are evaluating the merits of the two options. The first option has a capital cost of € 15 000, the second has a capital cost of € 5 000 and if not sponsored, an estimated monthly cost of € 1 500

Because the object store option requires development work and we need a planet server at DB4 immediately, we decided to go with the similar server replacement at a higher cost.

**Comment by pnorman** [comment]
Quote number: 189589

Consists of
1 x Delivery - Pallet Overnight
1 x Server Build
1 x Supermicro Ultra SuperServer 120U-TNR
2 x Intel ICX-SP 4310 12C/24T 2.1G 18M
16 x 16GB DDR4-3200 2Rx8 ECC REG DIMM,RoHS
2 x Enterprise Class 240GB SATA Solid State Drive
1 x AOC-URG4N4-I2XT-P
7 x 7.68TB Enterprise Class SAS Solid State Drive (1DWPD)
1 x Supermicro 8-port 12Gb/s SAS - RAID 0,1,10,5,6,50,60
1 x 3 Years Return to Base Warranty

**Comment by garcYj-fybgeg-8nebqu** [comment]
> - [x] Decide specs
> 
> - [x] Get quote
> 
> - [x] Circulate quote for comment
> 
> - [x] Request pro-forma invoice
> 
> - [x] Send invoice to treasurer
> 
> - [x] Wait for server to be built and shipped
> 
> - [x] Give vendor name and phone number for shipping
> 
> - [ ] Open incoming shipment ticket with Equinix
> 
> 
> 
> -----
> 
> 
> 
> From the budget
> 
> 
> 
> > The planet server powers a primary service and is due for replacement. There are two options — replace it with a similar server, or move long-term planet storage to a commercial object store. If we go with the second option we anticipate being able to secure sponsored hosting from a cloud provider for this. We are evaluating the merits of the two options. The first option has a capital cost of € 15 000, the second has a capital cost of € 5 000 and if not sponsored, an estimated monthly cost of € 1 500
> 
> 
> 
> Because the object store option requires development work and we need a planet server at DB4 immediately, we decided to go with the similar server replacement at a higher cost.

**Comment by tomhughes** [comment]
This has arrived and been installed as `horntail`.
