### ISSUE TITLE
Get new API database server for DB4

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#538]
- [x] Decide specs
- [x] Get quote
- [x] Circulate quote for comment
- [x] Request pro-forma invoice
- [x] Send invoice to treasurer
- [x] Wait for server to be built and shipped
- [ ] Open incoming shipment ticket with Equinix

-----

### Disk
Because snap hasn't been running for long enough to get good historic data usage, I've taken the numbers from karm. I could compare across servers, but that's more of a pain.

Current disk usage is 12.9 TB, with 13% growth over the last year. Forecasting the same growth rate for 5 years gives us 21TB with no buffer. In practice we'll have the buffer for another 2.5% growth with 3840GB drives, or more with 4000GB ones.

We set these up in RAID6 and have decided to go with one hot spare, so we're looking at one of
- 9 3840GB or 4000GB drives
- 6 7680GB or 8000TB drives

### CPU
CPU is not a limiting factor in our API database servers

### RAM
It's hard to predict RAM requirements, since more RAM will always improve read performance. snap has 512GiB of RAM. We could either go with the same, or add more.

_Originally posted by @pnorman in https://github.com/openstreetmap/operations/issues/528#issuecomment-842677008_

**Comment by pnorman** [comment]
Quote 189589

1 x Delivery - Pallet Overnight
1 x Server Build
1 x Supermicro Ultra SuperServer 120U-TNR
2 x Intel ICX-SP 4310 12C/24T 2.1G 18M
16 x 16GB DDR4-3200 2Rx8 ECC REG DIMM,RoHS
2 x Enterprise Class 240GB SATA Solid State Drive
1 x AOC-URG4N4-I2XT-P
7 x 7.68TB Enterprise Class SAS Solid State Drive (1DWPD)
1 x Supermicro 8-port 12Gb/s SAS - RAID 0,1,10,5,6,50,60
1 x 3 Years Return to Base Warranty

**Comment by pnorman** [comment]
Quote 190430

**Comment by tomhughes** [comment]
This has arrived and been installed as `snap-03`.
