### ISSUE TITLE
Town name displayed inconsistenly in adjacent tiles

### ISSUE THREAD

**Issue by pols12** [openstreetmap/operations#539]
Hello,
Please look at "Le Thillot, Vosges, France" city at level-12 zoom: https://www.openstreetmap.org/#map=12/47.8655/6.7408
The name “Le Thillot” displays accros 2 distinct tiles: https://tile.openstreetmap.org/12/2124/1425.png and https://tile.openstreetmap.org/12/2125/1425.png
Issue: it is bigger on first tile than on the other one.
When I refresh the page (resetting cache, with Ctrl+Shift+R), it may be the opposite (left tile becomes bigger than right tile) or be fixed (same font size on both tiles).

**Comment by tomhughes** [comment]
Well it's certainly not an issue for the web site repository but I doubt it's a style issue either.

In fact I don't see any difference myself so it's probably just a transient caching issue that will go away once the rendering catches up - you are probably seeing two tiles of different ages.

**Comment by tomhughes** [comment]
Note that even a force reload doesn't guarantee a freshly rendered tiles because if the render server you hit is busy it will prioritise rendering of missing tiles over re-rendering of out of date ones and may return an out of date tile even for a force reload.

**Comment by pols12** [comment]
> In fact I don't see any difference myself so it's probably just a transient caching issue that will go away once the rendering catches up - you are probably seeing two tiles of different ages.

So, If I re-check in 1 week, I should not meet this bug anymore, isn’t it?

**Comment by tomhughes** [comment]
Well I can't guarantee anything but quite likely yes.

The output of https://tile.openstreetmap.org/cgi-bin/debug would help us know exactly what servers you are reaching which might let us say more.

**Comment by nrenner** [comment]
> Please look at "Le Thillot, Vosges, France" city at level-12 zoom: https://www.openstreetmap.org/#map=12/47.8655/6.7408

Zoom levels 0-12 are only rendered once a month, on the last Sunday.

> When I refresh the page (resetting cache, with Ctrl+Shift+R), it may be the opposite (left tile becomes bigger than right tile) or be fixed (same font size on both tiles).

This is most likely because of load balancing between two servers for each tile request, so tiles are mixed from different servers for each call. You can see this by reloading the debug page multiple times or by looking at the response header `x-tilerender` in the browser devtools Network tab (in Chrome/Chromium you can [add custom headers](https://developer.chrome.com/docs/devtools/network/reference/#custom-columns) to the request table).

The only server that still has the bigger font is "albi" ("ysera" doesn't respond). Looking at the metatile status, is seems low zoom tiles haven't been updated for a while on "albi":

https://albi.openstreetmap.org/12/2124/1425.png/status
`Last rendered at Sun Jan 31 02:19:26 2021.`

**Comment by pols12** [comment]
Thanks for your investigation. 🙂

Indeed, big-font tiles come from albi. Given the pretty-old last update, should the tiles not be re-rendered to avoid this kind of issues?
There was several “last Sunday of the month” since 2021-01-31: so does this minor issue not reveal a bigger one about automatic tile update?

**Comment by tomhughes** [comment]
I've just started a render on it although the logs seem to say one ran a few weeks ago.

**Comment by pols12** [comment]
Albi was down for a while, but it is well working now, and the font is now consistent with other tile server.

So this is definitely fixed, thank you both for your time! 🙂

**Comment by tomhughes** [comment]
Yes I think I have managed to re-render everything now but it took some effort - fundamentally I don't think machine has enough memory to cope with the low zoom render any more :-(

**Comment by HolgerJeromin** [comment]
Can we distribute the few low zoom files from other rendering servers?
But yes this will be more complicated to setup.

**Comment by tomhughes** [comment]
Well that server is currently specifically tasked as a low zoom server because it's not very powerful!
