### ISSUE TITLE
Request: please put Nabble email messages to Italian OSM mailing list in white list

### ISSUE THREAD

**Issue by aborruso** [openstreetmap/operations#541]
Hi,
I'm Andrea, I [have created](http://gis.19327.n8.nabble.com/Clone-di-questa-mailing-list-td5372281.html) in 2008 a Nabble clone of the [Italian OSM mailing list](https://lists.openstreetmap.org/pipermail/talk-it/).

It still works, but only the archiving part: it is no longer possible to write from the Nabble web interface.

Many of the Italian users love Nabble, they find it very handy and would like to be able to use it also in writing.
But it is not possible to do this, because OSM server that receives email messages sent via Nabble classify these as spam.
Here is an example of a message sent by me, blocked by spamassassin:

> This is the mail system at host n8.nabble.com.
> 
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.
> 
>   The mail system
> 
> <talk-it@openstreetmap.org>: host a.mx.openstreetmap.org[212.110.172.32] said:
>     550 This message scored 6.2 SpamAssassin points. (in reply to end of DATA
>     command)

I know, Nabble may be closed soon, but it still works and it is still very popular in a lot of OSM communities [1] and all major OSGeo Software Projects mailing lists [2].
In many of these it is also possible to write from Nabble GUI.

This issue to ask you to put in white list the emails that OSM mailing list receives from Nabble, so that they are no longer marked as spam and blocked.

Thank you

[1] http://gis.19327.n8.nabble.com/Local-Discussion-Groups-f5281959.html
[2] http://osgeo-org.1560.x6.nabble.com/OSGeo-Software-Projects-f3741872.html

**Comment by tomhughes** [comment]
There is no "white list" for us to add you to.

Frankly if they're scoring 6.5 they're doing something horribly wrong.

**Comment by tomhughes** [comment]
I can't even see that rejection in our logs - is that from today?

**Comment by aborruso** [comment]
hi @tomhughes I just sent a new message and I got this

> This is the mail system at host n8.nabble.com.
> 
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.
> 
>  The mail system
> 
> <talk-it@openstreetmap.org>: host a.mx.openstreetmap.org[212.110.172.32] said:
>     550 This message scored 6.7 SpamAssassin points. (in reply to end of DATA
>     command)

thank you

**Comment by aborruso** [comment]
> hi @tomhughes I just sent a new message and I got this

The subject is "Un test di verifica"

**Comment by tomhughes** [comment]
I think I found the original now - it was ten days ago! Here's the log from the spam scanner:

```
Jun  8 19:52:52 shenron spamd[24032]: spamd: connection from 127.0.0.1 [127.0.0.1]:38290 to port 783, fd 6
Jun  8 19:52:52 shenron spamd[24032]: spamd: checking message <1623181970055-0.post@n8.nabble.com> for nobody:116
Jun  8 19:52:58 shenron spamd[24032]: spamd: identified spam (6.2/5.0) for nobody:116 in 6.2 seconds, 1407 bytes.
Jun  8 19:52:58 shenron spamd[24032]: spamd: result: Y 6 - AWL,BAYES_50,DKIM_ADSP_CUSTOM_MED,FORGED_GMAIL_RCVD,FREEMAIL_FROM,NML_ADSP_CUSTOM_MED,SPOOFED_FREEMAIL,SPOOF_GMAIL_MID,T_SPF_HELO_TEMPERROR,T_SPF_TEMPERROR,URIBL_BLOCKED scantime=6.2,size=1407,user=nobody,uid=116,required_score=5.0,rhost=127.0.0.1,raddr=127.0.0.1,rport=38290,mid=<1623181970055-0.post@n8.nabble.com>,bayes=0.499400,autolearn=no autolearn_force=no
```

The main problem appears to be that nabble is sending email as you, using your gmail address, so it violates the SPF policy that google publish about who is allowed to send email from gmail.com addresses and is also won't have a valid DKIM signature.

**Comment by aborruso** [comment]
@tomhughes thank you

I think we cannot change anything in nabble. 
Could you add some spamassassin rule that adds an exception, and that gives the green light?

**Comment by tomhughes** [comment]
No, we're not going to add a rule that whitelists faking of gmail addresses!

That's even if I had the faintest clue how to do so, which I don't.

**Comment by aborruso** [comment]
@thomersch ok

I do not know how to nabble works. Probably it works always in this way, because the user that sends the email to the mailing list  is me, not nabble.

My proposal is not to enable fake sender, but to map  all emails that come from OSM italy nabble and apply only to these a green card.

If that's not possible, I understand.

Thanks for your time

**Comment by grischard** [comment]
I don't see any criteria we could reliably use to distinguish that an email comes from the OSM Italy nabble, unfortunately.

Do you want to come and help out with #377 to provide something even nicer than nabble?

**Comment by tomhughes** [comment]
Well fundamentally what nabble is doing is faking the sender, at least relative to the policies that gmail (and many other sources including us) publish about who is allowed to send email using their domain.

Try it with a yahoo address and many sites would just reject the email outright because they publish a DMARC policy telling people reject all mail that fails SPF or DKIM tests.

Basically what nabble are doing is just going to get less and less reliable - to offer a reliable posting interface they would probably have to give people mail aliases in their own domain, or at least use an address in that domain as the from address with just a reply-to for the real sender in much the same way as our lists rewrite the from address for users where this is likely to be a problem.

**Comment by mnalis** [comment]
@aborruso tomhughes is correct, your nabble server would need to implement some sort of [VERP](https://en.wikipedia.org/wiki/Variable_envelope_return_path) (like [SRS](https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme) does for mail forwarding) in order to continue sending e-mails claiming to be from foreign domains, or it will be classified as spam and rejected.

(Unfortunately I have no experience with nabble administration, but above links might give you pointers for searching, if you want to try if it is possible and how hard it would be)

**Comment by aborruso** [comment]
@mnalis I have no nabble server, I'm only a nabble user: as user I can create copy of mailman mailing lists. I cannot change any server settings.

There is no doubt that the settings that nabble uses are not good. I tried to insist because there is interest from users to be able to use it in writing, and because it looks like it can be enabled somehow.
In a lot of [OSGeo mailing lists](http://osgeo-org.1560.x6.nabble.com/) the messages sent from nabble spaces, with the same settings of OSM nabble, are delivered to the mailing list. Some examples:

- gdal-dev (the message in [mailing list](https://lists.osgeo.org/pipermail/gdal-dev/2021-June/054316.html) and in [nabble](http://osgeo-org.1560.x6.nabble.com/gdal-dev-LJPEG-Support-for-GDAL-tp5488769.html))

![image](https://user-images.githubusercontent.com/30607/122634563-227f8900-d0df-11eb-88a3-fb757bcf9ae3.png)

- QGIS-Developer (the message in [mailing list](https://lists.osgeo.org/pipermail/qgis-developer/2021-June/063708.html) and in [nabble](http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-It-s-time-to-contribute-to-the-Changelog-for-QGIS-3-20-tp5488144p5488173.html))

![image](https://user-images.githubusercontent.com/30607/122634600-5f4b8000-d0df-11eb-8add-74e92367cea7.png)


This message, just to add clarity, because I've probably created some confusion. I'm sorry.

Thank you

**Comment by mnalis** [comment]
@aborruso in that case, I don't see many options: 

- you can look at https://github.com/openstreetmap/operations/issues/377 as others have suggested to see about alternatives that might be implemented - perhaps they might be good enough fit (if/when they get implemented)
- you can try to get help at http://support.nabble.com/ (but as they have announced shutting down, I wouldn't be very optimistic) 
- you can setup your own server and instance of nabble (or pay someone to do it for you), and then switch over
- you (and other users that want to continue using nabble.com) can try to use different e-mail from e-mail providers which do not setup SPF / DKIM / DMARC records, so are more forgiving to services that forge `From:` field

**Comment by aborruso** [comment]
Thank you @mnalis 

There is also another option:

- the one used by those who manage the OSGeo mailman services, in which I can use nabble to write from a gmail address.

Unfortunately I don't know what it is.
