### ISSUE TITLE
New planet server in AM6

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#543]
- [x] Decide specs
- [x] Get quote
- [x] Circulate quote for comment
- [x] Request pro-forma invoice
- [x] Send invoice to treasurer
- [x] Wait for server to be built and shipped
- [x] Open incoming shipment ticket with Equinix

-----

#537 sets out the decision to go with the option for a planet server immediately and look at developing an object-store based solution later. We had planned replacing the AM6 planet server in 2022Q1, but I'd like to do that sooner because we've done a lot of the work already.

**Comment by pnorman** [comment]
With upcoming price increases I'm going to get this quoted immediately, for the same specs as the DB4 planet server in #537

**Comment by pnorman** [comment]
Quotation number: 190430

1 x Delivery - Pallet Overnight
1 x Server Build
1 x Supermicro Ultra SuperServer 120U-TNR
2 x Intel ICX-SP 4310 12C/24T 2.1G 18M
16 x 16GB DDR4-3200 2Rx8 ECC REG DIMM,RoHS
2 x Enterprise Class 240GB SATA Solid State Drive
1 x Supermicro 2 port 10GbE Riser Intel X710-AT2
7 x 7.68TB Enterprise Class SAS Solid State Drive (1DWPD)
1 x Supermicro 8-port 12Gb/s SAS - RAID 0,1,10,5,6,50,60
1 x 3 Years Return to Base Warranty

**Comment by tomhughes** [comment]
This has arrived and been installed as `norbert`.

**Comment by tomhughes** [comment]
This went live a long time ago.
