### ISSUE TITLE
Nominatim server for DB4

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#544]
- [x] Decide specs
- [x] Get quote
- [x] Circulate quote for comment
- [x] Request pro-forma invoice
- [x] Send invoice to treasurer
- [x] Wait for server to be built and shipped
- [x] Open incoming shipment ticket with Equinix

We have a nominatim server budgeted and planned for 2021Q4. With the extended lead times, I'd like to order it sooner rather than later. #259 puts the storage space needed as 2.5TB to be safe, +.5TB for autocomplete. This would require specs similar to a render server, so maybe if we just get a clone of that?

**Comment by pnorman** [comment]
Quote number 190402

1 x Delivery - Overnight
1 x Build and Full System Soak Test
1 x Supermicro Super Server 1124US-TNRP
2 x AMD EPYC™ 7453 DP/UP 28C/56T 2.75G 64M 225W SP3
16 x 16GB DDR4-3200 2Rx8 ECC REG DIMM,RoHS
3 x Enterprise Class 4TB NVMe U.2 SSD (1DWPD)
2 x Enterprise Class 240GB SATA Solid State Drive
1 x 3 Years Return to Base Warranty

**Comment by lonvia** [comment]
The server has arrived and is now in production: https://hardware.openstreetmap.org/servers/longma.openstreetmap.org/
