### ISSUE TITLE
Purchase new development ("tool") server

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#545]
- [x] Decide specs
- [x] Get quote
- [x] Circulate quote for comment
- [x] Request pro-forma invoice
- [x] Send invoice to treasurer
- [ ] Wait for server to be built and shipped
- [ ] Open incoming shipment ticket with Equinix

-----

The development server errol is a server open for developers to use, and many tasks are run on it. It is 10 years old and critically in need of replacement.

I see two options: something like the planet server, or used HP kit. We could get a HP DL360 Gen9 and put in two boot drives and up to 6 3.84TB SSDs, either SATA or SAS. I'd be fine with SATA in this application. We could put in 6x3.84TB + 2x240GB SATA and get 15.36TB in RAID6, and this would remain within budget.

**Comment by pnorman** [comment]
The HP option is about 6.7k eur net, the new option is likely to be >9k. Given this, I think the HP offers much better value.

**Comment by pnorman** [comment]
Something like this - I'll have to get a manual quote to get the RAM speed right and deal with a proforma/etc, but it's in budget and has RAID6+hotspare SAS

[SH-20210625022121.pdf](https://github.com/openstreetmap/operations/files/6715060/SH-20210625022121.pdf)

**Comment by pnorman** [comment]
Moved to 2022Q3 or 2022Q4

**Comment by pnorman** [comment]
Up to date quote for a HP DL360 Gen10: 7.6k EUR ex-vat.

[SH-20220801235138.pdf](https://github.com/openstreetmap/operations/files/9239742/SH-20220801235138.pdf)

Rackservers.com quote for new AMD EPYC 7413 (24 core @ 2.64GHz) with 256GB RAM and same drives is 13.7k EUR

**Comment by pnorman** [comment]
@Firefishy can you get me a total for disk space needed. Also, do you think we need a hot spare for the dev server drives?

**Comment by Firefishy** [comment]
@pnorman 

I emailed all dev users, I have heard back from some already. 15 are happy with me terminating their accounts.

Disk space requirement: 8TB to 10TB would be ideal. A hot spare would be my preference.

**Comment by pnorman** [comment]
Email sent for a quote for 2x AMD EPYC 7413, 256GB RAM, 6x 3.84TB SATA SSD, 2x480GB SATA SSD.

**Comment by pnorman** [comment]
Pro-forma sent to treasurer and accountant. We went for a HP DL360 Gen10 with NVMe, since they've come down in price.

**Comment by grischard** [comment]
Payment has been made, waiting to hear back from Serverschmiede

**Comment by pnorman** [comment]
ETA is 25th or 26th for when it gets shipped.

**Comment by Firefishy** [comment]
The supplier incorrectly shipped the server to the wrong address. The server is currently trapped somewhere between brexit land and nowhere. Supplier is chasing, but not much movement in the last week.

**Comment by Firefishy** [comment]
The machine is still in limbo.

**Comment by Firefishy** [comment]
Server is racked, OS installed and migration is happening in https://github.com/openstreetmap/operations/issues/752
