### ISSUE TITLE
Plan API database PostgreSQL upgrade

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#548]
Tracking issue because this will involve a downtime during the transition.

Rough plan:
- Test rails port and cgimap against latest PostgreSQL on the dev server
- Upgrade one of the DB read-only replicas
- Switch read-only traffic to the replica
- Bring site into read-only mode
- Switch primary DB server to the replica
- Bring site into online mode
- Upgrade replicas

**Comment by mmd-osm** [comment]
I would propose to also include osmdbt for minutely diffs in the test.

**Comment by tomhughes** [comment]
Argh. I thought I was dealing with this. I still haven't got around to doing my tests so we're not ready to progress this yet and I probably still have the "how to" plan from last time somewhere.

The dev server has been running an up to date postgres for some time so rail, cgimap, osmdbt etc are all tested already.

**Comment by tomhughes** [comment]
That plan doesn't work by the way - you can't do one server at a time. You have to take everything down and do a big bang - upgrade the primary and then do each secondary before you restart replication if memory serves me correctly.

**Comment by tomhughes** [comment]
Found my plan from the last attempt: https://github.com/openstreetmap/operations/issues/94#issuecomment-284243528

**Comment by pnorman** [comment]
Plan is for downtime on Sun Jan 22nd

**Comment by mmd-osm** [comment]
Do we know the target PostgreSQL release already? Any sort of preparation to watch out for?

**Comment by tomhughes** [comment]
This upgrade has been completed.
