### ISSUE TITLE
Renew *.openstreetmap.org certificate (Expires: 18 March 2016)

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#55]
The RapidSSL wildcard *.openstreetmap.org certificate expires on the 18th March 2016. 
Options:
1) Renew with RapidSSL (undesirable)
2) Switch to Letsencrypt. (preferred)
3) As per 2, but have a separate (Oracle JDK trusted) certificate for api.openstreetmap.org

**Comment by Firefishy** [comment]
Note: Letsencrypt's CA certificate is not trusted by default by the Oracle JDK. It is possible to hardcode support, but will require work by JOSM developers (and others?): https://community.letsencrypt.org/t/will-the-cross-root-cover-trust-by-the-default-list-in-the-jdk-jre/134/26?u=firefishy

**Comment by Firefishy** [comment]
CC'ing @don-vip @openstreetmap/josm

**Comment by don-vip** [comment]
Let's Encrypt is not yet supported by the JDK but they confirmed to have applied to Oracle program. I don't know how much time it will take, but as it is supported by major companies I hope it will be integrated soon... Next Java version is expected for 19th of January, we'll wait for it to see what to do next.

**Comment by pnorman** [comment]
I wouldn't hold my breath waiting for Oracle to add them, given their past non-addition of industry accepted CAs.

**Comment by tomhughes** [comment]
Even if they do add it in January would we really want to require every JOSM user to upgrade to the latest and greatest Java?

**Comment by stoecker** [comment]
JOSM also accesses svn.openstreetmap.org, wiki.openstretmap.org, trac.openstreetmap.org, taginfo.openstreetmap.org,  (gps-)(a|b|c).tile.openstreetmap.org, www.openstreetmap.org, nominatim.openstreetmap.org and not only api.openstreetmap.org.

See also issue #2.

Regarding Let's Encrypt? As far is I know they issue no wildcards.

**Comment by tomhughes** [comment]
They don't do wildcards no, but you can have as many altnames as you like so it's no problem.

**Comment by zerebubuth** [comment]
> Even if they do add it in January would we really want to require every JOSM user to upgrade to the latest and greatest Java?

I would have thought that upgrading to the latest and greatest Java version was highly recommended from a security standpoint. At least, that's what it says on the dialogue box that pops up every time I run it :wink:

It seems like much depends on whether that's even an option, so I'll be on the edge of my seat until the new version on the 19th.

**Comment by zerebubuth** [comment]
@don-vip, I fear that the new version didn't include any CA changes which would help with letsencrypt?

Talking with @tomhughes and @Firefishy, it seems like there's not much enthusiasm for going forward with Letsencrypt right now. Partially due to this Java issue and partially due to the [rate limits](https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769) making managing the issuing process a pain. We'd have to stagger the issuance to stay under the cap, which complicates a process which was supposed to get _simpler_.

On the other hand, this gives us 12 months to get all the Java clients in shape for switching next year. What's the best way to announce this? (I'm assuming that we can't rely on Oracle to help us out.)

**Comment by Firefishy** [comment]
*.openstreetmap.org certificate renewed. Best to open another ticket for the LetsEncrypt certificate.

**Comment by bastik** [comment]
Just to let you know, we have implemented support for custom CAs in JOSM version [9995](https://josm.openstreetmap.de/changeset/9995/josm). The hardcoded certificates are DST Root CA X3 (for Let's encrypt) and StartSSL.

As there is only a problem with the Oracle Java distribution, which is used mainly on Windows and OSX, a grace period of about one year should suffice. (Linux repositories would take longer to catch up.)

Obviously, there may be other Java software with the same dependency, now or by then.

**Comment by zerebubuth** [comment]
@bastik, thanks! That's great news.
