### ISSUE TITLE
OpenStreetMap Standard tiles not displaying in iD

### ISSUE THREAD

**Issue by sjorford** [openstreetmap/operations#550]
I can't get any OpenStreetMap Standard tiles to display in iD:
![image](https://user-images.githubusercontent.com/10633357/125294743-7404e780-e31c-11eb-8de6-3a57ad17617f.png)

They display okay when just veiwing the map:
![image](https://user-images.githubusercontent.com/10633357/125294421-26887a80-e31c-11eb-80a1-69b5583412f5.png)

But when in the editor the requests all come back with a response of `418 I'm a teapot` which I gather is some sort of rate limiting thing? Other tile types (Bing etc.) appear okay.

I've tested on multiple browsers (Firefox, Chrome, Edge) on multiple PCs on multiple networks, so it doesn't seem to be a local issue.

**Comment by pnorman** [comment]
I'll fix this - didn't realize iD was using the old hostnames

**Comment by tomhughes** [comment]
Should we open a PR to update https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/world/OpenStreetMap-Mapnik.geojson as well?

**Comment by pnorman** [comment]
iD taking arbitrary imagery URLs means I'll need to do something more sophisticated if I want to block those fakes - I'll have to reconsider if its worth it.

I did update the eli index because it's better to use tile.openstreetmap.org instead of the old three hostnames.

**Comment by pnorman** [comment]
Fixed yesterday.
