### ISSUE TITLE
Category selection on blog.openstreetmap.org selects language

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/operations#551]
Selecting a category (in this case "legal") on blog.openstreetmap.org doesn't select the category and instead changes the language to Russian.

Tested on android with the stock Samsung browser, FF on android, chrome and FF on windows (all current versions).

**Comment by harry-wood** [comment]
Thanks. I'll create an issue for this over here in the wordpress theme repo https://github.com/harry-wood/osmblog-wp-theme/issues/10  (and here it can be closed I guess)

**Comment by Firefishy** [comment]
I have updated to the latest version of WPML translation plugin. It had no effect. The fault likely lies with the wordpress theme.

**Comment by pnorman** [comment]
Closing as https://github.com/harry-wood/osmblog-wp-theme/issues/10 covers the same issue
