### ISSUE TITLE
planet.openstreetmap.org weekly update stopped

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap/operations#552]
`planet.openstreetmap.org` updates planet, changeset and discussion dumps weekly. Last dump was 2021-07-03, so we could expect 2021-07-10 to be the next one, which did not happen.
Note dumps are unaffected.

**Comment by tomhughes** [comment]
That probably just means the database backup failed last week for some reason - the dumps are driven from the backup so if it fails there will be no dumps that week.

**Comment by tomhughes** [comment]
Actually the backup was fine but the dump hasn't completed yet - there are actually two dumps running currently, last week's and this week's.

**Comment by tomhughes** [comment]
Looks like last weeks dump got stuck in some sort of thread deadlock. I've killed it and hopefully this week's will complete.
