### ISSUE TITLE
Is the Translate extension compatible with the Wiki?

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/operations#555]
I currently have been [in conversation](https://wiki.openstreetmap.org/wiki/Talk:Wiki#Add_Translate_Extension) with the Wiki community about adding the [Translate extension](https://www.mediawiki.org/wiki/Help:Extension:Translate) to the Wiki. 

@Tigerfell reccomended that I ask @Firefishy if it was compatible for install before proposing it publicly. I never received a response about that so I'm just creating an issue here to ask the same thing. 

If it is compatible, that's great because I've already wrote a [formal proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Add_Translate_extension_to_Wiki) and [implementation plan](https://wiki.openstreetmap.org/wiki/Proposed_features/Add_Translate_extension_to_Wiki#Implementation_plan). 

I would also like to know if the Wiki maintainers approve of this implementation plan, especially the parts about the user permissions proposed and the deleting of old translated pages when they're not needed anymore.

**Comment by pnorman** [comment]
Extension requests [should come from wiki admins](https://github.com/openstreetmap/operations/issues/509#issuecomment-785403089).

For any extension requests, the sysadmins will have to consider the cost of maintaining it, and have a strong bias to only enable modules that ship with mediawiki itself.

**Comment by lectrician1** [comment]
> Extension requests should come from wiki admins.

I do understand this. This is not a request, but just a step in the process that was recommended by a wiki admin _before_ actually proposing adding it.
