### ISSUE TITLE
Remove servers list from wiki?

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#56]
We now have https://hardware.openstreetmap.org which replaces most of the information found on the wiki regarding the servers.

http://wiki.openstreetmap.org/wiki/Servers

Are we now happy enough with the automated version to remove the wiki pages? I think we can remove all the individual server pages, and the location-based tables for a start.

**Comment by tomhughes** [comment]
I think the descriptions in the tables are the main thing that is still missing from the new site.

**Comment by zerebubuth** [comment]
Agreed, as long as we're not deleting the wiki pages entirely - the history has been very useful when trying to compile the historical portions of the asset register #37.

**Comment by tomhughes** [comment]
A normal deletion will keep history - only extreme action by an administrator can remove that.

**Comment by pnorman** [comment]
If I compare https://hardware.openstreetmap.org/servers/orm.openstreetmap.org/ and http://wiki.openstreetmap.org/wiki/Servers/orm there's some like what filesystem is on what physical drives on the Wiki, but it's not easy to get that from the new page.

Knowing which drives make up sd{a,b,c} would complete the picture.

On the other hand, the Wiki page is clearly wrong, as it specifys 1x 1TB SSD and an array made from 2x 1TB SSDs so losing this information is no great loss!

**Comment by tomhughes** [comment]
That's one thing I deliberately made sure was discoverable on the new pages! Yes you have to work backwards through the various levels of indirection, and there's a little bit of guesswork about which physical disks are part of which hardware arrays but it's usually obvious. The old pages only give aggregate information anyway.

Basically listing all the physical disks for each array was going to make the page insanely large for a summary so I decided to leave that for a hypothetical future "detail" page of some sort.

**Comment by yvecai** [comment]
I guess the new column 'description' could be filled from the 'Purpose' from the wiki for those who doesn't know the servers.

**Comment by tomhughes** [comment]
Well yes that's the point, that we need to replicate that data.

The question is how to do so...

Well it's not even really that, it's just getting around to doing it, given it probably means copying all that data to chef attributes so that osmf-server-info can see it.

**Comment by gravitystorm** [comment]
We could roughly approximate it by taking the roles for the node, and subtracting any location or hardware related ones.

**Comment by tomhughes** [comment]
Yes I was pondering something along those lines myself.

**Comment by gravitystorm** [comment]
I've updated the wiki page and pointed the server names at hardware.openstreetmap.org, and I've put in delete requests for all the individual pages. If a wiki-gnome doesn't sort those out I can deal with them later on.

When we automate the server descriptions then we can remove the tables from the wiki completely.

**Comment by DeeHants** [comment]
FYI, the `{{Delete|...}}`d pages have now been removed (history is still accessible to some.
There is now a `{{Server|...}}` template that links to the new hardware pages.

Is there any possibility of moving the old servers to the new style so they can be removed too?
(e.g. [smaug](http://wiki.openstreetmap.org/wiki/Servers/smaug), [faffy](http://wiki.openstreetmap.org/wiki/Servers/faffy), etc.)

Also, it appears as if the switch and power strip layouts are out of date too. Delete, or are they worth migrating?

**Comment by tomhughes** [comment]
I think both smaug and faffy are considered dead - certainly they have both been removed from chef which is why they don't appear on the new site at all.

I don't know how good the switch and power strip information is - it was correct when we migrated the servers to the new rack at UCL because I updated it all but I don't know how much it has bitrotted since. It's inherently manual in that we have no way to gather it automatically.

**Comment by DeeHants** [comment]
@tomhughes I guessed it was manual, but maybe a semi automated part of the hardware page with links to associated power strips and switches? (automatically removing offline servers, etc).
I don't know enough about chef or the hardware site to know if old data can be added (similar to idris)

**Comment by gravitystorm** [comment]
I'd recommend just deleting the pages for the servers that are no longer in use.

The alias pages aren't used officially for anything (and the two you linked to are both inaccurate, so they clearly aren't being maintained) so I'd recommend deleting them too.

Neither chef nor the hardware site (which is just a presentation of the information from chef) support old or historical data. The hardware site is just designed to show OWG the data we need for current operations - that's what the wiki pages were for too.

(As a sidenote, both @zerebubuth and I have considered how to build on top of the "current-only" chef information to record changes and historical information, but that's a project for elsewhere and another time).

**Comment by DeeHants** [comment]
The key thing I don't see on the new server pages is usage (beyond chef roles like `mail server`). Some are listed on the main page though.

**Comment by tomhughes** [comment]
Yes the roles was supposed to replace that in a reasonably automated way.

**Comment by tomhughes** [comment]
Well or rather the description column on the front page, which is driven from the roles.

**Comment by pnorman** [comment]
:+1: for removal of the tables. The advantages of automatically updating are showing themselves with the wiki being out of date. There is some information on the wiki page which isn't relevant to user but might be to ops, and I wanted to check before removing the tables

* Not in use servers
* Power porets
* Rack units

Also on the page are other lists, are these still needed?

* KVMs
* Power strips
* Network switches

What I plan to do is replace the tables with some prose about hardware.openstreetmap.org and the different datacenters.

**Comment by gravitystorm** [comment]
The list of servers has now been removed from the wiki
