### ISSUE TITLE
503 on help.openstreetmap.org again

### ISSUE THREAD

**Issue by TZornG** [openstreetmap/operations#561]
For what it's worth I'm raising the issue with 503s on our help site [again](https://github.com/openstreetmap/operations/issues/298). We've experienced a lot of them on the 3rd, 4th and 5th of August and then again since yesterday. While in the past the site would often load on a single refresh this time the site will not load for up to half a minute or so. During the past 15 minutes I have gotten this error for at least 5 times.

Other users [are experiencing it as well](https://help.openstreetmap.org/questions/75166/whats-with-the-website-wide-http-503-at-least-a-few-hours-ago).

---
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
_Apache/2.4.41 (Ubuntu) Server at help.openstreetmap.org Port 443_

**Comment by TZornG** [comment]
#298

**Comment by tomhughes** [comment]
I've restarted the web server.
