### ISSUE TITLE
Automate membership renewal check

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/operations#563]
Mail is sent:
> From: "OpenStreetMap Foundation" <membership@osmfoundation.org>
> Subject: OpenStreetMap Foundation membership renewal notification
> 
> Dear [member],
> 
> This is an automatic reminder that your OSMF membership is due to lapse on 29th August, 2021. As an active contributor member, instead of an annual payment, you can again fill out
> the active contributor form.
> 
> To renew your membership, if you are an active mapper, go to this page and submit the form:
> https://join.osmfoundation.org/application-form-for-active-contributor-membership-mapping/
> 
> If you contribute otherwise than mapping, go to this page and submit the form: https://join.osmfoundation.org/application-form-for-active-contributor-membership-other/
> 
> If you have any questions related to your membership, just reply to this e-mail and we’ll get back to you.
> 
> Happy mapping!
> 
> The Membership Working Group

Actually all these checks could be automated.

If they complete successfully, no reminder need be sent, reducing mailbox clutter. Membership should be extended automatically.

(Yes, filling out the form, one sees
> Please note that there are some manual steps in processing these applications, so it might take a few days before you hear back from us.

Which is another place automation could help.)

If they fail, the user should be warned his membership is about to expire, etc.

**Comment by datendelphin** [comment]
Hi @jidanni this is a topic for the [Membership Working Group](https://wiki.osmfoundation.org/wiki/Membership_Working_Group), not operations.

**Comment by jidanni** [comment]
Yes, I tried real hard to find them in https://github.com/osmfoundation .
