### ISSUE TITLE
OSM Wiki: Special:NewItem is currently broken ("Item:/" has been banned from creation)

### ISSUE THREAD

**Issue by tsmock** [openstreetmap/operations#564]
See https://wiki.openstreetmap.org/wiki/Talk:Data_items#creation_permission_error
(For testing, I used `Label=toll=no` and `Description=Where most traffic is not required to pay a fee` in [Special:NewItem](https://wiki.openstreetmap.org/wiki/Special:NewItem))

This is also present when directly calling the API.

Steps to reproduce (requires `curl` and `jq`):
```bash
#!/usr/bin/env bash
rm cookie.txt

USER_NAME="<USERNAME>"
PASSWORD="<PASSWORD>"
LOGINTOKEN=$(curl 'https://wiki.openstreetmap.org/w/api.php?action=query&meta=tokens&type=login&format=json' -b cookie.txt -c cookie.txt | jq '.query.tokens.logintoken' -r)
curl -X POST https://wiki.openstreetmap.org/w/api.php --form "action=clientlogin" --form "format=json" --form "loginreturnurl=http://example.org" --form "logintoken=${LOGINTOKEN}" --form "username=${USER_NAME}" --form "password=${PASSWORD}" -c cookie.txt -b cookie.txt
TOKEN=$(curl 'https://wiki.openstreetmap.org/w/api.php?action=query&meta=tokens&type=csrf&format=json' -c cookie.txt -b cookie.txt | jq '.query.tokens.csrftoken' -r)
curl -X POST https://wiki.openstreetmap.org/w/api.php -c cookie.txt -b cookie.txt -v --form "action=wbeditentity" --form "format=json" --form "new=item" --form "token=${TOKEN}" --form 'data={"labels":{"en":{"language":"en","value":"toll=no"}},"descriptions":{"en":{"language":"en","value":"Where most traffic is not required to pay a fee"}},"sitelinks":{"wiki":{"site":"wiki","title":"Tag:toll=no"}},"claims":[{"mainsnak":{"datavalue":{"value":{"entity-type":"item","numeric-id":"2","id":"Q2"},"type":"wikibase-entityid"},"property":"P2","snaktype":"value"},"type":"statement"},{"mainsnak":{"datavalue":{"value":{"entity-type":"item","numeric-id":"775","id":"Q775"},"type":"wikibase-entityid"},"property":"P10","snaktype":"value"},"type":"statement"},{"mainsnak":{"datavalue":{"type":"string","value":"toll=no"},"property":"P19","snaktype":"value"},"type":"statement"},{"mainsnak":{"datavalue":{"value":{"text":"Tag:toll=no","language":"en"},"type":"monolingualtext"},"property":"P31","snaktype":"value"},"type":"statement"},{"mainsnak":{"datavalue":{"value":{"entity-type":"item","numeric-id":"8001","id":"Q8001"},"type":"wikibase-entityid"},"property":"P33","snaktype":"value"},"type":"statement"},{"mainsnak":{"datavalue":{"value":{"entity-type":"item","numeric-id":"8000","id":"Q8000"},"type":"wikibase-entityid"},"property":"P34","snaktype":"value"},"type":"statement"},{"mainsnak":{"datavalue":{"value":{"entity-type":"item","numeric-id":"8001","id":"Q8001"},"type":"wikibase-entityid"},"property":"P35","snaktype":"value"},"type":"statement"},{"mainsnak":{"datavalue":{"value":{"entity-type":"item","numeric-id":"8001","id":"Q8001"},"type":"wikibase-entityid"},"property":"P36","snaktype":"value"},"type":"statement"}]}'
```
which currently returns
```json
{"error":{"code":"permissiondenied","info":"You do not have the permissions needed to carry out this action.","messages":[{"name":"wikibase-api-permissiondenied","parameters":[],"html":{"*":"You do not have the permissions needed to carry out this action."}},{"name":"titleblacklist-forbidden-edit","parameters":[" .*\\/","Item:/"],"html":{"*":"The title \"Item:/\" has been banned from creation.\nIt matches the following blacklist entry: <code> .*\\/</code>"}},{"name":"titleblacklist-forbidden-edit","parameters":[" .*\\/","Item:/"],"html":{"*":"The title \"Item:/\" has been banned from creation.\nIt matches the following blacklist entry: <code> .*\\/</code>"}}],"*":"See https://wiki.openstreetmap.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."}}
```

Notably, neither method is explicitly setting the `Item:Q<number>` title, which indicates something in the backend is try to add a `Item:/Q<number>` title.

**Comment by tomhughes** [comment]
This is a wikidata thing right? If so then we probably need @nyurik as none of knows anything about it...

**Comment by tsmock** [comment]
Yes, it is a wiki data thing.

**Comment by nyurik** [comment]
@tsmock thx for reporting. I was able to create the item as described in https://wiki.openstreetmap.org/wiki/Talk:Data_items#creation_permission_error , so i suspect it is a permission error. I have not touched Wikibase setting for a long time. I wonder if Wikibase or related extensions have recently been updated, or if some allowlist has been changed recently?  I will post the question in [OSM-US Slack](https://osmus-slack.herokuapp.com/) - `#osm-wiki` channel. Also CC: @1ec5 as he might know something about this.

**Comment by nyurik** [comment]
@tomhughes i was trying to figure out if there has been any updates to MediaWiki or any related extensions recently, but it seems  the versions are not part of the chef repo? How does chef decide the version of the extensions? [see also](https://github.com/openstreetmap/chef/blob/12007a1850cedfabce76c6802ccc9ffca3e6f027/cookbooks/wiki/recipes/default.rb#L77)

Also, all wikibase permissions are set in [here](https://github.com/openstreetmap/chef/blob/12007a1850cedfabce76c6802ccc9ffca3e6f027/cookbooks/wiki/templates/default/mw-ext-Wikibase.inc.php.erb#L72), and they have not been touched.

**Comment by tomhughes** [comment]
Extensions track the upstream branch for whatever major version is selected, so currently it is tracking the REL1_35 branch in the repository and right now it's running 2a87f2ff64e3ed137e9e6c90de4a51d39b2823d2 for Wikibase.

**Comment by nyurik** [comment]
Thanks @tomhughes . I actually just discovered this recently added rule added by @Tigerfell -- https://wiki.openstreetmap.org/w/index.php?title=MediaWiki%3ATitleblacklist&type=revision&diff=2159432&oldid=2101957 -- I commented it out. Could someone without wiki admin rights try to create a data item again?  I will CC to the wiki talk page.

**Comment by tsmock** [comment]
> P.S. i love the detailed bug report with a repo, well done!
In my experience, it is easier to fix a bug if you have one of the two following bits of information:
* Good steps to reproduce
* Useful stacktrace

Since I did not have a useful stacktrace, but was able to reliably reproduce, I wrote the script (it is pretty much what my JOSM plugin does).

Anyway, I was able to create a data item again ( https://wiki.openstreetmap.org/wiki/Item:Q21770 ). Thanks. :)

**Comment by Tigerfell** [comment]
I just want to point out that merging openstreetmap/chef/pull/442 would have definitely helped to resolve this problem, because it enables logging for the title black list. I regularly check the logs but if a tool does not produce any entries I can not do anything.
