### ISSUE TITLE
Trying to register as a full OSMF member fails

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#566]
> Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
DB Error: no such field

> Return to home page.

![screen01](https://user-images.githubusercontent.com/899988/131230706-17545d76-d71b-41d4-814d-5a6e37b3f46e.png)

Maybe because I am an associate member right now? Or due to https://en.wikipedia.org/wiki/Ogonek in my address?

Happened after filling https://join.osmfoundation.org/normal-membership/

If server logs are insufficient and/or it is not reproducible I can try to see what produces it. Not sharing input data as I prefer to not make my exact address very easy to get for others, but I can send them via some private channel.

**Comment by tomhughes** [comment]
You probably need to contact MWG about that - they got me to upgrade CiviCRM today and I assume they haven't run the migrations to update the database.

**Comment by tomhughes** [comment]
I've run the migrations now so hopefully it should be working again.
