### ISSUE TITLE
Weekly planet dump on planet.openstreetmap.org stuck again

### ISSUE THREAD

**Issue by Spiekerooger** [openstreetmap/operations#568]
The weekly planet dump stuck again after 2021-09-11.
2021-09-18 and 2021-09-25 are missing as of today.
Issue looks like this one from July: https://github.com/openstreetmap/operations/issues/552

**Comment by tomhughes** [comment]
Last week didn't happen because the database backup failed as I had to restart the database so the dump wasn't run.

This week's is still running.

**Comment by tomhughes** [comment]
I think it probably has finished but has deadlocked again before publishing the results - the sizes of the file look similar to last week though so it must have been close to finished at least.

**Comment by tomhughes** [comment]
Sadly it looks like it hasn't finished writing the relations so I'm going to have to abort it without publishing the results and there's no point restarting it now.

I'll open a bug on planetdump and see if Matt has any idea what is going on.

**Comment by tomhughes** [comment]
Opened https://github.com/zerebubuth/planet-dump-ng/issues/24.

**Comment by mnalis** [comment]
Don't know if that is still the same issue, but planet seems to not have been generated this weekend either.
