### ISSUE TITLE
OSMF instance of overpass for the 'Query Features' function

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/operations#569]
I find the 'Query Features' function on the main website extremely useful but the slowness becomes increasingly annoying. What are the feelings about running our own Overpass instance exclusively to be used for this feature only?

Hardware: The main instance currently runs on a Hetzner machine with 4 CPUs, 64GB RAM and 1TB NVME. The query feature is one of the cheaper queries, which means the given hardware specs are an upper limit in terms of what is needed. A version for the query feature would also not need history data, i.e. less disk would be needed.

Administration: I would be willing to set up, chef up and administrate such an instance.

**Comment by tomhughes** [comment]
I've long thought we should run our own, right back to when I implemented that feature so I would certainly agree that we should.

**Comment by Zverik** [comment]
Agreed, this is long overdue and thank you Sarah for taking this up. The query feature function stops working for me after two clicks, which is quite frustrating.

I wonder if we could disable more complex functions so that people do not overload the server with non-relevant queries. @mmd-osm?

**Comment by mmd-osm** [comment]
I think the underlying reasons for slowness are well understood (at least from my side), and also addressed in my fork: https://github.com/mmd-osm/Overpass-API. Unfortunately, most of this isn't available upstream, because those performance topics require rather large changes to the architecture and implementation details.

What would definitely help on the current production site is a much stricter enforcement of usage policies, in particular due to a large amount of very small requests triggered by mobile apps. They consume quite some load due to the CGI-based architecture and limited options for caching.

If you want to expose the Overpass instance for the Query features feature only, you could probably create some wrapper on the Rails port, and call an internal-only Overpass instance from there, so that the Overpass endpoint isn't exposed publicly.

Disabling more complex functions isn't something that the main branch supports out of the box, and I wouldn't recommend tweaking the code for this purpose.

**Comment by tomhughes** [comment]
To be clear I am talking about (and @lonvia was as well) running a server purely to support the main web site, not to provide general overpass service to wider community.

What would be useful in terms of enforcing that is a system of TOTP based tokens as used to prioritise tiles but we could probably do that as a frontend to overpass if necessary.

**Comment by mmd-osm** [comment]
When setting up a new instance please make sure to compile in and use lz4 compression. Default is zlib which is slower and uses more cpu. Both overpass-api.de instances also run on lz4.

**Comment by pnorman** [comment]
I also think we should run an overpass server, with severely restricted use, just for the osm.org queries.

We can probably get the resources needed for a single node, and if necessary for redundancy, it can fall back to the public overpass servers.

**Comment by lonvia** [comment]
gorwen is now up and running and the main site has been redirected. The munin graphs are [here](https://munin.openstreetmap.org/openstreetmap.org/gorwen.openstreetmap.org/index.html#overpass).

The uncompressed database without meta and attic data came out at 350GB. That means the minimum requirement for a new disk would be 600GB. That said, the spinning disks don't appear to be a bottleneck at the moment. In fact, the whole machine looks to be rather over- than underpowered. So, lets leave everything as is for now and see how the server does.

@mmd, two questions: 1) Is there a way to restrict maximum timeout and maxsize that a single client can request? I thought that this is what `--time` and `--space` were for but they only seem to request the overall global usage CPU and RAM by overpass.

2) I'm using an equivalent of rules_loop.sh for updating areas. It looks to be working fine but a single run takes 4.5h. That means that we are always a couple of hours behind the main DB with the area responses. Is that correct or should I be doing something different there? Note that I can't use the areas_delta.osm3s rules because the database doesn't have attic data.

**Comment by mmd-osm** [comment]
Thanks for the update!  I think spinning disks were quite a bottleneck for the initial database load, which would have taken less than 24h on NVMe. Disk IOs/second and disk latency do have some impact. Now that the initial load is done, that's not much of a concern anymore.

As I mentioned earlier, the only thing I would expect to happen now is an increased db lag when there's a bit more mapping activity. Earlier today at around 09:15:00Z, db contents were delayed by an hour, b/c someone deleted much data in Brazil.

Let's see how this works out over time. It's good to have munin stats up for the db lag, I think that's really helpful.

As you've noted correctly, `--time` and -`-space` are global parameters.  The only way to restrict maximum runtime and space for a single client it to use dedicated settings parameters as part of the query. You can find more details on this in the QL documentation: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Settings

The downside of this approach is that clients are free to provide insane values like `[timeout:100000]`. Release 0.7.57 has no way to override those settings, which I find a bit odd . I implemented such a logic in my fork, but I guess it would be good to have this in mainline, too.

Yes, delta mode for area creation works only along with attic data. I somehow forgot to mention that point. I don't think 4.5 hours is too bad for spinning disks. In comparison, SSD would be more like 30-40 minutes per single run.

On the positive side, you're lucky that release 0.7.57 got rid of all the ways for the areas creation. The job would likely take around 24 hours on the previous 0.7.56 release on this hardware.

By the way, It seems you've mentioned someone else :)

**Comment by lonvia** [comment]
Hmm, my impression with the import was that the lack of multi-threading really is the issue at hand but I might be wrong.

I've opened an issue for the timeout setting. Let's see what happens.

Closing here, as the instance is now in production. Will open a new issue for hardware resources as requeired.

**Comment by mmd-osm** [comment]
Yes, you're right, the lack of multi-threading also has some impact, in particular on the "Reorganizing the database ..." step. Importing Europe (28GB pbf) w/ multi-threading takes about 6 hours on my laptop, so there's some room for improvement for sure.

**Comment by mmd-osm** [comment]
I forgot if TOTP based tokens are already in place. It seems there’s a bit of high traffic on the box the last couple of days: https://munin.openstreetmap.org/openstreetmap.org/gorwen.openstreetmap.org/overpass_request_count.html

**Comment by mmd-osm** [comment]
@tomhughes : many thanks for resolving this issue so quickly! Everything seems to be back to normal again.
