### ISSUE TITLE
Replace failing disk in Yevaud

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#57]
SMART Disk issues. Disk has pending sectors in yevaud and should be replaced.

WDC WD3000HLFS-01G6U0, S/N:WD-WXL908104385, WWN:5-0014ee-0563c7e49, FW:04.04V04, 300 GB

I have a replacement disk in old stock.

**Comment by Firefishy** [comment]
I have given the spare to @zerebubuth

**Comment by zerebubuth** [comment]
Update: There's a problem of access. I'm working to try and get that resolved ASAP.

**Comment by Firefishy** [comment]
@zerebubuth has replaced the disk today. Rebuild in progress.

**Comment by zerebubuth** [comment]
New disk wasn't so new, and is also failing. Retry with new new disk.

**Comment by zerebubuth** [comment]
Disk replaced. @Firefishy all good with the rebuild?

**Comment by zerebubuth** [comment]
All RAIDs are normal.
