### ISSUE TITLE
Weekly planet PBF not released for last 3 weeks

### ISSUE THREAD

**Issue by rouen-sk** [openstreetmap/operations#570]
Last planet file available is `planet-210906.osm.pbf`, by now there should be `210913`, `210920` and `210927`. Lot of people and organizations are not running replication and rely on planet dumps for some periodic processing. I did not find any statement about this issue. Any idea when the planet releases will be resumed? Thanks.

**Comment by tomhughes** [comment]
Duplicate of #568.

**Comment by rouen-sk** [comment]
> Any idea when the planet releases will be resumed?

**Comment by tomhughes** [comment]
There's nothing to resume - they are continuing on their normal schedule and assuming nothing goes wrong this week it will appear when it is finished probably sometime on Saturday.
