### ISSUE TITLE
Get more power outlets at AM6

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#571]
All of the outets on the power bars are filled, except for the C19 ones. The PDUs have three of these each.

Deracking thorns, the MSA60, orm, and ramoth will help but we're still pressed for outlets. 

We could either get power bars for the C19 outlets, or use a C20 to C13 power cord

![image](https://user-images.githubusercontent.com/1190866/137063686-7debccc8-9fc1-452b-8cdf-240c902a76dd.png)

Given the difficulty in fitting in a 1U PDU my inclination is to get cables and disconnect old equipment. Next time someone is at the DC we could install a pair of 1U PDUs somewhere and rerun power cables.

**Comment by Firefishy** [comment]
We have installed a C20/C13 converts.

**Comment by Firefishy** [comment]
4x C19/20 ports now converted to C13/14 using plug-in adapter PDU side.
