### ISSUE TITLE
Provision S3 buckets for trace data and images

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#572]
We need to provision one or more S3 buckets for the trace data and images, along the lines of the existing bucket used for user avatars.

There are currently 3192818 traces, each of which has three files:

* A trace file - this is most of the data and totals about 762Gb
* Two images, a large animated one and a small thumbnail - there are 38Gb of images of which about 98% is the large ones

Looking at yesterday's requests I estimate the following:

* 17163 requests for trace data totalling 8906295830 bytes
* 2560 requests for the large images totalling 29682573 bytes
* 73521 requests for the small thumbnails totalling 117917997 bytes

**Comment by Firefishy** [comment]
@tomhughes Are the request estimates, per day, week or month?

**Comment by pnorman** [comment]
This comes to 40-50 USD/month on S3 standard. About half of that is S3 storage and half bandwidth. The per-request GET costs are not significant.

**Comment by tomhughes** [comment]
Two buckets (`openstreetmap-gps-traces` and `openstreetmap-gps-images`) have been provisioned and are now in use for new traces.

Migration of old traces will follow...
