### ISSUE TITLE
Capture LLDP ethernet port data in Chef (ohai) 

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#576]
It would be useful to capture LLDP port information into chef ohai.

The captured data could be reported on hardware.openstreetmap.org

There is an ohai plugin example here: https://signalvnoise.com/posts/3574-using-information-about-our-network-to-remove-monitoring-noise.

**Comment by tomhughes** [comment]
Implemented, with connected ports being reported:
![image](https://user-images.githubusercontent.com/147741/141513237-4a54c2cb-ac50-4620-aeec-3c41d4ea390e.png)
