### ISSUE TITLE
Missing tile log files

### ISSUE THREAD

**Issue by brawer** [openstreetmap/operations#577]
Most of the daily tile log files seem to get dropped before making it to https://planet.openstreetmap.org/tile_logs/:

| Month  | Expected | Observed | Status |
| :------------- | -------------: | -----: | :----- |
| October 2021  | 31 |  1 | ⚠️ 30 days missing |
| September 2021  | 30 |  2 | ⚠️ 28 days missing |
| August 2021  | 31 |  4 | ⚠️ 27 days missing |
| July 2021  | 31 |  24 | ⚠️ 7 days missing |
| June 2021  | 30 |  30 | ✅ OK |
| May 2021  | 31 |  31 | ✅ OK |

**Comment by tomhughes** [comment]
Duplicate of #554.
