### ISSUE TITLE
Adding emoji to wiki page deletes all text after it

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#583]
To reproduce I created 

```
before 
💥
after
```
at https://wiki.openstreetmap.org/wiki/User:Mateusz_Konieczny/test

it is displayed as expected, but opening it for editing (at least in code mode) removes emoji and all text after it

It is highly confusing, for example on https://wiki.openstreetmap.org/w/index.php?title=Foundation/AGM21/Election_to_Board/Answers_and_manifestos/Q12_Role_of_OSMF_in_large-scale_data_tagging_disputes&action=history someone used  🙂 in their answer what deleted all text after that

https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/amenity%3Dparcel_lockers was also recently affected - https://wiki.openstreetmap.org/w/index.php?title=Talk:Proposed_features/amenity%3Dparcel_lockers&diff=2216442&oldid=2216361 (they later complained that they lost a very long reply)

#373 may be related

**Comment by matkoniecz** [comment]
Note that for example https://commons.wikimedia.org/wiki/User:Mateusz_Konieczny/test_emoji was not affected so it may be fixable.

**Comment by 1ec5** [comment]
Yes, this is a symptom of #373. If you have a legitimate need for an emoji or another non-BMP character on a wiki page, use an HTML character entity reference or [Module:Char](https://wiki.openstreetmap.org/wiki/Module:Char). Some emoji like ⚠️ are unaffected as ordinary BMP characters that emoji fonts happen to provide glyphs for.

> Blocking adding emojis ( similar to https://en.wikipedia.org/wiki/MediaWiki:Abusefilter-disallowed-emoji ) would be also a possible workaround.

Good idea, I [adapted that filter](https://wiki.openstreetmap.org/wiki/Special:AbuseFilter/13) for the OSM Wiki to catch any character above U+FFFF, prevent the edit, and display a warning. I exempted the Item: and Property: namespaces, where labels and such appear to be unaffected by this issue for some reason.

**Comment by matkoniecz** [comment]
then I will close it as a duplicate, what specific to emojis could be done was achieved with the filter

thanks for configuring it
