### ISSUE TITLE
Random text at bottom of Licence/Contributor Terms OSMF wiki page

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/operations#589]
There's random `[Accept Button] [Decline Button]` text at the bottom of the [Licence/Contributor Terms OSMF wiki page](https://wiki.osmfoundation.org/wiki/Licence/Contributor_Terms) that needs to be fixed or removed.

**Comment by tomhughes** [comment]
The operations team are not responsible for the content of the OSMF wiki.

**Comment by Zverik** [comment]
Thanks for the report, removed them.
