### ISSUE TITLE
Separate DNS for Nominatim QA tiles

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/operations#590]
Nominatim exports some QA information in form of vector tiles. This got [a bit of attention](https://lists.openstreetmap.org/pipermail/talk/2022-January/087215.html) lately. Before people start to use the tile layer in other tools, it would be nice to have a proper external URL for it.

Can I have a DNS entry qa-tiles.nominatim.openstreetmap.org (or whatever else you think is suitable) which points to longma.openstreetmap.org?

**Comment by tomhughes** [comment]
Done.
