### ISSUE TITLE
Is there any value in https://wiki.openstreetmap.org/wiki/Servers/dev ?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#591]
I guess that it can be safely deleted without replacement, but I prefer to ask here

link: https://wiki.openstreetmap.org/wiki/Servers/dev

In general, it seems to me that all pages about specific servers in https://wiki.openstreetmap.org/wiki/Category:OpenStreetMap_Foundation_Servers should be deleted. Or marked as outdated, archived and not maintained at least. For example I hope that there are no [Ubuntu 12 servers](https://wiki.openstreetmap.org/wiki/Servers/faffy) running anywhere.

**Comment by mmd-osm** [comment]
https://hardware.openstreetmap.org includes up-to-date (since automatically generated) information. Current dev servers runs on https://hardware.openstreetmap.org/servers/errol.openstreetmap.org/

Wiki is not maintained (probably at all).

**Comment by matkoniecz** [comment]
But is there any archival value or some other reason why it may be worth keeping? Or is it just simply misleading, outdated and pointless?

**Comment by tomhughes** [comment]
I don't see any point in keeping them.

**Comment by matkoniecz** [comment]
article about the rackmounting rails attached to the servers at https://wiki.openstreetmap.org/wiki/Servers/Rails also can be deleted, right?

**Comment by Firefishy** [comment]
> article about the rackmounting rails attached to the servers at https://wiki.openstreetmap.org/wiki/Servers/Rails also can be deleted, right?

Yes, it can be deleted.
