### ISSUE TITLE
Introduce relation member limit (cgimap settings)

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#592]
_(copying over from website repo for better visibility)_

Even though https://github.com/openstreetmap/openstreetmap-website/pull/3440 is in production, is has no real impact, as all changeset uploads are handled by CGImap.

For this reason, some additional settings need to be made for CGImap:

- https://github.com/openstreetmap/chef/blob/master/cookbooks/web/recipes/cgimap.rb#L34
- https://github.com/openstreetmap/chef/blob/master/cookbooks/dev/templates/default/cgimap.environment.erb

Parameter to be added:

```
"CGIMAP_MAX_RELATION_MEMBERS" => "32000"
```

**Comment by tomhughes** [comment]
I already that before I deployed it!

**Comment by tomhughes** [comment]
Oh the push failed because I wasn't up to date - pushed now as https://github.com/openstreetmap/chef/commit/47765e0e711a11ec4f793d8a151fb1b9f8a925ba.

**Comment by mmd-osm** [comment]
Thank you for the quick update, seems all fine now!

**Comment by mmd-osm** [comment]
Very quick follow up: I'm not exactly sure about the dev instance settings in https://github.com/openstreetmap/chef/blob/master/cookbooks/dev/templates/default/cgimap.environment.erb

Are they good the way they are and settings in `cookbooks/web/recipes/cgimap.rb` would also apply there?
