### ISSUE TITLE
Many uploaded GPS traces are not rendering in iD layer

### ISSUE THREAD

**Issue by lint3** [openstreetmap/operations#593]
- Example 1, 4 days ago: https://www.openstreetmap.org/user/j_rides/traces/4118537 - Uploaded as Identifiable, visibility has not been changed
- Example 2, 3 days ago https://www.openstreetmap.org/user/Cole%20Myers/traces/4119322 - Currently shows as public, not sure about visibility changes
- Example 3, 3 days ago https://www.openstreetmap.org/user/johnnybegoode/traces/4118981 - Currently shows as identifiable, not sure about visibility changes

The traces have not rendered in iD's "Public GPS Traces" layer. While looking for examples I noticed that possibly some recently uploaded traces *have* been rendered.

**Comment by tomhughes** [comment]
It's already fixed and catching up.

**Comment by tomhughes** [comment]
Opened https://github.com/e-n-f/gpx-updater/pull/8 with the fix but I've applied it manually in production for now.

**Comment by lint3** [comment]
Awesome! Thanks!
