### ISSUE TITLE
Weekly planet stuck at 14 Feb 2022

### ISSUE THREAD

**Issue by ZeLonewolf** [openstreetmap/operations#595]
The current planet file posted at:
https://planet.openstreetmap.org/planet/2022/
...is dated 14 Feb.

I would expect the 21 Feb planet file to be available as of this past weekend.  Was there an issue with the most recent weekly planet build?

**Comment by tomhughes** [comment]
Yes it failed last week.

**Comment by Firefishy** [comment]
FYI: New planet is out: https://planet.osm.org/

**Comment by mnalis** [comment]
It seems planet dump failed again... 
Today is 2022-09-20, and last one is [planet-220905.osm.pbf](https://planet.openstreetmap.org/pbf/planet-220905.osm.pbf) (created on 2022-09-10).

**Comment by tomhughes** [comment]
Thank you for your interest but we already have monitoring which told us that five days ago so we don't really need you to go around commenting on multiple tickets.
