### ISSUE TITLE
NetworkImageLoadException (falha na solicitação HTTP, statusCode: 503, https://a.tile.openstreetmap.org/13/1317/3177.png)

### ISSUE THREAD

**Issue by AlysonTrizotto** [openstreetmap/operations#596]
[](https://user-images.githubusercontent.com/79091765/156691457-aec66b1a-ba71-4ddd-b8f7-647538db67cd.PNG)Oi, estou executando essa exceção, não entendo de onde ela está vindo ou por quê. Alguém pode me ajudar?

Olá, estou executando essa exceção, não entendo de onde ele está vindo ou o porque. Alguem pode me ajudar ?
![Capturar](https://user-images.githubusercontent.com/79091765/156691457-aec66b1a-ba71-4ddd-b8f7-647538db67cd.PNG)

`return MaterialApp(
home: Scaffold(
body: Center(
child: Stack(child:
FlutterMap(
mapController: mapController,
options: MapOptions(
maxZoom: 18,
minZoom: 4,
center: currentCenter,
zoom: zoomAtual,
onTap: (latlng)) {
removeMarker();
setState(() {
addMarker(latlng);
});
},
plugins: []),
camadas: [
TileLayerOptions(
urlTemplate:
"https://{s}.tile.openstreetmap.org/{z }/{x}/{y}.png",

fullCode[https://github.com/AlysonTrizotto/LocalizaCliente/blob/main/lib/componentes/mapa.dart](url)

**Comment by tomhughes** [comment]
At a guess you are in Brazil? In which case you were probably hitting Fastly's Curitaba cache which has been having problems but I believe it's working again now.

Unfortunately we don't control the cache network so all we can do is report problems to the operator as we observe them.

**Comment by tomhughes** [comment]
This shows the periods where the cache was having problems - as I say it seems to be OK at the moment:
![image](https://user-images.githubusercontent.com/147741/156759802-60497c27-dcbd-4397-8a3f-8c094f2e0bc8.png)

**Comment by Firefishy** [comment]
Pro Tip: Use https://tile.openstreetmap.org/ instead of (a. , b., c. names) as it is likely to be faster.

**Comment by AlysonTrizotto** [comment]
Okay, thank you all so much for the help. The bug was really temporary. It's normalized now. And @Firefishy about https://tile.openstreetmap.org/ I'll test it here.

Thank you all so much for the support. How can I contribute to the community?
