### ISSUE TITLE
Wiki categorisation does not work anymore

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#599]
There was a [huge spike in the queue length](https://wikiapiary.com/apiary/graph/?id=1516) on 13 February 2022. Since then, the categorisation is essentially broken. Some pages are missing in their categories, others are in wrong ones. There is a discussion at [Talk:Wiki](https://wiki.openstreetmap.org/wiki/Talk:Wiki#Categories_are_emptied) about potential causes and fixes. We hoped that the [weekly cron job](https://github.com/openstreetmap/chef/blob/01549dbd2e48dd0e6f0273d87a5a0c82ac1a983d/cookbooks/mediawiki/resources/site.rb#L203) would fix the issue. This was not the case. I guess we need some manual intervention. Maybe run the refreshLinks script and review the output?

**Comment by tomhughes** [comment]
What does wikiapiary have to do with our wiki?

**Comment by Tigerfell** [comment]
Wikiapiary monitors the queue length of the wiki. OWG's Prometheus/Grafana instance does not do that. In the past, this has been a useful indicator of load on MediaWiki.

**Comment by tomhughes** [comment]
Well perhaps we could have been asked to monitor it then instead of engaging some third party system - how does it even have visibility of the queues in our instance?

**Comment by Tigerfell** [comment]
Wikiapiary is a project monitoring many (if not all) publicly available instances of MediaWiki. I am not affiliated with them in any way. Nobody hinders you to use a publicly available MediaWiki API call. Here you go, Sir: https://wiki.openstreetmap.org/w/api.php?action=query&meta=siteinfo&siprop=statistics
The link is also available from the wiki's main page and named "Wiki status" there.

**Comment by matkoniecz** [comment]
> There was a [huge spike in the queue length](https://wikiapiary.com/apiary/graph/?id=1516) on 13 February 2022

This linked me to a page listing count of pages and articles

![screen04](https://user-images.githubusercontent.com/899988/158143201-2bad8588-41e7-40c6-b8e4-f6435096ac95.png)

**Comment by 1ec5** [comment]
> Someone else spotted that https://wiki.openstreetmap.org/wiki/Category:Pages_where_expansion_depth_is_exceeded has many pages which should not be there and where null edit (edit page, "save" without changing anything, this forces cache refresh) causes them to be removed from that category.

This suggests that an edit to a template (or something else transcluded like a template) could be responsible for populating the job queue. Some very widely transcluded pages have been edited multiple times in the last month, which would cause the job queue to get backed up:

* [Template:DescriptionLang](https://wiki.openstreetmap.org/wiki/Special:Diff/2234191/2290201) (×6), transcluded into 23,486&nbsp;pages
* [Template:Languages](https://wiki.openstreetmap.org/wiki/Special:Diff/2281969), 61,095 pages
* [Template:StatusLang](https://wiki.openstreetmap.org/wiki/Special:Diff/2290200), 22,568 pages
* [Template:DescriptionCategoriesLang](https://wiki.openstreetmap.org/wiki/Special:Diff/2260731), 22,534 pages
* [Template:ElementUsageLang](https://wiki.openstreetmap.org/wiki/Special:Diff/2290205), 22,382 pages
* [Template:ValueDescription](https://wiki.openstreetmap.org/wiki/Special:Diff/2270384), 15,699 pages

However, this has happened many times in the past without causing a prolonged backup of the queue. Maybe something else is causing this set of pages to take longer to clear than normal. 🤔

**Comment by tomhughes** [comment]
I did run the link rebuild that was originally requested but I assume it hasn't helped. Other than that I'm afraid I have no ideas of my own to offer.

**Comment by matkoniecz** [comment]
Maybe I will run bot through https://wiki.openstreetmap.org/wiki/Category:Pages_where_expansion_depth_is_exceeded making null edits? 4000 pages is not so high and I guess that it should not break server.

**Comment by Tigerfell** [comment]
It seems to be fixed for now.
