### ISSUE TITLE
Render database SSD replacement

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#6]
The rendering database on the tile servers is growing, and orm in particular is nearly full, so we need a plan to upgrade the SSDs used.

Currently orm has 2 x 450Gb SSDs in RAID1 and is 94% full.

Yevaud has a single 550Gb SSD and is only 76% full.

**Comment by tomhughes** [comment]
The database array on orm has now hit 95% full.

**Comment by zerebubuth** [comment]
What's the upgrade procedure? Worth trying to keep the existing DB, or just re-import from scratch?

**Comment by tomhughes** [comment]
Well orm is mirrored already so we can just add extra mirrors (or replace one at a time) and then grow once we are done.

As yevaud isn't mirrored that would need more thought.

**Comment by tomhughes** [comment]
One of the SSDs in orm has been replaced by a 1Tb disk and the database has been moved over. The other SSD can be removed next time somebody visits.

**Comment by tomhughes** [comment]
The SSH in yevaud has also been replaced by a 1Tb disk and the old SSDs have been pulled from both machines and stored as spares.
