### ISSUE TITLE
[Wiki] Fatal error using Tagalog localization

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/operations#602]
MediaWiki throws a fatal error any time you try to get MediaWiki to show anything from the Kapampangan (pam), Marathi (mr), or Tagalog (tl) localization, either to use the localization as the interface language or to extract any part of it for display in a template or wiki page.

For example, [MediaWiki:Mainpage/tl](https://wiki.openstreetmap.org/wiki/MediaWiki:Mainpage/tl) should be a wiki page containing the interface message that determines the name of the main page in the Tagalog localization, but instead it throws the following error:

> [66f361b16f997582aa24846c] 2022-03-19 21:28:34: Fatal exception of type "Wikimedia\Rdbms\DBQueryError"

This is the entirety of the error message that users like me can see, but presumably the server logs would record more details.

This error was previously reported in #533 as affecting some templates when viewed in English too, but we had worked around it by removing some offending template code. Unfortunately, the problem [appears to be more widespread](https://wiki.openstreetmap.org/wiki/Talk:Wiki#DBQueryError). The same error also affects [every category in Tagalog](https://wiki.openstreetmap.org/wiki/Special:PrefixIndex/Category:Tl:), probably because some template found on these categories happens to try to get the native name of the language. It also happens when you try to evaluate the following Lua code in a module:

```lua
mw.getLanguage("mr"):getFallbackLanguages() -- or substitute "pam" or "tl" as the language
```

> [234001f9f9d47316e744a75f] Caught exception of type Wikimedia\Rdbms\DBQueryError

We don’t have any Marathi or Kapampangan content on the wiki, other than some linguistic overarchitecting that Verdy_p did some years back, but we do have a fair amount of Tagalog content and users there.

It could be a red herring, but I noticed some chatter in [T251850](https://phabricator.wikimedia.org/T251850) about Marathi causing problems when [rebuilding the “localization cache”](https://www.mediawiki.org/wiki/Manual:RebuildLocalisationCache.php). The `LanguageFactory` mentioned in that ticket’s steps to reproduce is the class that produces the language objects that MediaWiki uses to obtain interface messages in a given language. I don’t know anything about the localization cache, but have we ever rebuilt it, and if so, did we see a similar series of errors?

/cc @Tigerfell

**Comment by tomhughes** [comment]
The localization cache is a pain in the arse and yes we have to take the wiki down while we rebuild it after every upgrade.

**Comment by 1ec5** [comment]
Just as mysteriously as this issue arose, it [vanished without a trace](https://wiki.openstreetmap.org/wiki/Special:Diff/2310980).
