### ISSUE TITLE
Enable 2FA requirement for osmfoundation Github organisation

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#607]
We will enable the 2FA requirement for the osmfoundation Github organisation later this year.

The following users need to [enable 2FA](https://github.com/settings/security) on their account or will they will automatically be removed from https://github.com/osmfoundation organisation when the 2FA requirement is enforced.

I propose 31st May 2022 as the deadline to enable 2FA.

We did the same for the Github OpenStreetMap organisation last year: https://github.com/openstreetmap/operations/issues/540

- [x] @amandasaurus amandasaurus Amanda
- [x] @hbogner hbogner Hrvoje Bogner
- [ ] @heatherleson heatherleson Heather Leson
- [ ] @PedaB PedaB
- [x] @tordanik tordanik Tobias Knerr
- [ ] @fredao fredao
- [ ] @aawiseman aawiseman Andrew Wiseman
- [x] @Jorieke Jorieke
- [ ] @pedrito1414 pedrito1414 Pete Masters
- [ ] @althio althio Benoît
- [x] @MarcoMinghini MarcoMinghini Marco Minghini
- [x] @dorotheakazazi dorotheakazazi Dorothea Kazazi
- [x] @frafra frafra Francesco Frassinelli
- [x] @napo napo Maurizio Napolitano
- [x] @mstock mstock Manfred Stock
- [x] @ovruni ovruni Omar Vega Ramos
- [x] @parpy parpy jmmapiranger
- [x] @arky arky Arky
- [x] @johnarupire johnarupire
- [x] @alesarrett alesarrett Alessandro Sarretta
- [x] @kateregga1 kateregga1 Geoffrey Katereggaand
- [x] @mcauer mcauer Michael Auer
- [x] @enockseth enockseth Enock Seth Nyamador
- [x] @rtroilo rtroilo Rafael Troilo
- [x] @redfrexx redfrexx Christina Ludwig
- [x] @lloos lloos Lukas Loos
- [x] @nissyyu nissyyu Yuichiro Nishimura
- [x] @AndrewHain AndrewHain
- [x] @yachaqruna yachaqruna YachaqRuna
- [x] @Gertrudeh Gertrudeh
- [x] @rkoeze rkoeze
- [x] @AleZena AleZena
- [x] @RhoBott RhoBott Kristin Bott
- [x] @Spartachetto Spartachetto
- [x] @JulianBruns JulianBruns
- [x] @craigallan craigallan Craig
- [x] @serenacoetzee serenacoetzee Serena Coetzee
- [x] @FabiKo117 FabiKo117 Fabian Kowatsch
- [x] @eluseful eluseful Yusuf Suleiman
- [x] @indiebio indiebio Bernelle Verster
- [x] @sidorelauku sidorelauku Sidorela Uku
- [x] @MelEckle MelEckle
- [x] @ikiya ikiya
- [x] @vannicer vannicer
- [x] @michaelgraaf michaelgraaf
- [x] @brvmnt brvmnt
- [x] @masain masain Sabrina Marx
- [x] @CarolinKlonner CarolinKlonner
- [x] @slautenb slautenb
- [x] @yair-grinb yair-grinb
- [x] @Girl-in-Geo Girl-in-Geo Laura Mugeha
- [x] @drolbr drolbr Roland Olbricht
- [ ] @rsavoye rsavoye Rob Savoye

Tracking in OpenStreetMap organisation as the osmfoundation does not have a similar tracker.

**Comment by tomhughes** [comment]
That seems like an extraordinary number of people to be members of the organisation anyway given it only has about 3 or 4 active repositories.

As with the openstreetmap organisation I suspect that most of them should just be removed and given collaborator access on the repos they need access to - organisation level access doesn't really work very well for organisations like ours that are umbrellas for lots of separate projects.

**Comment by arky** [comment]
+1 
Please kindly remove me from the organization as I haven't contributed for a long time.

**Comment by Firefishy** [comment]
@hbogner @heatherleson @PedaB @tordanik @fredao @aawiseman @Jorieke @pedrito1414  @althio @MarcoMinghini @frafra @napo @mstock @ovruni @arky @johnarupire @kateregga1 @rtroilo @redfrexx @lloos @nissyyu @yachaqruna @Gertrudeh @AleZena @RhoBott @Spartachetto @JulianBruns @FabiKo117 @eluseful @sidorelauku @MelEckle @vannicer @michaelgraaf @brvmnt @masain @CarolinKlonner @slautenb @yair-grinb @Girl-in-Geo

Please [enable 2FA on your github user login](https://github.com/settings/security). 

Alternatively please list in this ticket if you no longer require access, I am happy to add you back if later if desired.

**Comment by Jorieke** [comment]
Hi @Firefishy no need for me to be here at the moment! Thanks

**Comment by kateregga1** [comment]
Hi @Firefishy - I have enabled the 2FA

**Comment by Firefishy** [comment]
I have cleaned up repo membership of old repositories (e.g. SoTM 2019, SoTM LATAM, SoTM 2019 Book). If anyone had their membership removed and would like it back please enable 2FA on your account and message me and I'll immediately re-add you.

@drolbr @rsavoye You are new to the above list, please enable 2FA on your github accounts as listed above.

**Comment by Firefishy** [comment]
@heatherleson @PedaB @fredao @aawiseman @pedrito1414 @althio Please enable 2FA on your github account if you wish to retain access to the @osmfoundation organisation.

**Comment by Firefishy** [comment]
I've directly emailed the last 7 remaining users.

**Comment by Firefishy** [comment]
I have now enabled the 2FA requirement on the repo. 7 users without 2FA enabled on their github accounts were removed. I am more than happy to re-add them if they enabled 2FA on their accounts and message me.
