### ISSUE TITLE
Large number of emails in exim queue on shenron

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#61]
Backlog started just over a week ago

http://munin.openstreetmap.org/openstreetmap/shenron.openstreetmap/exim_mailqueue.html

![exim_mailqueue-month](https://cloud.githubusercontent.com/assets/360803/14674296/753d8c68-06fb-11e6-98ad-769ef1194697.png)

**Comment by tomhughes** [comment]
On 20/04/16 13:26, Andy Allan wrote:
> Backlog started just over a week ago
>
> http://munin.openstreetmap.org/openstreetmap/shenron.openstreetmap/exim_mailqueue.html
>
> exim_mailqueue-month
> <https://cloud.githubusercontent.com/assets/360803/14674296/753d8c68-06fb-11e6-98ad-769ef1194697.png>

Most likely yahoo hate us again. Doubt there is anything we can do.

Tom

-- 
Tom Hughes (tom@compton.nu)
http://compton.nu/

**Comment by tomhughes** [comment]
Nah, basically some spammer is trying to mass subscribe thousands of gmail addresses to the mailing lists.

No idea what the point is, but there's not much I can do about it.

**Comment by tomhughes** [comment]
I think I've managed to block the spammers now.
