### ISSUE TITLE
Upgrade wiki to MediaWiki 1.38

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/operations#610]
I am looking into adding the Translate extension to wiki and upgrading the wiki to MediaWiki 1.38 will [allow editors to use the Visual Editor when translating](https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/Add_Translate_extension_to_Wiki#Comments_from_a_developer) which is not possible with previous MediaWiki versions. This is a major plus.

Is there anything holding us back from upgrading at this time?

**Comment by tomhughes** [comment]
Yes, it hasn't been released yet.

**Comment by lectrician1** [comment]
... Well, yes that, but judging by how the wiki isn't 1.37, is there still anything?

**Comment by tomhughes** [comment]
I upgraded the other wiki's to 1.37 a few months ago but I usually leave it a while after I've done that before upgrading the main one in case any issues appear. We could probably do it now though.
