### ISSUE TITLE
Wikibase broken with mediaiwiki 1.37

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#611]
Despite trying to fix the Wikibase configuration in https://github.com/openstreetmap/chef/commit/ec0bc46d1275fc39a116736fc40372b0f6784fd0 and https://github.com/openstreetmap/chef/commit/c545095e765f5194c97275443cf73083a98690e2 is it still refusing to play ball since the 1.37 upgrade with:

```
[98d6aa4f789b746e983ef88e] [no req]   Exception: entitySources must be configured manually (or use the example settings)
Backtrace:
from /srv/wiki.openstreetmap.org/w/extensions/Wikibase/repo/config/Wikibase.default.php(325)
#0 /srv/wiki.openstreetmap.org/w/extensions/Wikibase/lib/includes/SettingsArray.php(68): Wikibase\Lib\WikibaseSettings::{closure}()
#1 /srv/wiki.openstreetmap.org/w/extensions/Wikibase/repo/WikibaseRepo.ServiceWiring.php(984): Wikibase\Lib\SettingsArray->getSetting()
#2 /srv/wiki.openstreetmap.org/w/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}()
#3 /srv/wiki.openstreetmap.org/w/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService()
#4 /srv/wiki.openstreetmap.org/w/includes/MediaWikiServices.php(279): Wikimedia\Services\ServiceContainer->getService()
#5 /srv/wiki.openstreetmap.org/w/vendor/wikimedia/services/src/ServiceContainer.php(424): MediaWiki\MediaWikiServices->getService()
#6 /srv/wiki.openstreetmap.org/w/extensions/Wikibase/repo/includes/WikibaseRepo.php(957): Wikimedia\Services\ServiceContainer->get()
#7 /srv/wiki.openstreetmap.org/w/extensions/Wikibase/repo/WikibaseRepo.ServiceWiring.php(1384): Wikibase\Repo\WikibaseRepo::getEntitySourceDefinitions()
#8 /srv/wiki.openstreetmap.org/w/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}()
#9 /srv/wiki.openstreetmap.org/w/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService()
#10 /srv/wiki.openstreetmap.org/w/includes/MediaWikiServices.php(279): Wikimedia\Services\ServiceContainer->getService()
#11 /srv/wiki.openstreetmap.org/w/vendor/wikimedia/services/src/ServiceContainer.php(424): MediaWiki\MediaWikiServices->getService()
#12 /srv/wiki.openstreetmap.org/w/extensions/Wikibase/repo/includes/WikibaseRepo.php(443): Wikimedia\Services\ServiceContainer->get()
#13 /srv/wiki.openstreetmap.org/w/extensions/Wikibase/repo/includes/RepoHooks.php(125): Wikibase\Repo\WikibaseRepo::getLocalEntitySource()
#14 /srv/wiki.openstreetmap.org/w/includes/HookContainer/HookContainer.php(338): Wikibase\Repo\RepoHooks::onSetupAfterCache()
#15 /srv/wiki.openstreetmap.org/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#16 /srv/wiki.openstreetmap.org/w/includes/HookContainer/HookRunner.php(3337): MediaWiki\HookContainer\HookContainer->run()
#17 /srv/wiki.openstreetmap.org/w/includes/Setup.php(732): MediaWiki\HookContainer\HookRunner->onSetupAfterCache()
#18 /srv/wiki.openstreetmap.org/w/maintenance/doMaintenance.php(90): require_once(string)
#19 /srv/wiki.openstreetmap.org/w/maintenance/update.php(264): require_once(string)
#20 {main}
```

I've disabled it manually for now.

Hopefully @nyurik has some idea what is going wrong here...

**Comment by nyurik** [comment]
I think this is related to the new settings required by wikibase -- see [local settings](https://www.mediawiki.org/wiki/Wikibase/Installation#Modify_LocalSettings.php).  It actually explicitly mentions which settings must be present and in what way. I haven't tried it yet, and will test it out shortly.

**Comment by tomhughes** [comment]
Yes that's what I added in https://github.com/openstreetmap/chef/commit/ec0bc46d1275fc39a116736fc40372b0f6784fd0 but despite it clearly setting `entitySources` it doesn't seem to help :-(

**Comment by nyurik** [comment]
ah, yes, i didn't notice that line, thx. I'll have to test it locally and will post something shortly. Do you have any running instance with a production-like config?   BTW, eventually i think we should build a docker container that we can run Chef against so that we can locally test upgrades.

**Comment by tomhughes** [comment]
We are able to test it in test kitchen, and indeed https://github.com/openstreetmap/chef/runs/6181201100?check_suite_focus=true is currently failing because of this. I should have let that run before doing the live update...

**Comment by mmd-osm** [comment]
Looking at the wikibase source code, it seems there's some property called `defaultEntityNamespaces`, which needs to be present somehow. If it can't be found, it would trigger the exception "entitySources must be configured manually (or use the example settings)"

https://github.com/wikimedia/Wikibase/blob/master/repo/config/Wikibase.default.php#L343

Now, https://www.mail-archive.com/wikidata-bugs@lists.wikimedia.org/msg220529.html has a bit of discussion on this flag, but I'm not sure about the implications.

**Comment by nyurik** [comment]
I'm still hacking on this - having some issues with setting up a local test site. Let me know if you have something running in test that could help.

**Comment by addshore** [comment]
`entitySources` should be set for both repo and client.
Right now in the code linked in this issue I only see client at https://github.com/openstreetmap/chef/commit/ec0bc46d1275fc39a116736fc40372b0f6784fd0#diff-976107d2c32132b6a7720c0effff868ffa51809ebec10df01734d9c1a665c369R92

See https://doc.wikimedia.org/Wikibase/master/php/md_docs_topics_entitysources.html

It suggests something like:

```
$entitySources = [
    'myrepo' => [
        'entityNamespaces' => [ 'item' => 120, 'property' => 122 ],
        'repoDatabase' => 'myrepodb',
        'baseUri' => 'SOME_CONCEPTBASEURI',
        'interwikiPrefix' => 'SOME_INTERWIKI',
        'rdfNodeNamespacePrefix' => 'SOME_NODERDFPREFIX',
        'rdfPredicateNamespacePrefix' => 'SOME_PREDICATERDFPREFIX',
        'type' => 'db'
    ],
];
$wgWBRepoSettings['entitySources'] = $entitySources;
$wgWBRepoSettings['localEntitySourceName'] = 'myrepo';
$wgWBClientSettings['entitySources'] = $entitySources;
$wgWBClientSettings['itemAndPropertySourceName'] = 'myrepo';
```

**Comment by tomhughes** [comment]
https://github.com/tomhughes/openstreetmap-chef/commit/550059cc90173987d028546ed1a592bceefb4c25 is my first attempt... Waiting to see what https://github.com/tomhughes/openstreetmap-chef/actions/runs/2241166632 makes of it...

**Comment by nyurik** [comment]
dope, you beat me to it :D

**Comment by nyurik** [comment]
I do have a concern that https://github.com/nyurik/chef/commit/ec0bc46d1275fc39a116736fc40372b0f6784fd0 has introduced a number of new settings that might be incorrect - but hopefully at worst it will just not have any data

**Comment by nyurik** [comment]
I have added [an error message](https://wiki.openstreetmap.org/w/index.php?title=Module:OSMWikiBase&diff=prev&oldid=2316774) when Wikibase is not active.  I had no way of testing it, so in case Wikibase is reenabled but it is still showing an error, please revert.

Also, per addshore,  apparently 1.37 wikibase was never officially released.  I'm not certain where we should have checked that, TBD for later.

**Comment by nyurik** [comment]
Cross-linking to the Wikibase community Telegram channel https://web.telegram.org/z/#-1478172663

**Comment by tomhughes** [comment]
My version (with a further tweak or two) has now successfully passed in test kitchen...

**Comment by tomhughes** [comment]
Now successfully deployed to production.

**Comment by nyurik** [comment]
It's alive!!!  Thanks @tomhughes .  @mmd-osm i don't see your comment for some reason

**Comment by mmd-osm** [comment]
@nyurik : I removed it in the meantime, it was referring to this post: https://www.mail-archive.com/wikidata-bugs@lists.wikimedia.org/msg220529.html and this line here: https://github.com/wikimedia/Wikibase/blob/master/repo/config/Wikibase.default.php#L312

Not super important now that Wikibase is up and running again.
