### ISSUE TITLE
New version of osmdbt available

### ISSUE THREAD

**Issue by joto** [openstreetmap/operations#613]
I have released a new version 0.5 of [osmdbt](https://github.com/openstreetmap/osmdbt/) (version 0.4 was a dud).This is one fix needed for the `osmdb-fake-log` program for PostgreSQL 14 and a bunch of code cleanups. You should upgrade to this version.

**Comment by tomhughes** [comment]
What's the use of `osmdb-fake-log` exactly? Only we're planning to upgrade Postgres fairly soon...

**Comment by tomhughes** [comment]
So we're using a built from source version of v0.2 for the database extension which I can update in chef, and dpkg of v0.3 that @mmd-osm built for the client.

**Comment by mmd-osm** [comment]
I uploaded 0.5 to launchpad, it will take a while to build. Let's see if this works... https://launchpad.net/~mmd-osm/+archive/ubuntu/osmdbt-005/+packages

**Comment by mmd-osm** [comment]
Build should be ok now. It took more than four hours before it even started.

**Comment by tomhughes** [comment]
Now deployed.
