### ISSUE TITLE
Is firnan working?

### ISSUE THREAD

**Issue by kocio-pl** [openstreetmap/operations#614]
Hi,

Is firnan (tile server located in Poland) working? It was announced by EPIX (hardware donor) on 22.12.2020 that it's already serving, but it seems that HTTP(S) ports are closed and the disk is empty:

https://munin.openstreetmap.org/openstreetmap.org/firnen.openstreetmap.org/index.html#disk

**Comment by tomhughes** [comment]
That's part of the old tile CDN so it hasn't been in use for well over a year.
