### ISSUE TITLE
thorn-02 chef not running?

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#62]
Ironbelly reports that thorn-02 hasn't had a chef run for over a week now:

http://munin.openstreetmap.org/openstreetmap/ironbelly.openstreetmap/chef_status.html

It's worth attention due to the upcoming server moves/outages at Imperial.

**Comment by tomhughes** [comment]
Machine looks fucked (ps hanging) so suggest  reboot but am away this week.

**Comment by tomhughes** [comment]
Rebooted, and chef completed.
