### ISSUE TITLE
Scheduled loss of redundant power at Amsterdam

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#621]
Equinix will be performing 5 year maintenance on the MDP-A/MCC-A power at AM6, resulting in switching one of the feeds off for up to 8 hours on SATURDAY, 11 JUN 20:00 - SUNDAY, 12 JUN 04:00 UTC.

We should check
- [ ] all power supplies are functional
* [ ] note down any equipment switched off
- [ ] verify that equipment is still switched off after maintenance work

**Comment by Firefishy** [comment]
https://hardware.openstreetmap.org/servers/dulcy.openstreetmap.org/ has a failed PSU and could experience an outage.

**Comment by Firefishy** [comment]
Update: OpenStreetMap services failed last night during the power outage.

The initial understanding is the Cisco RPS 2300 (dual redundant power feed device) failed which brought down our switches and upstream network connection.

Once AM6 power maintenance work was completed the power was returned and our switches returned to operation.

**Comment by Firefishy** [comment]
Outage was from 20:15 (UTC+1) until 4:47am (UTC+1).
