### ISSUE TITLE
Purchase next db server

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#63]
We're now at the stage of purchasing the next database server. Current status is with @zerebubuth for refreshing the NVMe server quote from the suppliers.

**Comment by zerebubuth** [comment]
Quote came back at a similar level - a couple of hundred quid cheaper. Since there were no objections, the purchase has gone ahead and we should be hearing about ETA sometime in the next week or so.

**Comment by gravitystorm** [comment]
Yay! If I was into gifs and emoticons, there would be one here.

**Comment by zerebubuth** [comment]
See [karm](https://hardware.openstreetmap.org/servers/karm.openstreetmap.org/), was racked up in #76 and currently undergoing testing and "burn-in" #78.
