### ISSUE TITLE
Report of Heavy load - May 29, 2022

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/operations#630]
Until >10:00 UTC, https://www.openstreetmap.org/ website returned Heavy Load error. Situation seems to be stabilising.
Do you know the cause of this?

("increasing" below means taking longer. sorry for present tense)

Response time on API HTTPS is increasing as of at least May 29 0:00 (UTC)

![image](https://user-images.githubusercontent.com/67521919/170862776-50b4aa43-253c-4504-9e2a-8dec4f8c83da.png)

Response time on Website HTTPS is increasing as of at least 01:00 (and is plateauing as of 10:00 seen on refresh?).

![image](https://user-images.githubusercontent.com/67521919/170862605-50feec44-1c59-438c-8bab-ea3cc61f27a0.png)
![image](https://user-images.githubusercontent.com/67521919/170863572-6e68e933-b98e-405e-847a-e70a8d6e5d31.png)

At 06:21:10, the website temporarily went 'down'.

![image](https://user-images.githubusercontent.com/67521919/170862712-c05a31c8-c4c5-46f5-a323-7111424d3745.png)

Response time on Website HTTPS (spike-01, spike-04, spike-05) is increasing as of at least 09:00.

![image](https://user-images.githubusercontent.com/67521919/170863374-262d01fc-dd30-42a5-a6a6-901ef80d306c.png)

![image](https://user-images.githubusercontent.com/67521919/170863401-f9dd8dbc-aa90-4e11-a22a-9a20c4efdaef.png)

![image](https://user-images.githubusercontent.com/67521919/170862902-0c18379e-8b27-4c54-b598-44531f02de09.png)

Response time on API HTTPS (capabilities) and Website HTTPS (spike-6) seems to be only very slowly returning to normal.

![image](https://user-images.githubusercontent.com/67521919/170863074-ae320d96-9861-4395-8e32-a2dda79b418d.png)

![image](https://user-images.githubusercontent.com/67521919/170863125-e2e5587b-35ff-49f5-aa47-62d7902f9718.png)

Response time on Website HTTPS (spike-07) seems to be quickly returning to normal after 09:00.

![image](https://user-images.githubusercontent.com/67521919/170863168-5b73db85-d0df-420a-a59a-ffd00b88594f.png)

Response time on Website HTTPS (spike-08) seems to be plateauing after increasing until 09:00.

![image](https://user-images.githubusercontent.com/67521919/170863225-2422b0ba-6ec5-496f-a975-86c02d380dfb.png)

Response time on Render HTTPS (paris/albi) seems to have had two spikes at 01:00 and 04:00.

![image](https://user-images.githubusercontent.com/67521919/170863320-e35114bc-c342-4047-9193-8fa4dc194561.png)

Response time on Nominatim HTTPS (longma) seems to have had one spike at 01:00.

![image](https://user-images.githubusercontent.com/67521919/170863456-d39ed4bb-d08c-4f9d-b27a-c6cdfdf1c7eb.png)

**Comment by tomhughes** [comment]
As you observe this was already picked up by our monitoring and fixed.

**Comment by danieldegroot2** [comment]
Ok. If possible, let me know the cause.

**Comment by Firefishy** [comment]
@danieldegroot2 The www site was overloaded by a torrent of traffic from someone using a bridge from www to nominatim. We blocked the user overloading the site and and improved timeout was deployed to the site: https://github.com/openstreetmap/openstreetmap-website/commit/eea25bd1546a42b783ffffb4d0c794d59e643597

Feel free to ask me if you would like any further details ;-)
