### ISSUE TITLE
Scheduled network outage with Cogent

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#632]
> As a valued customer, Cogent is committed to keeping you informed about any changes in the status of your service with us. This email is to alert you regarding maintenance we will be performing on our network: 
> 
> Start time: 00:00 CEST 11-JUN-2022
> End time: 05:00 CEST
> Work order number: NC925-102
> Order ID(s) impacted: 1-300246244
> Expected Outage/Downtime: 45-60 minutes
> Location: Amsterdam

We should fail over to Dublin in advance of this, or, if it's not ready, to the UK.

**Comment by tomhughes** [comment]
There is no reasonable way for us to plan and execute a failover in that timeframe.

**Comment by tomhughes** [comment]
Basically we should tell Cogent that six days notice for a 5 hour at risk window with a 1 hour downtime is just a fucking joke.

**Comment by pnorman** [comment]
This is done.

**Comment by mmd-osm** [comment]
Is the current AMS outage somehow related to this? It started at about 2022-06-11 20:20 UTC.

**Comment by grischard** [comment]
@mmd-osm it might be #621 hitting Cogent.

**Comment by tomhughes** [comment]
It is #621 yes. I believe the issue is the network switch which I assume is only single powered, or rather I think the two switches are each on one feed but the uplink is on the one with no power.
