### ISSUE TITLE
Forum announcements not visible on default Air3 style

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap/operations#634]
Hi,
Regarding #604 : there's a message about the migration, but it's not visible in the now-default Air3 forum style:

Air3 (default style):
![image](https://user-images.githubusercontent.com/1409116/172912882-d9b9ba25-1e22-494b-891b-456319995e77.png)

Air (previous style):
![image](https://user-images.githubusercontent.com/1409116/172912994-eae77a29-7c8f-4aaf-8ae3-c37785d79079.png)

This is due to an omission of `<pun_announcement>` in main.tpl:

https://github.com/fluxbb/fluxbb/blob/b958c04d30a4d5d9e716f930c4c3846887c34f69/include/template/main.tpl

vs 

https://github.com/natrius/air3/blob/master/Air3/main.tpl

**Comment by tomhughes** [comment]
The issue tracker for that skin can be found at https://github.com/natrius/air3 and that would be the correct place to report this.

**Comment by RicoElectrico** [comment]
Alright then, I was directed by kocio (one of the forum admins) to post here.

**Comment by tomhughes** [comment]
I did check and we appear to be running an unmodified version of the upstream skin. I suspect upstream is not very active though.

**Comment by Firefishy** [comment]
PR to fix the missing announcement message: https://github.com/natrius/air3/pull/12
I have manually hacked the support into forum.osm.org
