### ISSUE TITLE
OSM Wiki is down

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#636]
https://wiki.openstreetmap.org/ appears to be not reachable, and not only from my computer (see say https://www.isitdownrightnow.com/wiki.openstreetmap.org.html for easily done verifiable check)

**Comment by matkoniecz** [comment]
seems to be https://twitter.com/OSM_Tech/status/1533555914351030274

> [#OpenStreetMap](https://twitter.com/hashtag/OpenStreetMap?src=hashtag_click) services are likely to be disrupted on the 11 June 2022 between 00:01 CEST (UTC+2) until 05:00 CEST due to scheduled network maintenance by our ISP. Unfortunately unexpectedly short notice of the work given by our ISP.

**Comment by tomhughes** [comment]
No it's not that, that was last night. It's #621.
