### ISSUE TITLE
Increase US rendering capacity

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#637]
pyrene, the one US rendering server, no longer has the capacity to keep up with its demand. (https://github.com/openstreetmap/operations/issues/625#issuecomment-1146706362, and other reports) I was able to relieve some of the pressure by sending significant east coast US traffic to Europe, but sending IAD, EWR, LGA, YYZ, and MIA across the Atlantic is not ideal.

I see three options
1. Get some [donated capacity](https://wiki.openstreetmap.org/wiki/Servers/Tile_CDN), ideally on the US east coast. If someone reading this is able to help or can point us at someone to help, please email operations@osmfoundation.org. Anywhere in the US or Canada would work.
2. Buy a new server and send it to OSUOSL
3. Buy a new server and find a location on the East Coast to host

My preferred order is 1, 2, 3. I would rather not add another location we have hardware in for just one server.

**Comment by tomhughes** [comment]
No this has nothing to do with torrents.

**Comment by SmittyHalibut** [comment]
I can get you free space on the US west coast, Fremont, CA to be exact. What do you need? A virt? Physical space for a server you already have? You need someone to provide you a server? 

How much CPU/RAM/Disk would you expect it to consume? Network bandwidth?

**Comment by pnorman** [comment]
1 would have no costs for the OSMF. 2 and 3 cost about 7k USD in the past when we got new servers in Europe, but supply shortages will have increased costs since then.

**Comment by Firefishy** [comment]
@ke4qqq Thank you. I will reach out to you via email shortly.

**Comment by pnorman** [comment]
Current plans are to set up a rendering server on AWS (#682) but to also replace pyrene, which has a CPU that is 9 years old, spinning hard drives, and only 2.8TB in RAID5. We can use this issue to track replacing Pyrene.

Pyrene is owned by OSM US.

- [ ] Confirm with OSUOSL that we can have another machine hosted there
- [ ] Reach out to OSM US to see if they're interested in replacing the machine, or if the OSMF would be getting an additional machine
- [ ] Figure out specs. My inclination is we want >4TB of storage over the lifetime of the machine

**Comment by mcawley** [comment]
In conversations for locating a server in Arizona and also getting University of Arizona support to price out what we need as far as funding. Will connect via email.

**Comment by pnorman** [comment]
Current DB size is 1.1TiB, est. size in 5 years is 2TB. The tile store is tougher to measure, because it will consume as much space as its given, and more space is always good for cache hit ratios. We run [an daily cleanup job](https://github.com/openstreetmap/chef/blob/77487a96cb7b705cc55d8b39605bb86332367c51/cookbooks/tile/templates/default/cleanup-tiles.erb) that, if >88% of space is used, removes files not accessed in the last 2 days until 80% of disk space is used.

pyrene, with about 1.3TiB of tile store is having to do automated sweeps of old tiles multiple times per day, too often. Nidhogg and Culebre, splitting the metatiles between them, have about 2TiB of tile store each, and take 2-4 days to get from 80% to 88%.

Given the above, I would want >2TB of tile storage for a US server in 5 years, so a total >4TB, which means a 7.68TB disk.

**Comment by pnorman** [comment]
piasa is now running, so we have enough capacity, and it should remain enough once pyrene is shut off.
