### ISSUE TITLE
bowser down

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#638]
bowser has been down since June 9th. It's one of the rendering servers in Australia. They were contacted on the 9th, it's worth another contact since we haven't had a reply.

**Comment by Firefishy** [comment]
The server did not return after a reboot. The kernel was upgraded to latest Ubuntu 20.04 HWE kernel.

We have previously had a problem with the machine changing "static" NIC names on a reboot.

**Comment by tomhughes** [comment]
This is now back.
