### ISSUE TITLE
OSM Wiki is again unusually slow

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#640]
OSM Wiki in general is quite slow but today it is absurdly slow, all pages load for several seconds.

Other OSMF hosted services work fine.

Is it again

> A scraper was trying to use http://overpass.openstreetmap.fr/ which was then following the redirect to https://wiki.openstreetmap.org/wiki/Servers/overpass.openstreetmap.fr and overloading the wiki server. 1,884,121 requests today.

from  #627 ? Or something else fixable?

**Comment by mmd-osm** [comment]
The wiki server "tabaluga" shows pretty high CPU load : https://munin.openstreetmap.org/openstreetmap.org/tabaluga.openstreetmap.org/cpu.html

Somewhat usual that the CPU load was fairly in the past and suddenly started to increase in Feb 2022. overpass.openstreetmap.fr was shut down end of January 2022: https://github.com/osm-fr/infrastructure/issues/323

I'll open an issue on their repo and ask them to remove the redirect to the OSM wiki.

**Comment by matkoniecz** [comment]
So I guess that it is fixed?

Seriously, what kind of person manages to run DDOS by mistake, for months, by trying to scrap nonexisting API.

**Comment by mmd-osm** [comment]
Probably that’s quite easy to screw up in case you’re using some random piece of code you found on the internet that does some load balancing across servers under the hood.

**Comment by matkoniecz** [comment]
But still, not logging errors? Maybe I overestimate people and quality of such code that can be found...
