### ISSUE TITLE
Redundant network connections in Dublin

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#642]
Dublin is currently just a single uplink.

- [x] Ask HE for quotes

**Comment by Firefishy** [comment]
We now have final quotes for replacing the links in Dublin and Amsterdam. Both links will be replaced by bonded 1Gb links.

**Comment by Firefishy** [comment]
View of the fibre patch panel (open):
![001](https://github.com/openstreetmap/operations/assets/248188/aefa4814-f7b8-4dc8-9ba7-7de31a4b8b42)

View of the fibre patch panel (closed)
![002](https://github.com/openstreetmap/operations/assets/248188/2196da2b-1668-4b82-8719-34a6a3563a96)

View of the patches wired to junipers:
Switch-1 U15 port 3 to PPP:0115:1254967 port 1
Switch-2 U13 port 3 to PPP:0115:1254968 port 2
![003](https://github.com/openstreetmap/operations/assets/248188/9ab14ae6-0ec4-432b-b176-ea8d77c16233)

**Comment by Firefishy** [comment]
We have gone ahead with static routing. We are now live on 1x 1G link. 1x 10G needs to be re-patched to 1G module.

**Comment by grischard** [comment]
@Firefishy has submitted the Equinix remote hands to move the 10G patch to the 1G module.

**Comment by Firefishy** [comment]
Both links are live and fully operational.

**Comment by Firefishy** [comment]
Photo of the new cable locations:
![Patch Cable moved](https://github.com/openstreetmap/operations/assets/248188/e89d0fbb-77ef-49e5-bc33-1c4a8f3f5a94)
