### ISSUE TITLE
Back up network configs with oxidized

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#643]
https://github.com/ytti/oxidized - rancid successor.

**Comment by Firefishy** [comment]
- Juniper:[ Notes on adding a cfg-view only user for oxidized](https://github.com/ytti/oxidized/blob/master/docs/Model-Notes/JunOS.md)
- [Cisco Small Business Switch](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ciscosmb.rb)

**Comment by Firefishy** [comment]
Devices:
- switch1.ams.openstreetmap.org (includes switch2) - CiscoSB
- switch1.dub.openstreetmap.org - Juniper
- pdu1.ams.openstreetmap.org - APC
- pdu2.ams.openstreetmap.org - APC
- pdu1.dub.openstreetmap.org - APC
- pdu2.dub.openstreetmap.org - APC

**Comment by Firefishy** [comment]
Working well now. Closing.
