### ISSUE TITLE
OSM server status api

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/operations#644]
Hi,

related to https://github.com/pietervdvn/MapComplete/issues/880
I was wondering if there is a service that can be api checked to see if osm infrastructure is running normally (or if there are issues, or if there is maintenance).

Might be useful for editors (iD, JOSM, Mapcomplete, Streetcomplete, etc...) to be able to show users that their editor/app isn't having issues, it's OSM itself.

**Comment by tomhughes** [comment]
No there isn't, and I don't see how there could be - how would it work? We have alerting obviously for the admins but you wouldn't want ever minor alert to cause every editor to suddenly stop.

When there's a planned outage we display appropriate notices and when there's an unplanned outage we're usually too busy fixing it to spend time putting up pretty notices.

**Comment by thibaultmol** [comment]
I guess the problem is that currently there is no way to easily pull up those notices.

I'm not suggesting editors just stop. But if there is an outage or maintenance, it would be useful to tell the user that before they start editing or during editing, so if there is an error, they know it's not the app's fault.

I guess this could be done using one of the many uptime services like UptimeRobot, where you can plan maintenance windows (which apps/editors can then api to them to see when to display messages) https://blog.uptimerobot.com/new-feature-maintenance-windows-for-the-pro-plan/

**Comment by mmd-osm** [comment]
More specifically, if the database is in Tag only mode, you get an http bad request along with an error message like „Server is currently in read only mode, no database changes allowed at this time“.

**Comment by mmd-osm** [comment]
NB: Anyone noticed that the old forum and other sites using OAuth are be impacted as well when the central db is read only mode? I wasn't able to log in and reply to a post to comment on a post how long the read-only would last. As the old forum is still using Basic Auth, this was a bit unexpected.

**Comment by tomhughes** [comment]
That is around the time it was broken, where the requests being processed fell to zero:
![image](https://user-images.githubusercontent.com/147741/175016301-01b9661d-d03f-488e-a9f8-6ab282ab83b2.png)
