### ISSUE TITLE
Audit power connectivity in CAGB402

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#65]
We need to audit which machines are dual connected, and ensure each machine is connected to different PDUs in the various racks.

**Comment by zerebubuth** [comment]
There are 4 machines currently in CAGB402:

1. [spike-01](https://hardware.openstreetmap.org/servers/spike-01.openstreetmap.org/), dual PSU and plugged into both UPS and mains. Location: M2-522/7
2. [thorn-01](https://hardware.openstreetmap.org/servers/thorn-01.openstreetmap.org/), dual PSU and plugged into both UPS and mains. Location: M2-522/21
3. [orm](https://hardware.openstreetmap.org/servers/orm.openstreetmap.org/), dual PSU and plugged into both UPS and mains. Location: M2-324/20-23
4. [ouroboros](https://hardware.openstreetmap.org/servers/ouroboros.openstreetmap.org/), dual PSU and plugged into both UPS and mains (as of now, was plugged into 2x mains until today). Location: M2-324/15

**Comment by tomhughes** [comment]
What about their network connectivity? What power is that dependent on?

**Comment by zerebubuth** [comment]
Spike-01 and thorn-01 are patched into the switch in CAGB401, so aren't dependent on power in CAGB402. The internal networking gear in CAGB402 is dual-powered, but I'm not sure if orm and ouroboros are patched next-door, or connected to networking gear in the same room as they're in.
