### ISSUE TITLE
Wiki is down

### ISSUE THREAD

**Issue by mnalis** [openstreetmap/operations#650]
Wiki is acting up again right now (2022-06-20 at 14:21:09 CEST), BTW.

Slowness, `503 Service Unavailable` and finally now `Firefox can’t establish a connection to the server at wiki.openstreetmap.org`.
It's shown as down on https://uptime.openstreetmap.org/ too.

**Comment by mnalis** [comment]
Typical. After I try for 15 minutes and see it is still down, and post the issue, the problem seems to resolve itself.

Now wiki.openstreetmap.org works again, but it might be worth looking into why it happened, as those `503` might indicate problem on server software, and not transient network outages.

**Comment by tomhughes** [comment]
@Firefishy took the machine down to replace a failed battery.

**Comment by Firefishy** [comment]
Issue was short maintenance to replace failed battery. I announced in Slack US and IRC before power down. There is a chance there will another brief outage today.

**Comment by mnalis** [comment]
Although wiki works, many images are not shown, even after multiple attempts to refresh. Is that to be expected?

e.g.
![Screenshot 2022-06-20 at 14-49-43 Tag emergency=fire_hydrant - OpenStreetMap Wiki](https://user-images.githubusercontent.com/156656/174606612-9a5a9dad-ddf7-4890-bec4-6214e6b762ed.png)

**Comment by tomhughes** [comment]
That's a known issue that has other tickets I think, if they're coming from commons at least.

It also might be that caches and things are still warming up after the reboot.
