### ISSUE TITLE
After wiki.osm.org reboot, many images are not available 

### ISSUE THREAD

**Issue by mnalis** [openstreetmap/operations#651]
After machine was taken down for battery replacement in https://github.com/openstreetmap/operations/issues/650 and brought back up, many images are not showing, even after multiple attempts over half an hour to force-refresh the page.

e.g.:
![Screenshot 2022-06-20 at 14-49-43 Tag emergency=fire_hydrant - OpenStreetMap Wiki](https://user-images.githubusercontent.com/156656/174607765-cbbf4837-ebea-4615-ba6f-32ab7de3c33b.png)

**Comment by matkoniecz** [comment]
It seems that locally hosted files, invalidly cached ones ( https://wiki.openstreetmap.org/wiki/Talk:Wiki#Polymorphic_image ) work, while one referencing Wikimedia Commons stopped being shown.

**Comment by tomhughes** [comment]
I think this is fixed now - the clock was way off so DNS resolution was failing as DNSSEC is enabled.
