### ISSUE TITLE
Configure Juniper EX4300 switches @ AMS

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#657]
Switches need to be configured. This can be done by connecting them via USB Serial to the OOB device @ AMS.

After https://github.com/openstreetmap/operations/issues/656 completed

**Comment by grischard** [comment]
Playbook at https://github.com/openstreetmap/operations/wiki/AM6-Replace-Switch includes configuration

**Comment by grischard** [comment]
The switches have been installed, etc.

The last thing that's left to do is document the switch ports from the MAC address tables for https://github.com/openstreetmap/operations/wiki/AM6-Rack

**Comment by Firefishy** [comment]
Done and linked to Oxidized
