### ISSUE TITLE
Grindtooth (taginfo) chef runs missing

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#66]
Grindtooth hasn't checked in with chef for around 68 days.

http://munin.openstreetmap.org/openstreetmap/ironbelly.openstreetmap/chef_status.html

**Comment by tomhughes** [comment]
That's because it's not turned on :-)

**Comment by gravitystorm** [comment]
How does the magic work on munin to ignore the long-dead servers? Ones such as ascalon, idris etc just get `:` in their warn and critical columns. I can't find the magic in https://github.com/openstreetmap/chef/blob/master/cookbooks/munin/files/default/plugins/chef_status so it must be magic somewhere else.

**Comment by tomhughes** [comment]
Well the problem is that it's circular - munin drops them if hey stop checking into chef, but we don't really want to stop complaining about them checking into chef because they have stopped checking into chef.

**Comment by pnorman** [comment]
I'm not sure what the issue was, but after several years, this is stale and no longer an issue.
