### ISSUE TITLE
Incident Report for outage on 11/12 June 2022 - 7 hours 27 minutes

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#661]
From **11 June 2022 20:18:43** until **12 Jun 2022 03:45:48** (7 hours 27 minutes) the OpenStreetMap.org website, edit API, planet and wiki were unavailable.

The outage was caused by the unexpected power failure of our primary network switch at our primary hosting site in Amsterdam, Netherlands.

Services unavailable:
* www.openstreetmap.org ([Tier 1](https://operations.osmfoundation.org/policies/classification/))
* api.openstreetmap.org ([Tier 1](https://operations.osmfoundation.org/policies/classification/))
* planet.openstreetmap.org ([Tier 1](https://operations.osmfoundation.org/policies/classification/))
* wiki.openstreetmap.org ([Tier 2](https://operations.osmfoundation.org/policies/classification/))

Services disrupted or reduced capacity:
* nominatim.openstreetmap.org ([Tier 2](https://operations.osmfoundation.org/policies/classification/))
* ~~tile.openstreetmap.org ([Tier 2](https://operations.osmfoundation.org/policies/classification/))~~
* forum.openstreetmap.org login ([Tier 3](https://operations.osmfoundation.org/policies/classification/))
* community.openstreetmap.org login ([Tier 3](https://operations.osmfoundation.org/policies/classification/))
* help.openstreetmap.org login ([Tier 3](https://operations.osmfoundation.org/policies/classification/))

**Comment by pnorman** [comment]
I'll double check Prometheus but I don't think the tile service was impacted. Nidhogg should have been able to take all of Odin's load.

**Comment by pnorman** [comment]
Confirmed that the failover happened automatically and there was no impact on the tile service.

**Comment by pnorman** [comment]
Published in https://github.com/openstreetmap/owg-website/commit/e9089a73eb0f3385dbbf803fbc481a0ba1ae84a9, and will be part of the monthly report for June.

**Comment by Firefishy** [comment]
Published: https://operations.osmfoundation.org/2022/07/20/post-mortem.html
