### ISSUE TITLE
DMCA form is unfillable

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/operations#662]
[The DMCA form](https://dmca.openstreetmap.org/) looks like a Web form and even has interactive checkboxes and a Send button, but there are no fillable textboxes, just horizontal rules that look like lines to fill out on a printed form. Looking at the source code, there seem to be no `<input>` or `<textarea>` elements.

**Comment by Firefishy** [comment]
Will look into it. It is a PHP compatibility issue. We recently upgraded.

**Comment by Firefishy** [comment]
I have created a dedicated repo for the website and fixed the code: https://github.com/openstreetmap/dmca-website

I have not yet deployed it.

**Comment by Firefishy** [comment]
Fix deployed. Site should be working now.

Thank you for the report 👍
