### ISSUE TITLE
Define status of x-requested-with for tile usage

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#663]
Currently the [tile usage policy](https://operations.osmfoundation.org/policies/tiles/) requires a valid user-agent for apps.

About 750 TPS of requests come from apps which use a webview on android plus Leaflet, which sends a user-agent which is generic to the device, and in 20% of the cases the referer is localhost or blank. Instead of a meaningful UA and referer, we get the non-standard but widespread `x-requested-with` header

Currently we de-facto allow this. We should either write this in the tile usage policy, or notify users they need to send user-agent and referer headers, no x-requested-with.

I lean towards allowing it and updating the policy, even though I don't like the non-standard header.

**Comment by pnorman** [comment]
We will allow it and update the policy.

**Comment by grischard** [comment]
Do we log this too? Could it be part of the public access logs?

**Comment by pnorman** [comment]
> Do we log this too?

Yes

> Could it be part of the public access logs?

We don't currently publish any user-agent logs, but see https://github.com/openstreetmap/tilelog/issues/2
