### ISSUE TITLE
Migrate svn.openstreetmap.org away from shenron

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#665]
This is to track progress on migrating svn.openstreetmap.org away from shenron - the plan is to migrate it to a git repository on github (which provides svn access as well) and then archive that repository and host a simple site that redirects.

**Comment by Firefishy** [comment]
Currently I am trying to resolve the subversion `username` list to suitable git accounts.

**Comment by Firefishy** [comment]
The `svn.openstreetmap.org` repo now lives on github. The chef code is a skinny wrapper for redirecting requests there.

**Comment by Firefishy** [comment]
Moved role to lockheed in https://github.com/openstreetmap/dns/commit/91f3e2f9e3eda8b5621441a873c7a695b31aabd7 and https://github.com/openstreetmap/chef/commit/cca603bec99661631357eec859be3ec9085c6c4e

Final SVN backup including svn passwords (per https://github.com/openstreetmap/chef/commit/abb71dc00961ba66f2ec7989274b7b6950eed815) is `svn-2022-07-22.tar.gz`

Repo with conversion script to git is available here: https://github.com/Firefishy/osm-svn-convert-reposurgeon @tomhughes and @pnorman have invites. It contains the svn username = name + best github email I could find.

**Comment by Firefishy** [comment]
FYI: I have now forced a backup of `svn-2022-07-22.tar.gz` to S3 backup mirror due to https://github.com/openstreetmap/operations/issues/697
