### ISSUE TITLE
Migrate trac.openstreetmap.org away from shenron

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#666]
As part of winding down shenron we need to migrate the trac.openstreetmap.org redirector to a new host.

**Comment by Firefishy** [comment]
Moved to lockheed in https://github.com/openstreetmap/dns/commit/91f3e2f9e3eda8b5621441a873c7a695b31aabd7 and https://github.com/openstreetmap/chef/commit/cca603bec99661631357eec859be3ec9085c6c4e
