### ISSUE TITLE
Migrate blogs.openstreetmap.org away from shenron

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#668]
As part of winding down shenron we need to migrate the blogs.openstreetmap.org blog aggregator to a new host.

**Comment by Firefishy** [comment]
Moved as part of https://github.com/openstreetmap/dns/commit/50a4530529673151f4d4514a50ca43d908796f5d and https://github.com/openstreetmap/chef/commit/f9e3e2a61aca2a356d5e3f69b3f3f6f3c6986ce9

**Comment by Firefishy** [comment]
Database was manually migrated.
