### ISSUE TITLE
Rearrange database servers

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#67]
The electrical shutdown in CAGB401 means that we need to move a database machine out of the room to ensure availability. We can either put the new server in 402 (see #63 ) and sync it (delivery etc schedules permitted) or move one of the existing servers beforehand.

We also need to check that there's space in 402 for whichever server(s) we want to put there.

**Comment by zerebubuth** [comment]
It's not just the database servers - all our network connectivity currently goes via a switch in CAGB401, so we need to sort that out too. There appears to be a spare switch with our name on it (literally; "OSM-SW2"), so hopefully we can figure that out with the networks team.

**Comment by gravitystorm** [comment]
It turns out that we can't rearrange the servers within Imperial to any useful effect, and so a much larger project is being undertaken. I'm going to close this issue and break out all the tasks into parallel issues.
