### ISSUE TITLE
Figure out which machines to use as geodns servers

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#671]
We are currently announcing six machines as nameservers for `geo.openstreemap.org`:

```
geo.openstreetmap.org.	86400	IN	NS	katie.openstreetmap.org.
geo.openstreetmap.org.	86400	IN	NS	saphira.openstreetmap.org.
geo.openstreetmap.org.	86400	IN	NS	balerion.openstreetmap.org.
geo.openstreetmap.org.	86400	IN	NS	ridgeback.openstreetmap.org.
geo.openstreetmap.org.	86400	IN	NS	stormfly-04.openstreetmap.org.
geo.openstreetmap.org.	86400	IN	NS	chrysophylax.openstreetmap.org.
```

Only balerion and stormfly-04 are actually operational now...

The original set was chosen as a set of the more powerful nodes in the old tile CDN and with some attempt at geographic distribution.

**Comment by Firefishy** [comment]
I guess:
- [x] balerion 
- [x] stormfly-04
- [ ] 1 @ Equinix AM6 norbert?
- [ ] 1 @ Equinix DB4 horntail?

**Comment by tomhughes** [comment]
Probably a reasonable choice, yes...

**Comment by tomhughes** [comment]
This has been actioned, and the NS records are now generated automatically from chef as servers have the geodns role added.

**Comment by Firefishy** [comment]
Nice!
