### ISSUE TITLE
Content Security Policy broke the website.

### ISSUE THREAD

**Issue by michaelblyons** [openstreetmap/operations#672]
<img width="498" alt="Screen Shot 2022-07-03 at 5 10 36 PM" src="https://user-images.githubusercontent.com/2701605/177057367-bc2fce1c-b41d-40ed-b97c-5311c127b776.png">

As a consequence, the main CSS doesn't apply.

**Comment by tomhughes** [comment]
That makes no sense because `script-src` is about javascript not styles. Styles are controlled by the `style-src` rule.

**Comment by tomhughes** [comment]
More importantly why have you chosen to confuse matters by opening a second ticket here when there is a fuller, and far more accurate, discussion of this issue in the web site tracker.

**Comment by Firefishy** [comment]
@michaelblyons Thanks for the report. Flood of people spotted the issue. Confusingly not CSP related but an issue with related to enabling brotli compression.

**Comment by tomhughes** [comment]
As @Firefishy says this is nothing to to with CSP and I certainly wasn't seeing those errors. I suspect you have something injecting javescript into the page that is being blockec by the CSP but that was not the cause of the styling issues.

**Comment by michaelblyons** [comment]
Glad you got it worked out. 🙂 Initial response seemed a bit harsh, but that's not uncommon when one is bringing production back up.

**Comment by Firefishy** [comment]
FYI: some 3rd party virus scanners, firewalls or password managers inject content which violates our strict CSP.
