### ISSUE TITLE
The website is not loading properly due to Content Encoding Error

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/operations#673]
### URL

any openstreetmap.org page

### How to reproduce the issue?

1. Visit https://www.openstreetmap.org

### Screenshot(s) or anything else?

CSS files and the SVG logo are not loading. When I tried to open any of these files in a new tab, I get this error.
```
Content Encoding Error

An error occurred during a connection to www.openstreetmap.org.

    Please contact the website owners to inform them of this problem.
```

![image](https://user-images.githubusercontent.com/19364673/177056055-42c1aa6e-5154-47af-9c1c-69ecdd996df9.png)

**Comment by Firefishy** [comment]
Fix deployed.

**Comment by tomhughes** [comment]
Fixed by disabling brotli.
