### ISSUE TITLE
Arrange van and packaging for server moves

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#68]
We need to

- [x] hire a van
- [x] arrange parking at Imperial
- [x] order the server packaging for katla and grisu
- [x] find + bring or order katla spare disks

Any other real-world logistics to add to the list?

**Comment by gravitystorm** [comment]
I've added bringing the katla spare disks

**Comment by zerebubuth** [comment]
Parking is a bit of a pain, as the reg number needs to be known in advance. However, I've measured the back of my car and it seems we'd be able to fit 2 low stacks of servers (footprint 50x78cm according to [serverboxes](http://www.serverboxes.co.uk/)). I've ordered the boxes, and will test once they arrive (ETA tomorrow). I'm thinking that using my car will be both more convenient and allow less space for stuff to slide around.

@Firefishy does that sound right to you? Do you think we should get a van regardless?

**Comment by Firefishy** [comment]
Sounds ok to me, but remember we'll also have the 4x DL360 G7 machines too. I'll retain whatever packaging they come in.

**Comment by Firefishy** [comment]
@zerebubuth any luck with the spare disks?

**Comment by zerebubuth** [comment]
D'oh, forgot about that. I've got one of the 600GB ones here, might as well take that, although it's only suitable as an OS disk. I've ordered two 900GB ones, due on Saturday, to take too.

**Comment by zerebubuth** [comment]
Just noting: No van hire, it's a hassle and I've just checked that the boxes fit in the back of the car just fine.

**Comment by zerebubuth** [comment]
Parking fail at IC - there's the "Imperial College Festival" on, so no spaces are available. I'll use nearby pay & display. Suckage, but solveable. :disappointed:

**Comment by gravitystorm** [comment]
Do you need a third person to keep an eye on the car while you shuttle back and forth?

**Comment by Firefishy** [comment]
@gravitystorm Yes, that would be helpful.

**Comment by zerebubuth** [comment]
Spare disks arrived.

**Comment by gravitystorm** [comment]
Everything is on its way to the new datacentre
