### ISSUE TITLE
Discourage people from using git.openstreetmap.org

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#680]
git.openstreetmap.org exists for internal purposes related to deployment, and should not be where developers are normally going to get or contribute to OSM-related software.

We need to add a banner or front page directing people at the github repos.

**Comment by Firefishy** [comment]
I have updated:
- https://wiki.openstreetmap.org/wiki/Getting_The_Source
- https://wiki.openstreetmap.org/wiki/Potlatch_2/Developer_Documentation/git

**Comment by mmd-osm** [comment]
CGImap is over at https://github.com/zerebubuth/openstreetmap-cgimap - the mirror in the Osm GitHub org is pretty much outdated.

**Comment by Firefishy** [comment]
@mmd-osm My preference would be to move cgimap "master" to the https://github.com/openstreetmap/cgimap what do you think? cc: @zerebubuth 

My thinking is to have https://github.com/openstreetmap as the primary view for (new and old) developers contributing to core components of the project.

**Comment by mmd-osm** [comment]
https://github.com/zerebubuth/openstreetmap-cgimap/issues/160 has a bit of discussion on the topic (the minimized comments are the relevant ones). 

TBH, as long as it doesn't screw up the whole dev process, I don't really care that much where the repo resides.

**Comment by HolgerJeromin** [comment]
We could also delete github.com/osm/osm-cgi to reduce confusion with old code

**Comment by mmd-osm** [comment]
@HolgerJeromin not exactly sure what you mean, the link you’ve posted doesn’t work here.

**Comment by HolgerJeromin** [comment]
I meant removing the repo https://github.com/openstreetmap/cgimap to avoid confusion.

**Comment by Firefishy** [comment]
Added some text to https://git.openstreetmap.org/ via https://github.com/openstreetmap/chef/commit/ab3cf06

**Comment by leongal** [comment]
Hello Everyone!
Currently I am trying to deploy OSM to my VPS(Linux)
I deployed OSM into my Server by following this article [https://www.linuxbabe.com/ubuntu/install-osrm-ubuntu-20-04-open-source-routing-machine], [https://www.linuxbabe.com/ubuntu/osm-nominatim-geocoding-server-ubuntu-20-04 ]
And my question is, how can I check daily updates of Map Data(OSM)?
Is there any way to write a few log to check the daily updates of Map Data(I would like to check it console)?

**Comment by gravitystorm** [comment]
@leongal Please ask any technical support questions on https://help.openstreetmap.org/ or https://gis.stackexchange.com/

And in particular, it's considered rude to add comments to existing issues on completely unrelated matters. I will shortly hide both these comments as off topic.

**Comment by Firefishy** [comment]
I have updated the `cloneurl` displayed on git.openstreetmap.org for reach repo and updated the project descriptions.

With the home page banner and updated clone URLs, I think we are good.

**Comment by Firefishy** [comment]
PPS: @mmd-osm I have syned https://github.com/openstreetmap/cgimap and https://git.openstreetmap.org/cgimap.git
If desired I can hack up a script to keep them in sync, my personal preference would be for https://github.com/openstreetmap/cgimap to be the primary repo for manageability, visibility and authority reasons... But not too worried about it.

**Comment by tomhughes** [comment]
We can just get rid of the git.osm.org one - it's a hangover from when we deployed cgimap from source and that was the deployment repo.

**Comment by Firefishy** [comment]
> We can just get rid of the git.osm.org one - it's a hangover from when we deployed cgimap from source and that was the deployment repo.

Sounds like a good idea to me.

**Comment by tomhughes** [comment]
Done. Much the same applies to gpx-import, planetdump and potlatch2 I think. The first two aren't even used anymore...

Need to check if planetdump (the old one) is on github first. The other two are.

**Comment by tomhughes** [comment]
Yes it is, at https://github.com/openstreetmap/planetdump.

**Comment by mmd-osm** [comment]
> my personal preference would be for https://github.com/openstreetmap/cgimap to be the primary repo for manageability, visibility and authority reasons

Github supports fancy stuff like transferring a repo to another organisation. I can't really help here, as the repo belongs to @zerebubuth. I can't even change the repo description in case we want to switch primary and mirror roles. Collaborators really can't do all that much.

**Comment by mmd-osm** [comment]
> If desired I can hack up a script to keep them in sync

Keeping them in sync without any manual activity would be really useful. Right now, it's still mirroring the broken 0.8.7 release.

**Comment by tomhughes** [comment]
Isn't that one of avar's mirrors? So there should already be something keeping it in sync...

**Comment by mmd-osm** [comment]
Not sure if that script is still up and running. Before @Firefishy triggered a manual sync, the repo was last synced a few years back.

**Comment by pnorman** [comment]
I think it's better to get rid of the openstreetmap/cgimap repo, if matt's is going to be the primary.

**Comment by mmd-osm** [comment]
> I think it's better to get rid of the openstreetmap/cgimap repo, if matt's is going to be the primary.

Maybe that’s the better solution. Thr repo is still (again?) out of sync, and even points to a known to be broken release 😞

**Comment by Firefishy** [comment]
Planning on fixing it: https://github.com/openstreetmap/operations/issues/769
