### ISSUE TITLE
ysera load is jumping up/down

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#685]
![image](https://user-images.githubusercontent.com/1190866/179460356-22afac73-1808-4673-8ca8-0a4fb2a80a7d.png)

I considered that this might be a sampling artifact where conversion to a rate results in oddities, but the same is present on the CPU graphs

![image](https://user-images.githubusercontent.com/1190866/179460474-dbf1d5c0-5cc0-4282-a794-838d230fdd18.png)

**Comment by pnorman** [comment]
It's paired with culebre, which is showing normal load.

Relevant VCL

```vcl
director european_servers_0 random {
  { .backend = F_Odin___Amsterdam; .weight = 10; }
  { .backend = F_Nidhogg___Umea; .weight = 30; }
}
director european_servers_1 random {
  { .backend = F_Ysera___Slough; .weight = 10; }
  { .backend = F_Culebre___Dublin; .weight = 30; }
}
```

```vcl
declare local var.x_mod INTEGER;

if (server.region == "APAC" || server.region == "Asia" || server.region ~ "^Asia-") {
  set req.backend = australia;
} else if ((server.region == "North-America" || server.region ~ "^(US|SA)-")
&& server.datacenter != "IAD" && server.datacenter != "EWR" && server.datacenter != "LGA" && server.datacenter != "YYZ" && server.datacenter != "MIA" && server.datacenter != "DFW" ) {
  set req.backend = america;
} else {
  if (req.url.path ~ "^/([1-9]?[0-9]+)/([0-9]+)/([0-9]+)\.png") {
    // Compute the X metatile and split into two groups
    set var.x_mod = std.atoi(re.group.2);
    set var.x_mod /= 8;
    set var.x_mod %= 2;
    
    // Assign to different servers based on groups
    if (var.x_mod == 0 ) {
      set req.backend = europe_0;
    } else {
      set req.backend = europe_1;
    }
  } else {
    set req.backend = europe_0;
  }
}
```

**Comment by pnorman** [comment]
Turned off ysera at the CDN. No major impact on traffic. odin and nidhogg are spiking. Suspecting that there's someone using the tile server and bypassing the CDN.

**Comment by pnorman** [comment]
Restored the CDN to config it was over the weekend, but it's not changed anything.

Odin is badly off. Started at about 7 AM UTC
![image](https://user-images.githubusercontent.com/1190866/179467945-5802c8b9-447c-4cd0-a608-8746c1ff370b.png)

**Comment by pnorman** [comment]
Contacted Fastly support. Unsure what's going on.

**Comment by mmd-osm** [comment]
Pretty large amount of SYN SENT out there: https://munin.openstreetmap.org/openstreetmap.org/ysera.openstreetmap.org/fw_conntrack.html

**Comment by pnorman** [comment]
Graph of
```sql
SELECT COUNT(*), time FROM logs.fastly_logs_v18
WHERE year = 2022 AND month = 07 AND day = 18 AND hour = 08 AND render='odin.openstreetmap.org' and cachehit='MISS'
GROUP BY time ORDER BY time;
```

<img width="454" alt="fastly-odin-log-bysecond" src="https://user-images.githubusercontent.com/1190866/179475619-e09e5246-b2d2-4b48-a4fc-38ea1b954505.png">

**Comment by pnorman** [comment]
Removed odin from all_servers  and european_servers_all groups to see if it has any impact.

**Comment by pnorman** [comment]
> Removed odin from all_servers and european_servers_all groups to see if it has any impact.

No impact, as expected. Now removing odin completely from the CDN

**Comment by pnorman** [comment]
Bringing it back with a weight of 1 has brought the traffic up to the same level it had when it had a weight of 10

**Comment by pnorman** [comment]
I'm wondering if it's healthcheck related somehow. if nidhogg failed its healthcheck it would divert all of its traffic to odin, regardless of weighting.

Trying an adjustment by making the healthcheck only want 1/10 of checks to pass, with checks ever 5s.

**Comment by pnorman** [comment]
I changed the health check to 1/10 threshold & window, 1 initial, 5000s interval and it's changed the behavior.

The behavior is still not correct, there should be a 1:30 ratio between odin traffic and nidhogg traffic, but the fact that it changed indicates some connection with health checks.

<img width="553" alt="fastly-odin-nidhogg-healthcheck change" src="https://user-images.githubusercontent.com/1190866/179481538-cc607a6e-4619-4f5d-adbc-f9287f91fd47.png">

**Comment by pnorman** [comment]
Confirmed that servers were failing health checks - at least pyrene, nidhogg, and ysera. 

A cluster-wide apache restart has been completed, and that appears to have fixed it.

**Comment by pnorman** [comment]
A few things to investigate

## What was wrong that an Apache restart fixed?

The error `[Mon Jul 18 09:38:37.894876 2022] [mpm_event:error] [pid 2239:tid 140189126043520] AH03490: scoreboard is full, not at MaxRequestWorkers.Increase ServerLimit.` was observed

## What happened to Pyrene?
Pyrene stopped responding to all traffic at 2022-07-17T00:03:15Z. This is suspiciously close to midnight UTC.

## What monitoring do we need?
We had no monitoring that indicated that health checks were failing, and when I loaded tiles manually, everything worked, so it wasn't immediately obvious what went wrong.

## What alarms do we need?
Probably some apache ones, but perhaps also on monitoring of health checks

**Comment by pnorman** [comment]
Failover from US to Europe doesn't work as intended. `america` is defined as a fallback from pyrene to all_servers, which will put US traffic on the wrong even/odd servers. The same is true for Australia.

Each region needs its own even/odd split defined, even if the even/odd servers are the same. They can then fall back to the right servers in Europe

**Comment by pnorman** [comment]
The tile service experienced degraded service from 2022-07-18T07:30:00Z to approximately 2022-07-18T10:00:00Z, impacting an average of 4% of traffic during the event.

See graph of `sum(rate(fastly_rt_status_code_total{service_name=~"OSM Tiles CDN",status_code=~"404|5.."}[$__rate_interval]))/sum(rate(fastly_rt_requests_total{service_name=~"OSM Tiles CDN"}[$__rate_interval]))`
![image](https://user-images.githubusercontent.com/1190866/179648318-9c82d357-33a7-4149-be1f-0732effa901d.png)

**Comment by pnorman** [comment]
Published in https://github.com/openstreetmap/owg-website/commit/6fd72e793e24b4d2acd7b3818ddac240d5fd9444
