### ISSUE TITLE
Ensure Amsterdam servers are in balanced or power-saving mode

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#686]
From Equinix advisory notification 5-218621835985

> In the Netherlands, legislation requires owners and users of IT equipment to be as energy efficient as possible, so we are sharing information for your action to ensure compliance.
> Many server manufacturers and operating system suppliers have “Balanced Power Mode" or "Power-Saving Mode" settings for their equipment. Owners and users are required to activate this option unless there is an acceptable exception, such as demonstrable performance degradation under the setting. 
> Q: Am I obliged to implement this measure? 
> A: In compliance with Dutch legislation, owners of server equipment must implement measures that will pay for themselves within five years. Setting power saving or balanced power mode is part of this. 

ref: https://english.rvo.nl/information/laws-regulations/energy-efficiency-notification-obligation/energy-efficiency-obligation

**Comment by Firefishy** [comment]
- [ ] Ensure all our HPE servers have [Power Supply Mode set to High Efficiency Mode (Auto)](https://techlibrary.hpe.com/docs/iss/proliant-gen10-uefi/s_set_redundant_power_mode.html) via BIOS / UEFI.
- [ ] Ensure all our HPE servers are set to Balanced Performance via BIOS / UEFI or IPMI.
- [x] dulcy set fan speed to optimal (via ipmi)
- [x] ironbelly set fan speed to optimal (via ipmi)
- [x] karm set fan speed to optimal (via ipmi)
- [x] norbert set fan speed to optimal (via ipmi)
- [x] odin set fan speed to standard (no optimal) (via ipmi)
- [ ] snap-01 set fan speed to optimal (via ipmi)
- [ ] Power down unused machines (thorn-01, thorn-02, thorn-03)

**Comment by Firefishy** [comment]
thorn-02 & thorn-03 powered down.

**Comment by pnorman** [comment]
Looks good. We'll probably save some more when Europe isn't so hot.

We also have replacing the old power-inefficient machines in the budget.
