### ISSUE TITLE
Monitor Cisco Switch PSU status via SNMP

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#689]
Add monitoring to capture PSU status.

**Comment by tomhughes** [comment]
It's a bit of a pain to do but I know how to do it.... We can do the temps and fans as well by the looks of it.

**Comment by Firefishy** [comment]
All the interesting items are under: `1.3.6.1.4.1.9.6.1.101.53.15.1`

**Comment by tomhughes** [comment]
I still need to write some alerts but we have a [dashboard](https://prometheus.openstreetmap.org/d/CMu3T1R4k/switch-monitoring?orgId=1&refresh=1m) now:

![image](https://user-images.githubusercontent.com/147741/180198508-e0d11d8f-8701-4414-98e5-63d204bd6df7.png)

**Comment by tomhughes** [comment]
Alerts are now in place.
