### ISSUE TITLE
New RAM for Ramoth

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#69]
The RAM for RAMoth (ahaha) has been failing memtest. We're going to buy and fit replacements before the server move on 9th May

- [x] Purchase new RAM
- [ ] Fit to Ramoth and confirm working.

**Comment by gravitystorm** [comment]
RAM due for delivery to @Firefishy Wednesday before 9am.

**Comment by Firefishy** [comment]
RAM arrived Thursday before 9am after being delayed by a day. Likely going to return the RAM as memory tests in ramoth are passing.

**Comment by Firefishy** [comment]
RAM is no longer required. Closing ticket.
