### ISSUE TITLE
PDUs in AM6 require firmware update

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#691]
The PDUs in AM6 require a firmware. They are prone to losing IP networking and require reboot issued via serial console.

Upgrades and reboots do not alter PDU port supply status.

Model: AP8953
Current Firmware: v6.4.6

**Comment by Firefishy** [comment]
PDU 1 has successfully been upgraded to v7.0.6

Upgrade via Serial console using XMODEM via bootloader.

**Comment by Firefishy** [comment]
PDU 2 is automatically upgrading via guest control (bridge cable). Slow. ETA minimum 10 minutes.

**Comment by Firefishy** [comment]
PDU 1 has successfully been upgraded to v7.0.6

(via automatic guest update via link cable)

**Comment by LaJobe** [comment]
Hi @Firefishy, I also have 2 linked AP8953 PDUs to upgrade.
Could you please helping doing so ? I can't find the new firmware anywhere on APC/SE websites.

Thanks

**Comment by Firefishy** [comment]
> Hi @Firefishy, I also have 2 linked AP8953 PDUs to upgrade. Could you please helping doing so ? I can't find the new firmware anywhere on APC/SE websites.
> 

@LaJobe ...

The current latest firmware is available here: https://www.se.com/ww/en/download/document/APC_RPDU2G_708_EN/
I've used the serial XMODEM and the FTP methods described here reliably in the past: https://www.apc.com/us/en/faqs/FA156047/#XMOD
The utility for Window is also ok.

I always upgrade the lowest ID PDU first if they are linked. In some cases it appears the other PDUs will automatically trigger an update, they stop responding for ~10mins while upgrading, some of the time they respond to pings. In our case, each PDU has its own serial + ethernet as backup connectivity if the link between PDU stops working.

**Comment by LaJobe** [comment]
@Firefishy Thanks a lot for your quick and detailed answer !
As I'm working from a Mac I still have some stuff to learn before I can use XMODEM fluently… But thanks to your help, I'm on the good way with the good infos right now !

**Comment by Firefishy** [comment]
I use [minicom for xmodem transfers](https://ixnfo.com/en/how-to-transfer-a-file-via-xmodem-using-minicom.html) transfers. I installed minicom via homebrew. The FTP upgrade is likely easier. The ftp commands I use: binary, hash, put

**Comment by LaJobe** [comment]
All right thank you, might be easier for me from a Linux device. Reading your post I understand that I can run the process upgrade either with XModem **or** FTP. Is that correct ?

**Comment by Firefishy** [comment]
Correct, APC devices support multiple upgrade methods. FTP is likely easiest. XModem method can be tricky because you need to change serial baud speed to access the bootloader. XModem is likely the only method in the event of a (unlikely?) bad flash.
