### ISSUE TITLE
Monitor Fastly health checks

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#695]
Fastly's health checks determine where a POP routes its traffic, but we have no monitoring of their status. In the recent degraded tile service incident, this caused us to have no visibility that servers were failing some health checks because when manually queried the servers responded okay.

In general, Fastly will have a much better view on the health of the render servers, because they are querying from POPs around the world every few seconds. Additionally, in case of network problems, it's the Fastly health checks that matter, not other ones.

Fastly does not have an API for monitoring health checks, but one can [be written in VCL](https://support.fastly.com/hc/en-us/community/posts/360040444872-Monitoring-health-status-from-fastly-health-checks#:~:text=Regarding%20this%20topic%2C%20yes%2C%20we%27re%20aware%20of%20your%20needs%20as%20this%20is%20one%20of%20the%20frequently%20asked%20questions.) and then an API can be used to get the status from every POP.

- [x] Ask on Fastly forums/support if anyone has integrated health checks they describe with prometheus or other monitoring solutions
- [x] Set up synthetic API response with health status (temporary one done, but needs some cleanup)
- [ ] Set up monitoring of API with edge check

**Comment by tomhughes** [comment]
Pulling the data into prometheus from the edge check API is no problem - we could do it right now with the API response you setup.

**Comment by pnorman** [comment]
I've cleaned up the API. The headers in the response are all `x-hcstatus-<server>`, where `<server>` is the backend name

**Comment by tomhughes** [comment]
So it's ready for me to pull into prometheus?

**Comment by pnorman** [comment]
Yes - I'm not sure what permissions the fastly API token needs - hopefully the existing prometheus has everything necessary

**Comment by tomhughes** [comment]
I've added a backend status chart to the tile CDN dashboard - alerts to follow.

I don't seem to be getting any data for balerion though?

**Comment by tomhughes** [comment]
Fixed it - the status for balerion was being assigned to the ysera header.

**Comment by tomhughes** [comment]
Alert added in https://github.com/openstreetmap/chef/commit/faeb3b7259889dc1b789ea14c223b41a0b78116b.
