### ISSUE TITLE
AWS Database contingency

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#70]
- [x] Arrange an OSMF AWS account
- [x] Arrange the VM and EBS storage
- [x] Clearance from LWG
- [ ] Replicate database

**Comment by gravitystorm** [comment]
https://hardware.openstreetmap.org/servers/fafnir.openstreetmap.org/ is the machine at AWS

**Comment by Firefishy** [comment]
With kind help from @iandees we have received AWS credits which should cover us for the server. :-)

**Comment by tomhughes** [comment]
The replica reached a consistent recovery state at about 02:30 this morning and caught up completely and switched to streaming mode at 03:50 so we're good to go on this.
