### ISSUE TITLE
Failing Disk in Errol

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#701]
Failing disks in error need replacing:

```
Device: /dev/sg2 [areca_disk#05_enc#01], Self-Test Log error count increased from 2 to 3

Device info:
WDC WD2003FYYS-02W0B0, S/N:WD-WMAY00506800, WWN:5-0014ee-0ad1ed740, FW:01.01D01, 2.00 TB
```

**Comment by grischard** [comment]
See also #677 about replacing errol completely

**Comment by Firefishy** [comment]
The controller battery has also failed in the system.

**Comment by Firefishy** [comment]
https://gist.github.com/Firefishy/881aed7b6f9e9e4378f75c9256211643

**Comment by Firefishy** [comment]
Tasks:
- [ ] 1. One-off tar backup of all users to norbert.
- [ ] 2. Offline (single user mode) run `xfs_repair`
- [ ] 3. Manually Trigger RAID Controller RAID5 patrol read + repair to force remap bad sectors (across disks)
- [ ] 4. Replace Failing Disk (2TB spinning rust or entry level 2TB SDD) during site visit.

**Comment by Firefishy** [comment]
Option to Manually trigger patrol + repair (via `archttp64`)
<img width="604" alt="Screenshot 2022-08-14 at 04 30 36" src="https://user-images.githubusercontent.com/248188/184519223-a11b5a46-b4ce-406e-af7d-63e7416de662.png">

**Comment by Firefishy** [comment]
tar completed backup of all the users except: `ant`, `harrywood` and `mvexel` for who limited backups were created because they have millions of tiny cache files which would have significantly delayed completion.

**Comment by Firefishy** [comment]
Disk still causing minor issues, but fixed the system crashing. Th areca controller was not compatible with Ubuntu 22.04 kernel (5.15), reverted to Ubuntu 20.04 kernel (5.13) and the crashes have stopped.

**Comment by Firefishy** [comment]
Not going to replace disk. Faffy server is now up and will replace errol shortly.
