### ISSUE TITLE
Failed disk in scorch

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#703]
A disk appears to have failed in scorch, to the extent that `megacli` is only actually reporting on 3 physical disks, with no information given for disk 0 but the array marked as degraded.

Array is RAID 5 over four disks.

**Comment by pnorman** [comment]
Let's return it to OVH since we're not using it.

**Comment by Firefishy** [comment]
I reported the issue to OVH. Ticket: 6094652

**Comment by pnorman** [comment]
OVH has replaced the drive
