### ISSUE TITLE
Make fastly_healthcheck_status match other fastly metrics in labels

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#705]
fastly_healthcheck_status reports metrics with the pop label. Unfortunately, this doesn't match other metrics. This prevents properly integrating them in dashboards where the POP can be selected.

For POP, the fastly metric uses datacenter and reports upper-case airport codes. Unfortunately, the only way I can see to get airport code from the edge_check response is to parse the `server` attribute (e.g. `cache-fra19139`) to get the airport code, then upper-case it.

**Comment by tomhughes** [comment]
I think this is hopeless because the fastly naming is completely inconsistent. I suspect there is no way to automatically convert the pop names from the edge check response to the names from the API responses.

I deliberately left the pop names as they are because the names from the edge check response are actually much detailed than anything else I've ever seen.

Is there actually any need to compare those metrics with other ones?

**Comment by pnorman** [comment]
> I think this is hopeless because the fastly naming is completely inconsistent. I suspect there is no way to automatically convert the pop names from the edge check response to the names from the API responses.

That's why it needs to be from the `server` attribute, or I could add the POP as a header.

> I deliberately left the pop names as they are because the names from the edge check response are actually much detailed than anything else I've ever seen.

Yes, I like the names, but they don't work well.

> Is there actually any need to compare those metrics with other ones?

Yes. If I go to the CDN dashboard and select some subset of POPs the health check graphs still show health checks for all POPs.

**Comment by tomhughes** [comment]
But I don't see how to parse it from server either unless I'm misunderstanding? You want to split at the hyphen and then strip trailing numbers? Have you checked that works for every single one?

Also any one edge check won't see every served (but will see every pop) so we still couldn't be sure it will work...

**Comment by pnorman** [comment]
> But I don't see how to parse it from server either unless I'm misunderstanding? You want to split at the hyphen and then strip trailing numbers? Have you checked that works for every single one?

It's consistent across all the POPs I've seen, but I haven't gone through each one to verify.

> Also any one edge check won't see every served (but will see every pop) so we still couldn't be sure it will work...

I'm not sure what you mean.

**Comment by tomhughes** [comment]
Done in https://github.com/openstreetmap/prometheus-exporters/commit/d5c83d108587f85fb42c98c32caf1e8940718d6f and dashboard updated to match the data centre.
