### ISSUE TITLE
Prepare Grisu for move

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#71]
We're taking [grisu](https://hardware.openstreetmap.org/servers/grisu.openstreetmap.org/) as a temporary stand-in for [ironbelly](https://hardware.openstreetmap.org/servers/ironbelly.openstreetmap.org/) when ironbelly goes offline.

- [x] Migrate aerial imagery to kessie
- [x] Initial sync from ironbelly

**Comment by Firefishy** [comment]
I have migrated the imagery to kessie. Handing over to @tomhughes for the sync.

**Comment by tomhughes** [comment]
Initial sync from ironbelly has been completed.
