### ISSUE TITLE
Additional storage disks for horntail

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#713]
Ask supplier for quote 2x Seagate Nytro 3332 7.68 TB disks (XS7680SE70084) or compatible equivalent.

Disks for [horntail](https://hardware.openstreetmap.org/servers/horntail.openstreetmap.org/)

**Comment by pnorman** [comment]
Do we need a quote for just Dublin, or also the equivalent server in Amsterdam?

**Comment by Firefishy** [comment]
Both I guess.

**Comment by pnorman** [comment]
ref #537 #543

**Comment by pnorman** [comment]
Email sent to get a quote from the original supplier

**Comment by pnorman** [comment]
Notes
- Seagate part is SAS 12GBps, new SAS SSDs are up to 24G
- SAS SSD selection is limited, as NVMe is what would be used for new builds
- Kioxia (ex-Toshiba) KPM61RUG7T68 and KPM71RUG7T68 are equivalents

**Comment by Firefishy** [comment]
1x [Samsung PM1643a 7.68 TB 2.5"](https://www.scan.co.uk/products/768tb-samsung-pm1643a-25-inch-enterprise-ssd-sas-3-12gb-s-2100mb-s-read-2000mb-s-write-400k-70k-iops) installed in norbert and array expaned. Closing Amsterdam portion of this ticket.

**Comment by Firefishy** [comment]
1x [Samsung PM1643a 7.68 TB 2.5"](https://www.scan.co.uk/products/768tb-samsung-pm1643a-25-inch-enterprise-ssd-sas-3-12gb-s-2100mb-s-read-2000mb-s-write-400k-70k-iops) is in stock waiting for install into horntail.

**Comment by Firefishy** [comment]
Norbert: 8x SAS disks, 4x SATA on front panel. Likely same for horntail. Once disk upgraded no further room to expand the controller array.

**Comment by Firefishy** [comment]
Horntail disk physically added. RAID join still required

**Comment by Firefishy** [comment]
Confirmed. RAID adding disk. One RAID rebuild done, resize filesystem.

**Comment by Firefishy** [comment]
RAID rebuild done, partition resized and resized filesystem.
