### ISSUE TITLE
intermittent 500 error codes at wiki 

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#715]
https://wiki.openstreetmap.org/w/index.php?title=Key:toilets:wheelchair - this page now works normally, but from time to time random OSM Wiki pages are returning with 500 error codes

![screen13](https://user-images.githubusercontent.com/899988/181697678-7faf9055-71b9-4959-8aa8-4856c373a2ba.png)

I needed to rerun https://github.com/openstreetmap/openstreetmap-website/pull/3638 several times due to crashing on encountering 500 error code

**Comment by Firefishy** [comment]
I will look into it.

**Comment by Firefishy** [comment]
I have not been able to find the error in the logs. There have been some heavy bot/scanner traffic.

**Comment by matkoniecz** [comment]
would it help to report exact time or some additional logs if I run into it again?

**Comment by Firefishy** [comment]
@matkoniecz Yes, exact time details would be helpful

**Comment by matkoniecz** [comment]
OK, I will close it and reopen if I will have some usable report.
