### ISSUE TITLE
Order replacement geocoding server

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#716]
pummlezaken is getting old (#259) and still has mechanical HDDs. Replacing it is part of the 2022 budget that has been approved.

per @lonvia, 3.84TB is more than enough disk space to last 5 years.

Questions remaining

- [x] Where to locate it? My inclination is AM6, since the last Nominatim server went into DB4
- [x] Decide on RAM. Will 256GB of RAM be enough?
- [x] Decide on CPU - did we get the CPU/IO balance right with [longma](https://hardware.openstreetmap.org/servers/longma.openstreetmap.org/)? If so, I'd go for the EPYC 7453 again. If it is cpu-heavy, we could go for EPYC 7443 for 96 threads instead of 112.
- [x] Get quote(s)
- [x] Place order

**Comment by lonvia** [comment]
The limiting factor for Nominatim is still IO. I haven't managed to have more than 30 CPUs in use in parallel on longma. Rather save on CPU and go for more RAM instead.

**Comment by pnorman** [comment]
Tentative specs
Supermicro 1124US-TNRP
2x [AMD EPYC 7413 (24 core@2.65GHz)](https://www.amd.com/en/products/cpu/amd-epyc-7413)
512GB RAM?
2x 3.84TB Samsung PM9A3 or equivalent PCI-e 4.0 NVMe
2x240GB boot drives
No RAID controller

Basically longma with less CPU cores and frequency, more L3 cache, more boost clock, double the RAM, and latest-generation NVMe. Retail price 12.5k EUR.

Intel equivalent would be 2x [Xeon Scalable 3 Gold 5318Y](https://ark.intel.com/content/www/us/en/ark/products/215271/intel-xeon-gold-5318y-processor-36m-cache-2-10-ghz.html) in SYS-120U-TNR for about the same retail. Slower clock rates, slower RAM, less L3 cache, different architecture. I've been pretty happy with how the AMD servers have performed, so I'm inclined to stick with them.

**Comment by lonvia** [comment]
Looks good to me.

**Comment by pnorman** [comment]
Email sent off for quote.

**Comment by pnorman** [comment]
Quote 200071 obtained for specs as above, with RAM from 8x 64GB

**Comment by pnorman** [comment]
We've emailed for a quote on a used HP DL360 w/ 2x Xeon 6148, 384GB RAM, 2x3.84TB NVMe.

**Comment by grischard** [comment]
Space prepared in AM6 rack, see rack wiki.

**Comment by pnorman** [comment]
Server is on order, due to arrive next week

**Comment by pnorman** [comment]
Server is installed, chef role assigned, and handed over to lonvia as nominatim sysadmin.

**Comment by pnorman** [comment]
Server is running
