### ISSUE TITLE
Migrate osmfoundation email from Gsuite to Mailbox.org

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#718]
The osmfoundation.org is moving away from Google Workspace (formerly GSuite) to Mailbox.org

We have access to the dedicated migration tool audriga.

**Comment by Firefishy** [comment]
? We haven't paid Google any money so far ?

**Comment by Firefishy** [comment]
Before any accounts can be migrated a suitable replacement needs to be selected, then a migration plan needs to be made. Have these been done?

**Comment by grischard** [comment]
I didn't know we weren't paying them yet. We're about to, then.

No migration plan has been made, and no replacement has been selected.

**Comment by pnorman** [comment]
Closing in favour of #860 which has details

**Comment by grischard** [comment]
#860 was investigation. Reopening this to track actual movement.

**Comment by Firefishy** [comment]
* Audriga estimates nearly a 2x size increase in mailbox size. Migration is limited to <= 2GB per day.
* Google App specific password work.
* Google IMAP needs to be enabled.
* Contacts and Calendar are NOT migrated.

**Comment by Firefishy** [comment]
The osmfoundation.org email migration has been completed. All email has been synced (ok ok, 1 user is still syncing). MX updated.

Docs (mostly minutes) will be migrated over the next month via a separate ticket.
