### ISSUE TITLE
Spike/thorn 04 and 05

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#72]
We're purchasing 4 new HP G7s to live with katla and grisu at the new site.

- [x] Purchase machines
- [x] Install FBWC
- [x] Firmware Updates
- [x] Burn-in testing
- [x] Install Ubuntu 14.04 base OS.

~~What's the ETA for their delivery to London?~~

**Comment by Firefishy** [comment]
I will check with supplier today. I suspect they will arrive Wednesday or Thursday.

**Comment by Firefishy** [comment]
Machines arrived yesterday. Installed FBWC and installed Firmware Updates. Started an overnight HP Insight Diagnostics burn-in. 1 of the machines have a seemingly faulty disk backplane, I have a spare which I will install Saturday.

**Comment by Firefishy** [comment]
All seems good in tests. I have reseated the backplane connectors and is working as expected.

**Comment by Firefishy** [comment]
All servers are ready (including initial chef run) and will be dropped off with @zerebubuth on Sunday.
