### ISSUE TITLE
Publish outage reports for Amsterdam network and for tile service

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#720]

**Comment by pnorman** [comment]
They'll be published in the monthly report automatically, did you have something else in mind?

**Comment by Firefishy** [comment]
Network outage was via: https://github.com/openstreetmap/operations/issues/661

**Comment by Firefishy** [comment]
Both reports are now available via: https://operations.osmfoundation.org/2022/07/31/july.html
