### ISSUE TITLE
Don't reserve ext4 space on non-root tile server storage

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#721]
/store on the tile servers with separate boot and storage volumes has reserved space for the superuser. This makes sense on boot drives, but is using space that could be used for the tile store. It would be best to remove the reserved space.

Pyrene only has one volume, but 130 GiB reserved is more than it needs to be.

**Comment by Firefishy** [comment]
I've updated the reserver on Pyrene from 34118649 blocks (130GB) -> 6823729 blocks (26GB).

/store mount varies server to server. Pyrene only has a single backing disk. Some others machines have separate disks.

**Comment by pnorman** [comment]
The tile servers with /store still need adjustment

**Comment by tomhughes** [comment]
I've reduced the reserved blocks for /store on the other six tile servers to zero.
