### ISSUE TITLE
Track WebGL support with Matomo

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#726]
https://github.com/openstreetmap/chef/commit/bf96ed36324669a5c261a34fd7903663ff11c2aa added the DeviceFeatureWebGL plugin to Matomo, but it never showed up in the statistics as anything other than 0%, and there was no reference to the webgl checks in the matomo javascript.

Now, after recent updates, it's not even showing up at 0%

**Comment by tomhughes** [comment]
That's what https://github.com/openstreetmap/chef/commit/7c9a614d51617d1d88e685d0e9ea333c0c9de9b2 was for.
