### ISSUE TITLE
Set openstreetmap-fastly-logs retention to 30 days

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#727]
In #698 I suggested changing the retention to 30 days for the raw fastly logs, as the successful request data logs will contain all the same information for successful tiles, so the only loss is failed requests and non-tile requests, which we've never needed.

Since the log aggregation has been running for a couple weeks without issues, I recommend turning on a bucket policy to delete files >30 days old. This will bring the bucket size down from 86TB to about 4TB.

**Comment by Firefishy** [comment]
I have now enabled this, except for now I have used 90 day object expiry.

**Comment by Firefishy** [comment]
I will keep ticket open until object expiry confirmed.

**Comment by Firefishy** [comment]
Current size: 79TB
Number of Objects: 3.5M

**Comment by Firefishy** [comment]
Current size: 18.6 TB
Number of Objects: 847,374

**Comment by Firefishy** [comment]
New limits set.

**Comment by Firefishy** [comment]
11th August: 79.5 TB
13th August: 4.5 TB
