### ISSUE TITLE
Disable 'postgresql deadlock' alerts on Nominatim machines

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/operations#728]
Nominatim occasionally creates deadlocks in Postgresql when indexing places in parallel. This can't be avoided and is caught and handled by the software. Thus the prometheus alerts about deadlocks are most of the time false positives. Can we disable them for the Nominatim machines?

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/52d0c6357c9d5afe687c8302d02a6e14cb6cecf4.
