### ISSUE TITLE
Capture rasdaemon events in prometheus + alert 

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#729]
`rasdaemon` replaced `mcelog` in Ubuntu 18.04. We should capture any events in  prometheus and likely alert on them.

`rasdaemon` isn't currently managed by Chef, but is likely a default install package.

`ras-mc-ctl` is `rasdaemon` client. `ras-mc-ctl --error-count` and `ras-mc-ctl --summary` to get the details of logged events.

**Comment by Firefishy** [comment]
`errol` has some logged events if a test is needed.

**Comment by tomhughes** [comment]
Implemented in https://github.com/openstreetmap/prometheus-exporters/commit/5101de6cf08e208382fea6404a9acb29284d934c, https://github.com/openstreetmap/chef/commit/6d4344a0b4300fd8210ee0b1e2af90d1ddfa9072 and https://github.com/openstreetmap/chef/commit/5bbe6932cd6068a287a109cf811c075ab7d3bb47.
