### ISSUE TITLE
Low disk space on karm and eddie

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#730]
The two previous generation database servers, [karm](https://hardware.openstreetmap.org/servers/karm.openstreetmap.org/) and [eddie](https://hardware.openstreetmap.org/servers/eddie.openstreetmap.org/), are both getting low on space on their database array.

**Comment by Firefishy** [comment]
Replacement disk P4510 2TB: https://ark.intel.com/content/www/us/en/ark/products/122580/intel-ssd-dc-p4510-series-2-0tb-2-5in-pcie-3-1-x4-3d2-tlc.html

**Comment by tomhughes** [comment]
I discussed this with Paul on the operations call last week and our thought was not to bother and just to decommision them as database servers as that will still leave us with three snaps in three different data centres.

**Comment by Firefishy** [comment]
For now I have changed ext4 reserved space to 1% on both which has brought disk space usage down to 92%.

**Comment by Firefishy** [comment]
Closing as not planned.
