### ISSUE TITLE
OSMF SOTM email bounces

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#732]
The SOTM email is sotm@openstreetmap.org, but this internally redirects to sotm@osmfoundation.org, and when emailing the first address an error response is given

> Your message wasn't delivered to sotm@osmfoundation.org because the address couldn't be found, or is unable to receive mail. 

@Firefishy could this be from cleaning up accounts?

**Comment by matkoniecz** [comment]
And this email is advertised at https://wiki.osmfoundation.org/wiki/StateoftheMap_Organizing_Committee

**Comment by matkoniecz** [comment]
emailing sotm@osmfoundation.org directly is also broken

**Comment by Firefishy** [comment]
I have created these email forward groups now. I am still trying to find out who is meant to receive these emails. I will check what happened later.

**Comment by Firefishy** [comment]
This should now have been resolved.
