### ISSUE TITLE
Some changeset diffs from 2018 missing

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#734]
We seem to have lost a few hundred ~minutely~ changeset diffs on the server back from 2018:

* https://planet.openstreetmap.org/replication/changesets/003/115/  -> ends at 723
* https://planet.openstreetmap.org/replication/changesets/003/116/  -> starts at 043

I don't know how this might happen, and if other changeset diffs are impacted as well.

Could these be restored again? 

Edit: correction: issue affects changeset diffs, not minutely diffs. Removed link to minutely diff backup (not relevant)

**Comment by tomhughes** [comment]
Restored from those archives.

**Comment by mmd-osm** [comment]
Ah I just realized that I made a stupid mistake, and mixed up changeset diffs and minutely diffs :(

There's a gap of 5 hours in there still, but the archive copy I provided isn't suitable to fix it.   Sorry about that.

**Comment by tomhughes** [comment]
I thought the dates were a bit off... Removed again.

**Comment by mmd-osm** [comment]
Yes, I also noticed that the dates were off, and then looked into state.txt, which has a different format for changeset diffs.

I just double checked if the changeset dump has any gaps on that day, but it all looks fine (https://planet.openstreetmap.org/planet/changesets-latest.osm.bz2). I guess the changeset diffs are gone forever, and people need to back fill their db from a changeset dump instead.

```
...
 <changeset id="63681557" created_at="2018-10-19T14:58:02Z" closed_at="2018-10-19T14:58:04Z" open="false" user="RunRunShow" uid="3553413" min_lat="2.1232447" min_lon="102.3415662" max_lat="2.1605765" max_lon="102.5008892" num_changes="30" comments_count="0">
 <changeset id="63681558" created_at="2018-10-19T14:58:05Z" closed_at="2018-10-19T14:58:05Z" open="false" user="sarxos" uid="3130936" min_lat="53.1693042" min_lon="18.1573426" max_lat="53.1695531" max_lon="18.1576052" num_changes="1" comments_count="0">
 <changeset id="63681559" created_at="2018-10-19T14:58:09Z" closed_at="2018-10-19T14:58:14Z" open="false" user="brianboru" uid="9065" min_lat="52.5235522" min_lon="-2.0878032" max_lat="52.5269934" max_lon="-2.082235" num_changes="177" comments_count="0">
...
```

**Comment by Firefishy** [comment]
We appear to have the backups in AWS backup. I will check about restoring them.

**Comment by Firefishy** [comment]
The backups are in deep glacier, so there is a time + cost implication in restoring them.

**Comment by mmd-osm** [comment]
I cannot completely rule out that those files have never been written in the first place due to some bug. -> which seems to be the case here...

**Comment by Firefishy** [comment]
Yeah, I cannot find the files. I suspect they may have never existed or where removed due to corruption or similar.

**Comment by mmd-osm** [comment]
I do remember the (now abandoned) PR to make the changeset replication a bit more robust, https://github.com/openstreetmap/chef/pull/198 and some infrequent reports on zere's repo about issues due to a stopped replication: https://github.com/zerebubuth/openstreetmap-changeset-replication/issues?q=is%3Aissue+

The missing files might be related to those issues...
