### ISSUE TITLE
Move wiki to konqi

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#735]
The wiki server, tabaluga, is getting low on space.

I deleted an old wiki dump which means we now have about 10% free - there is now 377Gb used with about 150Gb of mysql data and 150Gb in the main wiki directory.

**Comment by Firefishy** [comment]
Potential replacement disk 2x https://www.ebay.co.uk/itm/203855641256

**Comment by pnorman** [comment]
Let's switch the wiki to one of the newer HP DL360s that we haven't yet used in Dublin, as they have 3x1.9TB.

**Comment by tomhughes** [comment]
This is back over 95% again - should we go with @pnorman's suggestion and move it to Dublin?

**Comment by Firefishy** [comment]
Going to move to konqi

**Comment by Firefishy** [comment]
konqi runs PHP8 (ubuntu 22.04) which mediawiki is not yet compatible with. Mediawiki 1.39 will support PHP8.

**Comment by Firefishy** [comment]
27% free (122GiB) after cleanup. Should give us a bit of breathing room.

**Comment by grischard** [comment]
Breathing room is holding, changing title.

**Comment by grischard** [comment]
Breathing room is holding, changing title.

**Comment by grischard** [comment]
Linked issue: #760 for migration to a mediawiki version that will work with the php 8 on konqi

**Comment by pnorman** [comment]
Unblocked, we've upgraded MW

**Comment by tomhughes** [comment]
This has now been completed.
