### ISSUE TITLE
DNS entry for test.osm2pgsql.org

### ISSUE THREAD

**Issue by joto** [openstreetmap/operations#736]
FOSSGIS is sponsoring a new test server for osm2pgsql development. Can you please add a DNS entry for `test.osm2pgsql.org` to `135.181.221.216`?

**Comment by Firefishy** [comment]
Done via: https://github.com/openstreetmap/dns/commit/f16c035f3c9f60b131892ac18a5f87a987a0f1b7
DNS should be live within 10mins.

**Comment by Firefishy** [comment]
PS: `test.osm2pgsql.org` + `test.osm2pgsql.com` are now live.
