### ISSUE TITLE
Investigate IP rate limiting on the CDN

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#740]
Right now we rate-limit per IP on the render servers, which only measures cache misses.

Fastly has some abilities for rate-limiting on the cache, which would improve the consistency of limits.

Related: #709

**Comment by pnorman** [comment]
I'm talking to Fastly about this perhaps next week.

**Comment by grischard** [comment]
Do you want to mention #709 to them while you're chatting with them?

**Comment by pnorman** [comment]
With #709 worked around, I'm going to try to figure out appropriate rate-limits and look at implementation

**Comment by pnorman** [comment]
I've put in rate limiting at 100 r/s over 10s, and am monitoring what is block.

I need to figure out how to do monitoring for number of blocked entries in penalty boxes.

**Comment by pnorman** [comment]
We're now doing this, but there's no way to monitor how many blocked IPs we have without additional logging and log parsing.
