### ISSUE TITLE
Cross Account S3 Replication for openstreetmap-user-avatars

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#744]
Setup cross account S3 replication for `openstreetmap-user-avatars` to an S3 bucket in an AWS backup account.

Document replication on wiki here.

**Comment by Firefishy** [comment]
Blocked by: https://github.com/openstreetmap/operations/issues/746

**Comment by grischard** [comment]
Unblocked now that #746 is closed

**Comment by Firefishy** [comment]
The bucket is now fully in-sync to a backup bucket in EU-North-1. The bucket lives in another dedicated backups account.
