### ISSUE TITLE
Service-impacting low voltage work

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#748]
Equinix has scheduled maintenance on the low-voltage distribution system at AM6.

It's not clear from the notice if this is A-side or B-side power.

Scheduled outage is WEDNESDAY, 26 OCT 20:00 - THURSDAY, 27 OCT 04:00 (UTC)

**Comment by pnorman** [comment]
Contacted Equinix to check if it's A-side or B-side. When we find out, we should do a test to make sure nothing will go wrong for the 8 hour outage.

**Comment by pnorman** [comment]
This is B-side power for us.

**Comment by Firefishy** [comment]
B-side currently powers the upstream switch. The RPS device is powered up and supplying power (alertmanager is linked)

**Comment by Firefishy** [comment]
It is likely I will visit AMS in next 2 week to enable the new switches (with properly redundant PSUs)

**Comment by pnorman** [comment]
Let's do a test powering off B-side when you're there to make sure that we're aware of any failures in advance.

**Comment by grischard** [comment]
Grant didn't have time to test powering off the B-side while he was there, but we can do a remote test, and confirm the power ports on https://github.com/openstreetmap/operations/wiki/AM6-Rack from ipmi while we're at it.

**Comment by grischard** [comment]
Done.
