### ISSUE TITLE
Replace MultiMaps extension

### ISSUE THREAD

**Issue by Tigerfell** [openstreetmap/operations#749]
Once again we have to find a new extension to display maps in the OSM wiki because MultiMaps extension [throws errors](https://phabricator.wikimedia.org/T314227) when used with MediaWiki >= 1.38. The extension is [not maintained anymore](https://phabricator.wikimedia.org/T315007). 

I would suggest to use the [Kartographer extension](https://www.mediawiki.org/wiki/Extension:Kartographer) because it is maintained by the Wikimedia Foundation. This suggestion has several shortcomings however:

- Wikimedia maps is attributed even if we show our own maps.
- API keys are readable from a wiki page (example: [wikivoyage.org](https://en.wikivoyage.org/wiki/MediaWiki:Kartographer.js))
- The extension makes useless HTTPS requests to `<tileserver>/img/,13,37.8013,-122.3988,350x350.png?lang=en&domain=localhost&title=Sandbox&groups=_2251fa240a210d2861cc9f44c48d7e3ba116ff2f` (some leftover code by WMF, OSM's tile servers are configured differently).
- It expects to find the images of pins at tile.openstreetmap.org, so one can not use them.
- It is impossible to show another tile layer like Thunderforest per default. One always has to access the map and then switch the layer individually. 

All of those issues relate to the fact that WMF first developed this extension for themselves only. They did not take into account other setups or common practices employing Leaflet. I got in touch with their German chapter and they said they will not address these points in 2022 but maybe later. MediaWiki 1.37 has its end of live in November 2022 however.

**Comment by Tigerfell** [comment]
Related Phabricator tickets for further research

- [Configuring Kartographer for external tileserver wrongly inserts "osm-intl" into URL](https://phabricator.wikimedia.org/T271617)
- [Add the Kartographer & JsonConfig extensions to the next release of Wikibase-Release-Pipeline](https://phabricator.wikimedia.org/T297062)
- [Make it easier to configure map layers for 3rd party users](https://phabricator.wikimedia.org/T259868)

**Comment by 1ec5** [comment]
There’s also a [Maps](https://maps.extension.wiki/) extension. It’s [actively maintained](https://www.mediawiki.org/wiki/Extension:Maps) and based on [Leaflet](https://maps.extension.wiki/wiki/Displaying_Leaflet_maps) like MultiMaps, and it seems to address some of the caveats above. At a glance, the main downside would probably be that it’s more complex than MultiMaps.

**Comment by lectrician1** [comment]
What's the decision on what we will replace it with so that we can get this moving? Using the Maps extension seems like the clear solution to me.

**Comment by Firefishy** [comment]
I can see advantages to both Kartographer and Maps extensions. I do like something that Wikimedia supports, but the attribution would need to be fixed.

**Comment by lectrician1** [comment]
@grischard 
> Do you want to take the lead on migrating to the Maps extension?

Of course! But I don't know how!

I don't know how the current maps work so I can look into it. Do I need to research configuring the extensions? Will I end up editing chef files?

**Comment by 1ec5** [comment]
> It is impossible to show another tile layer like Thunderforest per default. One always has to access the map and then switch the layer individually.

There is a [`$wgKartographerStyles`](https://www.mediawiki.org/wiki/Extension:Kartographer#Configuration) configuration variable that allows the `<mapframe>` to specify one of the values in the `mapstyle="…"` attribute. However, all it does is insert the map style after the `$wgKartographerMapServer` in the URL. It isn’t flexible enough to load a layer from a different host. As a workaround, the same MediaWiki:Kartographer.js or MediaWiki:Kartographer-wv-layer-wikimedia mentioned in https://github.com/openstreetmap/chef/pull/552#issue-1501381457 could hot-swap the tile layers’ base URLs.
