### ISSUE TITLE
Migrate Dev users from errol to faffy

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#752]
Faffy is the replacement dev server.

- [x] Sync user passwords errol to faffy
- [x] Restore user /home files from backup
- [x] Rsync user /home files from errol to faffy
- [x] Update required packages in chef
- [x] Sync mysql databases from errol to faffy
- [x] Sync postgresql databases from errol to faffy
- [x] Sync user cron jobs from errol to faffy
- [x] User announcement by email and in errol MOTD with cut-off date
- [x]  Last sync from errol with services stopped
- [ ]  Sync private ssh key from errol
- [x] CNAME dev.openstreetmap.org to faffy

**Comment by Firefishy** [comment]
Started the restore of user homedirs from backup

**Comment by aSeniyants** [comment]
Hi. I can not register on dev server, i dont get email for validation.
Help me

**Comment by tomhughes** [comment]
> Hi. I can not register on dev server, i dont get email for validation. Help me

Then contact support@openstreetmap.org for assistance and don't interject on unrelated tickets in this repository!

**Comment by Firefishy** [comment]
Errol services have been shutdown. DNS moved. Waiting on final syncs before cut across.

**Comment by Firefishy** [comment]
All migrated. Email sending shortly.
