### ISSUE TITLE
Wiki main page bad automatic translation

### ISSUE THREAD

**Issue by larhun** [openstreetmap/operations#753]
### URL

https://wiki.openstreetmap.org/wiki/IT:Main_Page

### How to reproduce the issue?

Please fix the automatic translation of the wiki main page. It doesn't respect the current wiki language. For example, if you

1. open the Italian [main page](https://wiki.openstreetmap.org/wiki/IT:Main_Page),
2. set the wiki language to Italian,
3. and click the "Pagina principale" link on the left side navigation bar

the English main page is shown. I would expect the Italian main page.

**Comment by Tigerfell** [comment]
@larhun Should be fixed now. 
For other people reading along: The best place to report this issue would be https://wiki.openstreetmap.org/wiki/MediaWiki_talk:Sidebar. If unsure if it relates to the sidebar, one can also use https://wiki.openstreetmap.org/wiki/Talk:Wiki.
