### ISSUE TITLE
spike-06 returning errors to some requests

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#754]
![image](https://user-images.githubusercontent.com/1190866/192919270-07e56f60-aafe-4c8d-8fc0-aae9847cd6cc.png)

Prometheus reports a 50% request error rate on spike-06.

Start date 2022-09-29T00:02:00Z.

Passenger queues are also up.

**Comment by pnorman** [comment]
I managed to get the it to display for me, and the error is a Phusion Passenger error page with "We're sorry, but something went wrong."

Error ID: 126ad620

Details: Web application could not be started by the Phusion Passenger(R) application server.
Please read [the Passenger log file](https://www.phusionpassenger.com/library/admin/log_file/) (search for the Error ID) to find the details of the error.

**Comment by tomhughes** [comment]
For some reason at midnight it started failing to spawn new rails servers with:

```
App 1830097 output: Error: The application encountered the following error: 1050 out of char range (RangeError)
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:119:in `chr'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:119:in `string'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:78:in `value'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:92:in `block in hash'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:140:in `repeat_until'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:88:in `hash'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:74:in `object'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:78:in `value'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:92:in `block in hash'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:140:in `repeat_until'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:88:in `hash'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:74:in `object'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:64:in `parse'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:43:in `parse'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:74:in `block in read_startup_arguments'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:73:in `open'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:73:in `read_startup_arguments'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:35:in `init'
App 1830097 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb:38:in `init'
App 1830097 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:184:in `<module:App>'
App 1830097 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 1830097 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

which isn't very enlightening.

Restarting apache seems to have fixed it though.

**Comment by CamJN** [comment]
What version of ruby are you using? I've had reports of this cropping up with ruby 1.8 and 2.0. I think it might be related to this change from Passenger: 

https://github.com/phusion/passenger/commit/0242be1f

More info would be welcome. I'm tracking this issue here: https://github.com/phusion/passenger/issues/2445

**Comment by tomhughes** [comment]
It's the Ubuntu 22.04 packaged ruby which is currently ruby 3.0.2p107.

The trigger at midnight will have been the logs rolling over and doing a reload on apache which restarts (or tries to) the passenger instances.

**Comment by tomhughes** [comment]
We upgraded to passenger 6.0.15 last Friday and this is the first time it's happened with three production servers reloading each night.

**Comment by CamJN** [comment]
Thanks, if at all possible i'd recommend downgrading to 6.0.14 for now, as this does seem to be an issue with 6.0.15. I'll try to get a fix made as fast as i can.
