### ISSUE TITLE
Decommission errol

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#756]
Decommission errol at UCL. Depends on #752 being done first!

Internal IP 10.0.0.14
External IP 193.60.236.13
OOB IP: 10.0.1.14

- [x] Remove Chef config
- [x] Remove DNS (or point cname at faffy?)
- [x] Wipe Disks ("dban" https://aban.derobert.net/)
- [ ] De-rack
- [ ] Disposed

**Comment by tomhughes** [comment]
I think errol has the weird IPMI that sometimes decides to move interface.

**Comment by Firefishy** [comment]
Machine has been wiped and is ready for de-racking.

**Comment by Firefishy** [comment]
Hardware:
1 x 4TB HGST HUS726T4TALE6L4
1 x 2TB Western Digital WD2000FYYZ
1 x 2TB Western Digital WD2001FASS
3 x 2TB Western Digital WD2003FYYS
2 x 1TB Western Digital WD1003FBYX

8 x 8GB PC3-10600 DDR3-1333 ECC

**Comment by Firefishy** [comment]
[Blocked until our access to UCL Slough is restored.](https://github.com/openstreetmap/operations/issues/1060)

**Comment by Firefishy** [comment]
Disks have been removed and retained. Server has gone for WEEE recycling and is waiting to be collected.
