### ISSUE TITLE
Issue accessing a note

### ISSUE THREAD

**Issue by angoca** [openstreetmap/operations#761]
I have an issue accessing this note: https://www.openstreetmap.org/note/3286662

> The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)
>
>Feel free to [contact](http://wiki.openstreetmap.org/wiki/Contact) the OpenStreetMap community if your problem persists. Make a note of the exact URL / post data of your request.
>
>This may be a problem in our Ruby On Rails code. 500 occurs with exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code)

I am trying to access it from Neis Pascal page. Is it a hidden note?

**Comment by tomhughes** [comment]
Well all it's comments are probably hidden, either directly or indirectly because the commenter has deleted their account.

See https://github.com/openstreetmap/openstreetmap-website/issues/2146 or more.
