### ISSUE TITLE
taginfo returning Passenger errors

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/operations#762]
The taginfo website and API have been returning Passenger errors for me for several hours:

![taginfo](https://user-images.githubusercontent.com/1231218/197461758-5f0860d4-e53c-4db5-9945-73ff5004d901.png)

**Comment by 1ec5** [comment]
This is still happening when visiting some pages like https://taginfo.openstreetmap.org/ or making some API requests like https://taginfo.openstreetmap.org/api/4/key/values?filter=ways&key=building&lang=en&page=1&query=&rp=25&sortname=count_ways&sortorder=desc , but others like https://taginfo.openstreetmap.org/api/4/key/values?filter=ways&key=surface&lang=vi&page=1&query=&rp=25&sortname=count_ways&sortorder=desc are starting to come through.

**Comment by tomhughes** [comment]
Already reported to @joto in https://github.com/taginfo/taginfo/commit/f3749812b850f748ff816531770253eb67b4257a#r87690669.
