### ISSUE TITLE
Decommission AM6 old Cisco gear

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#763]
Two Cisco SG550X-48 switches and one Cisco RPS 2300, and I believe a few PSUs, are left in the AM6 rack. They should be de-racked, and ebayed/donated/reused/recycled as appropriate.

**Comment by grischard** [comment]
The switches seem to go for about $700 on eBay, $100 for the RPS.

**Comment by Firefishy** [comment]
The Cisco Switches can likely be removed up and out at the rear of the rack. They are already disconnected.

**Comment by grischard** [comment]
Dimensions, depending on model:

model | dimension
-- | --
SG550X-48 | 440 x 44 x 257 mm (17.3 x 1.7 x 10.12 in)
SG550X-48P | 440 x 44 x 350 mm (17.3 x 1.7 x 13.78 in)
SG550X-48MP | 440 x 44 x 450 mm (17.3 x 1.7 x 17.72 in)

Should fit in my suitcase between a few jumpers :)

**Comment by Firefishy** [comment]
The old switches are the `SG550X-48` model.

**Comment by Firefishy** [comment]
Not yet sold the units on ebay. They have been heavily discounted now since initial listing: https://www.ebay.co.uk/itm/325459066408
