### ISSUE TITLE
The domain is blocked in China

### ISSUE THREAD

**Issue by LoveBodhi** [openstreetmap/operations#765]
https://www.solidot.org/story?sid=73207

**Comment by tomhughes** [comment]
I thought I had closed this earlier to be honest.

**Comment by Firefishy** [comment]
@LoveBodhi @LaoshuBaby Thank you for the report, and sorry about the website being blocked.

I am unsure what options we have. If we setup OSM to be accessible under another domain name: (eg: osm.org) it would likely also be blocked in time.

**Comment by LaoshuBaby** [comment]
> I am unsure what options we have. If we setup OSM to be accessible under another domain name: (eg: osm.org) it would likely also be blocked in time.

I tested, `osm.org` and `openstreetmap.com` is also blocked (so all other domain in https://github.com/openstreetmap/dns/blob/master/dnsconfig.js may already blocked).

Looks like DNS record about OSM in China was polluted. And http(https don't have this problem) requests that return a OSM XML also have possibility been intercepted.

**Comment by LoveBodhi** [comment]
Since it's illegal to surveying maps without certificate in CN (also JP, KR, etc.), the license is void in these regions.
