### ISSUE TITLE
enable ipv6 to taginfo

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/operations#766]
taginfo is only available via ipv4

```
$ host taginfo.openstreetmap.org
taginfo.openstreetmap.org has address 193.60.236.15
```
it's possible to enable ipv6 accès to it ? or it is a consequence of  https://github.com/openstreetmap/operations/issues/559 ?

**Comment by tomhughes** [comment]
No it's not a consequence of that, it's a consequence of #354 and the service being hosted at UCL currently.

As I have explained repeatedly it is our policy to enable IPv6 wherever we can so if it hasn't been done it's because we don't have IPv6 available at the site where something is hosted.

**Comment by Firefishy** [comment]
Taginfo is hosted at UCL / Slough. We do not have IPv6 connectivity there. See: https://github.com/openstreetmap/operations/issues/354
