### ISSUE TITLE
SSD/NVME for overpass instance

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/operations#767]
We've been close to IO capacity for the spinning disks on gorwen for a while. Upgrading to the latest overpass version has pushed things over the edge and the instance has now [trouble keeping up](https://prometheus.openstreetmap.org/d/_MGuv5SVk/overpass?orgId=1&refresh=1m) with minutely. Downgrading overpass will only delay the inevitable. We really should get SSD/NVME for the server (or a different server).

Overpass DB is 250GB at the moment, so 500GB disk will be plenty for some time to come. If we want to keep the option to import a new DB while serving from the old one, I'd rather go for 900 GB.

**Comment by pnorman** [comment]
We could move overpass to one of the Gen9s with 1.9TB SAS SSDs, or one of the general-purpose Gen10 machines we'll be getting with NVMe.

**Comment by mmd-osm** [comment]
I wanted to mention that enabling lz4 compression has helped mitigate the "trouble keeping up with minutely" issue in the meantime. We're even in a better shape than before the upgrade.

This doesn't imply that switching to SSD/NVMe wouldn't be a useful thing to do.

**Comment by pnorman** [comment]
The plan is to move it to one of the general-purpose Gen10 machines.

**Comment by tomhughes** [comment]
It is? First I've heard of it and there's only one left which was loosely planned to possibly replace ridley and/or become a host for containerised services. Possibly we could use tabaluga for that once the wiki is moved to konqi which would leave a Gen10 available for overpass.

**Comment by lonvia** [comment]
Aren't the Gen10's utter overkill for overpass? The service does keep less than 2 CPUs busy.

As mmd said the machine is now coping, so consider this low prio. Also, the disk requirements are less with lz4 compression. We are at 250GB database size now. I'll adapt the numbers in the original issue.

**Comment by pnorman** [comment]
Overpass is running on one of the last HP DL360e Gen8 machines which is being replaced soon

**Comment by Firefishy** [comment]
[fume](https://hardware.openstreetmap.org/servers/fume.openstreetmap.org/) and [grisu](https://hardware.openstreetmap.org/servers/grisu.openstreetmap.org/) are now available.

**Comment by pnorman** [comment]
The meeting minute notes indicate I am to ping @lonvia on this, as we still need to move overpass to a new machine.

**Comment by tomhughes** [comment]
I think the key question we wanted to ask @lonvia was whether she thought it was best to do a new import on the new machine, or to sync the data from the old one.

**Comment by lonvia** [comment]
A reimport should be simpler and quick enough on those machines. I would also update the overpass version on that occasion. If you assign an overpass role on a machine, I'm happy to set it up.

In the long term, overpass is a very likely candidate for being put into docker given that the machines are far too big. Unfortunately, I can't really help with that.

**Comment by tomhughes** [comment]
I've allocated grisu for this and added the role and set @lonvia's password.

**Comment by tomhughes** [comment]
The move to grisu is now complete.
