### ISSUE TITLE
Re-label Network and Power Cables at AM6

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#768]
After the last set of maintenance a number of servers moved.

The labelling of network and power cables should be updated.

The [wiki](https://github.com/openstreetmap/operations/wiki/AM6-Rack) has been updated and should be double checked.

**Comment by Firefishy** [comment]
There are the following sets of labels / flags were prepared:
* Switch 1: SW1-01 to SW1-48 ethernet cable label flags for server side. Note: ports 24 to 48 are OOB
* Switch 2: SW2-01 to SW2-48 ethernet cable label flags for server side. Note: ports 24 to 48 are OOB
* A01 to A24 are Power A side power cable label flags for server side.
* B01 to B24 are Power B side power cable label flags for server side.
* Server Name Labels x2
* Switch Name Labels x3

**Comment by grischard** [comment]
So the labels will go on the server side close to the servers, and not on the switch/psu side?

**Comment by Firefishy** [comment]
> So the labels will go on the server side close to the servers, and not on the switch/psu side?

Correct. Just 1 label near the server per cable.

**Comment by Firefishy** [comment]
Currently blocked due to late shipment from Fedex.

**Comment by grischard** [comment]
Power all relabeled. Network not relabeled as discussed with Grant.
