### ISSUE TITLE
Fix poldi boot

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#77]
Poldi doesn't print anything to the serial console post-grub, and doesn't become available on the network. Not clear if this is a networking + serial console issue, or if the machine is hung after grub.

**Comment by zerebubuth** [comment]
Machine is hung after grub. Black screen, blinking cursor, no response to input. Trying to check disks.

**Comment by zerebubuth** [comment]
I think one of the boot disks got mangled. Booting from the other seems to be working, but with the usual disk problems. /data disappeared.

**Comment by zerebubuth** [comment]
One disk looks to be completely dead (6.5 year old WD3000-HLFS -- it had a good run). Given the general flakiness of this machine's disks, might be a good time to de-rack and see if we can fix. @lonvia what do you think? Would you miss poldi for a few weeks?

**Comment by lonvia** [comment]
Fine with me. It's also fine with we if it is repurposed afterwards (3rd tile server?). pummelzacken & dulcy are sufficient to take the load for Nominatim.

**Comment by zerebubuth** [comment]
Cool, thanks. Scheduled for pick-up next Monday (23rd).

**Comment by zerebubuth** [comment]
Closing in favour of #79.
