### ISSUE TITLE
Ironbelly has failing disk

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#773]
Disk failing in ironbelly:

```
The following warning/error was logged by the smartd daemon:

Device: /dev/sg2 [megaraid_disk_10], Self-Test Log error count increased from 0 to 1

Device info:
[WD       WD4001FYYG-01SL3 VR02], lu id: 0x50000c0f01c43c5c, S/N: WMC1F0798396, 4.00 TB
```

**Comment by Firefishy** [comment]
I likely have a stock replacement. Will confirm.

**Comment by Firefishy** [comment]
Found a 4TB SAS disk.

**Comment by Firefishy** [comment]
2x 4TB SAS disks shipped to Data Centre. 1x for install, 1x for on-site spare.

**Comment by Firefishy** [comment]
Disk should be ready for removal. Locate LED should be enabled.
If wrong serial number disk is pulled DO NOT PROCEED.

**Comment by grischard** [comment]
Is the locate LED located on the disk caddy, or next to it? Can you remember what colour it is? Hard to miss?

**Comment by Firefishy** [comment]
The LED is hard to miss. It is I think blue and should be the only LED of type lit.

**Comment by Firefishy** [comment]
Currently blocked due to late shipment from Fedex.

**Comment by grischard** [comment]
One red LED. ![image](https://user-images.githubusercontent.com/1556567/206151602-51927931-56f8-4a3b-afa7-1e424327d363.jpeg)

**Comment by grischard** [comment]
I've only just realised that the red led isn't on in the picture. It's actually blinking red in the middle row of the leftmost column.

**Comment by grischard** [comment]
![image](https://user-images.githubusercontent.com/1556567/206422857-dc86e6cf-9bb2-4067-ac8c-9b5a27afc74d.jpeg)

@Firefishy please confirm the new one is working

**Comment by Firefishy** [comment]
Confirmed working.
