### ISSUE TITLE
palulukon tile retrieval latency spikes

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#776]
![image](https://user-images.githubusercontent.com/1190866/201828077-50b6eb0c-69f5-4319-b507-d9bd72e7fd82.png)

Palulukon is experiencing bursts of high avg tile retrieval latency, with about 1-3 hours between them. These bursts last 2-3 data points (15-45s) and are 10-15ms latency.

There is no correlation with rendering load.

There is a correlation with IO pressure.

![image](https://user-images.githubusercontent.com/1190866/201828664-575a1bed-18fe-4159-a6a7-8dbee3bb9e09.png)

The drives tiles are on are local NVMe drives.

**Comment by Firefishy** [comment]
Do we really care about these spikes? 10ms is tiny. Most likely NVMe controller garbage collection or similar.

Only option I see is if performance could be improved by switching to NVMe io polling (instead of IRQ).

**Comment by pnorman** [comment]
If we knew what the cause was we could decide to dismiss it, but without knowing what's going on, I don't want to say it isn't a problem, particularly with the limited metrics we have being average only.

**Comment by Firefishy** [comment]
I have looked into this further, the latency spikes are periods of 1 minute and only around 1.6ms. I think this is SSD garbage collection.

**Comment by Firefishy** [comment]
The spikes seem to be less frequent now, we are running a much newer kernel `6.2.0-1010-aws`. Outside the weekly md scrubs there are not any alarming spikes.
