### ISSUE TITLE
[Account request]: 

### ISSUE THREAD

**Issue by darkhorse46** [openstreetmap/operations#777]
### Name

Boris

### Email address

darkhooorse@gmail.com

### OpenStreetMap username

darkhorse46

### Username on the server

boris

### Bio

```markdown
Hello,
I'm a OpenStreetMap user and I noticed some MAPS errors...

I would like to contribute to the correction.

Best regards

Boris
```

### Code of Conduct

- [X] I agree to follow the OpenStreetMap policies and codes of conduct, and to use the dev server only for OpenStreetMap-related tasks

**Comment by tomhughes** [comment]
You don't need a shell account on the dev server to edit the map - you just need to signup on www.openstreetmap.org as normal.

**Comment by darkhorse46** [comment]
Thanks for the reply!

A week ago I made some changes by logging into the openstreetmaps.org site, but I don't see any changes in the map. So I thought maybe I needed to act differently through the dev server. 
I'm so sorry for the misunderstanding! 

Good work
Boris

**Comment by mmd-osm** [comment]
@grischard : can I suggest to add a remark, that no private information should be entered in this form, as all the information will be visible to everyone, not only OWG or system admins?

**Comment by grischard** [comment]
@mmd-osm sounds reasonable, feel free to improve.

**Comment by mmd-osm** [comment]
Ok, and how what about a mailto: email template to send all this information by email to "operations@ ..." ?

**Comment by tomhughes** [comment]
What would that achieve? The people that can act on the requests will be subscribed here anyway.

It's also not very helpful to be discussing this here, where we're spamming the person that opened the ticket with side discussions.

**Comment by tomhughes** [comment]
I had misunderstood what you meant by the way - I thought you meant a github action to automatically send these issues to operations.

**Comment by mmd-osm** [comment]
>  I thought you meant a github action to automatically send these issues to operations.

I also looked into that, but I think that's not possible. So yes, the idea was to add an email link with subject and body to be used as a template: [sent account request email](mailto:support@osm.org?subject=Account%20request&body=Name:%0D%0A%0D%0A%0D%0AOpenstreetmap%20username:%0D%0A%0D%0A%0D%0A...)
