### ISSUE TITLE
SNMP timeouts querying Amsterdam switches

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#783]
We're seeing issues with prometheus querying the Amsterdam switches over SNMP with periods of several hours when they don't seem to respond, as seen in the gaps here:

![image](https://user-images.githubusercontent.com/147741/202555813-d28da7fd-7c9c-48d2-94e9-66faf211dbb8.png)

I choose that graph because it also hints at a possible cause in that the CPU load on switch 2 appears to spike to 100% as it stops responding, and fall back when it starts again so I suspect the control plane is becoming overloaded and unable to respond to the SNMP queries.

**Comment by Firefishy** [comment]
I've enabled the following options in an attempt to reduce the runaway SNMP user CPU time. Seems to have been more stable for the last 24 hours. I will continue to monitor.

```
snmp {
+    filter-interfaces {
+        all-internal-interfaces;
+    }
+    filter-duplicates;
    community xxxx;
}
```

**Comment by Firefishy** [comment]
Looks like switch CPU usage now under control. SNMP and other switch config changes see to have improved the situation. Changes in https://github.com/openstreetmap/oxidized-configs (private repo)

**Comment by Firefishy** [comment]
Link to switch monitoring: https://prometheus.openstreetmap.org/d/CMu3T1R4k/switch-monitoring?orgId=1&refresh=1m&from=now-7d&to=now

**Comment by Firefishy** [comment]
Seem ok now. Can re-open if the issue returns.
