### ISSUE TITLE
Move oob1 @ AMS 2nd ethernet NIC to Switch 2

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#784]
Currently oob1 @ AMS ethernet ports are both connected to the same switch:

```
ge-0/0/26          -                   dc:a6:32:49:56:da   enx8cae4cdb46b4    oob1
ge-0/0/25          -                   dc:a6:32:49:56:da   eth0               oob1
```

Cable to ge-0/0/26 should be moved to switch 2.

**Comment by Firefishy** [comment]
The spared shipped 1x USB Ethernet should be returned to London stock.

**Comment by grischard** [comment]
The on-board ethernet will stay as it is; the usb ethernet will be moved to the same port on the other switch.

**Comment by grischard** [comment]
Is that 26 on bottom or top switch?

**Comment by grischard** [comment]
Moved 26 bottom to 34 top. 26 top is tabaluga oob.
