### ISSUE TITLE
Add up recurring costs

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#789]
e.g. DC power&space, network, statuscake, etc.

AWS is covered by #788

**Comment by Firefishy** [comment]
* Equinix - Racks, Power, Cross-Connect, Remote Hands
* Cogent - Connectivity + Subnet
* HE.net - Connectivity + Subnet
* Gandi.net (Domain)
* Statuscake - £152.89/year (May)  
* Report URI - $11.99/month

**Comment by Firefishy** [comment]
## Equinix Breakdown
### AM6
1. Interconnection: €105ex / month
2. Power: €334.89ex / month
3. Space: €560ex / month
4. Remote Hands: €165 / hour
### DB4
1. Interconnection: 
2. Power: 
3. Space: 
4. Remote Hands: €165 / hour

**Comment by pnorman** [comment]
Do we have something for the paging service?

**Comment by Firefishy** [comment]
> Do we have something for the paging service?

Pagerduty we have a sponsored account.
