### ISSUE TITLE
Poldi rebuild

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#79]
After problems with the disks (see #77, #42, issues _passim_), which might or might not be related to trying to run 6Gbps SATA over a 3Gbps backplane, it was decided to pull this and work on it or rebuild it offline. It's no longer needed as a Nominatim server, but still has some quite good hardware which might make it suitable for other purposes, e.g: tile rendering, backups, imagery, etc...

It's getting pulled on 23/05/2016.

**Comment by Firefishy** [comment]
Poldi disk is also failing: WDC WD2003FYYS-02W0B0, S/N:WD-WMAY00703188, WWN:5-0014ee-0ad34b7ed, FW:01.01D01, 2.00 TB

**Comment by zerebubuth** [comment]
Poldi was de-racked earlier today, and now we have to figure out how to rebuild it. @Firefishy do you think it's worth investigating more, or just getting a new chassis (e.g: [SilverStone RM208](http://www.silverstonetek.com/product.php?pid=541&area=en) or [X-Case RM208](https://www.xcase.co.uk/2u-rackmount-server-cases/x-case-rm-208-pro-8-hotswap-caddy-with-6gb-sata-sas-backplane-temperature-controlled-fans-179-00-x-case.html) -- the latter looks very similar, might be a re-brand) and swapping over the mobo, PSUs, drives, etc...?

**Comment by zerebubuth** [comment]
Or a [Supermicro SuperChassis 826A-R1200LPB](https://www.servercase.co.uk/shop/server-cases/rackmount/2u-chassis/supermicro-superchassis-826a-r1200lpb-black-cse-826a-r1200lpb/). Although that has 12 bays, and we've only got an HBA that can serve 8.

**Comment by Firefishy** [comment]
The machine is in pieces in an attempt to rebuild without a faulty 3Gbps backplane. The space is incredibly tight and disks would be lose mounted. The only way it would ever come back is as a beast of a franken-server. A better chassis would be good, but CPU and motherboard are old.

**Comment by pnorman** [comment]
Is replacing the backplane an option or is it one of those difficult to obtain parts? Otherwise it sounds like as parts is the best use.

**Comment by Firefishy** [comment]
It is a proprietary backplane, custom power connector, custom size and mountings for the case. Searches for numbers on it were unfruitful.

Without the backplane it is quite difficult to feed sata cables + power + power splitter behind the disk caddies. Around 2 inches. Removing + reinserting a caddy can mean removing all cabling to get back to the disk connectors again and rewriting again.

**Comment by pnorman** [comment]
I had a setup similar to that when I was a starving student. It wasn't worth the bother and cuts from the case when it was a home server, I'd expect that to be even more the case when colocated.

**Comment by pnorman** [comment]
Did we decide to get rid of the old poldi?

**Comment by Firefishy** [comment]
Yes. Chassis has been scrapped. What could be recovered was.
