### ISSUE TITLE
[Account request]: 

### ISSUE THREAD

**Issue by Janick7** [openstreetmap/operations#793]
### Name

Janos Tothmajor

### Email address

tothmajor.janos@tmj.hu

### OpenStreetMap username

Janick7

### Username on the server

Janick7

### Code of Conduct

- [X] I agree to follow the OpenStreetMap policies and codes of conduct, and to use the dev server only for OpenStreetMap-related tasks

**Comment by tomhughes** [comment]
Can you explain a bit more about what you want to use the dev server for?

**Comment by Firefishy** [comment]
@Janick7 any comment on the above quest?

**Comment by Firefishy** [comment]
Not heard back, closing.
