### ISSUE TITLE
 master.apis.dev.openstreetmap.org is not working anymore

### ISSUE THREAD

**Issue by Ferenc-** [openstreetmap/operations#794]
[master.apis.dev.openstreetmap.org](https://master.apis.dev.openstreetmap.org/) is not working anymore.
And none of the test instances suggested for client testing on [apis.dev.openstreetmap.org](https://apis.dev.openstreetmap.org/) work.
And this has been like this for days, and the organicmaps CI has stuck because of this.
Any suggestions on what to use instead? Or what to do?

**Comment by tomhughes** [comment]
Fixed,
