### ISSUE TITLE
Service-impacting low voltage work in Amsterdam

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#795]
Equinix has scheduled maintenance on the low-voltage distribution system at AM6.

Scheduled outage is SATURDAY, 28 JAN 19:00 - SUNDAY, 29 JAN 05:00

The work is on MDP-D, which, per previous communication is B-side.

We tested this power configuration recently for #748, so I'm not worried about outages.

Ref: Equinix 5-221462294474

**Comment by pnorman** [comment]
Looks like they reschedule it at some point to 	SATURDAY, 25 MAR 19:00 - SUNDAY, 26 MAR 04:00 UTC

**Comment by pnorman** [comment]
The above date is a copy/paste from the email, but day and date contradict each other.

**Comment by pnorman** [comment]
This has occured without any problems.

**Comment by Firefishy** [comment]
Maintenance has started we have lost power to PDU2 aka B-side. 
https://prometheus.openstreetmap.org/d/BF2AdDUGz/site-monitoring?orgId=1&var-site=amsterdam&var-uplink=ge-%5B01%5D%2F2%2F0&from=1679771258197&to=1679773765737

**Comment by pnorman** [comment]
This was done some time ago. Current work is #847
