### ISSUE TITLE
Add CleanChanges Wiki Extension

### ISSUE THREAD

**Issue by lens0021** [openstreetmap/operations#797]
It seems the wiki is multilingual, but there is no way to filter recent changes and RSS feeds by language. CleanChanges can provide the language filter.

> It also provides two extra filters: by user and by language code suffix.
> -- [Extension:CleanChanges on MediaWikiWiki](https://www.mediawiki.org/wiki/Extension:CleanChanges)

CleanChanges has no dependency extension, is stable and used on WMF wiki.

Example configuration:

```php
wfLoadExtension( 'CleanChanges' );

# defaults to "false". It is needed to filter by language (code suffix).
$wgCCTrailerFilter = true;
```

You can see [a live example on Translate wiki](https://translatewiki.net/wiki/Special:RecentChanges).

**Comment by mmd-osm** [comment]
Related discussion: https://wiki.openstreetmap.org/wiki/Talk:Wiki#Per_language_feeds_of_wiki_edits?

**Comment by pnorman** [comment]
The OWG requires extension requests [come from wiki sysadmins](https://github.com/openstreetmap/operations/issues/509#issuecomment-785403089). A wiki admin can open a new request for this extension if the wiki admins believe it should be added to the OSM wikis.

#785 is about writing up evaluation criteria for mediawiki extensions
