### ISSUE TITLE
Replace the 10G Fibre modules in Juniper Switches in Amsterdam

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#799]
The existing installed 10G Fibre modules should be removed from the Juniper switches in Amsterdam.
They existing installed modules are 850nm.

2x 10G 1310nm (LR) SFP+ fibre modules have been sent as replacements.

* Remove all existing 10G modules from both switches. Do not remove 1G modules (1 x in use in Switch 0, 1x spare in Switch 1) 
* Install 1x 10G 1310nm (LR) SFP+ fibre module into Switch 0.
* Install 1x 10G 1310nm (LR) SFP+ fibre module into Switch 1.

**Comment by Firefishy** [comment]
Currently blocked due to late shipment from Fedex.

**Comment by grischard** [comment]
Old modules removed

**Comment by grischard** [comment]
![image](https://user-images.githubusercontent.com/1556567/206424071-77d809bf-63e2-499b-9a96-bf653bf3016f.jpeg)

Modules installed. Missing one rubber gasket.
