### ISSUE TITLE
Test katla disks

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#80]
One by one, do a long SMART test of each of katla's disks. They had a long road journey, so better to be sure they're still okay. Note that there are 4 new spares (3x900GB, 1x600GB) to replace any failures, and be assigned as global hot spares if they're not needed immediately.

SMART Long Test Done:
- [x] /dev/sdc
- [x] /dev/sdd
- [x] /dev/sg2 -d megaraid,8
- [ ] /dev/sg2 -d megaraid,9
- [ ] /dev/sg2 -d megaraid,10
- [ ] /dev/sg2 -d megaraid,11
- [ ] /dev/sg2 -d megaraid,12
- [ ] /dev/sg2 -d megaraid,13
- [ ] /dev/sg2 -d megaraid,14
- [ ] /dev/sg2 -d megaraid,15
- [ ] /dev/sg2 -d megaraid,24
- [ ] /dev/sg2 -d megaraid,17
- [ ] /dev/sg2 -d megaraid,18
- [ ] /dev/sg2 -d megaraid,19
- [ ] /dev/sg2 -d megaraid,20
- [ ] /dev/sg2 -d megaraid,21
- [ ] /dev/sg2 -d megaraid,22
- [ ] /dev/sg2 -d megaraid,23
- [x] /dev/sg5 -d megaraid,8
- [ ] /dev/sg5 -d megaraid,9
- [ ] /dev/sg5 -d megaraid,10
- [ ] /dev/sg5 -d megaraid,11
- [ ] /dev/sg5 -d megaraid,12
- [ ] /dev/sg5 -d megaraid,13
- [ ] /dev/sg5 -d megaraid,14
- [ ] /dev/sg2 -d megaraid,29
- [x] /dev/sg2 -d megaraid,25
- [x] /dev/sg10
- [x] /dev/sg9

**Comment by Firefishy** [comment]
I've added a checkbox table and marked off a few disks I've already done.

**Comment by gravitystorm** [comment]
Is this still relevant?

**Comment by Firefishy** [comment]
No longer relevant. If a disk didn't properly survive the trip the disk would have died already. Closing.
