### ISSUE TITLE
Decommission lockheed (aka thorn-01)

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#800]
Decommission lockheed  at AM6.

- [x] Remove Chef config
- [x] Remove DNS
- [x] Wipe Disks
- [x] De-rack
- [x] Disposed

Lockheed is an old server and should be scrapped in prep for new servers.

Arrange with on-site Equinix engineer to accept the server for WEEE recycling (or other safe disposal method).

**Comment by Firefishy** [comment]
Server has been powered down in prep for removal.

**Comment by grischard** [comment]
Outer rails left in rack because I don't have the special tool to remove them. Will ask equinix folks.

**Comment by Firefishy** [comment]
All done.
