### ISSUE TITLE
Swap eth0 / eth1 cables for tabaluga / odin / norbert

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#802]
To match NIC eth0 (normally black cable) to switch1 and NIC eth1 (normally white) to switch2 the following servers should have their ethernet cables swapped around at the server side. The OOB port should not be changed.

- [x] tabaluga
- [x] odin
- [x] norbert

All other servers at Amsterdam are correct?

Why we doing this? This allows consistent LACP force-up configuration on the switches to allow PXE on eth0 before OS has enabled LACP.

**Comment by grischard** [comment]
Most other servers have blue on left afaict
