### ISSUE TITLE
s3://osm-pds/2022/planet-221205.osm.pbf missing

### ISSUE THREAD

**Issue by jakajancar** [openstreetmap/operations#808]
The latest planet dump has torrent & md5 files, but is missing `.osm.pbf` and `.orc`.

**Comment by tomhughes** [comment]
I don't think that file is anything to do with us as we don't publish to S3 yet - somebody else may be mirroring planet there but you would to ask whoever is doing it about that.

Are the files present on the official site at planet.openstreetmap.org?

**Comment by tomhughes** [comment]
I can see the pbf is on the official site and I have no idea what the orc is but I don't think it's anything we produce.

Bear in mind that planet only came out a few hours ago so whoever is mirroring it to S3 it may still be copying.

**Comment by Firefishy** [comment]
The `osm-pds` bucket is managed by the team here: https://docs.opendata.aws/osm-pds/readme.html
The OSM operations team to not yet directly publish to AWS.

**Comment by mojodna** [comment]
@jakajancar the ORC and OSM PBF files are now in place. Tom was right; it was in the process of being copied and transcoded when you looked before.
