### ISSUE TITLE
osm.org doesn't work in Opera

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/operations#809]
### URL

https://www.openstreetmap.org

### How to reproduce the issue?

I can't open https://www.openstreetmap.org in Opera.

### Screenshot(s) or anything else?

![osm org_Opera](https://user-images.githubusercontent.com/57260466/206879434-06a85c95-d4c8-4c2a-b864-6a7ca3a2ae10.png)

Translation:

Your connection is not private
Perhaps someone is trying to steal your data from www.openstreetmap.org (e.g. passwords, messages, credit card data).
NET::ERR_CERT_DATE_INVALID
You cannot visit www.openstreetmap.org right now because the site uses the HSTS mechanism. Network errors and attacks are usually temporary, so the site will probably be available soon.

**Comment by tomhughes** [comment]
I've moved this to operations as it's not a code issue but in any case whatever is going on here is clearly an issue with the user's configuration or we'd have a lot more complaints.

Is this a very old version of Opera and/or a very old operating system that may have out of date root certificates? Maybe it is the root certificate that has expired rather than the actual site certificate?

**Comment by maro-21** [comment]
> Is this a very old version of Opera and/or a very old operating system that may have out of date root certificates? Maybe it is the root certificate that has expired rather than the actual site certificate?

It was on the newest version of Opera. System is Windows 7 (Does the system even matter? On the same system in other browsers the website works. I suppose something needs to be configured in Opera, maybe privacy settings?)

**Comment by tomhughes** [comment]
Yes the system can matter if the browser uses the OS root certificate store (not sure if Opera does) and the OS is no longer getting updates to the root store.

In this case given you're using an old and no longer supported version of Windows my guess is you have the old and now expired IdenTrust DST Root CA X3 certificate that cross signed the letsencrypt intermediate and you possibly don't have letsencrypt root (though things can go wrong even with that).

**Comment by Firefishy** [comment]
Yes, this is likely an issue caused by the expired [DST Root CA X3 Expiration (September 2021)](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) root certificate we use for compatibility.

We currently use Let's Encrypt's **Legacy Chain** to [support older devices](https://letsencrypt.org/docs/certificate-compatibility/).

@maro-21 Do you get the error with Firefox when using the same machine?

**Comment by Firefishy** [comment]
@maro-21 Alternatively, please could you try install and trust the ISRG Root X1 from http://x1.i.lencr.org/
Are you on Windows or Mac?

**Comment by maro-21** [comment]
The same error I have with translatewiki.net website, but there I can click "Help me understand" and then open the site by clicking "Go to translatewiki.net anyway"
![Opera2](https://user-images.githubusercontent.com/57260466/206905334-40329ec2-1570-48e9-bed0-23e743e287ec.png)
![Opera3](https://user-images.githubusercontent.com/57260466/206905602-cfb6e656-0437-4471-b30a-58b55f59348c.png)

**Comment by maro-21** [comment]
> @maro-21 Do you get the error with Firefox when using the same machine?

No.

> Are you on Windows or Mac?

Windows.

**Comment by maro-21** [comment]
> @maro-21 Alternatively, please could you try install and trust the ISRG Root X1 from http://x1.i.lencr.org/

I installed it, but it didn't help...

![ISRG](https://user-images.githubusercontent.com/57260466/206906926-b736db84-1e4d-4e44-af56-b72adcedfacf.jpg)

**Comment by tomhughes** [comment]
See if you can find an expired "DST Root CA X3" certificate and remove it otherwise it can sometimes be preferred over the X1 certificate.

**Comment by maro-21** [comment]
It seems that I can't remove the certificate. The "delete" option is inactive:

![Opera4](https://user-images.githubusercontent.com/57260466/206908178-7ac18993-49d8-4722-ae8d-94eac684fdc9.jpg)

**Comment by Firefishy** [comment]
It is unlikely we can do anything to solve the certificate issue on @maro-21 machine

1. We use the move widely compatible certificate chain supported by LetsEncrypt.
2. We use HSTS preload by choice as detailed above.

The root certificate trust issues will need to be fixed locally by @maro-21 on his machine. Sorry.

**Comment by tomhughes** [comment]
Yes I don't know why he can't delete. I've only got Windows 10 here and that has a different structure to the interface but it certainly has a delete option.

Maybe if he's running as a normal user it won't let him edit the system certificates but will let him add roots to his personal trust store? In which he he needs to login as an administrator to remove it, and possibly to add the other one at system level.

**Comment by gravitystorm** [comment]
> Adding the ISRG Root X1 root certificate should fix the certificate trust issues on your machine. Alternatively enable Windows Update and you should get the updated certificates automatically via Windows updates.

Just to note, there's also the issue with old versions of OpenSSL that can throw a spanner in the works: 

> In OpenSSL 1.0.x, a quirk in certificate verification means that even clients that trust ISRG Root X1 will fail when presented with the Android-compatible certificate chain we are recommending by default.

This means that even with the ISRG Root X1 certificate installed correctly, depending on the software (and whether it uses an internal copy of OpenSSL, or a version provided by the platform) you can still get certificate errors. I've come across this multiple times dealing with customers with old versions of software running on old versions of Windows, and generally there's no fix for it other than upgrading. It can also explain why some browsers (or other applications) might work and others not, despite being on the same computer.

But the result is the same - there's nothing that can be done on the OSM.org side of things.
