### ISSUE TITLE
Upgrade machines to Ubuntu 16.04

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#81]
Upgrade all our machines to Ubuntu 16.04:
- [x] clifford.openstreetmap.org (currently 14.04)
- [x] cmok.openstreetmap.org (currently 16.04)
- [x] draco.openstreetmap.org (currently 14.04)
- [x] drogon.openstreetmap.org (currently 14.04)
- [x] dulcy.openstreetmap.org (currently 14.04)
- [x] errol.openstreetmap.org (currently 14.04)
- [x] eustace.openstreetmap.org (currently 14.04)
- [x] gorynych.openstreetmap.org (currently 14.04)
- [x] grindtooth.openstreetmap.org (currently 14.04)
- [x] grisu.openstreetmap.org (currently 14.04)
- [x] ironbelly.openstreetmap.org (currently 14.04)
- [x] jakelong.openstreetmap.org (currently 14.04)
- [x] karm.openstreetmap.org (currently 16.04)
- [x] katie.openstreetmap.org (currently 14.04)
- [x] katla.openstreetmap.org (currently 12.04)
- [x] kessie.openstreetmap.org (currently 14.04)
- [x] konqi.openstreetmap.org (currently 14.04)
- [x] longma.openstreetmap.org (currently 14.04)
- [x] lurien.openstreetmap.org (currently 14.04)
- [x] nadder-01.openstreetmap.org (currently 14.04)
- [x] nadder-02.openstreetmap.org (currently 14.04)
- [x] nepomuk.openstreetmap.org (currently 14.04)
- [x] noquiklos.openstreetmap.org (currently 14.04)
- [x] orm.openstreetmap.org (currently 14.04)
- [x] ouroboros.openstreetmap.org (currently 14.04)
- [x] pummelzacken.openstreetmap.org (currently 14.04)
- [x] ramoth.openstreetmap.org (currently 12.04)
- [x] ridgeback.openstreetmap.org (currently 14.04)
- [x] ridley.openstreetmap.org (currently 14.04)
- [x] saphira.openstreetmap.org (currently 14.04)
- [x] sarel.openstreetmap.org (currently 14.04)
- [x] sarkany.openstreetmap.org (currently 14.04)
- [ ] shenron.openstreetmap.org (currently 14.04)
- [x] simurgh.openstreetmap.org (currently 14.04)
- [x] spike-01.openstreetmap.org (currently 14.04)
- [x] spike-02.openstreetmap.org (currently 14.04)
- [x] spike-03.openstreetmap.org (currently 14.04)
- [x] spike-04.openstreetmap.org (currently 14.04)
- [x] spike-05.openstreetmap.org (currently 14.04)
- [x] stormfly-01.openstreetmap.org (currently 14.04)
- [x] stormfly-02.openstreetmap.org (currently 16.04)
- [x] thorn-01.openstreetmap.org (currently 14.04)
- [x] thorn-02.openstreetmap.org (currently 14.04)
- [x] thorn-03.openstreetmap.org (currently 14.04)
- [x] thorn-04.openstreetmap.org (currently 14.04)
- [x] thorn-05.openstreetmap.org (currently 14.04)
- [x] trogdor.openstreetmap.org (currently 14.04)
- [x] urmel.openstreetmap.org (currently 14.04)
- [x] viserion.openstreetmap.org (currently 14.04)
- [x] yevaud.openstreetmap.org (currently 14.04)

**Comment by gravitystorm** [comment]
fafnir was a temporary machine at AWS so I don't think it's important. Poldi is long-term offline (see #79) and I would imagine will be reinstalled before coming back online. 

So I think it's just shenron remaining now.

**Comment by Firefishy** [comment]
Poldi would only come back as a clean reinstall. I'm going to mark it as done.

**Comment by tomhughes** [comment]
I've removed fafnir and poldi completely - fafnir no longer exists and poldi as @Firefishy says will not come back as is.

Which just leaves shenron, which is waiting on figuring out the OSQA mess.

**Comment by gravitystorm** [comment]
https://github.com/openstreetmap/operations/issues/149 for the OSQA challenge.

**Comment by tomhughes** [comment]
Replaced by #220.
