### ISSUE TITLE
Review cookie lifetime for analytics

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#812]
Following discussion with LWG:

- @tomhughes to examine the options and what their effects will be. Suggestion to already lower the 13 month to 1 month lifetime for the long-lived cookie.
- Tom Hummel from LWG will look at cookie lifetimes to try to see what's acceptable.
- @grischard will take care of communication between OWG and LWG, and let LWG know about the timeline when we have one

The goal is to avoid having to add an obnoxious cookie notice for EU eyeballs. Note that this isn't related to GDPR, but to the EU cookie law.

**Comment by tomhughes** [comment]
We have stopped recording user IDs and the session cookie has been reduced to 28 days and the referrer cookie to 7 days.

**Comment by grischard** [comment]
Thank you! I'll let LWG know.
