### ISSUE TITLE
Migrate South Africa imagery to angor

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#813]
Our South Africa imagery is currently hosted on draco at UCL, which is due to be decommissioned or moved (#770). 

Migrate that imagery to angor, which is hosted by [INX-ZA](https://ispa.org.za/inx/) in Cape Town, and closer to the mappers who use the imagery.

**Comment by grischard** [comment]
@Firefishy do you want to do this before your UCL visit, and de-rack draco there?

**Comment by Firefishy** [comment]
Makes sense!

**Comment by Firefishy** [comment]
Imagery has been migrated to ironbelly for now. Future optimisation or moves will be done separately.
