### ISSUE TITLE
Create PostgreSQL dashboard

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#815]
When doing server-level investigations involving PostgreSQL I still turn back to munin, because there's no PostgreSQL dashboard

**Comment by tomhughes** [comment]
Actually there are two - one in drafts which just lists the servers and databases along with versions etc and one in munin where I started replicating the munin graphs.

Neither has been added to the public list yet.

**Comment by Firefishy** [comment]
Available here: https://prometheus.openstreetmap.org/d/77k_bqFMz/postgresql
If there is a need for extra features that can be opened as another request.
