### ISSUE TITLE
502 Bad Gateway on Discourse

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/operations#819]
As of a few minutes ago, https://community.openstreetmap.org/ consistently returns an HTTP 502 error when I connect from here in California.

**Comment by Firefishy** [comment]
It is caused by this https://github.com/discourse/discourse_docker/pull/653

I am trying to repair now. Discourse do not do normal software releases. I need to pin the config. It is horrible.

**Comment by 1ec5** [comment]
It’s up again, thanks!
