### ISSUE TITLE
Issue package lost in France

### ISSUE THREAD

**Issue by jbouzekri** [openstreetmap/operations#82]
Hi,

Sorry if I post this in the wrong place but i could not find the right place to do it.

I have issues since this morning when using a/b/c.tile.openstreetmap.org tile servers in https.

This is a simple mtr report : 

```
mtr --report a.tile.openstreetmap.org
Start: Mon May 23 13:57:37 2016
                                          Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- vss-6a-6k.fr.eu            0.0%    10    0.4   0.5   0.4   1.3   0.0
  2.|-- be11-209.rbx-g2-a9.fr.eu   0.0%    10    0.7   0.7   0.6   0.9   0.0
  3.|-- be100-1188.ldn-5-a9.uk.eu  0.0%    10    4.0   4.2   4.0   4.4   0.0
  4.|-- xe-01.linx.london01-baku0  0.0%    10   19.0  19.0  19.0  19.5   0.0
  5.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  6.|-- 94.20.20.55               40.0%    10   87.5  89.0  87.5  93.6   2.3
```

As you can see, there is a 40% loss of package.

It results in this kind of error : 

```
curl -v https://a.tile.openstreetmap.org/8/130/89.png 2>&1
* Hostname was NOT found in DNS cache
*   Trying 94.20.20.55...
* Connected to a.tile.openstreetmap.org (94.20.20.55) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to a.tile.openstreetmap.org:443 
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to a.tile.openstreetmap.org:443
```

Or 

```
curl -v https://a.tile.openstreetmap.org/8/130/89.png 2>&1
* Hostname was NOT found in DNS cache
*   Trying 94.20.20.55...
* Connected to a.tile.openstreetmap.org (94.20.20.55) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: OU=GT10956697; OU=See www.rapidssl.com/resources/cps (c)13; OU=Domain Control Validated - RapidSSL(R); CN=*.tile.openstreetmap.org
* 	 start date: 2015-05-16 07:28:06 GMT
* 	 expire date: 2017-10-20 18:18:01 GMT
* 	 subjectAltName: a.tile.openstreetmap.org matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
* 	 SSL certificate verify ok.
> GET /8/130/89.png HTTP/1.1
> User-Agent: curl/7.38.0
> Host: a.tile.openstreetmap.org
> Accept: */*
> 
* SSLv3, TLS alert, Client hello (1):
* Empty reply from server
* Connection #0 to host a.tile.openstreetmap.org left intact
curl: (52) Empty reply from server
```

And on a side note, why is GeoDNS for France in Azerbaijan when there is closer server in germany, london, ... ?

Thanks in advance

**Comment by tomhughes** [comment]
The Amsterdam tile server which normally carries much of our European load is currently down so the excess load has automatically spread out over our other servers hence why you are being sent to the server in Baku which seemingly is not reliably reachable from your location.

The reason France is being singled out is that it's a relatively large load (about 4-5 times Spain or Italy for example) so was harder for our algorithm to find a home for... I've increased the target bandwidth limits for a couple of the other caches now so it is getting served from somewhere closer to home.

I've also got somebody looking at the Amsterdam machine now so hopefully it will be back up soon.

**Comment by jbouzekri** [comment]
Thanks for your quick and detailed answer. 

* Do you know where I could watch the status of these servers ?
* Was it the right place to post this kind of issue ?

**Comment by tomhughes** [comment]
Well http://dns.openstreetmap.org/tile.openstreetmap.org.html shows the current mapping of sources to servers, and http://munin.openstreetmap.org/ is the general monitoring for all our servers but it would be hard to tell anything from that without know what you were looking for - we have enough tile caches that it is normally fairly harmless when one is out of action as the load just rebalances.

**Comment by jbouzekri** [comment]
Yeah I saw those 2 services. I think i will stay with the GeoDNS map to watch for the Amsterdam machine to be up online.
