### ISSUE TITLE
Investigate why AWS is not being billed

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#822]
Our AWS usage for non-rendering purposes has stopped being billed and is being paid by credits whose sources is unknown but which might be leakage from the rendering sub-account which is where they should be used.

**Comment by Firefishy** [comment]
We added AWS credits to an AWS Organizations sub-account and [credit sharing is enabled by default](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/useconsolidatedbilling-credits.html). The credits from the sub-account are being used unexpectedly by the other account.

At the moment we've spent 30% of our allocated credits which expiry after 1 year on 30/9/2023.

At the current spend rate we are likely to reach the 30/9/2023 expiry date without having used all the credits.
