### ISSUE TITLE
Semi-automatically update prometheus exporters

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#827]
https://github.com/openstreetmap/prometheus-exporters is currently maintained by hands.

https://gist.github.com/grischard/2cafeaa0073c45d74d4260c16b565f57 is a second draft for a system that automatically updates exporters. The idea is to create a github PR when there's an update.

**Comment by Firefishy** [comment]
The repo updated automatically since: https://github.com/openstreetmap/prometheus-exporters/commit/1fea9084d33625255c0e4de87bd3a89547b1386a
