### ISSUE TITLE
Decommission grisu

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#828]
Decommission grisu at Bytemark.

- [x] Remove Chef config
- [x] Wipe Disks https://github.com/PartialVolume/shredos.x86_64
- [x] Remove DNS
- [ ] De-rack
- [ ] Disposed

**Comment by tomhughes** [comment]
Note that #829 should be done first as grisu provides the network access both to katla and to katla's OOB console.

**Comment by Firefishy** [comment]
Wipe started. Expected to finish in a few hours.

**Comment by Firefishy** [comment]
Wiped.

**Comment by Firefishy** [comment]
Powered down. 

Nerd fun: No IPMI control, only pure serial access and only ability to PDU reset. In BIOS disabled automatic power-on after power restore. Used PDU to reset power. Done ;-)

**Comment by Firefishy** [comment]
Disks for scrapping:
1 x 2 TB HP MB2000FCWDF
2 x 2 TB HP MB2000FBUCL
9 x 2 TB HP MB2000FBZPN

**Comment by Firefishy** [comment]
Hardware is being donated to [University Radio York](https://ury.org.uk/). Hardware should be collected on 20th Feb 2023. Will re-open if required.
