### ISSUE TITLE
Decommission katla

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#829]
Decommission katla at Bytemark.

- [x] Remove Chef config
- [x] Wipe Disks https://github.com/PartialVolume/shredos.x86_64
- [x] Remove DNS
- [ ] De-rack
- [ ] Disposed

**Comment by Firefishy** [comment]
All data storage disks (including hotspare) are being erased now.
OS disks are pending.

**Comment by Firefishy** [comment]
Machine wiped. SO MANY DISKS!

**Comment by Firefishy** [comment]
Powered down.

**Comment by Firefishy** [comment]
For the archives... Katla cost £28,798.40 inc VAT when purchased in April 2013. We bought the machine with a 3 year warranty. It was in service for nearly 10 years ;-)

Original Hardware Spec:
```
1x SuperChassis 417E26-R1400LPB
1x SuperMicro X9DR7-LN4F mainboard
2x LSI MegaRAID SAS 9271-8iCC + CacheVault Module (LSICVM01) - Each
controller dedicated to a backplane with 2x cables (SFF-8087 to
SFF-8087) between controller and backplane
1x BPN-SAS-216A backplane - to replace 1x of BPN-SAS2-216EL2 backplane
supplied with chassis. Motherboard SAS ports (8 ports) + Motherboard
SATA (2 + 8) ports to be wired upto this backplane. Supermicro Support
have confirmed this backplane replacement is possible. BPN-SAS2-216EL2
will be retained as spare. SATA cables with clips much preferred.
2x Xeon E5-2665
16x 16GB PC3-12800 Registered ECC
18x  ST900MM0026 900GB 2.5” SAS2 (connected to 1st 216EL2 backplane
via 1st LSI controller)
7x ST900MM0026 900GB 2.5” SAS2 (connected to 2nd 216EL2 backplane via
2nd LSI controller)
2x ST600MM0026 600GB 2.5” SAS2 (connected to 216A backplane via SAS
ports on motherboard)
2x Intel DC S3700 400GB (connected to 216A backplane via SATA3 ports
on motherboard)
```

**Comment by Firefishy** [comment]
Disks for scrapping:
25 x 900GB Seagate ST900MM0026
2 x 600GB Seagate ST600MM0026

**Comment by Firefishy** [comment]
Hardware is being donated to [University Radio York](https://ury.org.uk/). Hardware should be collected on 20th Feb 2023. Will re-open if required.
