### ISSUE TITLE
Low zoom tile updates at z12 unreliable recently

### ISSUE THREAD

**Issue by imagico** [openstreetmap/operations#83]
For example on

http://a.tile.openstreetmap.org/12/2792/1745.png/status
http://a.tile.openstreetmap.org/12/2074/1974.png/status

i currently get last rendered Mar 03.  Seems to be only on z12.  Would be nice if someone could check if the last low zoom re-renders actually worked correctly.

**Comment by tomhughes** [comment]
I'm not sure what exactly we can check - we can hardly go round and examine every tile.

**Comment by tomhughes** [comment]
One server appears to have completed at 03:16 on 3rd March and the other at 00:43 on 4th March which is consistent with the last update to the style being on 2nd March.

**Comment by tomhughes** [comment]
The monthly low zoom render appears to have run on May 1st on both machines - the next run will be tomorrow I think as it runs on the first sunday of the month I think.

**Comment by tomhughes** [comment]
I suspect that the monthly low zoom renders on 1st May did fail but there is no indication why - both appear to have stopped almost immediately but the only thing in the log is:

```
debug: init_storage_backend: initialising file storage backend at: /srv/tile.openstreetmap.org/tiles
Rendering client
```

and I don't appear to have received any email problem reports so it looks like the reason will remain a mystery.

**Comment by tomhughes** [comment]
A manually started `render_list` produces more output but oddly one started by the script, with redirected output doesn't although it does seem to render ties, so those truncated logs are likely misleading.

**Comment by tomhughes** [comment]
Ah the other messages go to stdout not stderr so will be buffered when output is to a file rather than a terminal.

Likely the render_list process died before it finished then, with not everything getting rendered.

Looks like the cause will remain a mystery but hopefully it will kick in about 01:00 tomorrow.

**Comment by imagico** [comment]
That seems plausible - most other low zoom tiles z<12 seem to be from May 01 so the update evidently happened though not on z12 (or at least not completely).

If everything gets updated the next days with the scheduled update that's fine.

Is there maybe a difference in the low zoom update between the regularly scheduled monthly one and the one after style updates?  The time since the last style change has been unusually long.

**Comment by tomhughes** [comment]
Well both use `render_list` with `--min-zoom=0 --max-zoom=12` but the fact the reset of the output is missing from the list suggests to me the processes were killed in some way before they completed.

**Comment by tomhughes** [comment]
So it looks like last night's also failed somewhere in z12 and looking at the logs I believe I know why...

Basically both machines stopped rendering because `render_list` lost contact with `renderd` and that happened because renderd was restarted when the coastlines updated...

**Comment by tomhughes** [comment]
Hopefully https://github.com/openstreetmap/chef/commit/13468016d85ff18765ec72a8e050d3c48eb1bf68 should resolve this.
