### ISSUE TITLE
Many wiki pages are unavailable/blanks/error

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/operations#830]
Dear maintainers,

Starting this morning CET, many wiki pages look unavailable/blanks.
My own User page for instance: https://wiki.openstreetmap.org/wiki/User:Fanfouer
Many proposals: https://wiki.openstreetmap.org/wiki/Proposed_features/Utility_markers_proposal

Not every of them, this one looks safe: https://wiki.openstreetmap.org/wiki/Key:highway

I can provide any additional feedbacks useful to investigate this issue.

Best regards

**Comment by tomhughes** [comment]
The upgrade discussed in #760 is under way but there are 2.5 million page versions that need to be migrated which is taking some time.

**Comment by flacombe** [comment]
Glad to read that, thank you

All the best to end this update

**Comment by tomhughes** [comment]
The migration is complete now and those pages are visible again.

**Comment by flacombe** [comment]
Confirmed

Thank you and good evening
