### ISSUE TITLE
Purchase new DB server

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#832]
Two of the servers that power the API database are scheduled to reach end of life and need upgrades. Because we purchased a new database server last year for DB4, only one is required for AM6.

This upgrade is required in order to maintain the ability to run the website if one site is down.

Current DB server disk usage is 14TiB. Growth has been steady at 15% to 16% per year, so 30TiB is theoretically enough. I'd like some spare, which bumps the size over the 30.72 TiB which would be logical to 34.56 TiB or 39.30 TiB depending on drive size. The drives would be in RAID6 with one hot spare, and two boot drives in RAID1.

Because used HP Gen10 machines support NVMe, they're now the logical option for API DB servers. The two options are a 1U DL360 Gen10 with 10x NVMe or DL380 Gen10 with 16x NVMe capacity.

My preference is currently for the 1U machine, but will re-evaluate this when the budget is approved and it comes purchase time. The 2U is cheaper since it can use 3.84TiB drives instead of 7.68 TiB drives, but takes up more rack space and has fewer common parts with other machines. 

Katla, the [DB server we just decommissioned](https://github.com/openstreetmap/operations/issues/829#issuecomment-1396071216), was 29k GBP in 2013

**Comment by mmd-osm** [comment]
By the way, do you still publish a breakdown of those 14TiB by table/index somewhere?

**Comment by pnorman** [comment]
This is less urgent with the smaller indexes of PostgreSQL 15 since the older existing DB servers now have a longer life.

**Comment by pnorman** [comment]
Based on discussions today, deferring this. Software improvements (mainly PG index size) have reduced DB size *substantially* and we no longer need to replace the two servers scheduled for EOL.

We will need new servers at some point, but this would be 2024 at the soonest. Given the rate drive sizes have been increasing at, sizing the hardware will be much easier then.
