### ISSUE TITLE
Fill out Energy Efficiency Statement

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#833]
From Equinix ticket 5-218621835985 we need to fill out an Energy Efficiency Statement (EEV) to provide to statement to Equinix, and they talk to the government.

We took the required measures in #686, so this is just about providing the document.

I've asked Equinix for their EEV template.

**Comment by Firefishy** [comment]
Template has now been received.

**Comment by pnorman** [comment]
> OpenStreetMap Foundation handles the energy capacity which it has contracted with the data centre(s) responsibly and makes every effort to prevent unnecessary use of electricity by making good use of the technological (hardware/firmware and software) options to limit power consumption.
> 
> In particular, the following technical measures have been taken
> - HPE servers have had power supply mode set to [High Efficiency Mode (Auto)](https://github.com/openstreetmap/operations/issues/686#issuecomment-1189137875)
> - Power Savings Mode has [been enabled](https://github.com/openstreetmap/chef/pull/515) in configuration to be automatically applied for HPE servers
> - Other servers (e.g. Supermicro) which do not support automatic setting of power savings mode have been [manually set](https://github.com/openstreetmap/operations/issues/686#issuecomment-1189137875) to optimal, when available.
> - Unused servers are powered down
> - Old power-inefficient servers have been upgraded to more efficient servers as part of regular hardware replacement
> 
> These settings are applied across all servers on all sites, including Equinix AM6, Equinix DB4, and OSUOSL.

Planning on the above for a statement that is general enough for all sites.

**Comment by Firefishy** [comment]
All HPE servers we also have Power Regulator mode set to Dynamic Power Savings Mode (other options are: Static Low Power Mode, Static High Performance Mode and OS Control Mode)

**Comment by Firefishy** [comment]
Supermicro servers we have all set to `Optimal fan speed` to decrease power usage and allow higher temperature operations.

**Comment by Firefishy** [comment]
All servers have Kernel CPU Scaling Governor set to `ondemand` or `schedutil` (on newer kernels) which downclock the CPU frequency when usage is low, which saves power.

**Comment by Firefishy** [comment]
Intel performance and energy bias hint is set to `balance-performance` across all Intel servers.
