### ISSUE TITLE
Tile server response includes deprecated Expect-CT header

### ISSUE THREAD

**Issue by SandwichCZ** [openstreetmap/operations#837]
When requesting a tile image (such as [this one](https://tile.openstreetmap.org/17/72149/44546.png)), the server responds with various headers including [Expect-CT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT), which was implemented only in Chromium-based browsers. Chromium v107 deprecated this feature, future versions plan to remove it entirely and any response containing this header currently produces a warning (at least in Google Chrome and Microsoft Edge).

Would it be possible to stop sending this response header? According to MDN, certificate transparency is now enforced by default in Chromium-based browsers and any incompatible certificates should have already expired.

**Comment by tomhughes** [comment]
A warning where? Presumably just in the javascript console?

**Comment by tomhughes** [comment]
Also for tiles this may be outside our control as it may be the CDN adding it.

**Comment by tomhughes** [comment]
The current [SecurityHeaders report](https://securityheaders.com/?q=www.openstreetmap.org&followRedirects=on) says it will "soon be deprecated" but does also agree that it can be removed.

**Comment by SandwichCZ** [comment]
Yes, a warning in the JavaScript console, but also in a Lighthouse audit report.

**Comment by tomhughes** [comment]
This header has now been removed - note that for tiles you may continue to see it for a while due to edge caching but I've verified that it is gone from new tiles and old ones will lose the header over as the caches revalidate.

**Comment by pnorman** [comment]
I noticed this a couple days ago and thought about opening an issue
