### ISSUE TITLE
Questions about dev server: load & tracking edits

### ISSUE THREAD

**Issue by petya-kangalova** [openstreetmap/operations#838]
Hi, I have a question about  [master.apis.dev.openstreetmap.org](https://master.apis.dev.openstreetmap.org/). Let me know if I should use a different forum to direct my question.

I only recently discovered the dev server and a few colleagues are considering using it for training purposes. However, we wanted to check on the below:

1. What traffic does the server support? How many people at the same time (a mapathon, a training of +100 people?) 
2. Do the edits ever get cleared out of the dev server, or do they stay there indefinitely?

Thanks in advance! :)

**Comment by tomhughes** [comment]
It supports what it supports - we offer no guarantees of anything.

I don't think we've ever wiped it but we certainly don't guarantee not to - it's a sandbox for testing and anything might happen to it at any time,

**Comment by mmd-osm** [comment]
If you're planning to do end user training, including mapping and checking results on a map, then the dev instance is clearly not a good fit. It's good for some Rails and API testing, but not much more. Tiles, routing, search are all provided by the production services. Also, no minutely diffs are available.

**Comment by petya-kangalova** [comment]
Thanks @tomhughes  and @mmd-osm for answering my questions. We were indeed exploring options for user training but will not be a good fit.
