### ISSUE TITLE
Spring clean awstats

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#84]
Ironbelly is currently keeping ~47GB of awstats results (in `/var/lib/awstats`), which look to be monthly going back to late 2010. Some of these will, no doubt, be of interest to archaeologists in future centuries, but we probably don't need them available, uncompressed on `/`.

Potential options:
- Move to `/store` if we want to keep them available?
- Archive and compress older ones to `/store` if we want them, but not available?
- Thin them to one per year before 2014?

What does everyone think?

**Comment by Firefishy** [comment]
Storage is cheap. ;-)

**Comment by zerebubuth** [comment]
Indeed. But we've used up 50% of `/` in the past year:

![image](https://cloud.githubusercontent.com/assets/271360/15927955/4566fa02-2e3c-11e6-8189-edd7e088f57a.png)

In fact, it looks like `awstats` accounts for only 13GB (about 9%) of that... So there's something else accumulating on `/` as well. I've got nothing against accumulating long-term data, but preferably not on `/`! :smile:

**Comment by pnorman** [comment]
awstats is now shut down.
