### ISSUE TITLE
community.openstreetmap.org source IPv6 address not tracked

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#843]
The community.openstreetmap.org docker containers are not IPv6 enabled and client IPv6 source IP addresses are lost due to the traffic passing through docker-proxy process.

Native Docker IPv6 functionality should be enabled. 

Docker has 2 methods:
1. Provide an [IPv6 block](https://docs.docker.com/config/daemon/ipv6/) and allow container to dynamically use IPv6 addresses from the block.
2. Use a local IPv6 block eg `fd00:dead:beef::/48` with NAT, aka ip6tables, which retains the client IPv6 source IP.

Method 1 will require ensuring the `web_only` container is assigned the same IPv6 address.
Method 2 is likely the preferred method.

**Comment by Firefishy** [comment]
Also see: https://github.com/discourse/discourse_docker/pull/671

**Comment by Firefishy** [comment]
Enabled https://github.com/openstreetmap/chef/commit/17b3949ec013a32c35601f012f98998615f2b593 but still requires docker ip6tables changes.

**Comment by tomhughes** [comment]
As far as I can docker doesn't have builtin support for IPv6 with private addressing as it does for IPv4 by default.

So we'd have to allocate a subnet to it, which we could do but would need a route adding to the switch or else some kind of proxy ARP stuntery only it's proxy IPv6 neighbour discovery if that's even a thing.

The alternative would be to set `ipv6` to `true` in the configuration and `fixed-cidr-v6` to a ULA block and then add some NAT rules ourselves.

**Comment by Firefishy** [comment]
I think all that is required is adding the following to `/etc/docker/daemon.json`, with `ip6tables` docker then manages the NAT rules too.

```
    "ipv6": true,
    "ip6tables": true,
    "fixed-cidr-v6": "fd9e:d0ce:beef::/48" 
```

**Comment by tomhughes** [comment]
Well excuse me for not find the `ip6tables` option that the dockerd manual page doesn't mention.... Though that is probably because of this:

```
Apr 05 19:32:15 faffy.openstreetmap.org dockerd[2497954]: failed to start daemon: ip6tables rules are only available if experimental features are enabled
```

**Comment by Firefishy** [comment]
Docker documentation is generally horrible. I think despite the feature being marked as experimental it should be reasonably stable.

I've PR'ed the change: https://github.com/openstreetmap/chef/pull/586

Might need further testing to see if it works on an IPv4 only machine.

**Comment by Firefishy** [comment]
Confirm fixed.
