### ISSUE TITLE
Switching away from Ubuntu LTS to Debian as our preferred distribution

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#844]
Currently we run a combination of Ubuntu 20.04 LTS and Ubuntu 22.04 LTS across our server estate.

[Ubuntu 20.04 has recently moved away from the established 5 years of maintenance updates and now requires a paid Ubuntu Pro plan](https://askubuntu.com/questions/1452497/what-are-esm-apps-and-how-do-they-relate-to-ubuntu-pro) (<= 5 systems are free) to receive some package security updates. It is expected this will be expanded to Ubuntu 22.04 shortly.

We've also had issues with Ubuntu not fully supporting the packages they source from Debian. eg: Apache2 which required us to backport a fixed version to workaround an issue affecting mpm event scaling.

Ubuntu has also caused us issue with some packages now only being distributed as snap packages (eg: Firefox).

Debian stable is supported for 5 years and the complete package ecosystem, from my point of view seems to be better supported. ["Non-free firmware" bundled installers](https://wiki.debian.org/Firmware) are now also available.

Unresolved questions?

-  ~~HPE MCP support?~~ Maybe? https://downloads.linux.hpe.com/SDR/repo/mcp/Debian/dists/bullseye/
-  ~~Vendor Reports eg: PostgreSQL?~~ Yes: https://www.postgresql.org/download/linux/debian/
- Alternative to [launchpad PPA](https://launchpad.net/~osmadmins/+archive/ubuntu/ppa) (including build pipeline)
- Upgrades between LTS releases?

**Comment by Firefishy** [comment]
Debian Stable (currently: bullseye) seems like the logical choice to me.

**Comment by grischard** [comment]
Github actions run on ubuntu, will that be an issue?

**Comment by tomhughes** [comment]
What actions do you have in mind? As far as chef tests are concerned the tests run in a container separate to the host container that actions provisions so can run whatever we want.

**Comment by gravitystorm** [comment]
> [Ubuntu 20.04 has recently moved away from the established 5 years of maintenance updates and now requires a paid Ubuntu Pro plan](https://askubuntu.com/questions/1452497/what-are-esm-apps-and-how-do-they-relate-to-ubuntu-pro)

So as far as I understand, that's not quite what has happened. What has changed is that there are now additionally Ubuntu-supplied (i.e. from Canonical staff) patches for the universe repo, that are only available for their paid subscriptions.

Previously:
| | main | universe |
|---|---|---|
| free | Ubuntu supplied updates (5 years)    | Community-supplied updates only |
| paid (ESM) | Ubuntu supplied updates (10 years) | Community-supplied updates only |

Now:
| | main | universe |
|---|---|---|
| free | Ubuntu supplied updates (5 years) | Community-supplied updates only |
| paid (ESM) | Ubuntu supplied updates (10 years) | **Ubuntu supplied updates (10 years)** |

So now for people using the free option, like OSMF, you are seeing warnings that there are ESM-only updates for packages in universe. But for people on the free option nothing has changed - previously we needed to wait for community-supplied patches for packaged in universe, generally backports from debian, and we still do.

In saying all that, I can agree with the other reasons for considering alternatives :+1:

**Comment by tomhughes** [comment]
Yes I was struggling to parse that post but came to much the same conclusion as @gravitystorm that nothing is actually being lost it's that some things are being added for subscribers.

**Comment by Firefishy** [comment]
Yes, while previously `universe` was only _officially_ supported by the community it did receive some security updates from Canonical employees (and likely others). [Random example python2.7 2.7.18-13ubuntu1.1](https://changelogs.ubuntu.com/changelogs/pool/universe/p/python2.7/python2.7_2.7.18-13ubuntu1.1/changelog) but now that paid ESM has been introduced subsequent updates are only available via subscription. Example [python2.7 2.7.18-13ubuntu1.1+esm2](https://ubuntu.com/security/notices/USN-5342-2)

**Comment by Firefishy** [comment]
Requires some chef changes

* Replace netplan with systemd networkd
* Replace shorewall with nftables based firewall (desired)

**Comment by mmd-osm** [comment]
I found this issue today and was wondering a bit about the implications on cgimap. Did you have some timelines in mind with regards to the launchpad topic? What would the future workflow look like, and who would do package builds in the future, then?

**Comment by Firefishy** [comment]
> I found this issue today and was wondering a bit about the implications on cgimap. Did you have some timelines in mind with regards to the launchpad topic? What would the future workflow look like, and who would do package builds in the future, then?

One option might be to build package releases using GitHub actions. I am happy to help create this if desired.

**Comment by mmd-osm** [comment]
I think it would be good to have maybe one common approach for osmdbt, cgimap, and all the other tools on https://launchpad.net/~osmadmins/+archive/ubuntu/ppa - to make life a bit easier for everyone.

I've seen a few packages on https://github.com/orgs/openstreetmap/packages, which seem to be containerized versions of various repos. I'm not sure if this what you meant by package releases.

osmdbt uses `debuild -I.` to build debian packages, which could then be installed using dpkg -i. Somehow we would have to store these debian packages somewhere.

Itt would be good to have some sample repo covering all the steps, which could then serve as a reference for everyone.

**Comment by tomhughes** [comment]
Please stop panicing. Obviously we will need to arrange a replacement for the osmadmins PPA but that is an open issue that needs to be investigated.

Ideally we would host our own repository but past experience of investigating ways to do that tells me that it's ridiculously hard to do for apt repositories which is exactly why we used the PPA in the first place but we may to try and find a way to do it now as I'm not aware of any public alternatives.

Building in github actions as suggested by @Firefishy may work for doing the builds but as far I as know it doesn't help with hosting the resulting packages as an apt compatible repository.

**Comment by Firefishy** [comment]
We now have added Debian 12 to our chef tests.

**Comment by Firefishy** [comment]
On package building alternative: [PackageCloud offer free accounts to OSS projects](https://blog.packagecloud.io/packagecloud-loves-oss/). It is likely that we might qualify. [They also have an integration with GitHub actions which is nice](https://blog.packagecloud.io/using-github-actions-ci-to-publish-your-software-or-library-package-to-packagecloud-repository/).

**Comment by mmd-osm** [comment]
I’ve seen https://en.osm.town/@Firefishy/111428422893931648 and am wondering now which Debian version we need to support next year. In particular we need to know if packages in Debian would be much older or even don’t exist vs what we have now with Ubuntu 22.04. This obviously needs some planning that’s why I’m asking today already.

**Comment by matthewdarwin** [comment]
At work we use `dpkg-deb` to build debian packages for ourselves and then publish them into our own apt repo with `reprepro`.  Nothing too complicated there.  Then add the package repository to sources.list.d on the target machines.  Managing 100s of packages and 100s of servers (lxc containers) this way.

**Comment by Firefishy** [comment]
> I’ve seen https://en.osm.town/@Firefishy/111428422893931648 and am wondering now which Debian version we need to support next year. In particular we need to know if packages in Debian would be much older or even don’t exist vs what we have now with Ubuntu 22.04. This obviously needs some planning that’s why I’m asking today already.

We are currently targeting Debian 12 (bookworm). It is likely we will track Debian stable (currently Debian 12 - Bookworm).

**Comment by Firefishy** [comment]
Servers [fume](https://hardware.openstreetmap.org/servers/fume.openstreetmap.org/) and [grisu](https://hardware.openstreetmap.org/servers/grisu.openstreetmap.org/) are now running Debian 12. There were a few minor issues to resolve with Firmware, HPE Management Component Pack (MCP) repo, these are now all in chef.

I will create a follow-up ticket for a "PPA" package repo + builder replacement.
