### ISSUE TITLE
Set bucket policies on public buckets to enforce TLS 1.2

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#846]
AWS is removing TLS 1.1 and 1.0 support in June for buckets. Until then, they notify us every couple of weeks if we have TLS 1.0 or 1.1 activity on our user avatar or GPX trace buckets.

We should set up a bucket policy that blocks old TLS versions in preparation of it being required. This can be done as described in https://repost.aws/knowledge-center/s3-enforce-modern-tls

This has no real user impact as we only have a couple calls a month on old TLS versions, and 1.2 **will** be required later this year anyways. osm.org requires TLS 1.2 or later, so users from the website who request old objects are either getting incredibly unlucky and having a connection downgrade, or are being subject to some form of attack to downgrade the connection.

Mainly I just want to quiet the emails.

**Comment by Firefishy** [comment]
The most likely thing to break will be old code paths or libraries that expect TLS 1.0 or 1.1
I guess disabling 1.0/1.1 before is to flush these out sooner.

**Comment by pnorman** [comment]
> The most likely thing to break will be old code paths or libraries that expect TLS 1.0 or 1.1

There aren't any of these. We get breakdowns in email, and all the occasional uses are browsers that support 1.2.

**Comment by Firefishy** [comment]
> > The most likely thing to break will be old code paths or libraries that expect TLS 1.0 or 1.1
> 
> There aren't any of these. We get breakdowns in email, and all the occasional uses are browsers that support 1.2.

If there are no < TLS 1.2 clients, then why do we need a Bucket Policy which restricts TLS 1.2? Wouldn't it just be easier to wait for the change? A bucket policy it another thing to maintain.

> Mainly I just want to quiet the emails.

I am doubtful a custom bucket policy will stop the emails.

**Comment by pnorman** [comment]
> If there are no < TLS 1.2 clients, then why do we need a Bucket Policy which restricts TLS 1.2? Wouldn't it just be easier to wait for the change? A bucket policy it another thing to maintain.

TLS 1.2 clients are getting occasionally downgraded to TLS 1.0

> > Mainly I just want to quiet the emails.
> 
> I am doubtful a custom bucket policy will stop the emails.

It will stop the downgraded requests.

**Comment by pnorman** [comment]
At this point, it's close enough to when TLS 1.0 is being turned off that it's not worth the effort to disable it early to stop the emails.
