### ISSUE TITLE
Decommission noquiklos

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#849]
Decommission noquiklos at UCL Slough.

- [x] Remove Chef config
- [x] Wipe Disks
- [x] Remove DNS
- [x] De-rack
- [x] Disposed

**Comment by Firefishy** [comment]
Nothing worth keeping. Scrap.

**Comment by Firefishy** [comment]
Wiped and powered down.

**Comment by Firefishy** [comment]
Server has gone for WEEE recycling and is waiting to be collected.
