### ISSUE TITLE
Certificate SHA-256 MAC

### ISSUE THREAD

**Issue by ximex** [openstreetmap/operations#85]
Change certificate with a SHA-256 MAC

**Comment by Firefishy** [comment]
Which certificate? We have a few.

**Comment by ximex** [comment]
*.openstreetmap.org

**Comment by tomhughes** [comment]
That certificate has been SHA256 for some time:

https://www.ssllabs.com/ssltest/analyze.html?d=www.openstreetmap.org&s=89.16.162.22&latest

**Comment by ximex** [comment]
ahhh. i see. this is a problem of the server-preferred order. I got `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA` (Nr 3 in the order)
I will open a new issue for that
