### ISSUE TITLE
Decommission pummelzacken

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#850]
Decommission pummelzacken at UCL Slough.

- [x] Remove Chef config
- [x] Wipe Disks
- [x] Remove DNS
- [ ] Recover SSD and RAM
- [ ] De-rack
- [ ] Disposed

**Comment by Firefishy** [comment]
We should definitely keep:
6x 400GB SSD
8x 16GB DDR3 ecc

The machine isn't bad, could be repurposed with minor hardware refresh.

**Comment by Firefishy** [comment]
Wiped and powered down.

**Comment by grischard** [comment]
Blocked by #1060

**Comment by Firefishy** [comment]
Yesterday while on-site I tested upgrading to 16x 16GB RAM. The system would not boot.

The RAM should be recovered when we scrap the machine.

**Comment by Firefishy** [comment]
Disks have been removed and retained. Server has gone for WEEE recycling and is waiting to be collected.
