### ISSUE TITLE
decommission eddie as database mirror and as server

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#851]
As part of the move from UCL (#770), decommission eddie at UCL Slough.

- [ ] Remove eddie as database mirror
- [ ] Remove Chef config
- [ ] Wipe Disks
- [ ] Remove DNS
- [ ] De-rack
- [ ] Disposed

**Comment by pnorman** [comment]
karm and eddie were going to run out of disk space this year, but with the PG upgrade and smaller index sizes, I'm wondering if we should keep them around longer.

**Comment by pnorman** [comment]
We've decided to keep karm and eddie around as they have disk space now.
