### ISSUE TITLE
Discourse dashboard does not show 502 errors

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#853]
We've had some reports of 502 errors with discourse (e.g. https://community.openstreetmap.org/t/currently-no-login-possible/9506/3). Looking at the dashboard, there are no 502 errors in the errors graph, only 500. Looking at the underlying metric, discourse_http_requests, it only produces numbers for 500 errors.

**Comment by tomhughes** [comment]
Isn't 502 bad gateway? So it likely comes from the nginx on the host because proxying to the container failed, not from anything discourse knows anything about.

**Comment by tomhughes** [comment]
Actually there is no host proxy in this case, the docker container is directly exposed.

The root cause of the reported issue was that the docker container was unable to make outgoing network connections due to a firewall issue, so it was failing to get an OAuth access token.

**Comment by Firefishy** [comment]
We are reliant on the https://github.com/discourse/prometheus_exporter , functionality reports should go upstream.
