### ISSUE TITLE
Enable Strict Transport Security (HSTS)

### ISSUE THREAD

**Issue by ximex** [openstreetmap/operations#86]
Enable Strict Transport Security (HSTS) with max-age=15768000

**Comment by tomhughes** [comment]
Unfortunately we're not able to do this as it breaks OAuth for clients that are using http URLs - we did try once but it broke too many things.

Obviously it would be better if all those clients used https URLs but with no way to contact them all and ask them to change there is no easy way to get them to switch.

**Comment by ximex** [comment]
which webserver is in use? isn't it possible to add this header only to the `https` url? so clients that use `http` wouldn't see this header

**Comment by tomhughes** [comment]
You're missing the point - as soon as you return that header browsers will automatically convert future http requests to https.

So if another web site has javascript that tries to talk to our API using an http URL it will sign the request as if it was http but the browser will actually transmit it over https so when we try to validate the signature it will fail as the URL used in computing the signature will be different.

There's actually also a second problem, which is that if we enable it then it is essentially equivalent to going https only in that anybody who ever visits an https URL (such as the login page) is then unable to use http at all. We have some users who, for performance reasons, prefer to use http and for now we have chosen not to force them to use https but enabling this would essentially do so.

**Comment by ximex** [comment]
I See. Are there any statistics of how many % oft the request are still http or TLS 1.0 connections?
