### ISSUE TITLE
OSMF: Investigate replacements for osmfoundation.org email hosting

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#860]
osmfoundation.org currently use Google Workspace ("Gsuite") for email hosting and email group management. The other Google Workspace features / apps are generally not used.

Google Workspace spam filter is becoming unmanageable, frequently rejecting legitimate email even from osmfountation.org services.

Recent "spam" issue example:
Any email sent from any OSM Foundation wiki (https://wiki.osmfoundation.org/, https://mwg.osmfoundation.org/, https://board.osmfoundation.org and https://dwg.osmfoundation.org) to osmfoundation.org was being SMTP rejected by Google SMTP servers as spam. This despite the emails being DKIM signed, SPF allowed and the sender IP allowlisted in Google Workspace. Google support were able to help us to get the osmfoundation.org Google Workspace to accept the emails via a horrible workaround (set the sending SMTP server IP as a relay server in Google Workspace settings) but the emails are still being rejected by gmail.com or any other Google Workspace hosted email.

Google Workspace false positive spam filtering (including SMTP reject) rates are unacceptably high.

Supporting the broken Google Workspace email product is becoming untenable.

Current stats:
* 21 users
* 25 groups
* Largest current mailbox size: 9GB. (Median ~1GB)

Current Cost:
* £4.60 GBP per user/month (Google Workspace Business Starter). 

Requirements:
* Webmail
* Secure Email Hosting (with custom domain)
* Email Groups allow outside recipients
* Delegated Email Group Management (osmfoundation.org member can maintain groups and recipients)
* Low Maintenance overhead
* Reasonable Pricing and Billing
* Low false positive spam filtering
* Ability to import / migrate existing Google Workspace Email (mbox import, IMAP or other process)
* GDPR compliance

**Comment by Firefishy** [comment]
https://proton.me/business/plans is an option

**Comment by Firefishy** [comment]
https://www.fastmail.com/pricing/ has been suggested as good.

**Comment by ljrk0** [comment]
Very satisfied with https://www.migadu.com/, they don't even pretend that Mail is safe/secure but do their very best despite that.  Superb support, well-designed and functional control panel.  You can try for free first of course.

**Comment by redhumus** [comment]
iredmail.org is my best option

**Comment by Firefishy** [comment]
> Very satisfied with https://www.migadu.com/, they don't even pretend that Mail is safe/secure but do their very best despite that. Superb support, well-designed and functional control panel. You can try for free first of course.

Interesting. They also have Terraform support: https://registry.terraform.io/providers/metio/migadu/latest/docs

**Comment by lonvia** [comment]
Two more:
* https://tutanota.com/
* https://www.startmail.com/

**Comment by JaffaKetchup** [comment]
I've recently seen https://www.hey.com/ out in the wild, and they have a concept called The Screener. No email goes to spam or inbox, until you "Yes" it or "No" it.
Reasonably priced, although more than Google Workspace. Maybe possible to import email from Gmail through Google Takeout?

**Comment by RogueScholar** [comment]
I'd have to do some digging into the groups/distribution lists to make sure it met that requirement, but I have only the highest praise to offer to [PolarisMail](https://www.polarismail.com) (a/k/a EmailArray) out of Montreal, Canada. I've used them for my own e-mail hosting across a couple dozen domains for 4+ years as well as for several SMB consulting clients with 25-200 users and everything has Just Worked™. They've never had any downtime that I've observed in that instance, respond to my support requests quickly (in the rare event I make them), keep the GroupOffice webmail interface up-to-date, and don't charge me an arm and a leg to make it happen.

Having spent many years as an SA, I sadly concur that Google Workspace has eroded to the point of broad undesirability, which is sad considering about a decade ago I would've ranked it on the top of the heap in terms of manageability and user satisfaction. Currently the prevailing wisdom would appear to hold Microsoft 365 pretty peerless in this space and I think that's about right, but at the prices they charge they'd better be, and it's no cakewalk to oversee what with so key tasks requiring PowerShell to access and the UI getting shuffled like a deck of cards every 6-9 months. Behind them I don't see a ton of differentiation, save maybe with Zoho (mostly for the breadth of their services). My counsel to whomever is tasked with evaluating these options is not to get too granular in comparing feature sets but optimize for cost, security and relative simplicity instead, which is how I settled on PolarisMail the last time I had to perform this calculus myself.

**Comment by matkoniecz** [comment]
Email continues to be dropped. I received Linkedin message from someone who wrote to `trademarks@osmfoundation.org` and their message never arrived.

We may be ignoring people who wrote mails, only to be eaten by Google - and most likely will not try to reach OSMF board via Linkedin or other weird methods.

**Comment by Firefishy** [comment]
FYI @matkoniecz 09/09/2023 and 10/09/2023 some messages flagged as spam by Google that should have been quarantined for admin approval were silently rejected. Some emails in the quarantine queue prior to this may have also been lost. This was due to a configuration issue. @grischard may have more details. The quarantine queue is working again, but not perfect.

**Comment by Firefishy** [comment]
If privately let me know the sender email address I can check the logs to find out exactly what happened.

**Comment by matkoniecz** [comment]
This specific email was lost, though as I understand changes were applied to reduce risk of this happening again.

**Comment by pnorman** [comment]
If someone wants to help, a good place to start would be making a table with all the options listed above and how they evaluate on the requirements above, as well as cost at current usage.

Figuring out the two or three top options would go a long way.

**Comment by JaffaKetchup** [comment]
@Firefishy You said you've got 21 users, but are you using catch-alls anywhere?

**Comment by Firefishy** [comment]
No catch alls, but there are group email addresses which email internal and external email addresses.

**Comment by JaffaKetchup** [comment]
@Firefishy Sorry for more pinging. Would you settle for a service that limits email in/out? If yes, what is the minimum?

**Comment by JaffaKetchup** [comment]
Google Sheet for tracking: https://docs.google.com/spreadsheets/d/1SPm3_c20mjmkCajy6vLU-dGjurB45x-gd4S0ntqbAD0/edit?usp=sharing
Not 100% complete yet.

**Comment by JaffaKetchup** [comment]
One thing that maybe might need to be thought about is the UKs new Online Safety Bill, particularly around encryption. Some of the mail services have non-disablable E2EE for messages sent within their ecosystem (and some may support PGP for E2EE outside as well). Just saw this on r/ProtonMail as a post, not sure if it could be an issue or not.

**Comment by Firefishy** [comment]
I am going to trial an business account with mailbox.org. I have spoken to them about setting up the trial.

**Comment by Firefishy** [comment]
The trial has now been setup with mailbox.org and I will be testing functionality, imports and other bits.

**Comment by Firefishy** [comment]
I have evaluated mailbox.org and seems like a good replacement for the OSMF.

👍 Webmail - used hosted version of open-xchange.com
👍 Secure Email Hosting (with custom domain) - [testing using openstreetmap.io](https://github.com/openstreetmap/dns/blob/c25da1eb264607e0c30da8deb48107c1ec83f33e/src/openstreetmap-io.js).
👍 Email Groups allow outside recipients - mail forwarders are supported for free, or additional fee if archiving mail.
👎 Delegated Email Group Management (osmfoundation.org member can maintain groups and recipients) - groups have a login, but it doesn't seem to provide any functionality to manage the group.
👍 Low Maintenance overhead
❔ Reasonable Pricing and Billing - ~ €60/month to €120/month depending on support tier and additional functions (eg: Video Conference, Document Storage etc). See https://mailbox.org/en/business-customers#prices-and-contact
❔ Low false positive spam filtering - difficult to test, unknown long term, they use spamassasin + rspam internally.
👍❔ Ability to import / migrate existing Google Workspace Email (mbox import, IMAP or other process) - [Manual import is possible, but very manual](https://kb.mailbox.org/en/private/account-article/move-away-from-gmail-to-mailbox-org-step-by-step), they [offer access to a migration service](https://kb.mailbox.org/en/private/account-article/audriga-your-e-mail-migration-service) which was not tested which will help simplify the process a bit. 
👍 GDPR compliance

**Comment by Firefishy** [comment]
I have finished the initial investigation and made a recommendation to the OSMF.

I am closing this ticket. If the OSMF devices to continue the evaluation then I will re-open this ticket.

Any potential migration will be performance under its own ticket(s).
