### ISSUE TITLE
Matomo WebGL detection no longer working

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#868]
Matomo is reporting 0% support for WebGL, with about 30-40 visits that support it. Something changed in the end of December. On 2022-12-29, 98% of visitors reported WebGL support, on 2022-12-30 it was 78%, and on 2022-12-31 it was 13%.

**Comment by tomhughes** [comment]
The plugin is active so I don't see why there would be any problem, or what I could do to investigate futher.

**Comment by tomhughes** [comment]
Ah I bet the javascript needs rebuilding.

**Comment by tomhughes** [comment]
Should be fixed now.
