### ISSUE TITLE
Better server-preferred order of cipher suites

### ISSUE THREAD

**Issue by ximex** [openstreetmap/operations#87]
https://wiki.mozilla.org/Security/Server_Side_TLS
https://mozilla.github.io/server-side-tls/ssl-config-generator/

What to change:
- AES-128 before AES-256
- ECDH before DHE
- GCM before CBC
- SHA-256 bevore SHA-1

best is to choose the order in the links above

**Comment by tomhughes** [comment]
Thank your for your help, but our current options are very carefully chosen and we regularly check with the ssllabs analyser that we are maintaining the correct trade off between the highest possible security levels and maintaining as much back compatibility as possible so any change needs to be considered very carefully.

**Comment by tomhughes** [comment]
I believe this was resolved by https://github.com/openstreetmap/chef/commit/93462ef55b24b71edbcdbe0f1694f5ae483c6c6c.
