### ISSUE TITLE
Upgrade Equinix power

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#874]
Ask Equinix for quote for moving to 3.5 kVA power in AM6, as we're limited in the machines we can run there and regularly run over.

**Comment by Firefishy** [comment]
Email to Equinix has been sent, waiting for a quote.

**Comment by Firefishy** [comment]
Our agent at Equinix is away until 1st May. We should get the quote soon after then.

**Comment by pnorman** [comment]
Done. #884 has related actions now that we have more power.
