### ISSUE TITLE
Fix power usage monitoring and alerting

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#875]
- Monitoring and alerting should be on apparent power (VA), not real power (W)
- Current alarms should be set to warn of exceeding current limits on the PDU, not power draw limits as there's nothing wrong with imbalanced power across the A/B side
- power draw limits should be placed on total site usage, with one hour averaging

**Comment by tomhughes** [comment]
I've already done most of this.

I changed the dashboard to apparent power and added alerts on apparent power.

I can fix the over-current alerts if somebody can confirm what the limits should be.

One hour averaging might be tricky. I can do it on a rolling hour basis (ie the average over the last hour each time the alert is evaluated) but I'm not sure doing literal calendar hour slots is possible.

**Comment by tomhughes** [comment]
Currently we alert if a PDU in Amsterdam is drawing over 10A and in Dublin over 13A. There are also site wide limits but those were an attempt to police the power limit and can be removed.

What is the technical limit on what we're allowed to draw at each site from a feed?

**Comment by pnorman** [comment]
I think it's 32A per feed. Of course, at that level, we'd be well over the site power limit and have no guarantee of redundancy.

**Comment by tomhughes** [comment]
The PDUs are certainly rated for 32A so that seems like the important number given we have separate alerts for site power so I've set an alert at 28A for any individual PDU at both sites.

I've also changed the site power alert to use a one hour rolling average.

**Comment by pnorman** [comment]
This has been completed.
