### ISSUE TITLE
Cogent Network Maintenance - Amsterdam - 26 April 2023

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#876]
Start time: 00:00 CEST (UTC+2) 26-APR-2023
End time: 06:00 CEST (UTC+2)

Expected Outage/Downtime: 45-60 minutes
Location: Amsterdam

**Comment by pnorman** [comment]
Let's switch Dublin to the primary for this.

**Comment by Firefishy** [comment]
> Let's switch Dublin to the primary for this.

Permanently? Switching is far from easy and is high risk.

**Comment by tomhughes** [comment]
More to the point when we would do it - there's just not enough notice.

**Comment by Firefishy** [comment]
The maintenance has been completed. There was a larger than expected outage of 45 minutes.
