### ISSUE TITLE
Update hardware power caps @ Amsterdam

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#884]
Our contracted power in Amsterdam has been increased from 3kVA to 3.5kVA back dated to 1st May 2023.

The power caps on machines in Amsterdam should be updated accordingly.

**Comment by pnorman** [comment]
Alarms updated in https://github.com/openstreetmap/chef/commit/3c1bfa7a174ea5c22b5c2d241b8e0849af9758d8

**Comment by Firefishy** [comment]
* faffy adjusted 350W → 500W
* dulcy adjusted 400W → 500W
* ironbelly DCMI power not supported
* karm DCMI power limit not set
* norbert adjusted 400W → 500W
* odin adjusted 400W → 500W
* snap-01 DMCI power limit not set
* spike-06, 07, 08 DMCI power limit not set
* vhagar DMCI power limit not set
