### ISSUE TITLE
Expired SSL certificates

### ISSUE THREAD

**Issue by pedrocamargo** [openstreetmap/operations#887]
As per the title.

--2023-05-29 07:44:15--  https://dev.overpass-api.de/clone//2023-05-25/replicate_id
Resolving dev.overpass-api.de (dev.overpass-api.de)... 95.217.37.171, 2a01:4f9:2b:2fd4::2
Connecting to dev.overpass-api.de (dev.overpass-api.de)|95.217.37.171|:443... connected.
ERROR: The certificate of 'dev.overpass-api.de' is not trusted.
ERROR: The certificate of 'dev.overpass-api.de' has expired.
The certificate has expired

**Comment by tomhughes** [comment]
Well complain to the operators of overpass-api.de then - it is not one of our sites.

**Comment by tomhughes** [comment]
For the record I alerted somebody with better knowledge of who can fix this a some hours ago, about two hours after it expired as it triggered deployment failures for us.

**Comment by mmd-osm** [comment]
Let’s encrypt certificate renewal job should take care of it. It should be working again tomorrow by the latest without any further manual intervention needed.

**Comment by tomhughes** [comment]
If that was working then it would have renewed a month ago - most likely the renewal timer is not running or something.

**Comment by mmd-osm** [comment]
Back in February, @lonvia mentioned that some of the dev server settings are managed by Ansible. I believe the config should cover automated certificate renewal: https://github.com/fossgis-routing-server/ansible_openstreetmap.de/tree/master/roles/letsencrypt/tasks

As I'm totally unfamiliar with this part of the config, that's all I can contribute at this time without causing some major havoc.
