### ISSUE TITLE
Can't add bus routes

### ISSUE THREAD

**Issue by duiveldoder** [openstreetmap/operations#888]
increase the limits please. It's getting unworkable like this.

What's my issue. I've started to travel a bit more and wish to add medium-distance bus lines. 
I'm using JOSM and in it the functionality of the plugin:"download from OSM along this track"

My settings are :"download everything within 50 meter and maximum area per request 3 square km"|

and then I get this nice popup telling me:"Communication with the OSM server 'api.openstreetmap.org' failed. The server replied the following error code and the following error message:
Error code: 509
Error message (untranslated): you hae downloaded too much data. Please try again later

okay - so then I don't map this bus route of course because the error message tells me mapping bus routes is unwanted today.

So then I try the next day - but the next day I get the same error message. So the next day OSM officially tells me again don't map bus routes, we don't want bus routes today.

okay - then I try a week later my gpx traces, but then again I get the same message. Getting this now for 2 weeks.

So I'm at this moment at a point - where I'm considering just deleting all gpx traces for bus routes since you officially declare you do not wish mappers to add bus routes.

Would love to hear your opinion about this why your error message is telling me we shouldn't add bus routes based on gpx traces.

Thank you

And yes I've tried using overpass and other means of downloading data - which works - but it won't let me upload the changes then. I then get another message telling me you do not wish us to add bus routes.

**Comment by duiveldoder** [comment]
<img width="471" alt="java_45utTKe0vA" src="https://github.com/openstreetmap/operations/assets/15773876/9649b6ad-0024-436b-81f7-336ef8b438e1">
<img width="440" alt="java_zfL9FWRmki" src="https://github.com/openstreetmap/operations/assets/15773876/24a17cfd-d2a7-46f6-afaa-bb34341c7643">

**Comment by duiveldoder** [comment]
I mean common - this is hilarious. 50m width along a track and I'm not allowed to add this bus route with just 50m of data along a track I'm downloading?

**Comment by mmd-osm** [comment]
First of all, your report lacks a GPX example to reproduce the issue. Can you provide a link, ideally one pointing to https://www.openstreetmap.org/traces (or your own GPX uploads on osm.org)?

Are you the person on Telegram who mentioned that download along GPX tracks bypasses Overpass API and still tries to fetch data using the OSM API? Essentially this means, JOSM is ignoring its own settings. You might want to create a bug report for that on https://josm.openstreetmap.de/newticket (or even better, create a bug report in JOSM -> Help -> Report bug)

This is the flag I'm talking about:

![image](https://github.com/openstreetmap/operations/assets/5842757/3e36b2ea-0348-44e2-b90f-19c0b25cf8b2)


> _And yes I've tried using overpass and other means of downloading data - which works - but it won't let me upload the changes then. I then get another message telling me you do not wish us to add bus routes._

Can you be a bit more specific as to what messages you're seeing there? Downloading using Overpass API and uploading again should work without issue. It's also documented on the Wiki https://wiki.openstreetmap.org/wiki/Overpass_API/Sparse_Editing - maybe your query is not ok? community.osm.org might be a better place to discuss this.

**Comment by duiveldoder** [comment]
community.osm.org might be a better place to discuss this.

I think I can discuss the limitations for the next 1.000.000 years but it won't change the fact the limitations are too strict.

But since you by referring to the "talk non-stop 24/7 for endless times" I sense nothing will be done to fix this issue - then I'm closing it and just consider to finish the route I started with and then simply delete all traces that are left.

if Bus routes are unwanted - fine by me - I have enough to spent my time on - no need to wait 4-5 hours just to get a 50m wide area for 300km long bus route finally downloaded to be added properly.

Then medium range bus routes are out of the question for OSM - I'll focus then simply on short distance routes max 50km.

Thank you

**Comment by mmd-osm** [comment]
You're quoting me out of context and implying things I've never said. End of discussion for me.

**Comment by mmd-osm** [comment]
By the way, OP confirmed on Telegram that their Overpass query for JOSM didn't include `out meta;` ...
