### ISSUE TITLE
Faulty RAM in spike-01

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#89]
`LOG: Uncorrectable Machine Check Exception (Board 0, Processor 1, APIC ID 0x00000003, Bank 0x00000005, Status 0xBA000000'00400405, Address 0x00000000'00000000, Misc 0x00000000'00000280)`

@Firefishy do we need to replace this?

**Comment by Firefishy** [comment]
Yes, we should replace it. We have spare compatible RAM from the IC haul. I'll pick some out.

**Comment by zerebubuth** [comment]
Replaced.
