### ISSUE TITLE
Upgrade Amsterdam Juniper switches to latest firmware

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#893]
Upgrade Juniper EX4300 Amsterdam cluster

https://www.juniper.net/documentation/us/en/software/junos/junos-install-upgrade/topics/topic-map/install-software-on-ex.html is the procedure.

Link: https://github.com/openstreetmap/operations/issues/899

**Comment by Firefishy** [comment]
This will need testing and downtime planning. The change is meant to be seamless, but there are reports of the [latest (21.4R3-S3) upgrade not going smoothly.](https://www.linkedin.com/posts/tim-ngo-0058774b_juniper-srx4100-ex4300-activity-7056037114576048128-AeFY/)

Best not to bundle the Amsterdam and the Dublin upgrade in a single issue as they will be performed separately.

**Comment by Firefishy** [comment]
Split this issue into separate Amsterdam and Dublin issues.

**Comment by Firefishy** [comment]
We still need to source the latest stable Juniper EX4300 firmware release.

**Comment by Firefishy** [comment]
I have been able to source the latest stable firmware.

**Comment by Firefishy** [comment]
`jinstall-ex-4300-21.4R3-S5.4-signed.tgz` has now been released.

**Comment by grischard** [comment]
Before upgrading, run `request system storage cleanup` and `rm -rf /var/tmp/.schema-cache`.

**Comment by grischard** [comment]
NSSU: https://www.juniper.net/documentation/us/en/software/junos/high-availability/topics/concept/nssu-ex-series.html and https://www.juniper.net/documentation/us/en/software/junos/high-availability/topics/task/ex-series-software-upgrading-nssu-fixed-virtual-chassis-cli.html

**Comment by Firefishy** [comment]
Test upgrade on spare machine went without issue.

**Comment by Firefishy** [comment]
Commands:
```
request system storage cleanup
request system software nonstop-upgrade /var/tmp/jinstall-ex-4300-21.4R3-S5.4-signed.tgz
```

**Comment by Firefishy** [comment]
nonstop-upgrade required preprovision be enabled. I have now setup preprovision with the device serial numbers and have started the non-stop upgrade. Config changes: https://github.com/openstreetmap/oxidized-configs/commit/14851ccf529da47c300dc32445c8ebc1ff366fff (private repo)

**Comment by Firefishy** [comment]
Upgrade completed successfully.
