### ISSUE TITLE
Inbound transfer of osm.wiki to Gandi

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#894]
A community member has recently registered the domain `osm.wiki`. The person is happy to transfer the domain to OSM management.

- [ ] Unlock the domain for transfer
- [ ] Request and had across EPP transfer code
- [ ] Start transfer with OSM gandi.net account
- [ ] Setup Cloudflare DNS and add to git
- [ ] Wait for transfer to complete

**Comment by Firefishy** [comment]
DNS transfer now allowed in initial 60 days after registration.
Reminder set for 15th August 2023.

**Comment by 1ec5** [comment]
osm.wiki is redirecting to www.openstreetmap.org, whereas it used to redirect to wiki.openstreetmap.org. Would it be possible to redirect it to wiki.openstreetmap.org again?

**Comment by Firefishy** [comment]
The redirect now works. All done.
