### ISSUE TITLE
Disk full on angor

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#895]
The disks on angor have been [full since mid-May](https://prometheus.openstreetmap.org/d/lMxPYkt7k/filesystems?orgId=1&var-instance=angor&var-mountpoint=%2F&viewPanel=2&from=1678119179108&to=1687102728070).

Reserved disk space should also be lowered to, say, 42G with `sudo tune2fs -r $((42 * 1024**3 / 4096)) /dev/sda3`

**Comment by Firefishy** [comment]
Angor being full is a known issue. It is being used as a stepping stone for moving the new South African 12TB of 25cm aerial imagery.

**Comment by Firefishy** [comment]
Blocked by https://github.com/openstreetmap/operations/issues/813

**Comment by Firefishy** [comment]
This was fixed a few weeks back.
