### ISSUE TITLE
Add SVCB DNS record for tile.openstreetmap.org

### ISSUE THREAD

**Issue by bt90** [openstreetmap/operations#898]
This allows clients to directly establish a HTTP/2 or HTTP/3 connection while skipping the usual upgrade chain.

Cloudflare article: https://blog.cloudflare.com/speeding-up-https-and-http-3-negotiation-with-dns/

Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1623126

Chrome: https://chromestatus.com/feature/5485544526053376

To check:

https://dns.google/query?name=tile.openstreetmap.org&rr_type=HTTPS

IETF draft:

https://datatracker.ietf.org/doc/draft-ietf-dnsop-svcb-https/

**Comment by tomhughes** [comment]
It also doesn't look like dnscontrol has support for it yet :-(

**Comment by Firefishy** [comment]
Cloudflare do support SVCB, but yes blocked by dnscontrol support missing.

**Comment by bt90** [comment]
Hmm. Maybe the other way round? You're using fastly with a CNAME. Their DNS could provide the record.

**Comment by Firefishy** [comment]
We point `tile.openstreetmap.org` to a CNAME `dualstack.n.sni.global.fastly.net.`. It will be up to fastly to add HTTPS/SVCB records to the their fastly.net domain.

[I have just added HTTPS/SVCB to some openstreetmap.org domains](https://github.com/openstreetmap/dns/commit/04e97c7154b7d2dea32556a4c6d280758441686c).
