### ISSUE TITLE
Upgrade Dublin Juniper switches to latest firmware

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#899]
Upgrade Juniper EX4300 Dublin cluster.

https://www.juniper.net/documentation/us/en/software/junos/junos-install-upgrade/topics/topic-map/install-software-on-ex.html is the procedure.

Link: https://github.com/openstreetmap/operations/issues/893

**Comment by grischard** [comment]
Before upgrading, run `request system storage cleanup` and `rm -rf /var/tmp/.schema-cache`.

**Comment by grischard** [comment]
Test upgrade successful - config stays the same. Dublin switch ready to be upgraded using NSSU.

**Comment by grischard** [comment]
NSSU: https://www.juniper.net/documentation/us/en/software/junos/high-availability/topics/concept/nssu-ex-series.html and https://www.juniper.net/documentation/us/en/software/junos/high-availability/topics/task/ex-series-software-upgrading-nssu-fixed-virtual-chassis-cli.html

**Comment by Firefishy** [comment]
Commands:
```
request system storage cleanup
request system software nonstop-upgrade /var/tmp/jinstall-ex-4300-21.4R3-S5.4-signed.tgz
```

**Comment by Firefishy** [comment]
nonstop-upgrade required preprovision be enabled. I have now setup preprovision with the device serial numbers and have started the non-stop upgrade.

**Comment by Firefishy** [comment]
Dublin upgrade is done. There were a few 30s outages during the upgrade, but nothing severe enough to stop the upgrade in Amsterdam. We currently do not have non-stop bridging enabled which may have reduced some of the outages a bit.

Config change: https://github.com/openstreetmap/oxidized-configs/commit/90e4e4a1eaaea88f1557bc984b1d05d0f2acd19f (private repo)

**Comment by Firefishy** [comment]
Slices updated.

**Comment by Firefishy** [comment]
For reference the command to update the slices:

```
request system snapshot slice alternate
```
