### ISSUE TITLE
Share burden of dealing with spam users

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#90]
Some people use the OSM platform to put up spam or advertising material which is not appropriate for the platform. Currently, these are reported via various ad-hoc mechanisms to an _administrator_ who can delete the account.

To allow this to happen more effectively, and in more languages, it seems like it would be a good idea to have a wider pool of people able to handle spam. Although perhaps not by deleting the account, but putting it into a "flagged" state where it is either inactive or hidden.

Things to decide:
1. Is this a new permission, or an enlargement of the existing "moderator" role?
2. What permissions does a "spam moderator" need to function effectively? What is the least necessary privilege?
3. To what extent does there need to be oversight? For example, would accounts be flagged as spam for an administrator to delete, or placed in a queue where they'd be deleted automatically after some grace time?

Please discuss.

**Comment by gravitystorm** [comment]
Is this better discussed on the openstreetmap-website tracker? There might be more people there who can comment and/or are familiar with the code and/or willing to implement the changes :-)

In any case, I think 1 for now. Do we soft-delete accounts anyway? Like with a deleted_at timestamp?

**Comment by zerebubuth** [comment]
Yeah, sorry, this ticket is intended for discussion about what we want the behaviour to be, operationally. Once we know what we want, then it's appropriate to open a code ticket for it.

There are "suspended" accounts, which will hide the user's page, where we set the user's `status` to `suspended`. That's the closest we get to "soft-delete", although it appears that doesn't hide the user's diary entries and any other thing that would get deleted if the account were deleted.

I think we want to consider under what conditions we can safely soft-delete an account; the more things foreign-keyed to the user's account, the more we might need to unpick to delete the account. Would it be sensible to limit "spam soft-deletes" to accounts with no edits?

**Comment by tomhughes** [comment]
The time to discuss it would have been a year ago before the code was written... And yes I know I still need to review and merge that branch.

**Comment by zerebubuth** [comment]
Okay - if there's code already existing then that's great. What can we do to help? I assume it needs rebasing against current master? Anything else that can be done to make the review easier?

**Comment by tomhughes** [comment]
Well no PR was ever opened, so the first thing I need to do is to find the code last year's SoC student wrote... I think https://github.com/sbagroy986/openstreetmap-website/tree/moderation_queue is it?

**Comment by zerebubuth** [comment]
Cool. I'll take a look the next chance I get.

**Comment by pnorman** [comment]
I rebased it at a hack weekend and @woodpeck did a bit of work, https://github.com/woodpeck/openstreetmap-website/tree/moderation_rebased is probably a better place to start

**Comment by mmd-osm** [comment]
I'd suggest to close this one, follow up is in https://github.com/openstreetmap/openstreetmap-website/pull/1576

**Comment by pnorman** [comment]
Closing - the moderation branch is merged and further discussion is best had on the osm-website tracker.
