### ISSUE TITLE
Remove unused fibre modules from Amsterdam switches

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#900]
Remove the unused fibre modules from the Juniper switches in Amsterdam

SW1: 1x 1G module (1st port), 1x 10G module (2nd port)
SW2: 1x 1G module (1st port), 1x 10G module (2nd port)

Removed the disconnected patch fibre.

**Comment by Firefishy** [comment]
Removed modules should ideally be returned to London stock.

**Comment by Firefishy** [comment]
@pnorman If possible, please could you give me these when you come to SoTM-EU.

**Comment by pnorman** [comment]
Removed successfully and in my backpack with the cable.

**Comment by Firefishy** [comment]
Modules now in Catford.
