### ISSUE TITLE
Pyrene disposal or donate

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#906]
Pyrene will soon be up for disposal after it has been replaced. It is expected to be replaced in next few months.

Pyrene is on paper owned by OSM.us, they may wish to reclaim it or offer it up for donation to OSGeo who are in the same data centre.

**Comment by Firefishy** [comment]
Note: pyrene has a dead RAID controller battery and it should be replaced. Part Number: 660093-001

**Comment by iandees** [comment]
cc @quincylvania, who is helping with tech stuff for OSM US and might be interested in using this for some of the stuff they're currently running in AWS.

**Comment by Firefishy** [comment]
FYI: We have ordered the replacement machine. Pyrene will likely be ready for disposal ~ 1st Sept 2023.

**Comment by pnorman** [comment]
piasa is now up and running and pyrene should be shut off tomorrow. I'll contact OSM US and ask if they want it back.

**Comment by Firefishy** [comment]
@quincylvania any update from OSM US side? OSGeo (also hosted at OSUOSL) have shown an interest in the machine if it were to become available.

Feel free to discuss via email, slack or other channel if you prefer.

**Comment by tomhughes** [comment]
Decommissioning checklist:

- [ ] Remove Chef config
- [ ] Wipe Disks and install clean OS
- [ ] Remove DNS

**Comment by quincylvania** [comment]
@Firefishy Ubuntu sounds great, thanks!

**Comment by Firefishy** [comment]
Wiped and new base install done. Will hand over details shortly.

**Comment by Firefishy** [comment]
OSUOSL has now been notified of the handover of the server.
Thank you to OpenStreetMap.us for the use of the server for the last few years. Long live Pyrene!

**Comment by quincylvania** [comment]
@Firefishy Thanks for shepherding this through! Excited for the possibilities here 🧑‍🍳
