### ISSUE TITLE
Kernel warnings on Ramoth

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#91]
The disk on Ramoth was getting full with logs:

![image](https://cloud.githubusercontent.com/assets/271360/16951320/671c01a2-4dbc-11e6-8061-7d64ad3ae940.png)

These turned out to be kernel logs, which were frequent repeating warnings [of this form](https://gist.github.com/zerebubuth/db90760a680642dec908c06c9130f488), with the majority (75% of a sample of 30,000 traces) passing through one of `udpv6_sendmsg`, `udp_v6_push_pending_frames` or `udpv6_recv`. The only open IPv6 socket was a UDP socket from PostgreSQL to itself, possibly for the stats collector.

This seems similar to #29 and there are [other](https://brunomgalmeida.wordpress.com/2015/07/23/disable-ipv6-postgres-and-pgbouncer/) [reports](https://www.postgresql.org/message-id/CALXbVnehCf4XX1umL%3DZJ%2BRJ5OO_DQagNiVubt48h0B6oOL2swQ@mail.gmail.com) at large on the internet. Amusingly, [this report](https://ubuntuforums.org/showthread.php?t=2316485) refers back to #29! All that I've seen are using version 3.13.0, which may or may not be diagnostic, as it's the stable 14.04 kernel. I've not seen any reports from 16.04, which might indicate it's fixed there... or just that it's a rare enough bug that no one has (publicly) mentioned it for the latest version yet.

Rebooting cleared the state and the warnings stopped, although it [created other problems](https://github.com/openstreetmap/chef/commit/89e79e81b8da8ec51cf058e4877a749031477d92) because Ramoth wasn't warm any more and couldn't handle full load, leading to [these outages on the 19th](http://stats.pingdom.com/p310g2klasry/435275/2016/07).

The issue seems likely to re-occur. Is it worth considering a backport kernel, or disabling IPv6 as suggested by one report?

**Comment by Firefishy** [comment]
Closing. Doesn't seem to be an issue anymore. Machine has been upgraded to Ubuntu 16.04
