### ISSUE TITLE
Faffy account request

### ISSUE THREAD

**Issue by ted-piotrowski** [openstreetmap/operations#913]
### Name

Ted Piotrowski

### Email address

tppiotrowski gmail com

### OpenStreetMap username

shademap

### Username on the server

tppiotrowski

### Bio

I was referred by Guillaume Rischard

I plan to use the server to generate terrain map tiles using available LiDAR DSM data. 

My current project is to convert [swissSURFACE3D Raster](https://www.swisstopo.admin.ch/en/geodata/height/surface3d-raster.html) dataset to 512x512 .webp terrain tiles to use on my website [shademap.app](https://shademap.app). It takes a week to generate zoom levels 10-16 on my laptop.

I have plans to do similar for data from Liechtenstein, Spain, France and parts of the US.

I plan to potentially commercialize this data via my website but am also happy to give the tiles to OSMF to host and distribute. I will also provide attribution to the OSMF OWG for using this service.

### Public SSH key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtb0lW0hzR4XVsEdWJVYBA2lS8k7KZ65Hwq4G8aH8TAMnUh5z4xbGfSichi0ys44AXjxHulC03t7McccNep9IRsthgyzlMBd0DTnwUGR7bgcdCIWsCxliJrTPDV9z9sCjGekNMAxXrELYOFGmkga9YJ29VZUQmFxOEq8KNWiikR3QntrwY9ULfvChf9yt0ORqGoYsU16kWfaJU77bxdzhUy60QMix0yLAviTe5NX0zbuRD/ATGekWUrEI3kPheaBiYatoUxkgo3yUmFykveQ+sSwLwvJc8cj6W3rr5VeOt9UB+q/r7ddh152BNpW3o5UeX3gTRpToAyHUtHRUTnTTzx+p6IbRwGo/VLrGG7cScDWQchfvbbb31EtPzcEUEUw/2fOQTcCVNKuvLwaRCDLHCZUBn1y7yQlhhIg4bAQrjOqpLM/THYL85/yNRLt+NW7w+CeFYZdSMujGx2fbCA3pC3KN1a1bifJUHvq3s4rLE/d4smcWZ7hvPUYZ5CuRZkUgt6I5LA4n33nS4vPeCnjRc5+BjZvKSW+g0VejlYBg1hOR9aVEb6rSm97Saw3ptwExTBvfIvtkjUkHYb/mGE1c+MknaxyLS9me/IRJMGEXSTO+Qc7JGGrDgYxtC1w+03+VKzgQ+ajuhViwvSvz9uz4id3SomhaiZNTm3n0FQPUSjQ== ted@Teds-MacBook-Pro.local

### Code of Conduct

- [X] I agree to follow the OpenStreetMap policies and codes of conduct, and to use the dev server only for OpenStreetMap-related tasks

**Comment by grischard** [comment]
I hope you mean Luxembourg and not Liechtenstein :p

**Comment by grischard** [comment]
https://lidar-hillshade-2019.openstreetmap.lu is hosted by the OSMF for mappers. If you were interested in helping out to upgrade our imagery infrastructure to use webp and also generated something like https://lidar-hillshade-2019.openstreetmap.lu/  using https://www.swisstopo.admin.ch/en/geodata/height/surface3d.html the OSMF could probably host these tiles for Switzerland.

**Comment by tomhughes** [comment]
Maybe OWG should discuss it before we start making promises...

**Comment by ted-piotrowski** [comment]
After some more thought, I'm going to cancel this request for the time being. I think the type of DSM terrain generation I'm doing is very specific for my project and not of much use to the OSM. If I switch to doing more DEM/hillshade generation I'll reopen this issue.
