### ISSUE TITLE
Fix wordpress user discrepancy between file owner, PHP runtime and wp-cli users 

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#914]
Currently as setup per chef:
* wordpress files are owned by wordpress user
* wp-cli runs as wordpress user
* wordpress PHP fpm runs as www-data

This can cause a permission error when wp-cli wants to modify a file written by PHP fpm (eg: civicrm owned PHP cache files) for plugin activation or similar.

**Comment by Firefishy** [comment]
An fix might be to switch wp-cli to run as www-data.

Alternative wordpress cookbook could manage another user for runtime tasks and a different user for owning source code.

**Comment by tomhughes** [comment]
The `wordpress` user exists just to own (most of) the files while the directory that was being written to here is owned by `www-data` instead precisely to allow it to be written to by running wordpress code.

As `wp-cli` is essentially standing in for running something from the web interface it's probably right to run it with the same permissions as the web interface, ie as `www-data`.
