### ISSUE TITLE
Need to free up space on planet server

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#915]
The `/store` partition on norbert filled up today while publishing the new planet - fortunately the planet dump had completed so nothing was lost but replication stopped for a few hours.

I removed the oldest database dump to make some space which allowed replication to continue and then completed publication of the new planet files manually.

The [last months history](https://prometheus.openstreetmap.org/d/lMxPYkt7k/filesystems?orgId=1&refresh=1m&var-instance=norbert&var-mountpoint=All&from=now-30d&to=now&viewPanel=11) of the the space on the partition looks like:

![image](https://github.com/openstreetmap/operations/assets/147741/b88f1602-8c4f-44c5-bd2d-a9b7a07ce632)

We need to expire some old planets or something to make sure we don't have a repeat next week.

**Comment by Firefishy** [comment]
I have taken an axe to the old planet files. Full History `.osm.bz2` and the regular `.osm.bz2` planet files. I have left the `.torrent` files in place. I have also changed the filesystem reserve from 5% to 1%. 18.2 TB now available.

All the original planet files are backed up on S3. Currently 70.6 TB backed up.

<img width="1678" alt="Screenshot 2023-07-30 at 01 08 33" src="https://github.com/openstreetmap/operations/assets/248188/2baa250b-b002-4c1f-8a82-2eee36d2e90f">

**Comment by Firefishy** [comment]
Should now be OK for a year or so. We should migrated to new long term hosting service before then.
