### ISSUE TITLE
Replace APC to APC "ethernet" link cable with CAT5 cable.

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#916]
The ethernet cable which links left and right APC @ AMS should be replaced.

The APC use the ethernet cables as a special serial bus (not ethernet) to allow managing the remote APC. Each end has terminators. APC documentation: https://www.apc.com/ca/en/faqs/FA164436/

Very occasionally the link drops and the oxidized then logs the missing ini config of the remote APC.

I have found a short CAT5 cable seems to work best. A perfect CAT7 ethernet cable seems to increase the frequency of the drop-outs.

**Comment by Firefishy** [comment]
Example of a link outage during an oxidized config sync: https://github.com/openstreetmap/oxidized-configs/commit/25c944a8a2b7bd3f2129cdb031b938834f0e4914 (private repo)

**Comment by pnorman** [comment]
The APC link does not work. Which cable is the one that needs replacement?

**Comment by Firefishy** [comment]
It is the cable that goes from APC direct to other APC. Ports labelled "In" and "out". The port positions do not need changing.

**Comment by pnorman** [comment]
Cable changed, labels moved.
