### ISSUE TITLE
Buy new general-purpose machines for DB4

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#917]
From budget:
> We use general-purpose servers for most of our services. When they get too old they require replacement. We have standardized on used HP DL360s as they are reliable, good value, and well supported on the used market. In the last year upgrades to what is available used have allowed us to host more services like Nominatim on general-purpose servers.
> 
> Item | Operational cost | Capital cost
> -- | -- | --
> General-purpose servers | € 0 | 2x € 5 500

The servers in question are gorwen and jakelong, the last of the HP DL360e Gen8 used for our services.

**Comment by pnorman** [comment]
grindtooth, ridley, and draco are also G6 and G7 machines in UCL that should be replaced.

**Comment by pnorman** [comment]
Plan is to go ahead with the purchase. The servers will be the same as the last batch of four general-purpose machines we got in AM6, but with PSU 865408-B21 500W

**Comment by pnorman** [comment]
Pro-forma requested, will proceed with ordering.

**Comment by pnorman** [comment]
Pro-forma sent to accounts for payment.

**Comment by pnorman** [comment]
The wrong amount was sent as payment. They've started the build, but we need to send the remainder (VAT) before it's shipped.

**Comment by pnorman** [comment]
@Firefishy how close are we to switching gorwen and jakelong to the new servers?

**Comment by pnorman** [comment]
Adding a mention for searching later, these machines are running overpass and discourse.

**Comment by Firefishy** [comment]
Both machines are now in use. grisu: Overpass and fume: Discourse.
