### ISSUE TITLE
Replace pyrene with piasa

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#918]
Machine is on order from serverschmiede with 2x Xeon 6148, 384GB RAM, 2x7.68TB NVMe SSDs. No ETA on arrival as it hasn't yet been shipped.

* [x] Order new machine
* [x] Get tracking number from vendor
* [x] Attempt to pay import fees directly to shipper
* [x] Inform OSUOSL of tracking number
* [x] Rack new machine
* [x] Set up new machine and bring into CDN

Follow-up: #906

**Comment by pnorman** [comment]
Server is with UPS, and "in a secure facility pending clearance or resolution" so it sounds like it's in the US and awaiting customs clearance.

The new server is named piasa, which is a North American dragon from Cahokia on the Mississippi.

**Comment by Firefishy** [comment]
The machine is still held. I have reached out again to shipper, but not heard back from them.

**Comment by Firefishy** [comment]
We have been able to make contact with UPS the courier. I have supplied what details I can, OSUOSL also have a broker which may take over if needed.

**Comment by Firefishy** [comment]
Server has been released and is expected to be delivered today.

**Comment by Firefishy** [comment]
Server has delivered and will be racked likely next week.

**Comment by Firefishy** [comment]
Server has been racked and we are waiting for working iLO credentials to install OS and setup the machine.

**Comment by Firefishy** [comment]
System is up and configured, chef is installed. Render DB import still pending.
