### ISSUE TITLE
Migrate new donate staging to production

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#922]
This is a ticket with a few moving parts.

Join.osmfoundation.org will also be used for donations from now on. The work is being done over at join-staging.osmfoundation.org

Because 'join' makes no sense for donations and 'donate' no sense for memberships and 'support' seems like a place to get Nominatim questions answered, the name of the site should be changed to 'supporting.openstreetmap.org'.

Non-exhaustive list of stuff to transfer:

- theme
- child theme
- image and video assets
- plugin?
- page content
- civicrm donate form footer

We must also:

- redirect join.osmf.org and donate.osm.org to supporting.osm.org.
- change the site title (it currently says "Membership - OSM Foundation")
- set a preview image for sharing on socials

Date: the new website should be ready on 9 August, for OSM's birthday.

**Comment by tomhughes** [comment]
So is this intended to replace both join.openstreetmap.org and donate.openstreetmap.org?

**Comment by grischard** [comment]
@tomhughes yes.

**Comment by seav** [comment]
Not sure if this is the correct place to raise a problem but since it's related to this issue, the new donate page is no longer able to show the public list of donors despite having a checkbox saying "List my name on the public donor list".

**Comment by grischard** [comment]
Yeah, the civicrm donor report isn't done yet. Launching for the birthday seemed more important than being perfect.

**Comment by grischard** [comment]
Actually the ops part of this can probably be closed.
