### ISSUE TITLE
Check for issues with fibre patch for ge-0/2/2

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#924]
The signal receive strength for ge-0/2/2 dropped off on or before 2 August 2023.

On next site visit check patch, re-seat or replace patch if justified.

The signal receive strength is now actively monitoring with alerting.

If reseat or patch does not fix the issue, then potentially raise investigation with Equinix.

**Comment by Firefishy** [comment]
"In Amsterdam, we're seeing low light levels on one of your ports. It may be an issue with your optic or cross-connect at Equinix AM7. You'll need to ask for Equinix's help to check that.  The cross-connect ID is 22519284-Z." - HE engineer

**Comment by pnorman** [comment]
The link for checking the power when I'm there is https://prometheus.openstreetmap.org/d/af9a9579-10b4-4e23-a720-0f3fbae5219b/switch-monitoring?orgId=1&refresh=5m&from=now-1h&to=now

Do we need to do anything before unplugging to reseat, or will everything go to the other link without interruption?

**Comment by Firefishy** [comment]
I have ordered a spare 1G fibre module in the event that we'd like to replace the fibre module.

**Comment by Firefishy** [comment]
Steps for on-site:

0. Notify Ops team of start of work...
1. Confirm which switch has port ge-0/2/2 (Lower "00" Switch, 3rd fibre port, yellow cable. See photo below)
2. Check if fibre cable is severely bent or over extended anywhere.
3. Check that both ends of the fibre patch cable a securely connected.
4. [See if any improvement on receive strength via prometheus](https://prometheus.openstreetmap.org/d/af9a9579-10b4-4e23-a720-0f3fbae5219b/switch-monitoring?orgId=1&refresh=5m&from=now-30m&to=now).
5. If the signal strength does recover proceed with following steps...
6. Confirm ok routing of an existing spare patch cable. There should be 2x spare blue shielded fibre patch cables.
7. Using fibre clean pen clean both ends of the existing spare patch cable. [How to video is available here](https://www.fs.com/uk/products/39721.html).
8. Ensure existing spare patch cable pairs (B/A) are as per existing cable. It is unlikely, but the pairs may need to be unclipped and swapped left/right.
9. Unplug both ends (rack top / at switch fibre module) of the existing yellow patch cable.
10. Confirm the internet connection uplink is still up on the remaining cable.
11. Using fibre clean pen clean switch fibre module TX/RX ports. Clean rack top patch panel TX/RX ports.
12. Connect / Patch the blue replacement patch cable both ends (top and switch) and confirm the switch port connection LEDs illuminate. If the LEDs do not illuminate after 15 seconds, the pairs may need unclipping and swapping.
13. [Confirm signal strength via via prometheus](https://prometheus.openstreetmap.org/d/af9a9579-10b4-4e23-a720-0f3fbae5219b/switch-monitoring?orgId=1&refresh=5m&from=now-30m&to=now). If the signal strength does not recover, proceed with following steps to replace the fibre module.
14. Clean the replacement fibre module ports using the cleaning pen.
15. Disconnect the fibre patch cable at switch. Clean end again if desired
16. Pull down the fibre module latch which releases the fibre module from the switch. Do not pull the module out until the module is unlatched.
17. Confirm no disruption to internet connection.
18. Install the replacement fibre module
19. Re-connect blue fibre patch cable, confirm LEDs.
20. [Confirm signal strength via via prometheus](https://prometheus.openstreetmap.org/d/af9a9579-10b4-4e23-a720-0f3fbae5219b/switch-monitoring?orgId=1&refresh=5m&from=now-30m&to=now). If the signal strength does not improve the fault it not local and will require investigation by Equinix.

![SW1 link up (1)](https://github.com/openstreetmap/operations/assets/248188/ce6d7cd8-718a-4699-a1e5-15883f2507f7)

**Comment by pnorman** [comment]
Cable recovered after wiggling it and checking ends were fully seated. Decided not to switch to blue cable.
