### ISSUE TITLE
Discourse is reporting a need to migrate a plugin

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#927]
There is a new alert on discourse, presumably since the 3.1 update:

> The discourse-canned-replies plugin is no longer supported. Please [migrate to the new discourse-templates plugin](https://meta.discourse.org/t/discourse-templates/229250) and uninstall discourse-canned-replies.

**Comment by Firefishy** [comment]
The plugin can be removed from web_only.yml It is not used.

**Comment by Firefishy** [comment]
plugin removed in https://github.com/openstreetmap/chef/commit/9d1da497d442b16de5ab68a9cf74f832059734e7
