### ISSUE TITLE
Why does 25% of my donation go to Amazon

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap/operations#928]
https://community.openstreetmap.org/t/why-does-25-of-my-donation-go-to-amazon/102475

Please provide your feedback.

@pnorman @Firefishy

**Comment by Firefishy** [comment]
I am on holiday at the moment. Back later this week.

0% $0 has spent on AWS for the last 6 months. Hosting planet data will be $0/month.

Bit more detail here https://community.openstreetmap.org/t/why-does-25-of-my-donation-go-to-amazon/102475/4

**Comment by pnorman** [comment]
3% of the OSMF budget goes to AWS, and the actual spend is likely to be less.

**Comment by tomhughes** [comment]
It's closer to a year since we paid anything I think...

**Comment by Zaczero** [comment]
> Where on earth did you get that idea exactly?
> 
> I can see @Firefishy has already explained that we haven't paid a penny to them recently, and I don't believe it has ever been anywhere near 25% of the operations budget let alone of the entire OSMF budget.
> 
> The planet hosting in particular is not something that is going to involve us paying for the hosting.

I have hyperlinked all my findings.

**Comment by Zaczero** [comment]
> It's closer to a year since we paid anything I think...

I am working on publicly available information. I can't know what's exactly going on in OSMF. What I found is really concerning to me. If you know it's inaccurate please justify.

**Comment by Firefishy** [comment]
> > It's closer to a year since we paid anything I think...
> 
> I am working on publicly available information. I can't know what's exactly going on in OSMF. What I found is really concerning to me. If you know it's inaccurate please justify and provide necessary evidence (I did provide mine).

Our fortnightly meetings are open for constructive discussion. Else feel free to ask us if you have any specific questions. I am happy to publish an AWS usage/expense report or similar if it is needed.

**Comment by Zaczero** [comment]
> Can you edit the title? You already got info necessary to know that it is inaccurate even if actual spending will reach top of expected spending.

I don't tend to update closed issues.

**Comment by Zaczero** [comment]
> > > It's closer to a year since we paid anything I think...
> > 
> > 
> > I am working on publicly available information. I can't know what's exactly going on in OSMF. What I found is really concerning to me. If you know it's inaccurate please justify and provide necessary evidence (I did provide mine).
> 
> Our fortnightly meetings are open for constructive discussion. Else feel free to ask us if you have any specific questions. I am happy to publish an AWS usage/expense report or similar if it is needed.

> Our fortnightly meetings are open for constructive discussion

You clearly [[1]](https://operations.osmfoundation.org/meetings/) [[2]](https://operations.osmfoundation.org/reports/) don't actively meet for 'open and constructive' discussion.

> I am happy to publish an AWS usage/expense report or similar if it is needed.

Please provide as much detail about AWS usage/expenses as possible. Years 2022 and 2023. Costs but also how much data is stored in S3 and how much is being transferred. I also want to know what are the terms for "free" S3 storage you have mentioned on the forum.

**Comment by Firefishy** [comment]
Please keep good faith. With the exception of me (15 years volunteer, but 1 year now fulltime) the Ops team are all volunteers. The minutes are taken by Dorethea who is supported by OSMF. The minutes can lag. If you think we should improve anything, suggest that, without being accusative. 

We regularly have a video call every 2nd Thursday European time evening. Email me or Dorothea if you would like to join. We plan our calls by agenda, so best to observe and then raise an agenda item after for the next meeting.

We don't pour money down any wells, we run an extremely tight ship. All hardware is very good value. Our usage of cloud is conservative and use is justified.

More when I am back from holiday on Wednesday.

**Comment by dorotheakazazi** [comment]
> Email me or Dorothea

To join the OPS meetings you can email me at

 my username here and then add @ osmfoundation.org

**Comment by Zaczero** [comment]
> Please keep good faith. With the exception of me (15 years volunteer, but 1 year now fulltime) the Ops team are all volunteers. The minutes are taken by Dorethea who is supported by OSMF. The minutes can lag. If you think we should improve anything, suggest that, without being accusative.
> 
> We regularly have a video call every 2nd Thursday European time evening. Email me or Dorothea if you would like to join. We plan our calls by agenda, so best to observe and then raise an agenda item after for the next meeting.
> 
> We don't pour money down any wells, we run an extremely tight ship. All hardware is very good value. Our usage of cloud is conservative and use is justified.
> 
> More when I am back from holiday on Wednesday.

I really want, but when I read this https://community.openstreetmap.org/t/why-does-osmf-spend-25-000-on-amazon/102475/25 and none of my concerns are actually addressed, I simply can't, sorry.
