### ISSUE TITLE
AWS billing IAM permissions

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#929]
The AWS console is reporting the message

> Our records indicate that you have missed the July 06, 2023 cutoff date to update the IAM actions for AWS Billing, Cost Management, and Account consoles. The following IAM actions have reached the end of standard support and are replaced with granular IAM actions: aws-portal:ViewBilling, aws-portal:ModifyBilling, aws-portal:ViewAccount, aws-portal:ModifyAccount, aws-portal:ViewPaymentMethods, aws-portal:ModifyPaymentMethods, aws-portal:ViewUsage, purchase-orders:ViewPurchaseOrders, and purchase-orders:ModifyPurchaseOrders.
> 
> We are granting a final extension until December 11, 2023. Before the extended deadline, please [update your policies](https://console.aws.amazon.com/poliden/home) or contact your access administrator to complete your action. You can also use the [Bulk Policy Migrator](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/migrate-iam-permissions.html) to mass update polices from your Payer account (if using AWS Organizations) or use the [old to granular action mapping guide](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/migrate-granularaccess-iam-mapping-reference.html) to confirm the granular IAM actions which need to be added. For more information, please visit the [blog](https://aws.amazon.com/blogs/aws-cloud-financial-management/changes-to-aws-billing-cost-management-and-account-consoles-permissions/).

**Comment by Firefishy** [comment]
Only the treasurer account is affected. Non critical.

**Comment by Firefishy** [comment]
Billing permissions have been corrected.
