### ISSUE TITLE
Retire thinkup.openstreetmap.org

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#93]
It looks like [thinkup.openstreetmap.org](http://thinkup.openstreetmap.org) has been unmainted and possibly unnoticed for years. The company behind the hosted version has shut their service down this month. While I'm not sure that it affects our self-instance directly, I imagine nobody is going to put any effort into getting our instance working again.

**Comment by harry-wood** [comment]
@Jonobennett looked into it initially for CWG and we used it a little bit when it was first installed. I think we were hoping it'd bring in Google+ too and be a useful unified tracker of lots of different things. Don't think anyone used it at all recently.

**Comment by tomhughes** [comment]
This has now been retired.
