### ISSUE TITLE
Rename openstreetmap-fastly-processed-logs AWS S3 bucket

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#932]
This bucket is not for processed logs, but used as an Athena workspace which saves query results, temp tables, etc. Its name should reflect the real usage.

**Comment by Firefishy** [comment]
S3 does not have the ability to rename a bucket. Normal method is create a new bucket and sync contents across.

**Comment by pnorman** [comment]
Yes - that's in effect a rename. The actual steps are create the new bucket, point Athena workspace at the bucket and delete the old bucket. No need to keep the contents.

**Comment by Firefishy** [comment]
Let me know what you'd like me to do here, else close if no action required.
