### ISSUE TITLE
Setup Cloudwatch for S3 for shipping metrics to Prometheus

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#934]
We should have a dashboard for S3 usage, and S3 graphs should be added to other service dashboards where relevant.

At a minimum, we want
- BucketSizeBytes
- NumberOfObjects
- AllRequests
- BytesDownloaded
- 4xxErrors
- 5xxErrors

There seem to be two distinct ways to get S3 metrics to prometheus

## Ingesting CloudWatch metrics into Prometheus
[yet-another-cloudwatch-exporter](https://github.com/nerdswords/yet-another-cloudwatch-exporter) exports AWS CloudWatch to Prometheus. https://promcat.io/apps/aws-s3 seems a reasonable setup. It looks like it's not an exporter, but a setup for yet-another-cloudwatch-exporter.

## Displaying CloudWatch in Grafana
CloudWatch [can be added](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/) as a data source for Grafana. This seems like a better route, but some questions are
- can we mix prometheus and cloudwatch sources on a dashboard page
- how do we monitor CW costs

**Comment by tomhughes** [comment]
There's also an [official cloudwatch exporter](https://github.com/prometheus/cloudwatch_exporter) though bizarrely it's written in Java for some reason so the go one would probably be preferable unless there's a good reason to use something else.

You can mix sources on a dashboard - each visualisation can only use one source but different visualisations can use different sources. That said the idea of a dashboard that directly triggers AWS costs makes me very nervous!

**Comment by Firefishy** [comment]
[yet-another-cloudwatch-exporter](https://github.com/nerdswords/yet-another-cloudwatch-exporter) looks reasonable to me. It would require me setting up Cloudwatch properly first and creating the correct IAM + permissions for access.

Cloudwatch can if setup very badly be surprisingly expensive.

**Comment by Firefishy** [comment]
Hope you don't mind, I have hijacked the title to better fit the requirements.

**Comment by Firefishy** [comment]
I have created the IAM user, credentials and specific roles to allow for this:

```
arn:aws:iam::173189593406:role/osm-cloudwatch-export-role (main) Regions: eu-west-1, eu-west-2
arn:aws:iam::683740446523:role/osm-cloudwatch-export-role (render) Regions: us-east-2
arn:aws:iam::630658470130:role/osm-cloudwatch-export-role (planet) Regions: eu-central-1, us-west-2
arn:aws:iam::674083635870:role/osm-cloudwatch-export-role (backup) Regions: eu-north-1
```

**Comment by Firefishy** [comment]
I think this is now complete. Preliminary dashboard https://prometheus.openstreetmap.org/d/c6fba6cd-e8f0-4c3e-8a62-7eafbf92cd71/amazon-s3?orgId=1&refresh=5m (URL may change later)
