### ISSUE TITLE
supporting.openstreetmap.org used Google Cloud Fonts

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#936]
supporting.openstreetmap.org used Google Cloud Fonts. The fonts should be bundled in the theme.

Link: #925

**Comment by grischard** [comment]
https://themeshaper.com/2022/11/28/how-to-add-typographic-fonts-to-wordpress-block-themes/

**Comment by grischard** [comment]
Let's use [OMGF | Host Google Fonts Locally](https://wordpress.org/plugins/host-webfonts-local/)

**Comment by grischard** [comment]
Installed plugin in https://github.com/openstreetmap/chef/commit/8ee7a7b1bedbd7772b663fcd9d5507c8cd8d578b
