### ISSUE TITLE
Add cost_center tags to AWS Athena

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#937]
AWS Athena resources / jobs should have a tag added eg: `cost_center=fastly-athena` or similar to identify the billing source for AWS billing. The same tag key=value can be added across multiple services used for the same purpose.

https://docs.aws.amazon.com/athena/latest/ug/tags.html

Existing AWS tags for logs:
* `cost_center=fastly-logs`
* `cost_center=fastly-processed-logs`

**Comment by pnorman** [comment]
shouldn't the cost center be the standard tile layer?

**Comment by Firefishy** [comment]
> shouldn't the cost center be the standard tile layer?

Depends how granularly we want to segment the billing detail. At the moment I've broken it down quite granularly.

**Comment by pnorman** [comment]
we presumably want to match it up with cost centers in xero?

**Comment by Firefishy** [comment]
Example from AWS Cost Explorer using the `cost_centre` billing tag as the group by dimension.

**NOTE: The amounts showing are BEFORE AWS credits are included. OSM does not pay anywhere near the $ values from this screenshot.**

<img width="2286" alt="Screenshot 2023-08-24 at 17 35 11" src="https://github.com/openstreetmap/operations/assets/248188/5f925858-f8c7-41ad-96f9-7aa0725f8fd9">

**Comment by pnorman** [comment]
neither fastly-logs nor fastly-processed logs makes sense here, so I'm going with standard-layer-logs and have added it to the Athena workgroup

We use fastly for things other than the standard tile layer and should be logging them, and we can't split logs and processed logs since the jobs that turn one into the other are both.

**Comment by Firefishy** [comment]
Looks good. There is still a small amount of untagged costs eg: `EU-DataScannedInTB` but can see the new tag live.
