### ISSUE TITLE
Decommision grindtooth

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#938]
Decommission grindtooth at UCL Slough.

- [x] Remove Chef config
- [x] Wipe Disks
- [x] Remove DNS
- [x] De-rack
- [x] Disposed

**Comment by Firefishy** [comment]
Started the erase of the data on the 8 disks in the machine. 6 in array, 2 unassigned.

**Comment by Firefishy** [comment]
Erase done.

**Comment by grischard** [comment]
Blocked by #1060

**Comment by Firefishy** [comment]
Server has gone for WEEE recycling and is waiting to be collected.
