### ISSUE TITLE
Opening a local OSM API on my iPhone remotely via WiFi/HTML when no cellular or internet available.

### ISSUE THREAD

**Issue by paulw517** [openstreetmap/operations#939]
I am working on a project to share GPS coordinates to visually observe a friends position is visible on my iPhone.  I have a pair of LoRa radios equipped with GPS receivers and an ESP32 micro that share our current position in the forest where there is no access to cellular or internet.  I would like to pass my friend's received coordinates vIa WiFi to a local OSM API on my iPhone to display our current positions.  I have an Arduino sketch that does display the received coordinates, however the OSM API must be initially opened via HTML script via access to the internet or cellular.

  <link rel = "stylesheet" href = "http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css"/>
  <script src = "http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>

How can I create a script that would open the OSM API using HTML script in an off line environment?

**Comment by tomhughes** [comment]
This an issue track for the OpenStreetMAp operations team to use to manage the OpenStreetMap service, not a help forum for the general public.

Please ask your question in a more appropriate forum like https://community.openstreetmap.org/help although to be honest it doesn't really sound like your question is really very OSM related so a general programming forum like an appropriate StackExchange site would probably work just as well at least for everything other this mysterious "OSM API" that you seem to want to run on a phone.

**Comment by paulw517** [comment]
Hi Tom, my reference to an OSM API was to OpenStreetMap application installed on my iPhone. I need to initialize remotely via WiFi with HTML scripts instead of a actual finger touch method on the icon.  This project is to function off line, no cellular service or internet connectivity as the sample script attached was the method that I initially found.
Thank you for your response,
Paul


Sent from the all new AOL app for iOS


On Thursday, August 24, 2023, 4:23 PM, Tom Hughes ***@***.***> wrote:




This an issue track for the OpenStreetMAp operations team to use to manage the OpenStreetMap service, not a help forum for the general public.

Please ask your question in a more appropriate forum like https://community.openstreetmap.org/help although to be honest it doesn't really sound like your question is really very OSM related so a general programming forum like an appropriate StackExchange site would probably work just as well at least for everything other this mysterious "OSM API" that you seem to want to run on a phone.

**Comment by tomhughes** [comment]
The thing is there is no "OpenStreetMap Application" for an iPhone. We do not produce any mobile apps so whatever you have it was not created by us and we can't help you with it.

Please, go and ask for help in the forum I mentioned - maybe somebody there will be able to help you identify the app and how to get help with it.

I repeat that this is not the correct forum for this conversation and we are not able to help you.

**Comment by paulw517** [comment]
Hello Tom, I get it now. the app I have installed on my iPhone is OsmAnd Maps.
Thank you,
Paul


Sent from the all new AOL app for iOS


On Thursday, August 24, 2023, 6:51 PM, Tom Hughes ***@***.***> wrote:




The thing is there is no "OpenStreetMap Application" for an iPhone. We do not produce any mobile apps so whatever you have it was not created by us and we can't help you with it.

Please, go and ask for help in the forum I mentioned - maybe somebody there will be able to help you identify the app and how to get help with it.

I repeat that this is not the correct forum for this conversation and we are not able to help you.
