### ISSUE TITLE
Regularly reindex apidb tables

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#942]
When [investigating apidb database growth](https://github.com/openstreetmap/operations/issues/931#issuecomment-1684856811) we found that the indexes bloat by about 200GB/year, with the bloat focused on high churn indexes.

It would be worth reindexing all tables on a regular schedule to improve performance and reduce disk space usage.

I recommend reindexing monthly
1. all the non-geodata tables, in particular users and oauth-related tables. These tables are either small and cheap to reindex or subject to high churn
2. changesets, which are subject to high churn and high bloat
3. notes, which are subject to high churn with the visibility changes
4. current_relation_members, which are subject to high churn and bloat

I recommend reindexing **everything** annually.

Adjusting the index and table fillfactors for the high-churn tables might be worth it, but I don't know how to derive good values for those. [pg_repack](https://reorg.github.io/pg_repack/) is another option, but there's been concern about running it in production.

**Comment by tomhughes** [comment]
I've done a test run of the suggested monthly reindex and it took about an hour and fifteen minutes so shouldn't be a problem.

Interestingly the changesets table was far and away the slowest at about 45 minutes - far more than current_relation_members.

**Comment by tomhughes** [comment]
I've implemented the monthly reindex in https://github.com/openstreetmap/chef/commit/58368b10fb37cfcd56738324f90942a8fd8e3793 to run at 2am on the first Sunday of every month.

I haven't includes any GPS related tables, but maybe we should do `gpx_files` and `gpx_file_tags` and just leave the points table for the annual reindex?

I'm not sure at the moment whether to try and automate the annual one...

**Comment by tomhughes** [comment]
Those two tables only take about 30s total to reindex so I've added them to the monthly rebuild.

**Comment by pnorman** [comment]
> I'm not sure at the moment whether to try and automate the annual one...

I'm in favour of automating it, because otherwise we'll forget. If we automate it and it breaks, at least we get some notice of it.
