### ISSUE TITLE
Broken (possibly hacked) object names on tiles

### ISSUE THREAD

**Issue by alexerisov** [openstreetmap/operations#943]
Hi, I faced with issue with address/objects layer. Tiles from default server (https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png) are broken. There are additional political sentences in Russian regions. Try to zoom in Moscow city and check some streets, parks.

**Comment by tomhughes** [comment]
This is not an operational matter - it is being dealt by the Data Working Group in the normal way for any data issues.

**Comment by Firefishy** [comment]
We are aware of the vandalism and there are multiple teams to fix the issues.

Normally the underlying data is corrected fairly quickly and the rendered PNG map tiles will update once cache has expired. https://wiki.openstreetmap.org/wiki/Browser_cache

Best to follow up on the community forum
https://community.openstreetmap.org/t/horrors-are-written-on-the-maps-of-russia/102983

**Comment by Firefishy** [comment]
I am closing this ticket as the community forum is the best place for any action.
