### ISSUE TITLE
Failed PSU in karm

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#944]
There is a PSU failure being reported by karm - from `ipmitool-sensors`:

```
4627 | PS1 Status      | Power Supply      | N/A        | N/A   | 'Presence detected'
4694 | PS2 Status      | Power Supply      | N/A        | N/A   | 'Presence detected' 'Power Supply Failure detected'
```

**Comment by tomhughes** [comment]
PSUs are 1600W Supermicro [PWS-1K62A-1R](https://store.supermicro.com/1600w-1u-pws-1k62a-1r.html)

**Comment by pnorman** [comment]
The failure happened when the power briefly went out, so the supply was probably on the edge of failing for some time. A reboot didn't clear the failure.

Plan is to replace with 2x 1kW supermicro supplies for better efficiency, it should be worth it over the remainder of the lifetime of the machine.

**Comment by Firefishy** [comment]
2x 1000W replacement PSUs ordered.

**Comment by Firefishy** [comment]
Replacement PSUs have arrived.

**Comment by pnorman** [comment]
Power supplies should be mailed to be there on Nov 8th. The 9th is the planned date.

**Comment by Firefishy** [comment]
@pnorman Please can you book a site visit via the Equinix portal. I will then link the inbound to your visit ticket.

**Comment by Firefishy** [comment]
PSU have been posted. The server should be powered down when installing the new PSUs. Both PSUs should be replaced at the same time.

**Comment by pnorman** [comment]
Replaced. Sending broken PSU to ewaste. Good PSU on shelf.
