### ISSUE TITLE
Adjust retention policy on standard tile layer log-related buckets

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#945]
|Bucket | Prefix| Retention policy | Current retention policy | Estimated size | Reason|
|---|---|---|---|---|---|
`openstreetmap-fastly-logs` | `/` | 14d | 30d | 2.5TB | I've never needed to query logs more than a couple of days old, and this will cut the bucket size in half
`openstreetmap-tile-aggregated-logs` | `/fastly_success_logs/` | 60d | None | 4.4TB | These are the most useful logs for detailed analysis, so I want enough history to catch when something started
`openstreetmap-tile-aggregated-logs` | `/fastly_location_logs/`, `/fastly_minimised_logs/` | None | None | 0.75 TB/month | These are intended for retrospective analysis, year/year trends, presentations, etc

ref #698

The access pattern for all the objects is they will be accessed 1-3 times on the day they are written, some will be partially accessed a few times within the first few days, and then they might not be accessed at all or will be accessed potentially months later.

**Comment by Firefishy** [comment]
Implemented in: https://github.com/openstreetmap/terraform-aws/commit/9fc795556d3b8576f1f11c340b09f56ffe1bf8af

I did not need to add a rule for `openstreetmap-tile-aggregated-logs/fastly_location_logs/` as there is no retention policy required for `none`

**Comment by Firefishy** [comment]
We should also add lifecycle rules to manage [S3 storage class](https://aws.amazon.com/s3/storage-classes/).

**Comment by Firefishy** [comment]
Added in https://github.com/openstreetmap/terraform-aws/commit/bc0b395aa60016fe79b10cfaceec36c778fc0322
