### ISSUE TITLE
Standard layer tiles not shown in Firefox - tile.openstreetmap.org gives HTTP 418 "I'm a teapot"

### ISSUE THREAD

**Issue by Leloup79** [openstreetmap/operations#946]
### URL

https://www.openstreetmap.org

### How to reproduce the issue?

- When opening https://www.openstreetmap.org using the standard layer, the tiles are not shown (all grey)
- This only occurs in Firefox (currently 117.0 (64-Bit)) since a couple of days, works fine in e.g. Edge on same PC/network
- Occurs also in Firefox safe mode without any extensions active
- Looking into the console it shows HTTP 418 responses from tile.openstreetmap.org
- Opening a tile URL directly shows the tile (e.g. https://tile.openstreetmap.org/14/8616/5706.png) correctly

I am sorry if this is not the correct place to raise this issue, but I could not find another suitable place during my search.

Thanks and best regards!
Wolfram

### Screenshot(s) or anything else?

![grafik](https://github.com/openstreetmap/openstreetmap-website/assets/57175644/bf111bbc-9214-49f2-a360-d7f90df18933)

![grafik](https://github.com/openstreetmap/openstreetmap-website/assets/57175644/30fa641a-36b4-47a7-a569-e842dd533b86)

**Comment by Firefishy** [comment]
I have moved the ticket to the correct repo.

**Comment by Firefishy** [comment]
The `HTTP 418 Error` is due to fake browser / referrer system triggering.

We have tile scrapers which fake browser and referrer headers which overload our systems.

**Comment by tomhughes** [comment]
It's sending `Accept: */*` which is not expected for Firefox per https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values.

**Comment by tomhughes** [comment]
Firefox 116 sends `Accept: image/avif,image/webp,*/*` as documented and that is what we're expecting from genuine Firefox user agents.

**Comment by tomhughes** [comment]
I've upgraded to 117 now and I'm still seeing the correct accept and working tiles.

**Comment by tomhughes** [comment]
@Leloup79 have you got a custom value for `image.http.accept` in your firefox configuration or something?

**Comment by Firefishy** [comment]
Alternatively it could also be `image.webp.enabled = false` & `image.avif.enabled = false`. You can check in `about:config` URL.

**Comment by Leloup79** [comment]
> I have moved the ticket to the correct repo.
Thank you for moving the issue to the correct repo!

> Alternatively it could also be `image.webp.enabled = false` & `image.avif.enabled = false`. You can check in `about:config` URL.
image.webp.enabled = true
image.avif.enabled = true

> @Leloup79 have you got a custom value for `image.http.accept` in your firefox configuration or something?
For some reason it was indeed */*. After resetting to default (which is actually empty), tiles are loading again.

Thank you very much for pointing at this. I do not recall having set the value knowingly, but well.

Thank you all, I am closing this issue.

**Comment by Firefishy** [comment]
@pnorman heads up to a false positive.
