### ISSUE TITLE
Publish newly generated planet data to S3

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#958]
As part of #678 we need to arrange to published newly generated files in various categories to S3 as they are generated.

Some cases may be best done by an explicit copy and some by resyncing a tree but the list of things that need to be handled are:

- [x] Planet dumps
  - Changesets
  - Discussions
  - Planet (bz2 and pbf)
  - Full history planet (bz2 and pbf)
- [x] Minutely replication diffs
- [x] Hourly replication diffs
- [x] Daily replication diffs
- [x] Minutely changeset replication diffs
- [x] Notes dumps
- [x] Tile logs

**Comment by Firefishy** [comment]
For the replication diffs we need to be careful to only sync the state file after the content files have been synced.

**Comment by mmd-osm** [comment]
> sync the state file after the content files have been synced.

I'm not entirely clear if item (2) below counts as content file or state file. I would assume we're replicating files in the following sequence:

1. https://planet.openstreetmap.org/replication/minute/005/760/348.osc.gz
2. https://planet.openstreetmap.org/replication/minute/005/760/348.state.txt
3. https://planet.openstreetmap.org/replication/minute/state.txt

**Comment by tomhughes** [comment]
Well we haven't written any code yet, so we're not doing anything yet but yes obviously order is something we need to consider.

**Comment by Firefishy** [comment]
@tomhughes This looks done to me?

**Comment by tomhughes** [comment]
I'd leave it open until we see that the planet publishes OK next week - everything else has now happened at least once and published OK I think.

**Comment by Firefishy** [comment]
All looks good to me. Feel free to re-open if there is anything that needs resolving.
