### ISSUE TITLE
Move supporting.osm.org theme to git repo

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#968]
The theme used to run supporting.osm.org was manually installed.

The theme should copied to a ?private? git repo and installed via the standard chef managed method.

**Comment by Firefishy** [comment]
CC @grischard

**Comment by grischard** [comment]
The theme is [Morden](https://wordpress.com/theme/morden), which is a child theme of [Varia](https://wordpress.com/theme/varia). Both need to be installed.

**Comment by grischard** [comment]
The easiest way is probably by running [the `wp` command line tool](https://developer.wordpress.org/cli/commands/theme/) through chef.

**Comment by Firefishy** [comment]
The copies on the server are not the public copies AFAIK.

**Comment by grischard** [comment]
Superceded by https://github.com/openstreetmap/chef/pull/661
