### ISSUE TITLE
orm has full tile store (default-high)

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#97]
Orm's default-high tile store is full. The cleanup scripts are also bombing out with

`Can't kill a non-numeric process ID at /usr/share/perl5/LockFile/Simple.pm line 584.`

Furthermore, it looks like the cleanup script can't remove enough tiles each day for orm to still have space in the tilestore 24 hours later.

**Comment by zerebubuth** [comment]
Looks like someone fixed this - or it went away by itself?

![image](https://cloud.githubusercontent.com/assets/271360/17699043/6193eadc-63b6-11e6-8aa0-8471f6fafd59.png)

Do we still need to do anything here?

**Comment by tomhughes** [comment]
I've been working on it for the last couple of weeks and just waiting to try and get a few days worth of data to see if it was stable now but it does look like it probably is.

**Comment by zerebubuth** [comment]
Great, thanks!
