### ISSUE TITLE
Add hCaptcha (or similar) to dmca.openstreetmap.org

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#970]
dmca.openstreetmap.org is a form to email website. It has some basic field validation settings. The site is a gateway for a lot of spam being send to the DMCA email.

hCaptcha or similar should be added to the form to reduce the amount of spam sent via the site.

The codebase is here: https://github.com/openstreetmap/dmca-website
It is ancient PHP based form codebase.

**Comment by tomhughes** [comment]
Are you aware of the new cloudflare one? https://www.cloudflare.com/en-gb/products/turnstile/

**Comment by Firefishy** [comment]
Added the most basic of "sum" captchas in https://github.com/openstreetmap/dmca-website/commit/b0f3bbab7a078df3a703cfdb072be8b3ba05a3bd. Might be enough for the moment.
