### ISSUE TITLE
Enable Redirects for planet.osm.org replication diffs

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#971]
Since https://github.com/openstreetmap/operations/issues/678 and https://github.com/openstreetmap/operations/issues/958 we now publish planet replication diffs to a public S3 bucket.

Since https://github.com/openstreetmap/chef/commit/240313208ea75d2b57e0f1e231d244bf4e5bd955 we redirect planet.osm files and some other files to the public S3 bucket.

Currently we do not redirect replication diffs to S3 because some clients may not support following redirects.

We should evaluate, communicate and enable redirects for replication diffs.

**Comment by Firefishy** [comment]
A snapshot of 1.5 days worth of user-agents downloading replication diffs from planet.osm.org:

```
24319912 Osmosis/0.47
19363166 got (https://github.com/sindresorhus/got)
11559914 Osmosis/0.48.3
8143690 Osmosis/0.46
6051269 Wget/1.19.4 (linux-gnu)
4829732 pyosmium/3.1.3
2156557 pyosmium/3.2.0
2006736 Wget/1.21.2
1854418 Nominatim (pyosmium/3.6.0)
1812593 Wget/1.21
1808780 Wget/1.20.3 (linux-gnu)
1732380 Osmosis/0.47.3
1603358 Osmosis/0.47.4
1307412 pyosmium/3.6.0
1174419 github.com/omniscale/go-osm
 817624 Python-urllib/3.8
 816616 Java/1.7.0_171
 811462 pyosmium/3.1.0
 667388 Nominatim (pyosmium/3.5.0)
 596858 pyosmium/3.5.0
 520972 python-requests/2.31.0
 511460 Wget/1.17.1 (linux-gnu)
 484411 Wget/1.14 (linux-gnu)
 422286 Wget/1.20.1 (linux-gnu)
 410410 Apache-HttpClient/4.5.9 (Java/11.0.5)
 409082 Osmosis/0.44.1
 397866 -
 384802 Wget/1.21.3
 370118 got/7.1.0 (https://github.com/sindresorhus/got)
 363811 pyosmium/3.3.0
 349043 Nominatim (pyosmium/3.3.0)
 346154 python-requests/2.28.1
 327435 Osmosis/0.48.3-SNAPSHOT
 321104 pyosmium/3.4.1
 304734 Java/1.7.0_201
 304466 Imposm3 0.4.0dev-20180611-9be1e5a
 238634 Python-urllib/3.7
 206789 Osmosis/-SNAPSHOT
 202671 Imposm3 0.4.0dev-20201208-9be1e5a
 198655 Wget/1.19.5 (linux-gnu)
 188765 pyosmium/3.0.0
 170433 AHC/2.1
 158798 Python-urllib/3.6
 156911 Python-urllib/2.7
 135421 python-urllib3/1.26.11
 128521 Java/17.0.8.1
 125316 Wget
 121156 Python-urllib/3.9
 113756 openaedmap-backend/2.3.230925 (+https://openaedmap.org)
 112714 libwww-perl/6.61
 109568 Wget/1.21.4
 102339 Go-http-client/2.0
 101605 Go-http-client/1.1
 101538 Imposm3 0.3.0dev-20170321-2628d75
 100047 Wget/1.20.3 (freebsd12.0)
  96470 Java/1.7.0_121
  92478 python-requests/2.28.2
  82173 Osmosis/0.45
  73793 ReactorNetty/1.1.9
  71895 Python-urllib/3.10
  71293 Python-urllib/3.5
  69121 Wget/1.18 (linux-gnu)
  68826 node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
  68348 UnwiredBot 1.0
  57402 Java/1.8.0_181
  57383 python-requests/2.11.1
  57154 pyosmium/3.0.1
  50474 python-urllib3/2.0.3
  50474 python-urllib3/1.26.14
  47995 ureq/2.7.1
(trimmed to top 70 entries)
```

**Comment by lonvia** [comment]
python-urllib and python-requests both handle redirects. This means that also all versions of pyosmium are in the clear.

The catch is of course that redirects are only followed on a per-file base. That means that every single download will still hit planet.osm.org first. It is not possible to change the base URL the tools are using with a redirect.

**Comment by Firefishy** [comment]
> python-urllib and python-requests both handle redirects. This means that also all versions of pyosmium are in the clear.
> 
> The catch is of course that redirects are only followed on a per-file base. That means that every single download will still hit planet.osm.org first. It is not possible to change the base URL the tools are using with a redirect.

Thank you for the detail. Yes, still hitting planet.osm.org for the redirect is a known. At a later stage planet.osm.org may become just a thin ephemeral redirect wrapper.

**Comment by Firefishy** [comment]
* osmosis - Replication breaks on redirect - https://github.com/openstreetmap/trac-tickets/issues/5481

**Comment by mmd-osm** [comment]
Would it be feasible to move all of planet.osm.org to AWS, and change the DNS entry to avoid the redirect?
Minutely diffs or planet dumps probably need to local server to prepare the data and publish it on S3. However, this doesn't have to be accessible to the outside world.

**Comment by Firefishy** [comment]
I have currently marked Osmosis as not following redirects, but it seems HTTP -> HTTPS redirects do not work, but HTTPS -> HTTPS (and HTTP to HTTP) redirects are followed by default. 

Sample code snippet:

```java
import java.io.IOException;
import java.net.URL;
import java.net.URLConnection;

public class URLRedirectTester {
    public static void main(String[] args) {
        if (args.length < 1) {
            System.out.println("Please provide a URL as an argument.");
            return;
        }

        String urlString = args[0];
        try {
            URL url = new URL(urlString);
            URLConnection urlConnection = url.openConnection();

            // Force the connection to be established. This will cause any redirects to be followed.
            urlConnection.getInputStream().close();

            // If it's an HTTP connection, it would have followed redirects by default.
            System.out.println("Original URL: " + urlString);
            System.out.println("Final URL: " + urlConnection.getURL());
        } catch (IOException e) {
            System.out.println("Error while connecting: " + e.getMessage());
        }
    }
}
```

Test HTTPS -> HTTPS:
```
Original URL: https://planet.osm.org/pbf/planet-200120.osm.pbf.torrent
Final URL: https://osm-planet-eu-central-1.s3.amazonaws.com/planet/pbf/2020/planet-200120.osm.pbf.torrent
```

Test HTTP -> HTTPS:
```
Original URL: http://planet.osm.org/pbf/planet-200120.osm.pbf.torrent
Final URL: http://planet.osm.org/pbf/planet-200120.osm.pbf.torrent
```

Tested using: openjdk 11.0.20.1

**Comment by Firefishy** [comment]
I am likely going to go-ahead with enabling redirects later this week.

**Comment by mmd-osm** [comment]
I guess any client which can't handle redirects would be visible in the Apache log files : they would be fetching planet.openstreetmap.org/replication/minute/state.txt over and over, and nothing else, since they can't figure out anymore which minutely diff files to download.

**Comment by Firefishy** [comment]
Change is now live.

**Comment by Firefishy** [comment]
Went live via https://github.com/openstreetmap/chef/pull/633

**Comment by SomeoneElseOSM** [comment]
If anyone's using the example "pyosmium_replag.sh" from the Switch2osm documentation (not part of Pyosmium; something I created to report on in for munin) then you'll need to apply this change: https://github.com/SomeoneElseOSM/mod_tile/commit/200b22ce1f5a996bbd34f20f20ea13b6c1f9d815 .
