### ISSUE TITLE
CiviCRM ACL SQL error

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#972]
We upgraded to civicrm 5.66.0 in https://github.com/openstreetmap/chef/commit/8ee7a7b1bedbd7772b663fcd9d5507c8cd8d578b, after which it started throwing SQL exceptions on member renewals.

In an attempt to fix it I manually applied https://github.com/civicrm/civicrm-core/pull/27679

**Comment by Firefishy** [comment]
The manual fix will likely be automatically overridden on the next package upgrade.

**Comment by Firefishy** [comment]
Amanda is still reporting errors. It appears to me some `civicrm` groups were disabled but the membership not updated to the new groups.

**Comment by Firefishy** [comment]
This issue will be automatically fixed by the next release of CiviCRM after 5.66.0.

**Comment by grischard** [comment]
Hotfix applied to 5.66.1
