### ISSUE TITLE
Sync Juniper switch configs

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#977]
### Emergency messages

If an "emergency" level event occurs, Dublin's switch would notify all logged-in users. Amsterdam's would not.

In Amsterdam, enter:

`set system syslog user * any emergency`

### DHCP options

The dhcp service is disabled, so the trace options are moot. If we ever do enable it, better to be verbose.

In Amsterdam, enter:
`set processes dhcp-service traceoptions flag all`

### Old interfaces

Old interfaces clutter the Amsterdam config. This just cleans the config; they won't disappear from interface lists when running commands like `show interfaces terse`.

In Amsterdam, enter:

```
delete interfaces ge-0/2/0
delete interfaces ge-0/2/1
delete interfaces ge-0/2/3
delete interfaces xe-0/2/2
delete interfaces xe-0/2/3
delete interfaces ge-1/2/0
delete interfaces ge-1/2/1
delete interfaces ge-1/2/3
delete interfaces xe-1/2/2
delete interfaces xe-1/2/3
```

### The switch should be in LACP passive mode

As discussed on the chat, the Linux clients and the HE uplink are all in LACP active mode

In Amsterdam, enter:
```
delete interfaces ae1 aggregated-ether-options lacp active
delete interfaces ae2 aggregated-ether-options lacp active
delete interfaces ae3 aggregated-ether-options lacp active
delete interfaces ae4 aggregated-ether-options lacp active
delete interfaces ae5 aggregated-ether-options lacp active
delete interfaces ae6 aggregated-ether-options lacp active
delete interfaces ae7 aggregated-ether-options lacp active
delete interfaces ae8 aggregated-ether-options lacp active
delete interfaces ae9 aggregated-ether-options lacp active
delete interfaces ae10 aggregated-ether-options lacp active
delete interfaces ae11 aggregated-ether-options lacp active
delete interfaces ae12 aggregated-ether-options lacp active
delete interfaces ae13 aggregated-ether-options lacp active
delete interfaces ae14 aggregated-ether-options lacp active
delete interfaces ae15 aggregated-ether-options lacp active
delete interfaces ae16 aggregated-ether-options lacp active
delete interfaces ae17 aggregated-ether-options lacp active
delete interfaces ae18 aggregated-ether-options lacp active
delete interfaces ae19 aggregated-ether-options lacp active
delete interfaces ae20 aggregated-ether-options lacp active
delete interfaces ae21 aggregated-ether-options lacp active
delete interfaces ae22 aggregated-ether-options lacp active
delete interfaces ae23 aggregated-ether-options lacp active
delete interfaces ae60 aggregated-ether-options lacp active
```

In Dublin, enter:

`delete interfaces ae60 aggregated-ether-options lacp active`

### Disable dhcpv6 in Dublin

We configure our ipv6 subnet statically.

In Dublin, enter:

```
delete irb unit 0 family inet6 dhcpv6-client
delete vme unit 0 family inet6 dhcpv6-client
```

### Graceful restart of routing protocols

Since we use static routing, the config line is just clutter.

In Dublin, enter:
`delete routing-options graceful-restart`

### Delete superfluous 802.1x config

802.1x is disabled by default; the configuration does nothing.

In Amsterdam, enter:

`delete protocols dot1x`

### That's it

Finish with a `commit` on both sides.

**Comment by Firefishy** [comment]
I have made the changes across both sites, with exception of the `interface x/2/y` changes as these are because I am specifically trying to disable the unused optics which are due for removal.
