### ISSUE TITLE
Tile server 403 page should tell people to use https://tile.openstreetmap.org

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#978]
LWG recently got an email from someone asking why their code was borken:

```javascript
L.tileLayer( 'http://{s}.openstreetmap.org/{z}/{x}/{y}.png', {
	attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap-Mitwirkende</a>',
	subdomains: ['odin', 'ysera', 'albi', 'bowser', 'pyrene']
}).addTo( map )
```

Obviously, they were getting 403s from the tile server since we only allow requesting tiles over the CDN.

The Apache 403 error message at, e.g., https://odin.openstreetmap.org/1/1/1.png should tell people to use https://tile.openstreetmap.org instead; maybe something like:

> It seems you're trying to grab tiles directly from our tile server. For less error messages (and faster maps), please request them via our CDN at <a href="https://tile.openstreetmap.org">https://tile.openstreetmap.org/{z}{x}/{y}.png</a>. 

See also: #737

We could also update https://github.com/openstreetmap/chef/blob/master/cookbooks/tile/templates/default/index.html.erb and the tile usage policy.

Do we have logs to get an idea of the scale of the issue?

**Comment by tomhughes** [comment]
Do we care much what the scale is? or indeed about helping people that have deliberately attempted to evade controls by choosing to use a URL that has never been published as any sort of official way to access the tiles...

**Comment by grischard** [comment]
Not really - but we care about reducing the incoming traffic to lwg - but on the gripping hand, this is the first report we get.

**Comment by pnorman** [comment]
I don't see a compelling reason to do this. We have no documentation anywhere that suggests their URLs would work, and I've never seen any. If people construct URLs by looking at our internal documentation and mashing stuff together they'll get errors. Interestingly, that code is broken in other ways - two of the servers listed are no longer tile servers.
