### ISSUE TITLE
Fix planet upload / availability race condition

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#979]
There is a small window when the planet files appear on planet.osm.org but are not yet uploaded to S3. Any download during this period result in 404.

We should fix the upload script to avoid the race.

**Comment by grischard** [comment]
Linked PR: https://github.com/openstreetmap/chef/pull/630

**Comment by Firefishy** [comment]
Fixed in https://github.com/openstreetmap/chef/pull/636
