### ISSUE TITLE
longma (tile cache) has full disks

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#98]
Longma's disk usage has increased dramatically since 26th July, and is now full.

![df-week](https://cloud.githubusercontent.com/assets/360803/17298707/fdab6400-5802-11e6-87d8-942020f414ac.png)

It's not obvious what's caused such as sharp increase, but perhaps it's an increase in traffic leading to increased logfile sizes?

**Comment by tomhughes** [comment]
More likely it's other users on the machine - chef is taking a long time to run as well which usually means they have broken the networking to spin up their VMs but I have to arrange access to check and haven't got around to iy yet.

**Comment by gravitystorm** [comment]
This turned out to be a very popular website hitting this particular cache server hard - until it got blocked.
