### ISSUE TITLE
Increase Storage in Prometheus Server (stormfly-03)

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#981]
OpenStreetMap's Prometheus server will start to run low on disk space in the first hard of next year. We should add additional storage compacity before this happens.

Proposal: Add 4x 960GB SAS SSD.
Cost per disk is approximately $115 each on second hand.

**Comment by Firefishy** [comment]
https://www.ebay.com/itm/195238364546

**Comment by Firefishy** [comment]
I have ordered 2x disks instead of 4x. @grischard pushed for 1x as that might be sufficient. I compromised.
If we need additional disks we can order them separately later.

I have opened a ticket with OSUOSL so that they know about the disks which should arrive next week.

**Comment by grischard** [comment]
Can the controller turn raid5 into raid6?

**Comment by Firefishy** [comment]
> Can the controller turn raid5 into raid6?

Yes. RAID5 -> RAID6 and RAID6 -> RAID5 are supported.

**Comment by Firefishy** [comment]
Disks have been installed and RAID array expanded. Pending is conversion to RAID6 for improved redundancy / integrity.

**Comment by Firefishy** [comment]
Converted to RAID6.
