### ISSUE TITLE
Backup prometheus data to S3

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#982]
We need to backup prometheus data - the plan is to make daily [snapshots](https://prometheus.io/docs/prometheus/latest/querying/api/#snapshot) and then sync them to S3 for storage.

Most data in the snapshot will be the same from day to day so only new chunks, and chunks which were still live the day before and have changed, will need to actually be copied.

**Comment by Firefishy** [comment]
Added bucket + user + role + policy in https://github.com/openstreetmap/terraform-aws/commit/c9ab32f0941a3698474e8c9e245c9d06420c8eca#diff-baea6b22ea1e92e456714746008e4bda5475cc31aa86949369ea72230f1f53d9 (private repo)

**Comment by tomhughes** [comment]
This is now implemented and the initial backup is running.
