### ISSUE TITLE
Since #971 the changesets minutely state.yaml is outdated

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/operations#984]
#971 is ("Enable Redirects for planet.osm.org replication diffs"), 

https://planet.osm.org/replication/changesets/state.yaml

which redirects to

https://osm-planet-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com/changesets/replication/minute/state.yaml

contains

    ---
    last_run: 2023-09-24 15:53:31.626863000 +00:00
    sequence: 5680235

If it's relevant, I'm in the UK and the last "correct" one is from "2023-10-23 08:20:01.195511" this morning.  I'm using a Firefox private window to obtain the above, so I don't think it's a "not following redirects" issue.

**Comment by Firefishy** [comment]
Thank you for spotting and reporting it.

**Comment by Firefishy** [comment]
I thought about that, but I just copied the order that the script does it to the filesystem. Yeah, likely both orders should be changed.
