### ISSUE TITLE
Earthing the AMS Switches

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#985]
It is [recommended earth the Juniper EX4300 switches](https://www.juniper.net/documentation/en_US/release-independent/junos/information-products/topic-collections/hardware/ex-series/ex4300/topic-10412.html).

I have sent the earthing lugs, screws, washer and cabling. 1 cable + screw per switch.

There is a rack ground point I believe on the bottom left of the rack (looking from rear). The switches should wired into this using the provided cables.

**Comment by pnorman** [comment]
Do we have any screwdrivers required on site?

**Comment by pnorman** [comment]
Earthed to the top of the cage. The cables should really be about 20cm longer or more, I couldn't route as I wanted.
