### ISSUE TITLE
epic diary spam

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/operations#99]
I know individual spam reports don't belong as github issues, but there are big pornographic images (Japanese cartoons) decorating the website: http://www.openstreetmap.org/diary  They have been on there all day. I think a lot of sysadmins are away on holiday. Hoping this will reach somebody who can tackle this urgently.

**Comment by Firefishy** [comment]
I have hidden the p0rn diary entries. Internet connection is a wet piece of string.

**Comment by harry-wood** [comment]
thanks!
