### ISSUE TITLE
Put multi-bit screwdriver in AMS storage box

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#990]
I left the tiny screwdriver in AM6 but it's kind of useless except for screws in small areas. We need a real screwdriver for basic tasks like installing drives into trays.

Phillips 2, 1, and a couple flatheads are a minimum. The rack has mainly torx if we need to mess with grounding again.

There are some Phillips 3 and pozidrives but we can get by by using the other Phillips.

I recommend a quality Phillips 2 because those supermicro drive screws are really easy to strip, and a good bit is better than dealing with stripped screws.

**Comment by Firefishy** [comment]
I've ordered these 2: https://www.amazon.co.uk/dp/B07V843T2W and https://www.amazon.co.uk/dp/B07V3TF3NG
They are basic, but I've used them ok without stripping screws. Force + correct bit.

**Comment by Firefishy** [comment]
Done. 
![PXL_20240926_091013244](https://github.com/user-attachments/assets/f45b5479-4551-4e23-b171-c8ab22925410)
