### ISSUE TITLE
Minutely diffs occasionally return errors

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/operations#992]
Since the move to AWS, I've now see twice that pyosmium reports that a minutely diff is broken:

```
023-11-16 10:52:29: Using project directory: /srv/nominatim.openstreetmap.org/planet-project
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 12, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 226, in nominatim
    return get_set_parser().run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 121, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 199, in run
    self._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 154, in _update
    state = replication.update(dsn, params, socket_timeout=args.socket_timeout)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/replication.py", line 128, in update
    endseq = repl.apply_diffs(outhandler, startseq + 1,
  File "/usr/lib/python3/dist-packages/osmium/replication/server.py", line 171, in apply_diffs
    diffs = self.collect_diffs(start_id, max_size)
  File "/usr/lib/python3/dist-packages/osmium/replication/server.py", line 137, in collect_diffs
    left_size -= rd.add_buffer(diffdata, self.diff_type)
RuntimeError: gzip error: inflate failed: incorrect header check
```

I presume that means that the file was downloaded partially. Restart the process and the download is fine.

pyosmium assumes that the global `state.txt` file is written only after the actual diffs are published. Is this still guaranteed with the AWS files?

**Comment by Firefishy** [comment]
AWS S3 object copies are atomic operations up to 5GB with read-after-write consistency.

I am currently unsure where the issue might be.

**Comment by tomhughes** [comment]
I seriously doubt you'll get anything useful from support anyway - that all reads very much like "yeah random noise errors happen occassionally, just retry".

**Comment by Firefishy** [comment]
I have opened a support request with AWS.

**Comment by Firefishy** [comment]
"_It's a best practice to build retry logic into applications that make requests to Amazon S3._" - AWS tech support.

**Comment by pnorman** [comment]
Although elevated 500 error rates are an issue, they are right in that retires are a best practice.

Do we have metrics on the 5xx errors?

**Comment by Firefishy** [comment]
> Although elevated 500 error rates are an issue, they are right in that retires are a best practice.
> 
> Do we have metrics on the 5xx errors?

Yes: https://prometheus.openstreetmap.org/d/c6fba6cd-e8f0-4c3e-8a62-7eafbf92cd71/amazon-s3?orgId=1&refresh=5m&var-name=arn:aws:s3:::osm-planet-eu-central-1&viewPanel=2&from=now-30d&to=now
A few a day.

**Comment by lonvia** [comment]
I've published a [new release](https://github.com/osmcode/pyosmium/releases/tag/v3.7.0) of pyosmium that fixes the handling of non-200 responses and adds a transparent retry for 500 and 503. That should fix things for me. Feel free to close.

**Comment by pnorman** [comment]
On a 1h averaging period, the highest 5xx error rate was 0.014%. Typical is 0%, and it goes up to 0.002% fairly often. AWS' SLA for S3 Intelligent Tiering is having 99.0% success rate over the month, calculated as 5 minute intervals. We're at 0.00017%, which is well within SLA. 99.9998 is as good as we can reasonably expect. This means a typical server fetching one state file and one diff every minute will see 1-2 errors per year.

S3 Standard is 99.9%, but I doubt it matters here, since we're at almost 6 nines.

**Comment by lonvia** [comment]
pyosmium 3.7 is now available in Debian testing. Can we port it to our ppa?

**Comment by tomhughes** [comment]
Initial attempt failed as it needs a newer libosmium so I'm backporting that now.

A bigger problem is that it needs `python3-pytest-httpserver` which isn't available in Ubuntu until 22.10 and I don't really want to be trying to backport that...

**Comment by lonvia** [comment]
This is only a test dependency. I don't suppose you would want to disable tests?

**Comment by tomhughes** [comment]
I thought it was part of a larger pytest package but I realised it's actually completely separate so I'm trying a backport from 22.10 to see if that works.

**Comment by tomhughes** [comment]
Backport is now complete.
