### ISSUE TITLE
Identify all subscriptions

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#993]
e.g. domains, monitoring, discourse translations, etc. Xero should have a list of these.

**Comment by Firefishy** [comment]
In what scope? Ops only? Board have many that do not concern us.

Haven't we done this previously?

* Gandi
* Azure (Translations only)
* Report URI
* StatusCake
* AWS (covered by credits)

**Comment by pnorman** [comment]
OWG only, since this is for budgeting.

**Comment by pnorman** [comment]
> Haven't we done this previously?

If there's an existing list with prices that I can use, that would be good.
